import type { MindPreset, VoicePreset } from "./types";

/** Built-in mind plugins. Anything OpenAI-compatible can also use `custom`. */
export const MIND_PRESETS: MindPreset[] = [
  {
    id: "local",
    name: "House lines",
    blurb: "No AI and no internet. Each pet speaks its own words.",
    kind: "local",
    needsKey: false,
  },
  {
    id: "xai",
    name: "xAI Grok",
    blurb: "Grok, from xAI. The house's usual online AI.",
    kind: "openai",
    needsKey: true,
    defaultBaseUrl: "https://api.x.ai/v1",
    defaultModel: "grok-4.5",
    models: ["grok-4.5", "grok-4", "grok-3", "grok-3-mini"],
    envKey: "XAI_API_KEY",
  },
  {
    id: "openai",
    name: "OpenAI",
    blurb: "GPT, from OpenAI.",
    kind: "openai",
    needsKey: true,
    defaultBaseUrl: "https://api.openai.com/v1",
    defaultModel: "gpt-4.1-mini",
    models: ["gpt-4.1-mini", "gpt-4.1", "gpt-4o-mini", "gpt-4o"],
    envKey: "OPENAI_API_KEY",
  },
  {
    id: "anthropic",
    name: "Anthropic",
    blurb: "Claude. Short, careful sentences.",
    kind: "anthropic",
    needsKey: true,
    defaultBaseUrl: "https://api.anthropic.com",
    defaultModel: "claude-sonnet-4-5",
    models: ["claude-sonnet-4-5", "claude-haiku-4-5", "claude-opus-4-5"],
    envKey: "ANTHROPIC_API_KEY",
  },
  {
    id: "google",
    name: "Google Gemini",
    blurb: "Gemini, from Google.",
    kind: "gemini",
    needsKey: true,
    defaultBaseUrl: "https://generativelanguage.googleapis.com/v1beta",
    defaultModel: "gemini-2.5-flash",
    models: ["gemini-2.5-flash", "gemini-2.5-pro", "gemini-2.0-flash"],
    envKey: "GEMINI_API_KEY",
  },
  {
    id: "groq",
    name: "Groq",
    blurb: "Fast answers from open Llama models.",
    kind: "openai",
    needsKey: true,
    defaultBaseUrl: "https://api.groq.com/openai/v1",
    defaultModel: "llama-3.3-70b-versatile",
    models: ["llama-3.3-70b-versatile", "llama-3.1-8b-instant"],
    envKey: "GROQ_API_KEY",
  },
  {
    id: "openrouter",
    name: "OpenRouter",
    blurb: "One key, many AIs.",
    kind: "openai",
    needsKey: true,
    defaultBaseUrl: "https://openrouter.ai/api/v1",
    defaultModel: "x-ai/grok-4.5",
    models: ["x-ai/grok-4.5", "anthropic/claude-sonnet-4.5", "openai/gpt-4.1-mini"],
    envKey: "OPENROUTER_API_KEY",
  },
  {
    id: "together",
    name: "Together",
    blurb: "Many open AIs on one website.",
    kind: "openai",
    needsKey: true,
    defaultBaseUrl: "https://api.together.xyz/v1",
    defaultModel: "meta-llama/Meta-Llama-3.1-70B-Instruct-Turbo",
    envKey: "TOGETHER_API_KEY",
  },
  {
    id: "fireworks",
    name: "Fireworks",
    blurb: "Fast open AIs on one website.",
    kind: "openai",
    needsKey: true,
    defaultBaseUrl: "https://api.fireworks.ai/inference/v1",
    defaultModel: "accounts/fireworks/models/llama-v3p1-70b-instruct",
    envKey: "FIREWORKS_API_KEY",
  },
  {
    id: "deepseek",
    name: "DeepSeek",
    blurb: "DeepSeek's own AI.",
    kind: "openai",
    needsKey: true,
    defaultBaseUrl: "https://api.deepseek.com/v1",
    defaultModel: "deepseek-chat",
    envKey: "DEEPSEEK_API_KEY",
  },
  {
    id: "mistral",
    name: "Mistral",
    blurb: "Mistral's own AI, from France.",
    kind: "openai",
    needsKey: true,
    defaultBaseUrl: "https://api.mistral.ai/v1",
    defaultModel: "mistral-small-latest",
    envKey: "MISTRAL_API_KEY",
  },
  {
    id: "ollama",
    name: "Ollama",
    blurb: "An AI that runs on this computer.",
    kind: "ollama",
    needsKey: false,
    defaultBaseUrl: "http://127.0.0.1:11434",
    defaultModel: "llama3.2",
    models: ["llama3.2", "llama3.1", "mistral", "qwen2.5", "phi4"],
  },
  {
    id: "lmstudio",
    name: "LM Studio",
    blurb: "An AI on this computer, through the LM Studio app.",
    kind: "openai",
    needsKey: false,
    defaultBaseUrl: "http://127.0.0.1:1234/v1",
    defaultModel: "local-model",
  },
  {
    id: "custom",
    name: "Custom webhook",
    blurb: "Your own AI address. For builders has the details.",
    kind: "custom",
    needsKey: false,
    defaultBaseUrl: "http://127.0.0.1:8787/mind",
    defaultModel: "default",
  },
];

export const VOICE_PRESETS: VoicePreset[] = [
  { id: "browser", name: "Browser voice", blurb: "Your browser's own voice. Works offline.", needsKey: false },
  { id: "xai", name: "xAI voice", blurb: "House voices Eve, Ara, Leo.", needsKey: true },
  { id: "openai", name: "OpenAI voice", blurb: "OpenAI's own speaking voice.", needsKey: true },
  { id: "none", name: "Silent", blurb: "Text only.", needsKey: false },
];

export function mindPreset(id: string | undefined) {
  return MIND_PRESETS.find((p) => p.id === id) ?? MIND_PRESETS[0]!;
}
