from pathlib import Path
js = Path("desktop/renderer/window-play.js").read_text(encoding="utf-8")
idx = js.find('side: "grassplate"')
print(js[idx-500:idx+300])
print("====CONST====")
idx = js.find('const JUMP = "jump"')
print(repr(js[idx-60:idx+50]))
print("====DUR====")
idx = js.find("jumpOff:")
print(repr(js[idx-100:idx+40]))
print("====BEGIN====")
idx = js.find("  function beginPlay(target, petX) {")
print("beginPlay count", js.count("  function beginPlay(target, petX) {"))
print("====SILLHOP====")
print("sill-hop count", js.count('    if (next.phase === "sill-hop") {'))
