from pathlib import Path
t = Path(r"web/src/lib/pets/window-play.ts").read_text(encoding="utf-8")
end = t.find("*/")
Path("_brine_ts_hdr.txt").write_text(t[end-500:end+2], encoding="utf-8")
key = 'if (key === "nexus")'
idx = t.find(key)
Path("_brine_ts_pf.txt").write_text(repr(t[idx:idx+160]), encoding="utf-8")
idx = t.find("export const MANY")
Path("_brine_ts_const.txt").write_text(repr(t[idx-40:idx+100]), encoding="utf-8")
idx = t.find("manyOff:")
Path("_brine_ts_dur.txt").write_text(repr(t[idx:idx+90]), encoding="utf-8")
idx = t.find("typeof MANY")
Path("_brine_ts_kind.txt").write_text(repr(t[idx:idx+90]), encoding="utf-8")
idx = t.find('| "many-off"')
Path("_brine_ts_phase.txt").write_text(repr(t[idx-60:idx+90]), encoding="utf-8")
idx = t.find('| "paperweight"')
Path("_brine_ts_side.txt").write_text(repr(t[idx-80:idx+70]), encoding="utf-8")
idx = t.find('| "manyed"')
Path("_brine_ts_leave.txt").write_text(repr(t[idx-80:idx+50]), encoding="utf-8")
# size line with leading spaces
idx = t.find("kind === MANY")
Path("_brine_ts_size.txt").write_text(repr(t[idx-20:idx+130]), encoding="utf-8")
# approach / refit / tick
idx = t.find('goPhase(next, "many-on"')
Path("_brine_ts_approach.txt").write_text(repr(t[idx-150:idx+150]), encoding="utf-8")
idx = t.find("target.kind === MANY")
Path("_brine_ts_refit.txt").write_text(repr(t[idx-60:idx+180]), encoding="utf-8")
idx = t.find('if (next.phase === "many-off")')
idx2 = t.find('if (next.phase === "sill-hop")')
Path("_brine_ts_tick.txt").write_text(t[idx:idx2], encoding="utf-8")
print("wrote", len(t))
