import re
ts=open("web/src/lib/pets/window-play.ts",encoding="utf-8").read()
# find side union snippet around soilhusk
i=ts.find("soilhusk")
print(ts[i-80:i+120])
print("---leave---")
i=ts.find('"emerged"')
print(ts[i-80:i+80])
print("---kind---")
i=ts.find("typeof EMERGE")
print(ts[i-40:i+80])
print("---phase---")
i=ts.find('"emerge-off"')
print(ts[i-60:i+80])
print("---const---")
i=ts.find('export const EMERGE')
print(ts[i:i+80])
print("---DUR---")
i=ts.find("emergeOff")
print(ts[i-60:i+40])
# house title start
h=open("desktop/renderer/leftover-house.test.cjs",encoding="utf-8").read()
m=re.search(r'test\("Chirp|test\("Brood leftover[^\"]{0,200}', h)
print("---house---")
print(m.group(0)[:220] if m else "no")
print("next leftover is Chirp count", h.count("next leftover is Chirp"))
