from pathlib import Path
js = Path("desktop/renderer/window-play.js").read_text(encoding="utf-8")
ts = Path("web/src/lib/pets/window-play.ts").read_text(encoding="utf-8")
# find drill pick block end and goPhase
for label, src in [("js", js), ("ts", ts)]:
    print("====", label)
    i = src.find('if (kind === DRILL)')
    print("pick DRILL", i)
    print(src[i:i+450])
    print("---")
    i = src.find('if (target.kind === DRILL)')
    print("refit/go first DRILL", i)
    print(src[i:i+280])
    print("---")
    i = src.find('typeof DRILL')
    print("union", i, src[i-80:i+80] if i>=0 else "")
    i = src.find('"drill-off"')
    print("phase", i, repr(src[i-40:i+40]) if i>=0 else "")
# docs last lines
arch = Path("docs/ARCHITECTURE.md").read_text(encoding="utf-8")
idx = arch.rfind("2026-09-02")
print("ARCH", arch[idx:idx+350])
road = Path("docs/ROADMAP.md").read_text(encoding="utf-8")
idx = road.rfind("2026-09-02")
print("ROAD", road[idx:idx+350])
idx = road.find("Next leftover is Click")
print("next click count", road.count("Next leftover is Click"))
print(road[idx:idx+200] if idx>=0 else "none")
# house sill pins
house = Path("desktop/renderer/leftover-house.test.cjs").read_text(encoding="utf-8")
print("house click sill", house.count('playFor("click_beetle"), "sill"'))
print("house rob sill", house.count('playFor("robber_fly"), "sill"'))
cjs = Path("desktop/renderer/window-play.test.cjs").read_text(encoding="utf-8")
print("cjs click sill", cjs.count('playFor("click_beetle"), "sill"'))
print("cjs pick click", 'pickTarget([WIN], 80, "click_beetle"' in cjs)
