from pathlib import Path
js = Path("desktop/renderer/window-play.js").read_text(encoding="utf-8")
ts = Path("web/src/lib/pets/window-play.ts").read_text(encoding="utf-8")
cjs = Path("desktop/renderer/window-play.test.cjs").read_text(encoding="utf-8")
mjs = Path("web/scripts/window-play.test.mjs").read_text(encoding="utf-8")
house = Path("desktop/renderer/leftover-house.test.cjs").read_text(encoding="utf-8")
print("js CLOUD", "const CLOUD" in js)
print("js puffball CLOUD", 'key === "puffball") return CLOUD' in js)
print("cjs chicken sill", cjs.count('playFor("chicken_of_woods"), "sill"'))
print("mjs chicken sill", mjs.count('playFor("chicken_of_woods"), "sill"'))
print("house chicken", house.count("chicken_of_woods"))
idx = js.find("seventh leftover of the fungi den")
print("JS HDR", repr(js[idx:idx+170]))
idx = ts.find("seventh leftover of the fungi den")
print("TS HDR", repr(ts[idx:idx+200]))
idx = js.find("const CLOUD")
print("JS CONST", repr(js[idx:idx+55]))
idx = js.find("cloudOff:")
print("JS DUR", repr(js[idx:idx+45]))
idx = js.find('leave: "clouded"')
print("JS PICK", repr(js[idx:idx+120]))
# find WRAP after cloud pick
idx2 = js.find("if (kind === WRAP)", idx)
print("JS after cloud pick WRAP", repr(js[idx:idx2+30]))
idx = js.find("target.kind === CLOUD")
print("JS REFIT", repr(js[idx:idx+160]))
idx = js.find('goPhase(next, "cloud-on"')
print("JS approach", repr(js[idx-80:idx+90]))
idx = js.find("function beginPlay")
print("before beginPlay", repr(js[idx-60:idx+40]))
idx = js.rfind("cloudOffPath,")
print("export fns", repr(js[idx-100:idx+30]))
idx = js.find("CLOUD,\n")
print("export kind", repr(js[idx-20:idx+40]))
idx = house.find("Puff leftover")
print("HOUSE", repr(house[idx:idx+260]))
arch = Path("docs/ARCHITECTURE.md").read_text(encoding="utf-8")
idx = arch.find("Puff clouds")
print("ARCH", repr(arch[idx:idx+320]))
rm = Path("docs/ROADMAP.md").read_text(encoding="utf-8")
idx = rm.find("next leftover is Flame")
print("RM next", idx)
idx = rm.find("**Last Updated:** 2026-09-02 (Phase 6 leftover: Puff")
print("RM foot", repr(rm[idx:idx+320]))
for p in ["README.md", "desktop/README.md"]:
    t = Path(p).read_text(encoding="utf-8")
    idx = t.find("Puff clouds")
    print(p, idx >= 0, repr(t[idx:idx+200]) if idx >= 0 else "")
idx = cjs.find("refit follows the moved spore dish")
print("cjs puff abort end", repr(cjs[idx:idx+220]))
idx = mjs.find('refits Puff')
print("mjs puff", idx)
# TS type sides
idx = ts.find("sporedish")
print("ts side", repr(ts[idx-40:idx+40]))
idx = ts.find("clouded")
print("ts leave", repr(ts[idx-40:idx+40]))
idx = ts.find("| \"cloud-off\"")
print("ts phase", repr(ts[idx-60:idx+40]))
print("cjs tests", cjs.count('test("'), "mjs", mjs.count('test("'), "house", house.count('test("'))
# check drip unused
kinds = open("_kinds_unique.txt", encoding="utf-8").read().split()
for k in ["drip","bracket","layer","stack","cascade","blaze","sulfur","roast","orange"]:
    print(k, "USED" if k in kinds else "free")
