t=open(r"desktop/renderer/window-play.js",encoding="utf-8").read()
i=t.find("Rob seizes")
print("js header rob", i)
print(repr(t[i:i+750]))
print("====")
ts=open(r"web/src/lib/pets/window-play.ts",encoding="utf-8").read()
i=ts.find("Rob seizes")
print("ts header rob", i)
print(repr(ts[i:i+750]))
print("==== ROADMAP last")
rm=open(r"docs/ROADMAP.md",encoding="utf-8").read()
i=rm.find("Last Updated")
print(repr(rm[i:i+400]))
print("==== next leftover Frill count", rm.count("Next leftover is Frill"))
i=rm.find("Next leftover is Frill")
print(repr(rm[i:i+220]) if i>=0 else None)
i=rm.find("Rob (`robber_fly`")
print("rob bullet", i)
print(repr(rm[i:i+180]) if i>=0 else "missing")
j=rm.find("\n\n- [x] Spark", i if i>=0 else 0)
print("spark after", j)
print("==== ARCH")
a=open(r"docs/ARCHITECTURE.md",encoding="utf-8").read()
i=a.find("2026-09")
print(repr(a[i:i+300]))
print("==== README")
for p in ["README.md","desktop/README.md"]:
    txt=open(p,encoding="utf-8").read()
    for needle in ["Rob seizes","Click rights","meadow ten","Frill","grass perch","Phase 6"]:
        if needle in txt:
            k=txt.find(needle)
            print(p, needle, "->", repr(txt[max(0,k-30):k+100]))
