js = open(r"desktop\renderer\window-play.js", encoding="utf-8").read()
print("CASTINGS const", 'const CASTINGS = "castings"' in js)
print("playFor lugworm", 'if (key === "lugworm") return CASTINGS' in js)
print("castingsPoint", "function castingsPoint" in js)
print("export CASTINGS", "    CASTINGS," in js)
print("export castingsPoint", "    castingsPoint," in js)
print("drinkPoint export", "drinkPoint" in js)
print("springPoint export", "springPoint" in js)
print("DUR.drinkOn", "drinkOn:" in js)
print("leech drink", 'if (key === "leech") return DRINK' in js)
print("header tenth", "tenth shore leftover and closes shore ten" in js)
print("kind heap as kind?", 'const HEAP' in js)
print("playFor heap kind?", 'return "heap"' in js)

ts = open(r"web\src\lib\pets\window-play.ts", encoding="utf-8").read()
print("TS CASTINGS", 'export const CASTINGS = "castings"' in ts)
print("TS lugworm", 'if (key === "lugworm") return CASTINGS' in ts)
print("TS header", "tenth shore leftover and closes shore ten" in ts)
print("TS phase", '"castings-on"' in ts)

house = open(r"desktop\renderer\leftover-house.test.cjs", encoding="utf-8").read()
print("house next Heap?", "next leftover is Heap" in house)
print("house next Comb?", "next leftover is Comb" in house)
print("house lugworm castings", 'playFor("lugworm"), "castings"' in house)

cjs = open(r"desktop\renderer\window-play.test.cjs", encoding="utf-8").read()
print("cjs lugworm sill left", 'playFor("lugworm"), "sill"' in cjs)
print("mjs")
mjs = open(r"web\scripts\window-play.test.mjs", encoding="utf-8").read()
print("mjs lugworm sill left", 'playFor("lugworm"), "sill"' in mjs)
print("roadmap next Heap", "next leftover is Heap" in open(r"docs\ROADMAP.md", encoding="utf-8").read().lower())
