from pathlib import Path
t = Path("desktop/renderer/window-play.js").read_text(encoding="utf-8")
i = t.find('if (next.phase === "hollow-off")')
print("js hollow-off idx", i)
print(repr(t[i:i+950]))
print("---PICK---")
j = t.find('leave: "hollowed"')
print("js hollowed idx", j)
print(repr(t[j:j+320]))
ts = Path("web/src/lib/pets/window-play.ts").read_text(encoding="utf-8")
k = ts.find('if (next.phase === "hollow-off")')
print("ts hollow-off idx", k)
print(repr(ts[k:k+900]))
print("---TS PICK---")
m = ts.find('leave: "hollowed"')
print("ts hollowed idx", m)
print(repr(ts[m:m+300]))
