const P = require("./desktop/renderer/window-play.js");
const WORK = { width: 1400, height: 800, floorLift: 0 };
const WIN = { id: "hw", x: 360, y: 80, width: 640, height: 420 };
console.log("monarch", P.playFor("monarch"));
console.log("honeybee", P.playFor("honeybee"));
console.log("luna", P.playFor("luna"));
console.log("sip", P.playFor("hummingbird"));
console.log("wrap", P.playFor("kinkajou"));
console.log("snip", P.playFor("leafcutter"));
console.log("gold", P.playFor("ginkgo"));
console.log("drone", P.playFor("honey_drone"));
console.log("lay", P.playFor("honey_queen"));
console.log("draw", P.playFor("honeycomb"));
console.log("castings", P.playFor("lugworm"));
console.log("WEED", P.WEED, "WAGGLE", P.WAGGLE);
const t = P.pickTarget([WIN], 80, "monarch", WORK, P.SPRITE);
console.log("target", t && t.kind, t && t.side, t && t.leave, t && Math.round(t.holdLift));
const tiny = P.pickTarget([{ id: "tiny", x: 200, y: 80, width: 120, height: 50 }], 80, "monarch", WORK, P.SPRITE);
console.log("tiny", tiny);
const box = P.pickTarget([{ id: "box", x: 200, y: 80, width: 193, height: 169 }], 80, "monarch", WORK, P.SPRITE);
console.log("box", !!box);
const sip = P.sipPoint(WIN, P.SPRITE, WORK);
const weed = P.weedPoint(WIN, P.SPRITE, WORK);
const wrap = P.wrapPoint(WIN, P.SPRITE, WORK);
const waggle = P.wagglePoint(WIN, P.SPRITE, WORK);
const forage = P.foragePoint(WIN, P.SPRITE, WORK);
const snip = P.snipPoint(WIN, P.SPRITE, WORK);
const mouth = P.mouthPoint(WIN, P.SPRITE, WORK);
console.log("weed", weed);
console.log("dx sip", Math.abs(weed.x - sip.x), "dx wrap", Math.abs(weed.x - wrap.x), "dx forage", Math.abs(weed.x - forage.x), "dx snip", Math.abs(weed.x - snip.x), "dx mouth", Math.abs(weed.x - mouth.x));
console.log("dlift sip", Math.abs(weed.lift - sip.lift), "dlift wrap", Math.abs(weed.lift - wrap.lift), "dlift waggle", Math.abs(weed.lift - waggle.lift));
console.log("weedPath", P.weedPath(0.5));
console.log("rots", { weed: P.weedPath(0.5).rot, sip: P.sipPath(0.5).rot, wrap: P.wrapPath(0.5).rot, snip: P.snipPath(0.5).rot, forage: P.foragePath(0.5).rot, waggle: P.wagglePath(0.5).rot, gold: P.goldPath(0.5).rot, mouth: P.mouthPath(0.5).rot });
let play = P.beginPlay(t, t.approachX);
const seen = new Set();
for (let i = 0; i < 2400 && play.phase !== "done"; i++) {
  seen.add(play.phase);
  play = P.stepPlay(play, 0.05, { x: play.x, lift: play.lift }, [WIN], WORK, P.SPRITE, { cmd: "idle" });
}
console.log("phases", [...seen].join(","));
console.log("done", play.phase, "lift", play.lift);
