from pathlib import Path
ts = Path(r"C:\Users\730ri\projects\ComputerPets\web\src\lib\pets\window-play.ts").read_text(encoding="utf-8")
js = Path(r"C:\Users\730ri\projects\ComputerPets\desktop\renderer\window-play.js").read_text(encoding="utf-8")
# confirm js already has WEED
print("js WEED", js.count("const WEED"))
print("js monarch playFor", 'if (key === "monarch") return WEED;' in js)
print("js weedPoint", "function weedPoint" in js)
print("js sill-hop after weed-off", js.count('if (next.phase === "weed-on")'))
i = ts.find("kind === WAGGLE) return")
print("TS size around WAGGLE:")
print(repr(ts[i-20:i+120]))
i = ts.find("typeof CASTINGS | typeof WAGGLE")
print("kind union", repr(ts[i:i+80]) if i>=0 else "missing")
print("header milk", "Milk weeds" in ts)
print("WEED const ts", 'export const WEED = "weed"' in ts)
print("DUR weed", "weedOn:" in ts)
print("playFor monarch ts", 'if (key === "monarch") return WEED;' in ts)
print("pick WEED ts", "kind === WEED" in ts)
print("weedPoint ts", "function weedPoint" in ts)
print("weed-on phase type", '"weed-on"' in ts)
print("milkweedcup", "milkweedcup" in ts)
print("sill-hop ts count", ts.count('if (next.phase === "sill-hop")'))
