from pathlib import Path
js = Path("desktop/renderer/window-play.js").read_text(encoding="utf-8")
# Find Next leftover context in header (first comment block)
end = js.find("*/")
print("HEADER TAIL:", js[max(0,end-800):end+2])
print("====CHORD====")
i = js.find("function chordPoint")
print(js[i:i+700])
print("====FLOAT====")
i = js.find("function floatPoint")
print(js[i:i+500])
print("====THIRST====")
i = js.find("function thirstPoint")
print(js[i:i+500])
print("====MANTLE DUR====")
i = js.find("mantleOn:")
print(js[i:i+120])
print("====SIZE====")
i = js.find("if (kind === MANTLE) return")
print(js[i:i+200])
