const P = require("./desktop/renderer/window-play.js");
const WORK = { width: 1400, height: 800, floorLift: 0 };
const WIN = { id: "hw", x: 360, y: 80, width: 640, height: 420 };
console.log("playFor periwinkle", P.playFor("periwinkle"));
console.log("playFor pond_snail", P.playFor("pond_snail"));
console.log("playFor chiton", P.playFor("chiton"));
console.log("ROCK", P.ROCK);
const t = P.pickTarget([WIN], 80, "periwinkle", WORK, P.SPRITE);
console.log("target", t && { kind: t.kind, side: t.side, leave: t.leave, holdX: t.holdX, holdLift: t.holdLift });
const jamb = P.rockPoint(WIN, P.SPRITE, WORK);
const cling = P.clingPoint(WIN, P.SPRITE, WORK);
const bristle = P.bristlePoint(WIN, P.SPRITE, WORK);
const eight = P.eightPoint(WIN, P.SPRITE, WORK);
const rasp = P.raspPoint(WIN, P.SPRITE, WORK);
const cirri = P.cirriPoint(WIN, P.SPRITE, WORK);
const clamp = P.clampPoint(WIN, P.SPRITE, WORK);
console.log("jamb", jamb);
console.log("cling dx dl", Math.abs(jamb.x - cling.x), Math.abs(jamb.lift - cling.lift));
console.log("bristle dx dl", Math.abs(jamb.x - bristle.x), Math.abs(jamb.lift - bristle.lift));
console.log("eight dx", Math.abs(jamb.x - eight.x));
console.log("rasp dx dl", Math.abs(jamb.x - rasp.x), Math.abs(jamb.lift - rasp.lift));
console.log("cirri dx dl", Math.abs(jamb.x - cirri.x), Math.abs(jamb.lift - cirri.lift));
console.log("clamp dx dl", Math.abs(jamb.x - clamp.x), Math.abs(jamb.lift - clamp.lift));
console.log("rockPath0.5", P.rockPath(0.5));
console.log("eightPath", P.eightPath(0.5));
console.log("raspPath", P.raspPath(0.5));
console.log("bristlePath", P.bristlePath(0.5));
console.log("clingPath", P.clingPath(0.5));
console.log("DUR", P.DUR.rockOn, P.DUR.bristleOn, P.DUR.skinOn, P.DUR.mountOn, P.DUR.riseOn);
const tiny = P.pickTarget([{ id: "tiny", x: 200, y: 80, width: 120, height: 50 }], 80, "periwinkle", WORK, P.SPRITE);
const face = P.pickTarget([{ id: "jamb", x: 200, y: 80, width: 182, height: 216 }], 80, "periwinkle", WORK, P.SPRITE);
console.log("tiny", tiny, "face", !!face);
