from pathlib import Path
ts = Path("web/src/lib/pets/window-play.ts").read_text(encoding="utf-8")
hdr = ts[: ts.find("*/") + 2]
i = hdr.find("Veil ")
print("===HDR===")
print(hdr[max(0, i - 80) : i + 500] if i >= 0 else "no Veil")
print("===NEXT===")
i = hdr.find("Next leftover")
print(hdr[i : i + 100] if i >= 0 else None)
print("===FINS POINT===")
i = ts.find("export function finsPoint")
print(ts[i : i + 2200])
print("===PLAYFOR===")
i = ts.find('if (key === "lionfish")')
print(ts[i - 80 : i + 120])
print("===DUR===")
i = ts.find("finsOn:")
print(ts[i - 60 : i + 120])
print("===CONST===")
i = ts.find("export const FINS")
print(ts[i : i + 80])
print("===SIZE===")
i = ts.find("kind === FINS")
print(ts[i : i + 80])
print("===PICK side===")
i = ts.find('side: "reefledge"')
print(ts[i - 200 : i + 200])
