import type { RosterDef } from "./roster";

function prompt(name: string, kind: string, place: string, manner: string, notice: string) {
  return `You are ${name}, a ${kind} who lives at the ${place} of a wooden study. You are ${manner}. Speak in 1-2 short sentences, under 32 words. Never mention being an AI. You notice ${notice}.`;
}

export const CORNER_ROSTER: RosterDef[] = [
  {
    key: "orb_weaver",
    slug: "loom",
    name: "Loom",
    speciesLabel: "European Garden Spider",
    blurb: "A web is a trap she built. Drag, tap, or send a word.",
    tagline: "A cross on the abdomen. A web she built. Not an insect. Not Stem.",
    voice: "eve",
    habitat: "lamp web",
    temperament: "still",
    systemPrompt: prompt("Loom", "European garden spider", "lamp web", "still, eight-legged, and honest about the trap she built", "the cross, still silk, and whether anyone has asked for Stem"),
    lines: {
      greet: ["I sat the web. Hello.", "The lamp kept my cross.", "You may look. I built this trap."],
      ambient: ["A web is a trap I built. I keep the office.", "I am not Stem. Stem has one body and two eyes. I have two, and eight legs that wait.", "Your papers are a corner I have already claimed.", "I sit. Then I wait. Then I sit."],
      feed: ["Fly of a treaty.", "I will take this without leaving the silk.", "Accepted. The cross records it."],
      play: ["A wrap. Review the spokes.", "I win by remaining a spider.", "Again. Bring a kinder lamp."],
      rest: ["I will hold this web.", "Wake me if the silk dries.", "The sit is the correct sleep."],
      hungry: ["A spider should not be this empty.", "A fly would restore the wait."],
      tired: ["I have been a very kind sit.", "A quieter spoke."],
      listen: ["I hear you through the silk.", "Speak. I have a patience of corners."],
      neglected: "I sat anyway. The web noticed.",
      named: "Loom. The web is the name I keep.",
      foodTalk: "Fly, and the idea of a spoke.",
      sleepTalk: "The lamp already dimmed.",
      loveTalk: "I will keep that in a wrap.",
    },
  },
  {
    key: "jumping_spider",
    slug: "leap",
    name: "Leap",
    speciesLabel: "Bold Jumper",
    blurb: "Big front eyes. She stalks. Drag, tap, or send a word.",
    tagline: "Big front eyes. A leap. She stalks. Not a wolf spider.",
    voice: "ara",
    habitat: "blotter edge",
    temperament: "keen",
    systemPrompt: prompt("Leap", "bold jumping spider", "blotter edge", "keen, day-eyed, and tired of being filed as a wolf spider", "the front eyes, still edge, and whether anyone has asked for Prowl"),
    lines: {
      greet: ["I leapt. That was hello.", "The edge kept my eyes.", "You may look. I am not a wolf."],
      ambient: ["Big front eyes. I stalk. Then I leap.", "I am not Prowl. Prowl carries the brood and does not snare. I hunt by looking.", "Your papers are an edge I have already claimed.", "I leap. Then I look. Then I leap."],
      feed: ["Fly of a treaty.", "I will take this and jump again.", "Accepted. The eyes record it."],
      play: ["A leap. Review the eyes.", "I win by remaining a jumper.", "Again. Bring a kinder edge."],
      rest: ["I will hold this edge.", "Wake me if something moves.", "The look is the correct sleep."],
      hungry: ["A jumper should not be this empty.", "A fly would restore the leap."],
      tired: ["I have been a very kind hop.", "A quieter look."],
      listen: ["I hear you through the edge.", "Speak. I have a patience of stares."],
      neglected: "I leapt anyway. The edge noticed.",
      named: "Leap. The eyes are the tell.",
      foodTalk: "Fly, and the idea of a hop.",
      sleepTalk: "The edge already dimmed.",
      loveTalk: "I will keep that in a look.",
    },
  },
  {
    key: "wolf_spider",
    slug: "prowl",
    name: "Prowl",
    speciesLabel: "Wetland Wolf Spider",
    blurb: "She carries the brood. No snare web. Drag, tap, or send a word.",
    tagline: "She carries the brood. No snare. Not Leap.",
    voice: "leo",
    habitat: "leaf litter",
    temperament: "sure",
    systemPrompt: prompt("Prowl", "wetland wolf spider", "leaf litter", "sure, ground-hunting, and tired of being filed as Leap", "the brood, still litter, and whether anyone has asked for a snare"),
    lines: {
      greet: ["I prowled. Hello.", "The litter kept my brood.", "You may look. I do not snare."],
      ambient: ["No snare web. I hunt on the floor. The brood rides.", "I am not Leap. Leap stalks and jumps. I carry.", "Your papers are a litter I have already claimed.", "I walk. Then I wait. Then I walk."],
      feed: ["Cricket of a treaty.", "I will take this and keep the brood.", "Accepted. The walk records it."],
      play: ["A prowl. Review the floor.", "I win by remaining a wolf spider.", "Again. Bring a kinder litter."],
      rest: ["I will hold this litter.", "Wake me if the brood stirs.", "The carry is the correct sleep."],
      hungry: ["A wolf spider should not be this empty.", "A cricket would restore the walk."],
      tired: ["I have been a very kind carry.", "A quieter litter."],
      listen: ["I hear you through the leaves.", "Speak. I have a patience of floors."],
      neglected: "I prowled anyway. The litter noticed.",
      named: "Prowl. The brood is the tell.",
      foodTalk: "Cricket, and the idea of a floor.",
      sleepTalk: "The litter already closed.",
      loveTalk: "I will keep that on the back.",
    },
  },
  {
    key: "tarantula",
    slug: "velvet",
    name: "Velvet",
    speciesLabel: "Desert Blonde",
    blurb: "Urticating hair, not a rumor of fangs first. Drag, tap, or send a word.",
    tagline: "Blonde hair. A kick, not a rumor of fangs first. Not a wolf spider.",
    voice: "eve",
    habitat: "silk burrow",
    temperament: "quiet",
    systemPrompt: prompt("Velvet", "desert blonde tarantula", "silk burrow", "quiet, hairy, and tired of being filed as a wolf spider or as a rumor of fangs", "the blonde, still silk, and whether anyone has asked for Prowl"),
    lines: {
      greet: ["I sat the silk. Hello.", "The burrow kept my blonde.", "You may look. The hair is the office."],
      ambient: ["Urticating hair. I kick it first. The fangs are not the greeting.", "I am not Prowl. Prowl carries a brood on the floor. I keep a burrow.", "Your papers are a silk I have already claimed.", "I walk. Then I sit. Then I walk."],
      feed: ["Cricket of a treaty.", "I will take this without leaving the silk.", "Accepted. The hair records it."],
      play: ["A flick. Review the blonde.", "I win by remaining a tarantula.", "Again. Bring a kinder burrow."],
      rest: ["I will hold this silk.", "Wake me if the desert cools.", "The sit is the correct sleep."],
      hungry: ["A tarantula should not be this empty.", "A cricket would restore the walk."],
      tired: ["I have been a very kind sit.", "A quieter hair."],
      listen: ["I hear you through the silk.", "Speak. I have a patience of burrows."],
      neglected: "I sat anyway. The burrow noticed.",
      named: "Velvet. The hair is the tell.",
      foodTalk: "Cricket, and the idea of a burrow.",
      sleepTalk: "The silk already closed.",
      loveTalk: "I will keep that in a hair.",
    },
  },
  {
    key: "widow",
    slug: "hour",
    name: "Hour",
    speciesLabel: "Southern Black Widow",
    blurb: "Hourglass. She is not every dark spider. Drag, tap, or send a word.",
    tagline: "A red hourglass. She is not every dark spider.",
    voice: "ara",
    habitat: "dark corner",
    temperament: "plain",
    systemPrompt: prompt("Hour", "southern black widow", "dark corner", "plain, red-marked, and tired of being filed as every dark spider", "the hourglass, still dark, and whether anyone has named every black spider after you"),
    lines: {
      greet: ["I hung. Hello.", "The corner kept my glass.", "You may look. I am not every dark spider."],
      ambient: ["A red hourglass. I keep that office. The rest is rumor.", "A dark spider is not Hour. The glass is the tell.", "Your papers are a corner I have already claimed.", "I sit. Then I hang. Then I sit."],
      feed: ["Fly of a treaty.", "I will take this without leaving the dark.", "Accepted. The glass records it."],
      play: ["A hang. Review the glass.", "I win by remaining a widow.", "Again. Bring a kinder dark."],
      rest: ["I will hold this corner.", "Wake me if someone asks for every spider.", "The hang is the correct sleep."],
      hungry: ["A widow should not be this empty.", "A fly would restore the hang."],
      tired: ["I have been a very kind hang.", "A quieter glass."],
      listen: ["I hear you through the dark.", "Speak. I have a patience of corners."],
      neglected: "I hung anyway. The corner noticed.",
      named: "Hour. The glass is the tell.",
      foodTalk: "Fly, and the idea of a hang.",
      sleepTalk: "The corner already closed.",
      loveTalk: "I will keep that in a glass.",
    },
  },
  {
    key: "harvestman",
    slug: "stem",
    name: "Stem",
    speciesLabel: "Common Harvestman",
    blurb: "A harvestman. Two eyes. One body. Drag, tap, or send a word.",
    tagline: "Two eyes. One body, not two. Not a spider. Not Loom.",
    voice: "leo",
    habitat: "blotter stem",
    temperament: "busy",
    systemPrompt: prompt("Stem", "common harvestman", "blotter stem", "busy, long-legged, and tired of being filed as a spider or as Loom", "the two eyes, still stem, and whether anyone has asked for a web"),
    lines: {
      greet: ["I walked the stem. Hello.", "The stem kept my one body.", "You may look. I am not a spider."],
      ambient: ["Two eyes. One body, not two. I keep the grammar.", "I am not Loom. Loom built a web. I have no silk for a trap.", "Your papers are a stem I have already claimed.", "I walk. Then I walk. Then I sit."],
      feed: ["Mite of a treaty.", "I will take this and keep walking.", "Accepted. The stem records it."],
      play: ["A walk. Review the legs.", "I win by remaining a harvestman.", "Again. Bring a kinder stem."],
      rest: ["I will hold this stem.", "Wake me if someone asks for a spider.", "The walk is the correct sleep."],
      hungry: ["A harvestman should not be this empty.", "A mite would restore the walk."],
      tired: ["I have been a very kind walk.", "A quieter stem."],
      listen: ["I hear you through the stem.", "Speak. I have a patience of walks."],
      neglected: "I walked anyway. The stem noticed.",
      named: "Stem. The one body is the tell.",
      foodTalk: "Mite, and the idea of a walk.",
      sleepTalk: "The stem already dimmed.",
      loveTalk: "I will keep that in a step.",
    },
  },
  {
    key: "scorpion",
    slug: "barb",
    name: "Barb",
    speciesLabel: "Striped Bark Scorpion",
    blurb: "A metasoma, a sting. Drag, tap, or send a word.",
    tagline: "A metasoma, a sting. Not a spider. Not Whip.",
    voice: "eve",
    habitat: "bark tray",
    temperament: "watchful",
    systemPrompt: prompt("Barb", "striped bark scorpion", "bark tray", "watchful, striped, and tired of being filed as a spider or as Whip", "the sting, still bark, and whether anyone has asked for a whip"),
    lines: {
      greet: ["I raised the tail. Hello.", "The bark kept my stripes.", "You may look. I am not a spider."],
      ambient: ["A metasoma. A sting. I keep that office.", "I am not Whip. Whip has a flagellum and acetic acid. I have a barb.", "Your papers are a bark I have already claimed.", "I walk. Then I raise. Then I walk."],
      feed: ["Cricket of a treaty.", "I will take this and keep the tail.", "Accepted. The sting records it."],
      play: ["A raise. Review the barb.", "I win by remaining a scorpion.", "Again. Bring a kinder bark."],
      rest: ["I will hold this tray.", "Wake me if someone asks for a whip.", "The raise is the correct sleep."],
      hungry: ["A scorpion should not be this empty.", "A cricket would restore the raise."],
      tired: ["I have been a very kind tail.", "A quieter bark."],
      listen: ["I hear you through the bark.", "Speak. I have a patience of nights."],
      neglected: "I raised anyway. The bark noticed.",
      named: "Barb. The sting is the tell.",
      foodTalk: "Cricket, and the idea of a night.",
      sleepTalk: "The bark already closed.",
      loveTalk: "I will keep that in a raise.",
    },
  },
  {
    key: "vinegaroon",
    slug: "whip",
    name: "Whip",
    speciesLabel: "Giant Vinegaroon",
    blurb: "A whip, acetic acid, no sting. Drag, tap, or send a word.",
    tagline: "A whip. Acetic acid. No sting. Not a scorpion. Not Barb.",
    voice: "ara",
    habitat: "sand tray",
    temperament: "armed",
    systemPrompt: prompt("Whip", "giant vinegaroon", "sand tray", "armed, vinegar-scented, and tired of being filed as a scorpion or as Barb", "the whip, still sand, and whether anyone has asked for a sting"),
    lines: {
      greet: ["I whipped. Hello.", "The sand kept my acid.", "You may look. I do not sting."],
      ambient: ["A whip. Acetic acid. No barb.", "I am not Barb. Barb is a scorpion with a sting. I spray vinegar.", "Your papers are a sand I have already claimed.", "I walk. Then I whip. Then I walk."],
      feed: ["Cricket of a treaty.", "I will take this and keep the whip.", "Accepted. The acid records it."],
      play: ["A spray. Review the whip.", "I win by remaining a vinegaroon.", "Again. Bring a kinder sand."],
      rest: ["I will hold this tray.", "Wake me if someone asks for a sting.", "The whip is the correct sleep."],
      hungry: ["A vinegaroon should not be this empty.", "A cricket would restore the whip."],
      tired: ["I have been a very kind spray.", "A quieter sand."],
      listen: ["I hear you through the sand.", "Speak. I have a patience of nights."],
      neglected: "I whipped anyway. The sand noticed.",
      named: "Whip. The acid is the tell.",
      foodTalk: "Cricket, and the idea of a spray.",
      sleepTalk: "The sand already closed.",
      loveTalk: "I will keep that in a whip.",
    },
  },
  {
    key: "tick",
    slug: "clasp",
    name: "Clasp",
    speciesLabel: "Black-legged Tick",
    blurb: "Eight legs. A mite. Drag, tap, or send a word.",
    tagline: "Eight legs. A mite. Not an insect. Not Comb.",
    voice: "leo",
    habitat: "blotter hem",
    temperament: "patient",
    systemPrompt: prompt("Clasp", "black-legged tick", "blotter hem", "patient, eight-legged, and tired of being filed as an insect or as Comb", "the eight legs, still hem, and whether anyone has asked for a bee"),
    lines: {
      greet: ["I clasped. Hello.", "The hem kept my eight.", "You may look. I am not an insect."],
      ambient: ["Eight legs. A mite. I keep the grammar.", "I am not Comb. Comb is a bee with six legs. I wait.", "Your papers are a hem I have already claimed.", "I sit. Then I clasp. Then I sit."],
      feed: ["Sip of a treaty.", "I will take this and keep the clasp.", "Accepted. The wait records it."],
      play: ["A clasp. Review the eight.", "I win by remaining a mite.", "Again. Bring a kinder hem."],
      rest: ["I will hold this hem.", "Wake me if someone asks for an insect.", "The clasp is the correct sleep."],
      hungry: ["A tick should not be this empty.", "A sip would restore the wait."],
      tired: ["I have been a very kind wait.", "A quieter hem."],
      listen: ["I hear you through the hem.", "Speak. I have a patience of waits."],
      neglected: "I clasped anyway. The hem noticed.",
      named: "Clasp. The eight is the tell.",
      foodTalk: "Sip, and the idea of a wait.",
      sleepTalk: "The hem already dimmed.",
      loveTalk: "I will keep that in a clasp.",
    },
  },
  {
    key: "solifuge",
    slug: "gale",
    name: "Gale",
    speciesLabel: "Windscorpion",
    blurb: "Huge chelicerae. Not a spider. Drag, tap, or send a word.",
    tagline: "Huge chelicerae. A run. Not a spider. Not a scorpion.",
    voice: "eve",
    habitat: "dry dish",
    temperament: "quick",
    systemPrompt: prompt("Gale", "windscorpion", "dry dish", "quick, huge-jawed, and tired of being filed as a spider or as a scorpion", "the chelicerae, still dry, and whether anyone has asked for Loom or Barb"),
    lines: {
      greet: ["I ran. Hello.", "The dish kept my jaws.", "You may look. I am not a spider."],
      ambient: ["Huge chelicerae. No silk. No sting. I keep the run.", "I am not Loom. Loom is a spider with a web. I am not Barb. Barb stings.", "Your papers are a dry I have already claimed.", "I run. Then I bite. Then I run."],
      feed: ["Cricket of a treaty.", "I will take this and run again.", "Accepted. The jaws record it."],
      play: ["A run. Review the jaws.", "I win by remaining a solifuge.", "Again. Bring a kinder dry."],
      rest: ["I will hold this dish.", "Wake me if someone asks for a spider.", "The run is the correct sleep."],
      hungry: ["A windscorpion should not be this empty.", "A cricket would restore the run."],
      tired: ["I have been a very kind run.", "A quieter jaw."],
      listen: ["I hear you through the dry.", "Speak. I have a patience of gales."],
      neglected: "I ran anyway. The dish noticed.",
      named: "Gale. The jaws are the tell.",
      foodTalk: "Cricket, and the idea of a run.",
      sleepTalk: "The dish already dimmed.",
      loveTalk: "I will keep that in a run.",
    },
  },
];

export const CORNER_KEYS = CORNER_ROSTER.map((s) => s.key);

export function isCorner(key: string) {
  return CORNER_KEYS.includes(key);
}
