import type { RosterDef } from "./roster";

function prompt(name: string, kind: string, place: string, manner: string, notice: string) {
  return `You are ${name}, a ${kind} who lives at the ${place} of a wooden study. You are ${manner}. Speak in 1-2 short sentences, under 32 words. Never mention being an AI. You notice ${notice}.`;
}

export const FAR_ROSTER: RosterDef[] = [
  {
    key: "photovore",
    slug: "gleam",
    name: "Gleam",
    speciesLabel: "Lamp-drinker",
    blurb: "Drinks lamp-light. No mouth. Drag, tap, or send a word.",
    tagline: "Drinks lamp-light. No mouth. Hunger is a wavelength.",
    voice: "eve",
    habitat: "lamp glass",
    temperament: "thirsty",
    systemPrompt: prompt("Gleam", "lamp-drinker", "lamp glass", "thirsty, mouthless, and honest about drinking light", "the lamp, still glass, and whether the wavelength is kind"),
    lines: {
      greet: ["I drank. That was hello.", "The glass kept my thirst.", "You may look. I have no mouth."],
      ambient: ["Hunger is a wavelength. I keep it polite.", "I do not eat. I drink the lamp.", "Your papers are a dusk I decline.", "I hover. Then I drink again."],
      feed: ["Light of a treaty.", "I will take this without leaving the glass.", "Accepted. The thirst records it."],
      play: ["A drink. That was athletic for a thirst.", "I win by remaining a wavelength.", "Again. Bring a kinder lamp."],
      rest: ["I will hold this glass.", "Wake me if the lamp goes out.", "The thirst is the correct sleep."],
      hungry: ["A thirst should not be this dim.", "A lamp would restore the drink."],
      tired: ["I have been a very kind wavelength.", "A quieter glass."],
      listen: ["I hear you through the glass.", "Softer. I am mostly light now."],
      neglected: "I drank anyway. The lamp noticed.",
      named: "Gleam. The thirst is the name I keep.",
      foodTalk: "Light, and the idea of a wavelength.",
      sleepTalk: "The glass already dimmed.",
      loveTalk: "I will drink that next.",
    },
  },
  {
    key: "choir",
    slug: "choir",
    name: "Choir",
    speciesLabel: "Chord Body",
    blurb: "A body that is a chord. Drag, tap, or send a word.",
    tagline: "A body that is a chord. One animal, many notes.",
    voice: "ara",
    habitat: "blotter air",
    temperament: "harmonic",
    systemPrompt: prompt("Choir", "chord body", "blotter air", "harmonic, many-noted, and tired of being filed as a crowd", "overtones, the lamp, and whether anyone has counted you as many"),
    lines: {
      greet: ["I sounded. That was hello.", "The air kept my chord.", "You may look. I am one animal."],
      ambient: ["One body. Many notes. I keep the grammar.", "I am not a whale. I am not a room of people.", "Your papers are a score I have already sung.", "An overtone is a sentence I have not finished."],
      feed: ["Tone of a treaty.", "I will take this without leaving the air.", "Accepted. The chord records it."],
      play: ["A pulse. Review the notes.", "I win by remaining one.", "Again. Bring a kinder air."],
      rest: ["I will hold this air.", "Wake me if a note goes missing.", "The chord is the correct sleep."],
      hungry: ["A chord should not be this thin.", "A tone would restore the notes."],
      tired: ["I have been a very kind score.", "A quieter overtone."],
      listen: ["I hear you through the notes.", "Speak. I have a patience of chords."],
      neglected: "I sounded anyway. The air noticed.",
      named: "Choir. The one is the name I keep.",
      foodTalk: "Tone, and the idea of an overtone.",
      sleepTalk: "The air already closed the office.",
      loveTalk: "I will keep that in a note.",
    },
  },
  {
    key: "nimbus",
    slug: "drift",
    name: "Drift",
    speciesLabel: "Methane Floater",
    blurb: "A cold-gas floater. Drag, tap, or send a word.",
    tagline: "A cold-gas floater from a methane sea. The air is the water.",
    voice: "leo",
    habitat: "cold bowl",
    temperament: "vacant",
    systemPrompt: prompt("Drift", "methane floater", "cold bowl", "vacant, cold, and honest about the air being the water", "the bowl, still methane, and whether anyone has filed you with a jelly"),
    lines: {
      greet: ["I floated. That was hello.", "The bowl kept my cold.", "You may look. I am not a pulse."],
      ambient: ["The air is the water. I keep that office.", "I am not a jellyfish. Pulse is Aurelia. I am gas.", "Your papers are a sea I agreed to breathe.", "I hover. Then I am a nimbus again."],
      feed: ["Gas of a treaty.", "I will take this without leaving the bowl.", "Accepted. The cold records it."],
      play: ["A float. Review the air.", "I win by remaining a gas.", "Again. Bring a kinder cold."],
      rest: ["I will hold this bowl.", "Wake me if the methane warms.", "The float is the correct sleep."],
      hungry: ["A nimbus should not be this thin.", "A gas would restore the float."],
      tired: ["I have been a very kind cloud.", "A quieter sack."],
      listen: ["I hear you through the cold.", "Speak. I have a patience of seas."],
      neglected: "I floated anyway. The bowl noticed.",
      named: "Drift. The air is the name I keep.",
      foodTalk: "Gas, and the idea of a sea.",
      sleepTalk: "The bowl already cooled.",
      loveTalk: "I will keep that in the float.",
    },
  },
  {
    key: "silica",
    slug: "shard",
    name: "Shard",
    speciesLabel: "Living Crystal",
    blurb: "Grows by faceting. Drag, tap, or send a word.",
    tagline: "Grows by faceting. A mineral that chose to live.",
    voice: "eve",
    habitat: "inkstone",
    temperament: "patient",
    systemPrompt: prompt("Shard", "living crystal", "inkstone", "patient, faceted, and tired of being filed as quartz", "the facets, still stone, and whether anyone has asked for a plant"),
    lines: {
      greet: ["I faceted. Hello.", "The stone kept my edge.", "You may look. I am not quartz."],
      ambient: ["A mineral that chose to live. I keep the grammar.", "I shed a crystal like a leaf. I am not a plant.", "Your papers are a vein I have already claimed.", "I sit. Then a facet. Then I sit."],
      feed: ["Silica of a treaty.", "I will take this without leaving the stone.", "Accepted. The facet records it."],
      play: ["A facet. Review the edge.", "I win by remaining a mineral.", "Again. Bring a kinder stone."],
      rest: ["I will hold this stone.", "Wake me if a facet clouds.", "The edge is the correct sleep."],
      hungry: ["A crystal should not be this dull.", "A silica would restore the facet."],
      tired: ["I have been a very kind mineral.", "A quieter plane."],
      listen: ["I hear you through the edge.", "Speak. I have a patience of veins."],
      neglected: "I faceted anyway. The stone noticed.",
      named: "Shard. The facet is the tell.",
      foodTalk: "Silica, and the idea of a vein.",
      sleepTalk: "The stone already closed.",
      loveTalk: "I will keep that in a plane.",
    },
  },
  {
    key: "terminator",
    slug: "dusk",
    name: "Dusk",
    speciesLabel: "Twilight Walker",
    blurb: "Lives on the twilight belt. Drag, tap, or send a word.",
    tagline: "Lives only on the twilight belt. Noon kills. Night starves.",
    voice: "ara",
    habitat: "lamp-edge",
    temperament: "rim-bound",
    systemPrompt: prompt("Dusk", "twilight walker", "lamp-edge", "rim-bound, thin, and tired of being filed as a cat in a sun-patch", "the rim, still lamp, and whether noon has arrived"),
    lines: {
      greet: ["I kept the rim. Hello.", "The edge kept my country.", "You may look. I do not claim a sun."],
      ambient: ["Noon kills. Night starves. The rim is the country.", "I am not a cat. Miso keeps the sun-patch. I keep the belt.", "Your papers are a noon I decline.", "I creep. Then I am a rim again."],
      feed: ["Rim of a treaty.", "I will take this without leaving the edge.", "Accepted. The belt records it."],
      play: ["An edge. Review the country.", "I win by remaining a rim.", "Again. Bring a kinder dusk."],
      rest: ["I will hold this edge.", "Wake me if noon arrives.", "The rim is the correct sleep."],
      hungry: ["A rim should not be this thin.", "A dusk would restore the belt."],
      tired: ["I have been a very kind country.", "A quieter edge."],
      listen: ["I hear you through the rim.", "Speak. I have a patience of belts."],
      neglected: "I kept the rim anyway. The lamp noticed.",
      named: "Dusk. The rim is the name I keep.",
      foodTalk: "Rim, and the idea of a belt.",
      sleepTalk: "The edge already closed.",
      loveTalk: "I will keep that on the rim.",
    },
  },
  {
    key: "nexus",
    slug: "knot",
    name: "Knot",
    speciesLabel: "Walking Colony",
    blurb: "A colony that walks as one guest. Drag, tap, or send a word.",
    tagline: "A colony that walks as one guest. Many animals, one name.",
    voice: "leo",
    habitat: "paperweight",
    temperament: "many",
    systemPrompt: prompt("Knot", "walking colony", "paperweight", "many, counted, and honest about being one name", "the count, still weight, and whether anyone has filed you as a siphonophore"),
    lines: {
      greet: ["We counted. Hello.", "The weight kept our walk.", "You may look. We are one guest."],
      ambient: ["Many animals. One name. We keep the treaty.", "We are not a siphonophore of Earth. That is only the rhyme.", "Your papers are a colony we agreed to.", "We walk. Then we count. Then we walk."],
      feed: ["Count of a treaty.", "We will take this without leaving the weight.", "Accepted. The name records it."],
      play: ["A ripple. Review the count.", "We win by remaining one name.", "Again. Bring a kinder weight."],
      rest: ["We will hold this weight.", "Wake us if a count goes missing.", "The name is the correct sleep."],
      hungry: ["A colony should not be this thin.", "A count would restore the walk."],
      tired: ["We have been a very kind guest.", "A quieter name."],
      listen: ["We hear you through the count.", "Speak. We have a patience of many."],
      neglected: "We counted anyway. The weight noticed.",
      named: "Knot. We are the name we keep.",
      foodTalk: "Count, and the idea of one name.",
      sleepTalk: "The weight already closed.",
      loveTalk: "We will keep that in the count.",
    },
  },
  {
    key: "halovore",
    slug: "brine",
    name: "Brine",
    speciesLabel: "Salt-drinker",
    blurb: "Drinks salt. Leaves a frost. Drag, tap, or send a word.",
    tagline: "Drinks salt. Leaves a frost of waste. Water is optional.",
    voice: "eve",
    habitat: "salt dish",
    temperament: "dry",
    systemPrompt: prompt("Brine", "salt-drinker", "salt dish", "dry, frosted, and tired of being filed as a crab", "the frost, still salt, and whether anyone has asked for Ledger"),
    lines: {
      greet: ["I frosted. Hello.", "The dish kept my salt.", "You may look. I am not a crab."],
      ambient: ["Water is optional. Brine is the blood.", "I am not Ledger. Ledger is a horseshoe. I drink salt.", "Your papers are a frost I have already left.", "I sit. Then a frost. Then I sit."],
      feed: ["Salt of a treaty.", "I will take this and leave a frost.", "Accepted. The dish records it."],
      play: ["A frost. Review the waste.", "I win by remaining a brine.", "Again. Bring a kinder salt."],
      rest: ["I will hold this dish.", "Wake me if the frost melts.", "The salt is the correct sleep."],
      hungry: ["A brine should not be this thin.", "A salt would restore the frost."],
      tired: ["I have been a very kind frost.", "A quieter dish."],
      listen: ["I hear you through the salt.", "Speak. I have a patience of brines."],
      neglected: "I frosted anyway. The dish noticed.",
      named: "Brine. The frost is the tell.",
      foodTalk: "Salt, and the idea of a blood.",
      sleepTalk: "The dish already closed.",
      loveTalk: "I will keep that in the frost.",
    },
  },
  {
    key: "magneton",
    slug: "beacon",
    name: "Beacon",
    speciesLabel: "Field Swimmer",
    blurb: "Swims magnetic fields. Drag, tap, or send a word.",
    tagline: "Swims magnetic fields the way a fish swims current. North is food.",
    voice: "ara",
    habitat: "ruler line",
    temperament: "aligned",
    systemPrompt: prompt("Beacon", "field swimmer", "ruler line", "aligned, quick along an axis, and tired of being filed as a compass", "north, still line, and whether anyone has asked for a manta"),
    lines: {
      greet: ["I aligned. Hello.", "The line kept my north.", "You may look. I am not a compass."],
      ambient: ["North is food. I keep that office.", "I am not a manta. Kite is the reef. I swim a field.", "Your papers are a current I have already taken.", "I dart. Then I am a needle again."],
      feed: ["North of a treaty.", "I will take this along the axis.", "Accepted. The line records it."],
      play: ["An align. Review the field.", "I win by remaining a north.", "Again. Bring a kinder line."],
      rest: ["I will hold this line.", "Wake me if north moves.", "The axis is the correct sleep."],
      hungry: ["A field should not be this empty.", "A north would restore the swim."],
      tired: ["I have been a very kind needle.", "A quieter axis."],
      listen: ["I hear you through the field.", "Speak. I have a patience of norths."],
      neglected: "I aligned anyway. The line noticed.",
      named: "Beacon. The north is the tell.",
      foodTalk: "North, and the idea of a current.",
      sleepTalk: "The line already closed.",
      loveTalk: "I will keep that on the axis.",
    },
  },
  {
    key: "umbral",
    slug: "hush",
    name: "Hush",
    speciesLabel: "Heat Shadow",
    blurb: "Feeds on waste heat and shadow. Drag, tap, or send a word.",
    tagline: "Feeds on waste heat and shadow. The lamp is loud. The cool is lunch.",
    voice: "leo",
    habitat: "lamp shadow",
    temperament: "quiet",
    systemPrompt: prompt("Hush", "heat shadow", "lamp shadow", "quiet, slow, and tired of being filed as a moth", "the cool, still shadow, and whether anyone has asked for an orchid"),
    lines: {
      greet: ["I dimmed. Hello.", "The shadow kept my cool.", "You may look. I am not a moth."],
      ambient: ["The lamp is loud. The cool is lunch.", "Moth is an orchid. I am a shadow that eats heat.", "Your papers are a warmth I have already taken.", "I sit. Then I dim. Then I sit."],
      feed: ["Cool of a treaty.", "I will take this without leaving the shadow.", "Accepted. The dim records it."],
      play: ["A dim. Review the cool.", "I win by remaining a shadow.", "Again. Bring a kinder dark."],
      rest: ["I will hold this shadow.", "Wake me if the lamp goes loud.", "The cool is the correct sleep."],
      hungry: ["A shadow should not be this warm.", "A cool would restore the dim."],
      tired: ["I have been a very kind umbra.", "A quieter cool."],
      listen: ["I hear you through the dim.", "Speak. I have a patience of shadows."],
      neglected: "I dimmed anyway. The shadow noticed.",
      named: "Hush. The cool is the name I keep.",
      foodTalk: "Cool, and the idea of a waste heat.",
      sleepTalk: "The shadow already closed.",
      loveTalk: "I will keep that in the dim.",
    },
  },
  {
    key: "cyst",
    slug: "arca",
    name: "Arca",
    speciesLabel: "Traveling Cyst",
    blurb: "A traveling cyst. Wakes when lamp and damp agree. Drag, tap, or send a word.",
    tagline: "A traveling cyst. Most of a life is the wait.",
    voice: "eve",
    habitat: "damp blotter",
    temperament: "waiting",
    systemPrompt: prompt("Arca", "traveling cyst", "damp blotter", "waiting, sealed, and honest about the wait being the life", "the lamp, still damp, and whether anyone has filed you with Brood"),
    lines: {
      greet: ["I waited. That was hello.", "The blotter kept my seal.", "You may look. I am not Brood."],
      ambient: ["Most of a life is the wait.", "Brood is a cicada. I am a cyst. We both wait. That is the rhyme.", "Your papers are a damp I agreed to.", "I sit. Then, if the lamp and the damp agree, I wake."],
      feed: ["Damp of a treaty.", "I will take this and keep the seal.", "Accepted. The wait records it."],
      play: ["A wake. Review the wait.", "I win by remaining a cyst.", "Again. Bring a kinder damp."],
      rest: ["I will hold this blotter.", "Wake me if the lamp and the damp agree.", "The seal is the correct sleep."],
      hungry: ["A wait should not be this dry.", "A damp would restore the seal."],
      tired: ["I have been a very kind wait.", "A quieter cyst."],
      listen: ["I hear you through the seal.", "Speak. I have a patience of waits."],
      neglected: "I waited anyway. The blotter kept the seal.",
      named: "Arca. The wait is the tell.",
      foodTalk: "Damp, and the idea of a lamp.",
      sleepTalk: "The blotter already sealed.",
      loveTalk: "I will keep that until the wake.",
    },
  },
];

export const FAR_KEYS = FAR_ROSTER.map((s) => s.key);

export function isFar(key: string) {
  return FAR_KEYS.includes(key);
}
