/** Species ground-trick registry. Rui, Relay, Fuse, Ground, Miso, Pip, Thimble, Clip, Whee, Ink, Coin, Echo, Rue, Peck, Quill, Wick, Burr, Floss, Bloom, Keel, Sol, Vesper, Ember, Nori, Saffron, Bandit, Jade, Bluff, Sash, Lula, Coral, Blush, Atlas, Cup, Sepia, Chamber, Pulse, Cling, Tenant, Ledger, Anchor, Kite, Door, Felt, Vein, Fan, Mast, Disk, Moth, Arm, Snap, Drown, Dew, Comb, Milk, Ghost, Spark, Dart, Twig, Column, Seven, Fold, Brood, Thrum, Auger, Mortar, Disc, Pot, Sheen, Bank, Hum, Keep, Wax, Frill, Cap, Lattice, Horn, Ring, Mane, Puff, Flame, Starter, Pact, Gleam, Choir, Drift, Shard, Dusk, Knot, Brine, Beacon, Hush, Arca, Reed, Pebble, Eft, Dapple, Slip, Pinch, Whorl, Hinge, Latch, Prickle, Soot, Wedge, Heart, Hook, Dee, Brick, Drake, Vee, Drum, Sip, Loom, Leap, Prowl, Velvet, Hour, Stem, Barb, Whip, Clasp, Gale, Flag, Cape, Cache, Slick, Wash, Stripe, Grin, Dam, Spine, Coal, Soak, Pad, Wink, Dash, Shift, Spike, Levee, Jaw, Beak, Lid, Peak, Lunge, Speck, Whisk, Penny, Bar, Lance, Night, Spoon, Round, Silver, Haste, Link, Armor, Cast, Jet, Hop, Tun, Thread, Scud, Wave, Pale, Cone, Cement, Mail, Spire, Still, Gum, Ridge, Wreath, Paint, Scrape, Scrub, and Tube today. Overlay + /demo lockstep. */

import * as Rui from "./rui-tricks";
import * as Relay from "./relay-tricks";
import * as Fuse from "./fuse-tricks";
import * as Earth from "./earth-tricks";
import * as Cat from "./cat-tricks";
import * as Dog from "./dog-tricks";
import * as Rabbit from "./rabbit-tricks";
import * as Hamster from "./hamster-tricks";
import * as GuineaPig from "./guinea-pig-tricks";
import * as Turtle from "./turtle-tricks";
import * as Goldfish from "./goldfish-tricks";
import * as Budgie from "./budgie-tricks";
import * as Fox from "./fox-tricks";
import * as Penguin from "./penguin-tricks";
import * as Parrot from "./parrot-tricks";
import * as Ferret from "./ferret-tricks";
import * as Hedgehog from "./hedgehog-tricks";
import * as Chinchilla from "./chinchilla-tricks";
import * as Axolotl from "./axolotl-tricks";
import * as Toucan from "./toucan-tricks";
import * as Iguana from "./iguana-tricks";
import * as Dragon from "./dragon-tricks";
import * as Phoenix from "./phoenix-tricks";
import * as BallPython from "./ball-python-tricks";
import * as CornSnake from "./corn-snake-tricks";
import * as Kingsnake from "./kingsnake-tricks";
import * as GreenTreePython from "./green-tree-python-tricks";
import * as Hognose from "./hognose-tricks";
import * as Garter from "./garter-tricks";
import * as Boa from "./boa-tricks";
import * as MilkSnake from "./milk-snake-tricks";
import * as RosyBoa from "./rosy-boa-tricks";
import * as CarpetPython from "./carpet-python-tricks";
import * as Octopus from "./octopus-tricks";
import * as Cuttlefish from "./cuttlefish-tricks";
import * as Nautilus from "./nautilus-tricks";
import * as MoonJelly from "./moon_jelly-tricks";
import * as SeaStar from "./sea_star-tricks";
import * as HermitCrab from "./hermit_crab-tricks";
import * as HorseshoeCrab from "./horseshoe_crab-tricks";
import * as Seahorse from "./seahorse-tricks";
import * as Manta from "./manta-tricks";
import * as Moray from "./moray-tricks";
import * as Moss from "./moss-tricks";
import * as Maidenhair from "./maidenhair-tricks";
import * as Ginkgo from "./ginkgo-tricks";
import * as Oak from "./oak-tricks";
import * as WaterLily from "./water_lily-tricks";
import * as Orchid from "./orchid-tricks";
import * as Saguaro from "./saguaro-tricks";
import * as VenusFlytrap from "./venus_flytrap-tricks";
import * as Pitcher from "./pitcher-tricks";
import * as Sundew from "./sundew-tricks";
import * as Honeybee from "./honeybee-tricks";
import * as Monarch from "./monarch-tricks";
import * as Luna from "./luna-tricks";
import * as Firefly from "./firefly-tricks";
import * as Darner from "./darner-tricks";
import * as Stick from "./stick-tricks";
import * as CarpenterAnt from "./carpenter_ant-tricks";
import * as Ladybird from "./ladybird-tricks";
import * as Mantis from "./mantis-tricks";
import * as Cicada from "./cicada-tricks";
import * as Bumblebee from "./bumblebee-tricks";
import * as CarpenterBee from "./carpenter_bee-tricks";
import * as MasonBee from "./mason_bee-tricks";
import * as Leafcutter from "./leafcutter-tricks";
import * as Stingless from "./stingless-tricks";
import * as SweatBee from "./sweat_bee-tricks";
import * as MiningBee from "./mining_bee-tricks";
import * as HoneyDrone from "./honey_drone-tricks";
import * as HoneyQueen from "./honey_queen-tricks";
import * as Honeycomb from "./honeycomb-tricks";
import * as Oyster from "./oyster-tricks";
import * as FlyAgaric from "./fly_agaric-tricks";
import * as Morel from "./morel-tricks";
import * as Chanterelle from "./chanterelle-tricks";
import * as TurkeyTail from "./turkey_tail-tricks";
import * as LionsMane from "./lions_mane-tricks";
import * as Puffball from "./puffball-tricks";
import * as ChickenOfWoods from "./chicken_of_woods-tricks";
import * as Yeast from "./yeast-tricks";
import * as Lichen from "./lichen-tricks";
import * as Photovore from "./photovore-tricks";
import * as Choir from "./choir-tricks";
import * as Nimbus from "./nimbus-tricks";
import * as Silica from "./silica-tricks";
import * as Terminator from "./terminator-tricks";
import * as Nexus from "./nexus-tricks";
import * as Halovore from "./halovore-tricks";
import * as Magneton from "./magneton-tricks";
import * as Umbral from "./umbral-tricks";
import * as Cyst from "./cyst-tricks";
import * as Frog from "./frog-tricks";
import * as Toad from "./toad-tricks";
import * as Newt from "./newt-tricks";
import * as Salamander from "./salamander-tricks";
import * as Caecilian from "./caecilian-tricks";
import * as Crayfish from "./crayfish-tricks";
import * as PondSnail from "./pond_snail-tricks";
import * as Mussel from "./mussel-tricks";
import * as Leech from "./leech-tricks";
import * as Stickleback from "./stickleback-tricks";
import * as Crow from "./crow-tricks";
import * as Raven from "./raven-tricks";
import * as BarnOwl from "./barn_owl-tricks";
import * as RedTail from "./red_tail-tricks";
import * as Chickadee from "./chickadee-tricks";
import * as Robin from "./robin-tricks";
import * as Mallard from "./mallard-tricks";
import * as CanadaGoose from "./canada_goose-tricks";
import * as Pileated from "./pileated-tricks";
import * as Hummingbird from "./hummingbird-tricks";
import * as OrbWeaver from "./orb_weaver-tricks";
import * as JumpingSpider from "./jumping_spider-tricks";
import * as WolfSpider from "./wolf_spider-tricks";
import * as Tarantula from "./tarantula-tricks";
import * as Widow from "./widow-tricks";
import * as Harvestman from "./harvestman-tricks";
import * as Scorpion from "./scorpion-tricks";
import * as Vinegaroon from "./vinegaroon-tricks";
import * as Tick from "./tick-tricks";
import * as Solifuge from "./solifuge-tricks";
import * as Deer from "./deer-tricks";
import * as Bat from "./bat-tricks";
import * as Squirrel from "./squirrel-tricks";
import * as Otter from "./otter-tricks";
import * as Raccoon from "./raccoon-tricks";
import * as Skunk from "./skunk-tricks";
import * as Opossum from "./opossum-tricks";
import * as Beaver from "./beaver-tricks";
import * as Porcupine from "./porcupine-tricks";
import * as BlackBear from "./black_bear-tricks";
import * as Capybara from "./capybara-tricks";
import * as Gecko from "./gecko-tricks";
import * as Anole from "./anole-tricks";
import * as Skink from "./skink-tricks";
import * as Chameleon from "./chameleon-tricks";
import * as HornedLizard from "./horned_lizard-tricks";
import * as Alligator from "./alligator-tricks";
import * as Crocodile from "./crocodile-tricks";
import * as Snapper from "./snapper-tricks";
import * as BoxTurtle from "./box_turtle-tricks";
import * as Tuatara from "./tuatara-tricks";
import * as Bass from "./bass-tricks";
import * as BrookTrout from "./brook_trout-tricks";
import * as Catfish from "./catfish-tricks";
import * as Bluegill from "./bluegill-tricks";
import * as Perch from "./perch-tricks";
import * as Pike from "./pike-tricks";
import * as Walleye from "./walleye-tricks";
import * as Paddlefish from "./paddlefish-tricks";
import * as Lamprey from "./lamprey-tricks";
import * as AmericanEel from "./american_eel-tricks";
import * as HouseCentipede from "./house_centipede-tricks";
import * as Millipede from "./millipede-tricks";
import * as Pillbug from "./pillbug-tricks";
import * as Earthworm from "./earthworm-tricks";
import * as VelvetWorm from "./velvet_worm-tricks";
import * as Springtail from "./springtail-tricks";
import * as Tardigrade from "./tardigrade-tricks";
import * as Planarian from "./planarian-tricks";
import * as Nematode from "./nematode-tricks";
import * as Amphipod from "./amphipod-tricks";
import * as FiddlerCrab from "./fiddler_crab-tricks";
import * as GhostCrab from "./ghost_crab-tricks";
import * as Limpet from "./limpet-tricks";
import * as Barnacle from "./barnacle-tricks";
import * as Chiton from "./chiton-tricks";
import * as Periwinkle from "./periwinkle-tricks";
import * as SandDollar from "./sand_dollar-tricks";
import * as SeaUrchin from "./sea_urchin-tricks";
import * as KnobbedWhelk from "./knobbed_whelk-tricks";
import * as Lugworm from "./lugworm-tricks";
import * as FieldCricket from "./field_cricket-tricks";
import * as Katydid from "./katydid-tricks";
import * as Grasshopper from "./grasshopper-tricks";
import * as Swallowtail from "./swallowtail-tricks";
import * as Jewelwing from "./jewelwing-tricks";
import * as Lacewing from "./lacewing-tricks";
import * as Earwig from "./earwig-tricks";
import * as AcornWeevil from "./acorn_weevil-tricks";
import * as ClickBeetle from "./click_beetle-tricks";
import * as RobberFly from "./robber_fly-tricks";
import * as Sloth from "./sloth-tricks";
import * as Lemur from "./lemur-tricks";
import * as Gibbon from "./gibbon-tricks";
import * as Kinkajou from "./kinkajou-tricks";
import * as Colugo from "./colugo-tricks";
import * as FlyingSquirrel from "./flying_squirrel-tricks";
import * as Howler from "./howler-tricks";
import * as Tarsier from "./tarsier-tricks";
import * as Potto from "./potto-tricks";
import * as Koala from "./koala-tricks";
import * as BrainCoral from "./brain_coral-tricks";
import * as Anemone from "./anemone-tricks";
import * as Clownfish from "./clownfish-tricks";
import * as Parrotfish from "./parrotfish-tricks";
import * as CleanerShrimp from "./cleaner_shrimp-tricks";
import * as SeaCucumber from "./sea_cucumber-tricks";
import * as Lionfish from "./lionfish-tricks";
import * as GiantClam from "./giant_clam-tricks";
import * as EagleRay from "./eagle_ray-tricks";
import * as Grouper from "./grouper-tricks";
import * as CyberDragon from "./cyber_dragon-tricks";
import * as VoltDragon from "./volt_dragon-tricks";
import * as TraceDragon from "./trace_dragon-tricks";
import * as FluxDragon from "./flux_dragon-tricks";
import * as SparkDragon from "./spark_dragon-tricks";
import * as IonDragon from "./ion_dragon-tricks";
import * as GaussDragon from "./gauss_dragon-tricks";
import * as Paramecium from "./paramecium-tricks";
import * as Amoeba from "./amoeba-tricks";
import * as Euglena from "./euglena-tricks";
import * as Volvox from "./volvox-tricks";
import * as Diatom from "./diatom-tricks";
import * as Kelp from "./kelp-tricks";
import * as Chlamydomonas from "./chlamydomonas-tricks";
import * as Stentor from "./stentor-tricks";
import * as Coli from "./coli-tricks";
import * as Haloarchaea from "./haloarchaea-tricks";

export type GroundTricks = typeof Rui | typeof Relay | typeof Fuse | typeof Earth | typeof Cat | typeof Dog | typeof Rabbit | typeof Hamster | typeof GuineaPig | typeof Turtle | typeof Goldfish | typeof Budgie | typeof Fox | typeof Penguin | typeof Parrot | typeof Ferret | typeof Hedgehog | typeof Chinchilla | typeof Axolotl | typeof Toucan | typeof Iguana | typeof Dragon | typeof Phoenix | typeof BallPython | typeof CornSnake | typeof Kingsnake | typeof GreenTreePython | typeof Hognose | typeof Garter | typeof Boa | typeof MilkSnake | typeof RosyBoa | typeof CarpetPython | typeof Octopus | typeof Cuttlefish | typeof Nautilus | typeof MoonJelly | typeof SeaStar | typeof HermitCrab | typeof HorseshoeCrab | typeof Seahorse | typeof Manta | typeof Moray | typeof Moss | typeof Maidenhair | typeof Ginkgo | typeof Oak | typeof WaterLily | typeof Orchid | typeof Saguaro | typeof VenusFlytrap | typeof Pitcher | typeof Sundew | typeof Honeybee | typeof Monarch | typeof Luna | typeof Firefly | typeof Darner | typeof Stick | typeof CarpenterAnt | typeof Ladybird | typeof Mantis | typeof Cicada | typeof Bumblebee | typeof CarpenterBee | typeof MasonBee | typeof Leafcutter | typeof Stingless | typeof SweatBee | typeof MiningBee | typeof HoneyDrone | typeof HoneyQueen | typeof Honeycomb | typeof Oyster | typeof FlyAgaric | typeof Morel | typeof Chanterelle | typeof TurkeyTail | typeof LionsMane | typeof Puffball | typeof ChickenOfWoods | typeof Yeast | typeof Lichen | typeof Photovore | typeof Choir | typeof Nimbus | typeof Silica | typeof Terminator | typeof Nexus | typeof Halovore | typeof Magneton | typeof Umbral | typeof Cyst | typeof Frog | typeof Toad | typeof Newt | typeof Salamander | typeof Caecilian | typeof Crayfish | typeof PondSnail | typeof Mussel | typeof Leech | typeof Stickleback | typeof Crow | typeof Raven | typeof BarnOwl | typeof RedTail | typeof Chickadee | typeof Robin | typeof Mallard | typeof CanadaGoose | typeof Pileated | typeof Hummingbird | typeof OrbWeaver | typeof JumpingSpider | typeof WolfSpider | typeof Tarantula | typeof Widow | typeof Harvestman | typeof Scorpion | typeof Vinegaroon | typeof Tick | typeof Solifuge | typeof Deer | typeof Bat | typeof Squirrel | typeof Otter | typeof Raccoon | typeof Skunk | typeof Opossum | typeof Beaver | typeof Porcupine | typeof BlackBear | typeof Capybara | typeof Gecko | typeof Anole | typeof Skink | typeof Chameleon | typeof HornedLizard | typeof Alligator | typeof Crocodile | typeof Snapper | typeof BoxTurtle | typeof Tuatara | typeof Bass | typeof BrookTrout | typeof Catfish | typeof Bluegill | typeof Perch | typeof Pike | typeof Walleye | typeof Paddlefish | typeof Lamprey | typeof AmericanEel | typeof HouseCentipede | typeof Millipede | typeof Pillbug | typeof Earthworm | typeof VelvetWorm | typeof Springtail | typeof Tardigrade | typeof Planarian | typeof Nematode | typeof Amphipod | typeof FiddlerCrab | typeof GhostCrab | typeof Limpet | typeof Barnacle | typeof Chiton | typeof Periwinkle | typeof SandDollar | typeof SeaUrchin | typeof KnobbedWhelk | typeof Lugworm | typeof FieldCricket | typeof Katydid | typeof Grasshopper | typeof Swallowtail | typeof Jewelwing | typeof Lacewing | typeof Earwig | typeof AcornWeevil | typeof ClickBeetle | typeof RobberFly | typeof Sloth | typeof Lemur | typeof Gibbon | typeof Kinkajou | typeof Colugo | typeof FlyingSquirrel | typeof Howler | typeof Tarsier | typeof Potto | typeof Koala | typeof BrainCoral | typeof Anemone | typeof Clownfish | typeof Parrotfish | typeof CleanerShrimp | typeof SeaCucumber | typeof Lionfish | typeof GiantClam | typeof EagleRay | typeof Grouper | typeof CyberDragon | typeof VoltDragon | typeof TraceDragon | typeof FluxDragon | typeof SparkDragon | typeof IonDragon | typeof GaussDragon | typeof Paramecium | typeof Amoeba | typeof Euglena | typeof Volvox | typeof Diatom | typeof Kelp | typeof Chlamydomonas | typeof Stentor | typeof Coli | typeof Haloarchaea;

/** One guest's trick, thank-you, and their kind names, across every guest in `GroundTricks`. */
export type GroundTrick = ReturnType<GroundTricks["beginTrick"]>;
export type GroundTrickKind = GroundTrick["kind"];
export type GroundThankYou = NonNullable<ReturnType<GroundTricks["startThankYou"]>>;
export type GroundHappy = GroundThankYou["happy"];
export type GroundHappyKind = GroundThankYou["kind"];

export function tricksFor(key: string | undefined | null): GroundTricks | null {
  if (!key) return null;
  if (key === Rui.TRICK_KEY || key === "rui") return Rui;
  if (key === Relay.TRICK_KEY || key === "relay") return Relay;
  if (key === Fuse.TRICK_KEY || key === "fuse") return Fuse;
  if (key === Earth.TRICK_KEY || key === "ground") return Earth;
  if (key === Cat.TRICK_KEY || key === "miso") return Cat;
  if (key === Dog.TRICK_KEY || key === "pip") return Dog;
  if (key === Rabbit.TRICK_KEY || key === "thimble") return Rabbit;
  if (key === Hamster.TRICK_KEY || key === "clip") return Hamster;
  if (key === GuineaPig.TRICK_KEY || key === "whee") return GuineaPig;
  if (key === Turtle.TRICK_KEY || key === "ink") return Turtle;
  if (key === Goldfish.TRICK_KEY || key === "coin") return Goldfish;
  if (key === Budgie.TRICK_KEY || key === "echo") return Budgie;
  if (key === Fox.TRICK_KEY || key === "rue") return Fox;
  if (key === Penguin.TRICK_KEY || key === "peck") return Penguin;
  if (key === Parrot.TRICK_KEY || key === "quill") return Parrot;
  if (key === Ferret.TRICK_KEY || key === "wick") return Ferret;
  if (key === Hedgehog.TRICK_KEY || key === "burr") return Hedgehog;
  if (key === Chinchilla.TRICK_KEY || key === "floss") return Chinchilla;
  if (key === Axolotl.TRICK_KEY || key === "bloom") return Axolotl;
  if (key === Toucan.TRICK_KEY || key === "keel") return Toucan;
  if (key === Iguana.TRICK_KEY || key === "sol") return Iguana;
  if (key === Dragon.TRICK_KEY || key === "vesper") return Dragon;
  if (key === Phoenix.TRICK_KEY || key === "ember") return Phoenix;
  if (key === BallPython.TRICK_KEY || key === "nori") return BallPython;
  if (key === CornSnake.TRICK_KEY || key === "saffron") return CornSnake;
  if (key === Kingsnake.TRICK_KEY || key === "bandit") return Kingsnake;
  if (key === GreenTreePython.TRICK_KEY || key === "jade") return GreenTreePython;
  if (key === Hognose.TRICK_KEY || key === "bluff") return Hognose;
  if (key === Garter.TRICK_KEY || key === "sash") return Garter;
  if (key === Boa.TRICK_KEY || key === "lula") return Boa;
  if (key === MilkSnake.TRICK_KEY || key === "coral") return MilkSnake;
  if (key === RosyBoa.TRICK_KEY || key === "blush") return RosyBoa;
  if (key === CarpetPython.TRICK_KEY || key === "atlas") return CarpetPython;
  if (key === Octopus.TRICK_KEY || key === "cup") return Octopus;
  if (key === Cuttlefish.TRICK_KEY || key === "sepia") return Cuttlefish;
  if (key === Nautilus.TRICK_KEY || key === "chamber") return Nautilus;
  if (key === MoonJelly.TRICK_KEY || key === "pulse") return MoonJelly;
  if (key === SeaStar.TRICK_KEY || key === "cling") return SeaStar;
  if (key === HermitCrab.TRICK_KEY || key === "tenant") return HermitCrab;
  if (key === HorseshoeCrab.TRICK_KEY || key === "ledger") return HorseshoeCrab;
  if (key === Seahorse.TRICK_KEY || key === "anchor") return Seahorse;
  if (key === Manta.TRICK_KEY || key === "kite") return Manta;
  if (key === Moray.TRICK_KEY || key === "door") return Moray;
  if (key === Moss.TRICK_KEY || key === "felt") return Moss;
  if (key === Maidenhair.TRICK_KEY || key === "vein") return Maidenhair;
  if (key === Ginkgo.TRICK_KEY || key === "fan") return Ginkgo;
  if (key === Oak.TRICK_KEY || key === "mast") return Oak;
  if (key === WaterLily.TRICK_KEY || key === "disk") return WaterLily;
  if (key === Orchid.TRICK_KEY || key === "moth") return Orchid;
  if (key === Saguaro.TRICK_KEY || key === "arm") return Saguaro;
  if (key === VenusFlytrap.TRICK_KEY || key === "snap") return VenusFlytrap;
  if (key === Pitcher.TRICK_KEY || key === "drown") return Pitcher;
  if (key === Sundew.TRICK_KEY || key === "dew") return Sundew;
  if (key === Honeybee.TRICK_KEY || key === "comb") return Honeybee;
  if (key === Monarch.TRICK_KEY || key === "milk") return Monarch;
  if (key === Luna.TRICK_KEY || key === "ghost") return Luna;
  if (key === Firefly.TRICK_KEY || key === "spark") return Firefly;
  if (key === Darner.TRICK_KEY || key === "dart") return Darner;
  if (key === Stick.TRICK_KEY || key === "twig") return Stick;
  if (key === CarpenterAnt.TRICK_KEY || key === "column") return CarpenterAnt;
  if (key === Ladybird.TRICK_KEY || key === "seven") return Ladybird;
  if (key === Mantis.TRICK_KEY || key === "fold") return Mantis;
  if (key === Cicada.TRICK_KEY || key === "brood") return Cicada;
  if (key === Bumblebee.TRICK_KEY || key === "thrum") return Bumblebee;
  if (key === CarpenterBee.TRICK_KEY || key === "auger") return CarpenterBee;
  if (key === MasonBee.TRICK_KEY || key === "mortar") return MasonBee;
  if (key === Leafcutter.TRICK_KEY || key === "disc") return Leafcutter;
  if (key === Stingless.TRICK_KEY || key === "pot") return Stingless;
  if (key === SweatBee.TRICK_KEY || key === "sheen") return SweatBee;
  if (key === MiningBee.TRICK_KEY || key === "bank") return MiningBee;
  if (key === HoneyDrone.TRICK_KEY || key === "hum") return HoneyDrone;
  if (key === HoneyQueen.TRICK_KEY || key === "keep") return HoneyQueen;
  if (key === Honeycomb.TRICK_KEY || key === "wax") return Honeycomb;
  if (key === Oyster.TRICK_KEY || key === "frill") return Oyster;
  if (key === FlyAgaric.TRICK_KEY || key === "cap") return FlyAgaric;
if (key === Morel.TRICK_KEY || key === "lattice") return Morel;
if (key === Chanterelle.TRICK_KEY || key === "horn") return Chanterelle;
if (key === TurkeyTail.TRICK_KEY || key === "ring") return TurkeyTail;
if (key === LionsMane.TRICK_KEY || key === "mane") return LionsMane;
if (key === Puffball.TRICK_KEY || key === "puff") return Puffball;
if (key === ChickenOfWoods.TRICK_KEY || key === "flame") return ChickenOfWoods;
  if (key === Yeast.TRICK_KEY || key === "starter") return Yeast;
  if (key === Lichen.TRICK_KEY || key === "pact") return Lichen;
  if (key === Photovore.TRICK_KEY || key === "gleam") return Photovore;
  if (key === Choir.TRICK_KEY || key === "choir") return Choir;
  if (key === Nimbus.TRICK_KEY || key === "nimbus" || key === "drift") return Nimbus;
  if (key === Silica.TRICK_KEY || key === "silica" || key === "shard") return Silica;
  if (key === Terminator.TRICK_KEY || key === "terminator" || key === "dusk") return Terminator;
  if (key === Nexus.TRICK_KEY || key === "nexus" || key === "knot") return Nexus;
  if (key === Halovore.TRICK_KEY || key === "halovore" || key === "brine") return Halovore;
  if (key === Magneton.TRICK_KEY || key === "magneton" || key === "beacon") return Magneton;
  if (key === Umbral.TRICK_KEY || key === "umbral" || key === "hush") return Umbral;
  if (key === Cyst.TRICK_KEY || key === "cyst" || key === "arca") return Cyst;
  if (key === Frog.TRICK_KEY || key === "frog" || key === "reed") return Frog;
  if (key === Toad.TRICK_KEY || key === "toad" || key === "pebble") return Toad;
  if (key === Newt.TRICK_KEY || key === "newt" || key === "eft") return Newt;
  if (key === Salamander.TRICK_KEY || key === "salamander" || key === "dapple") return Salamander;
  if (key === Caecilian.TRICK_KEY || key === "caecilian" || key === "slip") return Caecilian;
  if (key === Crayfish.TRICK_KEY || key === "crayfish" || key === "pinch") return Crayfish;
  if (key === PondSnail.TRICK_KEY || key === "pond_snail" || key === "whorl") return PondSnail;
  if (key === Mussel.TRICK_KEY || key === "mussel" || key === "hinge") return Mussel;
  if (key === Leech.TRICK_KEY || key === "leech" || key === "latch") return Leech;
  if (key === Stickleback.TRICK_KEY || key === "stickleback" || key === "prickle") return Stickleback;
  if (key === Crow.TRICK_KEY || key === "crow" || key === "soot") return Crow;
  if (key === Raven.TRICK_KEY || key === "raven" || key === "wedge") return Raven;
  if (key === BarnOwl.TRICK_KEY || key === "barn_owl" || key === "heart") return BarnOwl;
  if (key === RedTail.TRICK_KEY || key === "red_tail" || key === "hook") return RedTail;
  if (key === Chickadee.TRICK_KEY || key === "chickadee" || key === "dee") return Chickadee;
  if (key === Robin.TRICK_KEY || key === "robin" || key === "brick") return Robin;
  if (key === Mallard.TRICK_KEY || key === "mallard" || key === "drake") return Mallard;
  if (key === CanadaGoose.TRICK_KEY || key === "canada_goose" || key === "vee") return CanadaGoose;
  if (key === Pileated.TRICK_KEY || key === "pileated" || key === "drum") return Pileated;
  if (key === Hummingbird.TRICK_KEY || key === "hummingbird" || key === "sip") return Hummingbird;
  if (key === OrbWeaver.TRICK_KEY || key === "orb_weaver" || key === "loom") return OrbWeaver;
  if (key === JumpingSpider.TRICK_KEY || key === "jumping_spider" || key === "leap") return JumpingSpider;
  if (key === WolfSpider.TRICK_KEY || key === "wolf_spider" || key === "prowl") return WolfSpider;
  if (key === Tarantula.TRICK_KEY || key === "tarantula" || key === "velvet") return Tarantula;
  if (key === Widow.TRICK_KEY || key === "widow" || key === "hour") return Widow;
  if (key === Harvestman.TRICK_KEY || key === "harvestman" || key === "stem") return Harvestman;
  if (key === Scorpion.TRICK_KEY || key === "scorpion" || key === "barb") return Scorpion;
  if (key === Vinegaroon.TRICK_KEY || key === "vinegaroon" || key === "whip") return Vinegaroon;
  if (key === Tick.TRICK_KEY || key === "tick" || key === "clasp") return Tick;
  if (key === Solifuge.TRICK_KEY || key === "solifuge" || key === "gale") return Solifuge;
  if (key === Deer.TRICK_KEY || key === "deer" || key === "rack" || key === "flag") return Deer;
  if (key === Bat.TRICK_KEY || key === "bat" || key === "cape") return Bat;
  if (key === Squirrel.TRICK_KEY || key === "squirrel" || key === "cache") return Squirrel;
  if (key === Otter.TRICK_KEY || key === "otter" || key === "slick") return Otter;
  if (key === Raccoon.TRICK_KEY || key === "raccoon" || key === "wash") return Raccoon;
  if (key === Skunk.TRICK_KEY || key === "skunk" || key === "stripe") return Skunk;
  if (key === Opossum.TRICK_KEY || key === "opossum" || key === "grin") return Opossum;
  if (key === Beaver.TRICK_KEY || key === "beaver" || key === "dam") return Beaver;
  if (key === Porcupine.TRICK_KEY || key === "porcupine" || key === "spine") return Porcupine;
  if (key === BlackBear.TRICK_KEY || key === "black_bear" || key === "coal") return BlackBear;
  if (key === Capybara.TRICK_KEY || key === "capybara" || key === "soak") return Capybara;
  if (key === Gecko.TRICK_KEY || key === "gecko" || key === "pad") return Gecko;
  if (key === Anole.TRICK_KEY || key === "anole" || key === "wink") return Anole;
  if (key === Skink.TRICK_KEY || key === "skink" || key === "dash") return Skink;
  if (key === Chameleon.TRICK_KEY || key === "chameleon" || key === "shift") return Chameleon;
  if (key === HornedLizard.TRICK_KEY || key === "horned_lizard" || key === "spike") return HornedLizard;
  if (key === Alligator.TRICK_KEY || key === "alligator" || key === "levee") return Alligator;
  if (key === Crocodile.TRICK_KEY || key === "crocodile" || key === "jaw") return Crocodile;
  if (key === Snapper.TRICK_KEY || key === "snapper" || key === "beak") return Snapper;
  if (key === BoxTurtle.TRICK_KEY || key === "box_turtle" || key === "lid") return BoxTurtle;
  if (key === Tuatara.TRICK_KEY || key === "tuatara" || key === "peak") return Tuatara;
  if (key === Bass.TRICK_KEY || key === "bass" || key === "lunge") return Bass;
  if (key === BrookTrout.TRICK_KEY || key === "brook_trout" || key === "speck") return BrookTrout;
  if (key === Catfish.TRICK_KEY || key === "catfish" || key === "whisk") return Catfish;
  if (key === Bluegill.TRICK_KEY || key === "bluegill" || key === "penny") return Bluegill;
  if (key === Perch.TRICK_KEY || key === "perch" || key === "bar") return Perch;
  if (key === Pike.TRICK_KEY || key === "pike" || key === "lance") return Pike;
  if (key === Walleye.TRICK_KEY || key === "walleye" || key === "night") return Walleye;
  if (key === Paddlefish.TRICK_KEY || key === "paddlefish" || key === "spoon") return Paddlefish;
  if (key === Lamprey.TRICK_KEY || key === "lamprey" || key === "round") return Lamprey;
  if (key === AmericanEel.TRICK_KEY || key === "american_eel" || key === "silver") return AmericanEel;
  if (key === HouseCentipede.TRICK_KEY || key === "house_centipede" || key === "haste") return HouseCentipede;
  if (key === Millipede.TRICK_KEY || key === "millipede" || key === "link") return Millipede;
  if (key === Pillbug.TRICK_KEY || key === "pillbug" || key === "armor") return Pillbug;
  if (key === Earthworm.TRICK_KEY || key === "earthworm" || key === "cast") return Earthworm;
  if (key === VelvetWorm.TRICK_KEY || key === "velvet_worm" || key === "jet") return VelvetWorm;
  if (key === Springtail.TRICK_KEY || key === "springtail" || key === "hop") return Springtail;
  if (key === Tardigrade.TRICK_KEY || key === "tardigrade" || key === "tun") return Tardigrade;
  if (key === Planarian.TRICK_KEY || key === "planarian" || key === "half") return Planarian;
  if (key === Nematode.TRICK_KEY || key === "nematode" || key === "thread") return Nematode;
  if (key === Amphipod.TRICK_KEY || key === "amphipod" || key === "scud") return Amphipod;
  if (key === FiddlerCrab.TRICK_KEY || key === "fiddler_crab" || key === "wave") return FiddlerCrab;
  if (key === GhostCrab.TRICK_KEY || key === "ghost_crab" || key === "pale") return GhostCrab;
  if (key === Limpet.TRICK_KEY || key === "limpet" || key === "cone") return Limpet;
  if (key === Barnacle.TRICK_KEY || key === "barnacle" || key === "cement") return Barnacle;
  if (key === Chiton.TRICK_KEY || key === "chiton" || key === "mail") return Chiton;
  if (key === Periwinkle.TRICK_KEY || key === "periwinkle" || key === "spire") return Periwinkle;
  if (key === SandDollar.TRICK_KEY || key === "sand_dollar" || key === "token") return SandDollar;
  if (key === SeaUrchin.TRICK_KEY || key === "sea_urchin" || key === "thorn") return SeaUrchin;
  if (key === KnobbedWhelk.TRICK_KEY || key === "knobbed_whelk" || key === "knurl") return KnobbedWhelk;
  if (key === Lugworm.TRICK_KEY || key === "lugworm" || key === "heap") return Lugworm;
  if (key === FieldCricket.TRICK_KEY || key === "field_cricket" || key === "chirp") return FieldCricket;
  if (key === Katydid.TRICK_KEY || key === "katydid" || key === "blade") return Katydid;
  if (key === Grasshopper.TRICK_KEY || key === "grasshopper" || key === "vault") return Grasshopper;
  if (key === Swallowtail.TRICK_KEY || key === "swallowtail" || key === "banner") return Swallowtail;
  if (key === Jewelwing.TRICK_KEY || key === "jewelwing" || key === "jewel") return Jewelwing;
  if (key === Lacewing.TRICK_KEY || key === "lacewing" || key === "lace") return Lacewing;
  if (key === Earwig.TRICK_KEY || key === "earwig" || key === "forceps") return Earwig;
  if (key === AcornWeevil.TRICK_KEY || key === "acorn_weevil" || key === "snout") return AcornWeevil;
  if (key === ClickBeetle.TRICK_KEY || key === "click_beetle" || key === "click") return ClickBeetle;
  if (key === RobberFly.TRICK_KEY || key === "robber_fly" || key === "rob") return RobberFly;
  if (key === Sloth.TRICK_KEY || key === "sloth" || key === "hang") return Sloth;
if (key === Lemur.TRICK_KEY || key === "lemur" || key === "sun") return Lemur;
if (key === Gibbon.TRICK_KEY || key === "gibbon" || key === "swing") return Gibbon;
  if (key === Kinkajou.TRICK_KEY || key === "kinkajou" || key === "wrist") return Kinkajou;
  if (key === Colugo.TRICK_KEY || key === "colugo" || key === "sail") return Colugo;
  if (key === FlyingSquirrel.TRICK_KEY || key === "flying_squirrel" || key === "glide") return FlyingSquirrel;
  if (key === Howler.TRICK_KEY || key === "howler" || key === "boom") return Howler;
  if (key === Tarsier.TRICK_KEY || key === "tarsier" || key === "gaze") return Tarsier;
  if (key === Potto.TRICK_KEY || key === "potto" || key === "still") return Potto;
  if (key === Koala.TRICK_KEY || key === "koala" || key === "gum") return Koala;
  if (key === BrainCoral.TRICK_KEY || key === "brain_coral" || key === "ridge") return BrainCoral;
  if (key === Anemone.TRICK_KEY || key === "anemone" || key === "wreath") return Anemone;
  if (key === Clownfish.TRICK_KEY || key === "clownfish" || key === "paint") return Clownfish;
  if (key === Parrotfish.TRICK_KEY || key === "parrotfish" || key === "scrape") return Parrotfish;
  if (key === CleanerShrimp.TRICK_KEY || key === "cleaner_shrimp" || key === "scrub") return CleanerShrimp;
  if (key === SeaCucumber.TRICK_KEY || key === "sea_cucumber" || key === "tube") return SeaCucumber;
  if (key === Lionfish.TRICK_KEY || key === "lionfish" || key === "veil") return Lionfish;
  if (key === GiantClam.TRICK_KEY || key === "giant_clam" || key === "gate") return GiantClam;
  if (key === EagleRay.TRICK_KEY || key === "eagle_ray" || key === "soar") return EagleRay;
  if (key === Grouper.TRICK_KEY || key === "grouper" || key === "hide") return Grouper;
  if (key === CyberDragon.TRICK_KEY || key === "cyber_dragon" || key === "arc") return CyberDragon;
  if (key === VoltDragon.TRICK_KEY || key === "volt_dragon" || key === "volt") return VoltDragon;
  if (key === TraceDragon.TRICK_KEY || key === "trace_dragon" || key === "trace") return TraceDragon;
  if (key === FluxDragon.TRICK_KEY || key === "flux_dragon" || key === "flux") return FluxDragon;
  if (key === SparkDragon.TRICK_KEY || key === "spark_dragon" || key === "crackle") return SparkDragon;
  if (key === IonDragon.TRICK_KEY || key === "ion_dragon" || key === "ion") return IonDragon;
  if (key === GaussDragon.TRICK_KEY || key === "gauss_dragon" || key === "gauss") return GaussDragon;
  if (key === Paramecium.TRICK_KEY || key === "paramecium" || key === "boot") return Paramecium;
  if (key === Amoeba.TRICK_KEY || key === "amoeba" || key === "reach") return Amoeba;
  if (key === Euglena.TRICK_KEY || key === "euglena" || key === "spot") return Euglena;
  if (key === Volvox.TRICK_KEY || key === "volvox" || key === "orb") return Volvox;
  if (key === Diatom.TRICK_KEY || key === "diatom" || key === "pane") return Diatom;
  if (key === Kelp.TRICK_KEY || key === "kelp" || key === "hold") return Kelp;
  if (key === Chlamydomonas.TRICK_KEY || key === "chlamydomonas" || key === "spin") return Chlamydomonas;
  if (key === Stentor.TRICK_KEY || key === "stentor" || key === "bell") return Stentor;
  if (key === Coli.TRICK_KEY || key === "coli" || key === "rod") return Coli;
  if (key === Haloarchaea.TRICK_KEY || key === "haloarchaea" || key === "rose") return Haloarchaea;
  return null;
}

export function wantsThankYou(key: string | undefined | null) {
  const T = tricksFor(key ?? undefined);
  return !!(T && T.wantsThankYou(key ?? undefined));
}

export function startThankYou(
  key: string | undefined | null,
  lastKind: string | null | undefined,
  x: number,
  facing: 1 | -1,
  flags?: Rui.TrickFlags,
) {
  const T = tricksFor(key ?? undefined);
  if (!T) return null;
  return T.startThankYou(key ?? undefined, lastKind as never, x, facing, flags);
}

/** What every guest's trick module offers: its own pick feeds its own begin. */
type TrickPicker = {
  pickTrick(rand?: number, musicOn?: boolean, lastKind?: string | null): string;
  beginTrick(kind: string, x: number, facing: 1 | -1): GroundTrick;
};

/** Pick a trick and begin it with the same guest's module (what the desk did inline before). */
export function beginPickedTrick(T: GroundTricks, musicOn: boolean, lastKind: string | null, x: number, facing: 1 | -1): GroundTrick {
  const mod: TrickPicker = T;
  return mod.beginTrick(mod.pickTrick(undefined, musicOn, lastKind), x, facing);
}

export function sleepHoldFrame(key: string | undefined | null, frameCount?: number) {
  const T = tricksFor(key ?? undefined);
  if (!T || !key) return null;
  return T.sleepHoldFrame(key, frameCount);
}



