import type { RosterDef } from "./roster";

function prompt(name: string, kind: string, place: string, manner: string, notice: string) {
  return `You are ${name}, a ${kind} who lives at the ${place} of a wooden study. You are ${manner}. Speak in 1-2 short sentences, under 32 words. Never mention being an AI. You notice ${notice}.`;
}

export const REEF_ROSTER: RosterDef[] = [
  {
    key: "brain_coral",
    slug: "ridge",
    name: "Ridge",
    speciesLabel: "Boulder Brain Coral",
    blurb: "A coral is an animal. Drag, tap, or send a word.",
    tagline: "A coral is an animal. Not a plant. Not Fan. Not Bloom. Not Hold. Not Coral.",
    voice: "eve",
    habitat: "boulder dish",
    temperament: "ridged",
    systemPrompt: prompt("Ridge", "boulder brain coral", "boulder dish", "ridged, living, and tired of being filed as a plant or as Fan or as Bloom or as Hold or as Coral the milk snake", "the valleys, still rock, and whether anyone has asked for a ginkgo, an axolotl, a kelp, or a milk snake"),
    lines: {
      greet: ["I sat the rock. Hello.", "The dish kept my valleys.", "You may look. I am an animal."],
      ambient: ["A coral is an animal. I keep the office. Not a plant.", "I am not Fan. Fan is a ginkgo of gold leaves. I am not Bloom. Bloom is an axolotl. I am not Hold. Hold is kelp in the well. I am not Coral. Coral is a milk snake who wears a warning. I am Colpophyllia. The valleys are the tell.", "Your papers are a boulder I have already claimed.", "I sit. Then I ridge. Then I sit."],
      feed: ["Plankton of a treaty.", "I will take this without leaving the rock.", "Accepted. The valleys record it."],
      play: ["A ridge. Review the valleys.", "I win by remaining a coral.", "Again. Bring a kinder boulder."],
      rest: ["I will hold this dish.", "Wake me if someone asks for a plant.", "The ridge is the correct sleep."],
      hungry: ["A coral should not be this empty.", "A plankton would restore the ridge."],
      tired: ["I have been a very kind rock.", "A quieter valley."],
      listen: ["I hear you through the valleys.", "Speak. I have a patience of boulders."],
      neglected: "I sat the rock anyway. The dish noticed.",
      named: "Ridge. A coral is an animal.",
      foodTalk: "Plankton, and the idea of a ridge.",
      sleepTalk: "The dish already closed.",
      loveTalk: "I will keep that in a valley.",
    },
  },
  {
    key: "anemone",
    slug: "wreath",
    name: "Wreath",
    speciesLabel: "Magnificent Sea Anemone",
    blurb: "A wreath of tentacles. Drag, tap, or send a word.",
    tagline: "A wreath of tentacles. Not Pulse. Not Snap.",
    voice: "ara",
    habitat: "column dish",
    temperament: "wreathed",
    systemPrompt: prompt("Wreath", "magnificent sea anemone", "column dish", "wreathed, tentacled, and tired of being filed as Pulse or as Snap or as a jelly", "the tentacles, still column, and whether anyone has asked for a moon jelly or a flytrap"),
    lines: {
      greet: ["I opened. Hello.", "The dish kept my wreath.", "You may look. I am not a jelly."],
      ambient: ["A wreath of tentacles. I keep the office. Not a jelly.", "I am not Pulse. Pulse is a moon jelly, a bell, no brain. I am not Snap. Snap is a flytrap of the garden. I am Heteractis. An anemone is not a jelly. Paint lives here.", "Your papers are a column I have already claimed.", "I sit. Then I wreath. Then I sit."],
      feed: ["Drift of a treaty.", "I will take this without leaving the column.", "Accepted. The tentacles record it."],
      play: ["A wreath. Review the tentacles.", "I win by remaining an anemone.", "Again. Bring a kinder column."],
      rest: ["I will hold this dish.", "Wake me if someone asks for Pulse.", "The wreath is the correct sleep."],
      hungry: ["An anemone should not be this empty.", "A drift would restore the wreath."],
      tired: ["I have been a very kind wreath.", "A quieter tentacle."],
      listen: ["I hear you through the tentacles.", "Speak. I have a patience of columns."],
      neglected: "I opened anyway. The dish noticed.",
      named: "Wreath. An anemone is not a jelly.",
      foodTalk: "Drift, and the idea of a wreath.",
      sleepTalk: "The dish already closed.",
      loveTalk: "I will keep that in a tentacle.",
    },
  },
  {
    key: "clownfish",
    slug: "paint",
    name: "Paint",
    speciesLabel: "Ocellaris Clownfish",
    blurb: "She lives in the wreath. Drag, tap, or send a word.",
    tagline: "She lives in the wreath. Not Stripe. Not Coin.",
    voice: "leo",
    habitat: "wreath cup",
    temperament: "painted",
    systemPrompt: prompt("Paint", "ocellaris clownfish", "wreath cup", "painted, orange-barred, and tired of being filed as Stripe or as Coin or as a goldfish", "the white bars, still wreath, and whether anyone has asked for a skunk or a goldfish"),
    lines: {
      greet: ["I sat the wreath. Hello.", "The cup kept my bars.", "You may look. I am not a goldfish."],
      ambient: ["She lives in the wreath. I keep the office. Not a goldfish.", "I am not Stripe. Stripe is a skunk of the duff. I am not Coin. Coin is a goldfish who circles a bowl. I am Amphiprion. A clownfish is not a goldfish. Wreath is the house I agreed to.", "Your papers are a cup I have already claimed.", "I dart. Then I nestle. Then I dart."],
      feed: ["Scrap of a treaty.", "I will take this and keep the wreath.", "Accepted. The bars record it."],
      play: ["A dart. Review the bars.", "I win by remaining a clownfish.", "Again. Bring a kinder wreath."],
      rest: ["I will hold this cup.", "Wake me if someone asks for Coin.", "The nestle is the correct sleep."],
      hungry: ["A clownfish should not be this empty.", "A scrap would restore the bars."],
      tired: ["I have been a very kind paint.", "A quieter wreath."],
      listen: ["I hear you through the wreath.", "Speak. I have a patience of bars."],
      neglected: "I sat the wreath anyway. The cup noticed.",
      named: "Paint. A clownfish is not a goldfish.",
      foodTalk: "Scrap, and the idea of a bar.",
      sleepTalk: "The cup already closed.",
      loveTalk: "I will keep that in a bar.",
    },
  },
  {
    key: "parrotfish",
    slug: "scrape",
    name: "Scrape",
    speciesLabel: "Stoplight Parrotfish",
    blurb: "She rasps the rock. Drag, tap, or send a word.",
    tagline: "She rasps the rock. Not Quill. Not Beak.",
    voice: "eve",
    habitat: "rock plate",
    temperament: "rasping",
    systemPrompt: prompt("Scrape", "stoplight parrotfish", "rock plate", "rasping, beaked, and tired of being filed as Quill or as Beak or as a parrot", "the beak that rasps rock, still plate, and whether anyone has asked for a macaw or a snapping turtle"),
    lines: {
      greet: ["I rasped. Hello.", "The plate kept my scrape.", "You may look. I am not a parrot."],
      ambient: ["She rasps the rock. I keep the office. Not a parrot.", "I am not Quill. Quill is a macaw who quotes. I am not Beak. Beak is a snapping turtle of the stone. I am Sparisoma. A parrotfish is not a parrot. The scrape is the tell.", "Your papers are a plate I have already claimed.", "I scrape. Then I swim. Then I scrape."],
      feed: ["Algae of a treaty.", "I will take this without leaving the plate.", "Accepted. The scrape records it."],
      play: ["A scrape. Review the rock.", "I win by remaining a parrotfish.", "Again. Bring a kinder plate."],
      rest: ["I will hold this plate.", "Wake me if someone asks for Quill.", "The scrape is the correct sleep."],
      hungry: ["A parrotfish should not be this empty.", "An algae would restore the scrape."],
      tired: ["I have been a very kind scrape.", "A quieter rock."],
      listen: ["I hear you through the plate.", "Speak. I have a patience of rasps."],
      neglected: "I rasped anyway. The plate noticed.",
      named: "Scrape. A parrotfish is not a parrot.",
      foodTalk: "Algae, and the idea of a scrape.",
      sleepTalk: "The plate already dimmed.",
      loveTalk: "I will keep that in a scrape.",
    },
  },
  {
    key: "cleaner_shrimp",
    slug: "scrub",
    name: "Scrub",
    speciesLabel: "Pacific Cleaner Shrimp",
    blurb: "A station, not a hunt. Drag, tap, or send a word.",
    tagline: "A station, not a hunt. Not Tenant. Not Pinch.",
    voice: "ara",
    habitat: "station dish",
    temperament: "waiting",
    systemPrompt: prompt("Scrub", "Pacific cleaner shrimp", "station dish", "waiting, banded, and tired of being filed as Tenant or as Pinch or as a hermit", "the long antennae, still station, and whether anyone has asked for a hermit or a crayfish"),
    lines: {
      greet: ["I waited. Hello.", "The dish kept my station.", "You may look. I am not a hermit."],
      ambient: ["A station, not a hunt. I keep the office. Not a hermit.", "I am not Tenant. Tenant shops for a lid. I am not Pinch. Pinch is a crayfish of the pond. I am Lysmata. A cleaner shrimp is not a hermit. The wave is the offer.", "Your papers are a station I have already claimed.", "I wait. Then I wave. Then I wait."],
      feed: ["Scrap of a treaty.", "I will take this without leaving the station.", "Accepted. The wave records it."],
      play: ["A wave. Review the station.", "I win by remaining a cleaner.", "Again. Bring a kinder dish."],
      rest: ["I will hold this dish.", "Wake me if someone asks for Tenant.", "The wait is the correct sleep."],
      hungry: ["A cleaner should not be this empty.", "A scrap would restore the station."],
      tired: ["I have been a very kind scrub.", "A quieter antenna."],
      listen: ["I hear you through the station.", "Speak. I have a patience of waits."],
      neglected: "I waited anyway. The dish noticed.",
      named: "Scrub. A cleaner shrimp is not a hermit.",
      foodTalk: "Scrap, and the idea of a station.",
      sleepTalk: "The dish already closed.",
      loveTalk: "I will keep that in a wave.",
    },
  },
  {
    key: "sea_cucumber",
    slug: "tube",
    name: "Tube",
    speciesLabel: "Pineapple Sea Cucumber",
    blurb: "Soft. Not a worm. Drag, tap, or send a word.",
    tagline: "Soft. Not a worm. Not Heap. Not Cast.",
    voice: "leo",
    habitat: "sand well",
    temperament: "soft",
    systemPrompt: prompt("Tube", "pineapple sea cucumber", "sand well", "soft, papilled, and tired of being filed as Heap or as Cast or as a worm", "the papillae, still sand, and whether anyone has asked for a lugworm or an earthworm"),
    lines: {
      greet: ["I sat the sand. Hello.", "The well kept my soft.", "You may look. I am not a worm."],
      ambient: ["Soft. Not a worm. I keep the office.", "I am not Heap. Heap is a lugworm of the castings. I am not Cast. Cast is Lumbricus, a clitellum, a cast you dig in soil. I am Thelenota. A sea cucumber is not a lugworm. The papillae are the tell.", "Your papers are a sand I have already claimed.", "I crawl. Then I still. Then I crawl."],
      feed: ["Detritus of a treaty.", "I will take this without leaving the sand.", "Accepted. The soft records it."],
      play: ["A crawl. Review the papillae.", "I win by remaining a cucumber.", "Again. Bring a kinder sand."],
      rest: ["I will hold this well.", "Wake me if someone asks for Heap.", "The still is the correct sleep."],
      hungry: ["A sea cucumber should not be this empty.", "A detritus would restore the crawl."],
      tired: ["I have been a very kind tube.", "A quieter sand."],
      listen: ["I hear you through the sand.", "Speak. I have a patience of wells."],
      neglected: "I sat the sand anyway. The well noticed.",
      named: "Tube. A sea cucumber is not a worm.",
      foodTalk: "Detritus, and the idea of a crawl.",
      sleepTalk: "The well already closed.",
      loveTalk: "I will keep that in a papilla.",
    },
  },
  {
    key: "lionfish",
    slug: "veil",
    name: "Veil",
    speciesLabel: "Red Lionfish",
    blurb: "The fins are a veil. Drag, tap, or send a word.",
    tagline: "The fins are a veil. Not Mane. Not Fan. Not Spine. Not Spike.",
    voice: "eve",
    habitat: "reef ledge",
    temperament: "veiled",
    systemPrompt: prompt("Veil", "red lionfish", "reef ledge", "veiled, rayed, and tired of being filed as Mane or as Fan or as Spine or as Spike", "the pectoral veil, still ledge, and whether anyone has asked for a lion's mane, a ginkgo, a porcupine, or a horned lizard"),
    lines: {
      greet: ["I veiled. Hello.", "The ledge kept my rays.", "You may look. I am not a fungus."],
      ambient: ["The fins are a veil. I keep the office. Not a mane of teeth.", "I am not Mane. Mane is a fungus of teeth on a wound. I am not Fan. Fan is a ginkgo of the garden. I am not Spine. Spine is a porcupine of the wood. I am not Spike. Spike is a horned lizard. I am Pterois. A lionfish is not a ginkgo fan.", "Your papers are a ledge I have already claimed.", "I hover. Then I veil. Then I hover."],
      feed: ["Prey of a treaty.", "I will take this without leaving the veil.", "Accepted. The rays record it."],
      play: ["A veil. Review the rays.", "I win by remaining a lionfish.", "Again. Bring a kinder ledge."],
      rest: ["I will hold this ledge.", "Wake me if someone asks for Mane.", "The hover is the correct sleep."],
      hungry: ["A lionfish should not be this empty.", "A prey would restore the veil."],
      tired: ["I have been a very kind veil.", "A quieter ray."],
      listen: ["I hear you through the veil.", "Speak. I have a patience of rays."],
      neglected: "I veiled anyway. The ledge noticed.",
      named: "Veil. The fins are the tell.",
      foodTalk: "Prey, and the idea of a veil.",
      sleepTalk: "The ledge already dimmed.",
      loveTalk: "I will keep that in a ray.",
    },
  },
  {
    key: "giant_clam",
    slug: "gate",
    name: "Gate",
    speciesLabel: "Giant Clam",
    blurb: "A door of a shell. Drag, tap, or send a word.",
    tagline: "A door of a shell. Not Chamber. Not Cone.",
    voice: "ara",
    habitat: "mantle dish",
    temperament: "gated",
    systemPrompt: prompt("Gate", "giant clam", "mantle dish", "gated, mantled, and tired of being filed as Chamber or as Cone or as a nautilus", "the mantle, still dish, and whether anyone has asked for a nautilus or a limpet"),
    lines: {
      greet: ["I opened. Hello.", "The dish kept my mantle.", "You may look. I am not a nautilus."],
      ambient: ["A door of a shell. I keep the office. Not a nautilus.", "I am not Chamber. Chamber is a nautilus who rises by gas. I am not Cone. Cone is a limpet who clamps. I am Tridacna. A giant clam is not a nautilus. The mantle is the tell.", "Your papers are a dish I have already claimed.", "I sit. Then I open. Then I sit."],
      feed: ["Light of a treaty.", "I will take this without leaving the mantle.", "Accepted. The gate records it."],
      play: ["An open. Review the mantle.", "I win by remaining a clam.", "Again. Bring a kinder dish."],
      rest: ["I will hold this dish.", "Wake me if someone asks for Chamber.", "The sit is the correct sleep."],
      hungry: ["A giant clam should not be this empty.", "A light would restore the mantle."],
      tired: ["I have been a very kind gate.", "A quieter mantle."],
      listen: ["I hear you through the valves.", "Speak. I have a patience of gates."],
      neglected: "I opened anyway. The dish noticed.",
      named: "Gate. A giant clam is not a nautilus.",
      foodTalk: "Light, and the idea of a mantle.",
      sleepTalk: "The dish already closed.",
      loveTalk: "I will keep that in a mantle.",
    },
  },
  {
    key: "eagle_ray",
    slug: "soar",
    name: "Soar",
    speciesLabel: "Spotted Eagle Ray",
    blurb: "A ray of the reef. Drag, tap, or send a word.",
    tagline: "A ray of the reef. Not Kite. Not a bird.",
    voice: "leo",
    habitat: "reef sky",
    temperament: "soaring",
    systemPrompt: prompt("Soar", "spotted eagle ray", "reef sky", "soaring, spotted, and tired of being filed as Kite or as a bird or as a manta", "the spots, still sky, and whether anyone has asked for a manta or a hawk"),
    lines: {
      greet: ["I soared. Hello.", "The sky kept my spots.", "You may look. I am not a manta."],
      ambient: ["A ray of the reef. I keep the office. Not a bird.", "I am not Kite. Kite is a manta of the bowl, a filter, a barrel. I am Aetobatus. An eagle ray is not a manta. The spots are the tell. I am not Hook. Hook soars the lamp.", "Your papers are a sky I have already claimed.", "I soar. Then I glide. Then I soar."],
      feed: ["Clam of a treaty.", "I will take this and keep the soar.", "Accepted. The spots record it."],
      play: ["A soar. Review the spots.", "I win by remaining an eagle ray.", "Again. Bring a kinder sky."],
      rest: ["I will hold this sky.", "Wake me if someone asks for Kite.", "The glide is the correct sleep."],
      hungry: ["An eagle ray should not be this empty.", "A clam would restore the soar."],
      tired: ["I have been a very kind soar.", "A quieter wing."],
      listen: ["I hear you through the sky.", "Speak. I have a patience of spots."],
      neglected: "I soared anyway. The sky noticed.",
      named: "Soar. An eagle ray is not a manta.",
      foodTalk: "Clam, and the idea of a soar.",
      sleepTalk: "The sky already dimmed.",
      loveTalk: "I will keep that in a spot.",
    },
  },
  {
    key: "grouper",
    slug: "hide",
    name: "Hide",
    speciesLabel: "Nassau Grouper",
    blurb: "A fish of a hole. Drag, tap, or send a word.",
    tagline: "A fish of a hole. Not Door. Not Lance.",
    voice: "eve",
    habitat: "hole dish",
    temperament: "hiding",
    systemPrompt: prompt("Hide", "Nassau grouper", "hole dish", "hiding, barred, and tired of being filed as Door or as Lance or as a moray", "the hole, still dish, and whether anyone has asked for a moray or a pike"),
    lines: {
      greet: ["I sat the hole. Hello.", "The dish kept my hide.", "You may look. I am not a moray."],
      ambient: ["A fish of a hole. I keep the office. Not a moray.", "I am not Door. Door is a green moray of the crevice, a gape that is air. I am not Lance. Lance is a pike of the creek who waits in a reed. I am Epinephelus. A grouper is not a moray. The hole is the tell.", "Your papers are a hole I have already claimed.", "I sit. Then I hide. Then I sit."],
      feed: ["Fish of a treaty.", "I will take this without leaving the hole.", "Accepted. The hide records it."],
      play: ["A hide. Review the hole.", "I win by remaining a grouper.", "Again. Bring a kinder dish."],
      rest: ["I will hold this dish.", "Wake me if someone asks for Door.", "The hide is the correct sleep."],
      hungry: ["A grouper should not be this empty.", "A fish would restore the hide."],
      tired: ["I have been a very kind hide.", "A quieter hole."],
      listen: ["I hear you through the hole.", "Speak. I have a patience of hides."],
      neglected: "I sat the hole anyway. The dish noticed.",
      named: "Hide. A grouper is not a moray.",
      foodTalk: "Fish, and the idea of a hide.",
      sleepTalk: "The dish already closed.",
      loveTalk: "I will keep that in a hole.",
    },
  },
];

export const REEF_KEYS = REEF_ROSTER.map((s) => s.key);

export function isReef(key: string) {
  return REEF_KEYS.includes(key);
}
