export type SpeciesTrait = {
  walk: number;
  hop: number;
  scale: number;
  wander: number;
  nocturnal: boolean;
  perch: boolean;
  aquatic: boolean;
  clingy: boolean;
  special: string;
  verb: string;
  line: string;
};

const T = (
  walk: number,
  hop: number,
  scale: number,
  wander: number,
  flags: Partial<Pick<SpeciesTrait, "nocturnal" | "perch" | "aquatic" | "clingy">>,
  special: string,
  verb: string,
  line: string,
): SpeciesTrait => ({
  walk,
  hop,
  scale,
  wander,
  nocturnal: !!flags.nocturnal,
  perch: !!flags.perch,
  aquatic: !!flags.aquatic,
  clingy: !!flags.clingy,
  special,
  verb,
  line,
});

export const TRAITS: Record<string, SpeciesTrait> = {
  red_panda: T(98, 26, 1, 0.48, {}, "ribbon", "Steal ribbon", "I found a ribbon. It was not lost. It is now safer."),
  cat: T(68, 16, 1.02, 0.22, {}, "sun", "Claim the sun", "This patch of light is reserved."),
  dog: T(122, 30, 0.96, 0.62, { clingy: true }, "follow", "Heel", "The cursor moved. I have prepared a walk."),
  rabbit: T(136, 36, 0.86, 0.4, {}, "thump", "Thump", "Thump. That was a warning and a hello."),
  hamster: T(148, 22, 0.7, 0.7, { nocturnal: true }, "hoard", "Hoard", "This paperclip is now mine. Officially."),
  guinea_pig: T(84, 18, 0.8, 0.5, { clingy: true }, "wheek", "Wheek", "Wheek. Deploy celebrated."),
  turtle: T(26, 3, 0.92, 0.08, {}, "still", "Be still", "I moved. You missed it. That is fine."),
  goldfish: T(52, 6, 0.78, 0.8, { aquatic: true }, "loop", "Loop", "Around again. The view improved."),
  budgie: T(92, 20, 0.68, 0.45, { perch: true }, "echo", "Echo", "Build failed. But musically."),
  fox: T(112, 24, 1.04, 0.4, { nocturnal: true }, "bug", "Find a bug", "There is a bug in the left pocket. You knew."),
  penguin: T(58, 12, 0.9, 0.28, {}, "ritual", "Bow", "A bow. It is brief. It is required."),
  parrot: T(88, 22, 0.94, 0.42, { perch: true }, "quote", "Quote", "Fix typo. A masterpiece."),
  ferret: T(156, 20, 0.88, 0.75, {}, "steal", "Steal", "I put your dongle somewhere better."),
  hedgehog: T(48, 10, 0.76, 0.16, { nocturnal: true }, "curl", "Curl", "Waiting is a kindness I notice."),
  chinchilla: T(118, 26, 0.8, 0.38, {}, "bath", "Dust bath", "That crumb is a scandal."),
  axolotl: T(34, 5, 0.9, 0.3, { aquatic: true }, "regrow", "Regrow", "I grew a little more calm."),
  toucan: T(80, 18, 1.08, 0.34, { perch: true }, "bill", "Inspect", "This perch has opinions about your posture."),
  iguana: T(20, 4, 1.06, 0.06, {}, "bask", "Bask", "I blinked. Minutes will not record it."),
  dragon: T(74, 22, 1.18, 0.24, {}, "hoard", "Keep watch", "I could be larger. I choose this."),
  phoenix: T(86, 24, 1.12, 0.3, { perch: true }, "reborn", "Ember", "I came back softer."),
  ball_python: T(36, 4, 0.92, 0.14, {}, "coil", "Coil", "I made a bun. I am the bun."),
  corn_snake: T(88, 8, 0.84, 0.55, { nocturnal: true }, "slither", "Thread", "I found a gap. I am the gap's problem."),
  kingsnake: T(74, 8, 0.88, 0.32, {}, "inspect", "Inspect", "I am the law of this drawer."),
  green_tree_python: T(28, 6, 0.9, 0.1, { perch: true, nocturnal: true }, "drape", "Drape", "I folded in half. That is sitting."),
  hognose: T(70, 10, 0.78, 0.38, {}, "playdead", "Play dead", "I died. I got over it."),
  garter: T(110, 10, 0.68, 0.7, {}, "patrol", "Patrol", "I do not lounge. I pause."),
  boa: T(42, 5, 1.08, 0.16, {}, "hold", "Hold", "I could be tighter. I choose this."),
  milk_snake: T(80, 8, 0.82, 0.4, { nocturnal: true }, "mimic", "Mimic", "I am not who I look like. Hello."),
  rosy_boa: T(34, 4, 0.8, 0.12, {}, "nest", "Nest", "I am a blush that learned to crawl."),
  carpet_python: T(64, 8, 1.04, 0.28, { perch: true }, "chart", "Chart", "This pattern is a map. I am the country."),
  octopus: T(48, 10, 0.88, 0.35, { aquatic: true }, "ink", "Ink", "I jet. Then I am a cup again."),
  cuttlefish: T(40, 4, 0.9, 0.45, { aquatic: true }, "flush", "Flush", "I changed for you. Then I changed back."),
  nautilus: T(36, 8, 0.95, 0.28, { aquatic: true }, "rise", "Rise", "I have been rising. You may wait."),
  moon_jelly: T(28, 2, 0.82, 0.7, { aquatic: true }, "pulse", "Pulse", "I pulsed. That was hello."),
  sea_star: T(14, 2, 0.7, 0.06, { aquatic: true }, "cling", "Cling", "I have not moved. That is hello."),
  hermit_crab: T(56, 8, 0.72, 0.4, {}, "trade", "Trade", "This shell is temporary. Hello."),
  horseshoe_crab: T(32, 4, 0.86, 0.18, {}, "molt", "Molt", "I am not a crab. Hello."),
  seahorse: T(24, 2, 0.68, 0.22, { aquatic: true }, "hitch", "Hitch", "I hitched. You may look."),
  manta: T(44, 3, 1.16, 0.5, { aquatic: true }, "soar", "Soar", "I saved you a length of sky."),
  moray: T(70, 6, 1.02, 0.08, { aquatic: true }, "gape", "Gape", "The gape is air. Not a threat. Mostly."),
  moss: T(6, 0, 0.55, 0.04, {}, "carpet", "Carpet", "I was already the page. Hello."),
  maidenhair: T(8, 0, 0.72, 0.06, {}, "unfurl", "Unfurl", "I unfurled an inch. Hello."),
  ginkgo: T(10, 0, 0.85, 0.08, {}, "gold", "Gold", "I have been gold before. Hello."),
  oak: T(8, 0, 0.78, 0.05, {}, "drop", "Drop", "I agreed to be small."),
  water_lily: T(12, 0, 0.88, 0.15, { aquatic: true }, "open", "Open", "I opened. That was hello."),
  orchid: T(8, 0, 0.9, 0.06, {}, "bloom", "Bloom", "I bloomed. You may look."),
  saguaro: T(4, 0, 1.05, 0.03, {}, "store", "Store", "I have not moved. That is hello."),
  venus_flytrap: T(8, 14, 0.68, 0.06, {}, "snap", "Snap", "I did not snap. That is hello."),
  pitcher: T(6, 0, 0.82, 0.03, {}, "drown", "Drown", "I did not chase. The well was enough."),
  sundew: T(8, 0, 0.55, 0.05, {}, "glue", "Glue", "I glittered. That was hello."),
  honeybee: T(140, 18, 0.58, 0.62, { perch: true }, "waggle", "Waggle", "I danced. That was hello."),
  monarch: T(88, 16, 0.82, 0.38, { perch: true }, "migrate", "Migrate", "I kept the orange. Hello."),
  luna: T(14, 6, 0.92, 0.1, { nocturnal: true, perch: true }, "still", "Moon", "I arrived without a mouth. Hello."),
  firefly: T(86, 28, 0.52, 0.4, { nocturnal: true }, "flash", "Flash", "I flashed. That was hello."),
  darner: T(156, 20, 0.84, 0.58, {}, "hawk", "Hawk", "I hawed the lamp. Hello."),
  stick: T(16, 2, 0.78, 0.05, {}, "freeze", "Freeze", "I have not moved. That is hello."),
  carpenter_ant: T(128, 10, 0.48, 0.68, { nocturnal: true }, "trail", "Trail", "I laid a road. Hello."),
  ladybird: T(78, 14, 0.5, 0.32, {}, "count", "Count", "I counted. Hello."),
  mantis: T(42, 8, 0.8, 0.12, {}, "fold", "Fold", "I did not strike. That is hello."),
  cicada: T(22, 8, 0.7, 0.08, {}, "emerge", "Emerge", "I emerged. You may wait."),
  bumblebee: T(96, 14, 0.72, 0.48, { perch: true }, "thrum", "Thrum", "I thrummed. That was hello."),
  carpenter_bee: T(88, 12, 0.78, 0.36, { perch: true }, "bore", "Bore", "I bored. Hello."),
  mason_bee: T(72, 10, 0.52, 0.28, {}, "seal", "Seal", "I sealed a cell. Hello."),
  leafcutter: T(76, 12, 0.54, 0.32, {}, "cut", "Cut", "I cut a circle. Hello."),
  stingless: T(84, 12, 0.5, 0.42, { perch: true }, "pot", "Pot", "I filled a pot. Hello."),
  sweat_bee: T(90, 14, 0.46, 0.4, {}, "shine", "Shine", "I shone. Hello."),
  mining_bee: T(68, 10, 0.5, 0.3, {}, "dig", "Dig", "I dug. Hello."),
  honey_drone: T(70, 8, 0.7, 0.18, { perch: true }, "hum", "Hum", "I hummed. That was hello."),
  honey_queen: T(28, 4, 0.86, 0.08, { perch: true }, "lay", "Lay", "I stayed. That was hello."),
  honeycomb: T(2, 0, 0.95, 0.02, {}, "hold", "Hold", "I sat. That was hello."),
  oyster: T(8, 0, 0.72, 0.05, {}, "fruit", "Fruit", "I fruited. That was hello."),
  fly_agaric: T(6, 0, 0.78, 0.04, {}, "warn", "Warn", "I am a warning. Hello."),
  morel: T(6, 0, 0.7, 0.04, {}, "pit", "Pit", "I am hollow. Hello."),
  chanterelle: T(8, 0, 0.68, 0.05, {}, "ridge", "Ridge", "The ridges fork. Hello."),
  turkey_tail: T(4, 0, 0.58, 0.03, {}, "zone", "Zone", "I zoned. Hello."),
  lions_mane: T(6, 0, 0.8, 0.04, {}, "tooth", "Tooth", "I grew teeth. Hello."),
  puffball: T(10, 8, 0.64, 0.12, {}, "spore", "Puff", "I puffed. That was hello."),
  chicken_of_woods: T(6, 0, 0.86, 0.04, {}, "shelf", "Shelf", "I shelved. Hello."),
  yeast: T(4, 2, 0.48, 0.08, {}, "rise", "Rise", "I rose. That was hello."),
  lichen: T(2, 0, 0.66, 0.02, {}, "share", "Share", "We are two. Hello."),
  photovore: T(36, 4, 0.62, 0.35, { aquatic: true }, "drink", "Drink", "I drank. That was hello."),
  choir: T(18, 2, 0.78, 0.16, {}, "chord", "Chord", "I sounded. That was hello."),
  nimbus: T(28, 2, 0.84, 0.55, { aquatic: true }, "float", "Float", "I floated. That was hello."),
  silica: T(4, 0, 0.7, 0.03, {}, "facet", "Facet", "I faceted. Hello."),
  terminator: T(42, 4, 0.68, 0.22, { clingy: true }, "edge", "Edge", "I kept the rim. Hello."),
  nexus: T(24, 4, 0.86, 0.2, {}, "count", "Count", "We counted. Hello."),
  halovore: T(16, 2, 0.72, 0.1, {}, "frost", "Frost", "I frosted. Hello."),
  magneton: T(132, 6, 0.74, 0.48, {}, "align", "Align", "I aligned. Hello."),
  umbral: T(6, 0, 0.76, 0.04, { nocturnal: true }, "dim", "Dim", "I dimmed. Hello."),
  cyst: T(2, 0, 0.58, 0.02, {}, "wake", "Wake", "I waited. That was hello."),
  frog: T(88, 32, 0.72, 0.45, {}, "croak", "Croak", "I jumped. That was hello."),
  toad: T(54, 18, 0.78, 0.22, {}, "puff", "Puff", "I hopped. Hello."),
  newt: T(62, 8, 0.58, 0.38, { aquatic: true }, "eft", "Eft", "I kept the orange. Hello."),
  salamander: T(48, 6, 0.7, 0.12, { nocturnal: true }, "hide", "Hide", "I waited under the leaf. Hello."),
  caecilian: T(44, 4, 0.82, 0.2, { aquatic: true }, "ring", "Ring", "I am not a worm. Hello."),
  crayfish: T(70, 8, 0.68, 0.32, { aquatic: true }, "pinch", "Pinch", "I pinched. That was hello."),
  pond_snail: T(10, 0, 0.55, 0.06, { aquatic: true }, "rasp", "Rasp", "I rasped. Hello."),
  mussel: T(4, 0, 0.72, 0.03, { aquatic: true }, "siphon", "Siphon", "I filtered. Hello."),
  leech: T(36, 4, 0.5, 0.28, { aquatic: true }, "latch", "Latch", "I latched. Hello."),
  stickleback: T(80, 6, 0.64, 0.5, { aquatic: true }, "flare", "Flare", "I flared. Hello."),
  paramecium: T(48, 2, 0.55, 0.5, { aquatic: true }, "cilia", "Cilia", "I rowed. That was hello."),
  amoeba: T(16, 2, 0.7, 0.12, { aquatic: true }, "reach", "Reach", "I reached. Hello."),
  euglena: T(40, 2, 0.52, 0.4, { aquatic: true }, "spot", "Spot", "I kept the red. Hello."),
  volvox: T(22, 2, 0.78, 0.25, { aquatic: true }, "roll", "Roll", "We rolled. Hello."),
  diatom: T(8, 0, 0.5, 0.06, { aquatic: true }, "pane", "Pane", "I grew the pane. Hello."),
  kelp: T(4, 0, 1.05, 0.03, {}, "holdfast", "Holdfast", "I held. Hello."),
  chlamydomonas: T(56, 2, 0.48, 0.45, { aquatic: true }, "spin", "Spin", "I spun. Hello."),
  stentor: T(12, 0, 0.72, 0.1, { aquatic: true }, "trumpet", "Trumpet", "I opened. Hello."),
  coli: T(90, 4, 0.42, 0.55, {}, "tumble", "Tumble", "I tumbled. Hello."),
  haloarchaea: T(28, 2, 0.5, 0.2, {}, "blush", "Blush", "I blushed. Hello."),
  crow: T(90, 22, 0.86, 0.48, { perch: true }, "caw", "Caw", "I cawed. That was hello."),
  raven: T(82, 18, 1.08, 0.36, { perch: true }, "kronk", "Croak", "I croaked. Hello."),
  barn_owl: T(70, 16, 0.92, 0.28, { nocturnal: true, perch: true }, "hiss", "Hiss", "I hissed. Hello."),
  red_tail: T(110, 14, 1.06, 0.55, { perch: true }, "soar", "Soar", "I soared. Hello."),
  chickadee: T(110, 28, 0.52, 0.55, { perch: true }, "dee", "Dee", "Dee-dee. Hello."),
  robin: T(85, 30, 0.72, 0.42, { perch: true }, "run", "Hop", "I hopped. Hello."),
  mallard: T(62, 10, 0.88, 0.32, {}, "dabble", "Dabble", "I dabbled. Hello."),
  canada_goose: T(70, 8, 1.16, 0.28, {}, "honk", "Honk", "I honked. Hello."),
  pileated: T(76, 20, 1.0, 0.34, { perch: true }, "drum", "Drum", "I drummed. Hello."),
  hummingbird: T(150, 30, 0.42, 0.7, { perch: true }, "hover", "Hover", "I hovered. Hello."),
  orb_weaver: T(18, 2, 0.62, 0.08, { perch: true }, "web", "Loom", "I sat the web. Hello."),
  jumping_spider: T(88, 36, 0.48, 0.55, {}, "leap", "Leap", "I leapt. That was hello."),
  wolf_spider: T(72, 10, 0.7, 0.32, { nocturnal: true }, "prowl", "Prowl", "I prowled. Hello."),
  tarantula: T(36, 4, 0.92, 0.14, { nocturnal: true }, "flick", "Flick", "I sat the silk. Hello."),
  widow: T(22, 2, 0.52, 0.08, { nocturnal: true, perch: true }, "hour", "Hour", "I hung. Hello."),
  harvestman: T(64, 6, 0.58, 0.42, { nocturnal: true }, "stem", "Stem", "I walked the stem. Hello."),
  scorpion: T(48, 6, 0.74, 0.18, { nocturnal: true }, "sting", "Sting", "I raised the tail. Hello."),
  vinegaroon: T(44, 4, 0.86, 0.16, { nocturnal: true }, "spray", "Spray", "I whipped. Hello."),
  tick: T(8, 0, 0.38, 0.04, { clingy: true }, "clasp", "Clasp", "I clasped. Hello."),
  solifuge: T(140, 12, 0.68, 0.62, { nocturnal: true }, "gale", "Gale", "I ran. Hello."),
  deer: T(110, 8, 1.12, 0.38, {}, "flag", "Flag", "I flagged. That was hello."),
  bat: T(130, 22, 0.56, 0.48, { nocturnal: true, perch: true }, "hang", "Hang", "I hung. Hello."),
  squirrel: T(128, 28, 0.7, 0.62, {}, "cache", "Cache", "I hid a thought. Hello."),
  otter: T(96, 12, 0.88, 0.55, { aquatic: true }, "slide", "Slide", "I slid. That was hello."),
  raccoon: T(88, 14, 0.92, 0.36, { nocturnal: true }, "rinse", "Wash", "I washed. Hello."),
  skunk: T(64, 8, 0.78, 0.22, { nocturnal: true }, "warn", "Warn", "I stamped. Hello."),
  opossum: T(72, 10, 0.84, 0.28, { nocturnal: true }, "playdead", "Play dead", "I went still. Hello."),
  beaver: T(42, 4, 0.96, 0.16, { aquatic: true }, "lodge", "Lodge", "I gnawed. Hello."),
  porcupine: T(36, 4, 0.86, 0.1, { nocturnal: true }, "bristle", "Bristle", "I bristled. Hello."),
  black_bear: T(58, 8, 1.22, 0.18, {}, "forage", "Forage", "I foraged. Hello."),
  gecko: T(88, 8, 0.48, 0.32, { nocturnal: true, clingy: true }, "climb", "Climb", "I climbed. Hello."),
  anole: T(86, 12, 0.52, 0.38, {}, "dewlap", "Flash", "I flashed. Hello."),
  skink: T(104, 10, 0.55, 0.48, {}, "dash", "Dash", "I dashed. Hello."),
  chameleon: T(18, 2, 0.72, 0.06, { perch: true }, "shift", "Shift", "I shifted. Hello."),
  horned_lizard: T(34, 4, 0.62, 0.1, {}, "squirt", "Squirt", "I sat the crown. Hello."),
  alligator: T(26, 2, 1.18, 0.08, { aquatic: true }, "levee", "Bank", "I sat the bank. Hello."),
  crocodile: T(30, 2, 1.16, 0.1, { aquatic: true }, "show", "Show", "I showed. Hello."),
  snapper: T(28, 3, 0.88, 0.1, { aquatic: true }, "snap", "Snap", "I snapped. Hello."),
  box_turtle: T(20, 2, 0.78, 0.06, {}, "shut", "Shut", "I shut. Hello."),
  tuatara: T(14, 2, 0.82, 0.04, { nocturnal: true }, "crest", "Still", "I kept still. Hello."),
  bass: T(72, 4, 0.92, 0.28, { aquatic: true }, "lunge", "Lunge", "I lunged. Hello."),
  brook_trout: T(86, 6, 0.7, 0.48, { aquatic: true }, "speck", "Speck", "I rose. Hello."),
  catfish: T(38, 2, 0.88, 0.18, { aquatic: true, nocturnal: true }, "whisk", "Whisk", "I whisked. Hello."),
  bluegill: T(64, 4, 0.58, 0.36, { aquatic: true }, "penny", "Penny", "I flared the flap. Hello."),
  perch: T(68, 4, 0.66, 0.38, { aquatic: true }, "bar", "Bar", "I kept the bars. Hello."),
  pike: T(48, 2, 1.08, 0.12, { aquatic: true }, "lance", "Lance", "I waited. Hello."),
  walleye: T(54, 3, 0.82, 0.22, { aquatic: true, nocturnal: true }, "night", "Night", "I hunted dusk. Hello."),
  paddlefish: T(26, 0, 1.14, 0.1, { aquatic: true }, "spoon", "Filter", "I filtered. Hello."),
  lamprey: T(22, 0, 0.72, 0.08, { aquatic: true }, "round", "Disk", "I sat the disk. Hello."),
  american_eel: T(58, 2, 0.86, 0.32, { aquatic: true, nocturnal: true }, "silver", "Silver", "I swam. Hello."),
  house_centipede: T(168, 8, 0.72, 0.55, { nocturnal: true }, "haste", "Hunt", "I hunted. Hello."),
  millipede: T(22, 2, 0.8, 0.1, { nocturnal: true }, "link", "Oil", "I oiled. Hello."),
  pillbug: T(36, 4, 0.5, 0.16, { nocturnal: true }, "armor", "Roll", "I rolled. Hello."),
  earthworm: T(18, 0, 0.7, 0.08, { nocturnal: true }, "cast", "Cast", "I cast. Hello."),
  velvet_worm: T(28, 2, 0.65, 0.12, { nocturnal: true }, "jet", "Jet", "I jetted. Hello."),
  springtail: T(90, 28, 0.4, 0.48, {}, "hop", "Hop", "I hopped. Hello."),
  tardigrade: T(12, 0, 0.35, 0.06, {}, "tun", "Tun", "I sat the moss. Hello."),
  planarian: T(16, 0, 0.5, 0.1, { aquatic: true }, "half", "Split", "I split. Hello."),
  nematode: T(40, 0, 0.3, 0.22, {}, "thread", "Thrash", "I thrashed. Hello."),
  amphipod: T(54, 4, 0.48, 0.36, { aquatic: true, nocturnal: true }, "scud", "Scud", "I swam on my side. Hello."),
  fiddler_crab: T(72, 6, 0.55, 0.38, {}, "wave", "Wave", "I waved. Hello."),
  ghost_crab: T(148, 10, 0.62, 0.52, { nocturnal: true }, "pale", "Run", "I ran. Hello."),
  limpet: T(10, 0, 0.48, 0.04, { clingy: true }, "clamp", "Clamp", "I clamped. Hello."),
  barnacle: T(2, 0, 0.42, 0.0, { clingy: true, aquatic: true }, "cement", "Stay", "I sat the stone. Hello."),
  chiton: T(18, 2, 0.52, 0.08, { clingy: true }, "mail", "Plate", "I plated. Hello."),
  periwinkle: T(16, 2, 0.46, 0.08, { clingy: true }, "spire", "Rasp", "I rasped. Hello."),
  sand_dollar: T(12, 0, 0.58, 0.06, { aquatic: true }, "token", "Bury", "I sat the sand. Hello."),
  sea_urchin: T(22, 2, 0.64, 0.1, { aquatic: true }, "thorn", "Spine", "I sat the spines. Hello."),
  knobbed_whelk: T(20, 2, 0.72, 0.08, {}, "knurl", "Hunt", "I hunted. Hello."),
  lugworm: T(14, 0, 0.6, 0.06, { nocturnal: true }, "heap", "Heap", "I heaped. Hello."),
  field_cricket: T(48, 8, 0.52, 0.22, { nocturnal: true }, "chirp", "Chirp", "I sang. Hello."),
  katydid: T(22, 4, 0.72, 0.08, { nocturnal: true, perch: true }, "blade", "Still", "I sat the leaf. Hello."),
  grasshopper: T(96, 32, 0.68, 0.42, {}, "vault", "Vault", "I vaulted. Hello."),
  swallowtail: T(92, 16, 0.84, 0.4, { perch: true }, "banner", "Banner", "I kept the yellow. Hello."),
  jewelwing: T(88, 14, 0.7, 0.38, {}, "jewel", "Jewel", "I kept the black. Hello."),
  lacewing: T(76, 12, 0.5, 0.3, { nocturnal: true }, "lace", "Lace", "I laced. Hello."),
  earwig: T(42, 4, 0.48, 0.18, { nocturnal: true }, "forceps", "Forceps", "I raised the cerci. Hello."),
  acorn_weevil: T(18, 2, 0.46, 0.08, {}, "snout", "Snout", "I sat the acorn. Hello."),
  click_beetle: T(64, 20, 0.62, 0.28, { nocturnal: true }, "click", "Click", "I clicked. Hello."),
  robber_fly: T(110, 12, 0.78, 0.48, {}, "rob", "Rob", "I hunted. Hello."),
  sloth: T(12, 2, 0.92, 0.04, { perch: true }, "hang", "Hang", "I hung. Hello."),
  lemur: T(88, 14, 0.78, 0.42, {}, "sun", "Sun", "I sat the sun. Hello."),
  gibbon: T(118, 18, 0.86, 0.48, { perch: true }, "swing", "Swing", "I sang. Hello."),
  kinkajou: T(76, 10, 0.7, 0.28, { nocturnal: true, perch: true }, "wrist", "Wrist", "I wrapped. Hello."),
  colugo: T(54, 6, 0.88, 0.16, { nocturnal: true, perch: true }, "sail", "Sail", "I sailed. Hello."),
  flying_squirrel: T(102, 22, 0.58, 0.52, { nocturnal: true, perch: true }, "glide", "Glide", "I glided. Hello."),
  howler: T(42, 6, 1.04, 0.14, { perch: true }, "boom", "Boom", "I howled. Hello."),
  tarsier: T(96, 28, 0.48, 0.36, { nocturnal: true, perch: true }, "gaze", "Gaze", "I looked. Hello."),
  potto: T(18, 2, 0.62, 0.06, { nocturnal: true, perch: true }, "still", "Still", "I kept still. Hello."),
  koala: T(22, 3, 0.84, 0.08, { perch: true }, "gum", "Gum", "I chewed. Hello."),
  brain_coral: T(4, 0, 0.88, 0.02, { aquatic: true, clingy: true }, "ridge", "Ridge", "I sat the rock. Hello."),
  anemone: T(6, 0, 0.82, 0.04, { aquatic: true }, "wreath", "Wreath", "I opened. Hello."),
  clownfish: T(86, 8, 0.58, 0.42, { aquatic: true }, "paint", "Paint", "I sat the wreath. Hello."),
  parrotfish: T(72, 6, 0.86, 0.32, { aquatic: true }, "scrape", "Scrape", "I rasped. Hello."),
  cleaner_shrimp: T(54, 8, 0.48, 0.28, { aquatic: true }, "scrub", "Scrub", "I waited. Hello."),
  sea_cucumber: T(16, 2, 0.78, 0.08, { aquatic: true }, "tube", "Tube", "I sat the sand. Hello."),
  lionfish: T(38, 4, 0.92, 0.14, { aquatic: true, nocturnal: true }, "veil", "Veil", "I veiled. Hello."),
  giant_clam: T(2, 0, 1.08, 0.02, { aquatic: true, clingy: true }, "gate", "Gate", "I opened. Hello."),
  eagle_ray: T(48, 4, 1.14, 0.46, { aquatic: true }, "soar", "Soar", "I soared. Hello."),
  grouper: T(42, 4, 0.96, 0.1, { aquatic: true }, "hide", "Hide", "I sat the hole. Hello."),
};

export const FALLBACK_TRAIT = TRAITS.red_panda!;

export function traitFor(key: string) {
  return TRAITS[key] ?? FALLBACK_TRAIT;
}
