export type TreatShape = "bamboo" | "crumb" | "seed" | "leaf" | "flake" | "pebble" | "ember" | "egg";

const TREATS: Record<string, { shape: TreatShape; verb: string }> = {
  red_panda: { shape: "bamboo", verb: "Bamboo" },
  cat: { shape: "crumb", verb: "Crumbs" },
  dog: { shape: "crumb", verb: "Biscuit" },
  rabbit: { shape: "leaf", verb: "Greens" },
  hamster: { shape: "seed", verb: "Seed" },
  guinea_pig: { shape: "leaf", verb: "Haybit" },
  turtle: { shape: "leaf", verb: "Leaf" },
  goldfish: { shape: "flake", verb: "Flake" },
  budgie: { shape: "seed", verb: "Seed" },
  fox: { shape: "crumb", verb: "Morsel" },
  penguin: { shape: "pebble", verb: "Pebble" },
  parrot: { shape: "seed", verb: "Nut" },
  ferret: { shape: "crumb", verb: "Nibble" },
  hedgehog: { shape: "crumb", verb: "Bug" },
  chinchilla: { shape: "seed", verb: "Rosehip" },
  axolotl: { shape: "flake", verb: "Worm" },
  toucan: { shape: "leaf", verb: "Fruit" },
  iguana: { shape: "leaf", verb: "Green" },
  dragon: { shape: "ember", verb: "Tribute" },
  phoenix: { shape: "ember", verb: "Ember" },
  ball_python: { shape: "crumb", verb: "Mouse" },
  corn_snake: { shape: "crumb", verb: "Pinkie" },
  kingsnake: { shape: "egg", verb: "Egg" },
  green_tree_python: { shape: "ember", verb: "Warmth" },
  hognose: { shape: "crumb", verb: "Toad" },
  garter: { shape: "flake", verb: "Worm" },
  boa: { shape: "crumb", verb: "Tribute" },
  milk_snake: { shape: "egg", verb: "Egg" },
  rosy_boa: { shape: "crumb", verb: "Mouse" },
  carpet_python: { shape: "crumb", verb: "Morsel" },
  octopus: { shape: "crumb", verb: "Crab" },
  cuttlefish: { shape: "crumb", verb: "Shrimp" },
  nautilus: { shape: "crumb", verb: "Morsel" },
  moon_jelly: { shape: "flake", verb: "Plankton" },
  sea_star: { shape: "pebble", verb: "Clam" },
  hermit_crab: { shape: "crumb", verb: "Scrap" },
  horseshoe_crab: { shape: "flake", verb: "Worm" },
  seahorse: { shape: "flake", verb: "Brine" },
  manta: { shape: "flake", verb: "Plankton" },
  moray: { shape: "crumb", verb: "Fish" },
  moss: { shape: "flake", verb: "Dew" },
  maidenhair: { shape: "flake", verb: "Mist" },
  ginkgo: { shape: "leaf", verb: "Leaf" },
  oak: { shape: "leaf", verb: "Water" },
  water_lily: { shape: "flake", verb: "Silt" },
  orchid: { shape: "flake", verb: "Mist" },
  saguaro: { shape: "pebble", verb: "Rain" },
  venus_flytrap: { shape: "crumb", verb: "Fly" },
  pitcher: { shape: "crumb", verb: "Midge" },
  sundew: { shape: "crumb", verb: "Gnat" },
  honeybee: { shape: "flake", verb: "Nectar" },
  monarch: { shape: "leaf", verb: "Milkweed" },
  luna: { shape: "flake", verb: "Dusk" },
  firefly: { shape: "crumb", verb: "Midge" },
  darner: { shape: "crumb", verb: "Mosquito" },
  stick: { shape: "leaf", verb: "Leaf" },
  carpenter_ant: { shape: "flake", verb: "Honeydew" },
  ladybird: { shape: "crumb", verb: "Aphid" },
  mantis: { shape: "crumb", verb: "Fly" },
  cicada: { shape: "flake", verb: "Sap" },
  bumblebee: { shape: "flake", verb: "Nectar" },
  carpenter_bee: { shape: "flake", verb: "Nectar" },
  mason_bee: { shape: "flake", verb: "Pollen" },
  leafcutter: { shape: "flake", verb: "Pollen" },
  stingless: { shape: "flake", verb: "Nectar" },
  sweat_bee: { shape: "flake", verb: "Nectar" },
  mining_bee: { shape: "flake", verb: "Pollen" },
  honey_drone: { shape: "flake", verb: "Nectar" },
  honey_queen: { shape: "flake", verb: "Jelly" },
  honeycomb: { shape: "flake", verb: "Nectar" },
  oyster: { shape: "leaf", verb: "Wood" },
  fly_agaric: { shape: "flake", verb: "Duff" },
  morel: { shape: "flake", verb: "Duff" },
  chanterelle: { shape: "flake", verb: "Duff" },
  turkey_tail: { shape: "leaf", verb: "Wood" },
  lions_mane: { shape: "leaf", verb: "Wood" },
  puffball: { shape: "flake", verb: "Duff" },
  chicken_of_woods: { shape: "leaf", verb: "Oak" },
  yeast: { shape: "crumb", verb: "Dough" },
  lichen: { shape: "flake", verb: "Dew" },
  photovore: { shape: "flake", verb: "Light" },
  choir: { shape: "flake", verb: "Tone" },
  nimbus: { shape: "flake", verb: "Gas" },
  silica: { shape: "pebble", verb: "Silica" },
  terminator: { shape: "ember", verb: "Rim" },
  nexus: { shape: "crumb", verb: "Count" },
  halovore: { shape: "flake", verb: "Salt" },
  magneton: { shape: "pebble", verb: "North" },
  umbral: { shape: "flake", verb: "Cool" },
  cyst: { shape: "crumb", verb: "Damp" },
  frog: { shape: "crumb", verb: "Cricket" },
  toad: { shape: "crumb", verb: "Cricket" },
  newt: { shape: "flake", verb: "Worm" },
  salamander: { shape: "flake", verb: "Worm" },
  caecilian: { shape: "flake", verb: "Worm" },
  crayfish: { shape: "crumb", verb: "Scrap" },
  pond_snail: { shape: "flake", verb: "Algae" },
  mussel: { shape: "flake", verb: "Silt" },
  leech: { shape: "flake", verb: "Worm" },
  stickleback: { shape: "flake", verb: "Flake" },
  paramecium: { shape: "flake", verb: "Bacteria" },
  amoeba: { shape: "crumb", verb: "Prey" },
  euglena: { shape: "flake", verb: "Light" },
  volvox: { shape: "flake", verb: "Light" },
  diatom: { shape: "pebble", verb: "Silica" },
  kelp: { shape: "flake", verb: "Light" },
  chlamydomonas: { shape: "flake", verb: "Light" },
  stentor: { shape: "flake", verb: "Bacteria" },
  coli: { shape: "crumb", verb: "Broth" },
  haloarchaea: { shape: "flake", verb: "Salt" },
  crow: { shape: "crumb", verb: "Scrap" },
  raven: { shape: "crumb", verb: "Scrap" },
  barn_owl: { shape: "crumb", verb: "Vole" },
  red_tail: { shape: "crumb", verb: "Vole" },
  chickadee: { shape: "seed", verb: "Seed" },
  robin: { shape: "flake", verb: "Worm" },
  mallard: { shape: "seed", verb: "Seed" },
  canada_goose: { shape: "leaf", verb: "Grass" },
  pileated: { shape: "crumb", verb: "Ant" },
  hummingbird: { shape: "flake", verb: "Nectar" },
  orb_weaver: { shape: "crumb", verb: "Fly" },
  jumping_spider: { shape: "crumb", verb: "Fly" },
  wolf_spider: { shape: "crumb", verb: "Cricket" },
  tarantula: { shape: "crumb", verb: "Cricket" },
  widow: { shape: "crumb", verb: "Fly" },
  harvestman: { shape: "crumb", verb: "Mite" },
  scorpion: { shape: "crumb", verb: "Cricket" },
  vinegaroon: { shape: "crumb", verb: "Cricket" },
  tick: { shape: "flake", verb: "Sip" },
  solifuge: { shape: "crumb", verb: "Cricket" },
  deer: { shape: "leaf", verb: "Browse" },
  bat: { shape: "crumb", verb: "Beetle" },
  squirrel: { shape: "seed", verb: "Acorn" },
  otter: { shape: "crumb", verb: "Fish" },
  raccoon: { shape: "crumb", verb: "Scrap" },
  skunk: { shape: "crumb", verb: "Grub" },
  opossum: { shape: "crumb", verb: "Scrap" },
  beaver: { shape: "leaf", verb: "Bark" },
  porcupine: { shape: "leaf", verb: "Bark" },
  black_bear: { shape: "leaf", verb: "Berry" },
  gecko: { shape: "crumb", verb: "Moth" },
  anole: { shape: "crumb", verb: "Cricket" },
  skink: { shape: "crumb", verb: "Cricket" },
  chameleon: { shape: "crumb", verb: "Cricket" },
  horned_lizard: { shape: "crumb", verb: "Ant" },
  alligator: { shape: "crumb", verb: "Fish" },
  crocodile: { shape: "crumb", verb: "Fish" },
  snapper: { shape: "crumb", verb: "Fish" },
  box_turtle: { shape: "crumb", verb: "Worm" },
  tuatara: { shape: "crumb", verb: "Insect" },
  bass: { shape: "flake", verb: "Minnow" },
  brook_trout: { shape: "flake", verb: "Fly" },
  catfish: { shape: "crumb", verb: "Scrap" },
  bluegill: { shape: "flake", verb: "Insect" },
  perch: { shape: "flake", verb: "Minnow" },
  pike: { shape: "crumb", verb: "Fish" },
  walleye: { shape: "flake", verb: "Minnow" },
  paddlefish: { shape: "flake", verb: "Plankton" },
  lamprey: { shape: "pebble", verb: "Stone" },
  american_eel: { shape: "crumb", verb: "Scrap" },
  house_centipede: { shape: "crumb", verb: "Silverfish" },
  millipede: { shape: "leaf", verb: "Leaf" },
  pillbug: { shape: "leaf", verb: "Leaf" },
  earthworm: { shape: "leaf", verb: "Leaf" },
  velvet_worm: { shape: "crumb", verb: "Cricket" },
  springtail: { shape: "flake", verb: "Flake" },
  tardigrade: { shape: "flake", verb: "Moss" },
  planarian: { shape: "crumb", verb: "Worm" },
  nematode: { shape: "flake", verb: "Flake" },
  amphipod: { shape: "crumb", verb: "Scrap" },
  fiddler_crab: { shape: "flake", verb: "Algae" },
  ghost_crab: { shape: "crumb", verb: "Scrap" },
  limpet: { shape: "flake", verb: "Algae" },
  barnacle: { shape: "flake", verb: "Drift" },
  chiton: { shape: "flake", verb: "Algae" },
  periwinkle: { shape: "flake", verb: "Algae" },
  sand_dollar: { shape: "flake", verb: "Diatom" },
  sea_urchin: { shape: "leaf", verb: "Kelp" },
  knobbed_whelk: { shape: "crumb", verb: "Clam" },
  lugworm: { shape: "pebble", verb: "Silt" },
};

export function treatFor(key: string) {
  return TREATS[key] ?? { shape: "crumb" as TreatShape, verb: "Treat" };
}

export const GIFT_LINE: Record<string, string> = {
  red_panda: "A ribbon I was not using. For the desk.",
  cat: "A moth. Consider it a review.",
  dog: "A sock. I found it first.",
  rabbit: "A clover. Four, if you squint.",
  hamster: "A seed from the official hoard.",
  guinea_pig: "Hay, arranged. Wheek optional.",
  turtle: "A stone I have been considering.",
  goldfish: "A bubble that lasted.",
  budgie: "A note. It says 'ok'.",
  fox: "The bug. Filed.",
  penguin: "A pebble of some standing.",
  parrot: "A word. Keep it.",
  ferret: "Your dongle. Improved.",
  hedgehog: "A leaf I trusted.",
  chinchilla: "Dust, but the good kind.",
  axolotl: "Calm, in object form.",
  toucan: "A berry. Inspected.",
  iguana: "Sun, compressed.",
  dragon: "A coin from the smaller hoard.",
  phoenix: "Ash that still glows.",
  ball_python: "A shed I was finished with.",
  corn_snake: "A pencil I was not using.",
  kingsnake: "A ruler. Straight, as required.",
  green_tree_python: "A loop of shed. Emerald still.",
  hognose: "A death scene, unused.",
  garter: "A moss sample. Official.",
  boa: "A weight I was not using.",
  milk_snake: "A stamp. Red, on purpose.",
  rosy_boa: "A warm pebble from the corner.",
  carpet_python: "A scrap of map. Accurate.",
  octopus: "A lid I was finished with.",
  cuttlefish: "A stripe I was not using.",
  nautilus: "A chamber of quiet.",
  moon_jelly: "A pulse that lasted.",
  sea_star: "A damp I trusted.",
  hermit_crab: "A lid that did not fit.",
  horseshoe_crab: "A page from the molt.",
  seahorse: "A hitch I was not using.",
  manta: "A barrel, unused.",
  moray: "A crevice I outgrew.",
  moss: "A square of green I was finished with.",
  maidenhair: "A fan I had already opened.",
  ginkgo: "A gold leaf I was not using.",
  oak: "An acorn I was finished considering.",
  water_lily: "A pad I was not using.",
  orchid: "A moth I was finished being.",
  saguaro: "A rain I stored twice.",
  venus_flytrap: "A snap I did not need.",
  pitcher: "A well I was finished holding.",
  sundew: "A drop I was finished glittering.",
  honeybee: "A dance I was not using.",
  monarch: "An orange I was finished wearing.",
  luna: "A dusk I was not eating.",
  firefly: "A flash I was finished saying.",
  darner: "A hawk I was not using.",
  stick: "A freeze I was finished holding.",
  carpenter_ant: "A road I was finished walking.",
  ladybird: "A count I was finished keeping.",
  mantis: "A fold I did not need.",
  cicada: "A year I was finished waiting.",
  bumblebee: "A thrum I was finished keeping.",
  carpenter_bee: "A hole I was finished boring.",
  mason_bee: "A cell I was finished sealing.",
  leafcutter: "A disc I was finished cutting.",
  stingless: "A pot I was finished filling.",
  sweat_bee: "A sheen I was finished wearing.",
  mining_bee: "A bank I was finished digging.",
  honey_drone: "A hum I was finished holding.",
  honey_queen: "A line I was finished writing.",
  honeycomb: "A cell I was finished holding.",
  oyster: "A shelf I was finished holding.",
  fly_agaric: "A warning I was not using.",
  morel: "A pit I was finished keeping.",
  chanterelle: "A ridge I was not using.",
  turkey_tail: "A zone I was finished wearing.",
  lions_mane: "A tooth I was finished hanging.",
  puffball: "A cloud I was finished saying.",
  chicken_of_woods: "A sulfur I was not using.",
  yeast: "A rise I was finished holding.",
  lichen: "A share I was finished keeping.",
  photovore: "A wavelength I was finished drinking.",
  choir: "A note I was not using.",
  nimbus: "A cold I was finished floating.",
  silica: "A facet I was finished shedding.",
  terminator: "A rim I was not using.",
  nexus: "A count I was finished keeping.",
  halovore: "A frost I was finished leaving.",
  magneton: "A north I was not using.",
  umbral: "A cool I was finished eating.",
  cyst: "A wait I was finished holding.",
  frog: "A hop I was finished keeping.",
  toad: "A puff I was not using.",
  newt: "An orange I was finished wearing.",
  salamander: "A coin I was finished hiding.",
  caecilian: "A ring I was not using.",
  crayfish: "A claw I was finished holding.",
  pond_snail: "A room I was finished growing.",
  mussel: "A silt I was finished filtering.",
  leech: "A latch I was finished keeping.",
  stickleback: "A spine I was not using.",
  paramecium: "A row I was finished keeping.",
  amoeba: "A foot I was not using.",
  euglena: "A red I was finished wearing.",
  volvox: "A daughter I was finished keeping.",
  diatom: "A pane I was finished growing.",
  kelp: "A bladder I was not using.",
  chlamydomonas: "An oar I was finished spinning.",
  stentor: "A horn I was finished opening.",
  coli: "A divide I was finished keeping.",
  haloarchaea: "A blush I was finished wearing.",
  crow: "A scrap I was finished hiding.",
  raven: "A thought I was finished keeping.",
  barn_owl: "A vole I was finished taking.",
  red_tail: "A vole I was finished stooping for.",
  chickadee: "A seed I was finished hiding.",
  robin: "A worm I was finished pulling.",
  mallard: "A seed I was finished tipping for.",
  canada_goose: "A grass I was finished keeping.",
  pileated: "An ant I was finished drumming for.",
  hummingbird: "A nectar I was finished sipping.",
  orb_weaver: "A fly I was finished wrapping.",
  jumping_spider: "A fly I was finished leaping for.",
  wolf_spider: "A cricket I was finished carrying past.",
  tarantula: "A cricket I was finished taking.",
  widow: "A fly I was finished hanging for.",
  harvestman: "A mite I was finished walking to.",
  scorpion: "A cricket I was finished raising for.",
  vinegaroon: "A cricket I was finished whipping for.",
  tick: "A sip I was finished waiting for.",
  solifuge: "A cricket I was finished running to.",
  deer: "A flag I was finished keeping.",
  bat: "A hang I was finished holding.",
  squirrel: "A thought I was finished hiding.",
  otter: "A slide I was finished keeping.",
  raccoon: "A rinse I was finished holding.",
  skunk: "A warning I was not using.",
  opossum: "A still I was finished keeping.",
  beaver: "A lodge I was finished holding.",
  porcupine: "A quill I was finished keeping.",
  black_bear: "A berry I was finished foraging.",
  gecko: "A moth I was finished climbing for.",
  anole: "A cricket I was finished flashing for.",
  skink: "A cricket I was finished dashing for.",
  chameleon: "A cricket I was finished aiming for.",
  horned_lizard: "An ant I was finished crowning for.",
  alligator: "A fish I was finished sitting for.",
  crocodile: "A fish I was finished showing for.",
  snapper: "A fish I was finished snapping for.",
  box_turtle: "A worm I was finished shutting after.",
  tuatara: "An insect I was finished keeping still for.",
  bass: "A minnow I was finished lunging for.",
  brook_trout: "A fly I was finished rising for.",
  catfish: "A scrap I was finished whisking for.",
  bluegill: "An insect I was finished flaring for.",
  perch: "A minnow I was finished barring for.",
  pike: "A fish I was finished waiting for.",
  walleye: "A minnow I was finished hunting dusk for.",
  paddlefish: "A plankton I was finished filtering.",
  lamprey: "A stone I was finished clinging to.",
  american_eel: "A scrap I was finished taking toward the Sargasso.",
  house_centipede: "A silverfish I was finished hunting.",
  millipede: "A leaf I was finished walking for.",
  pillbug: "A leaf I was finished rolling after.",
  earthworm: "A leaf I was finished casting from.",
  velvet_worm: "A cricket I was finished jetting for.",
  springtail: "A flake I was finished hopping for.",
  tardigrade: "A moss I was finished walking.",
  planarian: "A worm I was finished splitting after.",
  nematode: "A flake I was finished thrashing for.",
  amphipod: "A scrap I was finished taking on my side.",
  fiddler_crab: "An algae I was finished waving for.",
  ghost_crab: "A scrap I was finished running for.",
  limpet: "An algae I was finished clamping for.",
  barnacle: "A drift I was finished kicking for.",
  chiton: "An algae I was finished plating for.",
  periwinkle: "An algae I was finished rasping.",
  sand_dollar: "A diatom I was finished burying for.",
  sea_urchin: "A kelp I was finished walking for.",
  knobbed_whelk: "A clam I was finished hunting.",
  lugworm: "A silt I was finished heaping from.",
};
