import { LIVING_KINDS, type LivingKind } from "./living";

export function todaysVisitor(hostKey: string, now = new Date()): LivingKind {
  const day = Math.floor(Date.UTC(now.getFullYear(), now.getMonth(), now.getDate()) / 86400000);
  const others = LIVING_KINDS.filter((k) => k.key !== hostKey);
  return others[Math.abs(day + hostKey.length) % others.length]!;
}

const LINES: Record<string, string> = {
  red_panda: "I came for the ribbon. I'll put it back. Maybe.",
  cat: "I inspected the blotter. It will do.",
  dog: "I brought the whole tail. Then I took it home.",
  rabbit: "A short visit. The greens here are theoretical.",
  hamster: "I mapped the crumbs. Officially.",
  guinea_pig: "Wheek. That is the entire review.",
  turtle: "I arrived. I will leave in due course.",
  goldfish: "I drifted through. That counts.",
  budgie: "A note: your house is loud. I approve.",
  fox: "I found this desk first. Then I left it.",
  penguin: "A pebble of a visit.",
  parrot: "I came to quote the furniture.",
  ferret: "I borrowed a dongle. I'll return a better one.",
  hedgehog: "A quiet walk-through.",
  chinchilla: "The dust here is a scandal. I took a sample.",
  axolotl: "I grew a little more present. Then less.",
  toucan: "The bill approves of this blotter.",
  iguana: "I blinked at your lamp. Then I left.",
  dragon: "A courtesy inspection of the hoard.",
  phoenix: "I warmed the corner. You're welcome.",
  ball_python: "I came as a bun. I will leave as a bun.",
  corn_snake: "I threaded through. Your gap is fine.",
  kingsnake: "I inspected. You may keep the desk.",
  green_tree_python: "I hung on your lamp. Briefly.",
  hognose: "I died on your blotter. I got over it.",
  garter: "I patrolled. The moss is adequate.",
  boa: "I held the edge. Then I let go.",
  milk_snake: "I was a rumor. Then I was lunch-minded.",
  rosy_boa: "I borrowed the warm corner. I left it pink.",
  carpet_python: "I charted your shelf. You may land.",
  octopus: "I tasted the rim. Then I was a cup again.",
  cuttlefish: "I flushed. Then I left the weather.",
  nautilus: "I rose through. The house can wait.",
  moon_jelly: "I pulsed through. That counts.",
  sea_star: "I clung. Then I unclung. Slowly.",
  hermit_crab: "I measured the lids. None were free.",
  horseshoe_crab: "I walked the sand. I am not a crab.",
  seahorse: "I hitched your pencil. Briefly.",
  manta: "I soared the bowl. You may keep the sky.",
  moray: "I was the door. Then I was gone.",
  moss: "I carpeted. Then I was the page again.",
  maidenhair: "I unfurled. Then I folded.",
  ginkgo: "I golded. Then I left the autumn.",
  oak: "I dropped one. Then I was small again.",
  water_lily: "I opened. Then I closed.",
  orchid: "I bloomed. Then I was bark again.",
  saguaro: "I stored a visit. Then I sat.",
  venus_flytrap: "I did not snap. Then I left the cup.",
  pitcher: "I kept the well. Then I left the rain.",
  sundew: "I glittered. Then I uncurled.",
  honeybee: "I danced. Then I left the map.",
  monarch: "I kept the orange. Then I left the cup.",
  luna: "I drifted. I did not eat.",
  firefly: "I flashed. Then I left the grammar.",
  darner: "I hawed. Then I was air again.",
  stick: "I froze. Then I was a pencil again.",
  carpenter_ant: "I laid a road. Then I left the grain.",
  ladybird: "I counted. Then I left the seven.",
  mantis: "I folded. Then I left the stem.",
  cicada: "I sat. Then I left the years.",
  bumblebee: "I thrummed. Then I left the cup.",
  carpenter_bee: "I bored. Then I left the hole.",
  mason_bee: "I sealed. Then I left the stone.",
  leafcutter: "I cut. Then I left the disc.",
  stingless: "I potted. Then I left the wax.",
  sweat_bee: "I shone. Then I left the rim.",
  mining_bee: "I dug. Then I left the bank.",
  honey_drone: "I hummed. Then I left the dish.",
  honey_queen: "I stayed. Then I left the line.",
  honeycomb: "I sat. Then the line went quieter.",
  oyster: "I fruited. Then I left the wood.",
  fly_agaric: "I warned. Then I left the cup.",
  morel: "I sat hollow. Then I left the mold.",
  chanterelle: "I forked. Then I left the rim.",
  turkey_tail: "I zoned. Then I left the grain.",
  lions_mane: "I hung teeth. Then I left the wound.",
  puffball: "I puffed. Then I left the cloud.",
  chicken_of_woods: "I shelved. Then I left the oak.",
  yeast: "I rose. Then I left the crock.",
  lichen: "We sat. Then we left the share.",
  photovore: "I drank. Then I left the glass.",
  choir: "I sounded. Then I left the air.",
  nimbus: "I floated. Then I left the bowl.",
  silica: "I faceted. Then I left the stone.",
  terminator: "I kept the rim. Then I left the belt.",
  nexus: "We counted. Then we left the name.",
  halovore: "I frosted. Then I left the dish.",
  magneton: "I aligned. Then I left the line.",
  umbral: "I dimmed. Then I left the cool.",
  cyst: "I waited. Then I left the seal.",
  frog: "I jumped. Then I left the bank.",
  toad: "I hopped. Then I left the leaf.",
  newt: "I kept the orange. Then I left the moss.",
  salamander: "I hid. Then I left the mold.",
  caecilian: "I slipped. Then I left the silt.",
  crayfish: "I pinched. Then I left the pebble.",
  pond_snail: "I rasped. Then I left the rim.",
  mussel: "I filtered. Then I left the silt.",
  leech: "I latched. Then I left the damp.",
  stickleback: "I flared. Then I left the nest.",
  paramecium: "I rowed. Then I left the drop.",
  amoeba: "I reached. Then I left the film.",
  euglena: "I drank. Then I left the red.",
  volvox: "We rolled. Then we left the bowl.",
  diatom: "I glided. Then I left the pane.",
  kelp: "I held. Then I left the cold.",
  chlamydomonas: "I spun. Then I left the plate.",
  stentor: "I opened. Then I left the horn.",
  coli: "I tumbled. Then I left the broth.",
  haloarchaea: "I blushed. Then I left the pan.",
  crow: "I cawed. Then I left the ledge.",
  raven: "I croaked. Then I left the rafter.",
  barn_owl: "I hissed. Then I left the beam.",
  red_tail: "I soared. Then I left the post.",
  chickadee: "I deeed. Then I left the cup.",
  robin: "I hopped. Then I left the rim.",
  mallard: "I dabbled. Then I left the dish.",
  canada_goose: "I honked. Then I left the green.",
  pileated: "I drummed. Then I left the post.",
  hummingbird: "I hovered. Then I left the cup.",
  orb_weaver: "I sat. Then I left the web.",
  jumping_spider: "I leapt. Then I left the edge.",
  wolf_spider: "I prowled. Then I left the litter.",
  tarantula: "I sat. Then I left the silk.",
  widow: "I hung. Then I left the corner.",
  harvestman: "I walked. Then I left the stem.",
  scorpion: "I raised. Then I left the bark.",
  vinegaroon: "I whipped. Then I left the sand.",
  tick: "I clasped. Then I left the hem.",
  solifuge: "I ran. Then I left the dish.",
  deer: "I flagged. Then I left the edge.",
  bat: "I hung. Then I left the fold.",
  squirrel: "I hid a thought. Then I left the dish.",
  otter: "I slid. Then I left the dish.",
  raccoon: "I washed. Then I left the bowl.",
  skunk: "I stamped. Then I left the duff.",
  opossum: "I went still. Then I left the hem.",
  beaver: "I gnawed. Then I left the lodge.",
  porcupine: "I bristled. Then I left the post.",
  black_bear: "I foraged. Then I left the denside.",
  gecko: "I climbed. Then I left the plaster.",
  anole: "I flashed. Then I left the post.",
  skink: "I dashed. Then I left the crack.",
  chameleon: "I shifted. Then I left the perch.",
  horned_lizard: "I sat the crown. Then I left the sand.",
  alligator: "I sat the bank. Then I left the dish.",
  crocodile: "I showed. Then I left the dish.",
  snapper: "I snapped. Then I left the mud.",
  box_turtle: "I shut. Then I left the leaf.",
  tuatara: "I kept still. Then I left the burrow.",
  bass: "I lunged. Then I left the edge.",
  brook_trout: "I rose. Then I left the riffle.",
  catfish: "I whisked. Then I left the mud.",
  bluegill: "I flared. Then I left the shade.",
  perch: "I kept the bars. Then I left the rail.",
  pike: "I waited. Then I left the reed.",
  walleye: "I hunted dusk. Then I left the run.",
  paddlefish: "I filtered. Then I left the current.",
  lamprey: "I sat the disk. Then I left the stone.",
  american_eel: "I swam. Then I left the hole.",
};

export function visitLine(guestKey: string) {
  return LINES[guestKey] ?? "I came. I saw the lamp. I left.";
}
