# Replace every CHANGE_ME / empty crypto key before apply.
# The app fail-hard-starts if LICENSE / JWT / BUNDLE / ADMIN keys are
# missing, placeholder, or the wrong length. Do not commit real values.
apiVersion: v1
kind: Secret
metadata:
  name: computerpets-secrets
  namespace: computerpets
type: Opaque
stringData:
  LICENSE_SECRET_KEY: ""
  JWT_SECRET_KEY: ""
  BUNDLE_SIGNING_KEY: ""
  ADMIN_API_KEY: ""
  SPRING_DATASOURCE_USERNAME: computerpets
  SPRING_DATASOURCE_PASSWORD: CHANGE_ME
  POSTGRES_USER: computerpets
  POSTGRES_PASSWORD: CHANGE_ME
  POSTGRES_DB: computerpets
