from computerpets_client.ethogram import (
    SCRATCH_KEYS,
    TONGUE_KEYS,
    acts_for,
    pick_act,
)
from computerpets_client.species import BEE_KEYS, CANOPY_KEYS, CATALOG_KEYS, CORNER_KEYS, CREEK_KEYS, FAR_KEYS, FUNGI_KEYS, GARDEN_KEYS, INSECT_KEYS, LOG_KEYS, MEADOW_KEYS, POND_KEYS, REEF_KEYS, ROOST_KEYS, SEA_KEYS, SHORE_KEYS, SNAKE_KEYS, WELL_KEYS, WOOD_KEYS, STONE_KEYS


def test_every_catalog_kind_has_acts():
    for key in CATALOG_KEYS:
        assert acts_for(key), key


def test_snake_keys_never_schedule_scratch_and_can_schedule_tongue():
    assert tuple(TONGUE_KEYS) == SNAKE_KEYS
    for key in SNAKE_KEYS:
        names = [act["name"] for act in acts_for(key)]
        assert "tongue" in names, key
        assert "scratch" not in names, key
        assert "yawn" not in names, key
    tongue = 0
    for _ in range(80):
        act = pick_act("hognose")
        assert act is not None
        assert act["name"] != "scratch"
        if act["name"] == "tongue":
            tongue += 1
    assert tongue > 0


def test_only_scratching_mammals_scratch():
    assert SCRATCH_KEYS == ("dog", "cat", "red_panda")
    assert "scratch" not in [a["name"] for a in acts_for("goldfish")]
    assert "scratch" not in [a["name"] for a in acts_for("turtle")]
    for key in SEA_KEYS:
        names = [a["name"] for a in acts_for(key)]
        assert "scratch" not in names, key
        assert "tongue" not in names, key
    for key in GARDEN_KEYS:
        names = [a["name"] for a in acts_for(key)]
        assert "scratch" not in names, key
        assert "tongue" not in names, key
    for key in INSECT_KEYS:
        names = [a["name"] for a in acts_for(key)]
        assert "scratch" not in names, key
        assert "tongue" not in names, key
        assert "eat" not in names, key
    for key in BEE_KEYS:
        names = [a["name"] for a in acts_for(key)]
        assert "scratch" not in names, key
        assert "tongue" not in names, key
        assert "eat" not in names, key
        assert "waggle" not in names, key
    assert "tessera" in [a["name"] for a in acts_for("honeycomb")]
    assert "alveoli_soft" in [a["name"] for a in acts_for("honeycomb")]
    assert "foundation_soft" in [a["name"] for a in acts_for("honeycomb")]
    assert "freeze" in [a["name"] for a in acts_for("honeycomb")]
    assert "hold" not in [a["name"] for a in acts_for("honeycomb")]
    assert "brood" not in [a["name"] for a in acts_for("honeycomb")]
    assert "still" not in [a["name"] for a in acts_for("honeycomb")]
    assert "hum" in [a["name"] for a in acts_for("honey_drone")]
    assert "lay" in [a["name"] for a in acts_for("honey_queen")]
    assert "thrum" in [a["name"] for a in acts_for("bumblebee")]
    assert "hive" in [a["name"] for a in acts_for("honeybee")]
    assert "ocelli_soft" in [a["name"] for a in acts_for("honeybee")]
    assert "nasonov_soft" in [a["name"] for a in acts_for("honeybee")]
    assert "freeze" in [a["name"] for a in acts_for("honeybee")]
    assert "danaus" in [a["name"] for a in acts_for("monarch")]
    assert "cremaster_soft" in [a["name"] for a in acts_for("monarch")]
    assert "tarsus_soft" in [a["name"] for a in acts_for("monarch")]
    assert "freeze" in [a["name"] for a in acts_for("monarch")]
    assert "photinus" in [a["name"] for a in acts_for("firefly")]
    assert "photocyte_soft" in [a["name"] for a in acts_for("firefly")]
    assert "sternite_soft" in [a["name"] for a in acts_for("firefly")]
    assert "anax" in [a["name"] for a in acts_for("darner")]
    assert "obelisk_soft" in [a["name"] for a in acts_for("darner")]
    assert "ommatidia_soft" in [a["name"] for a in acts_for("darner")]
    assert "freeze" in [a["name"] for a in acts_for("darner")]
    assert "hawk" not in [a["name"] for a in acts_for("darner")]
    assert "still" not in [a["name"] for a in acts_for("darner")]
    assert "freeze" in [a["name"] for a in acts_for("firefly")]
    assert "flash" not in [a["name"] for a in acts_for("firefly")]
    assert "still" not in [a["name"] for a in acts_for("firefly")]
    assert "diapheromera" in [a["name"] for a in acts_for("stick")]
    assert "oviposit_soft" in [a["name"] for a in acts_for("stick")]
    assert "filiform_soft" in [a["name"] for a in acts_for("stick")]
    assert "freeze" in [a["name"] for a in acts_for("stick")]
    assert "still" not in [a["name"] for a in acts_for("stick")]
    assert "walk" not in [a["name"] for a in acts_for("stick")]
    assert "camponotus" in [a["name"] for a in acts_for("carpenter_ant")]
    assert "trophallaxis_soft" in [a["name"] for a in acts_for("carpenter_ant")]
    assert "frass_soft" in [a["name"] for a in acts_for("carpenter_ant")]
    assert "freeze" in [a["name"] for a in acts_for("carpenter_ant")]
    assert "still" not in [a["name"] for a in acts_for("carpenter_ant")]
    assert "trail" not in [a["name"] for a in acts_for("carpenter_ant")]
    assert "dart" not in [a["name"] for a in acts_for("carpenter_ant")]
    assert "coccinella" in [a["name"] for a in acts_for("ladybird")]
    assert "pronotum_soft" in [a["name"] for a in acts_for("ladybird")]
    assert "alar_soft" in [a["name"] for a in acts_for("ladybird")]
    assert "freeze" in [a["name"] for a in acts_for("ladybird")]
    assert "still" not in [a["name"] for a in acts_for("ladybird")]
    assert "count" not in [a["name"] for a in acts_for("ladybird")]
    assert "hunt" not in [a["name"] for a in acts_for("ladybird")]
    assert "mantodea" in [a["name"] for a in acts_for("mantis")]
    assert "ootheca_soft" in [a["name"] for a in acts_for("mantis")]
    assert "deimatic_soft" in [a["name"] for a in acts_for("mantis")]
    assert "freeze" in [a["name"] for a in acts_for("mantis")]
    assert "still" not in [a["name"] for a in acts_for("mantis")]
    assert "fold" not in [a["name"] for a in acts_for("mantis")]
    assert "strike" not in [a["name"] for a in acts_for("mantis")]
    assert "magicicada" in [a["name"] for a in acts_for("cicada")]
    assert "xylem_soft" in [a["name"] for a in acts_for("cicada")]
    assert "pharaoh_soft" in [a["name"] for a in acts_for("cicada")]
    assert "freeze" in [a["name"] for a in acts_for("cicada")]
    assert "still" not in [a["name"] for a in acts_for("cicada")]
    assert "emerge" not in [a["name"] for a in acts_for("cicada")]
    assert "burst" not in [a["name"] for a in acts_for("cicada")]
    assert "actias" in [a["name"] for a in acts_for("luna")]
    assert "aphagy_soft" in [a["name"] for a in acts_for("luna")]
    assert "cauda_soft" in [a["name"] for a in acts_for("luna")]
    assert "freeze" in [a["name"] for a in acts_for("luna")]
    assert "still" not in [a["name"] for a in acts_for("luna")]
    assert "poise" in [a["name"] for a in acts_for("venus_flytrap")]
    assert "cage_soft" in [a["name"] for a in acts_for("venus_flytrap")]
    assert "scape_soft" in [a["name"] for a in acts_for("venus_flytrap")]
    assert "freeze" in [a["name"] for a in acts_for("venus_flytrap")]
    assert "urn" in [a["name"] for a in acts_for("pitcher")]
    assert "ala_soft" in [a["name"] for a in acts_for("pitcher")]
    assert "baffle_soft" in [a["name"] for a in acts_for("pitcher")]
    assert "freeze" in [a["name"] for a in acts_for("pitcher")]
    assert "rosette" in [a["name"] for a in acts_for("sundew")]
    assert "lamina_soft" in [a["name"] for a in acts_for("sundew")]
    assert "circinate_soft" in [a["name"] for a in acts_for("sundew")]
    assert "freeze" in [a["name"] for a in acts_for("sundew")]
    for key in FUNGI_KEYS:
        names = [a["name"] for a in acts_for(key)]
        assert "scratch" not in names, key
        assert "tongue" not in names, key
        assert "waggle" not in names, key
        assert "yawn" not in names, key
    assert "lycoperdon" in [a["name"] for a in acts_for("puffball")]
    assert "gemmate_soft" in [a["name"] for a in acts_for("puffball")]
    assert "capillitium_soft" in [a["name"] for a in acts_for("puffball")]
    assert "freeze" in [a["name"] for a in acts_for("puffball")]
    assert "puff" not in [a["name"] for a in acts_for("puffball")]
    assert "lean" not in [a["name"] for a in acts_for("puffball")]
    assert "still" not in [a["name"] for a in acts_for("puffball")]
    assert "laetiporus" in [a["name"] for a in acts_for("chicken_of_woods")]
    assert "poroid_soft" in [a["name"] for a in acts_for("chicken_of_woods")]
    assert "cluster_soft" in [a["name"] for a in acts_for("chicken_of_woods")]
    assert "freeze" in [a["name"] for a in acts_for("chicken_of_woods")]
    assert "lean" not in [a["name"] for a in acts_for("chicken_of_woods")]
    assert "flush" not in [a["name"] for a in acts_for("chicken_of_woods")]
    assert "still" not in [a["name"] for a in acts_for("chicken_of_woods")]
    assert "saccharomyces" in [a["name"] for a in acts_for("yeast")]
    assert "ascus_soft" in [a["name"] for a in acts_for("yeast")]
    assert "floc_soft" in [a["name"] for a in acts_for("yeast")]
    assert "freeze" in [a["name"] for a in acts_for("yeast")]
    assert "rise" not in [a["name"] for a in acts_for("yeast")]
    assert "foam" not in [a["name"] for a in acts_for("yeast")]
    assert "still" not in [a["name"] for a in acts_for("yeast")]
    assert "saccharomyces" in [a["name"] for a in acts_for("yeast")]
    assert "cladonia" in [a["name"] for a in acts_for("lichen")]
    assert "soredia_soft" in [a["name"] for a in acts_for("lichen")]
    assert "scyphi_soft" in [a["name"] for a in acts_for("lichen")]
    assert "freeze" in [a["name"] for a in acts_for("lichen")]
    assert "share-still" not in [a["name"] for a in acts_for("lichen")]
    assert "lean" not in [a["name"] for a in acts_for("lichen")]
    assert "still" not in [a["name"] for a in acts_for("lichen")]
    assert "pleurotus" in [a["name"] for a in acts_for("oyster")]
    assert "sporulate_soft" in [a["name"] for a in acts_for("oyster")]
    assert "hypha_soft" in [a["name"] for a in acts_for("oyster")]
    assert "freeze" in [a["name"] for a in acts_for("oyster")]
    assert "lean" not in [a["name"] for a in acts_for("oyster")]
    assert "flush" not in [a["name"] for a in acts_for("oyster")]
    assert "still" not in [a["name"] for a in acts_for("oyster")]
    assert "amanita" in [a["name"] for a in acts_for("fly_agaric")]
    assert "pileus_soft" in [a["name"] for a in acts_for("fly_agaric")]
    assert "bulb_soft" in [a["name"] for a in acts_for("fly_agaric")]
    assert "freeze" in [a["name"] for a in acts_for("fly_agaric")]
    assert "lean" not in [a["name"] for a in acts_for("fly_agaric")]
    assert "flush" not in [a["name"] for a in acts_for("fly_agaric")]
    assert "still" not in [a["name"] for a in acts_for("fly_agaric")]
    assert "morchella" in [a["name"] for a in acts_for("morel")]
    assert "costa_soft" in [a["name"] for a in acts_for("morel")]
    assert "hymenium_soft" in [a["name"] for a in acts_for("morel")]
    assert "freeze" in [a["name"] for a in acts_for("morel")]
    assert "lean" not in [a["name"] for a in acts_for("morel")]
    assert "still_hold" not in [a["name"] for a in acts_for("morel")]
    assert "still" not in [a["name"] for a in acts_for("morel")]
    assert "cantharellus" in [a["name"] for a in acts_for("chanterelle")]
    assert "vase_soft" in [a["name"] for a in acts_for("chanterelle")]
    assert "plica_soft" in [a["name"] for a in acts_for("chanterelle")]
    assert "freeze" in [a["name"] for a in acts_for("chanterelle")]
    assert "lean" not in [a["name"] for a in acts_for("chanterelle")]
    assert "flush" not in [a["name"] for a in acts_for("chanterelle")]
    assert "still" not in [a["name"] for a in acts_for("chanterelle")]
    assert "trametes" in [a["name"] for a in acts_for("turkey_tail")]
    assert "concentric_soft" in [a["name"] for a in acts_for("turkey_tail")]
    assert "tomentum_soft" in [a["name"] for a in acts_for("turkey_tail")]
    assert "freeze" in [a["name"] for a in acts_for("turkey_tail")]
    assert "lean" not in [a["name"] for a in acts_for("turkey_tail")]
    assert "zone" not in [a["name"] for a in acts_for("turkey_tail")]
    assert "still" not in [a["name"] for a in acts_for("turkey_tail")]
    assert "hericium" in [a["name"] for a in acts_for("lions_mane")]
    assert "pompon_soft" in [a["name"] for a in acts_for("lions_mane")]
    assert "hydnoid_soft" in [a["name"] for a in acts_for("lions_mane")]
    assert "freeze" in [a["name"] for a in acts_for("lions_mane")]
    assert "lean" not in [a["name"] for a in acts_for("lions_mane")]
    assert "beard" not in [a["name"] for a in acts_for("lions_mane")]
    assert "still" not in [a["name"] for a in acts_for("lions_mane")]
    for key in FAR_KEYS:
        names = [a["name"] for a in acts_for(key)]
        assert "scratch" not in names, key
        assert "tongue" not in names, key
    assert "photovore" in [a["name"] for a in acts_for("photovore")]
    assert "opsin_soft" in [a["name"] for a in acts_for("photovore")]
    assert "iridophore_soft" in [a["name"] for a in acts_for("photovore")]
    assert "freeze" in [a["name"] for a in acts_for("photovore")]
    assert "drink-light" not in [a["name"] for a in acts_for("photovore")]
    assert "hover" not in [a["name"] for a in acts_for("photovore")]
    assert "still" not in [a["name"] for a in acts_for("photovore")]
    assert "harmonia" in [a["name"] for a in acts_for("choir")]
    assert "formant_soft" in [a["name"] for a in acts_for("choir")]
    assert "dyad_soft" in [a["name"] for a in acts_for("choir")]
    assert "freeze" in [a["name"] for a in acts_for("choir")]
    assert "chord-pulse" not in [a["name"] for a in acts_for("choir")]
    assert "stratus" in [a["name"] for a in acts_for("nimbus")]
    assert "tholin_soft" in [a["name"] for a in acts_for("nimbus")]
    assert "nucleate_soft" in [a["name"] for a in acts_for("nimbus")]
    assert "freeze" in [a["name"] for a in acts_for("nimbus")]
    assert "float" not in [a["name"] for a in acts_for("nimbus")]
    assert "still" not in [a["name"] for a in acts_for("nimbus")]
    assert "hover" not in [a["name"] for a in acts_for("nimbus")]
    assert "crescit" in [a["name"] for a in acts_for("silica")]
    assert "hopper_soft" in [a["name"] for a in acts_for("silica")]
    assert "phantom_soft" in [a["name"] for a in acts_for("silica")]
    assert "freeze" in [a["name"] for a in acts_for("silica")]
    assert "facet" not in [a["name"] for a in acts_for("silica")]
    assert "still" not in [a["name"] for a in acts_for("silica")]
    assert "shed" not in [a["name"] for a in acts_for("silica")]
    assert "limitor" in [a["name"] for a in acts_for("terminator")]
    assert "umbra_soft" in [a["name"] for a in acts_for("terminator")]
    assert "syzygy_soft" in [a["name"] for a in acts_for("terminator")]
    assert "freeze" in [a["name"] for a in acts_for("terminator")]
    assert "edge-walk" not in [a["name"] for a in acts_for("terminator")]
    assert "still" not in [a["name"] for a in acts_for("terminator")]
    assert "rim" not in [a["name"] for a in acts_for("terminator")]
    assert "mesh" in [a["name"] for a in acts_for("nexus")]
    assert "fascicle_soft" in [a["name"] for a in acts_for("nexus")]
    assert "sennit_soft" in [a["name"] for a in acts_for("nexus")]
    assert "freeze" in [a["name"] for a in acts_for("nexus")]
    assert "count-ripple" not in [a["name"] for a in acts_for("nexus")]
    assert "still" not in [a["name"] for a in acts_for("nexus")]
    assert "name" not in [a["name"] for a in acts_for("nexus")]
    assert "deliquesce" in [a["name"] for a in acts_for("halovore")]
    assert "ectoine_soft" in [a["name"] for a in acts_for("halovore")]
    assert "sabkha_soft" in [a["name"] for a in acts_for("halovore")]
    assert "freeze" in [a["name"] for a in acts_for("halovore")]
    assert "frost" not in [a["name"] for a in acts_for("halovore")]
    assert "still" not in [a["name"] for a in acts_for("halovore")]
    assert "waste" not in [a["name"] for a in acts_for("halovore")]
    assert "remanence" in [a["name"] for a in acts_for("magneton")]
    assert "barkhausen_soft" in [a["name"] for a in acts_for("magneton")]
    assert "hysteresis_soft" in [a["name"] for a in acts_for("magneton")]
    assert "freeze" in [a["name"] for a in acts_for("magneton")]
    assert "align" not in [a["name"] for a in acts_for("magneton")]
    assert "still" not in [a["name"] for a in acts_for("magneton")]
    assert "north" not in [a["name"] for a in acts_for("magneton")]
    assert "caligo" in [a["name"] for a in acts_for("umbral")]
    assert "sfumato_soft" in [a["name"] for a in acts_for("umbral")]
    assert "tenebrae_soft" in [a["name"] for a in acts_for("umbral")]
    assert "freeze" in [a["name"] for a in acts_for("umbral")]
    assert "dim" not in [a["name"] for a in acts_for("umbral")]
    assert "still" not in [a["name"] for a in acts_for("umbral")]
    assert "cool" not in [a["name"] for a in acts_for("umbral")]
    assert "cryptobiosis" in [a["name"] for a in acts_for("cyst")]
    assert "sporocyst_soft" in [a["name"] for a in acts_for("cyst")]
    assert "tachyzoite_soft" in [a["name"] for a in acts_for("cyst")]
    assert "freeze" in [a["name"] for a in acts_for("cyst")]
    assert "wake" not in [a["name"] for a in acts_for("cyst")]
    assert "wait" not in [a["name"] for a in acts_for("cyst")]
    assert "still" not in [a["name"] for a in acts_for("cyst")]
    for key in POND_KEYS:
        names = [a["name"] for a in acts_for(key)]
        assert "scratch" not in names, key
        assert "tongue" not in names, key
    assert "lentic" in [a["name"] for a in acts_for("frog")]
    assert "toepad_soft" in [a["name"] for a in acts_for("frog")]
    assert "webbing_soft" in [a["name"] for a in acts_for("frog")]
    assert "freeze" in [a["name"] for a in acts_for("frog")]
    assert "bufonid" in [a["name"] for a in acts_for("toad")]
    assert "unken_soft" in [a["name"] for a in acts_for("toad")]
    assert "cranial_soft" in [a["name"] for a in acts_for("toad")]
    assert "freeze" in [a["name"] for a in acts_for("toad")]
    assert "caudate" in [a["name"] for a in acts_for("newt")]
    assert "hedonic_soft" in [a["name"] for a in acts_for("newt")]
    assert "aposematic_soft" in [a["name"] for a in acts_for("newt")]
    assert "freeze" in [a["name"] for a in acts_for("newt")]
    assert "ambystomid" in [a["name"] for a in acts_for("salamander")]
    assert "mental_soft" in [a["name"] for a in acts_for("salamander")]
    assert "granular_soft" in [a["name"] for a in acts_for("salamander")]
    assert "freeze" in [a["name"] for a in acts_for("salamander")]
    assert "gymnophion" in [a["name"] for a in acts_for("caecilian")]
    assert "stegos_soft" in [a["name"] for a in acts_for("caecilian")]
    assert "dualjaw_soft" in [a["name"] for a in acts_for("caecilian")]
    assert "freeze" in [a["name"] for a in acts_for("caecilian")]
    assert "astacid" in [a["name"] for a in acts_for("crayfish")]
    assert "scaph_soft" in [a["name"] for a in acts_for("crayfish")]
    assert "meral_soft" in [a["name"] for a in acts_for("crayfish")]
    assert "freeze" in [a["name"] for a in acts_for("crayfish")]
    assert "lymnaeid" in [a["name"] for a in acts_for("pond_snail")]
    assert "odontophore_soft" in [a["name"] for a in acts_for("pond_snail")]
    assert "neuston_soft" in [a["name"] for a in acts_for("pond_snail")]
    assert "freeze" in [a["name"] for a in acts_for("pond_snail")]
    assert "unionid" in [a["name"] for a in acts_for("mussel")]
    assert "ligament_soft" in [a["name"] for a in acts_for("mussel")]
    assert "glochid_soft" in [a["name"] for a in acts_for("mussel")]
    assert "freeze" in [a["name"] for a in acts_for("mussel")]
    assert "hirudinean" in [a["name"] for a in acts_for("leech")]
    assert "botryoidal_soft" in [a["name"] for a in acts_for("leech")]
    assert "auricle_soft" in [a["name"] for a in acts_for("leech")]
    assert "freeze" in [a["name"] for a in acts_for("leech")]
    assert "gasterosteid" in [a["name"] for a in acts_for("stickleback")]
    assert "nuptial_soft" in [a["name"] for a in acts_for("stickleback")]
    assert "pelvic_soft" in [a["name"] for a in acts_for("stickleback")]
    assert "freeze" in [a["name"] for a in acts_for("stickleback")]
    for key in WELL_KEYS:
        names = [a["name"] for a in acts_for(key)]
        assert "scratch" not in names, key
        assert "tongue" not in names, key
    assert "ciliophora" in [a["name"] for a in acts_for("paramecium")]
    assert "trichocyst_soft" in [a["name"] for a in acts_for("paramecium")]
    assert "avoiding_soft" in [a["name"] for a in acts_for("paramecium")]
    assert "freeze" in [a["name"] for a in acts_for("paramecium")]
    assert "proteus" in [a["name"] for a in acts_for("amoeba")]
    assert "uroid_soft" in [a["name"] for a in acts_for("amoeba")]
    assert "streaming_soft" in [a["name"] for a in acts_for("amoeba")]
    assert "freeze" in [a["name"] for a in acts_for("amoeba")]
    assert "euglenid" in [a["name"] for a in acts_for("euglena")]
    assert "metaboly_soft" in [a["name"] for a in acts_for("euglena")]
    assert "paramylon_soft" in [a["name"] for a in acts_for("euglena")]
    assert "freeze" in [a["name"] for a in acts_for("euglena")]
    assert "coenobium" in [a["name"] for a in acts_for("volvox")]
    assert "daughter_soft" in [a["name"] for a in acts_for("volvox")]
    assert "gonidia_soft" in [a["name"] for a in acts_for("volvox")]
    assert "freeze" in [a["name"] for a in acts_for("volvox")]
    assert "navicula" in [a["name"] for a in acts_for("diatom")]
    assert "pennate_soft" in [a["name"] for a in acts_for("diatom")]
    assert "epitheca_soft" in [a["name"] for a in acts_for("diatom")]
    assert "freeze" in [a["name"] for a in acts_for("diatom")]
    assert "meristem" in [a["name"] for a in acts_for("kelp")]
    assert "sorus_soft" in [a["name"] for a in acts_for("kelp")]
    assert "sporophyll_soft" in [a["name"] for a in acts_for("kelp")]
    assert "freeze" in [a["name"] for a in acts_for("kelp")]
    assert "palmella" in [a["name"] for a in acts_for("chlamydomonas")]
    assert "cellwall_soft" in [a["name"] for a in acts_for("chlamydomonas")]
    assert "wetplate_soft" in [a["name"] for a in acts_for("chlamydomonas")]
    assert "freeze" in [a["name"] for a in acts_for("chlamydomonas")]
    assert "introversus" in [a["name"] for a in acts_for("stentor")]
    assert "vortex_soft" in [a["name"] for a in acts_for("stentor")]
    assert "beadedmac_soft" in [a["name"] for a in acts_for("stentor")]
    assert "freeze" in [a["name"] for a in acts_for("stentor")]
    assert "nucleoid" in [a["name"] for a in acts_for("coli")]
    assert "fimbria_soft" in [a["name"] for a in acts_for("coli")]
    assert "flagmotor_soft" in [a["name"] for a in acts_for("coli")]
    assert "freeze" in [a["name"] for a in acts_for("coli")]
    assert "retinal" in [a["name"] for a in acts_for("haloarchaea")]
    assert "archaellum_soft" in [a["name"] for a in acts_for("haloarchaea")]
    assert "brinedrift_soft" in [a["name"] for a in acts_for("haloarchaea")]
    assert "freeze" in [a["name"] for a in acts_for("haloarchaea")]
    for key in ROOST_KEYS:
        names = [a["name"] for a in acts_for(key)]
        assert "scratch" not in names, key
        assert "tongue" not in names, key
    assert "caw" in [a["name"] for a in acts_for("crow")]
    assert "cock_look" in [a["name"] for a in acts_for("crow")]
    assert "perch" in [a["name"] for a in acts_for("crow")]
    assert "kronk" in [a["name"] for a in acts_for("raven")]
    assert "ruff_flare" in [a["name"] for a in acts_for("raven")]
    assert "perch" in [a["name"] for a in acts_for("raven")]
    assert "hiss" in [a["name"] for a in acts_for("barn_owl")]
    assert "disk_listen" in [a["name"] for a in acts_for("barn_owl")]
    assert "perch" in [a["name"] for a in acts_for("barn_owl")]
    assert "soar" in [a["name"] for a in acts_for("red_tail")]
    assert "dee" in [a["name"] for a in acts_for("chickadee")]
    assert "fee_bee" in [a["name"] for a in acts_for("chickadee")]
    assert "perch" in [a["name"] for a in acts_for("chickadee")]
    assert "hop" in [a["name"] for a in acts_for("robin")]
    assert "carol_soft" in [a["name"] for a in acts_for("robin")]
    assert "perch" in [a["name"] for a in acts_for("robin")]
    assert "dabble" in [a["name"] for a in acts_for("mallard")]
    assert "quack_soft" in [a["name"] for a in acts_for("mallard")]
    assert "loaf" in [a["name"] for a in acts_for("mallard")]
    assert "honk" in [a["name"] for a in acts_for("canada_goose")]
    assert "graze_soft" in [a["name"] for a in acts_for("canada_goose")]
    assert "loaf" in [a["name"] for a in acts_for("canada_goose")]
    assert "drum" in [a["name"] for a in acts_for("pileated")]
    assert "excavate_soft" in [a["name"] for a in acts_for("pileated")]
    assert "loaf" in [a["name"] for a in acts_for("pileated")]
    assert "hover" in [a["name"] for a in acts_for("hummingbird")]
    assert "chip_soft" in [a["name"] for a in acts_for("hummingbird")]
    assert "perch" in [a["name"] for a in acts_for("hummingbird")]
    assert "preen" in [a["name"] for a in acts_for("budgie")]
    assert "beakgrind_soft" in [a["name"] for a in acts_for("budgie")]
    assert "loaf" in [a["name"] for a in acts_for("budgie")]
    assert "huddle" in [a["name"] for a in acts_for("penguin")]
    assert "rockhop_soft" in [a["name"] for a in acts_for("penguin")]
    assert "loaf" in [a["name"] for a in acts_for("penguin")]
    assert "quote" in [a["name"] for a in acts_for("parrot")]
    assert "pineye_soft" in [a["name"] for a in acts_for("parrot")]
    assert "loaf" in [a["name"] for a in acts_for("parrot")]
    assert "roost" in [a["name"] for a in acts_for("toucan")]
    assert "rattle_soft" in [a["name"] for a in acts_for("toucan")]
    assert "loaf" in [a["name"] for a in acts_for("toucan")]
    assert "cinder" in [a["name"] for a in acts_for("phoenix")]
    assert "reignite_soft" in [a["name"] for a in acts_for("phoenix")]
    assert "loaf" in [a["name"] for a in acts_for("phoenix")]
    assert "loaf" in [a["name"] for a in acts_for("cat")]
    assert "bunting_soft" in [a["name"] for a in acts_for("cat")]
    assert "mlem_soft" in [a["name"] for a in acts_for("cat")]
    assert "alert" in [a["name"] for a in acts_for("cat")]
    assert "wait" in [a["name"] for a in acts_for("dog")]
    assert "beg_soft" in [a["name"] for a in acts_for("dog")]
    assert "pant_soft" in [a["name"] for a in acts_for("dog")]
    assert "scratch" in [a["name"] for a in acts_for("dog")]
    assert "flop" in [a["name"] for a in acts_for("rabbit")]
    assert "rub_soft" in [a["name"] for a in acts_for("rabbit")]
    assert "nosh_soft" in [a["name"] for a in acts_for("rabbit")]
    assert "freeze" in [a["name"] for a in acts_for("rabbit")]
    assert "nest" in [a["name"] for a in acts_for("hamster")]
    assert "scrub_soft" in [a["name"] for a in acts_for("hamster")]
    assert "seed_soft" in [a["name"] for a in acts_for("hamster")]
    assert "freeze" in [a["name"] for a in acts_for("hamster")]
    assert "potato" in [a["name"] for a in acts_for("guinea_pig")]
    assert "lookout_soft" in [a["name"] for a in acts_for("guinea_pig")]
    assert "teeth_soft" in [a["name"] for a in acts_for("guinea_pig")]
    assert "freeze" in [a["name"] for a in acts_for("guinea_pig")]
    assert "soak" in [a["name"] for a in acts_for("turtle")]
    assert "snorkel_soft" in [a["name"] for a in acts_for("turtle")]
    assert "wipe_soft" in [a["name"] for a in acts_for("turtle")]
    assert "freeze" in [a["name"] for a in acts_for("turtle")]
    assert "drift" in [a["name"] for a in acts_for("goldfish")]
    assert "yawn_soft" in [a["name"] for a in acts_for("goldfish")]
    assert "forage_soft" in [a["name"] for a in acts_for("goldfish")]
    assert "freeze" in [a["name"] for a in acts_for("goldfish")]
    assert "den" in [a["name"] for a in acts_for("fox")]
    assert "cock_soft" in [a["name"] for a in acts_for("fox")]
    assert "stash_soft" in [a["name"] for a in acts_for("fox")]
    assert "freeze" in [a["name"] for a in acts_for("fox")]
    assert "tube" in [a["name"] for a in acts_for("ferret")]
    assert "corkscrew_soft" in [a["name"] for a in acts_for("ferret")]
    assert "slink_soft" in [a["name"] for a in acts_for("ferret")]
    assert "freeze" in [a["name"] for a in acts_for("ferret")]
    assert "curl" in [a["name"] for a in acts_for("hedgehog")]
    assert "trundle_soft" in [a["name"] for a in acts_for("hedgehog")]
    assert "wheel_soft" in [a["name"] for a in acts_for("hedgehog")]
    assert "freeze" in [a["name"] for a in acts_for("hedgehog")]
    assert "ash" in [a["name"] for a in acts_for("chinchilla")]
    assert "ricochet_soft" in [a["name"] for a in acts_for("chinchilla")]
    assert "gnaw_soft" in [a["name"] for a in acts_for("chinchilla")]
    assert "freeze" in [a["name"] for a in acts_for("chinchilla")]
    assert "gill" in [a["name"] for a in acts_for("axolotl")]
    assert "sprout_soft" in [a["name"] for a in acts_for("axolotl")]
    assert "glop_soft" in [a["name"] for a in acts_for("axolotl")]
    assert "freeze" in [a["name"] for a in acts_for("axolotl")]
    assert "sun" in [a["name"] for a in acts_for("iguana")]
    assert "sneeze_soft" in [a["name"] for a in acts_for("iguana")]
    assert "lash_soft" in [a["name"] for a in acts_for("iguana")]
    assert "freeze" in [a["name"] for a in acts_for("iguana")]
    assert "sprawl" in [a["name"] for a in acts_for("dragon")]
    assert "ruff_soft" in [a["name"] for a in acts_for("dragon")]
    assert "scrape_soft" in [a["name"] for a in acts_for("dragon")]
    assert "freeze" in [a["name"] for a in acts_for("dragon")]
    assert "tongue" in [a["name"] for a in acts_for("ball_python")]
    assert "orb" in [a["name"] for a in acts_for("ball_python")]
    assert "loom_soft" in [a["name"] for a in acts_for("ball_python")]
    assert "weave_soft" in [a["name"] for a in acts_for("ball_python")]
    assert "freeze" in [a["name"] for a in acts_for("ball_python")]
    assert "tongue" in [a["name"] for a in acts_for("corn_snake")]
    assert "comma" in [a["name"] for a in acts_for("corn_snake")]
    assert "blotter_soft" in [a["name"] for a in acts_for("corn_snake")]
    assert "pencil_soft" in [a["name"] for a in acts_for("corn_snake")]
    assert "freeze" in [a["name"] for a in acts_for("corn_snake")]
    assert "tongue" in [a["name"] for a in acts_for("kingsnake")]
    assert "verdict" in [a["name"] for a in acts_for("kingsnake")]
    assert "band_soft" in [a["name"] for a in acts_for("kingsnake")]
    assert "drawer_soft" in [a["name"] for a in acts_for("kingsnake")]
    assert "freeze" in [a["name"] for a in acts_for("kingsnake")]
    assert "inspect" not in [a["name"] for a in acts_for("kingsnake")]
    assert "tongue" in [a["name"] for a in acts_for("green_tree_python")]
    assert "bracelet" in [a["name"] for a in acts_for("green_tree_python")]
    assert "liana_soft" in [a["name"] for a in acts_for("green_tree_python")]
    assert "arbor_soft" in [a["name"] for a in acts_for("green_tree_python")]
    assert "freeze" in [a["name"] for a in acts_for("green_tree_python")]
    assert "drape" not in [a["name"] for a in acts_for("green_tree_python")]
    assert "tongue" in [a["name"] for a in acts_for("hognose")]
    assert "flatten" in [a["name"] for a in acts_for("hognose")]
    assert "quiver_soft" in [a["name"] for a in acts_for("hognose")]
    assert "upright_soft" in [a["name"] for a in acts_for("hognose")]
    assert "freeze" in [a["name"] for a in acts_for("hognose")]
    assert "flip" not in [a["name"] for a in acts_for("hognose")]
    assert "tongue" in [a["name"] for a in acts_for("garter")]
    assert "seam" in [a["name"] for a in acts_for("garter")]
    assert "ribbon_soft" in [a["name"] for a in acts_for("garter")]
    assert "creek_soft" in [a["name"] for a in acts_for("garter")]
    assert "freeze" in [a["name"] for a in acts_for("garter")]
    assert "patrol" not in [a["name"] for a in acts_for("garter")]
    assert "dart" not in [a["name"] for a in acts_for("garter")]
    assert "tongue" in [a["name"] for a in acts_for("boa")]
    assert "hold" in [a["name"] for a in acts_for("boa")]
    assert "anchor_soft" in [a["name"] for a in acts_for("boa")]
    assert "meander_soft" in [a["name"] for a in acts_for("boa")]
    assert "freeze" in [a["name"] for a in acts_for("boa")]
    assert "loop" not in [a["name"] for a in acts_for("boa")]
    assert "coil" not in [a["name"] for a in acts_for("boa")]
    assert "tongue" in [a["name"] for a in acts_for("milk_snake")]
    assert "rhyme" in [a["name"] for a in acts_for("milk_snake")]
    assert "cipher_soft" in [a["name"] for a in acts_for("milk_snake")]
    assert "verse_soft" in [a["name"] for a in acts_for("milk_snake")]
    assert "freeze" in [a["name"] for a in acts_for("milk_snake")]
    assert "mosaic" not in [a["name"] for a in acts_for("milk_snake")]
    assert "mimic" not in [a["name"] for a in acts_for("milk_snake")]
    assert "tongue" in [a["name"] for a in acts_for("rosy_boa")]
    assert "pebble" in [a["name"] for a in acts_for("rosy_boa")]
    assert "dune_soft" in [a["name"] for a in acts_for("rosy_boa")]
    assert "talus_soft" in [a["name"] for a in acts_for("rosy_boa")]
    assert "freeze" in [a["name"] for a in acts_for("rosy_boa")]
    assert "stone" not in [a["name"] for a in acts_for("rosy_boa")]
    assert "nest" not in [a["name"] for a in acts_for("rosy_boa")]
    assert "tongue" in [a["name"] for a in acts_for("carpet_python")]
    assert "legend" in [a["name"] for a in acts_for("carpet_python")]
    assert "canopy_soft" in [a["name"] for a in acts_for("carpet_python")]
    assert "inset_soft" in [a["name"] for a in acts_for("carpet_python")]
    assert "freeze" in [a["name"] for a in acts_for("carpet_python")]
    assert "chart" not in [a["name"] for a in acts_for("carpet_python")]
    assert "drape" not in [a["name"] for a in acts_for("carpet_python")]
    assert "hide" in [a["name"] for a in acts_for("octopus")]
    assert "papilla_soft" in [a["name"] for a in acts_for("octopus")]
    assert "ooze_soft" in [a["name"] for a in acts_for("octopus")]
    assert "freeze" in [a["name"] for a in acts_for("octopus")]
    assert "lid" not in [a["name"] for a in acts_for("octopus")]
    assert "flush" not in [a["name"] for a in acts_for("octopus")]
    assert "hide" in [a["name"] for a in acts_for("cuttlefish")]
    assert "strike_soft" in [a["name"] for a in acts_for("cuttlefish")]
    assert "zebra_soft" in [a["name"] for a in acts_for("cuttlefish")]
    assert "freeze" in [a["name"] for a in acts_for("cuttlefish")]
    assert "flush" not in [a["name"] for a in acts_for("cuttlefish")]
    assert "lid" not in [a["name"] for a in acts_for("cuttlefish")]
    assert "hide" in [a["name"] for a in acts_for("nautilus")]
    assert "hyponome_soft" in [a["name"] for a in acts_for("nautilus")]
    assert "aperture_soft" in [a["name"] for a in acts_for("nautilus")]
    assert "freeze" in [a["name"] for a in acts_for("nautilus")]
    assert "rise" not in [a["name"] for a in acts_for("nautilus")]
    assert "flush" not in [a["name"] for a in acts_for("nautilus")]
    assert "hide" in [a["name"] for a in acts_for("moon_jelly")]
    assert "rhopalium_soft" in [a["name"] for a in acts_for("moon_jelly")]
    assert "horseshoe_soft" in [a["name"] for a in acts_for("moon_jelly")]
    assert "freeze" in [a["name"] for a in acts_for("moon_jelly")]
    assert "chime" not in [a["name"] for a in acts_for("moon_jelly")]
    assert "pulse" not in [a["name"] for a in acts_for("moon_jelly")]
    assert "drift" not in [a["name"] for a in acts_for("moon_jelly")]
    assert "cling" in [a["name"] for a in acts_for("sea_star")]
    assert "madre_soft" in [a["name"] for a in acts_for("sea_star")]
    assert "papula_soft" in [a["name"] for a in acts_for("sea_star")]
    assert "freeze" in [a["name"] for a in acts_for("sea_star")]
    assert "reef" not in [a["name"] for a in acts_for("sea_star")]
    assert "still" not in [a["name"] for a in acts_for("sea_star")]
    assert "bell" not in [a["name"] for a in acts_for("sea_star")]
    assert "withdraw" in [a["name"] for a in acts_for("hermit_crab")]
    assert "chela_soft" in [a["name"] for a in acts_for("hermit_crab")]
    assert "bailer_soft" in [a["name"] for a in acts_for("hermit_crab")]
    assert "freeze" in [a["name"] for a in acts_for("hermit_crab")]
    assert "inspect" not in [a["name"] for a in acts_for("hermit_crab")]
    assert "shuffle" not in [a["name"] for a in acts_for("hermit_crab")]
    assert "knob" not in [a["name"] for a in acts_for("hermit_crab")]
    assert "carapace" in [a["name"] for a in acts_for("horseshoe_crab")]
    assert "pusher_soft" in [a["name"] for a in acts_for("horseshoe_crab")]
    assert "ocular_soft" in [a["name"] for a in acts_for("horseshoe_crab")]
    assert "freeze" in [a["name"] for a in acts_for("horseshoe_crab")]
    assert "plow" not in [a["name"] for a in acts_for("horseshoe_crab")]
    assert "still" not in [a["name"] for a in acts_for("horseshoe_crab")]
    assert "molt" not in [a["name"] for a in acts_for("horseshoe_crab")]
    assert "coil" in [a["name"] for a in acts_for("seahorse")]
    assert "dorsal_soft" in [a["name"] for a in acts_for("seahorse")]
    assert "pectoral_soft" in [a["name"] for a in acts_for("seahorse")]
    assert "freeze" in [a["name"] for a in acts_for("seahorse")]
    assert "hitch" not in [a["name"] for a in acts_for("seahorse")]
    assert "hover" not in [a["name"] for a in acts_for("seahorse")]
    assert "anchor" not in [a["name"] for a in acts_for("seahorse")]
    assert "span" in [a["name"] for a in acts_for("manta")]
    assert "breach_soft" in [a["name"] for a in acts_for("manta")]
    assert "ram_soft" in [a["name"] for a in acts_for("manta")]
    assert "freeze" in [a["name"] for a in acts_for("manta")]
    assert "soar" not in [a["name"] for a in acts_for("manta")]
    assert "glide" not in [a["name"] for a in acts_for("manta")]
    assert "barrel" not in [a["name"] for a in acts_for("manta")]
    assert "jamb" in [a["name"] for a in acts_for("moray")]
    assert "mucus_soft" in [a["name"] for a in acts_for("moray")]
    assert "sentry_soft" in [a["name"] for a in acts_for("moray")]
    assert "freeze" in [a["name"] for a in acts_for("moray")]
    assert "thatch" in [a["name"] for a in acts_for("moss")]
    assert "seta_soft" in [a["name"] for a in acts_for("moss")]
    assert "freeze" in [a["name"] for a in acts_for("moss")]
    assert "saucer" in [a["name"] for a in acts_for("maidenhair")]
    assert "sori_soft" in [a["name"] for a in acts_for("maidenhair")]
    assert "bulb_soft" in [a["name"] for a in acts_for("maidenhair")]
    assert "freeze" in [a["name"] for a in acts_for("maidenhair")]
    assert "amber" in [a["name"] for a in acts_for("ginkgo")]
    assert "dichotomy_soft" in [a["name"] for a in acts_for("ginkgo")]
    assert "petiole_soft" in [a["name"] for a in acts_for("ginkgo")]
    assert "freeze" in [a["name"] for a in acts_for("ginkgo")]
    assert "bole" in [a["name"] for a in acts_for("oak")]
    assert "catkin_soft" in [a["name"] for a in acts_for("oak")]
    assert "tyloses_soft" in [a["name"] for a in acts_for("oak")]
    assert "freeze" in [a["name"] for a in acts_for("oak")]
    assert "sheen" in [a["name"] for a in acts_for("water_lily")]
    assert "peltate_soft" in [a["name"] for a in acts_for("water_lily")]
    assert "hydropote_soft" in [a["name"] for a in acts_for("water_lily")]
    assert "freeze" in [a["name"] for a in acts_for("water_lily")]
    assert "bark" in [a["name"] for a in acts_for("orchid")]
    assert "keiki_soft" in [a["name"] for a in acts_for("orchid")]
    assert "pollinia_soft" in [a["name"] for a in acts_for("orchid")]
    assert "freeze" in [a["name"] for a in acts_for("orchid")]
    assert "sentinel" in [a["name"] for a in acts_for("saguaro")]
    assert "pleat_soft" in [a["name"] for a in acts_for("saguaro")]
    assert "boot_soft" in [a["name"] for a in acts_for("saguaro")]
    assert "freeze" in [a["name"] for a in acts_for("saguaro")]
    assert "gape" not in [a["name"] for a in acts_for("moray")]
    assert "hide" not in [a["name"] for a in acts_for("moray")]
    assert "dart" not in [a["name"] for a in acts_for("moray")]
    for key in CORNER_KEYS:
        names = [a["name"] for a in acts_for(key)]
        assert "scratch" not in names, key
        assert "tongue" not in names, key
    assert "araneus" in [a["name"] for a in acts_for("orb_weaver")]
    assert "dragline_soft" in [a["name"] for a in acts_for("orb_weaver")]
    assert "viscid_soft" in [a["name"] for a in acts_for("orb_weaver")]
    assert "freeze" in [a["name"] for a in acts_for("orb_weaver")]
    assert "phidippus" in [a["name"] for a in acts_for("jumping_spider")]
    assert "safetyline_soft" in [a["name"] for a in acts_for("jumping_spider")]
    assert "ame_soft" in [a["name"] for a in acts_for("jumping_spider")]
    assert "scopula_soft" in [a["name"] for a in acts_for("jumping_spider")]
    assert "freeze" in [a["name"] for a in acts_for("jumping_spider")]
    assert "tigrosa" in [a["name"] for a in acts_for("wolf_spider")]
    assert "spur_soft" in [a["name"] for a in acts_for("wolf_spider")]
    assert "apron_soft" in [a["name"] for a in acts_for("wolf_spider")]
    assert "cursor_soft" in [a["name"] for a in acts_for("wolf_spider")]
    assert "freeze" in [a["name"] for a in acts_for("wolf_spider")]
    assert "aphonopelma" in [a["name"] for a in acts_for("tarantula")]
    assert "rastellum_soft" in [a["name"] for a in acts_for("tarantula")]
    assert "apophysis_soft" in [a["name"] for a in acts_for("tarantula")]
    assert "urticate_soft" in [a["name"] for a in acts_for("tarantula")]
    assert "freeze" in [a["name"] for a in acts_for("tarantula")]
    assert "latrodectus" in [a["name"] for a in acts_for("widow")]
    assert "combfoot_soft" in [a["name"] for a in acts_for("widow")]
    assert "theridiid_soft" in [a["name"] for a in acts_for("widow")]
    assert "hourglass_soft" in [a["name"] for a in acts_for("widow")]
    assert "freeze" in [a["name"] for a in acts_for("widow")]
    assert "phalangium" in [a["name"] for a in acts_for("harvestman")]
    assert "ozopore_soft" in [a["name"] for a in acts_for("harvestman")]
    assert "leiobunum_soft" in [a["name"] for a in acts_for("harvestman")]
    assert "legwave_soft" in [a["name"] for a in acts_for("harvestman")]
    assert "freeze" in [a["name"] for a in acts_for("harvestman")]
    assert "centruroides" in [a["name"] for a in acts_for("scorpion")]
    assert "pectines_soft" in [a["name"] for a in acts_for("scorpion")]
    assert "booklung_soft" in [a["name"] for a in acts_for("scorpion")]
    assert "pedipalp_soft" in [a["name"] for a in acts_for("scorpion")]
    assert "freeze" in [a["name"] for a in acts_for("scorpion")]
    assert "mastigoproctus" in [a["name"] for a in acts_for("vinegaroon")]
    assert "pygidial_soft" in [a["name"] for a in acts_for("vinegaroon")]
    assert "antenniform_soft" in [a["name"] for a in acts_for("vinegaroon")]
    assert "caudalwhip_soft" in [a["name"] for a in acts_for("vinegaroon")]
    assert "freeze" in [a["name"] for a in acts_for("vinegaroon")]
    assert "ixodes" in [a["name"] for a in acts_for("tick")]
    assert "scutum_soft" in [a["name"] for a in acts_for("tick")]
    assert "capitulum_soft" in [a["name"] for a in acts_for("tick")]
    assert "quest_soft" in [a["name"] for a in acts_for("tick")]
    assert "freeze" in [a["name"] for a in acts_for("tick")]
    assert "eremobates" in [a["name"] for a in acts_for("solifuge")]
    assert "propeltidium_soft" in [a["name"] for a in acts_for("solifuge")]
    assert "tracheate_soft" in [a["name"] for a in acts_for("solifuge")]
    assert "malleoli_soft" in [a["name"] for a in acts_for("solifuge")]
    assert "freeze" in [a["name"] for a in acts_for("solifuge")]
    for key in WOOD_KEYS:
        names = [a["name"] for a in acts_for(key)]
        assert "scratch" not in names, key
        assert "tongue" not in names, key
    assert "odocoileus" in [a["name"] for a in acts_for("deer")]
    assert "eptesicus" in [a["name"] for a in acts_for("bat")]
    assert "sciurus" in [a["name"] for a in acts_for("squirrel")]
    assert "nutbury_soft" in [a["name"] for a in acts_for("squirrel")]
    assert "barkscramble_soft" in [a["name"] for a in acts_for("squirrel")]
    assert "scold_soft" in [a["name"] for a in acts_for("squirrel")]
    assert "freeze" in [a["name"] for a in acts_for("squirrel")]
    assert "lontra" in [a["name"] for a in acts_for("otter")]
    assert "bellyglide_soft" in [a["name"] for a in acts_for("otter")]
    assert "denslide_soft" in [a["name"] for a in acts_for("otter")]
    assert "spraint_soft" in [a["name"] for a in acts_for("otter")]
    assert "freeze" in [a["name"] for a in acts_for("otter")]
    assert "procyon" in [a["name"] for a in acts_for("raccoon")]
    assert "pawdouse_soft" in [a["name"] for a in acts_for("raccoon")]
    assert "dexterous_soft" in [a["name"] for a in acts_for("raccoon")]
    assert "ringtail_soft" in [a["name"] for a in acts_for("raccoon")]
    assert "freeze" in [a["name"] for a in acts_for("raccoon")]
    assert "mephitis" in [a["name"] for a in acts_for("skunk")]
    assert "footstomp_soft" in [a["name"] for a in acts_for("skunk")]
    assert "scentraise_soft" in [a["name"] for a in acts_for("skunk")]
    assert "plantigrade_soft" in [a["name"] for a in acts_for("skunk")]
    assert "freeze" in [a["name"] for a in acts_for("skunk")]
    assert "didelphis" in [a["name"] for a in acts_for("opossum")]
    assert "stillfeign_soft" in [a["name"] for a in acts_for("opossum")]
    assert "pouchcarry_soft" in [a["name"] for a in acts_for("opossum")]
    assert "prehensile_soft" in [a["name"] for a in acts_for("opossum")]
    assert "freeze" in [a["name"] for a in acts_for("opossum")]
    assert "castor" in [a["name"] for a in acts_for("beaver")]
    assert "woodfell_soft" in [a["name"] for a in acts_for("beaver")]
    assert "aspen_soft" in [a["name"] for a in acts_for("beaver")]
    assert "divehush_soft" in [a["name"] for a in acts_for("beaver")]
    assert "freeze" in [a["name"] for a in acts_for("beaver")]
    assert "erethizon" in [a["name"] for a in acts_for("porcupine")]
    assert "ursus" in [a["name"] for a in acts_for("black_bear")]
    assert "bipedrise_soft" in [a["name"] for a in acts_for("black_bear")]
    assert "bluffhuff_soft" in [a["name"] for a in acts_for("black_bear")]
    assert "mastforage_soft" in [a["name"] for a in acts_for("black_bear")]
    assert "freeze" in [a["name"] for a in acts_for("black_bear")]
    for key in STONE_KEYS:
        names = [a["name"] for a in acts_for(key)]
        assert "scratch" not in names, key
        assert "tongue" not in names, key
    assert "climb" in [a["name"] for a in acts_for("gecko")]
    assert "flash" in [a["name"] for a in acts_for("anole")]
    assert "dash" in [a["name"] for a in acts_for("skink")]
    assert "aim" in [a["name"] for a in acts_for("chameleon")]
    assert "phrynosoma" in [a["name"] for a in acts_for("horned_lizard")]
    assert "freeze" in [a["name"] for a in acts_for("horned_lizard")]
    assert "crown" not in [a["name"] for a in acts_for("horned_lizard")]
    assert "mississippi" in [a["name"] for a in acts_for("alligator")]
    assert "bellowbank_soft" in [a["name"] for a in acts_for("alligator")]
    assert "freeze" in [a["name"] for a in acts_for("alligator")]
    assert "bask" not in [a["name"] for a in acts_for("alligator")]
    assert "acutus" in [a["name"] for a in acts_for("crocodile")]
    assert "toothlock_soft" in [a["name"] for a in acts_for("crocodile")]
    assert "vsnout_soft" in [a["name"] for a in acts_for("crocodile")]
    assert "keelridge_soft" in [a["name"] for a in acts_for("crocodile")]
    assert "freeze" in [a["name"] for a in acts_for("crocodile")]
    assert "show" not in [a["name"] for a in acts_for("crocodile")]
    assert "sit" not in [a["name"] for a in acts_for("crocodile")]
    assert "still" not in [a["name"] for a in acts_for("crocodile")]
    assert "serpentina" in [a["name"] for a in acts_for("snapper")]
    assert "ambushgape_soft" in [a["name"] for a in acts_for("snapper")]
    assert "serrated_soft" in [a["name"] for a in acts_for("snapper")]
    assert "plastron_soft" in [a["name"] for a in acts_for("snapper")]
    assert "freeze" in [a["name"] for a in acts_for("snapper")]
    assert "snap" not in [a["name"] for a in acts_for("snapper")]
    assert "sit" not in [a["name"] for a in acts_for("snapper")]
    assert "still" not in [a["name"] for a in acts_for("snapper")]
    assert "shut" in [a["name"] for a in acts_for("box_turtle")]
    assert "still" in [a["name"] for a in acts_for("tuatara")]
    for key in CREEK_KEYS:
        names = [a["name"] for a in acts_for(key)]
        assert "scratch" not in names, key
        assert "tongue" not in names, key
    assert "salmoides" in [a["name"] for a in acts_for("bass")]
    assert "coverstrike_soft" in [a["name"] for a in acts_for("bass")]
    assert "maxilla_soft" in [a["name"] for a in acts_for("bass")]
    assert "weedline_soft" in [a["name"] for a in acts_for("bass")]
    assert "freeze" in [a["name"] for a in acts_for("bass")]
    assert "lunge" not in [a["name"] for a in acts_for("bass")]
    assert "sit" not in [a["name"] for a in acts_for("bass")]
    assert "gape" not in [a["name"] for a in acts_for("bass")]
    assert "fontinalis" in [a["name"] for a in acts_for("brook_trout")]
    assert "driftfeed_soft" in [a["name"] for a in acts_for("brook_trout")]
    assert "adipose_soft" in [a["name"] for a in acts_for("brook_trout")]
    assert "coldriffle_soft" in [a["name"] for a in acts_for("brook_trout")]
    assert "freeze" in [a["name"] for a in acts_for("brook_trout")]
    assert "dart" not in [a["name"] for a in acts_for("brook_trout")]
    assert "rise" not in [a["name"] for a in acts_for("brook_trout")]
    assert "still" not in [a["name"] for a in acts_for("brook_trout")]
    assert "ictalurus" in [a["name"] for a in acts_for("catfish")]
    assert "barbelprobe_soft" in [a["name"] for a in acts_for("catfish")]
    assert "channel_soft" in [a["name"] for a in acts_for("catfish")]
    assert "mudhush_soft" in [a["name"] for a in acts_for("catfish")]
    assert "freeze" in [a["name"] for a in acts_for("catfish")]
    assert "whisk" not in [a["name"] for a in acts_for("catfish")]
    assert "sit" not in [a["name"] for a in acts_for("catfish")]
    assert "still" not in [a["name"] for a in acts_for("catfish")]
    assert "macrochirus" in [a["name"] for a in acts_for("bluegill")]
    assert "platehover_soft" in [a["name"] for a in acts_for("bluegill")]
    assert "opercle_soft" in [a["name"] for a in acts_for("bluegill")]
    assert "earflap_soft" in [a["name"] for a in acts_for("bluegill")]
    assert "freeze" in [a["name"] for a in acts_for("bluegill")]
    assert "flare" not in [a["name"] for a in acts_for("bluegill")]
    assert "sit" not in [a["name"] for a in acts_for("bluegill")]
    assert "dart" not in [a["name"] for a in acts_for("bluegill")]
    assert "penny" not in [a["name"] for a in acts_for("bluegill")]
    assert "flavescens" in [a["name"] for a in acts_for("perch")]
    assert "tigerbar_soft" in [a["name"] for a in acts_for("perch")]
    assert "spiny_soft" in [a["name"] for a in acts_for("perch")]
    assert "yellowflank_soft" in [a["name"] for a in acts_for("perch")]
    assert "freeze" in [a["name"] for a in acts_for("perch")]
    assert "bar" not in [a["name"] for a in acts_for("perch")]
    assert "sit" not in [a["name"] for a in acts_for("perch")]
    assert "dart" not in [a["name"] for a in acts_for("perch")]
    assert "still" not in [a["name"] for a in acts_for("perch")]
    assert "lucius" in [a["name"] for a in acts_for("pike")]
    assert "weedambush_soft" in [a["name"] for a in acts_for("pike")]
    assert "duckbill_soft" in [a["name"] for a in acts_for("pike")]
    assert "lateral_soft" in [a["name"] for a in acts_for("pike")]
    assert "freeze" in [a["name"] for a in acts_for("pike")]
    assert "wait" not in [a["name"] for a in acts_for("pike")]
    assert "lance" not in [a["name"] for a in acts_for("pike")]
    assert "sit" not in [a["name"] for a in acts_for("pike")]
    assert "still" not in [a["name"] for a in acts_for("pike")]
    assert "vitreus" in [a["name"] for a in acts_for("walleye")]
    assert "tapetumglow_soft" in [a["name"] for a in acts_for("walleye")]
    assert "canine_soft" in [a["name"] for a in acts_for("walleye")]
    assert "glassy_soft" in [a["name"] for a in acts_for("walleye")]
    assert "freeze" in [a["name"] for a in acts_for("walleye")]
    assert "hunt" not in [a["name"] for a in acts_for("walleye")]
    assert "glow" not in [a["name"] for a in acts_for("walleye")]
    assert "still" not in [a["name"] for a in acts_for("walleye")]
    assert "night" not in [a["name"] for a in acts_for("walleye")]
    assert "sit" not in [a["name"] for a in acts_for("walleye")]
    assert "spathula" in [a["name"] for a in acts_for("paddlefish")]
    assert "rostrumscan_soft" in [a["name"] for a in acts_for("paddlefish")]
    assert "ampullae_soft" in [a["name"] for a in acts_for("paddlefish")]
    assert "cartilaginous_soft" in [a["name"] for a in acts_for("paddlefish")]
    assert "freeze" in [a["name"] for a in acts_for("paddlefish")]
    assert "filter" not in [a["name"] for a in acts_for("paddlefish")]
    assert "paddle" not in [a["name"] for a in acts_for("paddlefish")]
    assert "still" not in [a["name"] for a in acts_for("paddlefish")]
    assert "spoon" not in [a["name"] for a in acts_for("paddlefish")]
    assert "sit" not in [a["name"] for a in acts_for("paddlefish")]
    assert "marinus" in [a["name"] for a in acts_for("lamprey")]
    assert "oralclamp_soft" in [a["name"] for a in acts_for("lamprey")]
    assert "anadromous_soft" in [a["name"] for a in acts_for("lamprey")]
    assert "sevengill_soft" in [a["name"] for a in acts_for("lamprey")]
    assert "freeze" in [a["name"] for a in acts_for("lamprey")]
    assert "disk" not in [a["name"] for a in acts_for("lamprey")]
    assert "cling" not in [a["name"] for a in acts_for("lamprey")]
    assert "still" not in [a["name"] for a in acts_for("lamprey")]
    assert "round" not in [a["name"] for a in acts_for("lamprey")]
    assert "sit" not in [a["name"] for a in acts_for("lamprey")]
    assert "rostrata" in [a["name"] for a in acts_for("american_eel")]
    assert "glasscrawl_soft" in [a["name"] for a in acts_for("american_eel")]
    assert "sargasso_soft" in [a["name"] for a in acts_for("american_eel")]
    assert "yellowphase_soft" in [a["name"] for a in acts_for("american_eel")]
    assert "freeze" in [a["name"] for a in acts_for("american_eel")]
    assert "swim" not in [a["name"] for a in acts_for("american_eel")]
    assert "silver" not in [a["name"] for a in acts_for("american_eel")]
    assert "still" not in [a["name"] for a in acts_for("american_eel")]
    assert "sit" not in [a["name"] for a in acts_for("american_eel")]
    for key in LOG_KEYS:
        names = [a["name"] for a in acts_for(key)]
        assert "scratch" not in names, key
        assert "tongue" not in names, key
    assert "scutigera" in [a["name"] for a in acts_for("house_centipede")]
    assert "forcipule_soft" in [a["name"] for a in acts_for("house_centipede")]
    assert "compound_soft" in [a["name"] for a in acts_for("house_centipede")]
    assert "fifteenpair_soft" in [a["name"] for a in acts_for("house_centipede")]
    assert "freeze" in [a["name"] for a in acts_for("house_centipede")]
    assert "hunt" not in [a["name"] for a in acts_for("house_centipede")]
    assert "walk" not in [a["name"] for a in acts_for("house_centipede")]
    assert "still" not in [a["name"] for a in acts_for("house_centipede")]
    assert "sit" not in [a["name"] for a in acts_for("house_centipede")]
    assert "narceus" in [a["name"] for a in acts_for("millipede")]
    assert "coilcurl_soft" in [a["name"] for a in acts_for("millipede")]
    assert "benzoquinone_soft" in [a["name"] for a in acts_for("millipede")]
    assert "metachronal_soft" in [a["name"] for a in acts_for("millipede")]
    assert "freeze" in [a["name"] for a in acts_for("millipede")]
    assert "walk" not in [a["name"] for a in acts_for("millipede")]
    assert "oil" not in [a["name"] for a in acts_for("millipede")]
    assert "still" not in [a["name"] for a in acts_for("millipede")]
    assert "sit" not in [a["name"] for a in acts_for("millipede")]
    assert "vulgare" in [a["name"] for a in acts_for("pillbug")]
    assert "conglobate_soft" in [a["name"] for a in acts_for("pillbug")]
    assert "pleopods_soft" in [a["name"] for a in acts_for("pillbug")]
    assert "uropodtap_soft" in [a["name"] for a in acts_for("pillbug")]
    assert "freeze" in [a["name"] for a in acts_for("pillbug")]
    assert "roll" not in [a["name"] for a in acts_for("pillbug")]
    assert "walk" not in [a["name"] for a in acts_for("pillbug")]
    assert "still" not in [a["name"] for a in acts_for("pillbug")]
    assert "sit" not in [a["name"] for a in acts_for("pillbug")]

    assert "terrestris" in [a["name"] for a in acts_for("earthworm")]
    assert "peristalse_soft" in [a["name"] for a in acts_for("earthworm")]
    assert "clitellum_soft" in [a["name"] for a in acts_for("earthworm")]
    assert "setaebrace_soft" in [a["name"] for a in acts_for("earthworm")]
    assert "freeze" in [a["name"] for a in acts_for("earthworm")]
    assert "cast" not in [a["name"] for a in acts_for("earthworm")]
    assert "crawl" not in [a["name"] for a in acts_for("earthworm")]
    assert "still" not in [a["name"] for a in acts_for("earthworm")]
    assert "sit" not in [a["name"] for a in acts_for("earthworm")]

    assert "peripatus" in [a["name"] for a in acts_for("velvet_worm")]
    assert "slimejet_soft" in [a["name"] for a in acts_for("velvet_worm")]
    assert "oralpapilla_soft" in [a["name"] for a in acts_for("velvet_worm")]
    assert "onychophore_soft" in [a["name"] for a in acts_for("velvet_worm")]
    assert "freeze" in [a["name"] for a in acts_for("velvet_worm")]
    assert "jet" not in [a["name"] for a in acts_for("velvet_worm")]
    assert "walk" not in [a["name"] for a in acts_for("velvet_worm")]
    assert "still" not in [a["name"] for a in acts_for("velvet_worm")]
    assert "sit" not in [a["name"] for a in acts_for("velvet_worm")]

    assert "orchesella" in [a["name"] for a in acts_for("springtail")]
    assert "furculaflick_soft" in [a["name"] for a in acts_for("springtail")]
    assert "collophore_soft" in [a["name"] for a in acts_for("springtail")]
    assert "denspring_soft" in [a["name"] for a in acts_for("springtail")]
    assert "freeze" in [a["name"] for a in acts_for("springtail")]
    assert "hop" not in [a["name"] for a in acts_for("springtail")]
    assert "walk" not in [a["name"] for a in acts_for("springtail")]
    assert "still" not in [a["name"] for a in acts_for("springtail")]
    assert "sit" not in [a["name"] for a in acts_for("springtail")]
    assert "eutardigrada" in [a["name"] for a in acts_for("tardigrade")]
    assert "cryptotun_soft" in [a["name"] for a in acts_for("tardigrade")]
    assert "clawamble_soft" in [a["name"] for a in acts_for("tardigrade")]
    assert "mosssip_soft" in [a["name"] for a in acts_for("tardigrade")]
    assert "waterbearroll_soft" in [a["name"] for a in acts_for("tardigrade")]
    assert "styletpierce_soft" in [a["name"] for a in acts_for("tardigrade")]
    assert "anhydro_soft" in [a["name"] for a in acts_for("tardigrade")]
    assert "freeze" in [a["name"] for a in acts_for("tardigrade")]
    assert "tun" not in [a["name"] for a in acts_for("tardigrade")]
    assert "walk" not in [a["name"] for a in acts_for("tardigrade")]
    assert "still" not in [a["name"] for a in acts_for("tardigrade")]
    assert "sit" not in [a["name"] for a in acts_for("tardigrade")]
    assert "dugesia" in [a["name"] for a in acts_for("planarian")]
    assert "ciliaryglide_soft" in [a["name"] for a in acts_for("planarian")]
    assert "lightflee_soft" in [a["name"] for a in acts_for("planarian")]
    assert "preywrap_soft" in [a["name"] for a in acts_for("planarian")]
    assert "regensplit_soft" in [a["name"] for a in acts_for("planarian")]
    assert "auriclesense_soft" in [a["name"] for a in acts_for("planarian")]
    assert "pharynxprobe_soft" in [a["name"] for a in acts_for("planarian")]
    assert "freeze" in [a["name"] for a in acts_for("planarian")]
    assert "split" not in [a["name"] for a in acts_for("planarian")]
    assert "glide" not in [a["name"] for a in acts_for("planarian")]
    assert "still" not in [a["name"] for a in acts_for("planarian")]
    assert "half" not in [a["name"] for a in acts_for("planarian")]
    assert "sit" not in [a["name"] for a in acts_for("planarian")]
    assert "elegans" in [a["name"] for a in acts_for("nematode")]
    assert "sinusoid_soft" in [a["name"] for a in acts_for("nematode")]
    assert "dauerrest_soft" in [a["name"] for a in acts_for("nematode")]
    assert "pharynxpump_soft" in [a["name"] for a in acts_for("nematode")]
    assert "thrashturn_soft" in [a["name"] for a in acts_for("nematode")]
    assert "omegaturn_soft" in [a["name"] for a in acts_for("nematode")]
    assert "vulvaseek_soft" in [a["name"] for a in acts_for("nematode")]
    assert "freeze" in [a["name"] for a in acts_for("nematode")]
    assert "thrash" not in [a["name"] for a in acts_for("nematode")]
    assert "still" not in [a["name"] for a in acts_for("nematode")]
    assert "sit" not in [a["name"] for a in acts_for("nematode")]
    assert "thread" not in [a["name"] for a in acts_for("nematode")]
    assert "gammarus" in [a["name"] for a in acts_for("amphipod")]
    assert "sideswim_soft" in [a["name"] for a in acts_for("amphipod")]
    assert "gnathopod_soft" in [a["name"] for a in acts_for("amphipod")]
    assert "detritusclutch_soft" in [a["name"] for a in acts_for("amphipod")]
    assert "pairguard_soft" in [a["name"] for a in acts_for("amphipod")]
    assert "urosome_soft" in [a["name"] for a in acts_for("amphipod")]
    assert "pleopod_soft" in [a["name"] for a in acts_for("amphipod")]
    assert "freeze" in [a["name"] for a in acts_for("amphipod")]
    assert "scud" not in [a["name"] for a in acts_for("amphipod")]
    assert "dart" not in [a["name"] for a in acts_for("amphipod")]
    assert "still" not in [a["name"] for a in acts_for("amphipod")]
    assert "sit" not in [a["name"] for a in acts_for("amphipod")]
    for key in SHORE_KEYS:
        names = [a["name"] for a in acts_for(key)]
        assert "scratch" not in names, key
        assert "tongue" not in names, key
    assert "pugilator" in [a["name"] for a in acts_for("fiddler_crab")]
    assert "clawwave_soft" in [a["name"] for a in acts_for("fiddler_crab")]
    assert "burrowdig_soft" in [a["name"] for a in acts_for("fiddler_crab")]
    assert "sandfeed_soft" in [a["name"] for a in acts_for("fiddler_crab")]
    assert "lateralsidestep_soft" in [a["name"] for a in acts_for("fiddler_crab")]
    assert "majorclaw_soft" in [a["name"] for a in acts_for("fiddler_crab")]
    assert "mudball_soft" in [a["name"] for a in acts_for("fiddler_crab")]
    assert "freeze" in [a["name"] for a in acts_for("fiddler_crab")]
    assert "wave" not in [a["name"] for a in acts_for("fiddler_crab")]
    assert "walk" not in [a["name"] for a in acts_for("fiddler_crab")]
    assert "still" not in [a["name"] for a in acts_for("fiddler_crab")]
    assert "sit" not in [a["name"] for a in acts_for("fiddler_crab")]
    assert "ocypodehush" in [a["name"] for a in acts_for("ghost_crab")]
    assert "sprintdash_soft" in [a["name"] for a in acts_for("ghost_crab")]
    assert "stalkeyescan_soft" in [a["name"] for a in acts_for("ghost_crab")]
    assert "burrowplunge_soft" in [a["name"] for a in acts_for("ghost_crab")]
    assert "freezecamo_soft" in [a["name"] for a in acts_for("ghost_crab")]
    assert "nightforage_soft" in [a["name"] for a in acts_for("ghost_crab")]
    assert "sandghost_soft" in [a["name"] for a in acts_for("ghost_crab")]
    assert "freeze" in [a["name"] for a in acts_for("ghost_crab")]
    assert "run" not in [a["name"] for a in acts_for("ghost_crab")]
    assert "walk" not in [a["name"] for a in acts_for("ghost_crab")]
    assert "still" not in [a["name"] for a in acts_for("ghost_crab")]
    assert "sit" not in [a["name"] for a in acts_for("ghost_crab")]
    assert "patellahush" in [a["name"] for a in acts_for("limpet")]
    assert "clampseal_soft" in [a["name"] for a in acts_for("limpet")]
    assert "radialgraze_soft" in [a["name"] for a in acts_for("limpet")]
    assert "circumhome_soft" in [a["name"] for a in acts_for("limpet")]
    assert "shelltilt_soft" in [a["name"] for a in acts_for("limpet")]
    assert "homescar_soft" in [a["name"] for a in acts_for("limpet")]
    assert "radulasweep_soft" in [a["name"] for a in acts_for("limpet")]
    assert "freeze" in [a["name"] for a in acts_for("limpet")]
    assert "clamp" not in [a["name"] for a in acts_for("limpet")]
    assert "rasp" not in [a["name"] for a in acts_for("limpet")]
    assert "still" not in [a["name"] for a in acts_for("limpet")]
    assert "sit" not in [a["name"] for a in acts_for("limpet")]
    assert "balanushush" in [a["name"] for a in acts_for("barnacle")]
    assert "cirrikick_soft" in [a["name"] for a in acts_for("barnacle")]
    assert "opershut_soft" in [a["name"] for a in acts_for("barnacle")]
    assert "cementhold_soft" in [a["name"] for a in acts_for("barnacle")]
    assert "tidereopen_soft" in [a["name"] for a in acts_for("barnacle")]
    assert "cirrisweep_soft" in [a["name"] for a in acts_for("barnacle")]
    assert "plateshut_soft" in [a["name"] for a in acts_for("barnacle")]
    assert "freeze" in [a["name"] for a in acts_for("barnacle")]
    assert "kick" not in [a["name"] for a in acts_for("barnacle")]
    assert "still" not in [a["name"] for a in acts_for("barnacle")]
    assert "sit" not in [a["name"] for a in acts_for("barnacle")]
    assert "cirri" not in [a["name"] for a in acts_for("barnacle")]
    assert "chitonhush" in [a["name"] for a in acts_for("chiton")]
    assert "plateflex_soft" in [a["name"] for a in acts_for("chiton")]
    assert "radularasp_soft" in [a["name"] for a in acts_for("chiton")]
    assert "girdlesettle_soft" in [a["name"] for a in acts_for("chiton")]
    assert "rockcreep_soft" in [a["name"] for a in acts_for("chiton")]
    assert "eightvalve_soft" in [a["name"] for a in acts_for("chiton")]
    assert "aesthete_soft" in [a["name"] for a in acts_for("chiton")]
    assert "freeze" in [a["name"] for a in acts_for("chiton")]
    assert "graze" not in [a["name"] for a in acts_for("chiton")]
    assert "plate" not in [a["name"] for a in acts_for("chiton")]
    assert "still" not in [a["name"] for a in acts_for("chiton")]
    assert "sit" not in [a["name"] for a in acts_for("chiton")]
    assert "littorinahush" in [a["name"] for a in acts_for("periwinkle")]
    assert "spiralcrawl_soft" in [a["name"] for a in acts_for("periwinkle")]
    assert "filmgraze_soft" in [a["name"] for a in acts_for("periwinkle")]
    assert "opercshut_soft" in [a["name"] for a in acts_for("periwinkle")]
    assert "tidehuddle_soft" in [a["name"] for a in acts_for("periwinkle")]
    assert "tipup_soft" in [a["name"] for a in acts_for("periwinkle")]
    assert "littorine_soft" in [a["name"] for a in acts_for("periwinkle")]
    assert "freeze" in [a["name"] for a in acts_for("periwinkle")]
    assert "rasp" not in [a["name"] for a in acts_for("periwinkle")]
    assert "graze" not in [a["name"] for a in acts_for("periwinkle")]
    assert "still" not in [a["name"] for a in acts_for("periwinkle")]
    assert "sit" not in [a["name"] for a in acts_for("periwinkle")]
    assert "mellitahush" in [a["name"] for a in acts_for("sand_dollar")]
    assert "lunulesift_soft" in [a["name"] for a in acts_for("sand_dollar")]
    assert "dollarright_soft" in [a["name"] for a in acts_for("sand_dollar")]
    assert "sandfilmburrow_soft" in [a["name"] for a in acts_for("sand_dollar")]
    assert "spinefurcreep_soft" in [a["name"] for a in acts_for("sand_dollar")]
    assert "petaloid_soft" in [a["name"] for a in acts_for("sand_dollar")]
    assert "ambulacra_soft" in [a["name"] for a in acts_for("sand_dollar")]
    assert "freeze" in [a["name"] for a in acts_for("sand_dollar")]
    assert "bury" not in [a["name"] for a in acts_for("sand_dollar")]
    assert "flat" not in [a["name"] for a in acts_for("sand_dollar")]
    assert "still" not in [a["name"] for a in acts_for("sand_dollar")]
    assert "sit" not in [a["name"] for a in acts_for("sand_dollar")]
    assert "strongylhush" in [a["name"] for a in acts_for("sea_urchin")]
    assert "spinewalk_soft" in [a["name"] for a in acts_for("sea_urchin")]
    assert "lanterngraze_soft" in [a["name"] for a in acts_for("sea_urchin")]
    assert "gripcreep_soft" in [a["name"] for a in acts_for("sea_urchin")]
    assert "spineflare_soft" in [a["name"] for a in acts_for("sea_urchin")]
    assert "pedicellaria_soft" in [a["name"] for a in acts_for("sea_urchin")]
    assert "aristotle_soft" in [a["name"] for a in acts_for("sea_urchin")]
    assert "freeze" in [a["name"] for a in acts_for("sea_urchin")]
    assert "walk" not in [a["name"] for a in acts_for("sea_urchin")]
    assert "spine" not in [a["name"] for a in acts_for("sea_urchin")]
    assert "still" not in [a["name"] for a in acts_for("sea_urchin")]
    assert "sit" not in [a["name"] for a in acts_for("sea_urchin")]
    assert "hunt" in [a["name"] for a in acts_for("knobbed_whelk")]
    assert "heap" in [a["name"] for a in acts_for("lugworm")]
    for key in MEADOW_KEYS:
        names = [a["name"] for a in acts_for(key)]
        assert "scratch" not in names, key
        assert "tongue" not in names, key
    assert "chirp" in [a["name"] for a in acts_for("field_cricket")]
    assert "blade" in [a["name"] for a in acts_for("katydid")]
    assert "vault" in [a["name"] for a in acts_for("grasshopper")]
    assert "banner" in [a["name"] for a in acts_for("swallowtail")]
    assert "jewel" in [a["name"] for a in acts_for("jewelwing")]
    assert "lace" in [a["name"] for a in acts_for("lacewing")]
    assert "raise" in [a["name"] for a in acts_for("earwig")]
    assert "drill" in [a["name"] for a in acts_for("acorn_weevil")]
    assert "click" in [a["name"] for a in acts_for("click_beetle")]
    assert "hunt" in [a["name"] for a in acts_for("robber_fly")]
    for key in CANOPY_KEYS:
        names = [a["name"] for a in acts_for(key)]
        assert "scratch" not in names, key
        assert "tongue" not in names, key
    assert "hang" in [a["name"] for a in acts_for("sloth")]
    assert "sun" in [a["name"] for a in acts_for("lemur")]
    assert "swing" in [a["name"] for a in acts_for("gibbon")]
    assert "wrap" in [a["name"] for a in acts_for("kinkajou")]
    assert "sail" in [a["name"] for a in acts_for("colugo")]
    assert "glide" in [a["name"] for a in acts_for("flying_squirrel")]
    assert "boom" in [a["name"] for a in acts_for("howler")]
    assert "gaze" in [a["name"] for a in acts_for("tarsier")]
    assert "still" in [a["name"] for a in acts_for("potto")]
    assert "chew" in [a["name"] for a in acts_for("koala")]
    for key in REEF_KEYS:
        names = [a["name"] for a in acts_for(key)]
        assert "scratch" not in names, key
        assert "tongue" not in names, key
    assert "ridge" in [a["name"] for a in acts_for("brain_coral")]
    assert "wreath" in [a["name"] for a in acts_for("anemone")]
    assert "dart" in [a["name"] for a in acts_for("clownfish")]
    assert "scrape" in [a["name"] for a in acts_for("parrotfish")]
    assert "wave" in [a["name"] for a in acts_for("cleaner_shrimp")]
    assert "crawl" in [a["name"] for a in acts_for("sea_cucumber")]
    assert "veil" in [a["name"] for a in acts_for("lionfish")]
    assert "open" in [a["name"] for a in acts_for("giant_clam")]
    assert "soar" in [a["name"] for a in acts_for("eagle_ray")]
    assert "hide" in [a["name"] for a in acts_for("grouper")]
    assert "arc" in [a["name"] for a in acts_for("cyber_dragon")]
    assert "current" in [a["name"] for a in acts_for("volt_dragon")]
    assert "path" in [a["name"] for a in acts_for("trace_dragon")]
    assert "field" in [a["name"] for a in acts_for("flux_dragon")]
    assert "crackle" in [a["name"] for a in acts_for("spark_dragon")]
    assert "haze" in [a["name"] for a in acts_for("ion_dragon")]
    assert "filing" in [a["name"] for a in acts_for("gauss_dragon")]
    assert "relay" in [a["name"] for a in acts_for("relay_dragon")]
    assert "fuse" in [a["name"] for a in acts_for("fuse_dragon")]
    assert "earth" in [a["name"] for a in acts_for("ground_dragon")]
