import assert from "node:assert/strict";
import { createRequire } from "node:module";
import { dirname, join } from "node:path";
import { test } from "node:test";
import { fileURLToPath, pathToFileURL } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const T = await import(pathToFileURL(join(root, "src/lib/pets/axolotl-tricks.ts")).href);
const Rui = await import(pathToFileURL(join(root, "src/lib/pets/rui-tricks.ts")).href);
const Relay = await import(pathToFileURL(join(root, "src/lib/pets/relay-tricks.ts")).href);
const Fuse = await import(pathToFileURL(join(root, "src/lib/pets/fuse-tricks.ts")).href);
const Earth = await import(pathToFileURL(join(root, "src/lib/pets/earth-tricks.ts")).href);
const Cat = await import(pathToFileURL(join(root, "src/lib/pets/cat-tricks.ts")).href);
const Dog = await import(pathToFileURL(join(root, "src/lib/pets/dog-tricks.ts")).href);
const Rabbit = await import(pathToFileURL(join(root, "src/lib/pets/rabbit-tricks.ts")).href);
const Hamster = await import(pathToFileURL(join(root, "src/lib/pets/hamster-tricks.ts")).href);
const GuineaPig = await import(pathToFileURL(join(root, "src/lib/pets/guinea-pig-tricks.ts")).href);
const Turtle = await import(pathToFileURL(join(root, "src/lib/pets/turtle-tricks.ts")).href);
const Goldfish = await import(pathToFileURL(join(root, "src/lib/pets/goldfish-tricks.ts")).href);
const Budgie = await import(pathToFileURL(join(root, "src/lib/pets/budgie-tricks.ts")).href);
const Fox = await import(pathToFileURL(join(root, "src/lib/pets/fox-tricks.ts")).href);
const Penguin = await import(pathToFileURL(join(root, "src/lib/pets/penguin-tricks.ts")).href);
const Parrot = await import(pathToFileURL(join(root, "src/lib/pets/parrot-tricks.ts")).href);
const Ferret = await import(pathToFileURL(join(root, "src/lib/pets/ferret-tricks.ts")).href);
const Hedgehog = await import(pathToFileURL(join(root, "src/lib/pets/hedgehog-tricks.ts")).href);
const Chinchilla = await import(pathToFileURL(join(root, "src/lib/pets/chinchilla-tricks.ts")).href);
const Overlay = createRequire(import.meta.url)(join(root, "../desktop/renderer/axolotl-tricks.js"));
const OverlayGround = createRequire(import.meta.url)(join(root, "../desktop/renderer/ground-tricks.js"));
const OverlayRui = createRequire(import.meta.url)(join(root, "../desktop/renderer/rui-tricks.js"));
const OverlayRelay = createRequire(import.meta.url)(join(root, "../desktop/renderer/relay-tricks.js"));
const OverlayFuse = createRequire(import.meta.url)(join(root, "../desktop/renderer/fuse-tricks.js"));
const OverlayEarth = createRequire(import.meta.url)(join(root, "../desktop/renderer/earth-tricks.js"));
const OverlayCat = createRequire(import.meta.url)(join(root, "../desktop/renderer/cat-tricks.js"));
const OverlayDog = createRequire(import.meta.url)(join(root, "../desktop/renderer/dog-tricks.js"));
const OverlayRabbit = createRequire(import.meta.url)(join(root, "../desktop/renderer/rabbit-tricks.js"));
const OverlayHamster = createRequire(import.meta.url)(join(root, "../desktop/renderer/hamster-tricks.js"));
const OverlayGuineaPig = createRequire(import.meta.url)(join(root, "../desktop/renderer/guinea-pig-tricks.js"));
const OverlayTurtle = createRequire(import.meta.url)(join(root, "../desktop/renderer/turtle-tricks.js"));
const OverlayGoldfish = createRequire(import.meta.url)(join(root, "../desktop/renderer/goldfish-tricks.js"));
const OverlayBudgie = createRequire(import.meta.url)(join(root, "../desktop/renderer/budgie-tricks.js"));
const OverlayFox = createRequire(import.meta.url)(join(root, "../desktop/renderer/fox-tricks.js"));
const OverlayPenguin = createRequire(import.meta.url)(join(root, "../desktop/renderer/penguin-tricks.js"));
const OverlayParrot = createRequire(import.meta.url)(join(root, "../desktop/renderer/parrot-tricks.js"));
const OverlayFerret = createRequire(import.meta.url)(join(root, "../desktop/renderer/ferret-tricks.js"));
const OverlayHedgehog = createRequire(import.meta.url)(join(root, "../desktop/renderer/hedgehog-tricks.js"));
const OverlayChinchilla = createRequire(import.meta.url)(join(root, "../desktop/renderer/chinchilla-tricks.js"));
const OverlayToucan = createRequire(import.meta.url)(join(root, "../desktop/renderer/toucan-tricks.js"));
const OverlayIguana = createRequire(import.meta.url)(join(root, "../desktop/renderer/iguana-tricks.js"));
const OverlayDragon = createRequire(import.meta.url)(join(root, "../desktop/renderer/dragon-tricks.js"));
const OverlayPhoenix = createRequire(import.meta.url)(join(root, "../desktop/renderer/phoenix-tricks.js"));

test("Bloom tricks start only on idle ground", () => {
  assert.deepEqual([...T.TRICKS], ["gill", "amble", "mend", "smile", "plume", "sprout", "glop"]);
  assert.equal(T.canStart({ asleep: false, hidden: false, leaving: false, cmd: "idle" }), true);
  assert.equal(T.canStart({ asleep: true, hidden: false, leaving: false, cmd: "idle" }), false);
  assert.equal(T.canStart({ asleep: false, hidden: true, leaving: false, cmd: "idle" }), false);
  assert.equal(T.canStart({ asleep: false, hidden: false, leaving: false, cmd: "sleep" }), false);
  assert.equal(T.canStart({ asleep: false, hidden: false, leaving: false, cmd: "seek" }), false);
  assert.equal(T.canStart({ asleep: false, hidden: false, leaving: false, cmd: "idle", windowPlay: true }), false);
  assert.equal(T.canStart({ asleep: false, hidden: false, leaving: false, cmd: "idle", card: true }), false);
  assert.equal(T.shouldAbort({ asleep: true, hidden: false, leaving: false, cmd: "idle" }), true);
  assert.equal(T.shouldAbort({ asleep: false, hidden: false, leaving: false, cmd: "idle", card: true }), true);
  assert.equal(T.shouldAbort({ asleep: false, hidden: false, leaving: false, cmd: "idle" }), false);
  assert.equal(T.pickTrick(0.99, true), "gill");
  assert.notEqual(T.pickTrick(0.3, false, "gill"), "gill");
  assert.equal(Overlay.TRICK_KEY, "axolotl");
  assert.equal(T.sleepHoldFrame("chinchilla", 4), null);
  assert.equal(T.TRICKS.includes("wall"), false);
  assert.equal(T.TRICKS.includes("float"), false);
  assert.equal(T.TRICKS.includes("bloom"), false);
  assert.equal(T.TRICKS.includes("ash"), false);
  assert.equal(T.TRICKS.includes("ball"), false);
  assert.equal(T.TRICKS.includes("tube"), false);
  assert.equal(T.TRICKS.includes("dig"), false);
  assert.equal(T.TRICKS.includes("puff"), false);
  assert.equal(T.TRICKS.includes("potato"), false);
  assert.equal(T.TRICKS.includes("tuck"), false);
  assert.equal(T.TRICKS.includes("loaf"), false);
  assert.equal(T.TRICKS.includes("nest"), false);
  assert.equal(T.TRICKS.includes("scurry"), false);
  assert.equal(T.TRICKS.includes("den"), false);
  assert.equal(T.TRICKS.includes("zoom"), false);
  assert.equal(T.TRICKS.includes("dance"), false);
  assert.equal(T.TRICKS.includes("pounce"), false);
  assert.equal(T.TRICKS.includes("thread"), false);
  assert.equal(T.TRICKS.includes("noodle"), false);
  assert.equal(T.TRICKS.includes("steal"), false);
  assert.equal(T.TRICKS.includes("curl"), false);
  assert.equal(T.TRICKS.includes("snuffle"), false);
  assert.equal(T.TRICKS.includes("anoint"), false);
  assert.equal(T.TRICKS.includes("bristle"), false);
  assert.equal(T.TRICKS.includes("root"), false);
  assert.equal(T.TRICKS.includes("popcorn"), false);
  assert.equal(T.TRICKS.includes("groom"), false);
});

test("gill/amble/mend/smile/plume/sprout/glop are house-axolotl-true, not Rui cat dog rabbit hamster guinea-pig turtle goldfish budgie fox penguin parrot ferret hedgehog chinchilla or dragon clones", () => {
  const ground = { asleep: false, hidden: false, leaving: false, cmd: "idle" };
  const gill = T.beginTrick("gill", 80, 1);
  assert.equal(gill.anim, "sit");
  assert.equal(gill.phase, "hold");
  const held = T.stepTrick(gill, 5, ground);
  assert.equal(held.phase, "hold");
  assert.equal(held.anim, "sit");
  assert.ok(held.rot !== 0 || Math.abs(held.lift) > 0.5);
  const release = T.stepTrick(gill, T.GILL_HOLD + 0.2, ground);
  assert.equal(release.phase, "release");
  assert.equal(release.anim, "sit");
  const doneGill = T.stepTrick(gill, T.DUR.gill + 0.1, ground);
  assert.equal(doneGill.phase, "done");
  assert.ok(T.nextTrickWait(true, 0, "gill") > T.nextTrickWait(true, 0, "amble"));
  const amble = T.beginTrick("amble", 80, 1);
  assert.equal(amble.anim, "walk");
  const ambleMid = T.stepTrick(amble, 0.6, ground);
  assert.ok(Math.abs(ambleMid.x - 80) > 1 || Math.abs(ambleMid.lift) > 0.3 || Math.abs(ambleMid.rot) > 1);
  const mend = T.beginTrick("mend", 80, 1);
  assert.equal(mend.anim, "sit");
  const mendMid = T.stepTrick(mend, 0.55, ground);
  assert.ok(Math.abs(mendMid.lift) > 0.2 || Math.abs(mendMid.rot) > 1);
  const smile = T.beginTrick("smile", 80, 1);
  assert.equal(smile.anim, "sit");
  const smileMid = T.stepTrick(smile, 0.4, ground);
  assert.ok(Math.abs(smileMid.lift) > 0.2 || Math.abs(smileMid.rot) > 1);
  const plume = T.beginTrick("plume", 80, 1);
  assert.equal(plume.anim, "play");
  const plumeMid = T.stepTrick(plume, 0.45, ground);
  assert.ok(Math.abs(plumeMid.x - 80) > 0.5 || Math.abs(plumeMid.lift) > 0.3 || Math.abs(plumeMid.rot) > 1);
  const plumeDone = T.stepTrick(plume, T.DUR.plume + 0.1, ground);
  assert.equal(plumeDone.phase, "done");
  const sprout = T.beginTrick("sprout", 80, 1);
  assert.equal(sprout.anim, "play");
  const sproutMid = T.stepTrick(sprout, T.DUR.sprout * 0.4, ground);
  assert.ok(sproutMid.lift > 6 || Math.abs(sproutMid.rot) > 6);
  const glop = T.beginTrick("glop", 80, 1);
  assert.equal(glop.anim, "sit");
  const glopMid = T.stepTrick(glop, T.DUR.glop * 0.45, ground);
  assert.ok(Math.abs(glopMid.lift) > 2 || Math.abs(glopMid.rot) > 4);
  assert.equal(T.TRICKS.includes("wall"), false);
  assert.equal(T.TRICKS.includes("float"), false);
  assert.equal(T.TRICKS.includes("bloom"), false);
  assert.equal(T.TRICKS.includes("gulp"), false);
  assert.equal(T.TRICKS.includes("frill"), false);
  assert.equal(T.TRICKS.includes("waft"), false);
  const aborted = T.stepTrick(held, 0.1, { asleep: true, cmd: "sleep" });
  assert.equal(aborted.phase, "done");
  assert.equal(Rui.TRICKS.includes("gill"), false);
  assert.equal(Cat.TRICKS.includes("amble"), false);
  assert.equal(Dog.TRICKS.includes("mend"), false);
  assert.equal(Rabbit.TRICKS.includes("smile"), false);
  assert.equal(Hamster.TRICKS.includes("plume"), false);
  assert.equal(GuineaPig.TRICKS.includes("gill"), false);
  assert.equal(Turtle.TRICKS.includes("amble"), false);
  assert.equal(Goldfish.TRICKS.includes("mend"), false);
  assert.equal(Budgie.TRICKS.includes("smile"), false);
  assert.equal(Fox.TRICKS.includes("plume"), false);
  assert.equal(Penguin.TRICKS.includes("gill"), false);
  assert.equal(Parrot.TRICKS.includes("amble"), false);
  assert.equal(Ferret.TRICKS.includes("mend"), false);
  assert.equal(Relay.TRICKS.includes("gill"), false);
  assert.equal(Fuse.TRICKS.includes("amble"), false);
  assert.equal(Earth.TRICKS.includes("mend"), false);
  assert.equal(Hedgehog.TRICKS.includes("gill"), false);
  assert.equal(Hedgehog.TRICKS.includes("amble"), false);
  assert.equal(Hedgehog.TRICKS.includes("mend"), false);
  assert.equal(Hedgehog.TRICKS.includes("smile"), false);
  assert.equal(Hedgehog.TRICKS.includes("plume"), false);
  assert.equal(Chinchilla.TRICKS.includes("gill"), false);
  assert.equal(Chinchilla.TRICKS.includes("amble"), false);
  assert.equal(Chinchilla.TRICKS.includes("mend"), false);
  assert.equal(Chinchilla.TRICKS.includes("smile"), false);
  assert.equal(Chinchilla.TRICKS.includes("plume"), false);
  assert.equal(T.TRICKS.includes("wall"), false);
  assert.equal(T.TRICKS.includes("float"), false);
  assert.equal(T.TRICKS.includes("bloom"), false);
  assert.equal(T.TRICKS.includes("ball"), false);
  assert.equal(T.TRICKS.includes("tube"), false);
  assert.equal(T.TRICKS.includes("dig"), false);
  assert.equal(T.TRICKS.includes("puff"), false);
  assert.equal(T.TRICKS.includes("curl"), false);
});

test("Bloom feed-happy is its own sit: wink/blip/grin, and two feeds are not the same", () => {
  assert.deepEqual([...T.HAPPY], ["wink", "blip", "grin"]);
  assert.equal(T.HAPPY.includes("spark"), false);
  assert.equal(T.HAPPY.includes("purr"), false);
  assert.equal(T.HAPPY.includes("tail"), false);
  assert.equal(T.HAPPY.includes("twitch"), false);
  assert.equal(T.HAPPY.includes("stuff"), false);
  assert.equal(T.HAPPY.includes("peep"), false);
  assert.equal(T.HAPPY.includes("munch"), false);
  assert.equal(T.HAPPY.includes("huff"), false);
  assert.equal(T.HAPPY.includes("gleam"), false);
  assert.equal(T.HAPPY.includes("bubble"), false);
  assert.equal(T.HAPPY.includes("chirp"), false);
  assert.equal(T.HAPPY.includes("chatter"), false);
  assert.equal(T.HAPPY.includes("bob"), false);
  assert.equal(T.HAPPY.includes("whistle"), false);
  assert.equal(T.HAPPY.includes("trill"), false);
  assert.equal(T.HAPPY.includes("ruffle"), false);
  assert.equal(T.HAPPY.includes("yip"), false);
  assert.equal(T.HAPPY.includes("chuff"), false);
  assert.equal(T.HAPPY.includes("nuzzle"), false);
  assert.equal(T.HAPPY.includes("woof"), false);
  assert.equal(T.HAPPY.includes("bray"), false);
  assert.equal(T.HAPPY.includes("beak"), false);
  assert.equal(T.HAPPY.includes("shimmy"), false);
  assert.equal(T.HAPPY.includes("squawk"), false);
  assert.equal(T.HAPPY.includes("bravo"), false);
  assert.equal(T.HAPPY.includes("scissor"), false);
  assert.equal(T.HAPPY.includes("chitter"), false);
  assert.equal(T.HAPPY.includes("bounce"), false);
  assert.equal(T.HAPPY.includes("shuffle"), false);
  assert.equal(T.HAPPY.includes("nibble"), false);
  assert.equal(T.HAPPY.includes("dook"), false);
  assert.equal(T.HAPPY.includes("kiss"), false);
  assert.equal(T.HAPPY.includes("chuckle"), false);
  assert.equal(T.HAPPY.includes("snort"), false);
  assert.equal(T.HAPPY.includes("soft"), false);
  assert.equal(T.HAPPY.includes("grunt"), false);
  assert.equal(T.pickHappy("wink", 0), "blip");
  assert.notEqual(T.pickHappy("wink", 0.9), "wink");
  assert.equal(Overlay.pickHappy("blip", 0) !== "blip", true);
  assert.equal(T.happyCanStart({ asleep: false, hidden: false, leaving: false, cmd: "idle" }), true);
  assert.equal(T.happyCanStart({ asleep: false, hidden: false, leaving: false, cmd: "idle", card: true }), true);
  assert.equal(T.happyCanStart({ asleep: true, hidden: false, leaving: false, cmd: "idle" }), false);
  assert.equal(T.happyShouldAbort({ cmd: "sleep" }), true);
  assert.equal(T.happyShouldAbort({ cmd: "hide" }), true);
  assert.equal(T.happyShouldAbort({ card: true, cmd: "idle" }), false);
  const wink = T.beginHappy("wink", 80, 1);
  assert.equal(wink.anim, "sit");
  const winkMid = T.stepHappy(wink, 0.4, { cmd: "idle" });
  assert.ok(winkMid.lift !== 0 || Math.abs(winkMid.rot) > 0.5);
  assert.notEqual(winkMid.phase, "done");
  const blip = T.beginHappy("blip", 80, 1);
  assert.equal(blip.anim, "talk");
  const blipMid = T.stepHappy(blip, 0.3, { cmd: "idle" });
  assert.ok(blipMid.lift > 0.2 || Math.abs(blipMid.rot) > 0.5);
  const grinH = T.beginHappy("grin", 80, 1);
  assert.equal(grinH.anim, "play");
  const done = T.stepHappy(wink, T.HAPPY_DUR.wink + 0.1, { cmd: "idle" });
  assert.equal(done.phase, "done");
  const aborted = T.stepHappy(blipMid, 0.1, { asleep: true, cmd: "sleep" });
  assert.equal(aborted.phase, "done");
  assert.equal(aborted.abort, true);
  assert.equal(T.wantsThankYou("axolotl"), true);
  assert.equal(T.wantsThankYou("bloom"), true);
  assert.equal(T.wantsThankYou("hedgehog"), false);
  assert.equal(T.wantsThankYou("burr"), false);
  assert.equal(T.wantsThankYou("chinchilla"), false);
  assert.equal(T.wantsThankYou("floss"), false);
  assert.equal(T.wantsThankYou("ferret"), false);
  assert.equal(T.wantsThankYou("wick"), false);
  assert.equal(T.wantsThankYou("parrot"), false);
  assert.equal(T.wantsThankYou("quill"), false);
  assert.equal(T.wantsThankYou("penguin"), false);
  assert.equal(T.wantsThankYou("peck"), false);
  assert.equal(T.wantsThankYou("fox"), false);
  assert.equal(T.wantsThankYou("rue"), false);
  assert.equal(T.wantsThankYou("budgie"), false);
  assert.equal(T.wantsThankYou("echo"), false);
  assert.equal(T.wantsThankYou("goldfish"), false);
  assert.equal(T.wantsThankYou("coin"), false);
  assert.equal(T.wantsThankYou("turtle"), false);
  assert.equal(T.wantsThankYou("guinea_pig"), false);
  assert.equal(T.wantsThankYou("hamster"), false);
  assert.equal(T.wantsThankYou("dog"), false);
  assert.equal(T.wantsThankYou("cat"), false);
  assert.equal(T.wantsThankYou("rabbit"), false);
  assert.equal(T.wantsThankYou("red_panda"), false);
  assert.equal(T.wantsThankYou("ground_dragon"), false);
  const thanks = T.startThankYou("axolotl", "wink", 80, 1, { cmd: "idle", card: true, windowPlay: true });
  assert.ok(thanks);
  assert.notEqual(thanks.kind, "wink");
  assert.ok(thanks.happy.lift === 0);
  assert.notEqual(thanks.happy.anim, "eat");
  assert.notEqual(thanks.happy.anim, "idle");
  const thanksMid = T.stepHappy(thanks.happy, 0.35, { cmd: "idle", card: true });
  assert.ok(thanksMid.lift !== 0 || Math.abs(thanksMid.rot) > 0.5, "a thank-you winks or blips");
  const blocked = T.startThankYou("axolotl", "blip", 80, 1, { asleep: true, cmd: "idle" });
  assert.equal(blocked, null);
  const other = T.startThankYou("toucan", null, 80, 1, { cmd: "idle" });
  assert.equal(other, null);
  const second = T.startThankYou("axolotl", thanks.kind, 80, 1, { cmd: "idle", card: true });
  assert.ok(second);
  assert.notEqual(second.kind, thanks.kind);
});

test("ground registry keeps prior guests gated; Bloom selectable; no wall/float/bloom-name collision", () => {
  assert.equal(Rui.TRICK_KEY, "red_panda");
  assert.equal(Relay.TRICK_KEY, "relay_dragon");
  assert.equal(Fuse.TRICK_KEY, "fuse_dragon");
  assert.equal(Earth.TRICK_KEY, "ground_dragon");
  assert.equal(Cat.TRICK_KEY, "cat");
  assert.equal(Dog.TRICK_KEY, "dog");
  assert.equal(Rabbit.TRICK_KEY, "rabbit");
  assert.equal(Hamster.TRICK_KEY, "hamster");
  assert.equal(GuineaPig.TRICK_KEY, "guinea_pig");
  assert.equal(Turtle.TRICK_KEY, "turtle");
  assert.equal(Goldfish.TRICK_KEY, "goldfish");
  assert.equal(Budgie.TRICK_KEY, "budgie");
  assert.equal(Fox.TRICK_KEY, "fox");
  assert.equal(Penguin.TRICK_KEY, "penguin");
  assert.equal(Parrot.TRICK_KEY, "parrot");
  assert.equal(Ferret.TRICK_KEY, "ferret");
  assert.equal(Hedgehog.TRICK_KEY, "hedgehog");
  assert.equal(Chinchilla.TRICK_KEY, "chinchilla");
  assert.equal(T.TRICK_KEY, "axolotl");
  assert.deepEqual([...Rui.TRICKS], ["somersault", "lie", "scratch", "wave", "dance"]);
  assert.deepEqual([...Relay.TRICKS], ["click", "latch", "arc", "buzz", "switch"]);
  assert.deepEqual([...Fuse.TRICKS], ["seat", "current", "blow", "reseat"]);
  assert.deepEqual([...Earth.TRICKS], ["lug", "earth", "heave", "bed"]);
  assert.deepEqual([...Cat.TRICKS], ["loaf", "knead", "stretch", "wash", "pounce", "bunting", "mlem"]);
  assert.deepEqual([...Dog.TRICKS], ["wait", "wag", "sniff", "bow", "zoom", "beg", "pant"]);
  assert.deepEqual([...Rabbit.TRICKS], ["flop", "groom", "periscope", "dig", "binky", "rub", "nosh"]);
  assert.deepEqual([...Hamster.TRICKS], ["nest", "cheek", "scurry", "pocket", "reel", "scrub", "seed"]);
  assert.deepEqual([...GuineaPig.TRICKS], ["popcorn", "rumble", "hay", "potato", "zig", "lookout", "teeth"]);
  assert.deepEqual([...Turtle.TRICKS], ["soak", "tuck", "crane", "plod", "paddle", "snorkel", "wipe"]);
  assert.deepEqual([...Goldfish.TRICKS], ["drift", "gulp", "flare", "glint", "dart", "yawn", "forage"]);
  assert.deepEqual([...Budgie.TRICKS], ["preen", "bobble", "mimic", "sidle", "dangle", "beakgrind", "shellout"]);
  assert.deepEqual([...Fox.TRICKS], ["den", "mouser", "stalk", "trot", "prance", "cock", "stash"]);
  assert.deepEqual([...Penguin.TRICKS], ["huddle", "toboggan", "waddle", "porpoise", "trumpet", "rockhop", "ecstatic"]);
  assert.deepEqual([...Parrot.TRICKS], ["quote", "strut", "fan", "crack", "flash", "pineye", "invert"]);
  assert.deepEqual([...Ferret.TRICKS], ["tube", "romp", "steal", "puff", "noodle", "corkscrew", "slink"]);
  assert.deepEqual([...Hedgehog.TRICKS], ["curl", "snuffle", "anoint", "bristle", "root", "trundle", "wheel"]);
  assert.deepEqual([...Chinchilla.TRICKS], ["ash", "bound", "fluff", "chin", "sift", "ricochet", "gnaw"]);
  assert.deepEqual([...T.TRICKS], ["gill", "amble", "mend", "smile", "plume", "sprout", "glop"]);
  assert.equal(T.TRICKS.includes("wall"), false);
  assert.equal(T.TRICKS.includes("float"), false);
  assert.equal(T.TRICKS.includes("bloom"), false);
  assert.equal(T.TRICKS.includes("ash"), false);
  assert.equal(T.TRICKS.includes("ball"), false);
  assert.equal(T.TRICKS.includes("tube"), false);
  assert.equal(T.TRICKS.includes("dig"), false);
  assert.equal(T.TRICKS.includes("puff"), false);
  assert.equal(T.TRICKS.includes("curl"), false);
  assert.equal(Rui.wantsThankYou("chinchilla"), false);
  assert.equal(Relay.wantsThankYou("chinchilla"), false);
  assert.equal(Fuse.wantsThankYou("chinchilla"), false);
  assert.equal(Earth.wantsThankYou("chinchilla"), false);
  assert.equal(Cat.wantsThankYou("chinchilla"), false);
  assert.equal(Dog.wantsThankYou("chinchilla"), false);
  assert.equal(Rabbit.wantsThankYou("chinchilla"), false);
  assert.equal(Hamster.wantsThankYou("chinchilla"), false);
  assert.equal(GuineaPig.wantsThankYou("chinchilla"), false);
  assert.equal(Turtle.wantsThankYou("chinchilla"), false);
  assert.equal(Goldfish.wantsThankYou("chinchilla"), false);
  assert.equal(Budgie.wantsThankYou("chinchilla"), false);
  assert.equal(Fox.wantsThankYou("chinchilla"), false);
  assert.equal(Penguin.wantsThankYou("chinchilla"), false);
  assert.equal(Parrot.wantsThankYou("chinchilla"), false);
  assert.equal(Ferret.wantsThankYou("chinchilla"), false);
  assert.equal(T.wantsThankYou("axolotl"), true);
  assert.equal(T.wantsThankYou("bloom"), true);
  assert.equal(T.wantsThankYou("hedgehog"), false);
  assert.equal(T.wantsThankYou("burr"), false);
  assert.equal(T.wantsThankYou("chinchilla"), false);
  assert.equal(T.wantsThankYou("floss"), false);
  assert.equal(T.wantsThankYou("ferret"), false);
  assert.equal(T.wantsThankYou("wick"), false);
  assert.equal(Rui.sleepHoldFrame("red_panda", 4), 1);
  assert.equal(T.sleepHoldFrame("chinchilla", 4), null);
  globalThis.PetRuiTricks = OverlayRui;
  globalThis.PetRelayTricks = OverlayRelay;
  globalThis.PetFuseTricks = OverlayFuse;
  globalThis.PetEarthTricks = OverlayEarth;
  globalThis.PetCatTricks = OverlayCat;
  globalThis.PetDogTricks = OverlayDog;
  globalThis.PetRabbitTricks = OverlayRabbit;
  globalThis.PetHamsterTricks = OverlayHamster;
  globalThis.PetGuineaPigTricks = OverlayGuineaPig;
  globalThis.PetTurtleTricks = OverlayTurtle;
  globalThis.PetGoldfishTricks = OverlayGoldfish;
  globalThis.PetBudgieTricks = OverlayBudgie;
  globalThis.PetFoxTricks = OverlayFox;
  globalThis.PetPenguinTricks = OverlayPenguin;
  globalThis.PetParrotTricks = OverlayParrot;
  globalThis.PetFerretTricks = OverlayFerret;
  globalThis.PetHedgehogTricks = OverlayHedgehog;
  globalThis.PetAxolotlTricks = Overlay;
globalThis.PetToucanTricks = OverlayToucan;
globalThis.PetIguanaTricks = OverlayIguana;
  globalThis.PetDragonTricks = OverlayDragon;
  globalThis.PetPhoenixTricks = OverlayPhoenix;
  globalThis.PetChinchillaTricks = OverlayChinchilla;
  assert.equal(OverlayGround.tricksFor("red_panda"), OverlayRui);
  assert.equal(OverlayGround.tricksFor("rui"), OverlayRui);
  assert.equal(OverlayGround.tricksFor("relay_dragon"), OverlayRelay);
  assert.equal(OverlayGround.tricksFor("fuse_dragon"), OverlayFuse);
  assert.equal(OverlayGround.tricksFor("ground_dragon"), OverlayEarth);
  assert.equal(OverlayGround.tricksFor("ground"), OverlayEarth);
  assert.equal(OverlayGround.tricksFor("cat"), OverlayCat);
  assert.equal(OverlayGround.tricksFor("miso"), OverlayCat);
  assert.equal(OverlayGround.tricksFor("dog"), OverlayDog);
  assert.equal(OverlayGround.tricksFor("pip"), OverlayDog);
  assert.equal(OverlayGround.tricksFor("rabbit"), OverlayRabbit);
  assert.equal(OverlayGround.tricksFor("thimble"), OverlayRabbit);
  assert.equal(OverlayGround.tricksFor("hamster"), OverlayHamster);
  assert.equal(OverlayGround.tricksFor("clip"), OverlayHamster);
  assert.equal(OverlayGround.tricksFor("guinea_pig"), OverlayGuineaPig);
  assert.equal(OverlayGround.tricksFor("whee"), OverlayGuineaPig);
  assert.equal(OverlayGround.tricksFor("turtle"), OverlayTurtle);
  assert.equal(OverlayGround.tricksFor("ink"), OverlayTurtle);
  assert.equal(OverlayGround.tricksFor("goldfish"), OverlayGoldfish);
  assert.equal(OverlayGround.tricksFor("coin"), OverlayGoldfish);
  assert.equal(OverlayGround.tricksFor("budgie"), OverlayBudgie);
  assert.equal(OverlayGround.tricksFor("echo"), OverlayBudgie);
  assert.equal(OverlayGround.tricksFor("fox"), OverlayFox);
  assert.equal(OverlayGround.tricksFor("rue"), OverlayFox);
  assert.equal(OverlayGround.tricksFor("penguin"), OverlayPenguin);
  assert.equal(OverlayGround.tricksFor("peck"), OverlayPenguin);
  assert.equal(OverlayGround.tricksFor("parrot"), OverlayParrot);
  assert.equal(OverlayGround.tricksFor("quill"), OverlayParrot);
  assert.equal(OverlayGround.tricksFor("ferret"), OverlayFerret);
  assert.equal(OverlayGround.tricksFor("wick"), OverlayFerret);
  assert.equal(OverlayGround.tricksFor("hedgehog"), OverlayHedgehog);
  assert.equal(OverlayGround.tricksFor("burr"), OverlayHedgehog);
  assert.equal(OverlayGround.tricksFor("axolotl"), Overlay);
  assert.equal(OverlayGround.tricksFor("bloom"), Overlay);
  assert.equal(OverlayGround.tricksFor("chinchilla"), OverlayChinchilla);
  assert.equal(OverlayGround.tricksFor("floss"), OverlayChinchilla);
  assert.equal(OverlayGround.tricksFor("bloom"), Overlay);
  assert.equal(OverlayGround.tricksFor("toucan"), OverlayToucan);
  assert.equal(OverlayGround.tricksFor("keel"), OverlayToucan);
  assert.equal(OverlayGround.tricksFor("iguana"), OverlayIguana);
  assert.equal(OverlayGround.tricksFor("sol"), OverlayIguana);
  assert.equal(OverlayGround.tricksFor("dragon"), OverlayDragon);
  assert.equal(OverlayGround.tricksFor("vesper"), OverlayDragon);
  assert.equal(OverlayGround.wantsThankYou("red_panda"), true);
  assert.equal(OverlayGround.wantsThankYou("relay_dragon"), true);
  assert.equal(OverlayGround.wantsThankYou("fuse_dragon"), true);
  assert.equal(OverlayGround.wantsThankYou("ground_dragon"), true);
  assert.equal(OverlayGround.wantsThankYou("cat"), true);
  assert.equal(OverlayGround.wantsThankYou("miso"), true);
  assert.equal(OverlayGround.wantsThankYou("dog"), true);
  assert.equal(OverlayGround.wantsThankYou("pip"), true);
  assert.equal(OverlayGround.wantsThankYou("rabbit"), true);
  assert.equal(OverlayGround.wantsThankYou("thimble"), true);
  assert.equal(OverlayGround.wantsThankYou("hamster"), true);
  assert.equal(OverlayGround.wantsThankYou("clip"), true);
  assert.equal(OverlayGround.wantsThankYou("guinea_pig"), true);
  assert.equal(OverlayGround.wantsThankYou("whee"), true);
  assert.equal(OverlayGround.wantsThankYou("turtle"), true);
  assert.equal(OverlayGround.wantsThankYou("ink"), true);
  assert.equal(OverlayGround.wantsThankYou("goldfish"), true);
  assert.equal(OverlayGround.wantsThankYou("coin"), true);
  assert.equal(OverlayGround.wantsThankYou("budgie"), true);
  assert.equal(OverlayGround.wantsThankYou("echo"), true);
  assert.equal(OverlayGround.wantsThankYou("fox"), true);
  assert.equal(OverlayGround.wantsThankYou("rue"), true);
  assert.equal(OverlayGround.wantsThankYou("penguin"), true);
  assert.equal(OverlayGround.wantsThankYou("peck"), true);
  assert.equal(OverlayGround.wantsThankYou("parrot"), true);
  assert.equal(OverlayGround.wantsThankYou("quill"), true);
  assert.equal(OverlayGround.wantsThankYou("ferret"), true);
  assert.equal(OverlayGround.wantsThankYou("wick"), true);
  assert.equal(OverlayGround.wantsThankYou("hedgehog"), true);
  assert.equal(OverlayGround.wantsThankYou("burr"), true);
  assert.equal(OverlayGround.wantsThankYou("axolotl"), true);
  assert.equal(OverlayGround.wantsThankYou("bloom"), true);
  assert.equal(OverlayGround.wantsThankYou("toucan"), true);
  assert.equal(OverlayGround.wantsThankYou("keel"), true);
  assert.equal(OverlayGround.wantsThankYou("iguana"), true);
  assert.equal(OverlayGround.wantsThankYou("sol"), true);
  assert.equal(OverlayGround.wantsThankYou("dragon"), true);
  assert.equal(OverlayGround.wantsThankYou("vesper"), true);
  assert.equal(OverlayGround.sleepHoldFrame("red_panda", 4), 1);
  assert.equal(OverlayGround.sleepHoldFrame("dog", 4), null);
  assert.equal(OverlayGround.sleepHoldFrame("cat", 4), null);
  assert.equal(OverlayGround.sleepHoldFrame("rabbit", 4), null);
  assert.equal(OverlayGround.sleepHoldFrame("hamster", 4), null);
  assert.equal(OverlayGround.sleepHoldFrame("guinea_pig", 4), null);
  assert.equal(OverlayGround.sleepHoldFrame("turtle", 4), null);
  assert.equal(OverlayGround.sleepHoldFrame("goldfish", 4), null);
  assert.equal(OverlayGround.sleepHoldFrame("budgie", 4), null);
  assert.equal(OverlayGround.sleepHoldFrame("fox", 4), null);
  assert.equal(OverlayGround.sleepHoldFrame("penguin", 4), null);
  assert.equal(OverlayGround.sleepHoldFrame("parrot", 4), null);
  assert.equal(OverlayGround.sleepHoldFrame("ferret", 4), null);
  assert.equal(OverlayGround.sleepHoldFrame("hedgehog", 4), null);
  assert.equal(OverlayGround.sleepHoldFrame("axolotl", 4), null);
  assert.equal(OverlayGround.sleepHoldFrame("toucan", 4), null);
  assert.equal(OverlayGround.sleepHoldFrame("iguana", 4), null);
  assert.equal(OverlayGround.sleepHoldFrame("dragon", 4), null);
});


test("ultra-polish: Bloom gill/amble/sprout/glop lifts are Rui-visible (not micro idle-gen)", () => {
  const ex = T.beginTrick("gill", 80, 1);
  const mid = T.stepTrick(ex, 5, { cmd: "idle" });
  assert.ok(Math.abs(mid.rot) > 10, `gill mid rot ${mid.rot}`);
  assert.ok(Math.abs(mid.lift) > 0.5, `gill mid lift ${mid.lift}`);
  const am = T.beginTrick("amble", 80, 1);
  const a2 = T.stepTrick(am, T.DUR.amble * 0.4, { cmd: "idle" });
  assert.ok(a2.lift > 4 || Math.abs(a2.rot) > 4, `amble mid lift/rot ${a2.lift}/${a2.rot}`);
  const sp = T.beginTrick("sprout", 80, 1);
  const s2 = T.stepTrick(sp, T.DUR.sprout * 0.4, { cmd: "idle" });
  assert.ok(s2.lift > 6 || Math.abs(s2.rot) > 6, `sprout mid lift/rot ${s2.lift}/${s2.rot}`);
  const gl = T.beginTrick("glop", 80, 1);
  const g2 = T.stepTrick(gl, T.DUR.glop * 0.45, { cmd: "idle" });
  assert.ok(Math.abs(g2.lift) > 2 || Math.abs(g2.rot) > 4, `glop mid lift/rot ${g2.lift}/${g2.rot}`);
  assert.ok(Overlay.sproutPose && Overlay.glopPose);
  assert.deepEqual([...T.TRICKS], [...Overlay.TRICKS]);
  assert.equal(T.DUR.sprout, Overlay.DUR.sprout);
  assert.equal(T.DUR.glop, Overlay.DUR.glop);
  assert.equal(T.GILL_HOLD, Overlay.GILL_HOLD);
  assert.equal(T.HAPPY_DUR.wink, Overlay.HAPPY_DUR.wink);
});

test("notes: Bloom idle-life ultra done; Sol / iguana + Vesper / dragon + Nori / ball_python + Saffron / corn_snake ultra next-or-done; following house-order ultra guest is Bandit / kingsnake (birds Soot→Ember + Miso + Pip + Thimble + Clip + Whee + Ink + Coin + Rue + Wick + Burr + Floss already ultra; Echo/budgie + Peck/penguin + Quill/parrot + Keel/toucan + Ember skip bird)", () => {
  assert.deepEqual([...T.TRICKS], ["gill", "amble", "mend", "smile", "plume", "sprout", "glop"]);
  assert.equal(T.TRICK_KEY, "axolotl");
  assert.equal(T.wantsThankYou("bloom"), true);
  assert.equal(OverlayGround.tricksFor("toucan"), OverlayToucan);
  assert.equal(OverlayGround.tricksFor("keel"), OverlayToucan);
  assert.equal(OverlayGround.tricksFor("iguana"), OverlayIguana);
  assert.equal(OverlayGround.tricksFor("sol"), OverlayIguana);
  assert.equal(OverlayGround.tricksFor("dragon"), OverlayDragon);
  assert.equal(OverlayGround.wantsThankYou("toucan"), true);
  assert.equal(OverlayGround.wantsThankYou("keel"), true);
  assert.equal(OverlayGround.wantsThankYou("iguana"), true);
  assert.equal(OverlayGround.wantsThankYou("sol"), true);
  assert.equal(OverlayGround.wantsThankYou("dragon"), true);
  assert.equal(OverlayGround.tricksFor("phoenix"), OverlayPhoenix);
  assert.equal(OverlayGround.wantsThankYou("phoenix"), true);
});

