import assert from "node:assert/strict";
import { createRequire } from "node:module";
import { dirname, join } from "node:path";
import { test } from "node:test";
import { fileURLToPath, pathToFileURL } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const T = await import(pathToFileURL(join(root, "src/lib/pets/ball-python-tricks.ts")).href);
const Phoenix = await import(pathToFileURL(join(root, "src/lib/pets/phoenix-tricks.ts")).href);
const Dragon = await import(pathToFileURL(join(root, "src/lib/pets/dragon-tricks.ts")).href);
const Rui = await import(pathToFileURL(join(root, "src/lib/pets/rui-tricks.ts")).href);
const Relay = await import(pathToFileURL(join(root, "src/lib/pets/relay-tricks.ts")).href);
const Fuse = await import(pathToFileURL(join(root, "src/lib/pets/fuse-tricks.ts")).href);
const Earth = await import(pathToFileURL(join(root, "src/lib/pets/earth-tricks.ts")).href);
const Cat = await import(pathToFileURL(join(root, "src/lib/pets/cat-tricks.ts")).href);
const Dog = await import(pathToFileURL(join(root, "src/lib/pets/dog-tricks.ts")).href);
const Rabbit = await import(pathToFileURL(join(root, "src/lib/pets/rabbit-tricks.ts")).href);
const Hamster = await import(pathToFileURL(join(root, "src/lib/pets/hamster-tricks.ts")).href);
const GuineaPig = await import(pathToFileURL(join(root, "src/lib/pets/guinea-pig-tricks.ts")).href);
const Turtle = await import(pathToFileURL(join(root, "src/lib/pets/turtle-tricks.ts")).href);
const Goldfish = await import(pathToFileURL(join(root, "src/lib/pets/goldfish-tricks.ts")).href);
const Budgie = await import(pathToFileURL(join(root, "src/lib/pets/budgie-tricks.ts")).href);
const Fox = await import(pathToFileURL(join(root, "src/lib/pets/fox-tricks.ts")).href);
const Penguin = await import(pathToFileURL(join(root, "src/lib/pets/penguin-tricks.ts")).href);
const Parrot = await import(pathToFileURL(join(root, "src/lib/pets/parrot-tricks.ts")).href);
const Ferret = await import(pathToFileURL(join(root, "src/lib/pets/ferret-tricks.ts")).href);
const Hedgehog = await import(pathToFileURL(join(root, "src/lib/pets/hedgehog-tricks.ts")).href);
const Chinchilla = await import(pathToFileURL(join(root, "src/lib/pets/chinchilla-tricks.ts")).href);
const Axolotl = await import(pathToFileURL(join(root, "src/lib/pets/axolotl-tricks.ts")).href);
const Toucan = await import(pathToFileURL(join(root, "src/lib/pets/toucan-tricks.ts")).href);
const Iguana = await import(pathToFileURL(join(root, "src/lib/pets/iguana-tricks.ts")).href);
const Overlay = createRequire(import.meta.url)(join(root, "../desktop/renderer/ball-python-tricks.js"));
const OverlayPhoenix = createRequire(import.meta.url)(join(root, "../desktop/renderer/phoenix-tricks.js"));
const OverlayGround = createRequire(import.meta.url)(join(root, "../desktop/renderer/ground-tricks.js"));
const OverlayRui = createRequire(import.meta.url)(join(root, "../desktop/renderer/rui-tricks.js"));
const OverlayRelay = createRequire(import.meta.url)(join(root, "../desktop/renderer/relay-tricks.js"));
const OverlayFuse = createRequire(import.meta.url)(join(root, "../desktop/renderer/fuse-tricks.js"));
const OverlayEarth = createRequire(import.meta.url)(join(root, "../desktop/renderer/earth-tricks.js"));
const OverlayCat = createRequire(import.meta.url)(join(root, "../desktop/renderer/cat-tricks.js"));
const OverlayDog = createRequire(import.meta.url)(join(root, "../desktop/renderer/dog-tricks.js"));
const OverlayRabbit = createRequire(import.meta.url)(join(root, "../desktop/renderer/rabbit-tricks.js"));
const OverlayHamster = createRequire(import.meta.url)(join(root, "../desktop/renderer/hamster-tricks.js"));
const OverlayGuineaPig = createRequire(import.meta.url)(join(root, "../desktop/renderer/guinea-pig-tricks.js"));
const OverlayTurtle = createRequire(import.meta.url)(join(root, "../desktop/renderer/turtle-tricks.js"));
const OverlayGoldfish = createRequire(import.meta.url)(join(root, "../desktop/renderer/goldfish-tricks.js"));
const OverlayBudgie = createRequire(import.meta.url)(join(root, "../desktop/renderer/budgie-tricks.js"));
const OverlayFox = createRequire(import.meta.url)(join(root, "../desktop/renderer/fox-tricks.js"));
const OverlayPenguin = createRequire(import.meta.url)(join(root, "../desktop/renderer/penguin-tricks.js"));
const OverlayParrot = createRequire(import.meta.url)(join(root, "../desktop/renderer/parrot-tricks.js"));
const OverlayFerret = createRequire(import.meta.url)(join(root, "../desktop/renderer/ferret-tricks.js"));
const OverlayHedgehog = createRequire(import.meta.url)(join(root, "../desktop/renderer/hedgehog-tricks.js"));
const OverlayChinchilla = createRequire(import.meta.url)(join(root, "../desktop/renderer/chinchilla-tricks.js"));
const OverlayAxolotl = createRequire(import.meta.url)(join(root, "../desktop/renderer/axolotl-tricks.js"));
const OverlayToucan = createRequire(import.meta.url)(join(root, "../desktop/renderer/toucan-tricks.js"));
const OverlayIguana = createRequire(import.meta.url)(join(root, "../desktop/renderer/iguana-tricks.js"));
const OverlayDragon = createRequire(import.meta.url)(join(root, "../desktop/renderer/dragon-tricks.js"));

test("Nori tricks start only on idle ground", () => {
  assert.deepEqual([...Phoenix.TRICKS], ["cinder", "blaze", "shed", "lift", "return", "reignite", "hearth"]);
  assert.deepEqual([...T.TRICKS], ["orb", "nook", "taste", "inch", "unroll", "loom", "weave"]);
  assert.equal(T.canStart({ asleep: false, hidden: false, leaving: false, cmd: "idle" }), true);
  assert.equal(T.canStart({ asleep: true, hidden: false, leaving: false, cmd: "idle" }), false);
  assert.equal(T.canStart({ asleep: false, hidden: true, leaving: false, cmd: "idle" }), false);
  assert.equal(T.canStart({ asleep: false, hidden: false, leaving: false, cmd: "sleep" }), false);
  assert.equal(T.canStart({ asleep: false, hidden: false, leaving: false, cmd: "seek" }), false);
  assert.equal(T.canStart({ asleep: false, hidden: false, leaving: false, cmd: "idle", windowPlay: true }), false);
  assert.equal(T.canStart({ asleep: false, hidden: false, leaving: false, cmd: "idle", card: true }), false);
  assert.equal(T.shouldAbort({ asleep: true, hidden: false, leaving: false, cmd: "idle" }), true);
  assert.equal(T.shouldAbort({ asleep: false, hidden: false, leaving: false, cmd: "idle", card: true }), true);
  assert.equal(T.shouldAbort({ asleep: false, hidden: false, leaving: false, cmd: "idle" }), false);
  assert.equal(T.pickTrick(0.99, true), "orb");
  assert.notEqual(T.pickTrick(0.3, false, "orb"), "cinder");
  assert.equal(Overlay.TRICK_KEY, "ball_python");
  assert.equal(T.sleepHoldFrame("ball_python", 4), null);
  assert.equal(T.TRICKS.includes("bun"), false);
  assert.equal(T.TRICKS.includes("flatten"), false);
  assert.equal(T.TRICKS.includes("bask"), false);
  assert.equal(T.TRICKS.includes("flash"), false);
  assert.equal(T.TRICKS.includes("fan"), false);
  assert.equal(T.TRICKS.includes("quote"), false);
  assert.equal(T.TRICKS.includes("strut"), false);
  assert.equal(T.TRICKS.includes("crack"), false);
  assert.equal(T.TRICKS.includes("preen"), false);
  assert.equal(T.TRICKS.includes("beak"), false);
  assert.equal(T.TRICKS.includes("gill"), false);
  assert.equal(T.TRICKS.includes("plume"), false);
  assert.equal(T.TRICKS.includes("ash"), false);
  assert.equal(T.TRICKS.includes("tube"), false);
  assert.equal(T.TRICKS.includes("dig"), false);
  assert.equal(T.TRICKS.includes("potato"), false);
  assert.equal(T.TRICKS.includes("tuck"), false);
  assert.equal(T.TRICKS.includes("loaf"), false);
  assert.equal(T.TRICKS.includes("nest"), false);
  assert.equal(T.TRICKS.includes("scurry"), false);
  assert.equal(T.TRICKS.includes("den"), false);
  assert.equal(T.TRICKS.includes("zoom"), false);
  assert.equal(T.TRICKS.includes("dance"), false);
  assert.equal(T.TRICKS.includes("pounce"), false);
  assert.equal(T.TRICKS.includes("thread"), false);
  assert.equal(T.TRICKS.includes("hook"), false);
  assert.equal(T.TRICKS.includes("perch"), false);
  assert.equal(T.TRICKS.includes("popcorn"), false);
  assert.equal(T.TRICKS.includes("groom"), false);
});

test("orb/nook/taste/inch/unroll/loom/weave are house-ball-python-true, not Rui cat dog rabbit hamster guinea-pig turtle goldfish budgie fox penguin parrot ferret hedgehog chinchilla axolotl toucan iguana dragon/Vesper phoenix/Ember or electrical-dragon clones", () => {
  const ground = { asleep: false, hidden: false, leaving: false, cmd: "idle" };
  const orb = T.beginTrick("orb", 80, 1);
  assert.equal(orb.anim, "sit");
  assert.equal(orb.phase, "hold");
  const held = T.stepTrick(orb, 5, ground);
  assert.equal(held.phase, "hold");
  assert.equal(held.anim, "sit");
  assert.ok(held.rot !== 0 || Math.abs(held.lift) > 0.5);
  const release = T.stepTrick(orb, T.ORB_HOLD + 0.2, ground);
  assert.equal(release.phase, "release");
  assert.equal(release.anim, "sit");
  const doneOrb = T.stepTrick(orb, T.DUR.orb + 0.1, ground);
  assert.equal(doneOrb.phase, "done");
  assert.ok(T.nextTrickWait(true, 0, "orb") > T.nextTrickWait(true, 0, "nook"));
  const nook = T.beginTrick("nook", 80, 1);
  assert.equal(nook.anim, "sit");
  const nookMid = T.stepTrick(nook, 0.55, ground);
  assert.ok(Math.abs(nookMid.lift) > 0.2 || Math.abs(nookMid.rot) > 1);
  const taste = T.beginTrick("taste", 80, 1);
  assert.equal(taste.anim, "talk");
  const tasteMid = T.stepTrick(taste, 0.5, ground);
  assert.ok(Math.abs(tasteMid.lift) > 0.3 || Math.abs(tasteMid.rot) > 1);
  const inch = T.beginTrick("inch", 80, 1);
  assert.equal(inch.anim, "play");
  const inchMid = T.stepTrick(inch, 0.4, ground);
  assert.ok(Math.abs(inchMid.lift) > 0.2 || Math.abs(inchMid.rot) > 1);
  const unroll = T.beginTrick("unroll", 80, 1);
  assert.equal(unroll.anim, "play");
  const unrollMid = T.stepTrick(unroll, 0.5, ground);
  assert.ok(Math.abs(unrollMid.lift) > 0.3 || Math.abs(unrollMid.rot) > 1);
  const unrollDone = T.stepTrick(unroll, T.DUR.unroll + 0.1, ground);
  assert.equal(unrollDone.phase, "done");
  const loom = T.beginTrick("loom", 80, 1);
  assert.equal(loom.anim, "talk");
  const loomMid = T.stepTrick(loom, T.DUR.loom * 0.4, ground);
  assert.ok(loomMid.lift > 4 || Math.abs(loomMid.rot) > 6);
  const weave = T.beginTrick("weave", 80, 1);
  assert.equal(weave.anim, "play");
  const weaveMid = T.stepTrick(weave, T.DUR.weave * 0.45, ground);
  assert.ok(Math.abs(weaveMid.lift) > 2 || Math.abs(weaveMid.rot) > 4 || Math.abs(weaveMid.x - 80) > 2);
  assert.equal(T.TRICKS.includes("bun"), false);
  assert.equal(T.TRICKS.includes("ball"), false);
  assert.equal(T.TRICKS.includes("coil"), false);
  assert.equal(T.TRICKS.includes("curl"), false);
  assert.equal(T.TRICKS.includes("periscope"), false);
  const aborted = T.stepTrick(held, 0.1, { asleep: true, cmd: "sleep" });
  assert.equal(aborted.phase, "done");
  assert.equal(Rui.TRICKS.includes("orb"), false);
  assert.equal(Cat.TRICKS.includes("nook"), false);
  assert.equal(Dog.TRICKS.includes("taste"), false);
  assert.equal(Rabbit.TRICKS.includes("inch"), false);
  assert.equal(Hamster.TRICKS.includes("unroll"), false);
  assert.equal(GuineaPig.TRICKS.includes("orb"), false);
  assert.equal(Turtle.TRICKS.includes("nook"), false);
  assert.equal(Goldfish.TRICKS.includes("taste"), false);
  assert.equal(Budgie.TRICKS.includes("inch"), false);
  assert.equal(Fox.TRICKS.includes("unroll"), false);
  assert.equal(Penguin.TRICKS.includes("orb"), false);
  assert.equal(Parrot.TRICKS.includes("nook"), false);
  assert.equal(Ferret.TRICKS.includes("taste"), false);
  assert.equal(Relay.TRICKS.includes("orb"), false);
  assert.equal(Fuse.TRICKS.includes("nook"), false);
  assert.equal(Earth.TRICKS.includes("taste"), false);
  assert.equal(Hedgehog.TRICKS.includes("orb"), false);
  assert.equal(Chinchilla.TRICKS.includes("nook"), false);
  assert.equal(Axolotl.TRICKS.includes("orb"), false);
  assert.equal(Axolotl.TRICKS.includes("nook"), false);
  assert.equal(Axolotl.TRICKS.includes("taste"), false);
  assert.equal(Axolotl.TRICKS.includes("inch"), false);
  assert.equal(Axolotl.TRICKS.includes("unroll"), false);
  assert.equal(Toucan.TRICKS.includes("orb"), false);
  assert.equal(Toucan.TRICKS.includes("nook"), false);
  assert.equal(Toucan.TRICKS.includes("taste"), false);
  assert.equal(Toucan.TRICKS.includes("inch"), false);
  assert.equal(Toucan.TRICKS.includes("unroll"), false);
  
  assert.equal(Iguana.TRICKS.includes("orb"), false);
  assert.equal(Iguana.TRICKS.includes("nook"), false);
  assert.equal(Iguana.TRICKS.includes("taste"), false);
  assert.equal(Iguana.TRICKS.includes("inch"), false);
  assert.equal(Iguana.TRICKS.includes("unroll"), false);
  assert.equal(Dragon.TRICKS.includes("orb"), false);
  assert.equal(Dragon.TRICKS.includes("nook"), false);
  assert.equal(Dragon.TRICKS.includes("taste"), false);
  assert.equal(Dragon.TRICKS.includes("inch"), false);
  assert.equal(Dragon.TRICKS.includes("unroll"), false);
  assert.deepEqual([...Dragon.TRICKS], ["sprawl", "guard", "smolder", "claim", "fold", "ruff", "scrape"]);
  assert.equal(Phoenix.TRICKS.includes("orb"), false);
  assert.equal(Phoenix.TRICKS.includes("nook"), false);
  assert.equal(Phoenix.TRICKS.includes("taste"), false);
  assert.equal(Phoenix.TRICKS.includes("inch"), false);
  assert.equal(Phoenix.TRICKS.includes("unroll"), false);
  assert.deepEqual([...Phoenix.TRICKS], ["cinder", "blaze", "shed", "lift", "return", "reignite", "hearth"]);
  assert.equal(T.TRICKS.includes("bun"), false);
  assert.equal(T.TRICKS.includes("ball"), false);
  assert.equal(T.TRICKS.includes("coil"), false);
  assert.equal(T.TRICKS.includes("curl"), false);
  assert.equal(T.TRICKS.includes("hoard"), false);
  assert.equal(T.TRICKS.includes("sun"), false);
  assert.equal(T.TRICKS.includes("click"), false);
  assert.equal(Parrot.TRICKS.includes("flash"), true);
  assert.equal(T.TRICKS.includes("flatten"), false);
  assert.equal(T.TRICKS.includes("flash"), false);
  assert.equal(T.TRICKS.includes("fan"), false);
  assert.equal(T.TRICKS.includes("bask"), false);
  assert.equal(T.TRICKS.includes("gill"), false);
});

test("Nori feed-happy is its own sit: savor/nestle/center, and two feeds are not the same", () => {
  assert.deepEqual([...T.HAPPY], ["savor", "nestle", "center"]);
  assert.equal(T.HAPPY.includes("settle"), false);
  assert.equal(T.HAPPY.includes("thrum"), false);
  assert.equal(T.HAPPY.includes("glow"), false);
  assert.equal(T.HAPPY.includes("incline"), false);
  assert.equal(T.HAPPY.includes("swell"), false);
  assert.equal(T.HAPPY.includes("purr"), false);
  assert.equal(T.HAPPY.includes("tail"), false);
  assert.equal(T.HAPPY.includes("tilt"), false);
  assert.equal(T.HAPPY.includes("twitch"), false);
  assert.equal(T.HAPPY.includes("stuff"), false);
  assert.equal(T.HAPPY.includes("peep"), false);
  assert.equal(T.HAPPY.includes("munch"), false);
  assert.equal(T.HAPPY.includes("huff"), false);
  assert.equal(T.HAPPY.includes("gleam"), false);
  assert.equal(T.HAPPY.includes("bubble"), false);
  assert.equal(T.HAPPY.includes("chirp"), false);
  assert.equal(T.HAPPY.includes("chatter"), false);
  assert.equal(T.HAPPY.includes("bob"), false);
  assert.equal(T.HAPPY.includes("whistle"), false);
  assert.equal(T.HAPPY.includes("trill"), false);
  assert.equal(T.HAPPY.includes("ruffle"), false);
  assert.equal(T.HAPPY.includes("yip"), false);
  assert.equal(T.HAPPY.includes("chuff"), false);
  assert.equal(T.HAPPY.includes("nuzzle"), false);
  assert.equal(T.HAPPY.includes("woof"), false);
  assert.equal(T.HAPPY.includes("bray"), false);
  assert.equal(T.HAPPY.includes("beak"), false);
  assert.equal(T.HAPPY.includes("shimmy"), false);
  assert.equal(T.HAPPY.includes("squawk"), false);
  assert.equal(T.HAPPY.includes("bravo"), false);
  assert.equal(T.HAPPY.includes("scissor"), false);
  assert.equal(T.HAPPY.includes("chitter"), false);
  assert.equal(T.HAPPY.includes("bounce"), false);
  assert.equal(T.HAPPY.includes("shuffle"), false);
  assert.equal(T.HAPPY.includes("nibble"), false);
  assert.equal(T.HAPPY.includes("dook"), false);
  assert.equal(T.HAPPY.includes("kiss"), false);
  assert.equal(T.HAPPY.includes("chuckle"), false);
  assert.equal(T.HAPPY.includes("snort"), false);
  assert.equal(T.HAPPY.includes("soft"), false);
  assert.equal(T.HAPPY.includes("grunt"), false);
  assert.equal(T.HAPPY.includes("wink"), false);
  assert.equal(T.HAPPY.includes("blip"), false);
  assert.equal(T.HAPPY.includes("grin"), false);
  assert.equal(T.HAPPY.includes("eep"), false);
  assert.equal(T.HAPPY.includes("coo"), false);
  assert.equal(T.HAPPY.includes("bark"), false);
  assert.equal(T.HAPPY.includes("croak"), false);
  assert.equal(T.HAPPY.includes("tip"), false);
  assert.equal(T.HAPPY.includes("clack"), false);
  assert.equal(T.HAPPY.includes("yelp"), false);
  assert.equal(T.HAPPY.includes("tok"), false);
  assert.equal(T.pickHappy("savor", 0), "nestle");
  assert.notEqual(T.pickHappy("savor", 0.9), "savor");
  assert.equal(Overlay.pickHappy("nestle", 0) !== "nestle", true);
  assert.equal(T.happyCanStart({ asleep: false, hidden: false, leaving: false, cmd: "idle" }), true);
  assert.equal(T.happyCanStart({ asleep: false, hidden: false, leaving: false, cmd: "idle", card: true }), true);
  assert.equal(T.happyCanStart({ asleep: true, hidden: false, leaving: false, cmd: "idle" }), false);
  assert.equal(T.happyShouldAbort({ cmd: "sleep" }), true);
  assert.equal(T.happyShouldAbort({ cmd: "hide" }), true);
  assert.equal(T.happyShouldAbort({ card: true, cmd: "idle" }), false);
  const savor = T.beginHappy("savor", 80, 1);
  assert.equal(savor.anim, "sit");
  const savorMid = T.stepHappy(savor, 0.4, { cmd: "idle" });
  assert.ok(savorMid.lift !== 0 || Math.abs(savorMid.rot) > 0.5);
  assert.notEqual(savorMid.phase, "done");
  const nestle = T.beginHappy("nestle", 80, 1);
  assert.equal(nestle.anim, "sit");
  const nestleMid = T.stepHappy(nestle, 0.3, { cmd: "idle" });
  assert.ok(nestleMid.lift > 0.2 || Math.abs(nestleMid.rot) > 0.5);
  const centerH = T.beginHappy("center", 80, 1);
  assert.equal(centerH.anim, "talk");
  const done = T.stepHappy(savor, T.HAPPY_DUR.savor + 0.1, { cmd: "idle" });
  assert.equal(done.phase, "done");
  const aborted = T.stepHappy(nestleMid, 0.1, { asleep: true, cmd: "sleep" });
  assert.equal(aborted.phase, "done");
  assert.equal(aborted.abort, true);
  assert.equal(T.wantsThankYou("ball_python"), true);
  assert.equal(T.wantsThankYou("nori"), true);
  assert.equal(T.wantsThankYou("axolotl"), false);
  assert.equal(T.wantsThankYou("bloom"), false);
  assert.equal(T.wantsThankYou("hedgehog"), false);
  assert.equal(T.wantsThankYou("burr"), false);
  assert.equal(T.wantsThankYou("chinchilla"), false);
  assert.equal(T.wantsThankYou("floss"), false);
  assert.equal(T.wantsThankYou("ferret"), false);
  assert.equal(T.wantsThankYou("wick"), false);
  assert.equal(T.wantsThankYou("parrot"), false);
  assert.equal(T.wantsThankYou("quill"), false);
  assert.equal(T.wantsThankYou("penguin"), false);
  assert.equal(T.wantsThankYou("peck"), false);
  assert.equal(T.wantsThankYou("fox"), false);
  assert.equal(T.wantsThankYou("rue"), false);
  assert.equal(T.wantsThankYou("budgie"), false);
  assert.equal(T.wantsThankYou("echo"), false);
  assert.equal(T.wantsThankYou("goldfish"), false);
  assert.equal(T.wantsThankYou("coin"), false);
  assert.equal(T.wantsThankYou("turtle"), false);
  assert.equal(T.wantsThankYou("guinea_pig"), false);
  assert.equal(T.wantsThankYou("hamster"), false);
  assert.equal(T.wantsThankYou("dog"), false);
  assert.equal(T.wantsThankYou("cat"), false);
  assert.equal(T.wantsThankYou("rabbit"), false);
  assert.equal(T.wantsThankYou("red_panda"), false);
  assert.equal(T.wantsThankYou("ground_dragon"), false);
  const thanks = T.startThankYou("ball_python", "savor", 80, 1, { cmd: "idle", card: true, windowPlay: true });
  assert.ok(thanks);
  assert.notEqual(thanks.kind, "savor");
  assert.ok(thanks.happy.lift === 0);
  assert.notEqual(thanks.happy.anim, "eat");
  assert.notEqual(thanks.happy.anim, "idle");
  const thanksMid = T.stepHappy(thanks.happy, 0.35, { cmd: "idle", card: true });
  assert.ok(thanksMid.lift !== 0 || Math.abs(thanksMid.rot) > 0.5, "a thank-you savors or nestles");
  const blocked = T.startThankYou("ball_python", "nestle", 80, 1, { asleep: true, cmd: "idle" });
  assert.equal(blocked, null);
  const other = T.startThankYou("phoenix", null, 80, 1, { cmd: "idle" });
  assert.equal(other, null);
  const second = T.startThankYou("ball_python", thanks.kind, 80, 1, { cmd: "idle", card: true });
  assert.ok(second);
  assert.notEqual(second.kind, thanks.kind);
});

test("ground registry keeps prior guests gated; Nori selectable; no bun/ball/coil/curl/settle name collisions; prior guests still OK", () => {
  assert.equal(Rui.TRICK_KEY, "red_panda");
  assert.equal(Relay.TRICK_KEY, "relay_dragon");
  assert.equal(Fuse.TRICK_KEY, "fuse_dragon");
  assert.equal(Earth.TRICK_KEY, "ground_dragon");
  assert.equal(Cat.TRICK_KEY, "cat");
  assert.equal(Dog.TRICK_KEY, "dog");
  assert.equal(Rabbit.TRICK_KEY, "rabbit");
  assert.equal(Hamster.TRICK_KEY, "hamster");
  assert.equal(GuineaPig.TRICK_KEY, "guinea_pig");
  assert.equal(Turtle.TRICK_KEY, "turtle");
  assert.equal(Goldfish.TRICK_KEY, "goldfish");
  assert.equal(Budgie.TRICK_KEY, "budgie");
  assert.equal(Fox.TRICK_KEY, "fox");
  assert.equal(Penguin.TRICK_KEY, "penguin");
  assert.equal(Parrot.TRICK_KEY, "parrot");
  assert.equal(Ferret.TRICK_KEY, "ferret");
  assert.equal(Hedgehog.TRICK_KEY, "hedgehog");
  assert.equal(Chinchilla.TRICK_KEY, "chinchilla");
  assert.equal(Axolotl.TRICK_KEY, "axolotl");
  assert.equal(Toucan.TRICK_KEY, "toucan");
  assert.equal(Iguana.TRICK_KEY, "iguana");
  assert.equal(T.TRICK_KEY, "ball_python");
  assert.deepEqual([...Rui.TRICKS], ["somersault", "lie", "scratch", "wave", "dance"]);
  assert.deepEqual([...Relay.TRICKS], ["contactclick", "latchseat", "arcflick", "coilbuzz", "poleswitch", "armaturetap", "relayhush"]);
  assert.deepEqual([...Fuse.TRICKS], ["railseat", "holdcurrent", "blowclear", "reseatsnap", "cartridgerattle", "bladeflash", "fusehush"]);
  assert.deepEqual([...Earth.TRICKS], ["lugstrap", "earthseat", "heaveplate", "bedsettle", "soilgrip", "plateclamp", "groundhush"]);
  assert.deepEqual([...Cat.TRICKS], ["loaf", "knead", "stretch", "wash", "pounce", "bunting", "mlem"]);
  assert.deepEqual([...Dog.TRICKS], ["wait", "wag", "sniff", "bow", "zoom", "beg", "pant"]);
  assert.deepEqual([...Rabbit.TRICKS], ["flop", "groom", "periscope", "dig", "binky", "rub", "nosh"]);
  assert.deepEqual([...Hamster.TRICKS], ["nest", "cheek", "scurry", "pocket", "reel", "scrub", "seed"]);
  assert.deepEqual([...GuineaPig.TRICKS], ["popcorn", "rumble", "hay", "potato", "zig", "lookout", "teeth"]);
  assert.deepEqual([...Turtle.TRICKS], ["soak", "tuck", "crane", "plod", "paddle", "snorkel", "wipe"]);
  assert.deepEqual([...Goldfish.TRICKS], ["drift", "gulp", "flare", "glint", "dart", "yawn", "forage"]);
  assert.deepEqual([...Budgie.TRICKS], ["preen", "bobble", "mimic", "sidle", "dangle", "beakgrind", "shellout"]);
  assert.deepEqual([...Fox.TRICKS], ["den", "mouser", "stalk", "trot", "prance", "cock", "stash"]);
  assert.deepEqual([...Penguin.TRICKS], ["huddle", "toboggan", "waddle", "porpoise", "trumpet", "rockhop", "ecstatic"]);
  assert.deepEqual([...Parrot.TRICKS], ["quote", "strut", "fan", "crack", "flash", "pineye", "invert"]);
  assert.deepEqual([...Ferret.TRICKS], ["tube", "romp", "steal", "puff", "noodle", "corkscrew", "slink"]);
  assert.deepEqual([...Hedgehog.TRICKS], ["curl", "snuffle", "anoint", "bristle", "root", "trundle", "wheel"]);
  assert.deepEqual([...Chinchilla.TRICKS], ["ash", "bound", "fluff", "chin", "sift", "ricochet", "gnaw"]);
  assert.deepEqual([...Axolotl.TRICKS], ["gill", "amble", "mend", "smile", "plume", "sprout", "glop"]);
  assert.deepEqual([...Toucan.TRICKS], ["roost", "berry", "juggle", "peer", "skip", "rattle", "clatter"]);
  assert.deepEqual([...Iguana.TRICKS], ["sun", "dewlap", "nod", "press", "flick", "sneeze", "lash"]);
  assert.deepEqual([...Phoenix.TRICKS], ["cinder", "blaze", "shed", "lift", "return", "reignite", "hearth"]);
  assert.deepEqual([...T.TRICKS], ["orb", "nook", "taste", "inch", "unroll", "loom", "weave"]);
  assert.equal(T.TRICKS.includes("flatten"), false);
  assert.equal(T.TRICKS.includes("flash"), false);
  assert.equal(T.TRICKS.includes("bask"), false);
  assert.equal(T.TRICKS.includes("gill"), false);
  assert.equal(T.wantsThankYou("ball_python"), true);
  assert.equal(T.wantsThankYou("nori"), true);
  assert.equal(T.wantsThankYou("axolotl"), false);
  assert.equal(T.wantsThankYou("bloom"), false);
  assert.equal(Rui.sleepHoldFrame("red_panda", 4), 1);
  assert.equal(T.sleepHoldFrame("toucan", 4), null);
  globalThis.PetRuiTricks = OverlayRui;
  globalThis.PetRelayTricks = OverlayRelay;
  globalThis.PetFuseTricks = OverlayFuse;
  globalThis.PetEarthTricks = OverlayEarth;
  globalThis.PetCatTricks = OverlayCat;
  globalThis.PetDogTricks = OverlayDog;
  globalThis.PetRabbitTricks = OverlayRabbit;
  globalThis.PetHamsterTricks = OverlayHamster;
  globalThis.PetGuineaPigTricks = OverlayGuineaPig;
  globalThis.PetTurtleTricks = OverlayTurtle;
  globalThis.PetGoldfishTricks = OverlayGoldfish;
  globalThis.PetBudgieTricks = OverlayBudgie;
  globalThis.PetFoxTricks = OverlayFox;
  globalThis.PetPenguinTricks = OverlayPenguin;
  globalThis.PetParrotTricks = OverlayParrot;
  globalThis.PetFerretTricks = OverlayFerret;
  globalThis.PetHedgehogTricks = OverlayHedgehog;
  globalThis.PetChinchillaTricks = OverlayChinchilla;
  globalThis.PetAxolotlTricks = OverlayAxolotl;
  globalThis.PetToucanTricks = OverlayToucan;
  globalThis.PetIguanaTricks = OverlayIguana;
  globalThis.PetDragonTricks = OverlayDragon;
  globalThis.PetPhoenixTricks = OverlayPhoenix;
  globalThis.PetBallPythonTricks = Overlay;
  assert.equal(OverlayGround.tricksFor("red_panda"), OverlayRui);
  assert.equal(OverlayGround.tricksFor("rui"), OverlayRui);
  assert.equal(OverlayGround.tricksFor("relay_dragon"), OverlayRelay);
  assert.equal(OverlayGround.tricksFor("fuse_dragon"), OverlayFuse);
  assert.equal(OverlayGround.tricksFor("ground_dragon"), OverlayEarth);
  assert.equal(OverlayGround.tricksFor("ground"), OverlayEarth);
  assert.equal(OverlayGround.tricksFor("cat"), OverlayCat);
  assert.equal(OverlayGround.tricksFor("miso"), OverlayCat);
  assert.equal(OverlayGround.tricksFor("dog"), OverlayDog);
  assert.equal(OverlayGround.tricksFor("pip"), OverlayDog);
  assert.equal(OverlayGround.tricksFor("rabbit"), OverlayRabbit);
  assert.equal(OverlayGround.tricksFor("thimble"), OverlayRabbit);
  assert.equal(OverlayGround.tricksFor("hamster"), OverlayHamster);
  assert.equal(OverlayGround.tricksFor("clip"), OverlayHamster);
  assert.equal(OverlayGround.tricksFor("guinea_pig"), OverlayGuineaPig);
  assert.equal(OverlayGround.tricksFor("whee"), OverlayGuineaPig);
  assert.equal(OverlayGround.tricksFor("turtle"), OverlayTurtle);
  assert.equal(OverlayGround.tricksFor("ink"), OverlayTurtle);
  assert.equal(OverlayGround.tricksFor("goldfish"), OverlayGoldfish);
  assert.equal(OverlayGround.tricksFor("coin"), OverlayGoldfish);
  assert.equal(OverlayGround.tricksFor("budgie"), OverlayBudgie);
  assert.equal(OverlayGround.tricksFor("echo"), OverlayBudgie);
  assert.equal(OverlayGround.tricksFor("fox"), OverlayFox);
  assert.equal(OverlayGround.tricksFor("rue"), OverlayFox);
  assert.equal(OverlayGround.tricksFor("penguin"), OverlayPenguin);
  assert.equal(OverlayGround.tricksFor("peck"), OverlayPenguin);
  assert.equal(OverlayGround.tricksFor("parrot"), OverlayParrot);
  assert.equal(OverlayGround.tricksFor("quill"), OverlayParrot);
  assert.equal(OverlayGround.tricksFor("ferret"), OverlayFerret);
  assert.equal(OverlayGround.tricksFor("wick"), OverlayFerret);
  assert.equal(OverlayGround.tricksFor("hedgehog"), OverlayHedgehog);
  assert.equal(OverlayGround.tricksFor("burr"), OverlayHedgehog);
  assert.equal(OverlayGround.tricksFor("chinchilla"), OverlayChinchilla);
  assert.equal(OverlayGround.tricksFor("floss"), OverlayChinchilla);
  assert.equal(OverlayGround.tricksFor("axolotl"), OverlayAxolotl);
  assert.equal(OverlayGround.tricksFor("bloom"), OverlayAxolotl);
  assert.equal(OverlayGround.tricksFor("toucan"), OverlayToucan);
  assert.equal(OverlayGround.tricksFor("keel"), OverlayToucan);
  assert.equal(OverlayGround.tricksFor("iguana"), OverlayIguana);
  assert.equal(OverlayGround.tricksFor("sol"), OverlayIguana);
  assert.equal(OverlayGround.tricksFor("dragon"), OverlayDragon);
  assert.equal(OverlayGround.tricksFor("vesper"), OverlayDragon);
  assert.equal(OverlayGround.wantsThankYou("red_panda"), true);
  assert.equal(OverlayGround.wantsThankYou("relay_dragon"), true);
  assert.equal(OverlayGround.wantsThankYou("fuse_dragon"), true);
  assert.equal(OverlayGround.wantsThankYou("ground_dragon"), true);
  assert.equal(OverlayGround.wantsThankYou("cat"), true);
  assert.equal(OverlayGround.wantsThankYou("miso"), true);
  assert.equal(OverlayGround.wantsThankYou("dog"), true);
  assert.equal(OverlayGround.wantsThankYou("pip"), true);
  assert.equal(OverlayGround.wantsThankYou("rabbit"), true);
  assert.equal(OverlayGround.wantsThankYou("thimble"), true);
  assert.equal(OverlayGround.wantsThankYou("hamster"), true);
  assert.equal(OverlayGround.wantsThankYou("clip"), true);
  assert.equal(OverlayGround.wantsThankYou("guinea_pig"), true);
  assert.equal(OverlayGround.wantsThankYou("whee"), true);
  assert.equal(OverlayGround.wantsThankYou("turtle"), true);
  assert.equal(OverlayGround.wantsThankYou("ink"), true);
  assert.equal(OverlayGround.wantsThankYou("goldfish"), true);
  assert.equal(OverlayGround.wantsThankYou("coin"), true);
  assert.equal(OverlayGround.wantsThankYou("budgie"), true);
  assert.equal(OverlayGround.wantsThankYou("echo"), true);
  assert.equal(OverlayGround.wantsThankYou("fox"), true);
  assert.equal(OverlayGround.wantsThankYou("rue"), true);
  assert.equal(OverlayGround.wantsThankYou("penguin"), true);
  assert.equal(OverlayGround.wantsThankYou("peck"), true);
  assert.equal(OverlayGround.wantsThankYou("parrot"), true);
  assert.equal(OverlayGround.wantsThankYou("quill"), true);
  assert.equal(OverlayGround.wantsThankYou("ferret"), true);
  assert.equal(OverlayGround.wantsThankYou("wick"), true);
  assert.equal(OverlayGround.wantsThankYou("hedgehog"), true);
  assert.equal(OverlayGround.wantsThankYou("burr"), true);
  assert.equal(OverlayGround.wantsThankYou("chinchilla"), true);
  assert.equal(OverlayGround.wantsThankYou("floss"), true);
  assert.equal(OverlayGround.wantsThankYou("axolotl"), true);
  assert.equal(OverlayGround.wantsThankYou("bloom"), true);
  assert.equal(OverlayGround.wantsThankYou("toucan"), true);
  assert.equal(OverlayGround.wantsThankYou("keel"), true);
  assert.equal(OverlayGround.wantsThankYou("dragon"), true);
  assert.equal(OverlayGround.wantsThankYou("vesper"), true);
  assert.equal(OverlayGround.wantsThankYou("dragon"), true);
  assert.equal(OverlayGround.tricksFor("ball_python"), Overlay);
  assert.equal(OverlayGround.tricksFor("nori"), Overlay);
  assert.equal(OverlayGround.wantsThankYou("ball_python"), true);
  assert.equal(OverlayGround.wantsThankYou("nori"), true);
  assert.equal(OverlayGround.sleepHoldFrame("red_panda", 4), 1);
  assert.equal(OverlayGround.sleepHoldFrame("dog", 4), null);
  assert.equal(OverlayGround.sleepHoldFrame("cat", 4), null);
  assert.equal(OverlayGround.sleepHoldFrame("rabbit", 4), null);
  assert.equal(OverlayGround.sleepHoldFrame("hamster", 4), null);
  assert.equal(OverlayGround.sleepHoldFrame("guinea_pig", 4), null);
  assert.equal(OverlayGround.sleepHoldFrame("turtle", 4), null);
  assert.equal(OverlayGround.sleepHoldFrame("goldfish", 4), null);
  assert.equal(OverlayGround.sleepHoldFrame("budgie", 4), null);
  assert.equal(OverlayGround.sleepHoldFrame("fox", 4), null);
  assert.equal(OverlayGround.sleepHoldFrame("penguin", 4), null);
  assert.equal(OverlayGround.sleepHoldFrame("parrot", 4), null);
  assert.equal(OverlayGround.sleepHoldFrame("ferret", 4), null);
  assert.equal(OverlayGround.sleepHoldFrame("hedgehog", 4), null);
  assert.equal(OverlayGround.sleepHoldFrame("axolotl", 4), null);
  assert.equal(OverlayGround.sleepHoldFrame("toucan", 4), null);
  assert.equal(OverlayGround.sleepHoldFrame("iguana", 4), null);
  assert.equal(OverlayGround.sleepHoldFrame("dragon", 4), null);
  assert.equal(OverlayGround.sleepHoldFrame("ball_python", 4), null);
});


test("ultra-polish: Nori orb/nook/loom/weave lifts are Rui-visible (not micro idle-gen)", () => {
  const ex = T.beginTrick("orb", 80, 1);
  const mid = T.stepTrick(ex, 0.55, { cmd: "idle" });
  assert.ok(Math.abs(mid.rot) > 10, `orb mid rot ${mid.rot}`);
  assert.ok(Math.abs(mid.lift) > 2, `orb mid lift ${mid.lift}`);
  const nk = T.beginTrick("nook", 80, 1);
  const n2 = T.stepTrick(nk, T.DUR.nook * 0.4, { cmd: "idle" });
  assert.ok(n2.lift > 4 || Math.abs(n2.rot) > 4, `nook mid lift/rot ${n2.lift}/${n2.rot}`);
  const lm = T.beginTrick("loom", 80, 1);
  const l2 = T.stepTrick(lm, T.DUR.loom * 0.4, { cmd: "idle" });
  assert.ok(l2.lift > 4 || Math.abs(l2.rot) > 6, `loom mid lift/rot ${l2.lift}/${l2.rot}`);
  const wv = T.beginTrick("weave", 80, 1);
  const w2 = T.stepTrick(wv, T.DUR.weave * 0.45, { cmd: "idle" });
  assert.ok(Math.abs(w2.lift) > 2 || Math.abs(w2.rot) > 4 || Math.abs(w2.x - 80) > 2, `weave mid ${w2.lift}/${w2.rot}/${w2.x}`);
  assert.ok(Overlay.loomPose && Overlay.weavePose);
  assert.deepEqual([...T.TRICKS], [...Overlay.TRICKS]);
  assert.equal(T.DUR.loom, Overlay.DUR.loom);
  assert.equal(T.DUR.weave, Overlay.DUR.weave);
  assert.equal(T.ORB_HOLD, Overlay.ORB_HOLD);
  assert.equal(T.ORB_HOLD, 11.2);
  assert.equal(T.RELEASE_S, 1.18);
  assert.ok(T.nextTrickWait(true, 0, "orb") > 39);
  assert.ok(T.nextTrickWait(true, 0, "orb") < 80);
  assert.ok(T.nextTrickWait(true, 0, "orb") > T.nextTrickWait(true, 0, "nook"));
  assert.equal(T.HAPPY_DUR.savor, Overlay.HAPPY_DUR.savor);
});

test("notes: Nori Rui-dense ultra (ORB_HOLD=11.2); Saffron densified; Bandit densified; Jade densified; Bluff densified; Sash densified; Lula densified; Coral densified; Blush densified; Atlas densified; Cup densified; next leftover Sepia / cuttlefish", () => {
  assert.deepEqual([...T.TRICKS], ["orb", "nook", "taste", "inch", "unroll", "loom", "weave"]);
  assert.equal(T.TRICK_KEY, "ball_python");
  assert.equal(T.wantsThankYou("nori"), true);
  assert.equal(OverlayGround.tricksFor("ball_python"), Overlay);
  assert.equal(OverlayGround.tricksFor("nori"), Overlay);
  assert.equal(OverlayGround.wantsThankYou("ball_python"), true);
  assert.equal(OverlayGround.wantsThankYou("nori"), true);
  assert.equal(OverlayGround.tricksFor("phoenix"), OverlayPhoenix);
  assert.equal(OverlayGround.tricksFor("ember"), OverlayPhoenix);
  assert.equal(OverlayGround.wantsThankYou("phoenix"), true);
  assert.equal(OverlayGround.wantsThankYou("ember"), true);
  assert.equal(OverlayGround.tricksFor("corn_snake") == null, true);
  assert.equal(OverlayGround.wantsThankYou("corn_snake"), false);
  assert.equal(OverlayGround.tricksFor("saffron") == null, true);
});
