import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { test } from "node:test";
import { fileURLToPath, pathToFileURL } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const C = await import(pathToFileURL(join(root, "src/lib/pets/card.ts")).href);
const Care = await import(pathToFileURL(join(root, "src/lib/pets/care.ts")).href);
const K = await import(pathToFileURL(join(root, "src/lib/pets/keeper.ts")).href);

const cardSrc = readFileSync(join(root, "src/components/desk/keeper-card.tsx"), "utf8");
const livingSrc = readFileSync(join(root, "src/components/desk/living-pet.tsx"), "utf8");
const roomSrc = readFileSync(join(root, "src/components/desk/companion-room.tsx"), "utf8");
const overlayCard = readFileSync(join(root, "../desktop/renderer/card.js"), "utf8");
const overlayPet = readFileSync(join(root, "../desktop/renderer/pet.js"), "utf8");
const overlayHtml = readFileSync(join(root, "../desktop/renderer/index.html"), "utf8");
const overlayLife = readFileSync(join(root, "../desktop/renderer/life.js"), "utf8");
const styleSrc = readFileSync(join(root, "src/styles.css"), "utf8");

test("the desk card law matches the overlay card", () => {
  assert.deepEqual(C.CARD_COLORS.map((c) => c.id), ["ink", "blotter", "moss", "ember", "dusk", "frost"]);
  assert.deepEqual(C.VOICE_STYLES.map((s) => s.id), ["hearth", "hush", "even", "low", "bright"]);
  assert.deepEqual([...C.MUTE_BUSES], ["talk", "special", "weather", "treats", "steps", "music"]);
  assert.equal(C.VOICE_TRUTH, "Rui, Soot, Wedge, Heart, Hook, Dee, Brick, Drake, Vee, Drum, Sip, Echo, Peck, Quill, Keel, Ember, Miso, Pip, Thimble, Clip, Whee, Ink, Coin, Rue, Wick, Burr, Floss, Bloom, Vesper, Nori, Saffron, Bandit, Jade, Bluff, Sash, Lula, Coral, Blush, Atlas, Cup, Sepia, Chamber, Pulse, Ochre, Tenant, Ledger, Anchor, Kite, Door, Felt, Vein, Fan, Mast, Disk, Moth, Arm, Snap, Well, Dew, Comb, Milk, Ghost, Spark, Dart, Twig, Column, Seven, Fold, Brood, Wax, Frill, Cap, Lattice, Horn, Ring, Mane, Puff, Flame, Starter, Pact, Gleam, Choir, Drift, Shard, Dusk, Knot, Brine, Beacon, Hush, Arca, Reed, Pebble, Eft, Dapple, Slip, Pinch, Whorl, Hinge, Latch, Prickle, Boot, Reach, Spot, Orb, Pane, Hold, Loom, and Leap talk with house cry first; system speech is the backup.");
  assert.equal(K.VOICE_TRUTH, C.VOICE_TRUTH);
  assert.match(K.QUIT_TRUTH, /desktop\.ps1/);
  assert.equal(C.busOf("chirp"), "talk");
  assert.equal(C.isMuted({ talk: true }, "chirp"), true);
  assert.match(overlayCard, /VOICE_TRUTH/);
  assert.match(overlayHtml, /data-card="collapse"/);
  assert.match(cardSrc, /data-card="collapse"/);
  assert.match(cardSrc, /if \(card\.collapsed && !stayOpen\) return null/);
  assert.match(styleSrc, /\.keeper-card\[data-collapsed="1"\][\s\S]*display:\s*none/);
  assert.match(overlayPet, /openKeeperCard/);
  assert.match(cardSrc, /Save say/);
  assert.match(cardSrc, /Turn off/);
});

test("an asleep guest keeps sleep on the wander tick", () => {
  assert.deepEqual(C.wanderWhileAsleep(true), { cmd: "sleep", pose: "sleep" });
  assert.equal(C.wanderWhileAsleep(false), null);
  assert.equal(C.sleepHolds(true, "wander"), false);
  assert.equal(C.sleepHolds(true, "sit"), true);
  assert.equal(C.sleepHolds(true, "idle"), true);
  assert.equal(C.sleepHolds(true, "talk"), false);
  const rested = Care.applyRest({ energy: 40, hunger: 70 });
  assert.equal(rested.asleep, true);
  const day = Care.decayStats(rested, Date.now(), Date.now() + 20_000, false);
  assert.equal(day.asleep, true);
  assert.deepEqual(C.wanderWhileAsleep(day.asleep), { cmd: "sleep", pose: "sleep" });
  const woke = Care.applyCall(day);
  assert.equal(woke.asleep, false);
  assert.match(livingSrc, /asleepRef\.current/);
  assert.match(roomSrc, /wanderWhileAsleep/);
  assert.match(overlayPet, /wanderWhileAsleep/);
  assert.match(overlayLife, /sleepHeld/);
});

test("saved lines, alarm, and timer are machine-local", () => {
  let card = C.addLine(C.blankCard(), "red_panda", "A ribbon I was keeping.", "say");
  assert.equal(C.guestOf(card, "red_panda").lines[0].text, "A ribbon I was keeping.");
  const noon = new Date(2026, 7, 27, 7, 0, 5).getTime();
  assert.equal(C.alarmDue({ on: true, hour: 7, minute: 0, lastRingDay: "" }, noon), true);
  const started = C.startTimer(C.blankTimer(), 4000, 1000);
  assert.equal(C.timerTick(started, 5000).rang, true);
  const voices = [
    { name: "Zarvox" },
    { name: "Microsoft David Desktop" },
    { name: "Microsoft Aria Online (Natural)" },
    { name: "Microsoft Zira Compact" },
  ];
  assert.equal(C.pickSystemVoice(voices, "hearth")?.name, "Microsoft Aria Online (Natural)");
  assert.equal(C.prefersHouseCry("red_panda"), true);
  assert.equal(C.prefersHouseCry("crow"), true);
  assert.equal(C.prefersHouseCry("raven"), true);
  assert.equal(C.prefersHouseCry("barn_owl"), true);
  assert.equal(C.prefersHouseCry("red_tail"), true);
  assert.equal(C.prefersHouseCry("chickadee"), true);
  assert.equal(C.prefersHouseCry("robin"), true);
  assert.equal(C.prefersHouseCry("mallard"), true);
  assert.equal(C.prefersHouseCry("canada_goose"), true);
  assert.equal(C.prefersHouseCry("pileated"), true);
  assert.equal(C.prefersHouseCry("hummingbird"), true);
  assert.equal(C.prefersHouseCry("budgie"), true);
  assert.equal(C.prefersHouseCry("penguin"), true);
  assert.equal(C.prefersHouseCry("parrot"), true);
  assert.equal(C.prefersHouseCry("toucan"), true);
  assert.equal(C.prefersHouseCry("phoenix"), true);
  assert.equal(C.prefersHouseCry("cat"), true);
  assert.equal(C.prefersHouseCry("dog"), true);
  assert.equal(C.prefersHouseCry("rabbit"), true);
  assert.equal(C.prefersHouseCry("hamster"), true);
  assert.equal(C.prefersHouseCry("guinea_pig"), true);
  assert.equal(C.prefersHouseCry("turtle"), true);
  assert.equal(C.prefersHouseCry("goldfish"), true);
  assert.equal(C.prefersHouseCry("fox"), true);
  assert.equal(C.prefersHouseCry("ferret"), true);
  assert.equal(C.prefersHouseCry("hedgehog"), true);
  assert.equal(C.prefersHouseCry("chinchilla"), true);
  assert.equal(C.prefersHouseCry("axolotl"), true);
  assert.equal(C.prefersHouseCry("dragon"), true);
  assert.equal(C.prefersHouseCry("ball_python"), true);
  assert.equal(C.prefersHouseCry("corn_snake"), true);
  assert.equal(C.prefersHouseCry("kingsnake"), true);
  assert.equal(C.prefersHouseCry("green_tree_python"), true);
  assert.equal(C.prefersHouseCry("hognose"), true);
  assert.equal(C.prefersHouseCry("garter"), true);
  assert.equal(C.prefersHouseCry("boa"), true);
  assert.equal(C.prefersHouseCry("milk_snake"), true);
  assert.equal(C.prefersHouseCry("rosy_boa"), true);
  assert.equal(C.prefersHouseCry("carpet_python"), true);
  assert.equal(C.prefersHouseCry("octopus"), true);
  assert.equal(C.prefersHouseCry("cuttlefish"), true);
  assert.equal(C.prefersHouseCry("nautilus"), true);
  assert.equal(C.prefersHouseCry("moon_jelly"), true);
  assert.equal(C.prefersHouseCry("sea_star"), true);
  assert.equal(C.prefersHouseCry("hermit_crab"), true);
  assert.equal(C.prefersHouseCry("horseshoe_crab"), true);
  assert.equal(C.prefersHouseCry("seahorse"), true);
  assert.equal(C.prefersHouseCry("manta"), true);
  assert.equal(C.prefersHouseCry("moray"), true);
  assert.equal(C.prefersHouseCry("moss"), true);
  assert.equal(C.prefersHouseCry("maidenhair"), true);
  assert.equal(C.prefersHouseCry("ginkgo"), true);
  assert.equal(C.prefersHouseCry("oak"), true);
  assert.equal(C.prefersHouseCry("water_lily"), true);
  assert.equal(C.prefersHouseCry("orchid"), true);
  assert.equal(C.prefersHouseCry("saguaro"), true);
  assert.equal(C.prefersHouseCry("venus_flytrap"), true);
  assert.equal(C.prefersHouseCry("pitcher"), true);
  assert.equal(C.prefersHouseCry("sundew"), true);
  assert.equal(C.prefersHouseCry("honeybee"), true);
  assert.equal(C.prefersHouseCry("monarch"), true);
  assert.equal(C.prefersHouseCry("bumblebee"), true);
  assert.equal(C.prefersHouseCry("sweat_bee"), true);
  assert.equal(C.prefersHouseCry("honey_drone"), true);
  assert.equal(C.prefersHouseCry("carpenter_bee"), true);
  assert.equal(C.prefersHouseCry("mason_bee"), true);
  assert.equal(C.prefersHouseCry("leafcutter"), true);
  assert.equal(C.prefersHouseCry("stingless"), true);
  assert.equal(C.prefersHouseCry("mining_bee"), true);
  assert.equal(C.prefersHouseCry("honey_queen"), true);
  assert.equal(C.prefersHouseCry("luna"), true);
  assert.equal(C.prefersHouseCry("firefly"), true);
  assert.equal(C.prefersHouseCry("darner"), true);
  assert.equal(C.prefersHouseCry("stick"), true);
  assert.equal(C.prefersHouseCry("carpenter_ant"), true);
  assert.equal(C.prefersHouseCry("ladybird"), true);
  assert.equal(C.prefersHouseCry("mantis"), true);
  assert.equal(C.prefersHouseCry("cicada"), true);
  assert.equal(C.prefersHouseCry("honeycomb"), true);
  assert.equal(C.prefersHouseCry("oyster"), true);
  assert.equal(C.prefersHouseCry("fly_agaric"), true);
  assert.equal(C.prefersHouseCry("morel"), true);
  assert.equal(C.prefersHouseCry("chanterelle"), true);
  assert.equal(C.prefersHouseCry("turkey_tail"), true);
  assert.equal(C.prefersHouseCry("lions_mane"), true);
  assert.equal(C.prefersHouseCry("terminator"), true);
  assert.equal(C.prefersHouseCry("nexus"), true);
  assert.equal(C.prefersHouseCry("halovore"), true);
  assert.equal(C.prefersHouseCry("magneton"), true);
assert.equal(C.prefersHouseCry("umbral"), true);
  assert.equal(C.prefersHouseCry("cyst"), true);
  assert.equal(C.prefersHouseCry("frog"), true);
assert.equal(C.prefersHouseCry("toad"), true);
assert.equal(C.prefersHouseCry("newt"), true);
assert.equal(C.prefersHouseCry("salamander"), true);
assert.equal(C.prefersHouseCry("caecilian"), true);
assert.equal(C.prefersHouseCry("crayfish"), true);
assert.equal(C.prefersHouseCry("pond_snail"), true);
  assert.equal(C.prefersHouseCry("mussel"), true);
  assert.equal(C.prefersHouseCry("leech"), true);
  assert.equal(C.prefersHouseCry("stickleback"), true);
  assert.equal(C.prefersHouseCry("paramecium"), true);
  assert.equal(C.prefersHouseCry("amoeba"), true);
  assert.equal(C.prefersHouseCry("euglena"), true);
  assert.equal(C.prefersHouseCry("volvox"), true);
  assert.equal(C.prefersHouseCry("diatom"), true);
  assert.equal(C.prefersHouseCry("kelp"), true);
  assert.equal(C.prefersHouseCry("chlamydomonas"), true);
  assert.equal(C.prefersHouseCry("stentor"), true);
assert.equal(C.prefersHouseCry("coli"), true);
assert.equal(C.prefersHouseCry("haloarchaea"), true);
assert.equal(C.prefersHouseCry("orb_weaver"), true);
  assert.equal(C.prefersHouseCry("jumping_spider"), true);
  assert.equal(C.prefersHouseCry("wolf_spider"), true);
  assert.equal(C.prefersHouseCry("tarantula"), true);
  assert.equal(C.prefersHouseCry("widow"), true);
  assert.equal(C.prefersHouseCry("harvestman"), true);
  assert.equal(C.prefersHouseCry("scorpion"), true);
  assert.equal(C.prefersHouseCry("vinegaroon"), true);
  assert.equal(C.prefersHouseCry("tick"), true);
  assert.equal(C.prefersHouseCry("solifuge"), true);
  assert.equal(C.prefersHouseCry("deer"), true);
assert.equal(C.prefersHouseCry("bat"), true);
assert.equal(C.prefersHouseCry("squirrel"), true);
assert.equal(C.prefersHouseCry("otter"), true);
assert.equal(C.prefersHouseCry("raccoon"), true);
assert.equal(C.prefersHouseCry("skunk"), true);
assert.equal(C.prefersHouseCry("opossum"), true);
assert.equal(C.prefersHouseCry("beaver"), true);
assert.equal(C.prefersHouseCry("porcupine"), true);
assert.equal(C.prefersHouseCry("black_bear"), true);
assert.equal(C.prefersHouseCry("gecko"), true);
assert.equal(C.prefersHouseCry("anole"), true);
assert.equal(C.prefersHouseCry("skink"), true);
assert.equal(C.prefersHouseCry("alligator"), true);
  assert.equal(C.prefersHouseCry("capybara"), true);
  assert.equal(C.prefersHouseCry("iguana"), true);
  assert.equal(C.prefersHouseCry("chameleon"), true);
  assert.equal(C.prefersHouseCry("horned_lizard"), true);
  assert.equal(C.prefersHouseCry("snapper"), true);
  assert.equal(C.prefersHouseCry("box_turtle"), true);
  // Jaw has no legal American crocodile field tape yet, so no house cry.
  assert.equal(C.prefersHouseCry("crocodile"), false);
  assert.equal(C.prefersHouseCry("tuatara"), true);
  assert.equal(C.prefersHouseCry("bass"), true);
  assert.equal(C.prefersHouseCry("brook_trout"), true);
  assert.equal(C.prefersHouseCry("catfish"), true);
  assert.equal(C.prefersHouseCry("bluegill"), true);
  assert.equal(C.prefersHouseCry("perch"), true);
  assert.equal(C.prefersHouseCry("pike"), true);
  assert.equal(C.prefersHouseCry("walleye"), true);
  assert.equal(C.prefersHouseCry("paddlefish"), true);
  assert.equal(C.prefersHouseCry("lamprey"), true);
  assert.equal(C.prefersHouseCry("american_eel"), true);
  assert.equal(C.prefersHouseCry("house_centipede"), true);
  assert.equal(C.prefersHouseCry("millipede"), true);
  assert.equal(C.prefersHouseCry("pillbug"), true);
  assert.equal(C.prefersHouseCry("earthworm"), true);
  assert.equal(C.prefersHouseCry("velvet_worm"), true);
assert.equal(C.prefersHouseCry("springtail"), true);
assert.equal(C.prefersHouseCry("tardigrade"), true);
assert.equal(C.prefersHouseCry("planarian"), true);
assert.equal(C.prefersHouseCry("nematode"), true);
assert.equal(C.prefersHouseCry("amphipod"), true);
assert.equal(C.prefersHouseCry("fiddler_crab"), true);
assert.equal(C.prefersHouseCry("ghost_crab"), true);
assert.equal(C.prefersHouseCry("limpet"), true);
assert.equal(C.prefersHouseCry("barnacle"), true);
assert.equal(C.prefersHouseCry("chiton"), true);
assert.equal(C.prefersHouseCry("periwinkle"), true);
assert.equal(C.prefersHouseCry("sand_dollar"), true);
assert.equal(C.prefersHouseCry("sea_urchin"), true);
assert.equal(C.prefersHouseCry("knobbed_whelk"), true);
assert.equal(C.prefersHouseCry("lugworm"), true);
assert.equal(C.prefersHouseCry("field_cricket"), true);
assert.equal(C.prefersHouseCry("katydid"), true);
assert.equal(C.prefersHouseCry("grasshopper"), true);
assert.equal(C.prefersHouseCry("swallowtail"), true);
assert.equal(C.prefersHouseCry("jewelwing"), true);
assert.equal(C.prefersHouseCry("lacewing"), true);
assert.equal(C.prefersHouseCry("earwig"), true);
assert.equal(C.prefersHouseCry("acorn_weevil"), true);
assert.equal(C.prefersHouseCry("click_beetle"), true);
assert.equal(C.prefersHouseCry("robber_fly"), true);
assert.equal(C.prefersHouseCry("sloth"), true);
assert.equal(C.prefersHouseCry("lemur"), true);
assert.equal(C.prefersHouseCry("gibbon"), true);
assert.equal(C.prefersHouseCry("kinkajou"), true);
assert.equal(C.prefersHouseCry("colugo"), true);
assert.equal(C.prefersHouseCry("flying_squirrel"), true);
assert.equal(C.prefersHouseCry("howler"), true);
assert.equal(C.prefersHouseCry("tarsier"), true);
assert.equal(C.prefersHouseCry("potto"), true);
assert.equal(C.prefersHouseCry("koala"), true);
assert.equal(C.prefersHouseCry("brain_coral"), true);
assert.equal(C.prefersHouseCry("anemone"), true);
assert.equal(C.prefersHouseCry("clownfish"), true);
assert.equal(C.prefersHouseCry("parrotfish"), true);
assert.equal(C.prefersHouseCry("cleaner_shrimp"), true);
assert.equal(C.prefersHouseCry("sea_cucumber"), true);
assert.equal(C.prefersHouseCry("lionfish"), true);
assert.equal(C.prefersHouseCry("giant_clam"), true);
assert.equal(C.prefersHouseCry("eagle_ray"), true);
assert.equal(C.prefersHouseCry("grouper"), true);
assert.equal(C.prefersHouseCry("cyber_dragon"), true);
assert.equal(C.prefersHouseCry("volt_dragon"), true);
assert.equal(C.prefersHouseCry("trace_dragon"), true);
assert.equal(C.prefersHouseCry("flux_dragon"), true);
assert.equal(C.prefersHouseCry("spark_dragon"), true);
assert.equal(C.prefersHouseCry("ion_dragon"), true);
assert.equal(C.prefersHouseCry("gauss_dragon"), true);
assert.equal(C.prefersHouseCry("relay_dragon"), true);
assert.equal(C.prefersHouseCry("fuse_dragon"), true);
assert.equal(C.prefersHouseCry("ground_dragon"), true);
  assert.ok(C.speakOpts("hearth", 50).volume < 0.5);
  assert.match(roomSrc, /prefersHouseCry/);
  assert.match(roomSrc, /const cried = await playAnimalVoice/);
  assert.match(roomSrc, /house cry missing or blocked/);
  assert.match(overlayPet, /prefersHouseCry/);
  assert.match(overlayPet, /if \(!played\) speakText\(text\)/);
  assert.equal(C.CARD_STORE, "computerpets.card.v1");
  assert.equal(C.blankCard().collapsed, true);
  assert.equal(C.blankCard().sleepAid.plugin, "off");
  const withBed = C.parseCard({ sleepAid: { plugin: "rain", playing: true } });
  assert.equal(withBed.sleepAid.plugin, "rain");
  assert.equal(withBed.sleepAid.playing, true);
  assert.match(cardSrc, /SLEEP_AID_LABEL/);
  assert.match(overlayHtml, /id="hud-sleep"/);
});
