import assert from "node:assert/strict";
import { createRequire } from "node:module";
import { dirname, join } from "node:path";
import { test } from "node:test";
import { fileURLToPath, pathToFileURL } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const T = await import(pathToFileURL(join(root, "src/lib/pets/carpet-python-tricks.ts")).href);
const RosyBoa = await import(pathToFileURL(join(root, "src/lib/pets/rosy-boa-tricks.ts")).href);
const MilkSnake = await import(pathToFileURL(join(root, "src/lib/pets/milk-snake-tricks.ts")).href);
const Garter = await import(pathToFileURL(join(root, "src/lib/pets/garter-tricks.ts")).href);
const Boa = await import(pathToFileURL(join(root, "src/lib/pets/boa-tricks.ts")).href);
const Hognose = await import(pathToFileURL(join(root, "src/lib/pets/hognose-tricks.ts")).href);
const GreenTreePython = await import(pathToFileURL(join(root, "src/lib/pets/green-tree-python-tricks.ts")).href);
const BallPython = await import(pathToFileURL(join(root, "src/lib/pets/ball-python-tricks.ts")).href);
const CornSnake = await import(pathToFileURL(join(root, "src/lib/pets/corn-snake-tricks.ts")).href);
const Kingsnake = await import(pathToFileURL(join(root, "src/lib/pets/kingsnake-tricks.ts")).href);
const Phoenix = await import(pathToFileURL(join(root, "src/lib/pets/phoenix-tricks.ts")).href);
const Dragon = await import(pathToFileURL(join(root, "src/lib/pets/dragon-tricks.ts")).href);
const Rui = await import(pathToFileURL(join(root, "src/lib/pets/rui-tricks.ts")).href);
const Relay = await import(pathToFileURL(join(root, "src/lib/pets/relay-tricks.ts")).href);
const Fuse = await import(pathToFileURL(join(root, "src/lib/pets/fuse-tricks.ts")).href);
const Earth = await import(pathToFileURL(join(root, "src/lib/pets/earth-tricks.ts")).href);
const Cat = await import(pathToFileURL(join(root, "src/lib/pets/cat-tricks.ts")).href);
const Dog = await import(pathToFileURL(join(root, "src/lib/pets/dog-tricks.ts")).href);
const Rabbit = await import(pathToFileURL(join(root, "src/lib/pets/rabbit-tricks.ts")).href);
const Hamster = await import(pathToFileURL(join(root, "src/lib/pets/hamster-tricks.ts")).href);
const GuineaPig = await import(pathToFileURL(join(root, "src/lib/pets/guinea-pig-tricks.ts")).href);
const Turtle = await import(pathToFileURL(join(root, "src/lib/pets/turtle-tricks.ts")).href);
const Goldfish = await import(pathToFileURL(join(root, "src/lib/pets/goldfish-tricks.ts")).href);
const Budgie = await import(pathToFileURL(join(root, "src/lib/pets/budgie-tricks.ts")).href);
const Fox = await import(pathToFileURL(join(root, "src/lib/pets/fox-tricks.ts")).href);
const Penguin = await import(pathToFileURL(join(root, "src/lib/pets/penguin-tricks.ts")).href);
const Parrot = await import(pathToFileURL(join(root, "src/lib/pets/parrot-tricks.ts")).href);
const Ferret = await import(pathToFileURL(join(root, "src/lib/pets/ferret-tricks.ts")).href);
const Hedgehog = await import(pathToFileURL(join(root, "src/lib/pets/hedgehog-tricks.ts")).href);
const Chinchilla = await import(pathToFileURL(join(root, "src/lib/pets/chinchilla-tricks.ts")).href);
const Axolotl = await import(pathToFileURL(join(root, "src/lib/pets/axolotl-tricks.ts")).href);
const Toucan = await import(pathToFileURL(join(root, "src/lib/pets/toucan-tricks.ts")).href);
const Iguana = await import(pathToFileURL(join(root, "src/lib/pets/iguana-tricks.ts")).href);
const Overlay = createRequire(import.meta.url)(join(root, "../desktop/renderer/carpet-python-tricks.js"));
const OverlayRosyBoa = createRequire(import.meta.url)(join(root, "../desktop/renderer/rosy-boa-tricks.js"));
const OverlayMilkSnake = createRequire(import.meta.url)(join(root, "../desktop/renderer/milk-snake-tricks.js"));
const OverlayGarter = createRequire(import.meta.url)(join(root, "../desktop/renderer/garter-tricks.js"));
const OverlayBoa = createRequire(import.meta.url)(join(root, "../desktop/renderer/boa-tricks.js"));
const OverlayHognose = createRequire(import.meta.url)(join(root, "../desktop/renderer/hognose-tricks.js"));
const OverlayGreenTreePython = createRequire(import.meta.url)(join(root, "../desktop/renderer/green-tree-python-tricks.js"));
const OverlayBallPython = createRequire(import.meta.url)(join(root, "../desktop/renderer/ball-python-tricks.js"));
const OverlayCornSnake = createRequire(import.meta.url)(join(root, "../desktop/renderer/corn-snake-tricks.js"));
const OverlayKingsnake = createRequire(import.meta.url)(join(root, "../desktop/renderer/kingsnake-tricks.js"));
const OverlayPhoenix = createRequire(import.meta.url)(join(root, "../desktop/renderer/phoenix-tricks.js"));
const OverlayGround = createRequire(import.meta.url)(join(root, "../desktop/renderer/ground-tricks.js"));
const OverlayRui = createRequire(import.meta.url)(join(root, "../desktop/renderer/rui-tricks.js"));
const OverlayRelay = createRequire(import.meta.url)(join(root, "../desktop/renderer/relay-tricks.js"));
const OverlayFuse = createRequire(import.meta.url)(join(root, "../desktop/renderer/fuse-tricks.js"));
const OverlayEarth = createRequire(import.meta.url)(join(root, "../desktop/renderer/earth-tricks.js"));
const OverlayCat = createRequire(import.meta.url)(join(root, "../desktop/renderer/cat-tricks.js"));
const OverlayDog = createRequire(import.meta.url)(join(root, "../desktop/renderer/dog-tricks.js"));
const OverlayRabbit = createRequire(import.meta.url)(join(root, "../desktop/renderer/rabbit-tricks.js"));
const OverlayHamster = createRequire(import.meta.url)(join(root, "../desktop/renderer/hamster-tricks.js"));
const OverlayGuineaPig = createRequire(import.meta.url)(join(root, "../desktop/renderer/guinea-pig-tricks.js"));
const OverlayTurtle = createRequire(import.meta.url)(join(root, "../desktop/renderer/turtle-tricks.js"));
const OverlayGoldfish = createRequire(import.meta.url)(join(root, "../desktop/renderer/goldfish-tricks.js"));
const OverlayBudgie = createRequire(import.meta.url)(join(root, "../desktop/renderer/budgie-tricks.js"));
const OverlayFox = createRequire(import.meta.url)(join(root, "../desktop/renderer/fox-tricks.js"));
const OverlayPenguin = createRequire(import.meta.url)(join(root, "../desktop/renderer/penguin-tricks.js"));
const OverlayParrot = createRequire(import.meta.url)(join(root, "../desktop/renderer/parrot-tricks.js"));
const OverlayFerret = createRequire(import.meta.url)(join(root, "../desktop/renderer/ferret-tricks.js"));
const OverlayHedgehog = createRequire(import.meta.url)(join(root, "../desktop/renderer/hedgehog-tricks.js"));
const OverlayChinchilla = createRequire(import.meta.url)(join(root, "../desktop/renderer/chinchilla-tricks.js"));
const OverlayAxolotl = createRequire(import.meta.url)(join(root, "../desktop/renderer/axolotl-tricks.js"));
const OverlayToucan = createRequire(import.meta.url)(join(root, "../desktop/renderer/toucan-tricks.js"));
const OverlayIguana = createRequire(import.meta.url)(join(root, "../desktop/renderer/iguana-tricks.js"));
const OverlayDragon = createRequire(import.meta.url)(join(root, "../desktop/renderer/dragon-tricks.js"));


test("Atlas tricks start only on idle ground", () => {
  assert.deepEqual([...BallPython.TRICKS], ["orb", "nook", "taste", "inch", "unroll", "loom", "weave"]);
  assert.deepEqual([...Kingsnake.TRICKS], ["stripe", "audit", "verdict", "plumb", "raid", "band", "drawer"]);
  assert.deepEqual([...GreenTreePython.TRICKS], ["bracelet", "sway", "jewel", "heat", "bough", "liana", "arbor"]);
  assert.deepEqual([...Hognose.TRICKS], ["hood", "feign", "shovel", "gape", "encore", "quiver", "upright"]);
  assert.deepEqual([...Garter.TRICKS], ["seam", "rounds", "moss", "fork", "lap", "ribbon", "creek"]);
  assert.deepEqual([...Boa.TRICKS], ["pour", "heft", "oxbow", "slack", "bank", "anchor", "meander"]);
  assert.deepEqual([...MilkSnake.TRICKS], ["rhyme", "rumor", "costume", "frank", "tile", "cipher", "verse"]);
  assert.deepEqual([...RosyBoa.TRICKS], ["pebble", "crevice", "rosy", "mesa", "arroyo", "dune", "talus"]);
  assert.deepEqual([...T.TRICKS], ["legend", "rung", "contour", "runner", "bearing", "canopy", "inset"]);
  assert.equal(T.canStart({ asleep: false, hidden: false, leaving: false, cmd: "idle" }), true);
  assert.equal(T.canStart({ asleep: true, hidden: false, leaving: false, cmd: "idle" }), false);
  assert.equal(T.canStart({ asleep: false, hidden: true, leaving: false, cmd: "idle" }), false);
  assert.equal(T.canStart({ asleep: false, hidden: false, leaving: false, cmd: "sleep" }), false);
  assert.equal(T.canStart({ asleep: false, hidden: false, leaving: false, cmd: "seek" }), false);
  assert.equal(T.canStart({ asleep: false, hidden: false, leaving: false, cmd: "idle", windowPlay: true }), false);
  assert.equal(T.canStart({ asleep: false, hidden: false, leaving: false, cmd: "idle", card: true }), false);
  assert.equal(T.shouldAbort({ asleep: true, hidden: false, leaving: false, cmd: "idle" }), true);
  assert.equal(T.shouldAbort({ asleep: false, hidden: false, leaving: false, cmd: "idle", card: true }), true);
  assert.equal(T.shouldAbort({ asleep: false, hidden: false, leaving: false, cmd: "idle" }), false);
  assert.equal(T.pickTrick(0.99, true), "legend");
  assert.notEqual(T.pickTrick(0.3, false, "legend"), "orb");
  assert.notEqual(T.pickTrick(0.3, false, "legend"), "scribble");
  assert.notEqual(T.pickTrick(0.3, false, "legend"), "stripe");
  assert.notEqual(T.pickTrick(0.3, false, "legend"), "bracelet");
  assert.notEqual(T.pickTrick(0.3, false, "legend"), "hood");
  assert.notEqual(T.pickTrick(0.3, false, "legend"), "seam");
  assert.notEqual(T.pickTrick(0.3, false, "legend"), "pour");
  assert.equal(Overlay.TRICK_KEY, "carpet_python");
  assert.equal(T.sleepHoldFrame("carpet_python", 4), null);
  assert.equal(T.TRICKS.includes("mosaic"), false);
  assert.equal(T.TRICKS.includes("loop"), false);
  assert.equal(T.TRICKS.includes("patrol"), false);
  assert.equal(T.TRICKS.includes("stripe"), false);
  assert.equal(T.TRICKS.includes("hood"), false);
  assert.equal(T.TRICKS.includes("flip"), false);
  assert.equal(T.TRICKS.includes("saddle"), false);
  assert.equal(T.TRICKS.includes("drape"), false);
  assert.equal(T.TRICKS.includes("write"), false);
  assert.equal(T.TRICKS.includes("bun"), false);
  assert.equal(T.TRICKS.includes("orb"), false);
  assert.equal(T.TRICKS.includes("nook"), false);
  assert.equal(T.TRICKS.includes("taste"), false);
  assert.equal(T.TRICKS.includes("inch"), false);
  assert.equal(T.TRICKS.includes("unroll"), false);
  assert.equal(T.TRICKS.includes("thread"), false);
  assert.equal(T.TRICKS.includes("dart"), false);
  assert.equal(T.TRICKS.includes("noodle"), false);
  assert.equal(T.TRICKS.includes("flick"), false);
  assert.equal(T.TRICKS.includes("curl"), false);
  assert.equal(T.TRICKS.includes("coil"), false);
  assert.equal(T.TRICKS.includes("ball"), false);
  assert.equal(T.TRICKS.includes("perch"), false);
  assert.equal(T.TRICKS.includes("scent"), false);
  assert.equal(T.TRICKS.includes("stone"), false);
  assert.equal(T.TRICKS.includes("chart"), false);
  assert.equal(T.TRICKS.includes("pebble"), false);
  assert.equal(T.TRICKS.includes("crevice"), false);
  assert.equal(T.TRICKS.includes("mesa"), false);
  assert.equal(T.TRICKS.includes("arroyo"), false);
  assert.equal(T.TRICKS.includes("seam"), false);
  assert.equal(T.TRICKS.includes("gape"), false);
  assert.equal(T.TRICKS.includes("encore"), false);
});

test("legend/rung/contour/runner/bearing/canopy/inset are house-carpet-python-true, not copies of prior guests", () => {
  const ground = { asleep: false, hidden: false, leaving: false, cmd: "idle" };
  const rhyme = T.beginTrick("legend", 80, 1);
  assert.equal(rhyme.anim, "sit");
  assert.equal(rhyme.phase, "hold");
  const held = T.stepTrick(rhyme, 5, ground);
  assert.equal(held.phase, "hold");
  assert.equal(held.anim, "sit");
  assert.ok(held.rot !== 0 || Math.abs(held.lift) > 0.5);
  const release = T.stepTrick(rhyme, T.LEGEND_HOLD + 0.2, ground);
  assert.equal(release.phase, "release");
  assert.equal(release.anim, "sit");
  const doneRhyme = T.stepTrick(rhyme, T.DUR.legend + 0.1, ground);
  assert.equal(doneRhyme.phase, "done");
  assert.ok(T.nextTrickWait(true, 0, "legend") > T.nextTrickWait(true, 0, "contour"));
  const frank = T.beginTrick("runner", 80, 1);
  assert.equal(frank.anim, "walk");
  const frankMid = T.stepTrick(frank, 0.5, ground);
  assert.ok(Math.abs(frankMid.lift) > 0.05 || Math.abs(frankMid.rot) > 1 || Math.abs(frankMid.x - 80) > 0.2);
  const tile = T.beginTrick("bearing", 80, 1);
  assert.equal(tile.anim, "sit");
  const tileMid = T.stepTrick(tile, 0.55, ground);
  assert.ok(Math.abs(tileMid.lift) > 0.1 || Math.abs(tileMid.rot) > 1 || Math.abs(tileMid.x - 80) > 0.5);
  const rumor = T.beginTrick("rung", 80, 1);
  assert.equal(rumor.anim, "walk");
  const rumorMid = T.stepTrick(rumor, 0.5, ground);
  assert.ok(Math.abs(rumorMid.lift) > 0.3 || Math.abs(rumorMid.rot) > 1 || Math.abs(rumorMid.x - 80) > 0.2);
  const costume = T.beginTrick("contour", 80, 1);
  assert.equal(costume.anim, "walk");
  const costumeMid = T.stepTrick(costume, 0.5, ground);
  assert.ok(Math.abs(costumeMid.lift) > 0.05 || Math.abs(costumeMid.rot) > 1 || Math.abs(costumeMid.x - 80) > 0.1);
  const costumeDone = T.stepTrick(costume, T.DUR.contour + 0.1, ground);
  assert.equal(costumeDone.phase, "done");
  const canopy = T.beginTrick("canopy", 80, 1);
  assert.equal(canopy.anim, "walk");
  const canopyMid = T.stepTrick(canopy, T.DUR.canopy * 0.4, ground);
  assert.ok(canopyMid.lift > 2 || Math.abs(canopyMid.rot) > 8 || Math.abs(canopyMid.x - 80) > 1);
  const inset = T.beginTrick("inset", 80, 1);
  assert.equal(inset.anim, "sit");
  const insetMid = T.stepTrick(inset, T.DUR.inset * 0.45, ground);
  assert.ok(Math.abs(insetMid.lift) > 0.8 || Math.abs(insetMid.rot) > 4 || Math.abs(insetMid.x - 80) > 0.3);
  assert.equal(T.TRICKS.includes("chart"), false);
  assert.equal(T.TRICKS.includes("drape"), false);
  assert.equal(T.TRICKS.includes("perch"), false);
  assert.equal(T.TRICKS.includes("bough"), false);
  assert.equal(T.TRICKS.includes("liana"), false);
  assert.equal(T.TRICKS.includes("pebble"), false);
  assert.equal(T.TRICKS.includes("nest"), false);
  const aborted = T.stepTrick(held, 0.1, { asleep: true, cmd: "sleep" });
  assert.equal(aborted.phase, "done");
  for (const mod of [Rui, Cat, Dog, Rabbit, Hamster, GuineaPig, Turtle, Goldfish, Budgie, Fox, Penguin, Parrot, Ferret, Hedgehog, Chinchilla, Axolotl, Toucan, Iguana, Dragon, Phoenix, BallPython, CornSnake, Kingsnake, GreenTreePython, Hognose, Garter, Boa, MilkSnake, RosyBoa, Relay, Fuse, Earth]) {
    assert.equal(mod.TRICKS.includes("legend"), false);
    assert.equal(mod.TRICKS.includes("rung"), false);
    assert.equal(mod.TRICKS.includes("contour"), false);
    assert.equal(mod.TRICKS.includes("runner"), false);
    assert.equal(mod.TRICKS.includes("bearing"), false);
    assert.equal(mod.TRICKS.includes("canopy"), false);
    assert.equal(mod.TRICKS.includes("inset"), false);
  }
  assert.deepEqual([...BallPython.TRICKS], ["orb", "nook", "taste", "inch", "unroll", "loom", "weave"]);
  assert.deepEqual([...CornSnake.TRICKS], ["scribble", "gap", "comma", "probe", "canyon", "blotter", "pencil"]);
  assert.deepEqual([...Kingsnake.TRICKS], ["stripe", "audit", "verdict", "plumb", "raid", "band", "drawer"]);
  assert.deepEqual([...GreenTreePython.TRICKS], ["bracelet", "sway", "jewel", "heat", "bough", "liana", "arbor"]);
  assert.deepEqual([...Hognose.TRICKS], ["hood", "feign", "shovel", "gape", "encore", "quiver", "upright"]);
  assert.deepEqual([...Garter.TRICKS], ["seam", "rounds", "moss", "fork", "lap", "ribbon", "creek"]);
  assert.deepEqual([...Boa.TRICKS], ["pour", "heft", "oxbow", "slack", "bank", "anchor", "meander"]);
  assert.deepEqual([...Dragon.TRICKS], ["sprawl", "guard", "smolder", "claim", "fold", "ruff", "scrape"]);
  assert.deepEqual([...Phoenix.TRICKS], ["cinder", "blaze", "shed", "lift", "return", "reignite", "hearth"]);
  assert.equal(T.TRICKS.includes("mosaic"), false);
  assert.equal(T.TRICKS.includes("loop"), false);
  assert.equal(T.TRICKS.includes("pour"), false);
  assert.equal(T.TRICKS.includes("heft"), false);
  assert.equal(T.TRICKS.includes("oxbow"), false);
  assert.equal(T.TRICKS.includes("rhyme"), false);
  assert.equal(T.TRICKS.includes("stone"), false);
  assert.equal(T.TRICKS.includes("chart"), false);
  assert.equal(T.TRICKS.includes("pebble"), false);
  assert.equal(T.TRICKS.includes("crevice"), false);
  assert.equal(T.TRICKS.includes("mesa"), false);
  assert.equal(T.TRICKS.includes("arroyo"), false);
  assert.equal(T.TRICKS.includes("tuck"), false);
  assert.equal(T.TRICKS.includes("stripe"), false);
  assert.equal(T.TRICKS.includes("flip"), false);
  assert.equal(T.TRICKS.includes("write"), false);
  assert.equal(Parrot.TRICKS.includes("flash"), true);
});

test("Atlas feed-happy is its own sit: survey/gazette/shelf, and two feeds are not the same", () => {
  assert.deepEqual([...T.HAPPY], ["survey", "gazette", "shelf"]);
  assert.equal(T.HAPPY.includes("savor"), false);
  assert.equal(T.HAPPY.includes("nestle"), false);
  assert.equal(T.HAPPY.includes("center"), false);
  assert.equal(T.HAPPY.includes("settle"), false);
  assert.equal(T.HAPPY.includes("shine"), false);
  assert.equal(T.HAPPY.includes("purr"), false);
  assert.equal(T.HAPPY.includes("tribute"), false);
  assert.equal(T.HAPPY.includes("clause"), false);
  assert.equal(T.HAPPY.includes("aside"), false);
  assert.equal(T.HAPPY.includes("cue"), false);
  assert.equal(T.HAPPY.includes("ovation"), false);
  assert.equal(T.HAPPY.includes("copy"), false);
  assert.equal(T.HAPPY.includes("brief"), false);
  assert.equal(T.HAPPY.includes("visa"), false);
  assert.equal(T.HAPPY.includes("harbor"), false);
  assert.equal(T.HAPPY.includes("cradle"), false);
  assert.equal(T.HAPPY.includes("stay"), false);
  assert.equal(T.HAPPY.includes("postmark"), false);
  assert.equal(T.HAPPY.includes("cachet"), false);
  assert.equal(T.HAPPY.includes("courtesy"), false);
  assert.equal(T.HAPPY.includes("climate"), false);
  assert.equal(T.HAPPY.includes("manners"), false);
  assert.equal(T.HAPPY.includes("corner"), false);
  assert.equal(T.pickHappy("survey", 0), "gazette");
  assert.notEqual(T.pickHappy("survey", 0.9), "survey");
  assert.equal(Overlay.pickHappy("gazette", 0) !== "gazette", true);
  assert.equal(T.happyCanStart({ asleep: false, hidden: false, leaving: false, cmd: "idle" }), true);
  assert.equal(T.happyCanStart({ asleep: false, hidden: false, leaving: false, cmd: "idle", card: true }), true);
  assert.equal(T.happyCanStart({ asleep: true, hidden: false, leaving: false, cmd: "idle" }), false);
  assert.equal(T.happyShouldAbort({ cmd: "sleep" }), true);
  assert.equal(T.happyShouldAbort({ cmd: "hide" }), true);
  assert.equal(T.happyShouldAbort({ card: true, cmd: "idle" }), false);
  const postmark = T.beginHappy("survey", 80, 1);
  assert.equal(postmark.anim, "sit");
  const postmarkMid = T.stepHappy(postmark, 0.4, { cmd: "idle" });
  assert.ok(postmarkMid.lift !== 0 || Math.abs(postmarkMid.rot) > 0.5);
  assert.notEqual(postmarkMid.phase, "done");
  const cachet = T.beginHappy("gazette", 80, 1);
  assert.equal(cachet.anim, "sit");
  const cachetMid = T.stepHappy(cachet, 0.3, { cmd: "idle" });
  assert.ok(cachetMid.lift > 0.2 || Math.abs(cachetMid.rot) > 0.5);
  const courtesyH = T.beginHappy("shelf", 80, 1);
  assert.equal(courtesyH.anim, "talk");
  const done = T.stepHappy(postmark, T.HAPPY_DUR.survey + 0.1, { cmd: "idle" });
  assert.equal(done.phase, "done");
  const aborted = T.stepHappy(cachetMid, 0.1, { asleep: true, cmd: "sleep" });
  assert.equal(aborted.phase, "done");
  assert.equal(aborted.abort, true);
  assert.equal(T.wantsThankYou("carpet_python"), true);
  assert.equal(T.wantsThankYou("atlas"), true);
  assert.equal(T.wantsThankYou("ball_python"), false);
  assert.equal(T.wantsThankYou("nori"), false);
  assert.equal(T.wantsThankYou("kingsnake"), false);
  assert.equal(T.wantsThankYou("hognose"), false);
  assert.equal(T.wantsThankYou("garter"), false);
  assert.equal(T.wantsThankYou("phoenix"), false);
  const thanks = T.startThankYou("carpet_python", "survey", 80, 1, { cmd: "idle", card: true, windowPlay: true });
  assert.ok(thanks);
  assert.notEqual(thanks.kind, "survey");
  assert.ok(thanks.happy.lift === 0);
  assert.notEqual(thanks.happy.anim, "eat");
  assert.notEqual(thanks.happy.anim, "idle");
  const thanksMid = T.stepHappy(thanks.happy, 0.35, { cmd: "idle", card: true });
  assert.ok(thanksMid.lift !== 0 || Math.abs(thanksMid.rot) > 0.5, "a thank-you surveys or gazettes");
  const blocked = T.startThankYou("carpet_python", "tribute", 80, 1, { asleep: true, cmd: "idle" });
  assert.equal(blocked, null);
  const other = T.startThankYou("hognose", null, 80, 1, { cmd: "idle" });
  assert.equal(other, null);
  const second = T.startThankYou("carpet_python", thanks.kind, 80, 1, { cmd: "idle", card: true });
  assert.ok(second);
  assert.notEqual(second.kind, thanks.kind);
});

test("ground registry keeps prior guests gated; Atlas selectable; prior guests still OK", () => {
  assert.equal(Rui.TRICK_KEY, "red_panda");
  assert.equal(BallPython.TRICK_KEY, "ball_python");
  assert.equal(Kingsnake.TRICK_KEY, "kingsnake");
  assert.equal(Hognose.TRICK_KEY, "hognose");
  assert.equal(Garter.TRICK_KEY, "garter");
  assert.equal(Boa.TRICK_KEY, "boa");
  assert.equal(T.TRICK_KEY, "carpet_python");
  assert.deepEqual([...Rui.TRICKS], ["somersault", "lie", "scratch", "wave", "dance"]);
  assert.deepEqual([...BallPython.TRICKS], ["orb", "nook", "taste", "inch", "unroll", "loom", "weave"]);
  assert.deepEqual([...CornSnake.TRICKS], ["scribble", "gap", "comma", "probe", "canyon", "blotter", "pencil"]);
  assert.deepEqual([...Kingsnake.TRICKS], ["stripe", "audit", "verdict", "plumb", "raid", "band", "drawer"]);
  assert.deepEqual([...GreenTreePython.TRICKS], ["bracelet", "sway", "jewel", "heat", "bough", "liana", "arbor"]);
  assert.deepEqual([...Hognose.TRICKS], ["hood", "feign", "shovel", "gape", "encore", "quiver", "upright"]);
  assert.deepEqual([...Garter.TRICKS], ["seam", "rounds", "moss", "fork", "lap", "ribbon", "creek"]);
  assert.deepEqual([...Boa.TRICKS], ["pour", "heft", "oxbow", "slack", "bank", "anchor", "meander"]);
  assert.deepEqual([...Phoenix.TRICKS], ["cinder", "blaze", "shed", "lift", "return", "reignite", "hearth"]);
  assert.deepEqual([...T.TRICKS], ["legend", "rung", "contour", "runner", "bearing", "canopy", "inset"]);
  assert.equal(T.wantsThankYou("carpet_python"), true);
  assert.equal(T.wantsThankYou("atlas"), true);
  assert.equal(BallPython.wantsThankYou("nori"), true);
  assert.equal(Kingsnake.wantsThankYou("bandit"), true);
  assert.equal(Hognose.wantsThankYou("bluff"), true);
  assert.equal(Garter.wantsThankYou("sash"), true);
  assert.equal(Rui.sleepHoldFrame("red_panda", 4), 1);
  assert.equal(T.sleepHoldFrame("carpet_python", 4), null);
  globalThis.PetRuiTricks = OverlayRui;
  globalThis.PetRelayTricks = OverlayRelay;
  globalThis.PetFuseTricks = OverlayFuse;
  globalThis.PetEarthTricks = OverlayEarth;
  globalThis.PetCatTricks = OverlayCat;
  globalThis.PetDogTricks = OverlayDog;
  globalThis.PetRabbitTricks = OverlayRabbit;
  globalThis.PetHamsterTricks = OverlayHamster;
  globalThis.PetGuineaPigTricks = OverlayGuineaPig;
  globalThis.PetTurtleTricks = OverlayTurtle;
  globalThis.PetGoldfishTricks = OverlayGoldfish;
  globalThis.PetBudgieTricks = OverlayBudgie;
  globalThis.PetFoxTricks = OverlayFox;
  globalThis.PetPenguinTricks = OverlayPenguin;
  globalThis.PetParrotTricks = OverlayParrot;
  globalThis.PetFerretTricks = OverlayFerret;
  globalThis.PetHedgehogTricks = OverlayHedgehog;
  globalThis.PetChinchillaTricks = OverlayChinchilla;
  globalThis.PetAxolotlTricks = OverlayAxolotl;
  globalThis.PetToucanTricks = OverlayToucan;
  globalThis.PetIguanaTricks = OverlayIguana;
  globalThis.PetDragonTricks = OverlayDragon;
  globalThis.PetPhoenixTricks = OverlayPhoenix;
  globalThis.PetBallPythonTricks = OverlayBallPython;
  globalThis.PetCornSnakeTricks = OverlayCornSnake;
  globalThis.PetKingsnakeTricks = OverlayKingsnake;
  globalThis.PetGreenTreePythonTricks = OverlayGreenTreePython;
  globalThis.PetHognoseTricks = OverlayHognose;
  globalThis.PetGarterTricks = OverlayGarter;
  globalThis.PetBoaTricks = OverlayBoa;
  globalThis.PetMilkSnakeTricks = OverlayMilkSnake;
  globalThis.PetRosyBoaTricks = OverlayRosyBoa;
  globalThis.PetCarpetPythonTricks = Overlay;
  assert.equal(OverlayGround.tricksFor("red_panda"), OverlayRui);
  assert.equal(OverlayGround.tricksFor("rui"), OverlayRui);
  assert.equal(OverlayGround.tricksFor("relay_dragon"), OverlayRelay);
  assert.equal(OverlayGround.tricksFor("fuse_dragon"), OverlayFuse);
  assert.equal(OverlayGround.tricksFor("ground_dragon"), OverlayEarth);
  assert.equal(OverlayGround.tricksFor("cat"), OverlayCat);
  assert.equal(OverlayGround.tricksFor("miso"), OverlayCat);
  assert.equal(OverlayGround.tricksFor("dog"), OverlayDog);
  assert.equal(OverlayGround.tricksFor("pip"), OverlayDog);
  assert.equal(OverlayGround.tricksFor("rabbit"), OverlayRabbit);
  assert.equal(OverlayGround.tricksFor("thimble"), OverlayRabbit);
  assert.equal(OverlayGround.tricksFor("hamster"), OverlayHamster);
  assert.equal(OverlayGround.tricksFor("clip"), OverlayHamster);
  assert.equal(OverlayGround.tricksFor("guinea_pig"), OverlayGuineaPig);
  assert.equal(OverlayGround.tricksFor("whee"), OverlayGuineaPig);
  assert.equal(OverlayGround.tricksFor("turtle"), OverlayTurtle);
  assert.equal(OverlayGround.tricksFor("ink"), OverlayTurtle);
  assert.equal(OverlayGround.tricksFor("goldfish"), OverlayGoldfish);
  assert.equal(OverlayGround.tricksFor("coin"), OverlayGoldfish);
  assert.equal(OverlayGround.tricksFor("budgie"), OverlayBudgie);
  assert.equal(OverlayGround.tricksFor("echo"), OverlayBudgie);
  assert.equal(OverlayGround.tricksFor("fox"), OverlayFox);
  assert.equal(OverlayGround.tricksFor("rue"), OverlayFox);
  assert.equal(OverlayGround.tricksFor("penguin"), OverlayPenguin);
  assert.equal(OverlayGround.tricksFor("peck"), OverlayPenguin);
  assert.equal(OverlayGround.tricksFor("parrot"), OverlayParrot);
  assert.equal(OverlayGround.tricksFor("quill"), OverlayParrot);
  assert.equal(OverlayGround.tricksFor("ferret"), OverlayFerret);
  assert.equal(OverlayGround.tricksFor("wick"), OverlayFerret);
  assert.equal(OverlayGround.tricksFor("hedgehog"), OverlayHedgehog);
  assert.equal(OverlayGround.tricksFor("burr"), OverlayHedgehog);
  assert.equal(OverlayGround.tricksFor("chinchilla"), OverlayChinchilla);
  assert.equal(OverlayGround.tricksFor("floss"), OverlayChinchilla);
  assert.equal(OverlayGround.tricksFor("axolotl"), OverlayAxolotl);
  assert.equal(OverlayGround.tricksFor("bloom"), OverlayAxolotl);
  assert.equal(OverlayGround.tricksFor("toucan"), OverlayToucan);
  assert.equal(OverlayGround.tricksFor("keel"), OverlayToucan);
  assert.equal(OverlayGround.tricksFor("iguana"), OverlayIguana);
  assert.equal(OverlayGround.tricksFor("sol"), OverlayIguana);
  assert.equal(OverlayGround.tricksFor("dragon"), OverlayDragon);
  assert.equal(OverlayGround.tricksFor("vesper"), OverlayDragon);
  assert.equal(OverlayGround.tricksFor("phoenix"), OverlayPhoenix);
  assert.equal(OverlayGround.tricksFor("ember"), OverlayPhoenix);
  assert.equal(OverlayGround.tricksFor("ball_python"), OverlayBallPython);
  assert.equal(OverlayGround.tricksFor("nori"), OverlayBallPython);
  assert.equal(OverlayGround.tricksFor("corn_snake"), OverlayCornSnake);
  assert.equal(OverlayGround.tricksFor("saffron"), OverlayCornSnake);
  assert.equal(OverlayGround.tricksFor("kingsnake"), OverlayKingsnake);
  assert.equal(OverlayGround.tricksFor("bandit"), OverlayKingsnake);
  assert.equal(OverlayGround.tricksFor("green_tree_python"), OverlayGreenTreePython);
  assert.equal(OverlayGround.tricksFor("jade"), OverlayGreenTreePython);
  assert.equal(OverlayGround.tricksFor("hognose"), OverlayHognose);
  assert.equal(OverlayGround.tricksFor("bluff"), OverlayHognose);
  assert.equal(OverlayGround.tricksFor("garter"), OverlayGarter);
  assert.equal(OverlayGround.tricksFor("sash"), OverlayGarter);
  assert.equal(OverlayGround.tricksFor("boa"), OverlayBoa);
  assert.equal(OverlayGround.tricksFor("lula"), OverlayBoa);
  assert.equal(OverlayGround.tricksFor("milk_snake"), OverlayMilkSnake);
  assert.equal(OverlayGround.tricksFor("coral"), OverlayMilkSnake);
  assert.equal(OverlayGround.tricksFor("rosy_boa"), OverlayRosyBoa);
  assert.equal(OverlayGround.tricksFor("blush"), OverlayRosyBoa);
  assert.equal(OverlayGround.tricksFor("carpet_python"), Overlay);
  assert.equal(OverlayGround.tricksFor("atlas"), Overlay);
  assert.equal(OverlayGround.wantsThankYou("red_panda"), true);
  assert.equal(OverlayGround.wantsThankYou("cat"), true);
  assert.equal(OverlayGround.wantsThankYou("miso"), true);
  assert.equal(OverlayGround.wantsThankYou("dog"), true);
  assert.equal(OverlayGround.wantsThankYou("pip"), true);
  assert.equal(OverlayGround.wantsThankYou("ball_python"), true);
  assert.equal(OverlayGround.wantsThankYou("nori"), true);
  assert.equal(OverlayGround.wantsThankYou("corn_snake"), true);
  assert.equal(OverlayGround.wantsThankYou("saffron"), true);
  assert.equal(OverlayGround.wantsThankYou("kingsnake"), true);
  assert.equal(OverlayGround.wantsThankYou("bandit"), true);
  assert.equal(OverlayGround.wantsThankYou("hognose"), true);
  assert.equal(OverlayGround.wantsThankYou("bluff"), true);
  assert.equal(OverlayGround.wantsThankYou("garter"), true);
  assert.equal(OverlayGround.wantsThankYou("sash"), true);
  assert.equal(OverlayGround.wantsThankYou("boa"), true);
  assert.equal(OverlayGround.wantsThankYou("lula"), true);
  assert.equal(OverlayGround.wantsThankYou("milk_snake"), true);
  assert.equal(OverlayGround.wantsThankYou("coral"), true);
  assert.equal(OverlayGround.wantsThankYou("rosy_boa"), true);
  assert.equal(OverlayGround.wantsThankYou("blush"), true);
  assert.equal(OverlayGround.wantsThankYou("carpet_python"), true);
  assert.equal(OverlayGround.wantsThankYou("atlas"), true);
  assert.equal(OverlayGround.wantsThankYou("phoenix"), true);
  assert.equal(OverlayGround.wantsThankYou("ember"), true);
  assert.equal(OverlayGround.sleepHoldFrame("red_panda", 4), 1);
  assert.equal(OverlayGround.sleepHoldFrame("ball_python", 4), null);
  assert.equal(OverlayGround.sleepHoldFrame("kingsnake", 4), null);
  assert.equal(OverlayGround.sleepHoldFrame("hognose", 4), null);
  assert.equal(OverlayGround.sleepHoldFrame("garter", 4), null);
  assert.equal(OverlayGround.sleepHoldFrame("boa", 4), null);
  assert.equal(OverlayGround.sleepHoldFrame("carpet_python", 4), null);
  assert.deepEqual([...OverlayBallPython.TRICKS], ["orb", "nook", "taste", "inch", "unroll", "loom", "weave"]);
  assert.deepEqual([...OverlayCornSnake.TRICKS], ["scribble", "gap", "comma", "probe", "canyon", "blotter", "pencil"]);
  assert.deepEqual([...OverlayKingsnake.TRICKS], ["stripe", "audit", "verdict", "plumb", "raid", "band", "drawer"]);
  assert.deepEqual([...OverlayGreenTreePython.TRICKS], ["bracelet", "sway", "jewel", "heat", "bough", "liana", "arbor"]);
  assert.deepEqual([...OverlayHognose.TRICKS], ["hood", "feign", "shovel", "gape", "encore", "quiver", "upright"]);
  assert.deepEqual([...OverlayGarter.TRICKS], ["seam", "rounds", "moss", "fork", "lap", "ribbon", "creek"]);
  assert.deepEqual([...OverlayBoa.TRICKS], ["pour", "heft", "oxbow", "slack", "bank", "anchor", "meander"]);
  assert.deepEqual([...Overlay.TRICKS], ["legend", "rung", "contour", "runner", "bearing", "canopy", "inset"]);
  assert.equal(Overlay.TRICKS.includes("orb"), false);
  assert.equal(Overlay.TRICKS.includes("write"), false);
  assert.equal(Overlay.TRICKS.includes("flip"), false);
  assert.equal(Overlay.TRICKS.includes("loop"), false);
  assert.equal(Overlay.TRICKS.includes("mosaic"), false);
  assert.equal(Overlay.TRICKS.includes("patrol"), false);
  assert.equal(Overlay.TRICKS.includes("bracelet"), false);
  assert.equal(Overlay.TRICKS.includes("scribble"), false);
  assert.equal(Overlay.TRICKS.includes("stripe"), false);
  assert.equal(Overlay.TRICKS.includes("hood"), false);
  assert.equal(Overlay.TRICKS.includes("seam"), false);
  assert.equal(Overlay.TRICKS.includes("pour"), false);
  assert.equal(Overlay.TRICKS.includes("mimic"), false);
  assert.equal(Overlay.TRICKS.includes("chart"), false);
  assert.equal(Overlay.TRICKS.includes("unroll"), false);
  assert.equal(Overlay.TRICKS.includes("bracelet"), false);
  assert.equal(Overlay.TRICKS.includes("pebble"), false);
});

test("ultra-polish: Atlas legend/canopy/inset lifts are Rui-visible (not micro idle-gen)", () => {
  const lg = T.beginTrick("legend", 80, 1);
  const mid = T.stepTrick(lg, 5, { cmd: "idle" });
  assert.ok(Math.abs(mid.rot) > 10, `legend mid rot ${mid.rot}`);
  assert.ok(Math.abs(mid.lift) > 0.5, `legend mid lift ${mid.lift}`);
  const ca = T.beginTrick("canopy", 80, 1);
  const c2 = T.stepTrick(ca, T.DUR.canopy * 0.4, { cmd: "idle" });
  assert.ok(c2.lift > 2 || Math.abs(c2.rot) > 8 || Math.abs(c2.x - 80) > 1, `canopy mid ${c2.lift}/${c2.rot}/${c2.x}`);
  const inn = T.beginTrick("inset", 80, 1);
  const i2 = T.stepTrick(inn, T.DUR.inset * 0.45, { cmd: "idle" });
  assert.ok(Math.abs(i2.lift) > 0.8 || Math.abs(i2.rot) > 4 || Math.abs(i2.x - 80) > 0.3, `inset mid ${i2.lift}/${i2.rot}/${i2.x}`);
  const ru = T.beginTrick("rung", 80, 1);
  const r2 = T.stepTrick(ru, T.DUR.rung * 0.4, { cmd: "idle" });
  assert.ok(r2.lift > 0.5 || Math.abs(r2.rot) > 4 || Math.abs(r2.x - 80) > 0.5, `rung mid ${r2.lift}/${r2.rot}/${r2.x}`);
  assert.ok(Overlay.canopyPose && Overlay.insetPose);
  assert.deepEqual([...T.TRICKS], [...Overlay.TRICKS]);
  assert.equal(T.LEGEND_HOLD, Overlay.LEGEND_HOLD);
  assert.equal(T.LEGEND_HOLD, 11.2);
  assert.equal(T.RELEASE_S, 1.18);
  assert.ok(T.nextTrickWait(true, 0, "legend") > 39);
});

test("notes: Atlas Rui-dense ultra (LEGEND_HOLD=11.2); Cup densified; Sepia densified; Chamber densified; Pulse densified; Ochre densified; Tenant densified; Ledger densified; Anchor densified; Kite densified; Door densified; Felt densified; Vein densified; next leftover Fan / ginkgo", () => {
  assert.equal(T.TRICK_KEY, "carpet_python");
  assert.equal(T.wantsThankYou("atlas"), true);
  assert.equal(OverlayGround.tricksFor("boa"), OverlayBoa);
  assert.equal(OverlayGround.tricksFor("lula"), OverlayBoa);
  assert.equal(OverlayGround.wantsThankYou("boa"), true);
  assert.equal(OverlayGround.wantsThankYou("lula"), true);
  assert.equal(OverlayGround.tricksFor("garter"), OverlayGarter);
  assert.equal(OverlayGround.tricksFor("sash"), OverlayGarter);
  assert.equal(OverlayGround.wantsThankYou("garter"), true);
  assert.equal(OverlayGround.wantsThankYou("sash"), true);
  assert.equal(OverlayGround.tricksFor("hognose"), OverlayHognose);
  assert.equal(OverlayGround.tricksFor("bluff"), OverlayHognose);
  assert.equal(OverlayGround.tricksFor("milk_snake"), OverlayMilkSnake);
  assert.equal(OverlayGround.tricksFor("coral"), OverlayMilkSnake);
  assert.equal(OverlayGround.wantsThankYou("milk_snake"), true);
  assert.equal(OverlayGround.wantsThankYou("coral"), true);
  assert.equal(OverlayGround.tricksFor("rosy_boa"), OverlayRosyBoa);
  assert.equal(OverlayGround.tricksFor("blush"), OverlayRosyBoa);
  assert.equal(OverlayGround.wantsThankYou("rosy_boa"), true);
  assert.equal(OverlayGround.wantsThankYou("blush"), true);
  assert.equal(OverlayGround.tricksFor("carpet_python"), Overlay);
  assert.equal(OverlayGround.tricksFor("atlas"), Overlay);
  assert.equal(OverlayGround.wantsThankYou("carpet_python"), true);
  assert.equal(OverlayGround.wantsThankYou("atlas"), true);
  assert.equal(OverlayGround.tricksFor("green_tree_python"), OverlayGreenTreePython);
  assert.equal(OverlayGround.tricksFor("jade"), OverlayGreenTreePython);
  assert.equal(OverlayGround.wantsThankYou("green_tree_python"), true);
  assert.equal(OverlayGround.wantsThankYou("jade"), true);
  assert.equal(OverlayGround.tricksFor("kingsnake"), OverlayKingsnake);
  assert.equal(OverlayGround.tricksFor("bandit"), OverlayKingsnake);
  assert.equal(OverlayGround.wantsThankYou("kingsnake"), true);
  assert.equal(OverlayGround.wantsThankYou("bandit"), true);
  assert.equal(OverlayGround.tricksFor("corn_snake"), OverlayCornSnake);
  assert.equal(OverlayGround.tricksFor("saffron"), OverlayCornSnake);
  assert.equal(OverlayGround.wantsThankYou("corn_snake"), true);
  assert.equal(OverlayGround.wantsThankYou("saffron"), true);
  assert.equal(OverlayGround.tricksFor("ball_python"), OverlayBallPython);
  assert.equal(OverlayGround.tricksFor("nori"), OverlayBallPython);
  assert.equal(OverlayGround.wantsThankYou("ball_python"), true);
  assert.equal(OverlayGround.wantsThankYou("nori"), true);
  assert.equal(OverlayGround.tricksFor("octopus") == null, true);
  assert.equal(OverlayGround.wantsThankYou("octopus"), false);
  assert.equal(OverlayGround.tricksFor("cup") == null, true);
});


