import assert from "node:assert/strict";
import { createRequire } from "node:module";
import { dirname, join } from "node:path";
import { test } from "node:test";
import { fileURLToPath, pathToFileURL } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const T = await import(pathToFileURL(join(root, "src/lib/pets/cat-tricks.ts")).href);
const Rui = await import(pathToFileURL(join(root, "src/lib/pets/rui-tricks.ts")).href);
const Relay = await import(pathToFileURL(join(root, "src/lib/pets/relay-tricks.ts")).href);
const Fuse = await import(pathToFileURL(join(root, "src/lib/pets/fuse-tricks.ts")).href);
const Earth = await import(pathToFileURL(join(root, "src/lib/pets/earth-tricks.ts")).href);
const Overlay = createRequire(import.meta.url)(join(root, "../desktop/renderer/cat-tricks.js"));
const OverlayGround = createRequire(import.meta.url)(join(root, "../desktop/renderer/ground-tricks.js"));
const OverlayRui = createRequire(import.meta.url)(join(root, "../desktop/renderer/rui-tricks.js"));
const OverlayRelay = createRequire(import.meta.url)(join(root, "../desktop/renderer/relay-tricks.js"));
const OverlayFuse = createRequire(import.meta.url)(join(root, "../desktop/renderer/fuse-tricks.js"));
const OverlayEarth = createRequire(import.meta.url)(join(root, "../desktop/renderer/earth-tricks.js"));

test("Miso tricks start only on idle ground", () => {
  assert.deepEqual([...T.TRICKS], ["loaf", "knead", "stretch", "wash", "pounce"]);
  assert.equal(T.canStart({ asleep: false, hidden: false, leaving: false, cmd: "idle" }), true);
  assert.equal(T.canStart({ asleep: true, hidden: false, leaving: false, cmd: "idle" }), false);
  assert.equal(T.canStart({ asleep: false, hidden: true, leaving: false, cmd: "idle" }), false);
  assert.equal(T.canStart({ asleep: false, hidden: false, leaving: false, cmd: "sleep" }), false);
  assert.equal(T.canStart({ asleep: false, hidden: false, leaving: false, cmd: "seek" }), false);
  assert.equal(T.canStart({ asleep: false, hidden: false, leaving: false, cmd: "idle", windowPlay: true }), false);
  assert.equal(T.canStart({ asleep: false, hidden: false, leaving: false, cmd: "idle", card: true }), false);
  assert.equal(T.shouldAbort({ asleep: true, hidden: false, leaving: false, cmd: "idle" }), true);
  assert.equal(T.shouldAbort({ asleep: false, hidden: false, leaving: false, cmd: "idle", card: true }), true);
  assert.equal(T.shouldAbort({ asleep: false, hidden: false, leaving: false, cmd: "idle" }), false);
  assert.equal(T.pickTrick(0.99, true), "loaf");
  assert.notEqual(T.pickTrick(0.3, false, "loaf"), "loaf");
  assert.equal(Overlay.TRICK_KEY, "cat");
  assert.equal(T.sleepHoldFrame("cat", 4), null);
  assert.equal(T.TRICKS.includes("somersault"), false);
  assert.equal(T.TRICKS.includes("scratch"), false);
  assert.equal(T.TRICKS.includes("lug"), false);
  assert.equal(T.TRICKS.includes("seat"), false);
  assert.equal(T.TRICKS.includes("click"), false);
});

test("loaf/knead/stretch/wash/pounce are house-cat-true, not Rui or dragon clones", () => {
  const ground = { asleep: false, hidden: false, leaving: false, cmd: "idle" };
  const loaf = T.beginTrick("loaf", 80, 1);
  assert.equal(loaf.anim, "sit");
  assert.equal(loaf.phase, "hold");
  const held = T.stepTrick(loaf, 5, ground);
  assert.equal(held.phase, "hold");
  assert.equal(held.anim, "sit");
  assert.equal(held.rot, 0);
  assert.ok(held.lift < 0);
  const release = T.stepTrick(loaf, T.LOAF_HOLD + 0.2, ground);
  assert.equal(release.phase, "release");
  assert.equal(release.anim, "sit");
  const doneLoaf = T.stepTrick(loaf, T.DUR.loaf + 0.1, ground);
  assert.equal(doneLoaf.phase, "done");
  assert.ok(T.nextTrickWait(true, 0, "loaf") > T.nextTrickWait(true, 0, "knead"));
  const knead = T.beginTrick("knead", 80, 1);
  assert.equal(knead.anim, "sit");
  const kneadMid = T.stepTrick(knead, 0.25, ground);
  assert.ok(Math.abs(kneadMid.rot) > 0.5 || kneadMid.lift !== -1.5);
  const stretch = T.beginTrick("stretch", 80, 1);
  assert.equal(stretch.anim, "sit");
  const stretchMid = T.stepTrick(stretch, 0.5, ground);
  assert.ok(stretchMid.rot < -2 || stretchMid.lift < 0);
  const wash = T.beginTrick("wash", 80, 1);
  assert.equal(wash.anim, "sit");
  const washMid = T.stepTrick(wash, 0.3, ground);
  assert.ok(Math.abs(washMid.rot) > 1);
  const pounce = T.beginTrick("pounce", 80, 1);
  assert.equal(pounce.anim, "play");
  const pounceMid = T.stepTrick(pounce, 0.45, ground);
  assert.ok(pounceMid.lift > 2);
  assert.ok(Math.abs(pounceMid.x - 80) > 2);
  const pounceDone = T.stepTrick(pounce, 1.2, ground);
  assert.equal(pounceDone.phase, "done");
  const aborted = T.stepTrick(held, 0.1, { asleep: true, cmd: "sleep" });
  assert.equal(aborted.phase, "done");
  assert.equal(Rui.TRICKS.includes("loaf"), false);
  assert.equal(Relay.TRICKS.includes("knead"), false);
  assert.equal(Fuse.TRICKS.includes("wash"), false);
  assert.equal(Earth.TRICKS.includes("pounce"), false);
  assert.equal(Rui.TRICKS.includes("pounce"), false);
});

test("Miso feed-happy is its own sit: purr/blink/chirp, and two feeds are not the same", () => {
  assert.deepEqual([...T.HAPPY], ["purr", "blink", "chirp"]);
  assert.equal(T.HAPPY.includes("spark"), false);
  assert.equal(T.HAPPY.includes("hum"), false);
  assert.equal(T.HAPPY.includes("twirl"), false);
  assert.equal(T.pickHappy("purr", 0), "blink");
  assert.notEqual(T.pickHappy("purr", 0.9), "purr");
  assert.equal(Overlay.pickHappy("blink", 0) !== "blink", true);
  assert.equal(T.happyCanStart({ asleep: false, hidden: false, leaving: false, cmd: "idle" }), true);
  assert.equal(T.happyCanStart({ asleep: false, hidden: false, leaving: false, cmd: "idle", card: true }), true);
  assert.equal(T.happyCanStart({ asleep: true, hidden: false, leaving: false, cmd: "idle" }), false);
  assert.equal(T.happyShouldAbort({ cmd: "sleep" }), true);
  assert.equal(T.happyShouldAbort({ cmd: "hide" }), true);
  assert.equal(T.happyShouldAbort({ card: true, cmd: "idle" }), false);
  const purr = T.beginHappy("purr", 80, 1);
  assert.equal(purr.anim, "talk");
  const purrMid = T.stepHappy(purr, 0.4, { cmd: "idle" });
  assert.ok(purrMid.lift > 0.3 || Math.abs(purrMid.rot) > 0.5);
  assert.notEqual(purrMid.phase, "done");
  const blink = T.beginHappy("blink", 80, 1);
  assert.equal(blink.anim, "sit");
  const blinkMid = T.stepHappy(blink, 0.3, { cmd: "idle" });
  assert.ok(blinkMid.lift < 0);
  const chirp = T.beginHappy("chirp", 80, 1);
  assert.equal(chirp.anim, "play");
  const done = T.stepHappy(purr, T.HAPPY_DUR.purr + 0.1, { cmd: "idle" });
  assert.equal(done.phase, "done");
  const aborted = T.stepHappy(purrMid, 0.1, { asleep: true, cmd: "sleep" });
  assert.equal(aborted.phase, "done");
  assert.equal(aborted.abort, true);
  assert.equal(T.wantsThankYou("cat"), true);
  assert.equal(T.wantsThankYou("miso"), true);
  assert.equal(T.wantsThankYou("red_panda"), false);
  assert.equal(T.wantsThankYou("ground_dragon"), false);
  const thanks = T.startThankYou("cat", "purr", 80, 1, { cmd: "idle", card: true, windowPlay: true });
  assert.ok(thanks);
  assert.notEqual(thanks.kind, "purr");
  assert.ok(thanks.happy.lift === 0);
  assert.notEqual(thanks.happy.anim, "eat");
  assert.notEqual(thanks.happy.anim, "idle");
  const thanksMid = T.stepHappy(thanks.happy, 0.35, { cmd: "idle", card: true });
  assert.ok(thanksMid.lift !== 0 || Math.abs(thanksMid.rot) > 0.5, "a thank-you purrs or blinks");
  const blocked = T.startThankYou("cat", "blink", 80, 1, { asleep: true, cmd: "idle" });
  assert.equal(blocked, null);
  const other = T.startThankYou("dog", null, 80, 1, { cmd: "idle" });
  assert.equal(other, null);
  const second = T.startThankYou("cat", thanks.kind, 80, 1, { cmd: "idle", card: true });
  assert.ok(second);
  assert.notEqual(second.kind, thanks.kind);
});

test("ground registry keeps prior guests gated; Miso selectable; no scratch-name collision", () => {
  assert.equal(Rui.TRICK_KEY, "red_panda");
  assert.equal(Relay.TRICK_KEY, "relay_dragon");
  assert.equal(Fuse.TRICK_KEY, "fuse_dragon");
  assert.equal(Earth.TRICK_KEY, "ground_dragon");
  assert.equal(T.TRICK_KEY, "cat");
  assert.deepEqual([...Rui.TRICKS], ["somersault", "lie", "scratch", "wave", "dance"]);
  assert.deepEqual([...Relay.TRICKS], ["click", "latch", "arc", "buzz", "switch"]);
  assert.deepEqual([...Fuse.TRICKS], ["seat", "current", "blow", "reseat"]);
  assert.deepEqual([...Earth.TRICKS], ["lug", "earth", "heave", "bed"]);
  assert.equal(T.TRICKS.includes("scratch"), false);
  assert.equal(Rui.wantsThankYou("cat"), false);
  assert.equal(Relay.wantsThankYou("cat"), false);
  assert.equal(Fuse.wantsThankYou("cat"), false);
  assert.equal(Earth.wantsThankYou("cat"), false);
  assert.equal(T.wantsThankYou("cat"), true);
  assert.equal(T.wantsThankYou("miso"), true);
  assert.equal(T.wantsThankYou("red_panda"), false);
  assert.equal(Rui.sleepHoldFrame("red_panda", 4), 1);
  assert.equal(T.sleepHoldFrame("cat", 4), null);
  globalThis.PetRuiTricks = OverlayRui;
  globalThis.PetRelayTricks = OverlayRelay;
  globalThis.PetFuseTricks = OverlayFuse;
  globalThis.PetEarthTricks = OverlayEarth;
  globalThis.PetCatTricks = Overlay;
  assert.equal(OverlayGround.tricksFor("red_panda"), OverlayRui);
  assert.equal(OverlayGround.tricksFor("rui"), OverlayRui);
  assert.equal(OverlayGround.tricksFor("relay_dragon"), OverlayRelay);
  assert.equal(OverlayGround.tricksFor("fuse_dragon"), OverlayFuse);
  assert.equal(OverlayGround.tricksFor("ground_dragon"), OverlayEarth);
  assert.equal(OverlayGround.tricksFor("ground"), OverlayEarth);
  assert.equal(OverlayGround.tricksFor("cat"), Overlay);
  assert.equal(OverlayGround.tricksFor("miso"), Overlay);
  assert.equal(OverlayGround.tricksFor("dog"), null);
  assert.equal(OverlayGround.wantsThankYou("red_panda"), true);
  assert.equal(OverlayGround.wantsThankYou("relay_dragon"), true);
  assert.equal(OverlayGround.wantsThankYou("fuse_dragon"), true);
  assert.equal(OverlayGround.wantsThankYou("ground_dragon"), true);
  assert.equal(OverlayGround.wantsThankYou("cat"), true);
  assert.equal(OverlayGround.wantsThankYou("miso"), true);
  assert.equal(OverlayGround.wantsThankYou("dog"), false);
  assert.equal(OverlayGround.sleepHoldFrame("red_panda", 4), 1);
  assert.equal(OverlayGround.sleepHoldFrame("cat", 4), null);
});
