import assert from "node:assert/strict";
import { createRequire } from "node:module";
import { dirname, join } from "node:path";
import { test } from "node:test";
import { fileURLToPath, pathToFileURL } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const T = await import(pathToFileURL(join(root, "src/lib/pets/chinchilla-tricks.ts")).href);
const Rui = await import(pathToFileURL(join(root, "src/lib/pets/rui-tricks.ts")).href);
const Relay = await import(pathToFileURL(join(root, "src/lib/pets/relay-tricks.ts")).href);
const Fuse = await import(pathToFileURL(join(root, "src/lib/pets/fuse-tricks.ts")).href);
const Earth = await import(pathToFileURL(join(root, "src/lib/pets/earth-tricks.ts")).href);
const Cat = await import(pathToFileURL(join(root, "src/lib/pets/cat-tricks.ts")).href);
const Dog = await import(pathToFileURL(join(root, "src/lib/pets/dog-tricks.ts")).href);
const Rabbit = await import(pathToFileURL(join(root, "src/lib/pets/rabbit-tricks.ts")).href);
const Hamster = await import(pathToFileURL(join(root, "src/lib/pets/hamster-tricks.ts")).href);
const GuineaPig = await import(pathToFileURL(join(root, "src/lib/pets/guinea-pig-tricks.ts")).href);
const Turtle = await import(pathToFileURL(join(root, "src/lib/pets/turtle-tricks.ts")).href);
const Goldfish = await import(pathToFileURL(join(root, "src/lib/pets/goldfish-tricks.ts")).href);
const Budgie = await import(pathToFileURL(join(root, "src/lib/pets/budgie-tricks.ts")).href);
const Fox = await import(pathToFileURL(join(root, "src/lib/pets/fox-tricks.ts")).href);
const Penguin = await import(pathToFileURL(join(root, "src/lib/pets/penguin-tricks.ts")).href);
const Parrot = await import(pathToFileURL(join(root, "src/lib/pets/parrot-tricks.ts")).href);
const Ferret = await import(pathToFileURL(join(root, "src/lib/pets/ferret-tricks.ts")).href);
const Hedgehog = await import(pathToFileURL(join(root, "src/lib/pets/hedgehog-tricks.ts")).href);
const Overlay = createRequire(import.meta.url)(join(root, "../desktop/renderer/chinchilla-tricks.js"));
const OverlayGround = createRequire(import.meta.url)(join(root, "../desktop/renderer/ground-tricks.js"));
const OverlayRui = createRequire(import.meta.url)(join(root, "../desktop/renderer/rui-tricks.js"));
const OverlayRelay = createRequire(import.meta.url)(join(root, "../desktop/renderer/relay-tricks.js"));
const OverlayFuse = createRequire(import.meta.url)(join(root, "../desktop/renderer/fuse-tricks.js"));
const OverlayEarth = createRequire(import.meta.url)(join(root, "../desktop/renderer/earth-tricks.js"));
const OverlayCat = createRequire(import.meta.url)(join(root, "../desktop/renderer/cat-tricks.js"));
const OverlayDog = createRequire(import.meta.url)(join(root, "../desktop/renderer/dog-tricks.js"));
const OverlayRabbit = createRequire(import.meta.url)(join(root, "../desktop/renderer/rabbit-tricks.js"));
const OverlayHamster = createRequire(import.meta.url)(join(root, "../desktop/renderer/hamster-tricks.js"));
const OverlayGuineaPig = createRequire(import.meta.url)(join(root, "../desktop/renderer/guinea-pig-tricks.js"));
const OverlayTurtle = createRequire(import.meta.url)(join(root, "../desktop/renderer/turtle-tricks.js"));
const OverlayGoldfish = createRequire(import.meta.url)(join(root, "../desktop/renderer/goldfish-tricks.js"));
const OverlayBudgie = createRequire(import.meta.url)(join(root, "../desktop/renderer/budgie-tricks.js"));
const OverlayFox = createRequire(import.meta.url)(join(root, "../desktop/renderer/fox-tricks.js"));
const OverlayPenguin = createRequire(import.meta.url)(join(root, "../desktop/renderer/penguin-tricks.js"));
const OverlayParrot = createRequire(import.meta.url)(join(root, "../desktop/renderer/parrot-tricks.js"));
const OverlayFerret = createRequire(import.meta.url)(join(root, "../desktop/renderer/ferret-tricks.js"));
const OverlayHedgehog = createRequire(import.meta.url)(join(root, "../desktop/renderer/hedgehog-tricks.js"));
const OverlayAxolotl = createRequire(import.meta.url)(join(root, "../desktop/renderer/axolotl-tricks.js"));
const OverlayToucan = createRequire(import.meta.url)(join(root, "../desktop/renderer/toucan-tricks.js"));

test("Floss tricks start only on idle ground", () => {
  assert.deepEqual([...T.TRICKS], ["ash", "bound", "fluff", "chin", "sift"]);
  assert.equal(T.canStart({ asleep: false, hidden: false, leaving: false, cmd: "idle" }), true);
  assert.equal(T.canStart({ asleep: true, hidden: false, leaving: false, cmd: "idle" }), false);
  assert.equal(T.canStart({ asleep: false, hidden: true, leaving: false, cmd: "idle" }), false);
  assert.equal(T.canStart({ asleep: false, hidden: false, leaving: false, cmd: "sleep" }), false);
  assert.equal(T.canStart({ asleep: false, hidden: false, leaving: false, cmd: "seek" }), false);
  assert.equal(T.canStart({ asleep: false, hidden: false, leaving: false, cmd: "idle", windowPlay: true }), false);
  assert.equal(T.canStart({ asleep: false, hidden: false, leaving: false, cmd: "idle", card: true }), false);
  assert.equal(T.shouldAbort({ asleep: true, hidden: false, leaving: false, cmd: "idle" }), true);
  assert.equal(T.shouldAbort({ asleep: false, hidden: false, leaving: false, cmd: "idle", card: true }), true);
  assert.equal(T.shouldAbort({ asleep: false, hidden: false, leaving: false, cmd: "idle" }), false);
  assert.equal(T.pickTrick(0.99, true), "ash");
  assert.notEqual(T.pickTrick(0.3, false, "ash"), "ash");
  assert.equal(Overlay.TRICK_KEY, "chinchilla");
  assert.equal(T.sleepHoldFrame("chinchilla", 4), null);
  assert.equal(T.TRICKS.includes("dust"), false);
  assert.equal(T.TRICKS.includes("ball"), false);
  assert.equal(T.TRICKS.includes("tube"), false);
  assert.equal(T.TRICKS.includes("dig"), false);
  assert.equal(T.TRICKS.includes("puff"), false);
  assert.equal(T.TRICKS.includes("potato"), false);
  assert.equal(T.TRICKS.includes("tuck"), false);
  assert.equal(T.TRICKS.includes("loaf"), false);
  assert.equal(T.TRICKS.includes("nest"), false);
  assert.equal(T.TRICKS.includes("scurry"), false);
  assert.equal(T.TRICKS.includes("den"), false);
  assert.equal(T.TRICKS.includes("zoom"), false);
  assert.equal(T.TRICKS.includes("dance"), false);
  assert.equal(T.TRICKS.includes("pounce"), false);
  assert.equal(T.TRICKS.includes("thread"), false);
  assert.equal(T.TRICKS.includes("noodle"), false);
  assert.equal(T.TRICKS.includes("steal"), false);
  assert.equal(T.TRICKS.includes("curl"), false);
  assert.equal(T.TRICKS.includes("snuffle"), false);
  assert.equal(T.TRICKS.includes("anoint"), false);
  assert.equal(T.TRICKS.includes("bristle"), false);
  assert.equal(T.TRICKS.includes("root"), false);
  assert.equal(T.TRICKS.includes("popcorn"), false);
  assert.equal(T.TRICKS.includes("groom"), false);
});

test("ash/bound/fluff/chin/sift are house-chinchilla-true, not Rui cat dog rabbit hamster guinea-pig turtle goldfish budgie fox penguin parrot ferret hedgehog or dragon clones", () => {
  const ground = { asleep: false, hidden: false, leaving: false, cmd: "idle" };
  const ash = T.beginTrick("ash", 80, 1);
  assert.equal(ash.anim, "sit");
  assert.equal(ash.phase, "hold");
  const held = T.stepTrick(ash, 5, ground);
  assert.equal(held.phase, "hold");
  assert.equal(held.anim, "sit");
  assert.ok(held.rot !== 0 || held.lift > 0);
  const release = T.stepTrick(ash, T.ASH_HOLD + 0.2, ground);
  assert.equal(release.phase, "release");
  assert.equal(release.anim, "sit");
  const doneCurl = T.stepTrick(ash, T.DUR.ash + 0.1, ground);
  assert.equal(doneCurl.phase, "done");
  assert.ok(T.nextTrickWait(true, 0, "ash") > T.nextTrickWait(true, 0, "bound"));
  const bound = T.beginTrick("bound", 80, 1);
  assert.equal(bound.anim, "play");
  const boundMid = T.stepTrick(bound, 0.6, ground);
  assert.ok(Math.abs(boundMid.x - 80) > 1 || Math.abs(boundMid.lift) > 0.3 || Math.abs(boundMid.rot) > 1);
  const fluff = T.beginTrick("fluff", 80, 1);
  assert.equal(fluff.anim, "sit");
  const fluffMid = T.stepTrick(fluff, 0.55, ground);
  assert.ok(Math.abs(fluffMid.lift) > 0.2 || Math.abs(fluffMid.rot) > 1);
  const chin = T.beginTrick("chin", 80, 1);
  assert.equal(chin.anim, "sit");
  const chinMid = T.stepTrick(chin, 0.4, ground);
  assert.ok(Math.abs(chinMid.lift) > 0.2 || Math.abs(chinMid.rot) > 1);
  const sift = T.beginTrick("sift", 80, 1);
  assert.equal(sift.anim, "play");
  const siftMid = T.stepTrick(sift, 0.45, ground);
  assert.ok(Math.abs(siftMid.x - 80) > 0.5 || Math.abs(siftMid.lift) > 0.3 || Math.abs(siftMid.rot) > 1);
  const siftDone = T.stepTrick(sift, 1.4, ground);
  assert.equal(siftDone.phase, "done");
  const aborted = T.stepTrick(held, 0.1, { asleep: true, cmd: "sleep" });
  assert.equal(aborted.phase, "done");
  assert.equal(Rui.TRICKS.includes("ash"), false);
  assert.equal(Cat.TRICKS.includes("bound"), false);
  assert.equal(Dog.TRICKS.includes("fluff"), false);
  assert.equal(Rabbit.TRICKS.includes("chin"), false);
  assert.equal(Hamster.TRICKS.includes("sift"), false);
  assert.equal(GuineaPig.TRICKS.includes("ash"), false);
  assert.equal(Turtle.TRICKS.includes("bound"), false);
  assert.equal(Goldfish.TRICKS.includes("fluff"), false);
  assert.equal(Budgie.TRICKS.includes("chin"), false);
  assert.equal(Fox.TRICKS.includes("sift"), false);
  assert.equal(Penguin.TRICKS.includes("ash"), false);
  assert.equal(Parrot.TRICKS.includes("bound"), false);
  assert.equal(Ferret.TRICKS.includes("fluff"), false);
  assert.equal(Relay.TRICKS.includes("ash"), false);
  assert.equal(Fuse.TRICKS.includes("bound"), false);
  assert.equal(Earth.TRICKS.includes("fluff"), false);
  assert.equal(Hedgehog.TRICKS.includes("ash"), false);
  assert.equal(Hedgehog.TRICKS.includes("bound"), false);
  assert.equal(Hedgehog.TRICKS.includes("fluff"), false);
  assert.equal(Hedgehog.TRICKS.includes("chin"), false);
  assert.equal(Hedgehog.TRICKS.includes("sift"), false);
  assert.equal(T.TRICKS.includes("dust"), false);
  assert.equal(T.TRICKS.includes("ball"), false);
  assert.equal(T.TRICKS.includes("tube"), false);
  assert.equal(T.TRICKS.includes("dig"), false);
  assert.equal(T.TRICKS.includes("puff"), false);
  assert.equal(T.TRICKS.includes("curl"), false);
});

test("Floss feed-happy is its own sit: eep/coo/bark, and two feeds are not the same", () => {
  assert.deepEqual([...T.HAPPY], ["eep", "coo", "bark"]);
  assert.equal(T.HAPPY.includes("spark"), false);
  assert.equal(T.HAPPY.includes("purr"), false);
  assert.equal(T.HAPPY.includes("tail"), false);
  assert.equal(T.HAPPY.includes("twitch"), false);
  assert.equal(T.HAPPY.includes("stuff"), false);
  assert.equal(T.HAPPY.includes("peep"), false);
  assert.equal(T.HAPPY.includes("munch"), false);
  assert.equal(T.HAPPY.includes("huff"), false);
  assert.equal(T.HAPPY.includes("gleam"), false);
  assert.equal(T.HAPPY.includes("bubble"), false);
  assert.equal(T.HAPPY.includes("chirp"), false);
  assert.equal(T.HAPPY.includes("chatter"), false);
  assert.equal(T.HAPPY.includes("bob"), false);
  assert.equal(T.HAPPY.includes("whistle"), false);
  assert.equal(T.HAPPY.includes("trill"), false);
  assert.equal(T.HAPPY.includes("ruffle"), false);
  assert.equal(T.HAPPY.includes("yip"), false);
  assert.equal(T.HAPPY.includes("chuff"), false);
  assert.equal(T.HAPPY.includes("nuzzle"), false);
  assert.equal(T.HAPPY.includes("woof"), false);
  assert.equal(T.HAPPY.includes("bray"), false);
  assert.equal(T.HAPPY.includes("beak"), false);
  assert.equal(T.HAPPY.includes("shimmy"), false);
  assert.equal(T.HAPPY.includes("squawk"), false);
  assert.equal(T.HAPPY.includes("bravo"), false);
  assert.equal(T.HAPPY.includes("scissor"), false);
  assert.equal(T.HAPPY.includes("chitter"), false);
  assert.equal(T.HAPPY.includes("bounce"), false);
  assert.equal(T.HAPPY.includes("shuffle"), false);
  assert.equal(T.HAPPY.includes("nibble"), false);
  assert.equal(T.HAPPY.includes("dook"), false);
  assert.equal(T.HAPPY.includes("kiss"), false);
  assert.equal(T.HAPPY.includes("chuckle"), false);
  assert.equal(T.HAPPY.includes("snort"), false);
  assert.equal(T.HAPPY.includes("soft"), false);
  assert.equal(T.HAPPY.includes("grunt"), false);
  assert.equal(T.pickHappy("eep", 0), "coo");
  assert.notEqual(T.pickHappy("eep", 0.9), "eep");
  assert.equal(Overlay.pickHappy("coo", 0) !== "coo", true);
  assert.equal(T.happyCanStart({ asleep: false, hidden: false, leaving: false, cmd: "idle" }), true);
  assert.equal(T.happyCanStart({ asleep: false, hidden: false, leaving: false, cmd: "idle", card: true }), true);
  assert.equal(T.happyCanStart({ asleep: true, hidden: false, leaving: false, cmd: "idle" }), false);
  assert.equal(T.happyShouldAbort({ cmd: "sleep" }), true);
  assert.equal(T.happyShouldAbort({ cmd: "hide" }), true);
  assert.equal(T.happyShouldAbort({ card: true, cmd: "idle" }), false);
  const eep = T.beginHappy("eep", 80, 1);
  assert.equal(eep.anim, "talk");
  const eepMid = T.stepHappy(eep, 0.4, { cmd: "idle" });
  assert.ok(eepMid.lift !== 0 || Math.abs(eepMid.rot) > 0.5);
  assert.notEqual(eepMid.phase, "done");
  const coo = T.beginHappy("coo", 80, 1);
  assert.equal(coo.anim, "sit");
  const cooMid = T.stepHappy(coo, 0.3, { cmd: "idle" });
  assert.ok(cooMid.lift > 0.2 || Math.abs(cooMid.rot) > 0.5);
  const bark = T.beginHappy("bark", 80, 1);
  assert.equal(bark.anim, "play");
  const done = T.stepHappy(eep, T.HAPPY_DUR.eep + 0.1, { cmd: "idle" });
  assert.equal(done.phase, "done");
  const aborted = T.stepHappy(cooMid, 0.1, { asleep: true, cmd: "sleep" });
  assert.equal(aborted.phase, "done");
  assert.equal(aborted.abort, true);
  assert.equal(T.wantsThankYou("chinchilla"), true);
  assert.equal(T.wantsThankYou("floss"), true);
  assert.equal(T.wantsThankYou("hedgehog"), false);
  assert.equal(T.wantsThankYou("burr"), false);
  assert.equal(T.wantsThankYou("ferret"), false);
  assert.equal(T.wantsThankYou("wick"), false);
  assert.equal(T.wantsThankYou("parrot"), false);
  assert.equal(T.wantsThankYou("quill"), false);
  assert.equal(T.wantsThankYou("penguin"), false);
  assert.equal(T.wantsThankYou("peck"), false);
  assert.equal(T.wantsThankYou("fox"), false);
  assert.equal(T.wantsThankYou("rue"), false);
  assert.equal(T.wantsThankYou("budgie"), false);
  assert.equal(T.wantsThankYou("echo"), false);
  assert.equal(T.wantsThankYou("goldfish"), false);
  assert.equal(T.wantsThankYou("coin"), false);
  assert.equal(T.wantsThankYou("turtle"), false);
  assert.equal(T.wantsThankYou("guinea_pig"), false);
  assert.equal(T.wantsThankYou("hamster"), false);
  assert.equal(T.wantsThankYou("dog"), false);
  assert.equal(T.wantsThankYou("cat"), false);
  assert.equal(T.wantsThankYou("rabbit"), false);
  assert.equal(T.wantsThankYou("red_panda"), false);
  assert.equal(T.wantsThankYou("ground_dragon"), false);
  const thanks = T.startThankYou("chinchilla", "eep", 80, 1, { cmd: "idle", card: true, windowPlay: true });
  assert.ok(thanks);
  assert.notEqual(thanks.kind, "eep");
  assert.ok(thanks.happy.lift === 0);
  assert.notEqual(thanks.happy.anim, "eat");
  assert.notEqual(thanks.happy.anim, "idle");
  const thanksMid = T.stepHappy(thanks.happy, 0.35, { cmd: "idle", card: true });
  assert.ok(thanksMid.lift !== 0 || Math.abs(thanksMid.rot) > 0.5, "a thank-you eeps or coos");
  const blocked = T.startThankYou("chinchilla", "coo", 80, 1, { asleep: true, cmd: "idle" });
  assert.equal(blocked, null);
  const other = T.startThankYou("axolotl", null, 80, 1, { cmd: "idle" });
  assert.equal(other, null);
  const second = T.startThankYou("chinchilla", thanks.kind, 80, 1, { cmd: "idle", card: true });
  assert.ok(second);
  assert.notEqual(second.kind, thanks.kind);
});

test("ground registry keeps prior guests gated; Floss selectable; no dust/curl/ball-name collision", () => {
  assert.equal(Rui.TRICK_KEY, "red_panda");
  assert.equal(Relay.TRICK_KEY, "relay_dragon");
  assert.equal(Fuse.TRICK_KEY, "fuse_dragon");
  assert.equal(Earth.TRICK_KEY, "ground_dragon");
  assert.equal(Cat.TRICK_KEY, "cat");
  assert.equal(Dog.TRICK_KEY, "dog");
  assert.equal(Rabbit.TRICK_KEY, "rabbit");
  assert.equal(Hamster.TRICK_KEY, "hamster");
  assert.equal(GuineaPig.TRICK_KEY, "guinea_pig");
  assert.equal(Turtle.TRICK_KEY, "turtle");
  assert.equal(Goldfish.TRICK_KEY, "goldfish");
  assert.equal(Budgie.TRICK_KEY, "budgie");
  assert.equal(Fox.TRICK_KEY, "fox");
  assert.equal(Penguin.TRICK_KEY, "penguin");
  assert.equal(Parrot.TRICK_KEY, "parrot");
  assert.equal(Ferret.TRICK_KEY, "ferret");
  assert.equal(Hedgehog.TRICK_KEY, "hedgehog");
  assert.equal(T.TRICK_KEY, "chinchilla");
  assert.deepEqual([...Rui.TRICKS], ["somersault", "lie", "scratch", "wave", "dance"]);
  assert.deepEqual([...Relay.TRICKS], ["click", "latch", "arc", "buzz", "switch"]);
  assert.deepEqual([...Fuse.TRICKS], ["seat", "current", "blow", "reseat"]);
  assert.deepEqual([...Earth.TRICKS], ["lug", "earth", "heave", "bed"]);
  assert.deepEqual([...Cat.TRICKS], ["loaf", "knead", "stretch", "wash", "pounce"]);
  assert.deepEqual([...Dog.TRICKS], ["wait", "wag", "sniff", "bow", "zoom"]);
  assert.deepEqual([...Rabbit.TRICKS], ["flop", "groom", "periscope", "dig", "binky"]);
  assert.deepEqual([...Hamster.TRICKS], ["nest", "cheek", "scurry", "pocket", "reel"]);
  assert.deepEqual([...GuineaPig.TRICKS], ["popcorn", "rumble", "hay", "potato", "zig"]);
  assert.deepEqual([...Turtle.TRICKS], ["soak", "tuck", "crane", "plod", "paddle"]);
  assert.deepEqual([...Goldfish.TRICKS], ["drift", "gulp", "flare", "glint", "dart"]);
  assert.deepEqual([...Budgie.TRICKS], ["preen", "bobble", "mimic", "sidle", "dangle"]);
  assert.deepEqual([...Fox.TRICKS], ["den", "mouser", "stalk", "trot", "prance"]);
  assert.deepEqual([...Penguin.TRICKS], ["huddle", "toboggan", "waddle", "porpoise", "trumpet"]);
  assert.deepEqual([...Parrot.TRICKS], ["quote", "strut", "fan", "crack", "flash"]);
  assert.deepEqual([...Ferret.TRICKS], ["tube", "romp", "steal", "puff", "noodle"]);
  assert.deepEqual([...Hedgehog.TRICKS], ["curl", "snuffle", "anoint", "bristle", "root"]);
  assert.deepEqual([...T.TRICKS], ["ash", "bound", "fluff", "chin", "sift"]);
  assert.equal(T.TRICKS.includes("dust"), false);
  assert.equal(T.TRICKS.includes("ball"), false);
  assert.equal(T.TRICKS.includes("tube"), false);
  assert.equal(T.TRICKS.includes("dig"), false);
  assert.equal(T.TRICKS.includes("puff"), false);
  assert.equal(T.TRICKS.includes("curl"), false);
  assert.equal(Rui.wantsThankYou("chinchilla"), false);
  assert.equal(Relay.wantsThankYou("chinchilla"), false);
  assert.equal(Fuse.wantsThankYou("chinchilla"), false);
  assert.equal(Earth.wantsThankYou("chinchilla"), false);
  assert.equal(Cat.wantsThankYou("chinchilla"), false);
  assert.equal(Dog.wantsThankYou("chinchilla"), false);
  assert.equal(Rabbit.wantsThankYou("chinchilla"), false);
  assert.equal(Hamster.wantsThankYou("chinchilla"), false);
  assert.equal(GuineaPig.wantsThankYou("chinchilla"), false);
  assert.equal(Turtle.wantsThankYou("chinchilla"), false);
  assert.equal(Goldfish.wantsThankYou("chinchilla"), false);
  assert.equal(Budgie.wantsThankYou("chinchilla"), false);
  assert.equal(Fox.wantsThankYou("chinchilla"), false);
  assert.equal(Penguin.wantsThankYou("chinchilla"), false);
  assert.equal(Parrot.wantsThankYou("chinchilla"), false);
  assert.equal(Ferret.wantsThankYou("chinchilla"), false);
  assert.equal(T.wantsThankYou("chinchilla"), true);
  assert.equal(T.wantsThankYou("floss"), true);
  assert.equal(T.wantsThankYou("hedgehog"), false);
  assert.equal(T.wantsThankYou("burr"), false);
  assert.equal(T.wantsThankYou("ferret"), false);
  assert.equal(T.wantsThankYou("wick"), false);
  assert.equal(Rui.sleepHoldFrame("red_panda", 4), 1);
  assert.equal(T.sleepHoldFrame("chinchilla", 4), null);
  globalThis.PetRuiTricks = OverlayRui;
  globalThis.PetRelayTricks = OverlayRelay;
  globalThis.PetFuseTricks = OverlayFuse;
  globalThis.PetEarthTricks = OverlayEarth;
  globalThis.PetCatTricks = OverlayCat;
  globalThis.PetDogTricks = OverlayDog;
  globalThis.PetRabbitTricks = OverlayRabbit;
  globalThis.PetHamsterTricks = OverlayHamster;
  globalThis.PetGuineaPigTricks = OverlayGuineaPig;
  globalThis.PetTurtleTricks = OverlayTurtle;
  globalThis.PetGoldfishTricks = OverlayGoldfish;
  globalThis.PetBudgieTricks = OverlayBudgie;
  globalThis.PetFoxTricks = OverlayFox;
  globalThis.PetPenguinTricks = OverlayPenguin;
  globalThis.PetParrotTricks = OverlayParrot;
  globalThis.PetFerretTricks = OverlayFerret;
  globalThis.PetHedgehogTricks = OverlayHedgehog;
  globalThis.PetChinchillaTricks = Overlay;
  globalThis.PetAxolotlTricks = OverlayAxolotl;
globalThis.PetToucanTricks = OverlayToucan;
  assert.equal(OverlayGround.tricksFor("red_panda"), OverlayRui);
  assert.equal(OverlayGround.tricksFor("rui"), OverlayRui);
  assert.equal(OverlayGround.tricksFor("relay_dragon"), OverlayRelay);
  assert.equal(OverlayGround.tricksFor("fuse_dragon"), OverlayFuse);
  assert.equal(OverlayGround.tricksFor("ground_dragon"), OverlayEarth);
  assert.equal(OverlayGround.tricksFor("ground"), OverlayEarth);
  assert.equal(OverlayGround.tricksFor("cat"), OverlayCat);
  assert.equal(OverlayGround.tricksFor("miso"), OverlayCat);
  assert.equal(OverlayGround.tricksFor("dog"), OverlayDog);
  assert.equal(OverlayGround.tricksFor("pip"), OverlayDog);
  assert.equal(OverlayGround.tricksFor("rabbit"), OverlayRabbit);
  assert.equal(OverlayGround.tricksFor("thimble"), OverlayRabbit);
  assert.equal(OverlayGround.tricksFor("hamster"), OverlayHamster);
  assert.equal(OverlayGround.tricksFor("clip"), OverlayHamster);
  assert.equal(OverlayGround.tricksFor("guinea_pig"), OverlayGuineaPig);
  assert.equal(OverlayGround.tricksFor("whee"), OverlayGuineaPig);
  assert.equal(OverlayGround.tricksFor("turtle"), OverlayTurtle);
  assert.equal(OverlayGround.tricksFor("ink"), OverlayTurtle);
  assert.equal(OverlayGround.tricksFor("goldfish"), OverlayGoldfish);
  assert.equal(OverlayGround.tricksFor("coin"), OverlayGoldfish);
  assert.equal(OverlayGround.tricksFor("budgie"), OverlayBudgie);
  assert.equal(OverlayGround.tricksFor("echo"), OverlayBudgie);
  assert.equal(OverlayGround.tricksFor("fox"), OverlayFox);
  assert.equal(OverlayGround.tricksFor("rue"), OverlayFox);
  assert.equal(OverlayGround.tricksFor("penguin"), OverlayPenguin);
  assert.equal(OverlayGround.tricksFor("peck"), OverlayPenguin);
  assert.equal(OverlayGround.tricksFor("parrot"), OverlayParrot);
  assert.equal(OverlayGround.tricksFor("quill"), OverlayParrot);
  assert.equal(OverlayGround.tricksFor("ferret"), OverlayFerret);
  assert.equal(OverlayGround.tricksFor("wick"), OverlayFerret);
  assert.equal(OverlayGround.tricksFor("hedgehog"), OverlayHedgehog);
  assert.equal(OverlayGround.tricksFor("burr"), OverlayHedgehog);
  assert.equal(OverlayGround.tricksFor("chinchilla"), Overlay);
  assert.equal(OverlayGround.tricksFor("floss"), Overlay);
  assert.equal(OverlayGround.tricksFor("axolotl"), OverlayAxolotl);
  assert.equal(OverlayGround.tricksFor("bloom"), OverlayAxolotl);
  assert.equal(OverlayGround.tricksFor("toucan"), OverlayToucan);
  assert.equal(OverlayGround.tricksFor("keel"), OverlayToucan);
  assert.equal(OverlayGround.tricksFor("iguana"), null);
  assert.equal(OverlayGround.wantsThankYou("red_panda"), true);
  assert.equal(OverlayGround.wantsThankYou("relay_dragon"), true);
  assert.equal(OverlayGround.wantsThankYou("fuse_dragon"), true);
  assert.equal(OverlayGround.wantsThankYou("ground_dragon"), true);
  assert.equal(OverlayGround.wantsThankYou("cat"), true);
  assert.equal(OverlayGround.wantsThankYou("miso"), true);
  assert.equal(OverlayGround.wantsThankYou("dog"), true);
  assert.equal(OverlayGround.wantsThankYou("pip"), true);
  assert.equal(OverlayGround.wantsThankYou("rabbit"), true);
  assert.equal(OverlayGround.wantsThankYou("thimble"), true);
  assert.equal(OverlayGround.wantsThankYou("hamster"), true);
  assert.equal(OverlayGround.wantsThankYou("clip"), true);
  assert.equal(OverlayGround.wantsThankYou("guinea_pig"), true);
  assert.equal(OverlayGround.wantsThankYou("whee"), true);
  assert.equal(OverlayGround.wantsThankYou("turtle"), true);
  assert.equal(OverlayGround.wantsThankYou("ink"), true);
  assert.equal(OverlayGround.wantsThankYou("goldfish"), true);
  assert.equal(OverlayGround.wantsThankYou("coin"), true);
  assert.equal(OverlayGround.wantsThankYou("budgie"), true);
  assert.equal(OverlayGround.wantsThankYou("echo"), true);
  assert.equal(OverlayGround.wantsThankYou("fox"), true);
  assert.equal(OverlayGround.wantsThankYou("rue"), true);
  assert.equal(OverlayGround.wantsThankYou("penguin"), true);
  assert.equal(OverlayGround.wantsThankYou("peck"), true);
  assert.equal(OverlayGround.wantsThankYou("parrot"), true);
  assert.equal(OverlayGround.wantsThankYou("quill"), true);
  assert.equal(OverlayGround.wantsThankYou("ferret"), true);
  assert.equal(OverlayGround.wantsThankYou("wick"), true);
  assert.equal(OverlayGround.wantsThankYou("hedgehog"), true);
  assert.equal(OverlayGround.wantsThankYou("burr"), true);
  assert.equal(OverlayGround.wantsThankYou("chinchilla"), true);
  assert.equal(OverlayGround.wantsThankYou("floss"), true);
  assert.equal(OverlayGround.wantsThankYou("axolotl"), true);
  assert.equal(OverlayGround.wantsThankYou("bloom"), true);
  assert.equal(OverlayGround.wantsThankYou("toucan"), true);
  assert.equal(OverlayGround.wantsThankYou("keel"), true);
  assert.equal(OverlayGround.wantsThankYou("iguana"), false);
  assert.equal(OverlayGround.sleepHoldFrame("red_panda", 4), 1);
  assert.equal(OverlayGround.sleepHoldFrame("dog", 4), null);
  assert.equal(OverlayGround.sleepHoldFrame("cat", 4), null);
  assert.equal(OverlayGround.sleepHoldFrame("rabbit", 4), null);
  assert.equal(OverlayGround.sleepHoldFrame("hamster", 4), null);
  assert.equal(OverlayGround.sleepHoldFrame("guinea_pig", 4), null);
  assert.equal(OverlayGround.sleepHoldFrame("turtle", 4), null);
  assert.equal(OverlayGround.sleepHoldFrame("goldfish", 4), null);
  assert.equal(OverlayGround.sleepHoldFrame("budgie", 4), null);
  assert.equal(OverlayGround.sleepHoldFrame("fox", 4), null);
  assert.equal(OverlayGround.sleepHoldFrame("penguin", 4), null);
  assert.equal(OverlayGround.sleepHoldFrame("parrot", 4), null);
  assert.equal(OverlayGround.sleepHoldFrame("ferret", 4), null);
  assert.equal(OverlayGround.sleepHoldFrame("hedgehog", 4), null);
  assert.equal(OverlayGround.sleepHoldFrame("chinchilla", 4), null);
  assert.equal(OverlayGround.sleepHoldFrame("axolotl", 4), null);
  assert.equal(OverlayGround.sleepHoldFrame("toucan", 4), null);
});

test("notes: Floss idle-life done; Bloom and Keel now have tricks; next lacking is Sol / iguana", () => {
  assert.equal(T.TRICK_KEY, "chinchilla");
  assert.equal(T.wantsThankYou("floss"), true);
  assert.equal(OverlayGround.tricksFor("axolotl"), OverlayAxolotl);
  assert.equal(OverlayGround.tricksFor("bloom"), OverlayAxolotl);
  assert.equal(OverlayGround.tricksFor("toucan"), OverlayToucan);
  assert.equal(OverlayGround.tricksFor("keel"), OverlayToucan);
  assert.equal(OverlayGround.tricksFor("iguana"), null);
  assert.equal(OverlayGround.wantsThankYou("axolotl"), true);
  assert.equal(OverlayGround.wantsThankYou("bloom"), true);
  assert.equal(OverlayGround.wantsThankYou("toucan"), true);
  assert.equal(OverlayGround.wantsThankYou("keel"), true);
  assert.equal(OverlayGround.wantsThankYou("iguana"), false);
});

