import assert from "node:assert/strict";
import { createRequire } from "node:module";
import { dirname, join } from "node:path";
import { test } from "node:test";
import { fileURLToPath, pathToFileURL } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const T = await import(pathToFileURL(join(root, "src/lib/pets/corn-snake-tricks.ts")).href);
const BallPython = await import(pathToFileURL(join(root, "src/lib/pets/ball-python-tricks.ts")).href);
const Phoenix = await import(pathToFileURL(join(root, "src/lib/pets/phoenix-tricks.ts")).href);
const Dragon = await import(pathToFileURL(join(root, "src/lib/pets/dragon-tricks.ts")).href);
const Rui = await import(pathToFileURL(join(root, "src/lib/pets/rui-tricks.ts")).href);
const Relay = await import(pathToFileURL(join(root, "src/lib/pets/relay-tricks.ts")).href);
const Fuse = await import(pathToFileURL(join(root, "src/lib/pets/fuse-tricks.ts")).href);
const Earth = await import(pathToFileURL(join(root, "src/lib/pets/earth-tricks.ts")).href);
const Cat = await import(pathToFileURL(join(root, "src/lib/pets/cat-tricks.ts")).href);
const Dog = await import(pathToFileURL(join(root, "src/lib/pets/dog-tricks.ts")).href);
const Rabbit = await import(pathToFileURL(join(root, "src/lib/pets/rabbit-tricks.ts")).href);
const Hamster = await import(pathToFileURL(join(root, "src/lib/pets/hamster-tricks.ts")).href);
const GuineaPig = await import(pathToFileURL(join(root, "src/lib/pets/guinea-pig-tricks.ts")).href);
const Turtle = await import(pathToFileURL(join(root, "src/lib/pets/turtle-tricks.ts")).href);
const Goldfish = await import(pathToFileURL(join(root, "src/lib/pets/goldfish-tricks.ts")).href);
const Budgie = await import(pathToFileURL(join(root, "src/lib/pets/budgie-tricks.ts")).href);
const Fox = await import(pathToFileURL(join(root, "src/lib/pets/fox-tricks.ts")).href);
const Penguin = await import(pathToFileURL(join(root, "src/lib/pets/penguin-tricks.ts")).href);
const Parrot = await import(pathToFileURL(join(root, "src/lib/pets/parrot-tricks.ts")).href);
const Ferret = await import(pathToFileURL(join(root, "src/lib/pets/ferret-tricks.ts")).href);
const Hedgehog = await import(pathToFileURL(join(root, "src/lib/pets/hedgehog-tricks.ts")).href);
const Chinchilla = await import(pathToFileURL(join(root, "src/lib/pets/chinchilla-tricks.ts")).href);
const Axolotl = await import(pathToFileURL(join(root, "src/lib/pets/axolotl-tricks.ts")).href);
const Toucan = await import(pathToFileURL(join(root, "src/lib/pets/toucan-tricks.ts")).href);
const Iguana = await import(pathToFileURL(join(root, "src/lib/pets/iguana-tricks.ts")).href);
const Overlay = createRequire(import.meta.url)(join(root, "../desktop/renderer/corn-snake-tricks.js"));
const OverlayBallPython = createRequire(import.meta.url)(join(root, "../desktop/renderer/ball-python-tricks.js"));
const OverlayPhoenix = createRequire(import.meta.url)(join(root, "../desktop/renderer/phoenix-tricks.js"));
const OverlayGround = createRequire(import.meta.url)(join(root, "../desktop/renderer/ground-tricks.js"));
const OverlayRui = createRequire(import.meta.url)(join(root, "../desktop/renderer/rui-tricks.js"));
const OverlayRelay = createRequire(import.meta.url)(join(root, "../desktop/renderer/relay-tricks.js"));
const OverlayFuse = createRequire(import.meta.url)(join(root, "../desktop/renderer/fuse-tricks.js"));
const OverlayEarth = createRequire(import.meta.url)(join(root, "../desktop/renderer/earth-tricks.js"));
const OverlayCat = createRequire(import.meta.url)(join(root, "../desktop/renderer/cat-tricks.js"));
const OverlayDog = createRequire(import.meta.url)(join(root, "../desktop/renderer/dog-tricks.js"));
const OverlayRabbit = createRequire(import.meta.url)(join(root, "../desktop/renderer/rabbit-tricks.js"));
const OverlayHamster = createRequire(import.meta.url)(join(root, "../desktop/renderer/hamster-tricks.js"));
const OverlayGuineaPig = createRequire(import.meta.url)(join(root, "../desktop/renderer/guinea-pig-tricks.js"));
const OverlayTurtle = createRequire(import.meta.url)(join(root, "../desktop/renderer/turtle-tricks.js"));
const OverlayGoldfish = createRequire(import.meta.url)(join(root, "../desktop/renderer/goldfish-tricks.js"));
const OverlayBudgie = createRequire(import.meta.url)(join(root, "../desktop/renderer/budgie-tricks.js"));
const OverlayFox = createRequire(import.meta.url)(join(root, "../desktop/renderer/fox-tricks.js"));
const OverlayPenguin = createRequire(import.meta.url)(join(root, "../desktop/renderer/penguin-tricks.js"));
const OverlayParrot = createRequire(import.meta.url)(join(root, "../desktop/renderer/parrot-tricks.js"));
const OverlayFerret = createRequire(import.meta.url)(join(root, "../desktop/renderer/ferret-tricks.js"));
const OverlayHedgehog = createRequire(import.meta.url)(join(root, "../desktop/renderer/hedgehog-tricks.js"));
const OverlayChinchilla = createRequire(import.meta.url)(join(root, "../desktop/renderer/chinchilla-tricks.js"));
const OverlayAxolotl = createRequire(import.meta.url)(join(root, "../desktop/renderer/axolotl-tricks.js"));
const OverlayToucan = createRequire(import.meta.url)(join(root, "../desktop/renderer/toucan-tricks.js"));
const OverlayIguana = createRequire(import.meta.url)(join(root, "../desktop/renderer/iguana-tricks.js"));
const OverlayDragon = createRequire(import.meta.url)(join(root, "../desktop/renderer/dragon-tricks.js"));


test("Saffron tricks start only on idle ground", () => {
  assert.deepEqual([...BallPython.TRICKS], ["orb", "nook", "taste", "inch", "unroll", "loom", "weave"]);
  assert.deepEqual([...Phoenix.TRICKS], ["cinder", "blaze", "shed", "lift", "return", "reignite", "hearth"]);
  assert.deepEqual([...T.TRICKS], ["scribble", "gap", "comma", "probe", "canyon", "blotter", "pencil"]);
  assert.equal(T.canStart({ asleep: false, hidden: false, leaving: false, cmd: "idle" }), true);
  assert.equal(T.canStart({ asleep: true, hidden: false, leaving: false, cmd: "idle" }), false);
  assert.equal(T.canStart({ asleep: false, hidden: true, leaving: false, cmd: "idle" }), false);
  assert.equal(T.canStart({ asleep: false, hidden: false, leaving: false, cmd: "sleep" }), false);
  assert.equal(T.canStart({ asleep: false, hidden: false, leaving: false, cmd: "seek" }), false);
  assert.equal(T.canStart({ asleep: false, hidden: false, leaving: false, cmd: "idle", windowPlay: true }), false);
  assert.equal(T.canStart({ asleep: false, hidden: false, leaving: false, cmd: "idle", card: true }), false);
  assert.equal(T.shouldAbort({ asleep: true, hidden: false, leaving: false, cmd: "idle" }), true);
  assert.equal(T.shouldAbort({ asleep: false, hidden: false, leaving: false, cmd: "idle", card: true }), true);
  assert.equal(T.shouldAbort({ asleep: false, hidden: false, leaving: false, cmd: "idle" }), false);
  assert.equal(T.pickTrick(0.99, true), "comma");
  assert.notEqual(T.pickTrick(0.3, false, "comma"), "orb");
  assert.equal(Overlay.TRICK_KEY, "corn_snake");
  assert.equal(T.sleepHoldFrame("corn_snake", 4), null);
  assert.equal(T.TRICKS.includes("write"), false);
  assert.equal(T.TRICKS.includes("bun"), false);
  assert.equal(T.TRICKS.includes("orb"), false);
  assert.equal(T.TRICKS.includes("nook"), false);
  assert.equal(T.TRICKS.includes("taste"), false);
  assert.equal(T.TRICKS.includes("inch"), false);
  assert.equal(T.TRICKS.includes("unroll"), false);
  assert.equal(T.TRICKS.includes("thread"), false);
  assert.equal(T.TRICKS.includes("dart"), false);
  assert.equal(T.TRICKS.includes("noodle"), false);
  assert.equal(T.TRICKS.includes("flick"), false);
  assert.equal(T.TRICKS.includes("curl"), false);
  assert.equal(T.TRICKS.includes("coil"), false);
  assert.equal(T.TRICKS.includes("ball"), false);
});

test("scribble/gap/comma/probe/canyon/blotter/pencil are house-corn-snake-true, not copies of prior guests", () => {
  const ground = { asleep: false, hidden: false, leaving: false, cmd: "idle" };
  const comma = T.beginTrick("comma", 80, 1);
  assert.equal(comma.anim, "sit");
  assert.equal(comma.phase, "hold");
  const held = T.stepTrick(comma, 5, ground);
  assert.equal(held.phase, "hold");
  assert.equal(held.anim, "sit");
  assert.ok(held.rot !== 0 || Math.abs(held.lift) > 0.5);
  const release = T.stepTrick(comma, T.COMMA_HOLD + 0.2, ground);
  assert.equal(release.phase, "release");
  assert.equal(release.anim, "sit");
  const doneComma = T.stepTrick(comma, T.DUR.comma + 0.1, ground);
  assert.equal(doneComma.phase, "done");
  assert.ok(T.nextTrickWait(true, 0, "comma") > T.nextTrickWait(true, 0, "gap"));
  const gap = T.beginTrick("gap", 80, 1);
  assert.equal(gap.anim, "sit");
  const gapMid = T.stepTrick(gap, 0.55, ground);
  assert.ok(Math.abs(gapMid.lift) > 0.1 || Math.abs(gapMid.rot) > 1);
  const probe = T.beginTrick("probe", 80, 1);
  assert.equal(probe.anim, "talk");
  const probeMid = T.stepTrick(probe, 0.5, ground);
  assert.ok(Math.abs(probeMid.lift) > 0.3 || Math.abs(probeMid.rot) > 1);
  const scribble = T.beginTrick("scribble", 80, 1);
  assert.equal(scribble.anim, "play");
  const scribbleMid = T.stepTrick(scribble, 0.5, ground);
  assert.ok(Math.abs(scribbleMid.lift) > 0.3 || Math.abs(scribbleMid.rot) > 1 || Math.abs(scribbleMid.x - 80) > 0.5);
  const canyon = T.beginTrick("canyon", 80, 1);
  assert.equal(canyon.anim, "play");
  const canyonMid = T.stepTrick(canyon, 0.4, ground);
  assert.ok(Math.abs(canyonMid.lift) > 0.2 || Math.abs(canyonMid.rot) > 1);
  const canyonDone = T.stepTrick(canyon, T.DUR.canyon + 0.1, ground);
  assert.equal(canyonDone.phase, "done");
  const blotter = T.beginTrick("blotter", 80, 1);
  assert.equal(blotter.anim, "talk");
  const blotterMid = T.stepTrick(blotter, T.DUR.blotter * 0.4, ground);
  assert.ok(blotterMid.lift > 4 || Math.abs(blotterMid.rot) > 6);
  const pencil = T.beginTrick("pencil", 80, 1);
  assert.equal(pencil.anim, "play");
  const pencilMid = T.stepTrick(pencil, T.DUR.pencil * 0.45, ground);
  assert.ok(Math.abs(pencilMid.lift) > 2 || Math.abs(pencilMid.rot) > 4 || Math.abs(pencilMid.x - 80) > 2);
  assert.equal(T.TRICKS.includes("write"), false);
  assert.equal(T.TRICKS.includes("orb"), false);
  assert.equal(T.TRICKS.includes("loom"), false);
  assert.equal(T.TRICKS.includes("weave"), false);
  assert.equal(T.TRICKS.includes("periscope"), false);
  const aborted = T.stepTrick(held, 0.1, { asleep: true, cmd: "sleep" });
  assert.equal(aborted.phase, "done");
  for (const mod of [Rui, Cat, Dog, Rabbit, Hamster, GuineaPig, Turtle, Goldfish, Budgie, Fox, Penguin, Parrot, Ferret, Hedgehog, Chinchilla, Axolotl, Toucan, Iguana, Dragon, Phoenix, BallPython, Relay, Fuse, Earth]) {
    assert.equal(mod.TRICKS.includes("scribble"), false);
    assert.equal(mod.TRICKS.includes("gap"), false);
    assert.equal(mod.TRICKS.includes("comma"), false);
    assert.equal(mod.TRICKS.includes("probe"), false);
    assert.equal(mod.TRICKS.includes("canyon"), false);
  }
  assert.deepEqual([...BallPython.TRICKS], ["orb", "nook", "taste", "inch", "unroll", "loom", "weave"]);
  assert.deepEqual([...Dragon.TRICKS], ["sprawl", "guard", "smolder", "claim", "fold", "ruff", "scrape"]);
  assert.deepEqual([...Phoenix.TRICKS], ["cinder", "blaze", "shed", "lift", "return", "reignite", "hearth"]);
  assert.equal(T.TRICKS.includes("write"), false);
  assert.equal(Parrot.TRICKS.includes("flash"), true);
});

test("Saffron feed-happy is its own sit: clause/spice/cord, and two feeds are not the same", () => {
  assert.deepEqual([...T.HAPPY], ["clause", "spice", "cord"]);
  assert.equal(T.HAPPY.includes("savor"), false);
  assert.equal(T.HAPPY.includes("nestle"), false);
  assert.equal(T.HAPPY.includes("center"), false);
  assert.equal(T.HAPPY.includes("settle"), false);
  assert.equal(T.HAPPY.includes("shine"), false);
  assert.equal(T.HAPPY.includes("purr"), false);
  assert.equal(T.pickHappy("clause", 0), "spice");
  assert.notEqual(T.pickHappy("clause", 0.9), "clause");
  assert.equal(Overlay.pickHappy("spice", 0) !== "spice", true);
  assert.equal(T.happyCanStart({ asleep: false, hidden: false, leaving: false, cmd: "idle" }), true);
  assert.equal(T.happyCanStart({ asleep: false, hidden: false, leaving: false, cmd: "idle", card: true }), true);
  assert.equal(T.happyCanStart({ asleep: true, hidden: false, leaving: false, cmd: "idle" }), false);
  assert.equal(T.happyShouldAbort({ cmd: "sleep" }), true);
  assert.equal(T.happyShouldAbort({ cmd: "hide" }), true);
  assert.equal(T.happyShouldAbort({ card: true, cmd: "idle" }), false);
  const clause = T.beginHappy("clause", 80, 1);
  assert.equal(clause.anim, "sit");
  const clauseMid = T.stepHappy(clause, 0.4, { cmd: "idle" });
  assert.ok(clauseMid.lift !== 0 || Math.abs(clauseMid.rot) > 0.5);
  assert.notEqual(clauseMid.phase, "done");
  const spice = T.beginHappy("spice", 80, 1);
  assert.equal(spice.anim, "talk");
  const spiceMid = T.stepHappy(spice, 0.3, { cmd: "idle" });
  assert.ok(spiceMid.lift > 0.2 || Math.abs(spiceMid.rot) > 0.5);
  const cordH = T.beginHappy("cord", 80, 1);
  assert.equal(cordH.anim, "sit");
  const done = T.stepHappy(clause, T.HAPPY_DUR.clause + 0.1, { cmd: "idle" });
  assert.equal(done.phase, "done");
  const aborted = T.stepHappy(spiceMid, 0.1, { asleep: true, cmd: "sleep" });
  assert.equal(aborted.phase, "done");
  assert.equal(aborted.abort, true);
  assert.equal(T.wantsThankYou("corn_snake"), true);
  assert.equal(T.wantsThankYou("saffron"), true);
  assert.equal(T.wantsThankYou("ball_python"), false);
  assert.equal(T.wantsThankYou("nori"), false);
  assert.equal(T.wantsThankYou("phoenix"), false);
  const thanks = T.startThankYou("corn_snake", "clause", 80, 1, { cmd: "idle", card: true, windowPlay: true });
  assert.ok(thanks);
  assert.notEqual(thanks.kind, "clause");
  assert.ok(thanks.happy.lift === 0);
  assert.notEqual(thanks.happy.anim, "eat");
  assert.notEqual(thanks.happy.anim, "idle");
  const thanksMid = T.stepHappy(thanks.happy, 0.35, { cmd: "idle", card: true });
  assert.ok(thanksMid.lift !== 0 || Math.abs(thanksMid.rot) > 0.5, "a thank-you clauses or spices");
  const blocked = T.startThankYou("corn_snake", "spice", 80, 1, { asleep: true, cmd: "idle" });
  assert.equal(blocked, null);
  const other = T.startThankYou("ball_python", null, 80, 1, { cmd: "idle" });
  assert.equal(other, null);
  const second = T.startThankYou("corn_snake", thanks.kind, 80, 1, { cmd: "idle", card: true });
  assert.ok(second);
  assert.notEqual(second.kind, thanks.kind);
});

test("ground registry keeps prior guests gated; Saffron selectable; prior guests still OK", () => {
  assert.equal(Rui.TRICK_KEY, "red_panda");
  assert.equal(BallPython.TRICK_KEY, "ball_python");
  assert.equal(T.TRICK_KEY, "corn_snake");
  assert.deepEqual([...Rui.TRICKS], ["somersault", "lie", "scratch", "wave", "dance"]);
  assert.deepEqual([...BallPython.TRICKS], ["orb", "nook", "taste", "inch", "unroll", "loom", "weave"]);
  assert.deepEqual([...Phoenix.TRICKS], ["cinder", "blaze", "shed", "lift", "return", "reignite", "hearth"]);
  assert.deepEqual([...T.TRICKS], ["scribble", "gap", "comma", "probe", "canyon", "blotter", "pencil"]);
  assert.equal(T.wantsThankYou("corn_snake"), true);
  assert.equal(T.wantsThankYou("saffron"), true);
  assert.equal(BallPython.wantsThankYou("nori"), true);
  assert.equal(Rui.sleepHoldFrame("red_panda", 4), 1);
  assert.equal(T.sleepHoldFrame("corn_snake", 4), null);
  globalThis.PetRuiTricks = OverlayRui;
  globalThis.PetRelayTricks = OverlayRelay;
  globalThis.PetFuseTricks = OverlayFuse;
  globalThis.PetEarthTricks = OverlayEarth;
  globalThis.PetCatTricks = OverlayCat;
  globalThis.PetDogTricks = OverlayDog;
  globalThis.PetRabbitTricks = OverlayRabbit;
  globalThis.PetHamsterTricks = OverlayHamster;
  globalThis.PetGuineaPigTricks = OverlayGuineaPig;
  globalThis.PetTurtleTricks = OverlayTurtle;
  globalThis.PetGoldfishTricks = OverlayGoldfish;
  globalThis.PetBudgieTricks = OverlayBudgie;
  globalThis.PetFoxTricks = OverlayFox;
  globalThis.PetPenguinTricks = OverlayPenguin;
  globalThis.PetParrotTricks = OverlayParrot;
  globalThis.PetFerretTricks = OverlayFerret;
  globalThis.PetHedgehogTricks = OverlayHedgehog;
  globalThis.PetChinchillaTricks = OverlayChinchilla;
  globalThis.PetAxolotlTricks = OverlayAxolotl;
  globalThis.PetToucanTricks = OverlayToucan;
  globalThis.PetIguanaTricks = OverlayIguana;
  globalThis.PetDragonTricks = OverlayDragon;
  globalThis.PetPhoenixTricks = OverlayPhoenix;
  globalThis.PetBallPythonTricks = OverlayBallPython;
  globalThis.PetCornSnakeTricks = Overlay;
  assert.equal(OverlayGround.tricksFor("red_panda"), OverlayRui);
  assert.equal(OverlayGround.tricksFor("rui"), OverlayRui);
  assert.equal(OverlayGround.tricksFor("relay_dragon"), OverlayRelay);
  assert.equal(OverlayGround.tricksFor("fuse_dragon"), OverlayFuse);
  assert.equal(OverlayGround.tricksFor("ground_dragon"), OverlayEarth);
  assert.equal(OverlayGround.tricksFor("cat"), OverlayCat);
  assert.equal(OverlayGround.tricksFor("miso"), OverlayCat);
  assert.equal(OverlayGround.tricksFor("dog"), OverlayDog);
  assert.equal(OverlayGround.tricksFor("pip"), OverlayDog);
  assert.equal(OverlayGround.tricksFor("rabbit"), OverlayRabbit);
  assert.equal(OverlayGround.tricksFor("thimble"), OverlayRabbit);
  assert.equal(OverlayGround.tricksFor("hamster"), OverlayHamster);
  assert.equal(OverlayGround.tricksFor("clip"), OverlayHamster);
  assert.equal(OverlayGround.tricksFor("guinea_pig"), OverlayGuineaPig);
  assert.equal(OverlayGround.tricksFor("whee"), OverlayGuineaPig);
  assert.equal(OverlayGround.tricksFor("turtle"), OverlayTurtle);
  assert.equal(OverlayGround.tricksFor("ink"), OverlayTurtle);
  assert.equal(OverlayGround.tricksFor("goldfish"), OverlayGoldfish);
  assert.equal(OverlayGround.tricksFor("coin"), OverlayGoldfish);
  assert.equal(OverlayGround.tricksFor("budgie"), OverlayBudgie);
  assert.equal(OverlayGround.tricksFor("echo"), OverlayBudgie);
  assert.equal(OverlayGround.tricksFor("fox"), OverlayFox);
  assert.equal(OverlayGround.tricksFor("rue"), OverlayFox);
  assert.equal(OverlayGround.tricksFor("penguin"), OverlayPenguin);
  assert.equal(OverlayGround.tricksFor("peck"), OverlayPenguin);
  assert.equal(OverlayGround.tricksFor("parrot"), OverlayParrot);
  assert.equal(OverlayGround.tricksFor("quill"), OverlayParrot);
  assert.equal(OverlayGround.tricksFor("ferret"), OverlayFerret);
  assert.equal(OverlayGround.tricksFor("wick"), OverlayFerret);
  assert.equal(OverlayGround.tricksFor("hedgehog"), OverlayHedgehog);
  assert.equal(OverlayGround.tricksFor("burr"), OverlayHedgehog);
  assert.equal(OverlayGround.tricksFor("chinchilla"), OverlayChinchilla);
  assert.equal(OverlayGround.tricksFor("floss"), OverlayChinchilla);
  assert.equal(OverlayGround.tricksFor("axolotl"), OverlayAxolotl);
  assert.equal(OverlayGround.tricksFor("bloom"), OverlayAxolotl);
  assert.equal(OverlayGround.tricksFor("toucan"), OverlayToucan);
  assert.equal(OverlayGround.tricksFor("keel"), OverlayToucan);
  assert.equal(OverlayGround.tricksFor("iguana"), OverlayIguana);
  assert.equal(OverlayGround.tricksFor("sol"), OverlayIguana);
  assert.equal(OverlayGround.tricksFor("dragon"), OverlayDragon);
  assert.equal(OverlayGround.tricksFor("vesper"), OverlayDragon);
  assert.equal(OverlayGround.tricksFor("phoenix"), OverlayPhoenix);
  assert.equal(OverlayGround.tricksFor("ember"), OverlayPhoenix);
  assert.equal(OverlayGround.tricksFor("ball_python"), OverlayBallPython);
  assert.equal(OverlayGround.tricksFor("nori"), OverlayBallPython);
  assert.equal(OverlayGround.tricksFor("corn_snake"), Overlay);
  assert.equal(OverlayGround.tricksFor("saffron"), Overlay);
  assert.equal(OverlayGround.wantsThankYou("red_panda"), true);
  assert.equal(OverlayGround.wantsThankYou("cat"), true);
  assert.equal(OverlayGround.wantsThankYou("miso"), true);
  assert.equal(OverlayGround.wantsThankYou("dog"), true);
  assert.equal(OverlayGround.wantsThankYou("pip"), true);
  assert.equal(OverlayGround.wantsThankYou("ball_python"), true);
  assert.equal(OverlayGround.wantsThankYou("nori"), true);
  assert.equal(OverlayGround.wantsThankYou("corn_snake"), true);
  assert.equal(OverlayGround.wantsThankYou("saffron"), true);
  assert.equal(OverlayGround.wantsThankYou("phoenix"), true);
  assert.equal(OverlayGround.wantsThankYou("ember"), true);
  assert.equal(OverlayGround.sleepHoldFrame("red_panda", 4), 1);
  assert.equal(OverlayGround.sleepHoldFrame("ball_python", 4), null);
  assert.equal(OverlayGround.sleepHoldFrame("corn_snake", 4), null);
  assert.deepEqual([...OverlayBallPython.TRICKS], ["orb", "nook", "taste", "inch", "unroll", "loom", "weave"]);
  assert.deepEqual([...Overlay.TRICKS], ["scribble", "gap", "comma", "probe", "canyon", "blotter", "pencil"]);
  assert.equal(Overlay.TRICKS.includes("orb"), false);
  assert.equal(Overlay.TRICKS.includes("write"), false);
});


test("ultra-polish: Saffron scribble/gap/comma/blotter/pencil lifts are Rui-visible (not micro idle-gen)", () => {
  const cm = T.beginTrick("comma", 80, 1);
  const mid = T.stepTrick(cm, 5, { cmd: "idle" });
  assert.ok(Math.abs(mid.rot) > 10, `comma mid rot ${mid.rot}`);
  assert.ok(Math.abs(mid.lift) > 0.5, `comma mid lift ${mid.lift}`);
  const gp = T.beginTrick("gap", 80, 1);
  const g2 = T.stepTrick(gp, T.DUR.gap * 0.4, { cmd: "idle" });
  assert.ok(g2.lift > 4 || Math.abs(g2.rot) > 4, `gap mid lift/rot ${g2.lift}/${g2.rot}`);
  const bl = T.beginTrick("blotter", 80, 1);
  const b2 = T.stepTrick(bl, T.DUR.blotter * 0.4, { cmd: "idle" });
  assert.ok(b2.lift > 4 || Math.abs(b2.rot) > 6, `blotter mid lift/rot ${b2.lift}/${b2.rot}`);
  const pn = T.beginTrick("pencil", 80, 1);
  const p2 = T.stepTrick(pn, T.DUR.pencil * 0.45, { cmd: "idle" });
  assert.ok(Math.abs(p2.lift) > 2 || Math.abs(p2.rot) > 4 || Math.abs(p2.x - 80) > 2, `pencil mid ${p2.lift}/${p2.rot}/${p2.x}`);
  assert.ok(Overlay.blotterPose && Overlay.pencilPose);
  assert.deepEqual([...T.TRICKS], [...Overlay.TRICKS]);
  assert.equal(T.DUR.blotter, Overlay.DUR.blotter);
  assert.equal(T.DUR.pencil, Overlay.DUR.pencil);
  assert.equal(T.COMMA_HOLD, Overlay.COMMA_HOLD);
  assert.equal(T.COMMA_HOLD, 11.2);
  assert.equal(T.RELEASE_S, 1.18);
  assert.ok(T.nextTrickWait(true, 0, "comma") > 39);
  assert.ok(T.nextTrickWait(true, 0, "comma") < 80);
  assert.ok(T.nextTrickWait(true, 0, "comma") > T.nextTrickWait(true, 0, "gap"));
  assert.equal(T.HAPPY_DUR.clause, Overlay.HAPPY_DUR.clause);
});

test("notes: Saffron Rui-dense ultra (COMMA_HOLD=11.2); Bandit densified; Jade densified; Bluff densified; Sash densified; Lula densified; next leftover Coral / milk_snake", () => {
  assert.deepEqual([...T.TRICKS], ["scribble", "gap", "comma", "probe", "canyon", "blotter", "pencil"]);
  assert.equal(T.TRICK_KEY, "corn_snake");
  assert.equal(T.wantsThankYou("saffron"), true);
  assert.equal(OverlayGround.tricksFor("corn_snake"), Overlay);
  assert.equal(OverlayGround.tricksFor("saffron"), Overlay);
  assert.equal(OverlayGround.wantsThankYou("corn_snake"), true);
  assert.equal(OverlayGround.wantsThankYou("saffron"), true);
  assert.equal(OverlayGround.tricksFor("ball_python"), OverlayBallPython);
  assert.equal(OverlayGround.tricksFor("nori"), OverlayBallPython);
  assert.equal(OverlayGround.wantsThankYou("ball_python"), true);
  assert.equal(OverlayGround.wantsThankYou("nori"), true);
  assert.equal(OverlayGround.tricksFor("kingsnake") == null, true);
  assert.equal(OverlayGround.wantsThankYou("kingsnake"), false);
  assert.equal(OverlayGround.tricksFor("bandit") == null, true);
});
