import assert from "node:assert/strict";
import { createRequire } from "node:module";
import { dirname, join } from "node:path";
import { test } from "node:test";
import { fileURLToPath, pathToFileURL } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const T = await import(pathToFileURL(join(root, "src/lib/pets/dog-tricks.ts")).href);
const Rui = await import(pathToFileURL(join(root, "src/lib/pets/rui-tricks.ts")).href);
const Relay = await import(pathToFileURL(join(root, "src/lib/pets/relay-tricks.ts")).href);
const Fuse = await import(pathToFileURL(join(root, "src/lib/pets/fuse-tricks.ts")).href);
const Earth = await import(pathToFileURL(join(root, "src/lib/pets/earth-tricks.ts")).href);
const Cat = await import(pathToFileURL(join(root, "src/lib/pets/cat-tricks.ts")).href);
const Overlay = createRequire(import.meta.url)(join(root, "../desktop/renderer/dog-tricks.js"));
const OverlayGround = createRequire(import.meta.url)(join(root, "../desktop/renderer/ground-tricks.js"));
const OverlayRui = createRequire(import.meta.url)(join(root, "../desktop/renderer/rui-tricks.js"));
const OverlayRelay = createRequire(import.meta.url)(join(root, "../desktop/renderer/relay-tricks.js"));
const OverlayFuse = createRequire(import.meta.url)(join(root, "../desktop/renderer/fuse-tricks.js"));
const OverlayEarth = createRequire(import.meta.url)(join(root, "../desktop/renderer/earth-tricks.js"));
const OverlayCat = createRequire(import.meta.url)(join(root, "../desktop/renderer/cat-tricks.js"));
const OverlayRabbit = createRequire(import.meta.url)(join(root, "../desktop/renderer/rabbit-tricks.js"));
const OverlayHamster = createRequire(import.meta.url)(join(root, "../desktop/renderer/hamster-tricks.js"));
const OverlayGuineaPig = createRequire(import.meta.url)(join(root, "../desktop/renderer/guinea-pig-tricks.js"));

test("Pip tricks start only on idle ground", () => {
  assert.deepEqual([...T.TRICKS], ["wait", "wag", "sniff", "bow", "zoom", "beg", "pant"]);
  assert.equal(T.canStart({ asleep: false, hidden: false, leaving: false, cmd: "idle" }), true);
  assert.equal(T.canStart({ asleep: true, hidden: false, leaving: false, cmd: "idle" }), false);
  assert.equal(T.canStart({ asleep: false, hidden: true, leaving: false, cmd: "idle" }), false);
  assert.equal(T.canStart({ asleep: false, hidden: false, leaving: false, cmd: "sleep" }), false);
  assert.equal(T.canStart({ asleep: false, hidden: false, leaving: false, cmd: "seek" }), false);
  assert.equal(T.canStart({ asleep: false, hidden: false, leaving: false, cmd: "idle", windowPlay: true }), false);
  assert.equal(T.canStart({ asleep: false, hidden: false, leaving: false, cmd: "idle", card: true }), false);
  assert.equal(T.shouldAbort({ asleep: true, hidden: false, leaving: false, cmd: "idle" }), true);
  assert.equal(T.shouldAbort({ asleep: false, hidden: false, leaving: false, cmd: "idle", card: true }), true);
  assert.equal(T.shouldAbort({ asleep: false, hidden: false, leaving: false, cmd: "idle" }), false);
  assert.equal(T.pickTrick(0.99, true), "wait");
  assert.notEqual(T.pickTrick(0.3, false, "wait"), "wait");
  assert.equal(Overlay.TRICK_KEY, "dog");
  assert.equal(T.sleepHoldFrame("dog", 4), null);
  assert.equal(T.TRICKS.includes("somersault"), false);
  assert.equal(T.TRICKS.includes("scratch"), false);
  assert.equal(T.TRICKS.includes("loaf"), false);
  assert.equal(T.TRICKS.includes("pounce"), false);
  assert.equal(T.TRICKS.includes("lug"), false);
  assert.equal(T.TRICKS.includes("seat"), false);
  assert.equal(T.TRICKS.includes("click"), false);
});

test("wait/wag/sniff/bow/zoom/beg/pant are house-dog-true, not Rui cat or dragon clones", () => {
  const ground = { asleep: false, hidden: false, leaving: false, cmd: "idle" };
  const wait = T.beginTrick("wait", 80, 1);
  assert.equal(wait.anim, "sit");
  assert.equal(wait.phase, "hold");
  const held = T.stepTrick(wait, 5, ground);
  assert.equal(held.phase, "hold");
  assert.equal(held.anim, "sit");
  assert.ok(Math.abs(held.rot) > 6);
  assert.ok(held.lift < 0);
  const release = T.stepTrick(wait, T.WAIT_HOLD + 0.2, ground);
  assert.equal(release.phase, "release");
  assert.equal(release.anim, "sit");
  const doneWait = T.stepTrick(wait, T.DUR.wait + 0.1, ground);
  assert.equal(doneWait.phase, "done");
  assert.ok(T.nextTrickWait(true, 0, "wait") > T.nextTrickWait(true, 0, "wag"));
  const wag = T.beginTrick("wag", 80, 1);
  assert.equal(wag.anim, "sit");
  const wagMid = T.stepTrick(wag, 0.25, ground);
  assert.ok(Math.abs(wagMid.rot) > 0.5 || wagMid.lift !== -1.5);
  const sniff = T.beginTrick("sniff", 80, 1);
  assert.equal(sniff.anim, "sit");
  const sniffMid = T.stepTrick(sniff, 0.5, ground);
  assert.ok(sniffMid.lift < -1 || sniffMid.rot > 1);
  const bow = T.beginTrick("bow", 80, 1);
  assert.equal(bow.anim, "sit");
  const bowMid = T.stepTrick(bow, 0.4, ground);
  assert.ok(bowMid.rot < -2 || bowMid.lift < 0);
  const zoom = T.beginTrick("zoom", 80, 1);
  assert.equal(zoom.anim, "play");
  const zoomMid = T.stepTrick(zoom, T.DUR.zoom * 0.45, ground);
  assert.ok(zoomMid.lift > 2);
  assert.ok(Math.abs(zoomMid.x - 80) > 2);
  const zoomDone = T.stepTrick(zoom, T.DUR.zoom + 0.1, ground);
  assert.equal(zoomDone.phase, "done");
  const beg = T.beginTrick("beg", 80, 1);
  assert.equal(beg.anim, "sit");
  const begMid = T.stepTrick(beg, T.DUR.beg * 0.4, ground);
  assert.ok(begMid.lift > 4 || Math.abs(begMid.rot) > 6);
  const pant = T.beginTrick("pant", 80, 1);
  assert.equal(pant.anim, "sit");
  const pantMid = T.stepTrick(pant, T.DUR.pant * 0.4, ground);
  assert.ok(pantMid.lift > 2 || Math.abs(pantMid.rot) > 4);
  assert.equal(Overlay.TRICKS.includes("beg"), true);
  assert.equal(Overlay.TRICKS.includes("pant"), true);
  const aborted = T.stepTrick(held, 0.1, { asleep: true, cmd: "sleep" });
  assert.equal(aborted.phase, "done");
  assert.equal(Rui.TRICKS.includes("wait"), false);
  assert.equal(Cat.TRICKS.includes("wag"), false);
  assert.equal(Relay.TRICKS.includes("sniff"), false);
  assert.equal(Fuse.TRICKS.includes("bow"), false);
  assert.equal(Earth.TRICKS.includes("zoom"), false);
  assert.equal(Rui.TRICKS.includes("zoom"), false);
  assert.equal(Cat.TRICKS.includes("zoom"), false);
  assert.equal(Cat.TRICKS.includes("beg"), false);
  assert.equal(Cat.TRICKS.includes("pant"), false);
});

test("Pip feed-happy is its own sit: tail/tilt/woof, and two feeds are not the same", () => {
  assert.deepEqual([...T.HAPPY], ["tail", "tilt", "woof"]);
  assert.equal(T.HAPPY.includes("spark"), false);
  assert.equal(T.HAPPY.includes("purr"), false);
  assert.equal(T.HAPPY.includes("twirl"), false);
  assert.equal(T.pickHappy("tail", 0), "tilt");
  assert.notEqual(T.pickHappy("tail", 0.9), "tail");
  assert.equal(Overlay.pickHappy("tilt", 0) !== "tilt", true);
  assert.equal(T.happyCanStart({ asleep: false, hidden: false, leaving: false, cmd: "idle" }), true);
  assert.equal(T.happyCanStart({ asleep: false, hidden: false, leaving: false, cmd: "idle", card: true }), true);
  assert.equal(T.happyCanStart({ asleep: true, hidden: false, leaving: false, cmd: "idle" }), false);
  assert.equal(T.happyShouldAbort({ cmd: "sleep" }), true);
  assert.equal(T.happyShouldAbort({ cmd: "hide" }), true);
  assert.equal(T.happyShouldAbort({ card: true, cmd: "idle" }), false);
  const tail = T.beginHappy("tail", 80, 1);
  assert.equal(tail.anim, "talk");
  const tailMid = T.stepHappy(tail, 0.4, { cmd: "idle" });
  assert.ok(tailMid.lift > 0.3 || Math.abs(tailMid.rot) > 0.5);
  assert.notEqual(tailMid.phase, "done");
  const tilt = T.beginHappy("tilt", 80, 1);
  assert.equal(tilt.anim, "sit");
  const tiltMid = T.stepHappy(tilt, 0.3, { cmd: "idle" });
  assert.ok(tiltMid.rot > 2 || tiltMid.lift < 0);
  const woof = T.beginHappy("woof", 80, 1);
  assert.equal(woof.anim, "play");
  const done = T.stepHappy(tail, T.HAPPY_DUR.tail + 0.1, { cmd: "idle" });
  assert.equal(done.phase, "done");
  const aborted = T.stepHappy(tailMid, 0.1, { asleep: true, cmd: "sleep" });
  assert.equal(aborted.phase, "done");
  assert.equal(aborted.abort, true);
  assert.equal(T.wantsThankYou("dog"), true);
  assert.equal(T.wantsThankYou("pip"), true);
  assert.equal(T.wantsThankYou("cat"), false);
  assert.equal(T.wantsThankYou("red_panda"), false);
  assert.equal(T.wantsThankYou("ground_dragon"), false);
  const thanks = T.startThankYou("dog", "tail", 80, 1, { cmd: "idle", card: true, windowPlay: true });
  assert.ok(thanks);
  assert.notEqual(thanks.kind, "tail");
  assert.ok(thanks.happy.lift === 0);
  assert.notEqual(thanks.happy.anim, "eat");
  assert.notEqual(thanks.happy.anim, "idle");
  const thanksMid = T.stepHappy(thanks.happy, 0.35, { cmd: "idle", card: true });
  assert.ok(thanksMid.lift !== 0 || Math.abs(thanksMid.rot) > 0.5, "a thank-you wags or tilts");
  const blocked = T.startThankYou("dog", "tilt", 80, 1, { asleep: true, cmd: "idle" });
  assert.equal(blocked, null);
  const other = T.startThankYou("rabbit", null, 80, 1, { cmd: "idle" });
  assert.equal(other, null);
  const second = T.startThankYou("dog", thanks.kind, 80, 1, { cmd: "idle", card: true });
  assert.ok(second);
  assert.notEqual(second.kind, thanks.kind);
});

test("ground registry keeps prior guests gated; Pip selectable; no scratch-name collision", () => {
  assert.equal(Rui.TRICK_KEY, "red_panda");
  assert.equal(Relay.TRICK_KEY, "relay_dragon");
  assert.equal(Fuse.TRICK_KEY, "fuse_dragon");
  assert.equal(Earth.TRICK_KEY, "ground_dragon");
  assert.equal(Cat.TRICK_KEY, "cat");
  assert.equal(T.TRICK_KEY, "dog");
  assert.deepEqual([...Rui.TRICKS], ["somersault", "lie", "scratch", "wave", "dance"]);
  assert.deepEqual([...Relay.TRICKS], ["contactclick", "latchseat", "arcflick", "coilbuzz", "poleswitch", "armaturetap", "relayhush"]);
  assert.deepEqual([...Fuse.TRICKS], ["railseat", "holdcurrent", "blowclear", "reseatsnap", "cartridgerattle", "bladeflash", "fusehush"]);
  assert.deepEqual([...Earth.TRICKS], ["lugstrap", "earthseat", "heaveplate", "bedsettle", "soilgrip", "plateclamp", "groundhush"]);
  assert.deepEqual([...Cat.TRICKS], ["loaf", "knead", "stretch", "wash", "pounce", "bunting", "mlem"]);
  assert.equal(T.TRICKS.includes("scratch"), false);
  assert.equal(Rui.wantsThankYou("dog"), false);
  assert.equal(Relay.wantsThankYou("dog"), false);
  assert.equal(Fuse.wantsThankYou("dog"), false);
  assert.equal(Earth.wantsThankYou("dog"), false);
  assert.equal(Cat.wantsThankYou("dog"), false);
  assert.equal(T.wantsThankYou("dog"), true);
  assert.equal(T.wantsThankYou("pip"), true);
  assert.equal(T.wantsThankYou("cat"), false);
  assert.equal(Rui.sleepHoldFrame("red_panda", 4), 1);
  assert.equal(T.sleepHoldFrame("dog", 4), null);
  globalThis.PetRuiTricks = OverlayRui;
  globalThis.PetRelayTricks = OverlayRelay;
  globalThis.PetFuseTricks = OverlayFuse;
  globalThis.PetEarthTricks = OverlayEarth;
  globalThis.PetCatTricks = OverlayCat;
  globalThis.PetDogTricks = Overlay;
  globalThis.PetRabbitTricks = OverlayRabbit;
  globalThis.PetHamsterTricks = OverlayHamster;
  globalThis.PetGuineaPigTricks = OverlayGuineaPig;
  assert.equal(OverlayGround.tricksFor("red_panda"), OverlayRui);
  assert.equal(OverlayGround.tricksFor("rui"), OverlayRui);
  assert.equal(OverlayGround.tricksFor("relay_dragon"), OverlayRelay);
  assert.equal(OverlayGround.tricksFor("fuse_dragon"), OverlayFuse);
  assert.equal(OverlayGround.tricksFor("ground_dragon"), OverlayEarth);
  assert.equal(OverlayGround.tricksFor("ground"), OverlayEarth);
  assert.equal(OverlayGround.tricksFor("cat"), OverlayCat);
  assert.equal(OverlayGround.tricksFor("miso"), OverlayCat);
  assert.equal(OverlayGround.tricksFor("dog"), Overlay);
  assert.equal(OverlayGround.tricksFor("pip"), Overlay);
  assert.equal(OverlayGround.tricksFor("rabbit"), OverlayRabbit);
  assert.equal(OverlayGround.tricksFor("thimble"), OverlayRabbit);
  assert.equal(OverlayGround.tricksFor("hamster"), OverlayHamster);
  assert.equal(OverlayGround.tricksFor("clip"), OverlayHamster);
  assert.equal(OverlayGround.tricksFor("guinea_pig"), OverlayGuineaPig);
  assert.equal(OverlayGround.tricksFor("whee"), OverlayGuineaPig);
  assert.equal(OverlayGround.tricksFor("turtle") == null, true);
  assert.equal(OverlayGround.wantsThankYou("red_panda"), true);
  assert.equal(OverlayGround.wantsThankYou("relay_dragon"), true);
  assert.equal(OverlayGround.wantsThankYou("fuse_dragon"), true);
  assert.equal(OverlayGround.wantsThankYou("ground_dragon"), true);
  assert.equal(OverlayGround.wantsThankYou("cat"), true);
  assert.equal(OverlayGround.wantsThankYou("miso"), true);
  assert.equal(OverlayGround.wantsThankYou("dog"), true);
  assert.equal(OverlayGround.wantsThankYou("pip"), true);
  assert.equal(OverlayGround.wantsThankYou("rabbit"), true);
  assert.equal(OverlayGround.wantsThankYou("thimble"), true);
  assert.equal(OverlayGround.wantsThankYou("hamster"), true);
  assert.equal(OverlayGround.wantsThankYou("clip"), true);
  assert.equal(OverlayGround.wantsThankYou("guinea_pig"), true);
  assert.equal(OverlayGround.wantsThankYou("whee"), true);
  assert.equal(OverlayGround.wantsThankYou("turtle"), false);
  assert.equal(OverlayGround.sleepHoldFrame("red_panda", 4), 1);
  assert.equal(OverlayGround.sleepHoldFrame("dog", 4), null);
  assert.equal(OverlayGround.sleepHoldFrame("hamster", 4), null);
});

test("ultra-polish: Pip wait/wag/bow/beg/pant lifts are Rui-visible (not micro idle-gen)", () => {
  const ex = T.beginTrick("wait", 80, 1);
  const mid = T.stepTrick(ex, 5, { cmd: "idle" });
  assert.ok(Math.abs(mid.rot) > 6, `wait mid rot ${mid.rot}`);
  assert.ok(Math.abs(mid.lift) > 2, `wait mid lift ${mid.lift}`);
  const wg = T.beginTrick("wag", 80, 1);
  const w2 = T.stepTrick(wg, T.DUR.wag * 0.4, { cmd: "idle" });
  assert.ok(Math.abs(w2.rot) > 6, `wag mid rot ${w2.rot}`);
  assert.ok(Math.abs(w2.lift) > 2 || w2.lift > 2, `wag mid lift ${w2.lift}`);
  const bw = T.beginTrick("bow", 80, 1);
  const b2 = T.stepTrick(bw, T.DUR.bow * 0.4, { cmd: "idle" });
  assert.ok(Math.abs(b2.rot) > 6, `bow mid rot ${b2.rot}`);
  const bg = T.beginTrick("beg", 80, 1);
  const g2 = T.stepTrick(bg, T.DUR.beg * 0.4, { cmd: "idle" });
  assert.ok(g2.lift > 4, `beg mid lift ${g2.lift}`);
  const pt = T.beginTrick("pant", 80, 1);
  const p2 = T.stepTrick(pt, T.DUR.pant * 0.4, { cmd: "idle" });
  assert.ok(p2.lift > 3 || Math.abs(p2.rot) > 6, `pant mid lift/rot ${p2.lift}/${p2.rot}`);
  assert.ok(Overlay.begPose && Overlay.pantPose);
  assert.ok(T.nextTrickWait(true, 0, "wait") < 80);
  assert.ok(T.nextTrickWait(true, 0, "wait") > T.nextTrickWait(true, 0, "wag"));
});

test("notes: Pip idle-life ultra done; Thimble / rabbit ultra next-or-done; following house-order ultra guest is Clip / hamster (birds Soot→Ember + Miso already ultra)", () => {
  assert.deepEqual([...T.TRICKS], ["wait", "wag", "sniff", "bow", "zoom", "beg", "pant"]);
  assert.equal(T.TRICKS.includes("scratch"), false);
  assert.equal(T.TRICKS.includes("loaf"), false);
  assert.equal(T.TRICKS.includes("flop"), false);
  assert.equal(T.TRICKS.includes("bunting"), false);
  assert.equal(T.TRICKS.includes("somersault"), false);
  assert.equal(T.TRICKS.includes("lug"), false);
  assert.equal(T.TRICKS.includes("howl"), false);
  assert.equal(T.TRICKS.includes("mlem"), false);
});
