import assert from "node:assert/strict";
import { createRequire } from "node:module";
import { dirname, join } from "node:path";
import { test } from "node:test";
import { fileURLToPath, pathToFileURL } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const T = await import(pathToFileURL(join(root, "src/lib/pets/earth-tricks.ts")).href);
const Rui = await import(pathToFileURL(join(root, "src/lib/pets/rui-tricks.ts")).href);
const GaussDragon = await import(pathToFileURL(join(root, "src/lib/pets/gauss_dragon-tricks.ts")).href);
const SparkDragon = await import(pathToFileURL(join(root, "src/lib/pets/spark_dragon-tricks.ts")).href);
const CyberDragon = await import(pathToFileURL(join(root, "src/lib/pets/cyber_dragon-tricks.ts")).href);
const Relay = await import(pathToFileURL(join(root, "src/lib/pets/relay-tricks.ts")).href);
const Fuse = await import(pathToFileURL(join(root, "src/lib/pets/fuse-tricks.ts")).href);
const Overlay = createRequire(import.meta.url)(join(root, "../desktop/renderer/earth-tricks.js"));
const OverlayGround = createRequire(import.meta.url)(join(root, "../desktop/renderer/ground-tricks.js"));
const OverlayRui = createRequire(import.meta.url)(join(root, "../desktop/renderer/rui-tricks.js"));

test("Ground tricks start only on idle ground", () => {
  assert.deepEqual(
    [...T.TRICKS],
    ["lugstrap", "earthseat", "heaveplate", "bedsettle", "soilgrip", "plateclamp", "groundhush"],
  );
  assert.deepEqual([...T.HAPPY], ["densground", "inkground", "densgrounddragon"]);
  assert.equal(T.GROUNDHUSH_HOLD, 11.2);
  assert.equal(T.RELEASE_S, 1.18);
  assert.equal(T.HAPPY.includes("hum"), false);
  assert.equal(T.HAPPY.includes("bow"), false);
  assert.equal(T.HAPPY.includes("gleam"), false);
  assert.equal(T.TRICKS.includes("earth"), false);
  assert.equal(T.TRICKS.includes("lug"), false);
  assert.equal(T.TRICKS.includes("heave"), false);
  assert.equal(T.TRICKS.includes("bed"), false);
  assert.equal(T.TRICKS.includes("fusehush"), false);
  assert.equal(T.TRICKS.includes("railseat"), false);
  assert.equal(T.TRICKS.includes("latch"), false);
  assert.equal(T.TRICKS.includes("click"), false);
  assert.equal(Fuse.TRICKS.includes("groundhush"), false);
  assert.equal(Relay.TRICKS.includes("lugstrap"), false);
  assert.equal(GaussDragon.TRICKS.includes("groundhush"), false);
  assert.equal(T.canStart({ asleep: false, hidden: false, leaving: false, cmd: "idle" }), true);
  assert.equal(T.canStart({ asleep: true, hidden: false, leaving: false, cmd: "idle" }), false);
  assert.equal(T.canStart({ asleep: false, hidden: true, leaving: false, cmd: "idle" }), false);
  assert.equal(T.canStart({ asleep: false, hidden: false, leaving: false, cmd: "sleep" }), false);
  assert.equal(T.canStart({ asleep: false, hidden: false, leaving: false, cmd: "seek" }), false);
  assert.equal(T.canStart({ asleep: false, hidden: false, leaving: false, cmd: "idle", windowPlay: true }), false);
  assert.equal(T.canStart({ asleep: false, hidden: false, leaving: false, cmd: "idle", card: true }), false);
  assert.equal(T.shouldAbort({ asleep: true, hidden: false, leaving: false, cmd: "idle" }), true);
  assert.equal(T.shouldAbort({ asleep: false, hidden: false, leaving: false, cmd: "idle", card: true }), true);
  assert.equal(T.shouldAbort({ asleep: false, hidden: false, leaving: false, cmd: "idle" }), false);
  assert.equal(T.pickTrick(0.99, true), "groundhush");
  assert.notEqual(T.pickTrick(0.3, false, "groundhush"), "groundhush");
  assert.equal(Overlay.TRICK_KEY, "ground_dragon");
  assert.equal(T.sleepHoldFrame("ground_dragon", 4), null);
  assert.equal(T.TRICKS.includes("somersault"), false);
  assert.equal(T.TRICKS.includes("dance"), false);
});

test("lugstrap/earthseat/heaveplate/bedsettle/soilgrip/plateclamp/groundhush are ground_dragon/Earth-Dragon-true, not copies of prior guests", () => {
  const ground = { asleep: false, hidden: false, leaving: false, cmd: "idle" };
  const hush = T.beginTrick("groundhush", 80, 1);
  assert.equal(hush.anim, "sit");
  assert.equal(hush.phase, "hold");
  const held = T.stepTrick(hush, 5, ground);
  assert.equal(held.phase, "hold");
  assert.equal(held.anim, "sit");
  assert.ok(held.rot !== 0 || held.lift > 0);
  const release = T.stepTrick(hush, T.GROUNDHUSH_HOLD + 0.2, ground);
  assert.equal(release.phase, "release");
  assert.equal(release.anim, "sit");
  const doneHush = T.stepTrick(hush, T.DUR.groundhush + 0.1, ground);
  assert.equal(doneHush.phase, "done");
  assert.ok(T.nextTrickWait(true, 0, "groundhush") > T.nextTrickWait(true, 0, "bedsettle"));
  const latch = T.beginTrick("earthseat", 80, 1);
  assert.equal(latch.anim, "walk");
  const latchMid = T.stepTrick(latch, 0.5, ground);
  assert.ok(Math.abs(latchMid.lift) > 0.5 || Math.abs(latchMid.rot) > 2 || Math.abs(latchMid.x - 80) > 0.1);
  const coil = T.beginTrick("bedsettle", 80, 1);
  assert.equal(coil.anim, "sit");
  const coilMid = T.stepTrick(coil, 0.85, ground);
  assert.ok(Math.abs(coilMid.lift) > 0.5 || Math.abs(coilMid.rot) > 2 || Math.abs(coilMid.x - 80) > 0.1);
  const flick = T.beginTrick("heaveplate", 80, 1);
  assert.equal(flick.anim, "sit");
  const flickMid = T.stepTrick(flick, 0.5, ground);
  assert.ok(Math.abs(flickMid.lift) > 0.5 || Math.abs(flickMid.rot) > 2 || Math.abs(flickMid.x - 80) > 0.1);
  const click = T.beginTrick("lugstrap", 80, 1);
  assert.equal(click.anim, "play");
  const clickMid = T.stepTrick(click, 0.5, ground);
  assert.ok(Math.abs(clickMid.lift) > 0.5 || Math.abs(clickMid.rot) > 2 || Math.abs(clickMid.x - 80) > 0.1);
  const flickDone = T.stepTrick(flick, T.DUR.heaveplate + 0.01, ground);
  assert.equal(flickDone.phase, "done");
  const pole = T.beginTrick("soilgrip", 80, 1);
  assert.equal(pole.anim, "walk");
  const poleMid = T.stepTrick(pole, 0.5, ground);
  assert.ok(Math.abs(poleMid.lift) > 0.5 || Math.abs(poleMid.rot) > 2 || Math.abs(poleMid.x - 80) > 0.1);
  const tap = T.beginTrick("plateclamp", 80, 1);
  assert.equal(tap.anim, "talk");
  const tapMid = T.stepTrick(tap, 0.5, ground);
  assert.ok(Math.abs(tapMid.lift) > 0.5 || Math.abs(tapMid.rot) > 2 || Math.abs(tapMid.x - 80) > 0.1);
  const aborted = T.stepTrick(held, 0.1, { asleep: true, cmd: "sleep" });
  assert.equal(aborted.phase, "done");
  for (const mod of [GaussDragon, SparkDragon, CyberDragon, Relay, Fuse, Rui]) {
    assert.equal(mod.TRICKS.includes("earthseat"), false);
    assert.equal(mod.TRICKS.includes("bedsettle"), false);
    assert.equal(mod.TRICKS.includes("heaveplate"), false);
    assert.equal(mod.TRICKS.includes("lugstrap"), false);
    assert.equal(mod.TRICKS.includes("groundhush"), false);
    assert.equal(mod.TRICKS.includes("soilgrip"), false);
    assert.equal(mod.TRICKS.includes("plateclamp"), false);
    assert.equal(mod.HAPPY.includes("densground"), false);
    assert.equal(mod.HAPPY.includes("inkground"), false);
    assert.equal(mod.HAPPY.includes("densgrounddragon"), false);
  }
});

test("Ground feed-happy is its own sit: densground/inkground/densgrounddragon, and two feeds are not the same", () => {
  assert.deepEqual([...T.HAPPY], ["densground", "inkground", "densgrounddragon"]);
  assert.equal(T.HAPPY.includes("hum"), false);
  assert.equal(T.HAPPY.includes("bow"), false);
  assert.equal(T.HAPPY.includes("gleam"), false);
  assert.equal(T.HAPPY.includes("warm"), false);
  assert.equal(T.HAPPY.includes("densfuse"), false);
  assert.equal(T.pickHappy("densground", 0), "inkground");
  assert.notEqual(T.pickHappy("densground", 0.9), "densground");
  assert.equal(Overlay.pickHappy("inkground", 0) !== "inkground", true);
  assert.equal(T.happyCanStart({ asleep: false, hidden: false, leaving: false, cmd: "idle" }), true);
  assert.equal(T.happyCanStart({ asleep: false, hidden: false, leaving: false, cmd: "idle", card: true }), true);
  assert.equal(T.happyCanStart({ asleep: true, hidden: false, leaving: false, cmd: "idle" }), false);
  assert.equal(T.happyShouldAbort({ cmd: "sleep" }), true);
  assert.equal(T.happyShouldAbort({ cmd: "hide" }), true);
  assert.equal(T.happyShouldAbort({ card: true, cmd: "idle" }), false);
  const dens = T.beginHappy("densground", 80, 1);
  assert.equal(dens.anim, "sit");
  const densMid = T.stepHappy(dens, 0.4, { cmd: "idle" });
  assert.ok(densMid.lift > 0.5 || Math.abs(densMid.rot) > 2);
  assert.notEqual(densMid.phase, "done");
  const ink = T.beginHappy("inkground", 80, 1);
  assert.equal(ink.anim, "play");
  const inkMid = T.stepHappy(ink, 0.35, { cmd: "idle" });
  assert.ok(inkMid.lift > 0.5 || Math.abs(inkMid.rot) > 2);
  const dragon = T.beginHappy("densgrounddragon", 80, 1);
  assert.equal(dragon.anim, "play");
  const done = T.stepHappy(dens, T.HAPPY_DUR.densground + 0.1, { cmd: "idle" });
  assert.equal(done.phase, "done");
  const aborted = T.stepHappy(densMid, 0.1, { asleep: true, cmd: "sleep" });
  assert.equal(aborted.phase, "done");
  assert.equal(aborted.abort, true);
  assert.equal(T.wantsThankYou("ground_dragon"), true);
  assert.equal(T.wantsThankYou("ground"), true);
  assert.equal(T.wantsThankYou("red_panda"), false);
  assert.equal(T.wantsThankYou("fuse_dragon"), false);
  assert.equal(T.wantsThankYou("relay_dragon"), false);
  const thanks = T.startThankYou("ground_dragon", "densground", 80, 1, { cmd: "idle", card: true, windowPlay: true });
  assert.ok(thanks);
  assert.notEqual(thanks.kind, "densground");
  assert.ok(thanks.happy.lift === 0);
  assert.notEqual(thanks.happy.anim, "eat");
  assert.notEqual(thanks.happy.anim, "idle");
  const thanksMid = T.stepHappy(thanks.happy, 0.35, { cmd: "idle", card: true });
  assert.ok(thanksMid.lift > 0 || Math.abs(thanksMid.rot) > 4 || Math.abs(thanksMid.x - 80) > 4, "a thank-you lifts or moves");
  const blocked = T.startThankYou("ground_dragon", "inkground", 80, 1, { asleep: true, cmd: "idle" });
  assert.equal(blocked, null);
  const other = T.startThankYou("fuse_dragon", null, 80, 1, { cmd: "idle" });
  assert.equal(other, null);
  const second = T.startThankYou("ground_dragon", thanks.kind, 80, 1, { cmd: "idle", card: true });
  assert.ok(second);
  assert.notEqual(second.kind, thanks.kind);
});

test("ground registry keeps Rui gated and Ground selectable", () => {
  assert.equal(Rui.TRICK_KEY, "red_panda");
  assert.deepEqual([...Rui.TRICKS], ["somersault", "lie", "scratch", "wave", "dance"]);
  assert.equal(T.TRICK_KEY, "ground_dragon");
  assert.equal(Fuse.TRICK_KEY, "fuse_dragon");
  assert.equal(Rui.wantsThankYou("red_panda"), true);
  assert.equal(Rui.wantsThankYou("ground_dragon"), false);
  assert.equal(T.wantsThankYou("ground_dragon"), true);
  assert.equal(T.wantsThankYou("red_panda"), false);
  assert.equal(Rui.sleepHoldFrame("red_panda", 4), 1);
  assert.equal(T.sleepHoldFrame("ground_dragon", 4), null);
  globalThis.PetRuiTricks = OverlayRui;
  globalThis.PetEarthTricks = Overlay;
  assert.equal(OverlayGround.tricksFor("red_panda"), OverlayRui);
  assert.equal(OverlayGround.tricksFor("rui"), OverlayRui);
  assert.equal(OverlayGround.tricksFor("ground_dragon"), Overlay);
  assert.equal(OverlayGround.tricksFor("ground"), Overlay);
  assert.equal(OverlayGround.wantsThankYou("red_panda"), true);
  assert.equal(OverlayGround.wantsThankYou("ground_dragon"), true);
  assert.equal(OverlayGround.sleepHoldFrame("red_panda", 4), 1);
  assert.equal(OverlayGround.sleepHoldFrame("ground_dragon", 4), null);
});

test("notes: Ground idle-life ultra done; next house-order guests still thin are monarch / bees (parent pick)", () => {
  assert.equal("monarch", "monarch");
  assert.equal("bumblebee", "bumblebee");
  assert.equal(T.TRICK_KEY, "ground_dragon");
  assert.equal(T.GROUNDHUSH_HOLD, 11.2);
  assert.equal(T.RELEASE_S, 1.18);
  assert.equal(T.HAPPY.includes("hum"), false);
  assert.equal(T.TRICKS.includes("earth"), false);
});

// Recommend next house-order guest still lacking dense idle (do not implement): monarch / bumblebee / sweat_bee / honey_drone. Catalog 221.
// Window-play key "earth" unchanged (not a trick kind).
