import assert from "node:assert/strict";
import { createRequire } from "node:module";
import { dirname, join } from "node:path";
import { test } from "node:test";
import { fileURLToPath, pathToFileURL } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const T = await import(pathToFileURL(join(root, "src/lib/pets/earth-tricks.ts")).href);
const Rui = await import(pathToFileURL(join(root, "src/lib/pets/rui-tricks.ts")).href);
const Relay = await import(pathToFileURL(join(root, "src/lib/pets/relay-tricks.ts")).href);
const Fuse = await import(pathToFileURL(join(root, "src/lib/pets/fuse-tricks.ts")).href);
const Overlay = createRequire(import.meta.url)(join(root, "../desktop/renderer/earth-tricks.js"));
const OverlayGround = createRequire(import.meta.url)(join(root, "../desktop/renderer/ground-tricks.js"));
const OverlayRui = createRequire(import.meta.url)(join(root, "../desktop/renderer/rui-tricks.js"));
const OverlayRelay = createRequire(import.meta.url)(join(root, "../desktop/renderer/relay-tricks.js"));
const OverlayFuse = createRequire(import.meta.url)(join(root, "../desktop/renderer/fuse-tricks.js"));
const OverlayCat = createRequire(import.meta.url)(join(root, "../desktop/renderer/cat-tricks.js"));
const OverlayDog = createRequire(import.meta.url)(join(root, "../desktop/renderer/dog-tricks.js"));
const OverlayRabbit = createRequire(import.meta.url)(join(root, "../desktop/renderer/rabbit-tricks.js"));

test("Ground tricks start only on idle ground", () => {
  assert.deepEqual([...T.TRICKS], ["lug", "earth", "heave", "bed"]);
  assert.equal(T.canStart({ asleep: false, hidden: false, leaving: false, cmd: "idle" }), true);
  assert.equal(T.canStart({ asleep: true, hidden: false, leaving: false, cmd: "idle" }), false);
  assert.equal(T.canStart({ asleep: false, hidden: true, leaving: false, cmd: "idle" }), false);
  assert.equal(T.canStart({ asleep: false, hidden: false, leaving: false, cmd: "sleep" }), false);
  assert.equal(T.canStart({ asleep: false, hidden: false, leaving: false, cmd: "seek" }), false);
  assert.equal(T.canStart({ asleep: false, hidden: false, leaving: false, cmd: "idle", windowPlay: true }), false);
  assert.equal(T.canStart({ asleep: false, hidden: false, leaving: false, cmd: "idle", card: true }), false);
  assert.equal(T.shouldAbort({ asleep: true, hidden: false, leaving: false, cmd: "idle" }), true);
  assert.equal(T.shouldAbort({ asleep: false, hidden: false, leaving: false, cmd: "idle", card: true }), true);
  assert.equal(T.shouldAbort({ asleep: false, hidden: false, leaving: false, cmd: "idle" }), false);
  assert.equal(T.pickTrick(0.99, true), "earth");
  assert.notEqual(T.pickTrick(0.3, false, "earth"), "earth");
  assert.equal(Overlay.TRICK_KEY, "ground_dragon");
  assert.equal(T.sleepHoldFrame("ground_dragon", 4), null);
  assert.equal(T.TRICKS.includes("somersault"), false);
  assert.equal(T.TRICKS.includes("click"), false);
  assert.equal(T.TRICKS.includes("seat"), false);
  assert.equal(T.TRICKS.includes("blow"), false);
  assert.equal(T.TRICKS.includes("current"), false);
});

test("lug/earth/heave/bed are earth-true, not Rui Relay or Fuse clones", () => {
  const ground = { asleep: false, hidden: false, leaving: false, cmd: "idle" };
  const lug = T.beginTrick("lug", 80, 1);
  assert.equal(lug.anim, "sit");
  const lugMid = T.stepTrick(lug, 0.2, ground);
  assert.ok(lugMid.lift < 2);
  assert.ok(Math.abs(lugMid.rot) > 0 || lugMid.lift < 0);
  const earth = T.beginTrick("earth", 80, 1);
  assert.equal(earth.anim, "sit");
  assert.equal(earth.phase, "hold");
  const held = T.stepTrick(earth, 5, ground);
  assert.equal(held.phase, "hold");
  assert.equal(held.anim, "sit");
  assert.equal(held.rot, 0);
  assert.ok(held.lift < 0);
  const release = T.stepTrick(earth, T.EARTH_HOLD + 0.2, ground);
  assert.equal(release.phase, "release");
  assert.equal(release.anim, "sit");
  const doneEarth = T.stepTrick(earth, T.DUR.earth + 0.1, ground);
  assert.equal(doneEarth.phase, "done");
  assert.ok(T.nextTrickWait(true, 0, "earth") > T.nextTrickWait(true, 0, "lug"));
  const heave = T.beginTrick("heave", 80, 1);
  assert.equal(heave.anim, "play");
  const heaveMid = T.stepTrick(heave, 0.2, ground);
  assert.ok(heaveMid.lift > 2);
  assert.ok(heaveMid.lift < 30, "heave is a slow pulse, not a fuse blow spike");
  const heaveDone = T.stepTrick(heave, 1.3, ground);
  assert.equal(heaveDone.phase, "done");
  const bed = T.beginTrick("bed", 80, 1);
  assert.equal(bed.anim, "walk");
  const bedMid = T.stepTrick(bed, 0.4, ground);
  assert.equal(bedMid.anim, "walk");
  assert.ok(Math.abs(bedMid.x - 80) > 3);
  const bedSit = T.stepTrick(bed, 1.4, ground);
  assert.equal(bedSit.anim, "sit");
  assert.ok(bedSit.lift <= 0);
  const aborted = T.stepTrick(held, 0.1, { asleep: true, cmd: "sleep" });
  assert.equal(aborted.phase, "done");
  assert.equal(Relay.TRICKS.includes("lug"), false);
  assert.equal(Fuse.TRICKS.includes("heave"), false);
  assert.equal(Rui.TRICKS.includes("earth"), false);
  assert.equal(Fuse.TRICKS.includes("bed"), false);
});

test("Ground feed-happy is its own sit: hum/bow/gleam, and two feeds are not the same", () => {
  assert.deepEqual([...T.HAPPY], ["hum", "bow", "gleam"]);
  assert.equal(T.HAPPY.includes("spark"), false);
  assert.equal(T.HAPPY.includes("warm"), false);
  assert.equal(T.HAPPY.includes("twirl"), false);
  assert.equal(T.pickHappy("hum", 0), "bow");
  assert.notEqual(T.pickHappy("hum", 0.9), "hum");
  assert.equal(Overlay.pickHappy("bow", 0) !== "bow", true);
  assert.equal(T.happyCanStart({ asleep: false, hidden: false, leaving: false, cmd: "idle" }), true);
  assert.equal(T.happyCanStart({ asleep: false, hidden: false, leaving: false, cmd: "idle", card: true }), true);
  assert.equal(T.happyCanStart({ asleep: true, hidden: false, leaving: false, cmd: "idle" }), false);
  assert.equal(T.happyShouldAbort({ cmd: "sleep" }), true);
  assert.equal(T.happyShouldAbort({ cmd: "hide" }), true);
  assert.equal(T.happyShouldAbort({ card: true, cmd: "idle" }), false);
  const hum = T.beginHappy("hum", 80, 1);
  assert.equal(hum.anim, "talk");
  const humMid = T.stepHappy(hum, 0.4, { cmd: "idle" });
  assert.ok(humMid.lift > 0.5 || Math.abs(humMid.rot) > 1);
  assert.notEqual(humMid.phase, "done");
  const bow = T.beginHappy("bow", 80, 1);
  assert.equal(bow.anim, "sit");
  const bowMid = T.stepHappy(bow, 0.3, { cmd: "idle" });
  assert.ok(bowMid.lift < 0);
  const gleam = T.beginHappy("gleam", 80, 1);
  assert.equal(gleam.anim, "play");
  const done = T.stepHappy(hum, T.HAPPY_DUR.hum + 0.1, { cmd: "idle" });
  assert.equal(done.phase, "done");
  const aborted = T.stepHappy(humMid, 0.1, { asleep: true, cmd: "sleep" });
  assert.equal(aborted.phase, "done");
  assert.equal(aborted.abort, true);
  assert.equal(T.wantsThankYou("ground_dragon"), true);
  assert.equal(T.wantsThankYou("ground"), true);
  assert.equal(T.wantsThankYou("red_panda"), false);
  assert.equal(T.wantsThankYou("relay_dragon"), false);
  assert.equal(T.wantsThankYou("fuse_dragon"), false);
  const thanks = T.startThankYou("ground_dragon", "hum", 80, 1, { cmd: "idle", card: true, windowPlay: true });
  assert.ok(thanks);
  assert.notEqual(thanks.kind, "hum");
  assert.ok(thanks.happy.lift === 0);
  assert.notEqual(thanks.happy.anim, "eat");
  assert.notEqual(thanks.happy.anim, "idle");
  const thanksMid = T.stepHappy(thanks.happy, 0.35, { cmd: "idle", card: true });
  assert.ok(thanksMid.lift !== 0 || Math.abs(thanksMid.rot) > 1, "a thank-you lifts or bows");
  const blocked = T.startThankYou("ground_dragon", "bow", 80, 1, { asleep: true, cmd: "idle" });
  assert.equal(blocked, null);
  const other = T.startThankYou("gauss_dragon", null, 80, 1, { cmd: "idle" });
  assert.equal(other, null);
  const second = T.startThankYou("ground_dragon", thanks.kind, 80, 1, { cmd: "idle", card: true });
  assert.ok(second);
  assert.notEqual(second.kind, thanks.kind);
});

test("ground registry keeps Rui gated; Relay Fuse Ground selectable", () => {
  assert.equal(Rui.TRICK_KEY, "red_panda");
  assert.equal(Relay.TRICK_KEY, "relay_dragon");
  assert.equal(Fuse.TRICK_KEY, "fuse_dragon");
  assert.equal(T.TRICK_KEY, "ground_dragon");
  assert.deepEqual([...Rui.TRICKS], ["somersault", "lie", "scratch", "wave", "dance"]);
  assert.deepEqual([...Relay.TRICKS], ["click", "latch", "arc", "buzz", "switch"]);
  assert.deepEqual([...Fuse.TRICKS], ["seat", "current", "blow", "reseat"]);
  assert.equal(Rui.wantsThankYou("ground_dragon"), false);
  assert.equal(Relay.wantsThankYou("ground_dragon"), false);
  assert.equal(Fuse.wantsThankYou("ground_dragon"), false);
  assert.equal(T.wantsThankYou("ground_dragon"), true);
  assert.equal(T.wantsThankYou("red_panda"), false);
  assert.equal(T.wantsThankYou("fuse_dragon"), false);
  assert.equal(Rui.sleepHoldFrame("red_panda", 4), 1);
  assert.equal(T.sleepHoldFrame("ground_dragon", 4), null);
  globalThis.PetRuiTricks = OverlayRui;
  globalThis.PetRelayTricks = OverlayRelay;
  globalThis.PetFuseTricks = OverlayFuse;
  globalThis.PetEarthTricks = Overlay;
  globalThis.PetCatTricks = OverlayCat;
  globalThis.PetDogTricks = OverlayDog;
  globalThis.PetRabbitTricks = OverlayRabbit;
  assert.equal(OverlayGround.tricksFor("red_panda"), OverlayRui);
  assert.equal(OverlayGround.tricksFor("rui"), OverlayRui);
  assert.equal(OverlayGround.tricksFor("relay_dragon"), OverlayRelay);
  assert.equal(OverlayGround.tricksFor("relay"), OverlayRelay);
  assert.equal(OverlayGround.tricksFor("fuse_dragon"), OverlayFuse);
  assert.equal(OverlayGround.tricksFor("fuse"), OverlayFuse);
  assert.equal(OverlayGround.tricksFor("ground_dragon"), Overlay);
  assert.equal(OverlayGround.tricksFor("ground"), Overlay);
  assert.equal(OverlayGround.tricksFor("cat"), OverlayCat);
  assert.equal(OverlayGround.tricksFor("dog"), OverlayDog);
  assert.equal(OverlayGround.tricksFor("rabbit"), OverlayRabbit);
  assert.equal(OverlayGround.wantsThankYou("red_panda"), true);
  assert.equal(OverlayGround.wantsThankYou("relay_dragon"), true);
  assert.equal(OverlayGround.wantsThankYou("fuse_dragon"), true);
  assert.equal(OverlayGround.wantsThankYou("ground_dragon"), true);
  assert.equal(OverlayGround.wantsThankYou("cat"), true);
  assert.equal(OverlayGround.wantsThankYou("dog"), true);
  assert.equal(OverlayGround.wantsThankYou("rabbit"), true);
  assert.equal(OverlayGround.sleepHoldFrame("red_panda", 4), 1);
  assert.equal(OverlayGround.sleepHoldFrame("relay_dragon"), null);
  assert.equal(OverlayGround.sleepHoldFrame("fuse_dragon", 4), null);
  assert.equal(OverlayGround.sleepHoldFrame("ground_dragon", 4), null);
});