import assert from "node:assert/strict";
import { createRequire } from "node:module";
import { dirname, join } from "node:path";
import { test } from "node:test";
import { fileURLToPath, pathToFileURL } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const T = await import(pathToFileURL(join(root, "src/lib/pets/ferret-tricks.ts")).href);
const Rui = await import(pathToFileURL(join(root, "src/lib/pets/rui-tricks.ts")).href);
const Relay = await import(pathToFileURL(join(root, "src/lib/pets/relay-tricks.ts")).href);
const Fuse = await import(pathToFileURL(join(root, "src/lib/pets/fuse-tricks.ts")).href);
const Earth = await import(pathToFileURL(join(root, "src/lib/pets/earth-tricks.ts")).href);
const Cat = await import(pathToFileURL(join(root, "src/lib/pets/cat-tricks.ts")).href);
const Dog = await import(pathToFileURL(join(root, "src/lib/pets/dog-tricks.ts")).href);
const Rabbit = await import(pathToFileURL(join(root, "src/lib/pets/rabbit-tricks.ts")).href);
const Hamster = await import(pathToFileURL(join(root, "src/lib/pets/hamster-tricks.ts")).href);
const GuineaPig = await import(pathToFileURL(join(root, "src/lib/pets/guinea-pig-tricks.ts")).href);
const Turtle = await import(pathToFileURL(join(root, "src/lib/pets/turtle-tricks.ts")).href);
const Goldfish = await import(pathToFileURL(join(root, "src/lib/pets/goldfish-tricks.ts")).href);
const Budgie = await import(pathToFileURL(join(root, "src/lib/pets/budgie-tricks.ts")).href);
const Fox = await import(pathToFileURL(join(root, "src/lib/pets/fox-tricks.ts")).href);
const Penguin = await import(pathToFileURL(join(root, "src/lib/pets/penguin-tricks.ts")).href);
const Parrot = await import(pathToFileURL(join(root, "src/lib/pets/parrot-tricks.ts")).href);
const Overlay = createRequire(import.meta.url)(join(root, "../desktop/renderer/ferret-tricks.js"));
const OverlayGround = createRequire(import.meta.url)(join(root, "../desktop/renderer/ground-tricks.js"));
const OverlayRui = createRequire(import.meta.url)(join(root, "../desktop/renderer/rui-tricks.js"));
const OverlayRelay = createRequire(import.meta.url)(join(root, "../desktop/renderer/relay-tricks.js"));
const OverlayFuse = createRequire(import.meta.url)(join(root, "../desktop/renderer/fuse-tricks.js"));
const OverlayEarth = createRequire(import.meta.url)(join(root, "../desktop/renderer/earth-tricks.js"));
const OverlayCat = createRequire(import.meta.url)(join(root, "../desktop/renderer/cat-tricks.js"));
const OverlayDog = createRequire(import.meta.url)(join(root, "../desktop/renderer/dog-tricks.js"));
const OverlayRabbit = createRequire(import.meta.url)(join(root, "../desktop/renderer/rabbit-tricks.js"));
const OverlayHamster = createRequire(import.meta.url)(join(root, "../desktop/renderer/hamster-tricks.js"));
const OverlayGuineaPig = createRequire(import.meta.url)(join(root, "../desktop/renderer/guinea-pig-tricks.js"));
const OverlayTurtle = createRequire(import.meta.url)(join(root, "../desktop/renderer/turtle-tricks.js"));
const OverlayGoldfish = createRequire(import.meta.url)(join(root, "../desktop/renderer/goldfish-tricks.js"));
const OverlayBudgie = createRequire(import.meta.url)(join(root, "../desktop/renderer/budgie-tricks.js"));
const OverlayFox = createRequire(import.meta.url)(join(root, "../desktop/renderer/fox-tricks.js"));
const OverlayPenguin = createRequire(import.meta.url)(join(root, "../desktop/renderer/penguin-tricks.js"));
const OverlayParrot = createRequire(import.meta.url)(join(root, "../desktop/renderer/parrot-tricks.js"));
const OverlayHedgehog = createRequire(import.meta.url)(join(root, "../desktop/renderer/hedgehog-tricks.js"));
const OverlayChinchilla = createRequire(import.meta.url)(join(root, "../desktop/renderer/chinchilla-tricks.js"));
const OverlayAxolotl = createRequire(import.meta.url)(join(root, "../desktop/renderer/axolotl-tricks.js"));
const OverlayToucan = createRequire(import.meta.url)(join(root, "../desktop/renderer/toucan-tricks.js"));
const OverlayIguana = createRequire(import.meta.url)(join(root, "../desktop/renderer/iguana-tricks.js"));
const OverlayDragon = createRequire(import.meta.url)(join(root, "../desktop/renderer/dragon-tricks.js"));

test("Wick tricks start only on idle ground", () => {
  assert.deepEqual([...T.TRICKS], ["tube", "romp", "steal", "puff", "noodle", "corkscrew", "slink"]);
  assert.equal(T.canStart({ asleep: false, hidden: false, leaving: false, cmd: "idle" }), true);
  assert.equal(T.canStart({ asleep: true, hidden: false, leaving: false, cmd: "idle" }), false);
  assert.equal(T.canStart({ asleep: false, hidden: true, leaving: false, cmd: "idle" }), false);
  assert.equal(T.canStart({ asleep: false, hidden: false, leaving: false, cmd: "sleep" }), false);
  assert.equal(T.canStart({ asleep: false, hidden: false, leaving: false, cmd: "seek" }), false);
  assert.equal(T.canStart({ asleep: false, hidden: false, leaving: false, cmd: "idle", windowPlay: true }), false);
  assert.equal(T.canStart({ asleep: false, hidden: false, leaving: false, cmd: "idle", card: true }), false);
  assert.equal(T.shouldAbort({ asleep: true, hidden: false, leaving: false, cmd: "idle" }), true);
  assert.equal(T.shouldAbort({ asleep: false, hidden: false, leaving: false, cmd: "idle", card: true }), true);
  assert.equal(T.shouldAbort({ asleep: false, hidden: false, leaving: false, cmd: "idle" }), false);
  assert.equal(T.pickTrick(0.99, true), "tube");
  assert.notEqual(T.pickTrick(0.3, false, "tube"), "tube");
  assert.equal(Overlay.TRICK_KEY, "ferret");
  assert.equal(T.sleepHoldFrame("ferret", 4), null);
  assert.equal(T.TRICKS.includes("thread"), false);
  assert.equal(T.TRICKS.includes("scurry"), false);
  assert.equal(T.TRICKS.includes("den"), false);
  assert.equal(T.TRICKS.includes("zoom"), false);
  assert.equal(T.TRICKS.includes("dance"), false);
  assert.equal(T.TRICKS.includes("pounce"), false);
  assert.equal(T.TRICKS.includes("mouser"), false);
  assert.equal(T.TRICKS.includes("quote"), false);
  assert.equal(T.TRICKS.includes("strut"), false);
  assert.equal(T.TRICKS.includes("flash"), false);
  assert.equal(T.TRICKS.includes("binky"), false);
  assert.equal(T.TRICKS.includes("popcorn"), false);
  assert.equal(T.TRICKS.includes("prance"), false);
  assert.equal(T.TRICKS.includes("trot"), false);
  assert.equal(T.TRICKS.includes("nest"), false);
});

test("tube/romp/steal/puff/noodle/corkscrew/slink are house-ferret-true, not Rui cat dog rabbit hamster guinea-pig turtle goldfish budgie fox penguin parrot or dragon clones", () => {
  const ground = { asleep: false, hidden: false, leaving: false, cmd: "idle" };
  const tube = T.beginTrick("tube", 80, 1);
  assert.equal(tube.anim, "sit");
  assert.equal(tube.phase, "hold");
  const held = T.stepTrick(tube, 5, ground);
  assert.equal(held.phase, "hold");
  assert.equal(held.anim, "sit");
  assert.ok(held.rot !== 0 || Math.abs(held.lift) > 1);
  const release = T.stepTrick(tube, T.TUBE_HOLD + 0.2, ground);
  assert.equal(release.phase, "release");
  assert.equal(release.anim, "sit");
  const doneTube = T.stepTrick(tube, T.DUR.tube + 0.1, ground);
  assert.equal(doneTube.phase, "done");
  assert.ok(T.nextTrickWait(true, 0, "tube") > T.nextTrickWait(true, 0, "romp"));
  const romp = T.beginTrick("romp", 80, 1);
  assert.equal(romp.anim, "play");
  const rompMid = T.stepTrick(romp, 0.6, ground);
  assert.ok(Math.abs(rompMid.x - 80) > 1 || Math.abs(rompMid.lift) > 0.3 || Math.abs(rompMid.rot) > 1);
  const steal = T.beginTrick("steal", 80, 1);
  assert.equal(steal.anim, "walk");
  const stealMid = T.stepTrick(steal, 0.5, ground);
  assert.ok(Math.abs(stealMid.x - 80) > 1 || Math.abs(stealMid.lift) > 0.2 || Math.abs(stealMid.rot) > 1);
  const puff = T.beginTrick("puff", 80, 1);
  assert.equal(puff.anim, "sit");
  const puffMid = T.stepTrick(puff, 0.45, ground);
  assert.ok(Math.abs(puffMid.lift) > 0.2 || Math.abs(puffMid.rot) > 1);
  const noodle = T.beginTrick("noodle", 80, 1);
  assert.equal(noodle.anim, "play");
  const noodleMid = T.stepTrick(noodle, 0.4, ground);
  assert.ok(noodleMid.lift > 0.5 || Math.abs(noodleMid.rot) > 2);
  const noodleDone = T.stepTrick(noodle, T.DUR.noodle + 0.1, ground);
  assert.equal(noodleDone.phase, "done");
  const cork = T.beginTrick("corkscrew", 80, 1);
  assert.equal(cork.anim, "play");
  const corkMid = T.stepTrick(cork, T.DUR.corkscrew * 0.4, ground);
  assert.ok(corkMid.lift > 4 || Math.abs(corkMid.rot) > 6);
  const slink = T.beginTrick("slink", 80, 1);
  assert.equal(slink.anim, "walk");
  const slinkMid = T.stepTrick(slink, T.DUR.slink * 0.4, ground);
  assert.ok(slinkMid.lift < -2 || Math.abs(slinkMid.rot) > 4);
  assert.equal(T.TRICKS.includes("dance"), false);
  assert.equal(T.TRICKS.includes("twist"), false);
  assert.equal(T.TRICKS.includes("spiral"), false);
  assert.equal(T.TRICKS.includes("tumble"), false);
  assert.equal(T.TRICKS.includes("sneak"), false);
  assert.equal(T.TRICKS.includes("stalk"), false);
  const aborted = T.stepTrick(held, 0.1, { asleep: true, cmd: "sleep" });
  assert.equal(aborted.phase, "done");
  assert.equal(Rui.TRICKS.includes("tube"), false);
  assert.equal(Cat.TRICKS.includes("romp"), false);
  assert.equal(Dog.TRICKS.includes("steal"), false);
  assert.equal(Rabbit.TRICKS.includes("puff"), false);
  assert.equal(Hamster.TRICKS.includes("noodle"), false);
  assert.equal(GuineaPig.TRICKS.includes("tube"), false);
  assert.equal(Turtle.TRICKS.includes("romp"), false);
  assert.equal(Goldfish.TRICKS.includes("steal"), false);
  assert.equal(Budgie.TRICKS.includes("puff"), false);
  assert.equal(Fox.TRICKS.includes("noodle"), false);
  assert.equal(Penguin.TRICKS.includes("tube"), false);
  assert.equal(Parrot.TRICKS.includes("romp"), false);
  assert.equal(Relay.TRICKS.includes("tube"), false);
  assert.equal(Fuse.TRICKS.includes("romp"), false);
  assert.equal(Earth.TRICKS.includes("steal"), false);
  assert.equal(T.TRICKS.includes("thread"), false);
  assert.equal(T.TRICKS.includes("scurry"), false);
  assert.equal(T.TRICKS.includes("den"), false);
  assert.equal(T.TRICKS.includes("dance"), false);
});

test("Wick feed-happy is its own sit: dook/kiss/chuckle, and two feeds are not the same", () => {
  assert.deepEqual([...T.HAPPY], ["dook", "kiss", "chuckle"]);
  assert.equal(T.HAPPY.includes("spark"), false);
  assert.equal(T.HAPPY.includes("purr"), false);
  assert.equal(T.HAPPY.includes("tail"), false);
  assert.equal(T.HAPPY.includes("twitch"), false);
  assert.equal(T.HAPPY.includes("stuff"), false);
  assert.equal(T.HAPPY.includes("peep"), false);
  assert.equal(T.HAPPY.includes("munch"), false);
  assert.equal(T.HAPPY.includes("gleam"), false);
  assert.equal(T.HAPPY.includes("bubble"), false);
  assert.equal(T.HAPPY.includes("chirp"), false);
  assert.equal(T.HAPPY.includes("chatter"), false);
  assert.equal(T.HAPPY.includes("bob"), false);
  assert.equal(T.HAPPY.includes("whistle"), false);
  assert.equal(T.HAPPY.includes("trill"), false);
  assert.equal(T.HAPPY.includes("ruffle"), false);
  assert.equal(T.HAPPY.includes("yip"), false);
  assert.equal(T.HAPPY.includes("chuff"), false);
  assert.equal(T.HAPPY.includes("nuzzle"), false);
  assert.equal(T.HAPPY.includes("woof"), false);
  assert.equal(T.HAPPY.includes("bray"), false);
  assert.equal(T.HAPPY.includes("beak"), false);
  assert.equal(T.HAPPY.includes("shimmy"), false);
  assert.equal(T.HAPPY.includes("squawk"), false);
  assert.equal(T.HAPPY.includes("bravo"), false);
  assert.equal(T.HAPPY.includes("scissor"), false);
  assert.equal(T.HAPPY.includes("chitter"), false);
  assert.equal(T.HAPPY.includes("bounce"), false);
  assert.equal(T.pickHappy("dook", 0), "kiss");
  assert.notEqual(T.pickHappy("dook", 0.9), "dook");
  assert.equal(Overlay.pickHappy("kiss", 0) !== "kiss", true);
  assert.equal(T.happyCanStart({ asleep: false, hidden: false, leaving: false, cmd: "idle" }), true);
  assert.equal(T.happyCanStart({ asleep: false, hidden: false, leaving: false, cmd: "idle", card: true }), true);
  assert.equal(T.happyCanStart({ asleep: true, hidden: false, leaving: false, cmd: "idle" }), false);
  assert.equal(T.happyShouldAbort({ cmd: "sleep" }), true);
  assert.equal(T.happyShouldAbort({ cmd: "hide" }), true);
  assert.equal(T.happyShouldAbort({ card: true, cmd: "idle" }), false);
  const dook = T.beginHappy("dook", 80, 1);
  assert.equal(dook.anim, "talk");
  const dookMid = T.stepHappy(dook, 0.4, { cmd: "idle" });
  assert.ok(dookMid.lift !== 0 || Math.abs(dookMid.rot) > 0.5);
  assert.notEqual(dookMid.phase, "done");
  const kiss = T.beginHappy("kiss", 80, 1);
  assert.equal(kiss.anim, "sit");
  const kissMid = T.stepHappy(kiss, 0.3, { cmd: "idle" });
  assert.ok(kissMid.lift > 0.2 || Math.abs(kissMid.rot) > 0.5);
  const chuckle = T.beginHappy("chuckle", 80, 1);
  assert.equal(chuckle.anim, "play");
  const done = T.stepHappy(dook, T.HAPPY_DUR.dook + 0.1, { cmd: "idle" });
  assert.equal(done.phase, "done");
  const aborted = T.stepHappy(kissMid, 0.1, { asleep: true, cmd: "sleep" });
  assert.equal(aborted.phase, "done");
  assert.equal(aborted.abort, true);
  assert.equal(T.wantsThankYou("ferret"), true);
  assert.equal(T.wantsThankYou("wick"), true);
  assert.equal(T.wantsThankYou("parrot"), false);
  assert.equal(T.wantsThankYou("quill"), false);
  assert.equal(T.wantsThankYou("penguin"), false);
  assert.equal(T.wantsThankYou("peck"), false);
  assert.equal(T.wantsThankYou("fox"), false);
  assert.equal(T.wantsThankYou("rue"), false);
  assert.equal(T.wantsThankYou("budgie"), false);
  assert.equal(T.wantsThankYou("echo"), false);
  assert.equal(T.wantsThankYou("goldfish"), false);
  assert.equal(T.wantsThankYou("coin"), false);
  assert.equal(T.wantsThankYou("turtle"), false);
  assert.equal(T.wantsThankYou("guinea_pig"), false);
  assert.equal(T.wantsThankYou("hamster"), false);
  assert.equal(T.wantsThankYou("dog"), false);
  assert.equal(T.wantsThankYou("cat"), false);
  assert.equal(T.wantsThankYou("rabbit"), false);
  assert.equal(T.wantsThankYou("red_panda"), false);
  assert.equal(T.wantsThankYou("ground_dragon"), false);
  const thanks = T.startThankYou("ferret", "dook", 80, 1, { cmd: "idle", card: true, windowPlay: true });
  assert.ok(thanks);
  assert.notEqual(thanks.kind, "dook");
  assert.ok(thanks.happy.lift === 0);
  assert.notEqual(thanks.happy.anim, "eat");
  assert.notEqual(thanks.happy.anim, "idle");
  const thanksMid = T.stepHappy(thanks.happy, 0.35, { cmd: "idle", card: true });
  assert.ok(thanksMid.lift !== 0 || Math.abs(thanksMid.rot) > 0.5, "a thank-you dooks or chuckles");
  const blocked = T.startThankYou("ferret", "kiss", 80, 1, { asleep: true, cmd: "idle" });
  assert.equal(blocked, null);
  const other = T.startThankYou("chinchilla", null, 80, 1, { cmd: "idle" });
  assert.equal(other, null);
  const second = T.startThankYou("ferret", thanks.kind, 80, 1, { cmd: "idle", card: true });
  assert.ok(second);
  assert.notEqual(second.kind, thanks.kind);
});

test("ground registry keeps prior guests gated; Wick selectable; no thread/scurry/den/dance-name collision", () => {
  assert.equal(Rui.TRICK_KEY, "red_panda");
  assert.equal(Relay.TRICK_KEY, "relay_dragon");
  assert.equal(Fuse.TRICK_KEY, "fuse_dragon");
  assert.equal(Earth.TRICK_KEY, "ground_dragon");
  assert.equal(Cat.TRICK_KEY, "cat");
  assert.equal(Dog.TRICK_KEY, "dog");
  assert.equal(Rabbit.TRICK_KEY, "rabbit");
  assert.equal(Hamster.TRICK_KEY, "hamster");
  assert.equal(GuineaPig.TRICK_KEY, "guinea_pig");
  assert.equal(Turtle.TRICK_KEY, "turtle");
  assert.equal(Goldfish.TRICK_KEY, "goldfish");
  assert.equal(Budgie.TRICK_KEY, "budgie");
  assert.equal(Fox.TRICK_KEY, "fox");
  assert.equal(Penguin.TRICK_KEY, "penguin");
  assert.equal(Parrot.TRICK_KEY, "parrot");
  assert.equal(T.TRICK_KEY, "ferret");
  assert.deepEqual([...Rui.TRICKS], ["somersault", "lie", "scratch", "wave", "dance"]);
  assert.deepEqual([...Relay.TRICKS], ["contactclick", "latchseat", "arcflick", "coilbuzz", "poleswitch", "armaturetap", "relayhush"]);
  assert.deepEqual([...Fuse.TRICKS], ["railseat", "holdcurrent", "blowclear", "reseatsnap", "cartridgerattle", "bladeflash", "fusehush"]);
  assert.deepEqual([...Earth.TRICKS], ["lugstrap", "earthseat", "heaveplate", "bedsettle", "soilgrip", "plateclamp", "groundhush"]);
  assert.deepEqual([...Cat.TRICKS], ["loaf", "knead", "stretch", "wash", "pounce", "bunting", "mlem"]);
  assert.deepEqual([...Dog.TRICKS], ["wait", "wag", "sniff", "bow", "zoom", "beg", "pant"]);
  assert.deepEqual([...Rabbit.TRICKS], ["flop", "groom", "periscope", "dig", "binky", "rub", "nosh"]);
  assert.deepEqual([...Hamster.TRICKS], ["nest", "cheek", "scurry", "pocket", "reel", "scrub", "seed"]);
  assert.deepEqual([...GuineaPig.TRICKS], ["popcorn", "rumble", "hay", "potato", "zig", "lookout", "teeth"]);
  assert.deepEqual([...Turtle.TRICKS], ["soak", "tuck", "crane", "plod", "paddle", "snorkel", "wipe"]);
  assert.deepEqual([...Goldfish.TRICKS], ["drift", "gulp", "flare", "glint", "dart", "yawn", "forage"]);
  assert.deepEqual([...Budgie.TRICKS], ["preen", "bobble", "mimic", "sidle", "dangle", "beakgrind", "shellout"]);
  assert.deepEqual([...Fox.TRICKS], ["den", "mouser", "stalk", "trot", "prance", "cock", "stash"]);
  assert.deepEqual([...Penguin.TRICKS], ["huddle", "toboggan", "waddle", "porpoise", "trumpet", "rockhop", "ecstatic"]);
  assert.deepEqual([...Parrot.TRICKS], ["quote", "strut", "fan", "crack", "flash", "pineye", "invert"]);
  assert.equal(T.TRICKS.includes("thread"), false);
  assert.equal(T.TRICKS.includes("scurry"), false);
  assert.equal(T.TRICKS.includes("den"), false);
  assert.equal(T.TRICKS.includes("dance"), false);
  assert.equal(Rui.wantsThankYou("ferret"), false);
  assert.equal(Relay.wantsThankYou("ferret"), false);
  assert.equal(Fuse.wantsThankYou("ferret"), false);
  assert.equal(Earth.wantsThankYou("ferret"), false);
  assert.equal(Cat.wantsThankYou("ferret"), false);
  assert.equal(Dog.wantsThankYou("ferret"), false);
  assert.equal(Rabbit.wantsThankYou("ferret"), false);
  assert.equal(Hamster.wantsThankYou("ferret"), false);
  assert.equal(GuineaPig.wantsThankYou("ferret"), false);
  assert.equal(Turtle.wantsThankYou("ferret"), false);
  assert.equal(Goldfish.wantsThankYou("ferret"), false);
  assert.equal(Budgie.wantsThankYou("ferret"), false);
  assert.equal(Fox.wantsThankYou("ferret"), false);
  assert.equal(Penguin.wantsThankYou("ferret"), false);
  assert.equal(Parrot.wantsThankYou("ferret"), false);
  assert.equal(T.wantsThankYou("ferret"), true);
  assert.equal(T.wantsThankYou("wick"), true);
  assert.equal(T.wantsThankYou("parrot"), false);
  assert.equal(T.wantsThankYou("quill"), false);
  assert.equal(Rui.sleepHoldFrame("red_panda", 4), 1);
  assert.equal(T.sleepHoldFrame("ferret", 4), null);
  globalThis.PetRuiTricks = OverlayRui;
  globalThis.PetRelayTricks = OverlayRelay;
  globalThis.PetFuseTricks = OverlayFuse;
  globalThis.PetEarthTricks = OverlayEarth;
  globalThis.PetCatTricks = OverlayCat;
  globalThis.PetDogTricks = OverlayDog;
  globalThis.PetRabbitTricks = OverlayRabbit;
  globalThis.PetHamsterTricks = OverlayHamster;
  globalThis.PetGuineaPigTricks = OverlayGuineaPig;
  globalThis.PetTurtleTricks = OverlayTurtle;
  globalThis.PetGoldfishTricks = OverlayGoldfish;
  globalThis.PetBudgieTricks = OverlayBudgie;
  globalThis.PetFoxTricks = OverlayFox;
  globalThis.PetPenguinTricks = OverlayPenguin;
  globalThis.PetParrotTricks = OverlayParrot;
  globalThis.PetFerretTricks = Overlay;
  globalThis.PetHedgehogTricks = OverlayHedgehog;
  globalThis.PetChinchillaTricks = OverlayChinchilla;
  globalThis.PetAxolotlTricks = OverlayAxolotl;
globalThis.PetToucanTricks = OverlayToucan;
globalThis.PetIguanaTricks = OverlayIguana;
  globalThis.PetDragonTricks = OverlayDragon;
  assert.equal(OverlayGround.tricksFor("red_panda"), OverlayRui);
  assert.equal(OverlayGround.tricksFor("rui"), OverlayRui);
  assert.equal(OverlayGround.tricksFor("relay_dragon"), OverlayRelay);
  assert.equal(OverlayGround.tricksFor("fuse_dragon"), OverlayFuse);
  assert.equal(OverlayGround.tricksFor("ground_dragon"), OverlayEarth);
  assert.equal(OverlayGround.tricksFor("ground"), OverlayEarth);
  assert.equal(OverlayGround.tricksFor("cat"), OverlayCat);
  assert.equal(OverlayGround.tricksFor("miso"), OverlayCat);
  assert.equal(OverlayGround.tricksFor("dog"), OverlayDog);
  assert.equal(OverlayGround.tricksFor("pip"), OverlayDog);
  assert.equal(OverlayGround.tricksFor("rabbit"), OverlayRabbit);
  assert.equal(OverlayGround.tricksFor("thimble"), OverlayRabbit);
  assert.equal(OverlayGround.tricksFor("hamster"), OverlayHamster);
  assert.equal(OverlayGround.tricksFor("clip"), OverlayHamster);
  assert.equal(OverlayGround.tricksFor("guinea_pig"), OverlayGuineaPig);
  assert.equal(OverlayGround.tricksFor("whee"), OverlayGuineaPig);
  assert.equal(OverlayGround.tricksFor("turtle"), OverlayTurtle);
  assert.equal(OverlayGround.tricksFor("ink"), OverlayTurtle);
  assert.equal(OverlayGround.tricksFor("goldfish"), OverlayGoldfish);
  assert.equal(OverlayGround.tricksFor("coin"), OverlayGoldfish);
  assert.equal(OverlayGround.tricksFor("budgie"), OverlayBudgie);
  assert.equal(OverlayGround.tricksFor("echo"), OverlayBudgie);
  assert.equal(OverlayGround.tricksFor("fox"), OverlayFox);
  assert.equal(OverlayGround.tricksFor("rue"), OverlayFox);
  assert.equal(OverlayGround.tricksFor("penguin"), OverlayPenguin);
  assert.equal(OverlayGround.tricksFor("peck"), OverlayPenguin);
  assert.equal(OverlayGround.tricksFor("parrot"), OverlayParrot);
  assert.equal(OverlayGround.tricksFor("quill"), OverlayParrot);
  assert.equal(OverlayGround.tricksFor("ferret"), Overlay);
  assert.equal(OverlayGround.tricksFor("wick"), Overlay);
  assert.equal(OverlayGround.tricksFor("hedgehog"), OverlayHedgehog);
  assert.equal(OverlayGround.tricksFor("burr"), OverlayHedgehog);
  assert.equal(OverlayGround.tricksFor("chinchilla"), OverlayChinchilla);
  assert.equal(OverlayGround.tricksFor("floss"), OverlayChinchilla);
  assert.equal(OverlayGround.tricksFor("axolotl"), OverlayAxolotl);
  assert.equal(OverlayGround.tricksFor("bloom"), OverlayAxolotl);
  assert.equal(OverlayGround.tricksFor("toucan"), OverlayToucan);
  assert.equal(OverlayGround.tricksFor("keel"), OverlayToucan);
  assert.equal(OverlayGround.tricksFor("iguana"), OverlayIguana);
  assert.equal(OverlayGround.tricksFor("sol"), OverlayIguana);
  assert.equal(OverlayGround.tricksFor("dragon"), OverlayDragon);
  assert.equal(OverlayGround.tricksFor("vesper"), OverlayDragon);
  assert.equal(OverlayGround.wantsThankYou("red_panda"), true);
  assert.equal(OverlayGround.wantsThankYou("relay_dragon"), true);
  assert.equal(OverlayGround.wantsThankYou("fuse_dragon"), true);
  assert.equal(OverlayGround.wantsThankYou("ground_dragon"), true);
  assert.equal(OverlayGround.wantsThankYou("cat"), true);
  assert.equal(OverlayGround.wantsThankYou("miso"), true);
  assert.equal(OverlayGround.wantsThankYou("dog"), true);
  assert.equal(OverlayGround.wantsThankYou("pip"), true);
  assert.equal(OverlayGround.wantsThankYou("rabbit"), true);
  assert.equal(OverlayGround.wantsThankYou("thimble"), true);
  assert.equal(OverlayGround.wantsThankYou("hamster"), true);
  assert.equal(OverlayGround.wantsThankYou("clip"), true);
  assert.equal(OverlayGround.wantsThankYou("guinea_pig"), true);
  assert.equal(OverlayGround.wantsThankYou("whee"), true);
  assert.equal(OverlayGround.wantsThankYou("turtle"), true);
  assert.equal(OverlayGround.wantsThankYou("ink"), true);
  assert.equal(OverlayGround.wantsThankYou("goldfish"), true);
  assert.equal(OverlayGround.wantsThankYou("coin"), true);
  assert.equal(OverlayGround.wantsThankYou("budgie"), true);
  assert.equal(OverlayGround.wantsThankYou("echo"), true);
  assert.equal(OverlayGround.wantsThankYou("fox"), true);
  assert.equal(OverlayGround.wantsThankYou("rue"), true);
  assert.equal(OverlayGround.wantsThankYou("penguin"), true);
  assert.equal(OverlayGround.wantsThankYou("peck"), true);
  assert.equal(OverlayGround.wantsThankYou("parrot"), true);
  assert.equal(OverlayGround.wantsThankYou("quill"), true);
  assert.equal(OverlayGround.wantsThankYou("ferret"), true);
  assert.equal(OverlayGround.wantsThankYou("wick"), true);
  assert.equal(OverlayGround.wantsThankYou("hedgehog"), true);
  assert.equal(OverlayGround.wantsThankYou("burr"), true);
  assert.equal(OverlayGround.wantsThankYou("chinchilla"), true);
  assert.equal(OverlayGround.wantsThankYou("floss"), true);
  assert.equal(OverlayGround.wantsThankYou("axolotl"), true);
  assert.equal(OverlayGround.wantsThankYou("bloom"), true);
  assert.equal(OverlayGround.wantsThankYou("toucan"), true);
  assert.equal(OverlayGround.wantsThankYou("keel"), true);
  assert.equal(OverlayGround.wantsThankYou("iguana"), true);
  assert.equal(OverlayGround.wantsThankYou("sol"), true);
  assert.equal(OverlayGround.wantsThankYou("dragon"), true);
  assert.equal(OverlayGround.wantsThankYou("vesper"), true);
  assert.equal(OverlayGround.sleepHoldFrame("red_panda", 4), 1);
  assert.equal(OverlayGround.sleepHoldFrame("dog", 4), null);
  assert.equal(OverlayGround.sleepHoldFrame("cat", 4), null);
  assert.equal(OverlayGround.sleepHoldFrame("rabbit", 4), null);
  assert.equal(OverlayGround.sleepHoldFrame("hamster", 4), null);
  assert.equal(OverlayGround.sleepHoldFrame("guinea_pig", 4), null);
  assert.equal(OverlayGround.sleepHoldFrame("turtle", 4), null);
  assert.equal(OverlayGround.sleepHoldFrame("goldfish", 4), null);
  assert.equal(OverlayGround.sleepHoldFrame("budgie", 4), null);
  assert.equal(OverlayGround.sleepHoldFrame("fox", 4), null);
  assert.equal(OverlayGround.sleepHoldFrame("penguin", 4), null);
  assert.equal(OverlayGround.sleepHoldFrame("parrot", 4), null);
  assert.equal(OverlayGround.sleepHoldFrame("ferret", 4), null);
  assert.equal(OverlayGround.sleepHoldFrame("hedgehog", 4), null);
  assert.equal(OverlayGround.sleepHoldFrame("chinchilla", 4), null);
  assert.equal(OverlayGround.sleepHoldFrame("axolotl", 4), null);
  assert.equal(OverlayGround.sleepHoldFrame("toucan", 4), null);
  assert.equal(OverlayGround.sleepHoldFrame("iguana", 4), null);
  assert.equal(OverlayGround.sleepHoldFrame("dragon", 4), null);
});

test("ultra-polish: Wick tube/romp/corkscrew/slink lifts are Rui-visible (not micro idle-gen)", () => {
  const ex = T.beginTrick("tube", 80, 1);
  const mid = T.stepTrick(ex, 5, { cmd: "idle" });
  assert.ok(Math.abs(mid.rot) > 4, `tube mid rot ${mid.rot}`);
  assert.ok(Math.abs(mid.lift) > 2, `tube mid lift ${mid.lift}`);
  const ro = T.beginTrick("romp", 80, 1);
  const r2 = T.stepTrick(ro, T.DUR.romp * 0.35, { cmd: "idle" });
  assert.ok(r2.lift > 6 || Math.abs(r2.rot) > 4, `romp mid lift/rot ${r2.lift}/${r2.rot}`);
  const ck = T.beginTrick("corkscrew", 80, 1);
  const c2 = T.stepTrick(ck, T.DUR.corkscrew * 0.4, { cmd: "idle" });
  assert.ok(c2.lift > 6 || Math.abs(c2.rot) > 6, `corkscrew mid lift/rot ${c2.lift}/${c2.rot}`);
  const sl = T.beginTrick("slink", 80, 1);
  const s2 = T.stepTrick(sl, T.DUR.slink * 0.4, { cmd: "idle" });
  assert.ok(s2.lift < -2 || Math.abs(s2.rot) > 6, `slink mid lift/rot ${s2.lift}/${s2.rot}`);
  assert.ok(Overlay.corkscrewPose && Overlay.slinkPose);
  assert.deepEqual([...T.TRICKS], [...Overlay.TRICKS]);
  assert.equal(T.DUR.corkscrew, Overlay.DUR.corkscrew);
  assert.equal(T.DUR.slink, Overlay.DUR.slink);
  assert.equal(T.TUBE_HOLD, Overlay.TUBE_HOLD);
  assert.equal(T.TUBE_HOLD, 11.2);
  assert.equal(T.RELEASE_S, 1.18);
  assert.ok(T.nextTrickWait(true, 0, "tube") > 39);
});

test("notes: Wick Rui-dense ultra (TUBE_HOLD=11.2); next house-order densify leftover after early house guests: Burr / hedgehog then Floss / chinchilla", () => {
  assert.deepEqual([...T.TRICKS], ["tube", "romp", "steal", "puff", "noodle", "corkscrew", "slink"]);
  assert.equal(T.TRICKS.includes("thread"), false);
  assert.equal(Overlay.TRICKS.includes("corkscrew"), true);
  assert.equal(Overlay.TRICKS.includes("slink"), true);
  assert.equal(T.TRICKS.includes("dance"), false);
  assert.equal(T.TRICKS.includes("stash"), false);
});
