import assert from "node:assert/strict";
import { createRequire } from "node:module";
import { dirname, join } from "node:path";
import { test } from "node:test";
import { fileURLToPath, pathToFileURL } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const T = await import(pathToFileURL(join(root, "src/lib/pets/fuse-tricks.ts")).href);
const Rui = await import(pathToFileURL(join(root, "src/lib/pets/rui-tricks.ts")).href);
const Relay = await import(pathToFileURL(join(root, "src/lib/pets/relay-tricks.ts")).href);
const Overlay = createRequire(import.meta.url)(join(root, "../desktop/renderer/fuse-tricks.js"));
const OverlayGround = createRequire(import.meta.url)(join(root, "../desktop/renderer/ground-tricks.js"));
const OverlayRui = createRequire(import.meta.url)(join(root, "../desktop/renderer/rui-tricks.js"));
const OverlayRelay = createRequire(import.meta.url)(join(root, "../desktop/renderer/relay-tricks.js"));

test("Fuse tricks start only on idle ground", () => {
  assert.deepEqual([...T.TRICKS], ["seat", "current", "blow", "reseat"]);
  assert.equal(T.canStart({ asleep: false, hidden: false, leaving: false, cmd: "idle" }), true);
  assert.equal(T.canStart({ asleep: true, hidden: false, leaving: false, cmd: "idle" }), false);
  assert.equal(T.canStart({ asleep: false, hidden: true, leaving: false, cmd: "idle" }), false);
  assert.equal(T.canStart({ asleep: false, hidden: false, leaving: false, cmd: "sleep" }), false);
  assert.equal(T.canStart({ asleep: false, hidden: false, leaving: false, cmd: "seek" }), false);
  assert.equal(T.canStart({ asleep: false, hidden: false, leaving: false, cmd: "idle", windowPlay: true }), false);
  assert.equal(T.canStart({ asleep: false, hidden: false, leaving: false, cmd: "idle", card: true }), false);
  assert.equal(T.shouldAbort({ asleep: true, hidden: false, leaving: false, cmd: "idle" }), true);
  assert.equal(T.shouldAbort({ asleep: false, hidden: false, leaving: false, cmd: "idle", card: true }), true);
  assert.equal(T.shouldAbort({ asleep: false, hidden: false, leaving: false, cmd: "idle" }), false);
  assert.equal(T.pickTrick(0.99, true), "current");
  assert.notEqual(T.pickTrick(0.3, false, "current"), "current");
  assert.equal(Overlay.TRICK_KEY, "fuse_dragon");
  assert.equal(T.sleepHoldFrame("fuse_dragon", 4), null);
  assert.equal(T.TRICKS.includes("somersault"), false);
  assert.equal(T.TRICKS.includes("click"), false);
  assert.equal(T.TRICKS.includes("latch"), false);
  assert.equal(T.TRICKS.includes("arc"), false);
});

test("seat/current/blow/reseat are cartridge-true, not Rui or Relay clones", () => {
  const ground = { asleep: false, hidden: false, leaving: false, cmd: "idle" };
  const seat = T.beginTrick("seat", 80, 1);
  assert.equal(seat.anim, "sit");
  const seatMid = T.stepTrick(seat, 0.1, ground);
  assert.ok(seatMid.lift > 0 || Math.abs(seatMid.rot) > 0);
  const current = T.beginTrick("current", 80, 1);
  assert.equal(current.anim, "sit");
  assert.equal(current.phase, "hold");
  const held = T.stepTrick(current, 5, ground);
  assert.equal(held.phase, "hold");
  assert.equal(held.anim, "sit");
  assert.equal(held.rot, 0);
  assert.equal(held.lift, 0);
  const release = T.stepTrick(current, T.CURRENT_HOLD + 0.2, ground);
  assert.equal(release.phase, "release");
  assert.equal(release.anim, "sit");
  const doneCurrent = T.stepTrick(current, T.DUR.current + 0.1, ground);
  assert.equal(doneCurrent.phase, "done");
  assert.ok(T.nextTrickWait(true, 0, "current") > T.nextTrickWait(true, 0, "seat"));
  const blow = T.beginTrick("blow", 80, 1);
  assert.equal(blow.anim, "play");
  const blowMid = T.stepTrick(blow, 0.12, ground);
  assert.ok(blowMid.lift > 8);
  assert.ok(Math.abs(blowMid.rot) > 8);
  const blowDone = T.stepTrick(blow, 1.1, ground);
  assert.equal(blowDone.phase, "done");
  const reseat = T.beginTrick("reseat", 80, 1);
  assert.equal(reseat.anim, "walk");
  const reseatMid = T.stepTrick(reseat, 0.4, ground);
  assert.equal(reseatMid.anim, "walk");
  assert.ok(Math.abs(reseatMid.x - 80) > 4);
  const reseatSit = T.stepTrick(reseat, 1.3, ground);
  assert.equal(reseatSit.anim, "sit");
  const aborted = T.stepTrick(held, 0.1, { asleep: true, cmd: "sleep" });
  assert.equal(aborted.phase, "done");
  assert.equal(Relay.TRICKS.includes("seat"), false);
  assert.equal(Rui.TRICKS.includes("blow"), false);
});

test("Fuse feed-happy is its own sit: warm/snap/pulse, and two feeds are not the same", () => {
  assert.deepEqual([...T.HAPPY], ["warm", "snap", "pulse"]);
  assert.equal(T.HAPPY.includes("spark"), false);
  assert.equal(T.HAPPY.includes("twirl"), false);
  assert.equal(T.HAPPY.includes("toggle"), false);
  assert.equal(T.pickHappy("warm", 0), "snap");
  assert.notEqual(T.pickHappy("warm", 0.9), "warm");
  assert.equal(Overlay.pickHappy("snap", 0) !== "snap", true);
  assert.equal(T.happyCanStart({ asleep: false, hidden: false, leaving: false, cmd: "idle" }), true);
  assert.equal(T.happyCanStart({ asleep: false, hidden: false, leaving: false, cmd: "idle", card: true }), true);
  assert.equal(T.happyCanStart({ asleep: true, hidden: false, leaving: false, cmd: "idle" }), false);
  assert.equal(T.happyShouldAbort({ cmd: "sleep" }), true);
  assert.equal(T.happyShouldAbort({ cmd: "hide" }), true);
  assert.equal(T.happyShouldAbort({ card: true, cmd: "idle" }), false);
  const warm = T.beginHappy("warm", 80, 1);
  assert.equal(warm.anim, "play");
  const warmMid = T.stepHappy(warm, 0.4, { cmd: "idle" });
  assert.ok(warmMid.lift > 2 || Math.abs(warmMid.rot) > 2);
  assert.notEqual(warmMid.phase, "done");
  const snap = T.beginHappy("snap", 80, 1);
  assert.equal(snap.anim, "sit");
  const pulse = T.beginHappy("pulse", 80, 1);
  assert.equal(pulse.anim, "talk");
  const done = T.stepHappy(warm, T.HAPPY_DUR.warm + 0.1, { cmd: "idle" });
  assert.equal(done.phase, "done");
  const aborted = T.stepHappy(warmMid, 0.1, { asleep: true, cmd: "sleep" });
  assert.equal(aborted.phase, "done");
  assert.equal(aborted.abort, true);
  assert.equal(T.wantsThankYou("fuse_dragon"), true);
  assert.equal(T.wantsThankYou("fuse"), true);
  assert.equal(T.wantsThankYou("red_panda"), false);
  assert.equal(T.wantsThankYou("relay_dragon"), false);
  const thanks = T.startThankYou("fuse_dragon", "warm", 80, 1, { cmd: "idle", card: true, windowPlay: true });
  assert.ok(thanks);
  assert.notEqual(thanks.kind, "warm");
  assert.ok(thanks.happy.lift === 0);
  assert.notEqual(thanks.happy.anim, "eat");
  assert.notEqual(thanks.happy.anim, "idle");
  const thanksMid = T.stepHappy(thanks.happy, 0.35, { cmd: "idle", card: true });
  assert.ok(thanksMid.lift > 0 || Math.abs(thanksMid.rot) > 2, "a thank-you lifts or moves");
  const blocked = T.startThankYou("fuse_dragon", "snap", 80, 1, { asleep: true, cmd: "idle" });
  assert.equal(blocked, null);
  const other = T.startThankYou("gauss_dragon", null, 80, 1, { cmd: "idle" });
  assert.equal(other, null);
  const second = T.startThankYou("fuse_dragon", thanks.kind, 80, 1, { cmd: "idle", card: true });
  assert.ok(second);
  assert.notEqual(second.kind, thanks.kind);
});

test("ground registry keeps Rui gated, Relay + Fuse selectable", () => {
  assert.equal(Rui.TRICK_KEY, "red_panda");
  assert.equal(Relay.TRICK_KEY, "relay_dragon");
  assert.equal(T.TRICK_KEY, "fuse_dragon");
  assert.deepEqual([...Rui.TRICKS], ["somersault", "lie", "scratch", "wave", "dance"]);
  assert.deepEqual([...Relay.TRICKS], ["click", "latch", "arc", "buzz", "switch"]);
  assert.equal(Rui.wantsThankYou("fuse_dragon"), false);
  assert.equal(Relay.wantsThankYou("fuse_dragon"), false);
  assert.equal(T.wantsThankYou("fuse_dragon"), true);
  assert.equal(T.wantsThankYou("red_panda"), false);
  assert.equal(T.wantsThankYou("relay_dragon"), false);
  assert.equal(Rui.sleepHoldFrame("red_panda", 4), 1);
  assert.equal(T.sleepHoldFrame("fuse_dragon", 4), null);
  globalThis.PetRuiTricks = OverlayRui;
  globalThis.PetRelayTricks = OverlayRelay;
  globalThis.PetFuseTricks = Overlay;
  assert.equal(OverlayGround.tricksFor("red_panda"), OverlayRui);
  assert.equal(OverlayGround.tricksFor("rui"), OverlayRui);
  assert.equal(OverlayGround.tricksFor("relay_dragon"), OverlayRelay);
  assert.equal(OverlayGround.tricksFor("relay"), OverlayRelay);
  assert.equal(OverlayGround.tricksFor("fuse_dragon"), Overlay);
  assert.equal(OverlayGround.tricksFor("fuse"), Overlay);
  assert.equal(OverlayGround.tricksFor("ground_dragon"), null);
  assert.equal(OverlayGround.tricksFor("cat"), null);
  assert.equal(OverlayGround.wantsThankYou("red_panda"), true);
  assert.equal(OverlayGround.wantsThankYou("relay_dragon"), true);
  assert.equal(OverlayGround.wantsThankYou("fuse_dragon"), true);
  assert.equal(OverlayGround.wantsThankYou("ground_dragon"), false);
  assert.equal(OverlayGround.sleepHoldFrame("red_panda", 4), 1);
  assert.equal(OverlayGround.sleepHoldFrame("relay_dragon"), null);
  assert.equal(OverlayGround.sleepHoldFrame("fuse_dragon", 4), null);
});
