import assert from "node:assert/strict";
import { createRequire } from "node:module";
import { dirname, join } from "node:path";
import { test } from "node:test";
import { fileURLToPath, pathToFileURL } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const T = await import(pathToFileURL(join(root, "src/lib/pets/green-tree-python-tricks.ts")).href);
const BallPython = await import(pathToFileURL(join(root, "src/lib/pets/ball-python-tricks.ts")).href);
const CornSnake = await import(pathToFileURL(join(root, "src/lib/pets/corn-snake-tricks.ts")).href);
const Kingsnake = await import(pathToFileURL(join(root, "src/lib/pets/kingsnake-tricks.ts")).href);
const Phoenix = await import(pathToFileURL(join(root, "src/lib/pets/phoenix-tricks.ts")).href);
const Dragon = await import(pathToFileURL(join(root, "src/lib/pets/dragon-tricks.ts")).href);
const Rui = await import(pathToFileURL(join(root, "src/lib/pets/rui-tricks.ts")).href);
const Relay = await import(pathToFileURL(join(root, "src/lib/pets/relay-tricks.ts")).href);
const Fuse = await import(pathToFileURL(join(root, "src/lib/pets/fuse-tricks.ts")).href);
const Earth = await import(pathToFileURL(join(root, "src/lib/pets/earth-tricks.ts")).href);
const Cat = await import(pathToFileURL(join(root, "src/lib/pets/cat-tricks.ts")).href);
const Dog = await import(pathToFileURL(join(root, "src/lib/pets/dog-tricks.ts")).href);
const Rabbit = await import(pathToFileURL(join(root, "src/lib/pets/rabbit-tricks.ts")).href);
const Hamster = await import(pathToFileURL(join(root, "src/lib/pets/hamster-tricks.ts")).href);
const GuineaPig = await import(pathToFileURL(join(root, "src/lib/pets/guinea-pig-tricks.ts")).href);
const Turtle = await import(pathToFileURL(join(root, "src/lib/pets/turtle-tricks.ts")).href);
const Goldfish = await import(pathToFileURL(join(root, "src/lib/pets/goldfish-tricks.ts")).href);
const Budgie = await import(pathToFileURL(join(root, "src/lib/pets/budgie-tricks.ts")).href);
const Fox = await import(pathToFileURL(join(root, "src/lib/pets/fox-tricks.ts")).href);
const Penguin = await import(pathToFileURL(join(root, "src/lib/pets/penguin-tricks.ts")).href);
const Parrot = await import(pathToFileURL(join(root, "src/lib/pets/parrot-tricks.ts")).href);
const Ferret = await import(pathToFileURL(join(root, "src/lib/pets/ferret-tricks.ts")).href);
const Hedgehog = await import(pathToFileURL(join(root, "src/lib/pets/hedgehog-tricks.ts")).href);
const Chinchilla = await import(pathToFileURL(join(root, "src/lib/pets/chinchilla-tricks.ts")).href);
const Axolotl = await import(pathToFileURL(join(root, "src/lib/pets/axolotl-tricks.ts")).href);
const Toucan = await import(pathToFileURL(join(root, "src/lib/pets/toucan-tricks.ts")).href);
const Iguana = await import(pathToFileURL(join(root, "src/lib/pets/iguana-tricks.ts")).href);
const Overlay = createRequire(import.meta.url)(join(root, "../desktop/renderer/green-tree-python-tricks.js"));
const OverlayBallPython = createRequire(import.meta.url)(join(root, "../desktop/renderer/ball-python-tricks.js"));
const OverlayCornSnake = createRequire(import.meta.url)(join(root, "../desktop/renderer/corn-snake-tricks.js"));
const OverlayKingsnake = createRequire(import.meta.url)(join(root, "../desktop/renderer/kingsnake-tricks.js"));
const OverlayPhoenix = createRequire(import.meta.url)(join(root, "../desktop/renderer/phoenix-tricks.js"));
const OverlayGround = createRequire(import.meta.url)(join(root, "../desktop/renderer/ground-tricks.js"));
const OverlayRui = createRequire(import.meta.url)(join(root, "../desktop/renderer/rui-tricks.js"));
const OverlayRelay = createRequire(import.meta.url)(join(root, "../desktop/renderer/relay-tricks.js"));
const OverlayFuse = createRequire(import.meta.url)(join(root, "../desktop/renderer/fuse-tricks.js"));
const OverlayEarth = createRequire(import.meta.url)(join(root, "../desktop/renderer/earth-tricks.js"));
const OverlayCat = createRequire(import.meta.url)(join(root, "../desktop/renderer/cat-tricks.js"));
const OverlayDog = createRequire(import.meta.url)(join(root, "../desktop/renderer/dog-tricks.js"));
const OverlayRabbit = createRequire(import.meta.url)(join(root, "../desktop/renderer/rabbit-tricks.js"));
const OverlayHamster = createRequire(import.meta.url)(join(root, "../desktop/renderer/hamster-tricks.js"));
const OverlayGuineaPig = createRequire(import.meta.url)(join(root, "../desktop/renderer/guinea-pig-tricks.js"));
const OverlayTurtle = createRequire(import.meta.url)(join(root, "../desktop/renderer/turtle-tricks.js"));
const OverlayGoldfish = createRequire(import.meta.url)(join(root, "../desktop/renderer/goldfish-tricks.js"));
const OverlayBudgie = createRequire(import.meta.url)(join(root, "../desktop/renderer/budgie-tricks.js"));
const OverlayFox = createRequire(import.meta.url)(join(root, "../desktop/renderer/fox-tricks.js"));
const OverlayPenguin = createRequire(import.meta.url)(join(root, "../desktop/renderer/penguin-tricks.js"));
const OverlayParrot = createRequire(import.meta.url)(join(root, "../desktop/renderer/parrot-tricks.js"));
const OverlayFerret = createRequire(import.meta.url)(join(root, "../desktop/renderer/ferret-tricks.js"));
const OverlayHedgehog = createRequire(import.meta.url)(join(root, "../desktop/renderer/hedgehog-tricks.js"));
const OverlayChinchilla = createRequire(import.meta.url)(join(root, "../desktop/renderer/chinchilla-tricks.js"));
const OverlayAxolotl = createRequire(import.meta.url)(join(root, "../desktop/renderer/axolotl-tricks.js"));
const OverlayToucan = createRequire(import.meta.url)(join(root, "../desktop/renderer/toucan-tricks.js"));
const OverlayIguana = createRequire(import.meta.url)(join(root, "../desktop/renderer/iguana-tricks.js"));
const OverlayDragon = createRequire(import.meta.url)(join(root, "../desktop/renderer/dragon-tricks.js"));


test("Jade tricks start only on idle ground", () => {
  assert.deepEqual([...BallPython.TRICKS], ["orb", "nook", "taste", "inch", "unroll", "loom", "weave"]);
  assert.deepEqual([...Kingsnake.TRICKS], ["stripe", "audit", "verdict", "plumb", "raid", "band", "drawer"]);
  assert.deepEqual([...T.TRICKS], ["bracelet", "sway", "jewel", "heat", "bough", "liana", "arbor"]);
  assert.equal(T.canStart({ asleep: false, hidden: false, leaving: false, cmd: "idle" }), true);
  assert.equal(T.canStart({ asleep: true, hidden: false, leaving: false, cmd: "idle" }), false);
  assert.equal(T.canStart({ asleep: false, hidden: true, leaving: false, cmd: "idle" }), false);
  assert.equal(T.canStart({ asleep: false, hidden: false, leaving: false, cmd: "sleep" }), false);
  assert.equal(T.canStart({ asleep: false, hidden: false, leaving: false, cmd: "seek" }), false);
  assert.equal(T.canStart({ asleep: false, hidden: false, leaving: false, cmd: "idle", windowPlay: true }), false);
  assert.equal(T.canStart({ asleep: false, hidden: false, leaving: false, cmd: "idle", card: true }), false);
  assert.equal(T.shouldAbort({ asleep: true, hidden: false, leaving: false, cmd: "idle" }), true);
  assert.equal(T.shouldAbort({ asleep: false, hidden: false, leaving: false, cmd: "idle", card: true }), true);
  assert.equal(T.shouldAbort({ asleep: false, hidden: false, leaving: false, cmd: "idle" }), false);
  assert.equal(T.pickTrick(0.99, true), "bracelet");
  assert.notEqual(T.pickTrick(0.3, false, "bracelet"), "orb");
  assert.notEqual(T.pickTrick(0.3, false, "bracelet"), "scribble");
  assert.notEqual(T.pickTrick(0.3, false, "bracelet"), "stripe");
  assert.equal(Overlay.TRICK_KEY, "green_tree_python");
  assert.equal(T.sleepHoldFrame("green_tree_python", 4), null);
  assert.equal(T.TRICKS.includes("saddle"), false);
  assert.equal(T.TRICKS.includes("drape"), false);
  assert.equal(T.TRICKS.includes("write"), false);
  assert.equal(T.TRICKS.includes("bun"), false);
  assert.equal(T.TRICKS.includes("orb"), false);
  assert.equal(T.TRICKS.includes("nook"), false);
  assert.equal(T.TRICKS.includes("taste"), false);
  assert.equal(T.TRICKS.includes("inch"), false);
  assert.equal(T.TRICKS.includes("unroll"), false);
  assert.equal(T.TRICKS.includes("thread"), false);
  assert.equal(T.TRICKS.includes("dart"), false);
  assert.equal(T.TRICKS.includes("noodle"), false);
  assert.equal(T.TRICKS.includes("flick"), false);
  assert.equal(T.TRICKS.includes("curl"), false);
  assert.equal(T.TRICKS.includes("coil"), false);
  assert.equal(T.TRICKS.includes("ball"), false);
  assert.equal(T.TRICKS.includes("loop"), false);
  assert.equal(T.TRICKS.includes("perch"), false);
  assert.equal(T.TRICKS.includes("stripe"), false);
  assert.equal(T.TRICKS.includes("verdict"), false);
});

test("bracelet/sway/jewel/heat/bough/liana/arbor are house-green-tree-python-true, not copies of prior guests", () => {
  const ground = { asleep: false, hidden: false, leaving: false, cmd: "idle" };
  const bracelet = T.beginTrick("bracelet", 80, 1);
  assert.equal(bracelet.anim, "sit");
  assert.equal(bracelet.phase, "hold");
  const held = T.stepTrick(bracelet, 5, ground);
  assert.equal(held.phase, "hold");
  assert.equal(held.anim, "sit");
  assert.ok(held.rot !== 0 || Math.abs(held.lift) > 0.5);
  const release = T.stepTrick(bracelet, T.BRACELET_HOLD + 0.2, ground);
  assert.equal(release.phase, "release");
  assert.equal(release.anim, "sit");
  const doneBracelet = T.stepTrick(bracelet, T.DUR.bracelet + 0.1, ground);
  assert.equal(doneBracelet.phase, "done");
  assert.ok(T.nextTrickWait(true, 0, "bracelet") > T.nextTrickWait(true, 0, "jewel"));
  const jewel = T.beginTrick("jewel", 80, 1);
  assert.equal(jewel.anim, "sit");
  const jewelMid = T.stepTrick(jewel, 0.55, ground);
  assert.ok(Math.abs(jewelMid.lift) > 0.1 || Math.abs(jewelMid.rot) > 1);
  const heat = T.beginTrick("heat", 80, 1);
  assert.equal(heat.anim, "talk");
  const heatMid = T.stepTrick(heat, 0.5, ground);
  assert.ok(Math.abs(heatMid.lift) > 0.3 || Math.abs(heatMid.rot) > 1);
  const sway = T.beginTrick("sway", 80, 1);
  assert.equal(sway.anim, "play");
  const swayMid = T.stepTrick(sway, 0.5, ground);
  assert.ok(Math.abs(swayMid.lift) > 0.3 || Math.abs(swayMid.rot) > 1 || Math.abs(swayMid.x - 80) > 0.5);
  const bough = T.beginTrick("bough", 80, 1);
  assert.equal(bough.anim, "play");
  const boughMid = T.stepTrick(bough, 0.4, ground);
  assert.ok(Math.abs(boughMid.lift) > 0.2 || Math.abs(boughMid.rot) > 1);
  const boughDone = T.stepTrick(bough, T.DUR.bough + 0.1, ground);
  assert.equal(boughDone.phase, "done");
  const liana = T.beginTrick("liana", 80, 1);
  assert.equal(liana.anim, "play");
  const lianaMid = T.stepTrick(liana, T.DUR.liana * 0.45, ground);
  assert.ok(Math.abs(lianaMid.lift) > 2 || Math.abs(lianaMid.rot) > 4 || Math.abs(lianaMid.x - 80) > 1);
  const arbor = T.beginTrick("arbor", 80, 1);
  assert.equal(arbor.anim, "sit");
  const arborMid = T.stepTrick(arbor, T.DUR.arbor * 0.4, ground);
  assert.ok(arborMid.lift > 4 || Math.abs(arborMid.rot) > 6);
  assert.equal(T.TRICKS.includes("saddle"), false);
  assert.equal(T.TRICKS.includes("drape"), false);
  assert.equal(T.TRICKS.includes("moss"), false);
  assert.equal(T.TRICKS.includes("gleam"), false);
  assert.equal(T.TRICKS.includes("band"), false);
  assert.equal(T.TRICKS.includes("drawer"), false);
  const aborted = T.stepTrick(held, 0.1, { asleep: true, cmd: "sleep" });
  assert.equal(aborted.phase, "done");
  for (const mod of [Rui, Cat, Dog, Rabbit, Hamster, GuineaPig, Turtle, Goldfish, Budgie, Fox, Penguin, Parrot, Ferret, Hedgehog, Chinchilla, Axolotl, Toucan, Iguana, Dragon, Phoenix, BallPython, CornSnake, Kingsnake, Relay, Fuse, Earth]) {
    assert.equal(mod.TRICKS.includes("bracelet"), false);
    assert.equal(mod.TRICKS.includes("sway"), false);
    assert.equal(mod.TRICKS.includes("jewel"), false);
    assert.equal(mod.TRICKS.includes("heat"), false);
    assert.equal(mod.TRICKS.includes("bough"), false);
    assert.equal(mod.TRICKS.includes("liana"), false);
    assert.equal(mod.TRICKS.includes("arbor"), false);
  }
  assert.deepEqual([...BallPython.TRICKS], ["orb", "nook", "taste", "inch", "unroll", "loom", "weave"]);
  assert.deepEqual([...CornSnake.TRICKS], ["scribble", "gap", "comma", "probe", "canyon", "blotter", "pencil"]);
  assert.deepEqual([...Kingsnake.TRICKS], ["stripe", "audit", "verdict", "plumb", "raid", "band", "drawer"]);
  assert.deepEqual([...Dragon.TRICKS], ["sprawl", "guard", "smolder", "claim", "fold", "ruff", "scrape"]);
  assert.deepEqual([...Phoenix.TRICKS], ["cinder", "blaze", "shed", "lift", "return", "reignite", "hearth"]);
  assert.equal(T.TRICKS.includes("saddle"), false);
  assert.equal(T.TRICKS.includes("write"), false);
  assert.equal(Parrot.TRICKS.includes("flash"), true);
});

test("Jade feed-happy is its own sit: pendant/treaty/emerald, and two feeds are not the same", () => {
  assert.deepEqual([...T.HAPPY], ["pendant", "treaty", "emerald"]);
  assert.equal(T.HAPPY.includes("savor"), false);
  assert.equal(T.HAPPY.includes("nestle"), false);
  assert.equal(T.HAPPY.includes("center"), false);
  assert.equal(T.HAPPY.includes("settle"), false);
  assert.equal(T.HAPPY.includes("shine"), false);
  assert.equal(T.HAPPY.includes("purr"), false);
  assert.equal(T.HAPPY.includes("tribute"), false);
  assert.equal(T.HAPPY.includes("clause"), false);
  assert.equal(T.pickHappy("pendant", 0), "treaty");
  assert.notEqual(T.pickHappy("pendant", 0.9), "pendant");
  assert.equal(Overlay.pickHappy("treaty", 0) !== "treaty", true);
  assert.equal(T.happyCanStart({ asleep: false, hidden: false, leaving: false, cmd: "idle" }), true);
  assert.equal(T.happyCanStart({ asleep: false, hidden: false, leaving: false, cmd: "idle", card: true }), true);
  assert.equal(T.happyCanStart({ asleep: true, hidden: false, leaving: false, cmd: "idle" }), false);
  assert.equal(T.happyShouldAbort({ cmd: "sleep" }), true);
  assert.equal(T.happyShouldAbort({ cmd: "hide" }), true);
  assert.equal(T.happyShouldAbort({ card: true, cmd: "idle" }), false);
  const pendant = T.beginHappy("pendant", 80, 1);
  assert.equal(pendant.anim, "sit");
  const pendantMid = T.stepHappy(pendant, 0.4, { cmd: "idle" });
  assert.ok(pendantMid.lift !== 0 || Math.abs(pendantMid.rot) > 0.5);
  assert.notEqual(pendantMid.phase, "done");
  const treaty = T.beginHappy("treaty", 80, 1);
  assert.equal(treaty.anim, "talk");
  const treatyMid = T.stepHappy(treaty, 0.3, { cmd: "idle" });
  assert.ok(treatyMid.lift > 0.2 || Math.abs(treatyMid.rot) > 0.5);
  const emeraldH = T.beginHappy("emerald", 80, 1);
  assert.equal(emeraldH.anim, "sit");
  const done = T.stepHappy(pendant, T.HAPPY_DUR.pendant + 0.1, { cmd: "idle" });
  assert.equal(done.phase, "done");
  const aborted = T.stepHappy(treatyMid, 0.1, { asleep: true, cmd: "sleep" });
  assert.equal(aborted.phase, "done");
  assert.equal(aborted.abort, true);
  assert.equal(T.wantsThankYou("green_tree_python"), true);
  assert.equal(T.wantsThankYou("jade"), true);
  assert.equal(T.wantsThankYou("ball_python"), false);
  assert.equal(T.wantsThankYou("nori"), false);
  assert.equal(T.wantsThankYou("kingsnake"), false);
  assert.equal(T.wantsThankYou("phoenix"), false);
  const thanks = T.startThankYou("green_tree_python", "pendant", 80, 1, { cmd: "idle", card: true, windowPlay: true });
  assert.ok(thanks);
  assert.notEqual(thanks.kind, "pendant");
  assert.ok(thanks.happy.lift === 0);
  assert.notEqual(thanks.happy.anim, "eat");
  assert.notEqual(thanks.happy.anim, "idle");
  const thanksMid = T.stepHappy(thanks.happy, 0.35, { cmd: "idle", card: true });
  assert.ok(thanksMid.lift !== 0 || Math.abs(thanksMid.rot) > 0.5, "a thank-you pendants or treaties");
  const blocked = T.startThankYou("green_tree_python", "spice", 80, 1, { asleep: true, cmd: "idle" });
  assert.equal(blocked, null);
  const other = T.startThankYou("kingsnake", null, 80, 1, { cmd: "idle" });
  assert.equal(other, null);
  const second = T.startThankYou("green_tree_python", thanks.kind, 80, 1, { cmd: "idle", card: true });
  assert.ok(second);
  assert.notEqual(second.kind, thanks.kind);
});

test("ground registry keeps prior guests gated; Jade selectable; prior guests still OK", () => {
  assert.equal(Rui.TRICK_KEY, "red_panda");
  assert.equal(BallPython.TRICK_KEY, "ball_python");
  assert.equal(Kingsnake.TRICK_KEY, "kingsnake");
  assert.equal(T.TRICK_KEY, "green_tree_python");
  assert.deepEqual([...Rui.TRICKS], ["somersault", "lie", "scratch", "wave", "dance"]);
  assert.deepEqual([...BallPython.TRICKS], ["orb", "nook", "taste", "inch", "unroll", "loom", "weave"]);
  assert.deepEqual([...CornSnake.TRICKS], ["scribble", "gap", "comma", "probe", "canyon", "blotter", "pencil"]);
  assert.deepEqual([...Kingsnake.TRICKS], ["stripe", "audit", "verdict", "plumb", "raid", "band", "drawer"]);
  assert.deepEqual([...Phoenix.TRICKS], ["cinder", "blaze", "shed", "lift", "return", "reignite", "hearth"]);
  assert.deepEqual([...T.TRICKS], ["bracelet", "sway", "jewel", "heat", "bough", "liana", "arbor"]);
  assert.equal(T.wantsThankYou("green_tree_python"), true);
  assert.equal(T.wantsThankYou("jade"), true);
  assert.equal(BallPython.wantsThankYou("nori"), true);
  assert.equal(Kingsnake.wantsThankYou("bandit"), true);
  assert.equal(Rui.sleepHoldFrame("red_panda", 4), 1);
  assert.equal(T.sleepHoldFrame("green_tree_python", 4), null);
  globalThis.PetRuiTricks = OverlayRui;
  globalThis.PetRelayTricks = OverlayRelay;
  globalThis.PetFuseTricks = OverlayFuse;
  globalThis.PetEarthTricks = OverlayEarth;
  globalThis.PetCatTricks = OverlayCat;
  globalThis.PetDogTricks = OverlayDog;
  globalThis.PetRabbitTricks = OverlayRabbit;
  globalThis.PetHamsterTricks = OverlayHamster;
  globalThis.PetGuineaPigTricks = OverlayGuineaPig;
  globalThis.PetTurtleTricks = OverlayTurtle;
  globalThis.PetGoldfishTricks = OverlayGoldfish;
  globalThis.PetBudgieTricks = OverlayBudgie;
  globalThis.PetFoxTricks = OverlayFox;
  globalThis.PetPenguinTricks = OverlayPenguin;
  globalThis.PetParrotTricks = OverlayParrot;
  globalThis.PetFerretTricks = OverlayFerret;
  globalThis.PetHedgehogTricks = OverlayHedgehog;
  globalThis.PetChinchillaTricks = OverlayChinchilla;
  globalThis.PetAxolotlTricks = OverlayAxolotl;
  globalThis.PetToucanTricks = OverlayToucan;
  globalThis.PetIguanaTricks = OverlayIguana;
  globalThis.PetDragonTricks = OverlayDragon;
  globalThis.PetPhoenixTricks = OverlayPhoenix;
  globalThis.PetBallPythonTricks = OverlayBallPython;
  globalThis.PetCornSnakeTricks = OverlayCornSnake;
  globalThis.PetKingsnakeTricks = OverlayKingsnake;
  globalThis.PetGreenTreePythonTricks = Overlay;
  assert.equal(OverlayGround.tricksFor("red_panda"), OverlayRui);
  assert.equal(OverlayGround.tricksFor("rui"), OverlayRui);
  assert.equal(OverlayGround.tricksFor("relay_dragon"), OverlayRelay);
  assert.equal(OverlayGround.tricksFor("fuse_dragon"), OverlayFuse);
  assert.equal(OverlayGround.tricksFor("ground_dragon"), OverlayEarth);
  assert.equal(OverlayGround.tricksFor("cat"), OverlayCat);
  assert.equal(OverlayGround.tricksFor("miso"), OverlayCat);
  assert.equal(OverlayGround.tricksFor("dog"), OverlayDog);
  assert.equal(OverlayGround.tricksFor("pip"), OverlayDog);
  assert.equal(OverlayGround.tricksFor("rabbit"), OverlayRabbit);
  assert.equal(OverlayGround.tricksFor("thimble"), OverlayRabbit);
  assert.equal(OverlayGround.tricksFor("hamster"), OverlayHamster);
  assert.equal(OverlayGround.tricksFor("clip"), OverlayHamster);
  assert.equal(OverlayGround.tricksFor("guinea_pig"), OverlayGuineaPig);
  assert.equal(OverlayGround.tricksFor("whee"), OverlayGuineaPig);
  assert.equal(OverlayGround.tricksFor("turtle"), OverlayTurtle);
  assert.equal(OverlayGround.tricksFor("ink"), OverlayTurtle);
  assert.equal(OverlayGround.tricksFor("goldfish"), OverlayGoldfish);
  assert.equal(OverlayGround.tricksFor("coin"), OverlayGoldfish);
  assert.equal(OverlayGround.tricksFor("budgie"), OverlayBudgie);
  assert.equal(OverlayGround.tricksFor("echo"), OverlayBudgie);
  assert.equal(OverlayGround.tricksFor("fox"), OverlayFox);
  assert.equal(OverlayGround.tricksFor("rue"), OverlayFox);
  assert.equal(OverlayGround.tricksFor("penguin"), OverlayPenguin);
  assert.equal(OverlayGround.tricksFor("peck"), OverlayPenguin);
  assert.equal(OverlayGround.tricksFor("parrot"), OverlayParrot);
  assert.equal(OverlayGround.tricksFor("quill"), OverlayParrot);
  assert.equal(OverlayGround.tricksFor("ferret"), OverlayFerret);
  assert.equal(OverlayGround.tricksFor("wick"), OverlayFerret);
  assert.equal(OverlayGround.tricksFor("hedgehog"), OverlayHedgehog);
  assert.equal(OverlayGround.tricksFor("burr"), OverlayHedgehog);
  assert.equal(OverlayGround.tricksFor("chinchilla"), OverlayChinchilla);
  assert.equal(OverlayGround.tricksFor("floss"), OverlayChinchilla);
  assert.equal(OverlayGround.tricksFor("axolotl"), OverlayAxolotl);
  assert.equal(OverlayGround.tricksFor("bloom"), OverlayAxolotl);
  assert.equal(OverlayGround.tricksFor("toucan"), OverlayToucan);
  assert.equal(OverlayGround.tricksFor("keel"), OverlayToucan);
  assert.equal(OverlayGround.tricksFor("iguana"), OverlayIguana);
  assert.equal(OverlayGround.tricksFor("sol"), OverlayIguana);
  assert.equal(OverlayGround.tricksFor("dragon"), OverlayDragon);
  assert.equal(OverlayGround.tricksFor("vesper"), OverlayDragon);
  assert.equal(OverlayGround.tricksFor("phoenix"), OverlayPhoenix);
  assert.equal(OverlayGround.tricksFor("ember"), OverlayPhoenix);
  assert.equal(OverlayGround.tricksFor("ball_python"), OverlayBallPython);
  assert.equal(OverlayGround.tricksFor("nori"), OverlayBallPython);
  assert.equal(OverlayGround.tricksFor("corn_snake"), OverlayCornSnake);
  assert.equal(OverlayGround.tricksFor("saffron"), OverlayCornSnake);
  assert.equal(OverlayGround.tricksFor("kingsnake"), OverlayKingsnake);
  assert.equal(OverlayGround.tricksFor("bandit"), OverlayKingsnake);
  assert.equal(OverlayGround.tricksFor("green_tree_python"), Overlay);
  assert.equal(OverlayGround.tricksFor("jade"), Overlay);
  assert.equal(OverlayGround.wantsThankYou("red_panda"), true);
  assert.equal(OverlayGround.wantsThankYou("cat"), true);
  assert.equal(OverlayGround.wantsThankYou("miso"), true);
  assert.equal(OverlayGround.wantsThankYou("dog"), true);
  assert.equal(OverlayGround.wantsThankYou("pip"), true);
  assert.equal(OverlayGround.wantsThankYou("ball_python"), true);
  assert.equal(OverlayGround.wantsThankYou("nori"), true);
  assert.equal(OverlayGround.wantsThankYou("corn_snake"), true);
  assert.equal(OverlayGround.wantsThankYou("saffron"), true);
  assert.equal(OverlayGround.wantsThankYou("kingsnake"), true);
  assert.equal(OverlayGround.wantsThankYou("bandit"), true);
  assert.equal(OverlayGround.wantsThankYou("green_tree_python"), true);
  assert.equal(OverlayGround.wantsThankYou("jade"), true);
  assert.equal(OverlayGround.wantsThankYou("phoenix"), true);
  assert.equal(OverlayGround.wantsThankYou("ember"), true);
  assert.equal(OverlayGround.sleepHoldFrame("red_panda", 4), 1);
  assert.equal(OverlayGround.sleepHoldFrame("ball_python", 4), null);
  assert.equal(OverlayGround.sleepHoldFrame("kingsnake", 4), null);
  assert.equal(OverlayGround.sleepHoldFrame("green_tree_python", 4), null);
  assert.deepEqual([...OverlayBallPython.TRICKS], ["orb", "nook", "taste", "inch", "unroll", "loom", "weave"]);
  assert.deepEqual([...OverlayCornSnake.TRICKS], ["scribble", "gap", "comma", "probe", "canyon", "blotter", "pencil"]);
  assert.deepEqual([...OverlayKingsnake.TRICKS], ["stripe", "audit", "verdict", "plumb", "raid", "band", "drawer"]);
  assert.deepEqual([...Overlay.TRICKS], ["bracelet", "sway", "jewel", "heat", "bough", "liana", "arbor"]);
  assert.equal(Overlay.TRICKS.includes("orb"), false);
  assert.equal(Overlay.TRICKS.includes("write"), false);
  assert.equal(Overlay.TRICKS.includes("saddle"), false);
  assert.equal(Overlay.TRICKS.includes("inspect"), false);
  assert.equal(Overlay.TRICKS.includes("scribble"), false);
  assert.equal(Overlay.TRICKS.includes("stripe"), false);
});


test("ultra-polish: Jade bracelet/sway/jewel/liana/arbor lifts are Rui-visible (not micro idle-gen)", () => {
  const br = T.beginTrick("bracelet", 80, 1);
  const mid = T.stepTrick(br, 5, { cmd: "idle" });
  assert.ok(Math.abs(mid.rot) > 10, `bracelet mid rot ${mid.rot}`);
  assert.ok(Math.abs(mid.lift) > 0.5, `bracelet mid lift ${mid.lift}`);
  const sw = T.beginTrick("sway", 80, 1);
  const s2 = T.stepTrick(sw, T.DUR.sway * 0.4, { cmd: "idle" });
  assert.ok(s2.lift > 4 || Math.abs(s2.rot) > 4, `sway mid lift/rot ${s2.lift}/${s2.rot}`);
  const li = T.beginTrick("liana", 80, 1);
  const l2 = T.stepTrick(li, T.DUR.liana * 0.45, { cmd: "idle" });
  assert.ok(Math.abs(l2.lift) > 2 || Math.abs(l2.rot) > 4 || Math.abs(l2.x - 80) > 1, `liana mid ${l2.lift}/${l2.rot}/${l2.x}`);
  const ar = T.beginTrick("arbor", 80, 1);
  const a2 = T.stepTrick(ar, T.DUR.arbor * 0.4, { cmd: "idle" });
  assert.ok(a2.lift > 4 || Math.abs(a2.rot) > 6, `arbor mid lift/rot ${a2.lift}/${a2.rot}`);
  assert.ok(Overlay.lianaPose && Overlay.arborPose);
  assert.deepEqual([...T.TRICKS], [...Overlay.TRICKS]);
  assert.equal(T.DUR.liana, Overlay.DUR.liana);
  assert.equal(T.DUR.arbor, Overlay.DUR.arbor);
  assert.equal(T.BRACELET_HOLD, Overlay.BRACELET_HOLD);
  assert.equal(T.BRACELET_HOLD, 11.2);
  assert.equal(T.RELEASE_S, 1.18);
  assert.ok(T.nextTrickWait(true, 0, "bracelet") > 39);
  assert.ok(T.nextTrickWait(true, 0, "bracelet") < 80);
  assert.ok(T.nextTrickWait(true, 0, "bracelet") > T.nextTrickWait(true, 0, "jewel"));
  assert.equal(T.HAPPY_DUR.pendant, Overlay.HAPPY_DUR.pendant);
});

test("notes: Jade Rui-dense ultra (BRACELET_HOLD=11.2); Bluff densified; Sash densified; Lula densified; Coral densified; Blush densified; Atlas densified; Cup densified; Sepia densified; Chamber densified; Pulse densified; Ochre densified; Tenant densified; Ledger densified; Anchor densified; Kite densified; Door densified; Felt densified; Vein densified; Fan densified; Mast densified; Disk densified; next leftover Wax / honeycomb", () => {
  assert.deepEqual([...T.TRICKS], ["bracelet", "sway", "jewel", "heat", "bough", "liana", "arbor"]);
  assert.equal(T.TRICK_KEY, "green_tree_python");
  assert.equal(T.wantsThankYou("jade"), true);
  assert.equal(OverlayGround.tricksFor("green_tree_python"), Overlay);
  assert.equal(OverlayGround.tricksFor("jade"), Overlay);
  assert.equal(OverlayGround.wantsThankYou("green_tree_python"), true);
  assert.equal(OverlayGround.wantsThankYou("jade"), true);
  assert.equal(OverlayGround.tricksFor("kingsnake"), OverlayKingsnake);
  assert.equal(OverlayGround.tricksFor("bandit"), OverlayKingsnake);
  assert.equal(OverlayGround.wantsThankYou("kingsnake"), true);
  assert.equal(OverlayGround.wantsThankYou("bandit"), true);
  assert.equal(OverlayGround.tricksFor("corn_snake"), OverlayCornSnake);
  assert.equal(OverlayGround.tricksFor("saffron"), OverlayCornSnake);
  assert.equal(OverlayGround.wantsThankYou("corn_snake"), true);
  assert.equal(OverlayGround.wantsThankYou("saffron"), true);
  assert.equal(OverlayGround.tricksFor("ball_python"), OverlayBallPython);
  assert.equal(OverlayGround.tricksFor("nori"), OverlayBallPython);
  assert.equal(OverlayGround.wantsThankYou("ball_python"), true);
  assert.equal(OverlayGround.wantsThankYou("nori"), true);
  assert.equal(OverlayGround.tricksFor("hognose") == null, true);
  assert.equal(OverlayGround.wantsThankYou("hognose"), false);
  assert.equal(OverlayGround.tricksFor("bluff") == null, true);
});
