import assert from "node:assert/strict";
import { createRequire } from "node:module";
import { dirname, join } from "node:path";
import { test } from "node:test";
import { fileURLToPath, pathToFileURL } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const T = await import(pathToFileURL(join(root, "src/lib/pets/guinea-pig-tricks.ts")).href);
const Rui = await import(pathToFileURL(join(root, "src/lib/pets/rui-tricks.ts")).href);
const Relay = await import(pathToFileURL(join(root, "src/lib/pets/relay-tricks.ts")).href);
const Fuse = await import(pathToFileURL(join(root, "src/lib/pets/fuse-tricks.ts")).href);
const Earth = await import(pathToFileURL(join(root, "src/lib/pets/earth-tricks.ts")).href);
const Cat = await import(pathToFileURL(join(root, "src/lib/pets/cat-tricks.ts")).href);
const Dog = await import(pathToFileURL(join(root, "src/lib/pets/dog-tricks.ts")).href);
const Rabbit = await import(pathToFileURL(join(root, "src/lib/pets/rabbit-tricks.ts")).href);
const Hamster = await import(pathToFileURL(join(root, "src/lib/pets/hamster-tricks.ts")).href);
const Overlay = createRequire(import.meta.url)(join(root, "../desktop/renderer/guinea-pig-tricks.js"));
const OverlayGround = createRequire(import.meta.url)(join(root, "../desktop/renderer/ground-tricks.js"));
const OverlayRui = createRequire(import.meta.url)(join(root, "../desktop/renderer/rui-tricks.js"));
const OverlayRelay = createRequire(import.meta.url)(join(root, "../desktop/renderer/relay-tricks.js"));
const OverlayFuse = createRequire(import.meta.url)(join(root, "../desktop/renderer/fuse-tricks.js"));
const OverlayEarth = createRequire(import.meta.url)(join(root, "../desktop/renderer/earth-tricks.js"));
const OverlayCat = createRequire(import.meta.url)(join(root, "../desktop/renderer/cat-tricks.js"));
const OverlayDog = createRequire(import.meta.url)(join(root, "../desktop/renderer/dog-tricks.js"));
const OverlayRabbit = createRequire(import.meta.url)(join(root, "../desktop/renderer/rabbit-tricks.js"));
const OverlayHamster = createRequire(import.meta.url)(join(root, "../desktop/renderer/hamster-tricks.js"));
const OverlayTurtle = createRequire(import.meta.url)(join(root, "../desktop/renderer/turtle-tricks.js"));

test("Whee tricks start only on idle ground", () => {
  assert.deepEqual([...T.TRICKS], ["popcorn", "rumble", "hay", "potato", "zig", "lookout", "teeth"]);
  assert.equal(T.canStart({ asleep: false, hidden: false, leaving: false, cmd: "idle" }), true);
  assert.equal(T.canStart({ asleep: true, hidden: false, leaving: false, cmd: "idle" }), false);
  assert.equal(T.canStart({ asleep: false, hidden: true, leaving: false, cmd: "idle" }), false);
  assert.equal(T.canStart({ asleep: false, hidden: false, leaving: false, cmd: "sleep" }), false);
  assert.equal(T.canStart({ asleep: false, hidden: false, leaving: false, cmd: "seek" }), false);
  assert.equal(T.canStart({ asleep: false, hidden: false, leaving: false, cmd: "idle", windowPlay: true }), false);
  assert.equal(T.canStart({ asleep: false, hidden: false, leaving: false, cmd: "idle", card: true }), false);
  assert.equal(T.shouldAbort({ asleep: true, hidden: false, leaving: false, cmd: "idle" }), true);
  assert.equal(T.shouldAbort({ asleep: false, hidden: false, leaving: false, cmd: "idle", card: true }), true);
  assert.equal(T.shouldAbort({ asleep: false, hidden: false, leaving: false, cmd: "idle" }), false);
  assert.equal(T.pickTrick(0.99, true), "potato");
  assert.notEqual(T.pickTrick(0.3, false, "potato"), "potato");
  assert.equal(Overlay.TRICK_KEY, "guinea_pig");
  assert.equal(T.sleepHoldFrame("guinea_pig", 4), null);
  assert.equal(T.TRICKS.includes("somersault"), false);
  assert.equal(T.TRICKS.includes("scratch"), false);
  assert.equal(T.TRICKS.includes("loaf"), false);
  assert.equal(T.TRICKS.includes("wait"), false);
  assert.equal(T.TRICKS.includes("bow"), false);
  assert.equal(T.TRICKS.includes("dig"), false);
  assert.equal(T.TRICKS.includes("flop"), false);
  assert.equal(T.TRICKS.includes("nest"), false);
  assert.equal(T.TRICKS.includes("wheek"), false);
  assert.equal(T.TRICKS.includes("scurry"), false);
  assert.equal(T.TRICKS.includes("groom"), false);
  assert.equal(T.TRICKS.includes("zoom"), false);
  assert.equal(T.TRICKS.includes("periscope"), false);
  assert.equal(T.TRICKS.includes("chatter"), false);
  assert.equal(T.TRICKS.includes("beg"), false);
});

test("popcorn/rumble/hay/potato/zig/lookout/teeth are house-guinea-pig-true, not Rui cat dog rabbit hamster or dragon clones", () => {
  const ground = { asleep: false, hidden: false, leaving: false, cmd: "idle" };
  const potato = T.beginTrick("potato", 80, 1);
  assert.equal(potato.anim, "sit");
  assert.equal(potato.phase, "hold");
  const held = T.stepTrick(potato, 5, ground);
  assert.equal(held.phase, "hold");
  assert.equal(held.anim, "sit");
  assert.ok(held.rot !== 0 || held.lift < 0);
  const release = T.stepTrick(potato, T.POTATO_HOLD + 0.2, ground);
  assert.equal(release.phase, "release");
  assert.equal(release.anim, "sit");
  const donePotato = T.stepTrick(potato, T.DUR.potato + 0.1, ground);
  assert.equal(donePotato.phase, "done");
  assert.ok(T.nextTrickWait(true, 0, "potato") > T.nextTrickWait(true, 0, "hay"));
  const rumble = T.beginTrick("rumble", 80, 1);
  assert.equal(rumble.anim, "sit");
  const rumbleMid = T.stepTrick(rumble, 0.5, ground);
  assert.ok(Math.abs(rumbleMid.rot) > 0.5 || rumbleMid.lift !== 0);
  const hay = T.beginTrick("hay", 80, 1);
  assert.equal(hay.anim, "sit");
  const hayMid = T.stepTrick(hay, 0.5, ground);
  assert.ok(hayMid.lift < 0 || Math.abs(hayMid.rot) > 0.5);
  const lookout = T.beginTrick("lookout", 80, 1);
  assert.equal(lookout.anim, "sit");
  const lookMid = T.stepTrick(lookout, T.DUR.lookout * 0.4, ground);
  assert.ok(lookMid.lift > 6 || Math.abs(lookMid.rot) > 4);
  const teeth = T.beginTrick("teeth", 80, 1);
  assert.equal(teeth.anim, "sit");
  const teethMid = T.stepTrick(teeth, T.DUR.teeth * 0.4, ground);
  assert.ok(teethMid.lift < 0 || Math.abs(teethMid.rot) > 4);
  assert.equal(Overlay.TRICKS.includes("lookout"), true);
  assert.equal(Overlay.TRICKS.includes("teeth"), true);
  const popcorn = T.beginTrick("popcorn", 80, 1);
  assert.equal(popcorn.anim, "play");
  const popcornMid = T.stepTrick(popcorn, 0.5, ground);
  assert.ok(popcornMid.lift > 2 || Math.abs(popcornMid.rot) > 2);
  const zig = T.beginTrick("zig", 80, 1);
  assert.equal(zig.anim, "play");
  const zigMid = T.stepTrick(zig, 0.5, ground);
  assert.ok(zigMid.lift > 0 || Math.abs(zigMid.x - 80) > 2 || Math.abs(zigMid.rot) > 2);
  const zigDone = T.stepTrick(zig, T.DUR.zig + 0.1, ground);
  assert.equal(zigDone.phase, "done");
  const aborted = T.stepTrick(held, 0.1, { asleep: true, cmd: "sleep" });
  assert.equal(aborted.phase, "done");
  assert.equal(Rui.TRICKS.includes("popcorn"), false);
  assert.equal(Cat.TRICKS.includes("rumble"), false);
  assert.equal(Dog.TRICKS.includes("hay"), false);
  assert.equal(Rabbit.TRICKS.includes("potato"), false);
  assert.equal(Hamster.TRICKS.includes("zig"), false);
  assert.equal(Relay.TRICKS.includes("popcorn"), false);
  assert.equal(Fuse.TRICKS.includes("potato"), false);
  assert.equal(Earth.TRICKS.includes("hay"), false);
  assert.equal(Cat.TRICKS.includes("potato"), false);
  assert.equal(Rabbit.TRICKS.includes("lookout"), false);
  assert.equal(Rabbit.TRICKS.includes("teeth"), false);
  assert.equal(Hamster.TRICKS.includes("lookout"), false);
  assert.equal(Hamster.TRICKS.includes("teeth"), false);
  assert.equal(T.TRICKS.includes("loaf"), false);
  assert.equal(T.TRICKS.includes("wheek"), false);
  assert.equal(T.TRICKS.includes("nest"), false);
  assert.equal(T.TRICKS.includes("scurry"), false);
  assert.equal(T.TRICKS.includes("periscope"), false);
  assert.equal(T.TRICKS.includes("chatter"), false);
});

test("Whee feed-happy is its own sit: peep/nibble/toot, and two feeds are not the same", () => {
  assert.deepEqual([...T.HAPPY], ["peep", "nibble", "toot"]);
  assert.equal(T.HAPPY.includes("spark"), false);
  assert.equal(T.HAPPY.includes("purr"), false);
  assert.equal(T.HAPPY.includes("tail"), false);
  assert.equal(T.HAPPY.includes("twitch"), false);
  assert.equal(T.HAPPY.includes("stuff"), false);
  assert.equal(T.pickHappy("peep", 0), "nibble");
  assert.notEqual(T.pickHappy("peep", 0.9), "peep");
  assert.equal(Overlay.pickHappy("nibble", 0) !== "nibble", true);
  assert.equal(T.happyCanStart({ asleep: false, hidden: false, leaving: false, cmd: "idle" }), true);
  assert.equal(T.happyCanStart({ asleep: false, hidden: false, leaving: false, cmd: "idle", card: true }), true);
  assert.equal(T.happyCanStart({ asleep: true, hidden: false, leaving: false, cmd: "idle" }), false);
  assert.equal(T.happyShouldAbort({ cmd: "sleep" }), true);
  assert.equal(T.happyShouldAbort({ cmd: "hide" }), true);
  assert.equal(T.happyShouldAbort({ card: true, cmd: "idle" }), false);
  const peep = T.beginHappy("peep", 80, 1);
  assert.equal(peep.anim, "talk");
  const peepMid = T.stepHappy(peep, 0.3, { cmd: "idle" });
  assert.ok(peepMid.lift > 0.2 || Math.abs(peepMid.rot) > 0.5);
  assert.notEqual(peepMid.phase, "done");
  const nibble = T.beginHappy("nibble", 80, 1);
  assert.equal(nibble.anim, "sit");
  const nibbleMid = T.stepHappy(nibble, 0.4, { cmd: "idle" });
  assert.ok(nibbleMid.lift !== 0 || Math.abs(nibbleMid.rot) > 0.5);
  const toot = T.beginHappy("toot", 80, 1);
  assert.equal(toot.anim, "play");
  const done = T.stepHappy(nibble, T.HAPPY_DUR.nibble + 0.1, { cmd: "idle" });
  assert.equal(done.phase, "done");
  const aborted = T.stepHappy(peepMid, 0.1, { asleep: true, cmd: "sleep" });
  assert.equal(aborted.phase, "done");
  assert.equal(aborted.abort, true);
  assert.equal(T.wantsThankYou("guinea_pig"), true);
  assert.equal(T.wantsThankYou("whee"), true);
  assert.equal(T.wantsThankYou("hamster"), false);
  assert.equal(T.wantsThankYou("dog"), false);
  assert.equal(T.wantsThankYou("cat"), false);
  assert.equal(T.wantsThankYou("rabbit"), false);
  assert.equal(T.wantsThankYou("red_panda"), false);
  assert.equal(T.wantsThankYou("ground_dragon"), false);
  const thanks = T.startThankYou("guinea_pig", "peep", 80, 1, { cmd: "idle", card: true, windowPlay: true });
  assert.ok(thanks);
  assert.notEqual(thanks.kind, "peep");
  assert.ok(thanks.happy.lift === 0);
  assert.notEqual(thanks.happy.anim, "eat");
  assert.notEqual(thanks.happy.anim, "idle");
  const thanksMid = T.stepHappy(thanks.happy, 0.35, { cmd: "idle", card: true });
  assert.ok(thanksMid.lift !== 0 || Math.abs(thanksMid.rot) > 0.5, "a thank-you peeps or toots");
  const blocked = T.startThankYou("guinea_pig", "nibble", 80, 1, { asleep: true, cmd: "idle" });
  assert.equal(blocked, null);
  const other = T.startThankYou("turtle", null, 80, 1, { cmd: "idle" });
  assert.equal(other, null);
  const second = T.startThankYou("guinea_pig", thanks.kind, 80, 1, { cmd: "idle", card: true });
  assert.ok(second);
  assert.notEqual(second.kind, thanks.kind);
});

test("ground registry keeps prior guests gated; Whee selectable; no wheek/loaf/nest-name collision", () => {
  assert.equal(Rui.TRICK_KEY, "red_panda");
  assert.equal(Relay.TRICK_KEY, "relay_dragon");
  assert.equal(Fuse.TRICK_KEY, "fuse_dragon");
  assert.equal(Earth.TRICK_KEY, "ground_dragon");
  assert.equal(Cat.TRICK_KEY, "cat");
  assert.equal(Dog.TRICK_KEY, "dog");
  assert.equal(Rabbit.TRICK_KEY, "rabbit");
  assert.equal(Hamster.TRICK_KEY, "hamster");
  assert.equal(T.TRICK_KEY, "guinea_pig");
  assert.deepEqual([...Rui.TRICKS], ["somersault", "lie", "scratch", "wave", "dance"]);
  assert.deepEqual([...Relay.TRICKS], ["click", "latch", "arc", "buzz", "switch"]);
  assert.deepEqual([...Fuse.TRICKS], ["seat", "current", "blow", "reseat"]);
  assert.deepEqual([...Earth.TRICKS], ["lug", "earth", "heave", "bed"]);
  assert.deepEqual([...Cat.TRICKS], ["loaf", "knead", "stretch", "wash", "pounce", "bunting", "mlem"]);
  assert.deepEqual([...Dog.TRICKS], ["wait", "wag", "sniff", "bow", "zoom", "beg", "pant"]);
  assert.deepEqual([...Rabbit.TRICKS], ["flop", "groom", "periscope", "dig", "binky", "rub", "nosh"]);
  assert.deepEqual([...Hamster.TRICKS], ["nest", "cheek", "scurry", "pocket", "reel", "scrub", "seed"]);
  assert.equal(T.TRICKS.includes("scratch"), false);
  assert.equal(T.TRICKS.includes("wheek"), false);
  assert.equal(T.TRICKS.includes("loaf"), false);
  assert.equal(T.TRICKS.includes("nest"), false);
  assert.equal(Rui.wantsThankYou("guinea_pig"), false);
  assert.equal(Relay.wantsThankYou("guinea_pig"), false);
  assert.equal(Fuse.wantsThankYou("guinea_pig"), false);
  assert.equal(Earth.wantsThankYou("guinea_pig"), false);
  assert.equal(Cat.wantsThankYou("guinea_pig"), false);
  assert.equal(Dog.wantsThankYou("guinea_pig"), false);
  assert.equal(Rabbit.wantsThankYou("guinea_pig"), false);
  assert.equal(Hamster.wantsThankYou("guinea_pig"), false);
  assert.equal(T.wantsThankYou("guinea_pig"), true);
  assert.equal(T.wantsThankYou("whee"), true);
  assert.equal(T.wantsThankYou("hamster"), false);
  assert.equal(T.wantsThankYou("clip"), false);
  assert.equal(Rui.sleepHoldFrame("red_panda", 4), 1);
  assert.equal(T.sleepHoldFrame("guinea_pig", 4), null);
  globalThis.PetRuiTricks = OverlayRui;
  globalThis.PetRelayTricks = OverlayRelay;
  globalThis.PetFuseTricks = OverlayFuse;
  globalThis.PetEarthTricks = OverlayEarth;
  globalThis.PetCatTricks = OverlayCat;
  globalThis.PetDogTricks = OverlayDog;
  globalThis.PetRabbitTricks = OverlayRabbit;
  globalThis.PetHamsterTricks = OverlayHamster;
  globalThis.PetGuineaPigTricks = Overlay;
  globalThis.PetTurtleTricks = OverlayTurtle;
  assert.equal(OverlayGround.tricksFor("red_panda"), OverlayRui);
  assert.equal(OverlayGround.tricksFor("rui"), OverlayRui);
  assert.equal(OverlayGround.tricksFor("relay_dragon"), OverlayRelay);
  assert.equal(OverlayGround.tricksFor("fuse_dragon"), OverlayFuse);
  assert.equal(OverlayGround.tricksFor("ground_dragon"), OverlayEarth);
  assert.equal(OverlayGround.tricksFor("ground"), OverlayEarth);
  assert.equal(OverlayGround.tricksFor("cat"), OverlayCat);
  assert.equal(OverlayGround.tricksFor("miso"), OverlayCat);
  assert.equal(OverlayGround.tricksFor("dog"), OverlayDog);
  assert.equal(OverlayGround.tricksFor("pip"), OverlayDog);
  assert.equal(OverlayGround.tricksFor("rabbit"), OverlayRabbit);
  assert.equal(OverlayGround.tricksFor("thimble"), OverlayRabbit);
  assert.equal(OverlayGround.tricksFor("hamster"), OverlayHamster);
  assert.equal(OverlayGround.tricksFor("clip"), OverlayHamster);
  assert.equal(OverlayGround.tricksFor("guinea_pig"), Overlay);
  assert.equal(OverlayGround.tricksFor("whee"), Overlay);
  assert.equal(OverlayGround.tricksFor("turtle"), OverlayTurtle);
  assert.equal(OverlayGround.tricksFor("ink"), OverlayTurtle);
  assert.equal(OverlayGround.tricksFor("goldfish") == null, true);
  assert.equal(OverlayGround.wantsThankYou("red_panda"), true);
  assert.equal(OverlayGround.wantsThankYou("relay_dragon"), true);
  assert.equal(OverlayGround.wantsThankYou("fuse_dragon"), true);
  assert.equal(OverlayGround.wantsThankYou("ground_dragon"), true);
  assert.equal(OverlayGround.wantsThankYou("cat"), true);
  assert.equal(OverlayGround.wantsThankYou("miso"), true);
  assert.equal(OverlayGround.wantsThankYou("dog"), true);
  assert.equal(OverlayGround.wantsThankYou("pip"), true);
  assert.equal(OverlayGround.wantsThankYou("rabbit"), true);
  assert.equal(OverlayGround.wantsThankYou("thimble"), true);
  assert.equal(OverlayGround.wantsThankYou("hamster"), true);
  assert.equal(OverlayGround.wantsThankYou("clip"), true);
  assert.equal(OverlayGround.wantsThankYou("guinea_pig"), true);
  assert.equal(OverlayGround.wantsThankYou("whee"), true);
  assert.equal(OverlayGround.wantsThankYou("turtle"), true);
  assert.equal(OverlayGround.wantsThankYou("ink"), true);
  assert.equal(OverlayGround.wantsThankYou("goldfish"), false);
  assert.equal(OverlayGround.sleepHoldFrame("red_panda", 4), 1);
  assert.equal(OverlayGround.sleepHoldFrame("dog", 4), null);
  assert.equal(OverlayGround.sleepHoldFrame("cat", 4), null);
  assert.equal(OverlayGround.sleepHoldFrame("rabbit", 4), null);
  assert.equal(OverlayGround.sleepHoldFrame("hamster", 4), null);
  assert.equal(OverlayGround.sleepHoldFrame("guinea_pig", 4), null);
  assert.equal(OverlayGround.sleepHoldFrame("turtle", 4), null);
});

test("ultra-polish: Whee potato/hay/rumble/lookout/teeth lifts are Rui-visible (not micro idle-gen)", () => {
  const ex = T.beginTrick("potato", 80, 1);
  const mid = T.stepTrick(ex, 5, { cmd: "idle" });
  assert.ok(Math.abs(mid.rot) > 6, `potato mid rot ${mid.rot}`);
  assert.ok(Math.abs(mid.lift) > 2, `potato mid lift ${mid.lift}`);
  const hy = T.beginTrick("hay", 80, 1);
  const h2 = T.stepTrick(hy, T.DUR.hay * 0.4, { cmd: "idle" });
  assert.ok(h2.lift < -2 || Math.abs(h2.rot) > 6, `hay mid lift/rot ${h2.lift}/${h2.rot}`);
  const rb = T.beginTrick("rumble", 80, 1);
  const r2 = T.stepTrick(rb, T.DUR.rumble * 0.4, { cmd: "idle" });
  assert.ok(Math.abs(r2.rot) > 6 || r2.lift < -1, `rumble mid rot/lift ${r2.rot}/${r2.lift}`);
  const lo = T.beginTrick("lookout", 80, 1);
  const l2 = T.stepTrick(lo, T.DUR.lookout * 0.4, { cmd: "idle" });
  assert.ok(l2.lift > 6 || Math.abs(l2.rot) > 4, `lookout mid lift/rot ${l2.lift}/${l2.rot}`);
  const th = T.beginTrick("teeth", 80, 1);
  const t2 = T.stepTrick(th, T.DUR.teeth * 0.4, { cmd: "idle" });
  assert.ok(t2.lift < 0 || Math.abs(t2.rot) > 6, `teeth mid lift/rot ${t2.lift}/${t2.rot}`);
  assert.ok(Overlay.lookoutPose && Overlay.teethPose);
  assert.equal(T.POTATO_HOLD, Overlay.POTATO_HOLD);
  assert.ok(T.POTATO_HOLD >= 14);
  assert.equal(T.DUR.lookout, Overlay.DUR.lookout);
  assert.equal(T.DUR.teeth, Overlay.DUR.teeth);
});

test("notes: Whee idle-life ultra done; Ink / turtle ultra next-or-done; following house-order ultra guest is Coin / goldfish (birds Soot→Ember + Miso + Pip + Thimble + Clip already ultra; Echo skip)", () => {
  assert.deepEqual([...T.TRICKS], ["popcorn", "rumble", "hay", "potato", "zig", "lookout", "teeth"]);
  assert.equal(T.TRICK_KEY, "guinea_pig");
  assert.equal(T.wantsThankYou("whee"), true);
});
