import assert from "node:assert/strict";
import { createRequire } from "node:module";
import { dirname, join } from "node:path";
import { test } from "node:test";
import { fileURLToPath, pathToFileURL } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const T = await import(pathToFileURL(join(root, "src/lib/pets/hamster-tricks.ts")).href);
const Rui = await import(pathToFileURL(join(root, "src/lib/pets/rui-tricks.ts")).href);
const Relay = await import(pathToFileURL(join(root, "src/lib/pets/relay-tricks.ts")).href);
const Fuse = await import(pathToFileURL(join(root, "src/lib/pets/fuse-tricks.ts")).href);
const Earth = await import(pathToFileURL(join(root, "src/lib/pets/earth-tricks.ts")).href);
const Cat = await import(pathToFileURL(join(root, "src/lib/pets/cat-tricks.ts")).href);
const Dog = await import(pathToFileURL(join(root, "src/lib/pets/dog-tricks.ts")).href);
const Rabbit = await import(pathToFileURL(join(root, "src/lib/pets/rabbit-tricks.ts")).href);
const Overlay = createRequire(import.meta.url)(join(root, "../desktop/renderer/hamster-tricks.js"));
const OverlayGround = createRequire(import.meta.url)(join(root, "../desktop/renderer/ground-tricks.js"));
const OverlayRui = createRequire(import.meta.url)(join(root, "../desktop/renderer/rui-tricks.js"));
const OverlayRelay = createRequire(import.meta.url)(join(root, "../desktop/renderer/relay-tricks.js"));
const OverlayFuse = createRequire(import.meta.url)(join(root, "../desktop/renderer/fuse-tricks.js"));
const OverlayEarth = createRequire(import.meta.url)(join(root, "../desktop/renderer/earth-tricks.js"));
const OverlayCat = createRequire(import.meta.url)(join(root, "../desktop/renderer/cat-tricks.js"));
const OverlayDog = createRequire(import.meta.url)(join(root, "../desktop/renderer/dog-tricks.js"));
const OverlayRabbit = createRequire(import.meta.url)(join(root, "../desktop/renderer/rabbit-tricks.js"));
const OverlayGuineaPig = createRequire(import.meta.url)(join(root, "../desktop/renderer/guinea-pig-tricks.js"));

test("Clip tricks start only on idle ground", () => {
  assert.deepEqual([...T.TRICKS], ["nest", "cheek", "scurry", "pocket", "reel", "scrub", "seed"]);
  assert.equal(T.canStart({ asleep: false, hidden: false, leaving: false, cmd: "idle" }), true);
  assert.equal(T.canStart({ asleep: true, hidden: false, leaving: false, cmd: "idle" }), false);
  assert.equal(T.canStart({ asleep: false, hidden: true, leaving: false, cmd: "idle" }), false);
  assert.equal(T.canStart({ asleep: false, hidden: false, leaving: false, cmd: "sleep" }), false);
  assert.equal(T.canStart({ asleep: false, hidden: false, leaving: false, cmd: "seek" }), false);
  assert.equal(T.canStart({ asleep: false, hidden: false, leaving: false, cmd: "idle", windowPlay: true }), false);
  assert.equal(T.canStart({ asleep: false, hidden: false, leaving: false, cmd: "idle", card: true }), false);
  assert.equal(T.shouldAbort({ asleep: true, hidden: false, leaving: false, cmd: "idle" }), true);
  assert.equal(T.shouldAbort({ asleep: false, hidden: false, leaving: false, cmd: "idle", card: true }), true);
  assert.equal(T.shouldAbort({ asleep: false, hidden: false, leaving: false, cmd: "idle" }), false);
  assert.equal(T.pickTrick(0.99, true), "nest");
  assert.notEqual(T.pickTrick(0.3, false, "nest"), "nest");
  assert.equal(Overlay.TRICK_KEY, "hamster");
  assert.equal(T.sleepHoldFrame("hamster", 4), null);
  assert.equal(T.TRICKS.includes("somersault"), false);
  assert.equal(T.TRICKS.includes("scratch"), false);
  assert.equal(T.TRICKS.includes("loaf"), false);
  assert.equal(T.TRICKS.includes("wait"), false);
  assert.equal(T.TRICKS.includes("bow"), false);
  assert.equal(T.TRICKS.includes("dig"), false);
  assert.equal(T.TRICKS.includes("flop"), false);
  assert.equal(T.TRICKS.includes("stash"), false);
  assert.equal(T.TRICKS.includes("groom"), false);
  assert.equal(T.TRICKS.includes("binky"), false);
  assert.equal(T.TRICKS.includes("zoom"), false);
});

test("nest/cheek/scurry/pocket/reel/scrub/seed are house-hamster-true, not Rui cat dog rabbit or dragon clones", () => {
  const ground = { asleep: false, hidden: false, leaving: false, cmd: "idle" };
  const nest = T.beginTrick("nest", 80, 1);
  assert.equal(nest.anim, "sit");
  assert.equal(nest.phase, "hold");
  const held = T.stepTrick(nest, 5, ground);
  assert.equal(held.phase, "hold");
  assert.equal(held.anim, "sit");
  assert.ok(held.rot < 0 || held.lift < 0);
  const release = T.stepTrick(nest, T.NEST_HOLD + 0.2, ground);
  assert.equal(release.phase, "release");
  assert.equal(release.anim, "sit");
  const doneNest = T.stepTrick(nest, T.DUR.nest + 0.1, ground);
  assert.equal(doneNest.phase, "done");
  assert.ok(T.nextTrickWait(true, 0, "nest") > T.nextTrickWait(true, 0, "cheek"));
  const cheek = T.beginTrick("cheek", 80, 1);
  assert.equal(cheek.anim, "sit");
  const cheekMid = T.stepTrick(cheek, 0.25, ground);
  assert.ok(Math.abs(cheekMid.rot) > 0.5 || cheekMid.lift !== 0);
  const pocket = T.beginTrick("pocket", 80, 1);
  assert.equal(pocket.anim, "sit");
  const pocketMid = T.stepTrick(pocket, 0.5, ground);
  assert.ok(pocketMid.lift < 0 || Math.abs(pocketMid.rot) > 0.5);
  const reel = T.beginTrick("reel", 80, 1);
  assert.equal(reel.anim, "play");
  const reelMid = T.stepTrick(reel, 0.5, ground);
  assert.ok(Math.abs(reelMid.rot) > 2 || reelMid.lift > 0);
  const scrub = T.beginTrick("scrub", 80, 1);
  assert.equal(scrub.anim, "sit");
  const scrubMid = T.stepTrick(scrub, T.DUR.scrub * 0.4, ground);
  assert.ok(scrubMid.lift < -1 || Math.abs(scrubMid.rot) > 6);
  const seed = T.beginTrick("seed", 80, 1);
  assert.equal(seed.anim, "sit");
  const seedMid = T.stepTrick(seed, T.DUR.seed * 0.4, ground);
  assert.ok(seedMid.lift < 0 || Math.abs(seedMid.rot) > 4);
  assert.equal(Overlay.TRICKS.includes("scrub"), true);
  assert.equal(Overlay.TRICKS.includes("seed"), true);
  const scurry = T.beginTrick("scurry", 80, 1);
  assert.equal(scurry.anim, "play");
  const scurryMid = T.stepTrick(scurry, 0.5, ground);
  assert.ok(scurryMid.lift > 0 || Math.abs(scurryMid.x - 80) > 2 || Math.abs(scurryMid.rot) > 2);
  const scurryDone = T.stepTrick(scurry, T.DUR.scurry + 0.1, ground);
  assert.equal(scurryDone.phase, "done");
  const aborted = T.stepTrick(held, 0.1, { asleep: true, cmd: "sleep" });
  assert.equal(aborted.phase, "done");
  assert.equal(Rui.TRICKS.includes("nest"), false);
  assert.equal(Cat.TRICKS.includes("cheek"), false);
  assert.equal(Dog.TRICKS.includes("pocket"), false);
  assert.equal(Rabbit.TRICKS.includes("reel"), false);
  assert.equal(Relay.TRICKS.includes("scurry"), false);
  assert.equal(Fuse.TRICKS.includes("nest"), false);
  assert.equal(Earth.TRICKS.includes("cheek"), false);
  assert.equal(Rabbit.TRICKS.includes("nest"), false);
  assert.equal(Cat.TRICKS.includes("scrub"), false);
  assert.equal(Cat.TRICKS.includes("seed"), false);
  assert.equal(Rabbit.TRICKS.includes("scrub"), false);
  assert.equal(Rabbit.TRICKS.includes("seed"), false);
  assert.equal(T.TRICKS.includes("bow"), false);
  assert.equal(T.TRICKS.includes("stash"), false);
  assert.equal(T.TRICKS.includes("dig"), false);
  assert.equal(T.TRICKS.includes("wash"), false);
  assert.equal(T.TRICKS.includes("groom"), false);
  assert.equal(T.TRICKS.includes("nibble"), false);
  assert.equal(T.TRICKS.includes("nosh"), false);
});

test("Clip feed-happy is its own sit: stuff/chitter/sprint, and two feeds are not the same", () => {
  assert.deepEqual([...T.HAPPY], ["stuff", "chitter", "sprint"]);
  assert.equal(T.HAPPY.includes("spark"), false);
  assert.equal(T.HAPPY.includes("purr"), false);
  assert.equal(T.HAPPY.includes("tail"), false);
  assert.equal(T.HAPPY.includes("twitch"), false);
  assert.equal(T.pickHappy("stuff", 0), "chitter");
  assert.notEqual(T.pickHappy("stuff", 0.9), "stuff");
  assert.equal(Overlay.pickHappy("chitter", 0) !== "chitter", true);
  assert.equal(T.happyCanStart({ asleep: false, hidden: false, leaving: false, cmd: "idle" }), true);
  assert.equal(T.happyCanStart({ asleep: false, hidden: false, leaving: false, cmd: "idle", card: true }), true);
  assert.equal(T.happyCanStart({ asleep: true, hidden: false, leaving: false, cmd: "idle" }), false);
  assert.equal(T.happyShouldAbort({ cmd: "sleep" }), true);
  assert.equal(T.happyShouldAbort({ cmd: "hide" }), true);
  assert.equal(T.happyShouldAbort({ card: true, cmd: "idle" }), false);
  const stuff = T.beginHappy("stuff", 80, 1);
  assert.equal(stuff.anim, "sit");
  const stuffMid = T.stepHappy(stuff, 0.4, { cmd: "idle" });
  assert.ok(stuffMid.lift !== 0 || Math.abs(stuffMid.rot) > 0.5);
  assert.notEqual(stuffMid.phase, "done");
  const chitter = T.beginHappy("chitter", 80, 1);
  assert.equal(chitter.anim, "talk");
  const chitterMid = T.stepHappy(chitter, 0.3, { cmd: "idle" });
  assert.ok(chitterMid.lift > 0.2 || Math.abs(chitterMid.rot) > 0.5);
  const sprint = T.beginHappy("sprint", 80, 1);
  assert.equal(sprint.anim, "play");
  const done = T.stepHappy(stuff, T.HAPPY_DUR.stuff + 0.1, { cmd: "idle" });
  assert.equal(done.phase, "done");
  const aborted = T.stepHappy(stuffMid, 0.1, { asleep: true, cmd: "sleep" });
  assert.equal(aborted.phase, "done");
  assert.equal(aborted.abort, true);
  assert.equal(T.wantsThankYou("hamster"), true);
  assert.equal(T.wantsThankYou("clip"), true);
  assert.equal(T.wantsThankYou("dog"), false);
  assert.equal(T.wantsThankYou("cat"), false);
  assert.equal(T.wantsThankYou("rabbit"), false);
  assert.equal(T.wantsThankYou("red_panda"), false);
  assert.equal(T.wantsThankYou("ground_dragon"), false);
  const thanks = T.startThankYou("hamster", "stuff", 80, 1, { cmd: "idle", card: true, windowPlay: true });
  assert.ok(thanks);
  assert.notEqual(thanks.kind, "stuff");
  assert.ok(thanks.happy.lift === 0);
  assert.notEqual(thanks.happy.anim, "eat");
  assert.notEqual(thanks.happy.anim, "idle");
  const thanksMid = T.stepHappy(thanks.happy, 0.35, { cmd: "idle", card: true });
  assert.ok(thanksMid.lift !== 0 || Math.abs(thanksMid.rot) > 0.5, "a thank-you stuffs or sprints");
  const blocked = T.startThankYou("hamster", "chitter", 80, 1, { asleep: true, cmd: "idle" });
  assert.equal(blocked, null);
  const other = T.startThankYou("guinea_pig", null, 80, 1, { cmd: "idle" });
  assert.equal(other, null);
  const second = T.startThankYou("hamster", thanks.kind, 80, 1, { cmd: "idle", card: true });
  assert.ok(second);
  assert.notEqual(second.kind, thanks.kind);
});

test("ground registry keeps prior guests gated; Clip selectable; no stash/dig/bow-name collision", () => {
  assert.equal(Rui.TRICK_KEY, "red_panda");
  assert.equal(Relay.TRICK_KEY, "relay_dragon");
  assert.equal(Fuse.TRICK_KEY, "fuse_dragon");
  assert.equal(Earth.TRICK_KEY, "ground_dragon");
  assert.equal(Cat.TRICK_KEY, "cat");
  assert.equal(Dog.TRICK_KEY, "dog");
  assert.equal(Rabbit.TRICK_KEY, "rabbit");
  assert.equal(T.TRICK_KEY, "hamster");
  assert.deepEqual([...Rui.TRICKS], ["somersault", "lie", "scratch", "wave", "dance"]);
  assert.deepEqual([...Relay.TRICKS], ["contactclick", "latchseat", "arcflick", "coilbuzz", "poleswitch", "armaturetap", "relayhush"]);
  assert.deepEqual([...Fuse.TRICKS], ["railseat", "holdcurrent", "blowclear", "reseatsnap", "cartridgerattle", "bladeflash", "fusehush"]);
  assert.deepEqual([...Earth.TRICKS], ["lugstrap", "earthseat", "heaveplate", "bedsettle", "soilgrip", "plateclamp", "groundhush"]);
  assert.deepEqual([...Cat.TRICKS], ["loaf", "knead", "stretch", "wash", "pounce", "bunting", "mlem"]);
  assert.deepEqual([...Dog.TRICKS], ["wait", "wag", "sniff", "bow", "zoom", "beg", "pant"]);
  assert.deepEqual([...Rabbit.TRICKS], ["flop", "groom", "periscope", "dig", "binky", "rub", "nosh"]);
  assert.equal(T.TRICKS.includes("scratch"), false);
  assert.equal(T.TRICKS.includes("stash"), false);
  assert.equal(T.TRICKS.includes("dig"), false);
  assert.equal(T.TRICKS.includes("bow"), false);
  assert.equal(Rui.wantsThankYou("hamster"), false);
  assert.equal(Relay.wantsThankYou("hamster"), false);
  assert.equal(Fuse.wantsThankYou("hamster"), false);
  assert.equal(Earth.wantsThankYou("hamster"), false);
  assert.equal(Cat.wantsThankYou("hamster"), false);
  assert.equal(Dog.wantsThankYou("hamster"), false);
  assert.equal(Rabbit.wantsThankYou("hamster"), false);
  assert.equal(T.wantsThankYou("hamster"), true);
  assert.equal(T.wantsThankYou("clip"), true);
  assert.equal(T.wantsThankYou("dog"), false);
  assert.equal(T.wantsThankYou("rabbit"), false);
  assert.equal(Rui.sleepHoldFrame("red_panda", 4), 1);
  assert.equal(T.sleepHoldFrame("hamster", 4), null);
  globalThis.PetRuiTricks = OverlayRui;
  globalThis.PetRelayTricks = OverlayRelay;
  globalThis.PetFuseTricks = OverlayFuse;
  globalThis.PetEarthTricks = OverlayEarth;
  globalThis.PetCatTricks = OverlayCat;
  globalThis.PetDogTricks = OverlayDog;
  globalThis.PetRabbitTricks = OverlayRabbit;
  globalThis.PetHamsterTricks = Overlay;
  globalThis.PetGuineaPigTricks = OverlayGuineaPig;
  assert.equal(OverlayGround.tricksFor("red_panda"), OverlayRui);
  assert.equal(OverlayGround.tricksFor("rui"), OverlayRui);
  assert.equal(OverlayGround.tricksFor("relay_dragon"), OverlayRelay);
  assert.equal(OverlayGround.tricksFor("fuse_dragon"), OverlayFuse);
  assert.equal(OverlayGround.tricksFor("ground_dragon"), OverlayEarth);
  assert.equal(OverlayGround.tricksFor("ground"), OverlayEarth);
  assert.equal(OverlayGround.tricksFor("cat"), OverlayCat);
  assert.equal(OverlayGround.tricksFor("miso"), OverlayCat);
  assert.equal(OverlayGround.tricksFor("dog"), OverlayDog);
  assert.equal(OverlayGround.tricksFor("pip"), OverlayDog);
  assert.equal(OverlayGround.tricksFor("rabbit"), OverlayRabbit);
  assert.equal(OverlayGround.tricksFor("thimble"), OverlayRabbit);
  assert.equal(OverlayGround.tricksFor("hamster"), Overlay);
  assert.equal(OverlayGround.tricksFor("clip"), Overlay);
  assert.equal(OverlayGround.tricksFor("guinea_pig"), OverlayGuineaPig);
  assert.equal(OverlayGround.tricksFor("whee"), OverlayGuineaPig);
  assert.equal(OverlayGround.tricksFor("turtle") == null, true);
  assert.equal(OverlayGround.wantsThankYou("red_panda"), true);
  assert.equal(OverlayGround.wantsThankYou("relay_dragon"), true);
  assert.equal(OverlayGround.wantsThankYou("fuse_dragon"), true);
  assert.equal(OverlayGround.wantsThankYou("ground_dragon"), true);
  assert.equal(OverlayGround.wantsThankYou("cat"), true);
  assert.equal(OverlayGround.wantsThankYou("miso"), true);
  assert.equal(OverlayGround.wantsThankYou("dog"), true);
  assert.equal(OverlayGround.wantsThankYou("pip"), true);
  assert.equal(OverlayGround.wantsThankYou("rabbit"), true);
  assert.equal(OverlayGround.wantsThankYou("thimble"), true);
  assert.equal(OverlayGround.wantsThankYou("hamster"), true);
  assert.equal(OverlayGround.wantsThankYou("clip"), true);
  assert.equal(OverlayGround.wantsThankYou("guinea_pig"), true);
  assert.equal(OverlayGround.wantsThankYou("whee"), true);
  assert.equal(OverlayGround.wantsThankYou("turtle"), false);
  assert.equal(OverlayGround.sleepHoldFrame("red_panda", 4), 1);
  assert.equal(OverlayGround.sleepHoldFrame("dog", 4), null);
  assert.equal(OverlayGround.sleepHoldFrame("cat", 4), null);
  assert.equal(OverlayGround.sleepHoldFrame("rabbit", 4), null);
  assert.equal(OverlayGround.sleepHoldFrame("hamster", 4), null);
});

test("ultra-polish: Clip nest/cheek/pocket/scrub/seed lifts are Rui-visible (not micro idle-gen)", () => {
  const ex = T.beginTrick("nest", 80, 1);
  const mid = T.stepTrick(ex, 5, { cmd: "idle" });
  assert.ok(Math.abs(mid.rot) > 6, `nest mid rot ${mid.rot}`);
  assert.ok(Math.abs(mid.lift) > 2, `nest mid lift ${mid.lift}`);
  const ch = T.beginTrick("cheek", 80, 1);
  const c2 = T.stepTrick(ch, T.DUR.cheek * 0.4, { cmd: "idle" });
  assert.ok(Math.abs(c2.rot) > 6, `cheek mid rot ${c2.rot}`);
  assert.ok(Math.abs(c2.lift) > 2 || c2.lift > 2, `cheek mid lift ${c2.lift}`);
  const pk = T.beginTrick("pocket", 80, 1);
  const p2 = T.stepTrick(pk, T.DUR.pocket * 0.4, { cmd: "idle" });
  assert.ok(p2.lift < -2 || Math.abs(p2.rot) > 6, `pocket mid lift/rot ${p2.lift}/${p2.rot}`);
  const sb = T.beginTrick("scrub", 80, 1);
  const s2 = T.stepTrick(sb, T.DUR.scrub * 0.4, { cmd: "idle" });
  assert.ok(s2.lift < -1 || Math.abs(s2.rot) > 6, `scrub mid lift/rot ${s2.lift}/${s2.rot}`);
  const sd = T.beginTrick("seed", 80, 1);
  const n2 = T.stepTrick(sd, T.DUR.seed * 0.4, { cmd: "idle" });
  assert.ok(n2.lift < 0 || Math.abs(n2.rot) > 6, `seed mid lift/rot ${n2.lift}/${n2.rot}`);
  assert.ok(Overlay.scrubPose && Overlay.seedPose);
  assert.equal(T.NEST_HOLD, Overlay.NEST_HOLD);
  assert.equal(T.NEST_HOLD, 11.2);
  assert.equal(T.RELEASE_S, 1.18);
});

test("notes: Clip Rui-dense ultra (NEST_HOLD=11.2); next house-order densify leftover after early mammals: Whee / guinea_pig then Ink / turtle", () => {
  assert.deepEqual([...T.TRICKS], ["nest", "cheek", "scurry", "pocket", "reel", "scrub", "seed"]);
  assert.equal(T.TRICK_KEY, "hamster");
  assert.equal(T.wantsThankYou("clip"), true);
});
