import assert from "node:assert/strict";
import { existsSync } from "node:fs";
import { createRequire } from "node:module";
import { dirname, join } from "node:path";
import { test } from "node:test";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const M = await import(join(root, "src/lib/pets/house-music.ts"));
const Overlay = createRequire(import.meta.url)(join(root, "../desktop/renderer/house-music.js"));

test("Rui music is house loop or free radio, no paid key", () => {
  assert.deepEqual(M.MUSIC_PLUGINS.map((p) => p.id), ["off", "house", "radio"]);
  assert.equal(M.RADIO_CANT_REACH, "can't reach");
  assert.match(M.radioSearchUrl("piano"), /radio-browser\.info/);
  assert.match(M.radioSearchUrl("99.9 seattle fm"), /name=99\.9/);
  assert.ok(M.radioSearchUrls("99.9 seattle fm").some((u) => /city=Seattle/i.test(u)));
  assert.ok(M.radioSearchUrls("99.9 seattle fm").some((u) => /countrycode=US/.test(u)));
  assert.ok(M.radioSearchUrls("99.9 seattle fm").some((u) => /state=Washington/.test(u)));
  assert.ok(!M.radioSearchUrls("99.9 seattle fm").some((u) => /tag=seattle/.test(u)));
  assert.equal(M.parseRadioQuery("KEXP").raw, "KEXP");
  assert.match(M.radioSearchUrl("KEXP"), /name=KEXP/i);
  assert.deepEqual(M.radioSearchUrls(""), []);
  const seattle = { name: "Seattle, Washington, United States", query: "Seattle", lat: 47.6, lon: -122.3 };
  assert.ok(M.radioSearchUrls("", seattle).some((u) => /city=Seattle/i.test(u)));
  assert.equal(M.parseRadioQuery("99.9 seattle fm").city, "Seattle");
  assert.equal(M.parseRadioQuery("99.9 seattle fm").state, "Washington");
  assert.equal(M.parseRadioQuery("99.9 seattle fm").countrycode, "US");
  assert.equal(M.RADIO_EMPTY, "no station from that look-up");
  assert.equal(M.RADIO_LOCAL, "Local");
  assert.match(M.RADIO_UA, /ComputerPets/);
  assert.doesNotMatch(M.RADIO_DIR, /spotify|apple|youtube/i);
  const music = M.parseMusic({ plugin: "house", playing: true });
  assert.equal(M.playSrc(music), "/sounds/house-loop.wav");
  assert.equal(M.overlayPlaySrc(music), "sounds/house-loop.wav");
  assert.equal(M.playSrc(M.parseMusic({ plugin: "off", playing: true })), "");
  assert.equal(existsSync(join(root, "public/sounds/house-loop.wav")), true);
  assert.equal(Overlay.HOUSE_LOOP_LICENSE, M.HOUSE_LOOP_LICENSE);
  assert.equal(Overlay.RADIO_UA, M.RADIO_UA);
  const stations = M.parseStations([{ name: "A free station", url_resolved: "https://example.test/stream", stationuuid: "s1" }]);
  assert.equal(stations[0].name, "A free station");
});
