import assert from "node:assert/strict";
import { createRequire } from "node:module";
import { dirname, join } from "node:path";
import { test } from "node:test";
import { fileURLToPath, pathToFileURL } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const T = await import(pathToFileURL(join(root, "src/lib/pets/milk-snake-tricks.ts")).href);
const Garter = await import(pathToFileURL(join(root, "src/lib/pets/garter-tricks.ts")).href);
const Boa = await import(pathToFileURL(join(root, "src/lib/pets/boa-tricks.ts")).href);
const Hognose = await import(pathToFileURL(join(root, "src/lib/pets/hognose-tricks.ts")).href);
const GreenTreePython = await import(pathToFileURL(join(root, "src/lib/pets/green-tree-python-tricks.ts")).href);
const BallPython = await import(pathToFileURL(join(root, "src/lib/pets/ball-python-tricks.ts")).href);
const CornSnake = await import(pathToFileURL(join(root, "src/lib/pets/corn-snake-tricks.ts")).href);
const Kingsnake = await import(pathToFileURL(join(root, "src/lib/pets/kingsnake-tricks.ts")).href);
const Phoenix = await import(pathToFileURL(join(root, "src/lib/pets/phoenix-tricks.ts")).href);
const Dragon = await import(pathToFileURL(join(root, "src/lib/pets/dragon-tricks.ts")).href);
const Rui = await import(pathToFileURL(join(root, "src/lib/pets/rui-tricks.ts")).href);
const Relay = await import(pathToFileURL(join(root, "src/lib/pets/relay-tricks.ts")).href);
const Fuse = await import(pathToFileURL(join(root, "src/lib/pets/fuse-tricks.ts")).href);
const Earth = await import(pathToFileURL(join(root, "src/lib/pets/earth-tricks.ts")).href);
const Cat = await import(pathToFileURL(join(root, "src/lib/pets/cat-tricks.ts")).href);
const Dog = await import(pathToFileURL(join(root, "src/lib/pets/dog-tricks.ts")).href);
const Rabbit = await import(pathToFileURL(join(root, "src/lib/pets/rabbit-tricks.ts")).href);
const Hamster = await import(pathToFileURL(join(root, "src/lib/pets/hamster-tricks.ts")).href);
const GuineaPig = await import(pathToFileURL(join(root, "src/lib/pets/guinea-pig-tricks.ts")).href);
const Turtle = await import(pathToFileURL(join(root, "src/lib/pets/turtle-tricks.ts")).href);
const Goldfish = await import(pathToFileURL(join(root, "src/lib/pets/goldfish-tricks.ts")).href);
const Budgie = await import(pathToFileURL(join(root, "src/lib/pets/budgie-tricks.ts")).href);
const Fox = await import(pathToFileURL(join(root, "src/lib/pets/fox-tricks.ts")).href);
const Penguin = await import(pathToFileURL(join(root, "src/lib/pets/penguin-tricks.ts")).href);
const Parrot = await import(pathToFileURL(join(root, "src/lib/pets/parrot-tricks.ts")).href);
const Ferret = await import(pathToFileURL(join(root, "src/lib/pets/ferret-tricks.ts")).href);
const Hedgehog = await import(pathToFileURL(join(root, "src/lib/pets/hedgehog-tricks.ts")).href);
const Chinchilla = await import(pathToFileURL(join(root, "src/lib/pets/chinchilla-tricks.ts")).href);
const Axolotl = await import(pathToFileURL(join(root, "src/lib/pets/axolotl-tricks.ts")).href);
const Toucan = await import(pathToFileURL(join(root, "src/lib/pets/toucan-tricks.ts")).href);
const Iguana = await import(pathToFileURL(join(root, "src/lib/pets/iguana-tricks.ts")).href);
const Overlay = createRequire(import.meta.url)(join(root, "../desktop/renderer/milk-snake-tricks.js"));
const OverlayGarter = createRequire(import.meta.url)(join(root, "../desktop/renderer/garter-tricks.js"));
const OverlayBoa = createRequire(import.meta.url)(join(root, "../desktop/renderer/boa-tricks.js"));
const OverlayHognose = createRequire(import.meta.url)(join(root, "../desktop/renderer/hognose-tricks.js"));
const OverlayGreenTreePython = createRequire(import.meta.url)(join(root, "../desktop/renderer/green-tree-python-tricks.js"));
const OverlayBallPython = createRequire(import.meta.url)(join(root, "../desktop/renderer/ball-python-tricks.js"));
const OverlayCornSnake = createRequire(import.meta.url)(join(root, "../desktop/renderer/corn-snake-tricks.js"));
const OverlayKingsnake = createRequire(import.meta.url)(join(root, "../desktop/renderer/kingsnake-tricks.js"));
const OverlayPhoenix = createRequire(import.meta.url)(join(root, "../desktop/renderer/phoenix-tricks.js"));
const OverlayGround = createRequire(import.meta.url)(join(root, "../desktop/renderer/ground-tricks.js"));
const OverlayRui = createRequire(import.meta.url)(join(root, "../desktop/renderer/rui-tricks.js"));
const OverlayRelay = createRequire(import.meta.url)(join(root, "../desktop/renderer/relay-tricks.js"));
const OverlayFuse = createRequire(import.meta.url)(join(root, "../desktop/renderer/fuse-tricks.js"));
const OverlayEarth = createRequire(import.meta.url)(join(root, "../desktop/renderer/earth-tricks.js"));
const OverlayCat = createRequire(import.meta.url)(join(root, "../desktop/renderer/cat-tricks.js"));
const OverlayDog = createRequire(import.meta.url)(join(root, "../desktop/renderer/dog-tricks.js"));
const OverlayRabbit = createRequire(import.meta.url)(join(root, "../desktop/renderer/rabbit-tricks.js"));
const OverlayHamster = createRequire(import.meta.url)(join(root, "../desktop/renderer/hamster-tricks.js"));
const OverlayGuineaPig = createRequire(import.meta.url)(join(root, "../desktop/renderer/guinea-pig-tricks.js"));
const OverlayTurtle = createRequire(import.meta.url)(join(root, "../desktop/renderer/turtle-tricks.js"));
const OverlayGoldfish = createRequire(import.meta.url)(join(root, "../desktop/renderer/goldfish-tricks.js"));
const OverlayBudgie = createRequire(import.meta.url)(join(root, "../desktop/renderer/budgie-tricks.js"));
const OverlayFox = createRequire(import.meta.url)(join(root, "../desktop/renderer/fox-tricks.js"));
const OverlayPenguin = createRequire(import.meta.url)(join(root, "../desktop/renderer/penguin-tricks.js"));
const OverlayParrot = createRequire(import.meta.url)(join(root, "../desktop/renderer/parrot-tricks.js"));
const OverlayFerret = createRequire(import.meta.url)(join(root, "../desktop/renderer/ferret-tricks.js"));
const OverlayHedgehog = createRequire(import.meta.url)(join(root, "../desktop/renderer/hedgehog-tricks.js"));
const OverlayChinchilla = createRequire(import.meta.url)(join(root, "../desktop/renderer/chinchilla-tricks.js"));
const OverlayAxolotl = createRequire(import.meta.url)(join(root, "../desktop/renderer/axolotl-tricks.js"));
const OverlayToucan = createRequire(import.meta.url)(join(root, "../desktop/renderer/toucan-tricks.js"));
const OverlayIguana = createRequire(import.meta.url)(join(root, "../desktop/renderer/iguana-tricks.js"));
const OverlayDragon = createRequire(import.meta.url)(join(root, "../desktop/renderer/dragon-tricks.js"));


test("Coral tricks start only on idle ground", () => {
  assert.deepEqual([...BallPython.TRICKS], ["orb", "nook", "taste", "inch", "unroll", "loom", "weave"]);
  assert.deepEqual([...Kingsnake.TRICKS], ["stripe", "audit", "verdict", "plumb", "raid", "band", "drawer"]);
  assert.deepEqual([...GreenTreePython.TRICKS], ["bracelet", "sway", "jewel", "heat", "bough", "liana", "arbor"]);
  assert.deepEqual([...Hognose.TRICKS], ["hood", "feign", "shovel", "gape", "encore", "quiver", "upright"]);
  assert.deepEqual([...Garter.TRICKS], ["seam", "rounds", "moss", "fork", "lap", "ribbon", "creek"]);
  assert.deepEqual([...Boa.TRICKS], ["pour", "heft", "oxbow", "slack", "bank", "anchor", "meander"]);
  assert.deepEqual([...T.TRICKS], ["rhyme", "rumor", "costume", "frank", "tile", "cipher", "verse"]);
  assert.equal(T.canStart({ asleep: false, hidden: false, leaving: false, cmd: "idle" }), true);
  assert.equal(T.canStart({ asleep: true, hidden: false, leaving: false, cmd: "idle" }), false);
  assert.equal(T.canStart({ asleep: false, hidden: true, leaving: false, cmd: "idle" }), false);
  assert.equal(T.canStart({ asleep: false, hidden: false, leaving: false, cmd: "sleep" }), false);
  assert.equal(T.canStart({ asleep: false, hidden: false, leaving: false, cmd: "seek" }), false);
  assert.equal(T.canStart({ asleep: false, hidden: false, leaving: false, cmd: "idle", windowPlay: true }), false);
  assert.equal(T.canStart({ asleep: false, hidden: false, leaving: false, cmd: "idle", card: true }), false);
  assert.equal(T.shouldAbort({ asleep: true, hidden: false, leaving: false, cmd: "idle" }), true);
  assert.equal(T.shouldAbort({ asleep: false, hidden: false, leaving: false, cmd: "idle", card: true }), true);
  assert.equal(T.shouldAbort({ asleep: false, hidden: false, leaving: false, cmd: "idle" }), false);
  assert.equal(T.pickTrick(0.99, true), "rhyme");
  assert.notEqual(T.pickTrick(0.3, false, "rhyme"), "orb");
  assert.notEqual(T.pickTrick(0.3, false, "rhyme"), "scribble");
  assert.notEqual(T.pickTrick(0.3, false, "rhyme"), "stripe");
  assert.notEqual(T.pickTrick(0.3, false, "rhyme"), "bracelet");
  assert.notEqual(T.pickTrick(0.3, false, "rhyme"), "hood");
  assert.notEqual(T.pickTrick(0.3, false, "rhyme"), "seam");
  assert.notEqual(T.pickTrick(0.3, false, "rhyme"), "pour");
  assert.equal(Overlay.TRICK_KEY, "milk_snake");
  assert.equal(T.sleepHoldFrame("milk_snake", 4), null);
  assert.equal(T.TRICKS.includes("mosaic"), false);
  assert.equal(T.TRICKS.includes("loop"), false);
  assert.equal(T.TRICKS.includes("patrol"), false);
  assert.equal(T.TRICKS.includes("stripe"), false);
  assert.equal(T.TRICKS.includes("hood"), false);
  assert.equal(T.TRICKS.includes("flip"), false);
  assert.equal(T.TRICKS.includes("saddle"), false);
  assert.equal(T.TRICKS.includes("drape"), false);
  assert.equal(T.TRICKS.includes("write"), false);
  assert.equal(T.TRICKS.includes("bun"), false);
  assert.equal(T.TRICKS.includes("orb"), false);
  assert.equal(T.TRICKS.includes("nook"), false);
  assert.equal(T.TRICKS.includes("taste"), false);
  assert.equal(T.TRICKS.includes("inch"), false);
  assert.equal(T.TRICKS.includes("unroll"), false);
  assert.equal(T.TRICKS.includes("thread"), false);
  assert.equal(T.TRICKS.includes("dart"), false);
  assert.equal(T.TRICKS.includes("noodle"), false);
  assert.equal(T.TRICKS.includes("flick"), false);
  assert.equal(T.TRICKS.includes("curl"), false);
  assert.equal(T.TRICKS.includes("coil"), false);
  assert.equal(T.TRICKS.includes("ball"), false);
  assert.equal(T.TRICKS.includes("perch"), false);
  assert.equal(T.TRICKS.includes("scent"), false);
  assert.equal(T.TRICKS.includes("stone"), false);
  assert.equal(T.TRICKS.includes("seam"), false);
  assert.equal(T.TRICKS.includes("gape"), false);
  assert.equal(T.TRICKS.includes("encore"), false);
});

test("rhyme/rumor/costume/frank/tile/cipher/verse are house-milk-snake-true, not copies of prior guests", () => {
  const ground = { asleep: false, hidden: false, leaving: false, cmd: "idle" };
  const rhyme = T.beginTrick("rhyme", 80, 1);
  assert.equal(rhyme.anim, "sit");
  assert.equal(rhyme.phase, "hold");
  const held = T.stepTrick(rhyme, 5, ground);
  assert.equal(held.phase, "hold");
  assert.equal(held.anim, "sit");
  assert.ok(held.rot !== 0 || Math.abs(held.lift) > 0.5);
  const release = T.stepTrick(rhyme, T.RHYME_HOLD + 0.2, ground);
  assert.equal(release.phase, "release");
  assert.equal(release.anim, "sit");
  const doneRhyme = T.stepTrick(rhyme, T.DUR.rhyme + 0.1, ground);
  assert.equal(doneRhyme.phase, "done");
  assert.ok(T.nextTrickWait(true, 0, "rhyme") > T.nextTrickWait(true, 0, "costume"));
  const frank = T.beginTrick("frank", 80, 1);
  assert.equal(frank.anim, "sit");
  const frankMid = T.stepTrick(frank, 0.5, ground);
  assert.ok(Math.abs(frankMid.lift) > 0.05 || Math.abs(frankMid.rot) > 1 || Math.abs(frankMid.x - 80) > 0.2);
  const tile = T.beginTrick("tile", 80, 1);
  assert.equal(tile.anim, "walk");
  const tileMid = T.stepTrick(tile, 0.55, ground);
  assert.ok(Math.abs(tileMid.lift) > 0.1 || Math.abs(tileMid.rot) > 1 || Math.abs(tileMid.x - 80) > 0.5);
  const rumor = T.beginTrick("rumor", 80, 1);
  assert.equal(rumor.anim, "talk");
  const rumorMid = T.stepTrick(rumor, 0.5, ground);
  assert.ok(Math.abs(rumorMid.lift) > 0.3 || Math.abs(rumorMid.rot) > 1 || Math.abs(rumorMid.x - 80) > 0.2);
  const costume = T.beginTrick("costume", 80, 1);
  assert.equal(costume.anim, "sit");
  const costumeMid = T.stepTrick(costume, 0.5, ground);
  assert.ok(Math.abs(costumeMid.lift) > 0.05 || Math.abs(costumeMid.rot) > 1 || Math.abs(costumeMid.x - 80) > 0.1);
  const costumeDone = T.stepTrick(costume, T.DUR.costume + 0.1, ground);
  assert.equal(costumeDone.phase, "done");
  const cipher = T.beginTrick("cipher", 80, 1);
  assert.equal(cipher.anim, "sit");
  const cipherMid = T.stepTrick(cipher, T.DUR.cipher * 0.45, ground);
  assert.ok(Math.abs(cipherMid.lift) > 0.8 || Math.abs(cipherMid.rot) > 4 || Math.abs(cipherMid.x - 80) > 0.3);
  const verse = T.beginTrick("verse", 80, 1);
  assert.equal(verse.anim, "talk");
  const verseMid = T.stepTrick(verse, T.DUR.verse * 0.4, ground);
  assert.ok(verseMid.lift > 2 || Math.abs(verseMid.rot) > 8 || Math.abs(verseMid.x - 80) > 1);
  assert.equal(T.TRICKS.includes("mosaic"), false);
  assert.equal(T.TRICKS.includes("mimic"), false);
  assert.equal(T.TRICKS.includes("hide"), false);
  assert.equal(T.TRICKS.includes("tuck"), false);
  assert.equal(T.TRICKS.includes("nook"), false);
  assert.equal(T.TRICKS.includes("stripe"), false);
  assert.equal(T.TRICKS.includes("pour"), false);
  assert.equal(T.TRICKS.includes("pebble"), false);
  const aborted = T.stepTrick(held, 0.1, { asleep: true, cmd: "sleep" });
  assert.equal(aborted.phase, "done");
  for (const mod of [Rui, Cat, Dog, Rabbit, Hamster, GuineaPig, Turtle, Goldfish, Budgie, Fox, Penguin, Parrot, Ferret, Hedgehog, Chinchilla, Axolotl, Toucan, Iguana, Dragon, Phoenix, BallPython, CornSnake, Kingsnake, GreenTreePython, Hognose, Garter, Boa, Relay, Fuse, Earth]) {
    assert.equal(mod.TRICKS.includes("rhyme"), false);
    assert.equal(mod.TRICKS.includes("rumor"), false);
    assert.equal(mod.TRICKS.includes("costume"), false);
    assert.equal(mod.TRICKS.includes("frank"), false);
    assert.equal(mod.TRICKS.includes("tile"), false);
    assert.equal(mod.TRICKS.includes("cipher"), false);
    assert.equal(mod.TRICKS.includes("verse"), false);
  }
  assert.deepEqual([...BallPython.TRICKS], ["orb", "nook", "taste", "inch", "unroll", "loom", "weave"]);
  assert.deepEqual([...CornSnake.TRICKS], ["scribble", "gap", "comma", "probe", "canyon", "blotter", "pencil"]);
  assert.deepEqual([...Kingsnake.TRICKS], ["stripe", "audit", "verdict", "plumb", "raid", "band", "drawer"]);
  assert.deepEqual([...GreenTreePython.TRICKS], ["bracelet", "sway", "jewel", "heat", "bough", "liana", "arbor"]);
  assert.deepEqual([...Hognose.TRICKS], ["hood", "feign", "shovel", "gape", "encore", "quiver", "upright"]);
  assert.deepEqual([...Garter.TRICKS], ["seam", "rounds", "moss", "fork", "lap", "ribbon", "creek"]);
  assert.deepEqual([...Boa.TRICKS], ["pour", "heft", "oxbow", "slack", "bank", "anchor", "meander"]);
  assert.deepEqual([...Dragon.TRICKS], ["sprawl", "guard", "smolder", "claim", "fold", "ruff", "scrape"]);
  assert.deepEqual([...Phoenix.TRICKS], ["cinder", "blaze", "shed", "lift", "return", "reignite", "hearth"]);
  assert.equal(T.TRICKS.includes("mosaic"), false);
  assert.equal(T.TRICKS.includes("loop"), false);
  assert.equal(T.TRICKS.includes("pour"), false);
  assert.equal(T.TRICKS.includes("stripe"), false);
  assert.equal(T.TRICKS.includes("flip"), false);
  assert.equal(T.TRICKS.includes("write"), false);
  assert.equal(Parrot.TRICKS.includes("flash"), true);
});

test("Coral feed-happy is its own sit: postmark/cachet/courtesy, and two feeds are not the same", () => {
  assert.deepEqual([...T.HAPPY], ["postmark", "cachet", "courtesy"]);
  assert.equal(T.HAPPY.includes("savor"), false);
  assert.equal(T.HAPPY.includes("nestle"), false);
  assert.equal(T.HAPPY.includes("center"), false);
  assert.equal(T.HAPPY.includes("settle"), false);
  assert.equal(T.HAPPY.includes("shine"), false);
  assert.equal(T.HAPPY.includes("purr"), false);
  assert.equal(T.HAPPY.includes("tribute"), false);
  assert.equal(T.HAPPY.includes("clause"), false);
  assert.equal(T.HAPPY.includes("aside"), false);
  assert.equal(T.HAPPY.includes("cue"), false);
  assert.equal(T.HAPPY.includes("ovation"), false);
  assert.equal(T.HAPPY.includes("copy"), false);
  assert.equal(T.HAPPY.includes("brief"), false);
  assert.equal(T.HAPPY.includes("visa"), false);
  assert.equal(T.HAPPY.includes("harbor"), false);
  assert.equal(T.HAPPY.includes("cradle"), false);
  assert.equal(T.HAPPY.includes("stay"), false);
  assert.equal(T.pickHappy("postmark", 0), "cachet");
  assert.notEqual(T.pickHappy("postmark", 0.9), "postmark");
  assert.equal(Overlay.pickHappy("cachet", 0) !== "cachet", true);
  assert.equal(T.happyCanStart({ asleep: false, hidden: false, leaving: false, cmd: "idle" }), true);
  assert.equal(T.happyCanStart({ asleep: false, hidden: false, leaving: false, cmd: "idle", card: true }), true);
  assert.equal(T.happyCanStart({ asleep: true, hidden: false, leaving: false, cmd: "idle" }), false);
  assert.equal(T.happyShouldAbort({ cmd: "sleep" }), true);
  assert.equal(T.happyShouldAbort({ cmd: "hide" }), true);
  assert.equal(T.happyShouldAbort({ card: true, cmd: "idle" }), false);
  const postmark = T.beginHappy("postmark", 80, 1);
  assert.equal(postmark.anim, "sit");
  const postmarkMid = T.stepHappy(postmark, 0.4, { cmd: "idle" });
  assert.ok(postmarkMid.lift !== 0 || Math.abs(postmarkMid.rot) > 0.5);
  assert.notEqual(postmarkMid.phase, "done");
  const cachet = T.beginHappy("cachet", 80, 1);
  assert.equal(cachet.anim, "sit");
  const cachetMid = T.stepHappy(cachet, 0.3, { cmd: "idle" });
  assert.ok(cachetMid.lift > 0.2 || Math.abs(cachetMid.rot) > 0.5);
  const courtesyH = T.beginHappy("courtesy", 80, 1);
  assert.equal(courtesyH.anim, "talk");
  const done = T.stepHappy(postmark, T.HAPPY_DUR.postmark + 0.1, { cmd: "idle" });
  assert.equal(done.phase, "done");
  const aborted = T.stepHappy(cachetMid, 0.1, { asleep: true, cmd: "sleep" });
  assert.equal(aborted.phase, "done");
  assert.equal(aborted.abort, true);
  assert.equal(T.wantsThankYou("milk_snake"), true);
  assert.equal(T.wantsThankYou("coral"), true);
  assert.equal(T.wantsThankYou("ball_python"), false);
  assert.equal(T.wantsThankYou("nori"), false);
  assert.equal(T.wantsThankYou("kingsnake"), false);
  assert.equal(T.wantsThankYou("hognose"), false);
  assert.equal(T.wantsThankYou("garter"), false);
  assert.equal(T.wantsThankYou("phoenix"), false);
  const thanks = T.startThankYou("milk_snake", "postmark", 80, 1, { cmd: "idle", card: true, windowPlay: true });
  assert.ok(thanks);
  assert.notEqual(thanks.kind, "postmark");
  assert.ok(thanks.happy.lift === 0);
  assert.notEqual(thanks.happy.anim, "eat");
  assert.notEqual(thanks.happy.anim, "idle");
  const thanksMid = T.stepHappy(thanks.happy, 0.35, { cmd: "idle", card: true });
  assert.ok(thanksMid.lift !== 0 || Math.abs(thanksMid.rot) > 0.5, "a thank-you postmarks or cachets");
  const blocked = T.startThankYou("milk_snake", "tribute", 80, 1, { asleep: true, cmd: "idle" });
  assert.equal(blocked, null);
  const other = T.startThankYou("hognose", null, 80, 1, { cmd: "idle" });
  assert.equal(other, null);
  const second = T.startThankYou("milk_snake", thanks.kind, 80, 1, { cmd: "idle", card: true });
  assert.ok(second);
  assert.notEqual(second.kind, thanks.kind);
});

test("ground registry keeps prior guests gated; Coral selectable; prior guests still OK", () => {
  assert.equal(Rui.TRICK_KEY, "red_panda");
  assert.equal(BallPython.TRICK_KEY, "ball_python");
  assert.equal(Kingsnake.TRICK_KEY, "kingsnake");
  assert.equal(Hognose.TRICK_KEY, "hognose");
  assert.equal(Garter.TRICK_KEY, "garter");
  assert.equal(Boa.TRICK_KEY, "boa");
  assert.equal(T.TRICK_KEY, "milk_snake");
  assert.deepEqual([...Rui.TRICKS], ["somersault", "lie", "scratch", "wave", "dance"]);
  assert.deepEqual([...BallPython.TRICKS], ["orb", "nook", "taste", "inch", "unroll", "loom", "weave"]);
  assert.deepEqual([...CornSnake.TRICKS], ["scribble", "gap", "comma", "probe", "canyon", "blotter", "pencil"]);
  assert.deepEqual([...Kingsnake.TRICKS], ["stripe", "audit", "verdict", "plumb", "raid", "band", "drawer"]);
  assert.deepEqual([...GreenTreePython.TRICKS], ["bracelet", "sway", "jewel", "heat", "bough", "liana", "arbor"]);
  assert.deepEqual([...Hognose.TRICKS], ["hood", "feign", "shovel", "gape", "encore", "quiver", "upright"]);
  assert.deepEqual([...Garter.TRICKS], ["seam", "rounds", "moss", "fork", "lap", "ribbon", "creek"]);
  assert.deepEqual([...Boa.TRICKS], ["pour", "heft", "oxbow", "slack", "bank", "anchor", "meander"]);
  assert.deepEqual([...Phoenix.TRICKS], ["cinder", "blaze", "shed", "lift", "return", "reignite", "hearth"]);
  assert.deepEqual([...T.TRICKS], ["rhyme", "rumor", "costume", "frank", "tile", "cipher", "verse"]);
  assert.equal(T.wantsThankYou("milk_snake"), true);
  assert.equal(T.wantsThankYou("coral"), true);
  assert.equal(BallPython.wantsThankYou("nori"), true);
  assert.equal(Kingsnake.wantsThankYou("bandit"), true);
  assert.equal(Hognose.wantsThankYou("bluff"), true);
  assert.equal(Garter.wantsThankYou("sash"), true);
  assert.equal(Rui.sleepHoldFrame("red_panda", 4), 1);
  assert.equal(T.sleepHoldFrame("milk_snake", 4), null);
  globalThis.PetRuiTricks = OverlayRui;
  globalThis.PetRelayTricks = OverlayRelay;
  globalThis.PetFuseTricks = OverlayFuse;
  globalThis.PetEarthTricks = OverlayEarth;
  globalThis.PetCatTricks = OverlayCat;
  globalThis.PetDogTricks = OverlayDog;
  globalThis.PetRabbitTricks = OverlayRabbit;
  globalThis.PetHamsterTricks = OverlayHamster;
  globalThis.PetGuineaPigTricks = OverlayGuineaPig;
  globalThis.PetTurtleTricks = OverlayTurtle;
  globalThis.PetGoldfishTricks = OverlayGoldfish;
  globalThis.PetBudgieTricks = OverlayBudgie;
  globalThis.PetFoxTricks = OverlayFox;
  globalThis.PetPenguinTricks = OverlayPenguin;
  globalThis.PetParrotTricks = OverlayParrot;
  globalThis.PetFerretTricks = OverlayFerret;
  globalThis.PetHedgehogTricks = OverlayHedgehog;
  globalThis.PetChinchillaTricks = OverlayChinchilla;
  globalThis.PetAxolotlTricks = OverlayAxolotl;
  globalThis.PetToucanTricks = OverlayToucan;
  globalThis.PetIguanaTricks = OverlayIguana;
  globalThis.PetDragonTricks = OverlayDragon;
  globalThis.PetPhoenixTricks = OverlayPhoenix;
  globalThis.PetBallPythonTricks = OverlayBallPython;
  globalThis.PetCornSnakeTricks = OverlayCornSnake;
  globalThis.PetKingsnakeTricks = OverlayKingsnake;
  globalThis.PetGreenTreePythonTricks = OverlayGreenTreePython;
  globalThis.PetHognoseTricks = OverlayHognose;
  globalThis.PetGarterTricks = OverlayGarter;
  globalThis.PetBoaTricks = OverlayBoa;
  globalThis.PetMilkSnakeTricks = Overlay;
  assert.equal(OverlayGround.tricksFor("red_panda"), OverlayRui);
  assert.equal(OverlayGround.tricksFor("rui"), OverlayRui);
  assert.equal(OverlayGround.tricksFor("relay_dragon"), OverlayRelay);
  assert.equal(OverlayGround.tricksFor("fuse_dragon"), OverlayFuse);
  assert.equal(OverlayGround.tricksFor("ground_dragon"), OverlayEarth);
  assert.equal(OverlayGround.tricksFor("cat"), OverlayCat);
  assert.equal(OverlayGround.tricksFor("miso"), OverlayCat);
  assert.equal(OverlayGround.tricksFor("dog"), OverlayDog);
  assert.equal(OverlayGround.tricksFor("pip"), OverlayDog);
  assert.equal(OverlayGround.tricksFor("rabbit"), OverlayRabbit);
  assert.equal(OverlayGround.tricksFor("thimble"), OverlayRabbit);
  assert.equal(OverlayGround.tricksFor("hamster"), OverlayHamster);
  assert.equal(OverlayGround.tricksFor("clip"), OverlayHamster);
  assert.equal(OverlayGround.tricksFor("guinea_pig"), OverlayGuineaPig);
  assert.equal(OverlayGround.tricksFor("whee"), OverlayGuineaPig);
  assert.equal(OverlayGround.tricksFor("turtle"), OverlayTurtle);
  assert.equal(OverlayGround.tricksFor("ink"), OverlayTurtle);
  assert.equal(OverlayGround.tricksFor("goldfish"), OverlayGoldfish);
  assert.equal(OverlayGround.tricksFor("coin"), OverlayGoldfish);
  assert.equal(OverlayGround.tricksFor("budgie"), OverlayBudgie);
  assert.equal(OverlayGround.tricksFor("echo"), OverlayBudgie);
  assert.equal(OverlayGround.tricksFor("fox"), OverlayFox);
  assert.equal(OverlayGround.tricksFor("rue"), OverlayFox);
  assert.equal(OverlayGround.tricksFor("penguin"), OverlayPenguin);
  assert.equal(OverlayGround.tricksFor("peck"), OverlayPenguin);
  assert.equal(OverlayGround.tricksFor("parrot"), OverlayParrot);
  assert.equal(OverlayGround.tricksFor("quill"), OverlayParrot);
  assert.equal(OverlayGround.tricksFor("ferret"), OverlayFerret);
  assert.equal(OverlayGround.tricksFor("wick"), OverlayFerret);
  assert.equal(OverlayGround.tricksFor("hedgehog"), OverlayHedgehog);
  assert.equal(OverlayGround.tricksFor("burr"), OverlayHedgehog);
  assert.equal(OverlayGround.tricksFor("chinchilla"), OverlayChinchilla);
  assert.equal(OverlayGround.tricksFor("floss"), OverlayChinchilla);
  assert.equal(OverlayGround.tricksFor("axolotl"), OverlayAxolotl);
  assert.equal(OverlayGround.tricksFor("bloom"), OverlayAxolotl);
  assert.equal(OverlayGround.tricksFor("toucan"), OverlayToucan);
  assert.equal(OverlayGround.tricksFor("keel"), OverlayToucan);
  assert.equal(OverlayGround.tricksFor("iguana"), OverlayIguana);
  assert.equal(OverlayGround.tricksFor("sol"), OverlayIguana);
  assert.equal(OverlayGround.tricksFor("dragon"), OverlayDragon);
  assert.equal(OverlayGround.tricksFor("vesper"), OverlayDragon);
  assert.equal(OverlayGround.tricksFor("phoenix"), OverlayPhoenix);
  assert.equal(OverlayGround.tricksFor("ember"), OverlayPhoenix);
  assert.equal(OverlayGround.tricksFor("ball_python"), OverlayBallPython);
  assert.equal(OverlayGround.tricksFor("nori"), OverlayBallPython);
  assert.equal(OverlayGround.tricksFor("corn_snake"), OverlayCornSnake);
  assert.equal(OverlayGround.tricksFor("saffron"), OverlayCornSnake);
  assert.equal(OverlayGround.tricksFor("kingsnake"), OverlayKingsnake);
  assert.equal(OverlayGround.tricksFor("bandit"), OverlayKingsnake);
  assert.equal(OverlayGround.tricksFor("green_tree_python"), OverlayGreenTreePython);
  assert.equal(OverlayGround.tricksFor("jade"), OverlayGreenTreePython);
  assert.equal(OverlayGround.tricksFor("hognose"), OverlayHognose);
  assert.equal(OverlayGround.tricksFor("bluff"), OverlayHognose);
  assert.equal(OverlayGround.tricksFor("garter"), OverlayGarter);
  assert.equal(OverlayGround.tricksFor("sash"), OverlayGarter);
  assert.equal(OverlayGround.tricksFor("boa"), OverlayBoa);
  assert.equal(OverlayGround.tricksFor("lula"), OverlayBoa);
  assert.equal(OverlayGround.tricksFor("milk_snake"), Overlay);
  assert.equal(OverlayGround.tricksFor("coral"), Overlay);
  assert.equal(OverlayGround.wantsThankYou("red_panda"), true);
  assert.equal(OverlayGround.wantsThankYou("cat"), true);
  assert.equal(OverlayGround.wantsThankYou("miso"), true);
  assert.equal(OverlayGround.wantsThankYou("dog"), true);
  assert.equal(OverlayGround.wantsThankYou("pip"), true);
  assert.equal(OverlayGround.wantsThankYou("ball_python"), true);
  assert.equal(OverlayGround.wantsThankYou("nori"), true);
  assert.equal(OverlayGround.wantsThankYou("corn_snake"), true);
  assert.equal(OverlayGround.wantsThankYou("saffron"), true);
  assert.equal(OverlayGround.wantsThankYou("kingsnake"), true);
  assert.equal(OverlayGround.wantsThankYou("bandit"), true);
  assert.equal(OverlayGround.wantsThankYou("hognose"), true);
  assert.equal(OverlayGround.wantsThankYou("bluff"), true);
  assert.equal(OverlayGround.wantsThankYou("garter"), true);
  assert.equal(OverlayGround.wantsThankYou("sash"), true);
  assert.equal(OverlayGround.wantsThankYou("boa"), true);
  assert.equal(OverlayGround.wantsThankYou("lula"), true);
  assert.equal(OverlayGround.wantsThankYou("milk_snake"), true);
  assert.equal(OverlayGround.wantsThankYou("coral"), true);
  assert.equal(OverlayGround.wantsThankYou("phoenix"), true);
  assert.equal(OverlayGround.wantsThankYou("ember"), true);
  assert.equal(OverlayGround.sleepHoldFrame("red_panda", 4), 1);
  assert.equal(OverlayGround.sleepHoldFrame("ball_python", 4), null);
  assert.equal(OverlayGround.sleepHoldFrame("kingsnake", 4), null);
  assert.equal(OverlayGround.sleepHoldFrame("hognose", 4), null);
  assert.equal(OverlayGround.sleepHoldFrame("garter", 4), null);
  assert.equal(OverlayGround.sleepHoldFrame("boa", 4), null);
  assert.equal(OverlayGround.sleepHoldFrame("milk_snake", 4), null);
  assert.deepEqual([...OverlayBallPython.TRICKS], ["orb", "nook", "taste", "inch", "unroll", "loom", "weave"]);
  assert.deepEqual([...OverlayCornSnake.TRICKS], ["scribble", "gap", "comma", "probe", "canyon", "blotter", "pencil"]);
  assert.deepEqual([...OverlayKingsnake.TRICKS], ["stripe", "audit", "verdict", "plumb", "raid", "band", "drawer"]);
  assert.deepEqual([...OverlayGreenTreePython.TRICKS], ["bracelet", "sway", "jewel", "heat", "bough", "liana", "arbor"]);
  assert.deepEqual([...OverlayHognose.TRICKS], ["hood", "feign", "shovel", "gape", "encore", "quiver", "upright"]);
  assert.deepEqual([...OverlayGarter.TRICKS], ["seam", "rounds", "moss", "fork", "lap", "ribbon", "creek"]);
  assert.deepEqual([...OverlayBoa.TRICKS], ["pour", "heft", "oxbow", "slack", "bank", "anchor", "meander"]);
  assert.deepEqual([...Overlay.TRICKS], ["rhyme", "rumor", "costume", "frank", "tile", "cipher", "verse"]);
  assert.equal(Overlay.TRICKS.includes("orb"), false);
  assert.equal(Overlay.TRICKS.includes("write"), false);
  assert.equal(Overlay.TRICKS.includes("flip"), false);
  assert.equal(Overlay.TRICKS.includes("loop"), false);
  assert.equal(Overlay.TRICKS.includes("mosaic"), false);
  assert.equal(Overlay.TRICKS.includes("patrol"), false);
  assert.equal(Overlay.TRICKS.includes("bracelet"), false);
  assert.equal(Overlay.TRICKS.includes("scribble"), false);
  assert.equal(Overlay.TRICKS.includes("stripe"), false);
  assert.equal(Overlay.TRICKS.includes("hood"), false);
  assert.equal(Overlay.TRICKS.includes("seam"), false);
  assert.equal(Overlay.TRICKS.includes("pour"), false);
  assert.equal(Overlay.TRICKS.includes("mimic"), false);
});

test("ultra-polish: Coral rhyme/cipher/verse lifts are Rui-visible (not micro idle-gen)", () => {
  const rh = T.beginTrick("rhyme", 80, 1);
  const mid = T.stepTrick(rh, 5, { cmd: "idle" });
  assert.ok(Math.abs(mid.rot) > 10, `rhyme mid rot ${mid.rot}`);
  assert.ok(Math.abs(mid.lift) > 0.5, `rhyme mid lift ${mid.lift}`);
  const ci = T.beginTrick("cipher", 80, 1);
  const c2 = T.stepTrick(ci, T.DUR.cipher * 0.45, { cmd: "idle" });
  assert.ok(Math.abs(c2.lift) > 0.8 || Math.abs(c2.rot) > 4 || Math.abs(c2.x - 80) > 0.3, `cipher mid ${c2.lift}/${c2.rot}/${c2.x}`);
  const lg = T.beginTrick("verse", 80, 1);
  const l2 = T.stepTrick(lg, T.DUR.verse * 0.4, { cmd: "idle" });
  assert.ok(l2.lift > 2 || Math.abs(l2.rot) > 8 || Math.abs(l2.x - 80) > 1, `verse mid ${l2.lift}/${l2.rot}/${l2.x}`);
  const cos = T.beginTrick("costume", 80, 1);
  const o2 = T.stepTrick(cos, T.DUR.costume * 0.4, { cmd: "idle" });
  assert.ok(o2.lift > 0.5 || Math.abs(o2.rot) > 4 || Math.abs(o2.x - 80) > 0.5, `costume mid ${o2.lift}/${o2.rot}/${o2.x}`);
  assert.ok(Overlay.cipherPose && Overlay.versePose);
  assert.deepEqual([...T.TRICKS], [...Overlay.TRICKS]);
  assert.equal(T.RHYME_HOLD, Overlay.RHYME_HOLD);
  assert.equal(T.RHYME_HOLD, 11.2);
  assert.equal(T.RELEASE_S, 1.18);
  assert.ok(T.nextTrickWait(true, 0, "rhyme") > 39);
});

test("notes: Coral Rui-dense ultra (RHYME_HOLD=11.2); Blush densified; Atlas densified; Cup densified; next leftover Sepia / cuttlefish", () => {
  assert.equal(T.TRICK_KEY, "milk_snake");
  assert.equal(T.wantsThankYou("coral"), true);
  assert.equal(OverlayGround.tricksFor("boa"), OverlayBoa);
  assert.equal(OverlayGround.tricksFor("lula"), OverlayBoa);
  assert.equal(OverlayGround.wantsThankYou("boa"), true);
  assert.equal(OverlayGround.wantsThankYou("lula"), true);
  assert.equal(OverlayGround.tricksFor("garter"), OverlayGarter);
  assert.equal(OverlayGround.tricksFor("sash"), OverlayGarter);
  assert.equal(OverlayGround.wantsThankYou("garter"), true);
  assert.equal(OverlayGround.wantsThankYou("sash"), true);
  assert.equal(OverlayGround.tricksFor("hognose"), OverlayHognose);
  assert.equal(OverlayGround.tricksFor("bluff"), OverlayHognose);
  assert.equal(OverlayGround.tricksFor("milk_snake"), Overlay);
  assert.equal(OverlayGround.tricksFor("coral"), Overlay);
  assert.equal(OverlayGround.wantsThankYou("milk_snake"), true);
  assert.equal(OverlayGround.wantsThankYou("coral"), true);
  assert.equal(OverlayGround.tricksFor("green_tree_python"), OverlayGreenTreePython);
  assert.equal(OverlayGround.tricksFor("jade"), OverlayGreenTreePython);
  assert.equal(OverlayGround.wantsThankYou("green_tree_python"), true);
  assert.equal(OverlayGround.wantsThankYou("jade"), true);
  assert.equal(OverlayGround.tricksFor("kingsnake"), OverlayKingsnake);
  assert.equal(OverlayGround.tricksFor("bandit"), OverlayKingsnake);
  assert.equal(OverlayGround.wantsThankYou("kingsnake"), true);
  assert.equal(OverlayGround.wantsThankYou("bandit"), true);
  assert.equal(OverlayGround.tricksFor("corn_snake"), OverlayCornSnake);
  assert.equal(OverlayGround.tricksFor("saffron"), OverlayCornSnake);
  assert.equal(OverlayGround.wantsThankYou("corn_snake"), true);
  assert.equal(OverlayGround.wantsThankYou("saffron"), true);
  assert.equal(OverlayGround.tricksFor("ball_python"), OverlayBallPython);
  assert.equal(OverlayGround.tricksFor("nori"), OverlayBallPython);
  assert.equal(OverlayGround.wantsThankYou("ball_python"), true);
  assert.equal(OverlayGround.wantsThankYou("nori"), true);
  assert.equal(OverlayGround.tricksFor("rosy_boa") == null, true);
  assert.equal(OverlayGround.wantsThankYou("rosy_boa"), false);
  assert.equal(OverlayGround.tricksFor("blush") == null, true);
});
