import assert from "node:assert/strict";
import { createRequire } from "node:module";
import { dirname, join } from "node:path";
import { test } from "node:test";
import { fileURLToPath, pathToFileURL } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const T = await import(pathToFileURL(join(root, "src/lib/pets/moon_jelly-tricks.ts")).href);
const Nautilus = await import(pathToFileURL(join(root, "src/lib/pets/nautilus-tricks.ts")).href);
const Cuttlefish = await import(pathToFileURL(join(root, "src/lib/pets/cuttlefish-tricks.ts")).href);
const Octopus = await import(pathToFileURL(join(root, "src/lib/pets/octopus-tricks.ts")).href);
const CarpetPython = await import(pathToFileURL(join(root, "src/lib/pets/carpet-python-tricks.ts")).href);
const RosyBoa = await import(pathToFileURL(join(root, "src/lib/pets/rosy-boa-tricks.ts")).href);
const MilkSnake = await import(pathToFileURL(join(root, "src/lib/pets/milk-snake-tricks.ts")).href);
const Garter = await import(pathToFileURL(join(root, "src/lib/pets/garter-tricks.ts")).href);
const Boa = await import(pathToFileURL(join(root, "src/lib/pets/boa-tricks.ts")).href);
const Hognose = await import(pathToFileURL(join(root, "src/lib/pets/hognose-tricks.ts")).href);
const GreenTreePython = await import(pathToFileURL(join(root, "src/lib/pets/green-tree-python-tricks.ts")).href);
const BallPython = await import(pathToFileURL(join(root, "src/lib/pets/ball-python-tricks.ts")).href);
const CornSnake = await import(pathToFileURL(join(root, "src/lib/pets/corn-snake-tricks.ts")).href);
const Kingsnake = await import(pathToFileURL(join(root, "src/lib/pets/kingsnake-tricks.ts")).href);
const Phoenix = await import(pathToFileURL(join(root, "src/lib/pets/phoenix-tricks.ts")).href);
const Dragon = await import(pathToFileURL(join(root, "src/lib/pets/dragon-tricks.ts")).href);
const Rui = await import(pathToFileURL(join(root, "src/lib/pets/rui-tricks.ts")).href);
const Relay = await import(pathToFileURL(join(root, "src/lib/pets/relay-tricks.ts")).href);
const Fuse = await import(pathToFileURL(join(root, "src/lib/pets/fuse-tricks.ts")).href);
const Earth = await import(pathToFileURL(join(root, "src/lib/pets/earth-tricks.ts")).href);
const Cat = await import(pathToFileURL(join(root, "src/lib/pets/cat-tricks.ts")).href);
const Dog = await import(pathToFileURL(join(root, "src/lib/pets/dog-tricks.ts")).href);
const Rabbit = await import(pathToFileURL(join(root, "src/lib/pets/rabbit-tricks.ts")).href);
const Hamster = await import(pathToFileURL(join(root, "src/lib/pets/hamster-tricks.ts")).href);
const GuineaPig = await import(pathToFileURL(join(root, "src/lib/pets/guinea-pig-tricks.ts")).href);
const Turtle = await import(pathToFileURL(join(root, "src/lib/pets/turtle-tricks.ts")).href);
const Goldfish = await import(pathToFileURL(join(root, "src/lib/pets/goldfish-tricks.ts")).href);
const Budgie = await import(pathToFileURL(join(root, "src/lib/pets/budgie-tricks.ts")).href);
const Fox = await import(pathToFileURL(join(root, "src/lib/pets/fox-tricks.ts")).href);
const Penguin = await import(pathToFileURL(join(root, "src/lib/pets/penguin-tricks.ts")).href);
const Parrot = await import(pathToFileURL(join(root, "src/lib/pets/parrot-tricks.ts")).href);
const Ferret = await import(pathToFileURL(join(root, "src/lib/pets/ferret-tricks.ts")).href);
const Hedgehog = await import(pathToFileURL(join(root, "src/lib/pets/hedgehog-tricks.ts")).href);
const Chinchilla = await import(pathToFileURL(join(root, "src/lib/pets/chinchilla-tricks.ts")).href);
const Axolotl = await import(pathToFileURL(join(root, "src/lib/pets/axolotl-tricks.ts")).href);
const Toucan = await import(pathToFileURL(join(root, "src/lib/pets/toucan-tricks.ts")).href);
const Iguana = await import(pathToFileURL(join(root, "src/lib/pets/iguana-tricks.ts")).href);
const Overlay = createRequire(import.meta.url)(join(root, "../desktop/renderer/moon_jelly-tricks.js"));
const OverlayNautilus = createRequire(import.meta.url)(join(root, "../desktop/renderer/nautilus-tricks.js"));
const OverlayCuttlefish = createRequire(import.meta.url)(join(root, "../desktop/renderer/cuttlefish-tricks.js"));
const OverlayOctopus = createRequire(import.meta.url)(join(root, "../desktop/renderer/octopus-tricks.js"));
const OverlayCarpetPython = createRequire(import.meta.url)(join(root, "../desktop/renderer/carpet-python-tricks.js"));
const OverlayRosyBoa = createRequire(import.meta.url)(join(root, "../desktop/renderer/rosy-boa-tricks.js"));
const OverlayMilkSnake = createRequire(import.meta.url)(join(root, "../desktop/renderer/milk-snake-tricks.js"));
const OverlayGarter = createRequire(import.meta.url)(join(root, "../desktop/renderer/garter-tricks.js"));
const OverlayBoa = createRequire(import.meta.url)(join(root, "../desktop/renderer/boa-tricks.js"));
const OverlayHognose = createRequire(import.meta.url)(join(root, "../desktop/renderer/hognose-tricks.js"));
const OverlayGreenTreePython = createRequire(import.meta.url)(join(root, "../desktop/renderer/green-tree-python-tricks.js"));
const OverlayBallPython = createRequire(import.meta.url)(join(root, "../desktop/renderer/ball-python-tricks.js"));
const OverlayCornSnake = createRequire(import.meta.url)(join(root, "../desktop/renderer/corn-snake-tricks.js"));
const OverlayKingsnake = createRequire(import.meta.url)(join(root, "../desktop/renderer/kingsnake-tricks.js"));
const OverlayPhoenix = createRequire(import.meta.url)(join(root, "../desktop/renderer/phoenix-tricks.js"));
const OverlayGround = createRequire(import.meta.url)(join(root, "../desktop/renderer/ground-tricks.js"));
const OverlayRui = createRequire(import.meta.url)(join(root, "../desktop/renderer/rui-tricks.js"));
const OverlayRelay = createRequire(import.meta.url)(join(root, "../desktop/renderer/relay-tricks.js"));
const OverlayFuse = createRequire(import.meta.url)(join(root, "../desktop/renderer/fuse-tricks.js"));
const OverlayEarth = createRequire(import.meta.url)(join(root, "../desktop/renderer/earth-tricks.js"));
const OverlayCat = createRequire(import.meta.url)(join(root, "../desktop/renderer/cat-tricks.js"));
const OverlayDog = createRequire(import.meta.url)(join(root, "../desktop/renderer/dog-tricks.js"));
const OverlayRabbit = createRequire(import.meta.url)(join(root, "../desktop/renderer/rabbit-tricks.js"));
const OverlayHamster = createRequire(import.meta.url)(join(root, "../desktop/renderer/hamster-tricks.js"));
const OverlayGuineaPig = createRequire(import.meta.url)(join(root, "../desktop/renderer/guinea-pig-tricks.js"));
const OverlayTurtle = createRequire(import.meta.url)(join(root, "../desktop/renderer/turtle-tricks.js"));
const OverlayGoldfish = createRequire(import.meta.url)(join(root, "../desktop/renderer/goldfish-tricks.js"));
const OverlayBudgie = createRequire(import.meta.url)(join(root, "../desktop/renderer/budgie-tricks.js"));
const OverlayFox = createRequire(import.meta.url)(join(root, "../desktop/renderer/fox-tricks.js"));
const OverlayPenguin = createRequire(import.meta.url)(join(root, "../desktop/renderer/penguin-tricks.js"));
const OverlayParrot = createRequire(import.meta.url)(join(root, "../desktop/renderer/parrot-tricks.js"));
const OverlayFerret = createRequire(import.meta.url)(join(root, "../desktop/renderer/ferret-tricks.js"));
const OverlayHedgehog = createRequire(import.meta.url)(join(root, "../desktop/renderer/hedgehog-tricks.js"));
const OverlayChinchilla = createRequire(import.meta.url)(join(root, "../desktop/renderer/chinchilla-tricks.js"));
const OverlayAxolotl = createRequire(import.meta.url)(join(root, "../desktop/renderer/axolotl-tricks.js"));
const OverlayToucan = createRequire(import.meta.url)(join(root, "../desktop/renderer/toucan-tricks.js"));
const OverlayIguana = createRequire(import.meta.url)(join(root, "../desktop/renderer/iguana-tricks.js"));
const OverlayDragon = createRequire(import.meta.url)(join(root, "../desktop/renderer/dragon-tricks.js"));

test("Pulse tricks start only on idle ground", () => {
  assert.deepEqual([...Turtle.TRICKS], ["soak", "tuck", "crane", "plod", "paddle", "snorkel", "wipe"]);
  assert.deepEqual([...Goldfish.TRICKS], ["drift", "gulp", "flare", "glint", "dart", "yawn", "forage"]);
  assert.deepEqual([...Axolotl.TRICKS], ["gill", "amble", "mend", "smile", "plume", "sprout", "glop"]);
  assert.deepEqual([...Octopus.TRICKS], ["mantle", "sucker", "jet", "veil", "tinker", "papilla", "ooze"]);
  assert.deepEqual([...Cuttlefish.TRICKS], ["bone", "pupil", "chroma", "hover", "blot", "strike", "zebra"]);
  assert.deepEqual([...Nautilus.TRICKS], ["spiral", "siphuncle", "nacre", "pinhole", "fringe", "hyponome", "aperture"]);
  assert.deepEqual([...CarpetPython.TRICKS], ["legend", "rung", "contour", "runner", "bearing", "canopy", "inset"]);
  assert.deepEqual([...T.TRICKS], ["bell", "oral", "lucent", "trail", "medusa", "rhopalium", "horseshoe"]);
  assert.equal(T.canStart({ asleep: false, hidden: false, leaving: false, cmd: "idle" }), true);
  assert.equal(T.canStart({ asleep: true, hidden: false, leaving: false, cmd: "idle" }), false);
  assert.equal(T.canStart({ asleep: false, hidden: true, leaving: false, cmd: "idle" }), false);
  assert.equal(T.canStart({ asleep: false, hidden: false, leaving: false, cmd: "sleep" }), false);
  assert.equal(T.canStart({ asleep: false, hidden: false, leaving: false, cmd: "seek" }), false);
  assert.equal(T.canStart({ asleep: false, hidden: false, leaving: false, cmd: "idle", windowPlay: true }), false);
  assert.equal(T.canStart({ asleep: false, hidden: false, leaving: false, cmd: "idle", card: true }), false);
  assert.equal(T.shouldAbort({ asleep: true, hidden: false, leaving: false, cmd: "idle" }), true);
  assert.equal(T.shouldAbort({ asleep: false, hidden: false, leaving: false, cmd: "idle", card: true }), true);
  assert.equal(T.shouldAbort({ asleep: false, hidden: false, leaving: false, cmd: "idle" }), false);
  assert.equal(T.pickTrick(0.99, true), "bell");
  assert.notEqual(T.pickTrick(0.3, false, "bell"), "drift");
  assert.notEqual(T.pickTrick(0.3, false, "bell"), "soak");
  assert.notEqual(T.pickTrick(0.3, false, "bell"), "gill");
  assert.notEqual(T.pickTrick(0.3, false, "bell"), "mantle");
  assert.notEqual(T.pickTrick(0.3, false, "bell"), "bone");
  assert.notEqual(T.pickTrick(0.3, false, "bell"), "spiral");
  assert.notEqual(T.pickTrick(0.3, false, "bell"), "legend");
  assert.equal(Overlay.TRICK_KEY, "moon_jelly");
  assert.equal(T.sleepHoldFrame("moon_jelly", 4), null);
  assert.equal(T.TRICKS.includes("chime"), false);
  assert.equal(T.TRICKS.includes("pulse"), false);
  assert.equal(T.TRICKS.includes("rise"), false);
  assert.equal(T.TRICKS.includes("drift"), false);
  assert.equal(T.TRICKS.includes("hover"), false);
  assert.equal(T.TRICKS.includes("mantle"), false);
  assert.equal(T.TRICKS.includes("jet"), false);
  assert.equal(T.TRICKS.includes("veil"), false);
  assert.equal(T.TRICKS.includes("bone"), false);
  assert.equal(T.TRICKS.includes("spiral"), false);
  assert.equal(T.TRICKS.includes("fringe"), false);
  assert.equal(T.TRICKS.includes("nacre"), false);
  assert.equal(T.TRICKS.includes("gulp"), false);
  assert.equal(T.TRICKS.includes("flare"), false);
  assert.equal(T.TRICKS.includes("dart"), false);
  assert.equal(T.TRICKS.includes("soak"), false);
  assert.equal(T.TRICKS.includes("gill"), false);
  assert.equal(T.TRICKS.includes("hood"), false);
  assert.equal(Overlay.TRICKS.includes("chime"), false);
  assert.equal(Overlay.TRICKS.includes("pulse"), false);
  assert.equal(Overlay.HAPPY.includes("keep"), false);
  assert.equal(Overlay.HAPPY.includes("ripple"), false);
  assert.equal(Overlay.HAPPY.includes("chamber"), false);
  assert.equal(Overlay.HAPPY.includes("pulse"), false);
  assert.equal(Overlay.HAPPY.includes("bubble"), false);
  assert.equal(Overlay.HAPPY.includes("glow"), false);
  assert.deepEqual([...Overlay.TRICKS], ["bell", "oral", "lucent", "trail", "medusa", "rhopalium", "horseshoe"]);
  assert.deepEqual([...Overlay.HAPPY], ["halo", "lumen", "gel"]);
});

test("bell/oral/lucent/trail/medusa/rhopalium/horseshoe are house-moon-jelly-true, not copies of prior guests", () => {
  const ground = { asleep: false, hidden: false, leaving: false, cmd: "idle" };
  const bell = T.beginTrick("bell", 80, 1);
  assert.equal(bell.anim, "sit");
  assert.equal(bell.phase, "hold");
  const held = T.stepTrick(bell, 5, ground);
  assert.equal(held.phase, "hold");
  assert.equal(held.anim, "sit");
  assert.ok(held.rot !== 0 || held.lift > 0);
  const release = T.stepTrick(bell, T.BELL_HOLD + 0.2, ground);
  assert.equal(release.phase, "release");
  assert.equal(release.anim, "sit");
  const doneBell = T.stepTrick(bell, T.DUR.bell + 0.1, ground);
  assert.equal(doneBell.phase, "done");
  assert.ok(T.nextTrickWait(true, 0, "bell") > T.nextTrickWait(true, 0, "lucent"));
  const oral = T.beginTrick("oral", 80, 1);
  assert.equal(oral.anim, "talk");
  const oralMid = T.stepTrick(oral, 0.5, ground);
  assert.ok(Math.abs(oralMid.lift) > 0.05 || Math.abs(oralMid.rot) > 1 || Math.abs(oralMid.x - 80) > 0.05);
  const lucent = T.beginTrick("lucent", 80, 1);
  assert.equal(lucent.anim, "sit");
  const lucentMid = T.stepTrick(lucent, 0.5, ground);
  assert.ok(Math.abs(lucentMid.lift) > 0.05 || Math.abs(lucentMid.rot) > 1 || Math.abs(lucentMid.x - 80) > 0.05);
  const trail = T.beginTrick("trail", 80, 1);
  assert.equal(trail.anim, "play");
  const trailMid = T.stepTrick(trail, 0.5, ground);
  assert.ok(Math.abs(trailMid.lift) > 0.05 || Math.abs(trailMid.rot) > 1 || Math.abs(trailMid.x - 80) > 0.05);
  const medusa = T.beginTrick("medusa", 80, 1);
  assert.equal(medusa.anim, "walk");
  const medusaMid = T.stepTrick(medusa, 0.5, ground);
  assert.ok(Math.abs(medusaMid.lift) > 0.05 || Math.abs(medusaMid.rot) > 1 || Math.abs(medusaMid.x - 80) > 0.05);
  const rhopalium = T.beginTrick("rhopalium", 80, 1);
  assert.equal(rhopalium.anim, "talk");
  const rhopaliumMid = T.stepTrick(rhopalium, 0.5, ground);
  assert.ok(Math.abs(rhopaliumMid.lift) > 0.3 || Math.abs(rhopaliumMid.rot) > 1 || Math.abs(rhopaliumMid.x - 80) > 0.05);
  const rhopaliumDone = T.stepTrick(rhopalium, T.DUR.rhopalium + 0.1, ground);
  assert.equal(rhopaliumDone.phase, "done");
  const horseshoe = T.beginTrick("horseshoe", 80, 1);
  assert.equal(horseshoe.anim, "play");
  const horseshoeMid = T.stepTrick(horseshoe, 0.5, ground);
  assert.ok(Math.abs(horseshoeMid.lift) > 0.3 || Math.abs(horseshoeMid.rot) > 1 || Math.abs(horseshoeMid.x - 80) > 0.05);
  const horseshoeDone = T.stepTrick(horseshoe, T.DUR.horseshoe + 0.1, ground);
  assert.equal(horseshoeDone.phase, "done");
  const trailDone = T.stepTrick(trail, T.DUR.trail + 0.1, ground);
  assert.equal(trailDone.phase, "done");
  const aborted = T.stepTrick(held, 0.1, { asleep: true, cmd: "sleep" });
  assert.equal(aborted.phase, "done");
  for (const mod of [Rui, Cat, Dog, Rabbit, Hamster, GuineaPig, Turtle, Goldfish, Budgie, Fox, Penguin, Parrot, Ferret, Hedgehog, Chinchilla, Axolotl, Toucan, Iguana, Dragon, Phoenix, BallPython, CornSnake, Kingsnake, GreenTreePython, Hognose, Garter, Boa, MilkSnake, RosyBoa, CarpetPython, Octopus, Cuttlefish, Nautilus, Relay, Fuse, Earth]) {
    assert.equal(mod.TRICKS.includes("bell"), false);
    assert.equal(mod.TRICKS.includes("oral"), false);
    assert.equal(mod.TRICKS.includes("lucent"), false);
    assert.equal(mod.TRICKS.includes("trail"), false);
    assert.equal(mod.TRICKS.includes("medusa"), false);
    assert.equal(mod.TRICKS.includes("rhopalium"), false);
    assert.equal(mod.TRICKS.includes("horseshoe"), false);
  }
  assert.deepEqual([...Turtle.TRICKS], ["soak", "tuck", "crane", "plod", "paddle", "snorkel", "wipe"]);
  assert.deepEqual([...Goldfish.TRICKS], ["drift", "gulp", "flare", "glint", "dart", "yawn", "forage"]);
  assert.deepEqual([...Axolotl.TRICKS], ["gill", "amble", "mend", "smile", "plume", "sprout", "glop"]);
  assert.deepEqual([...Octopus.TRICKS], ["mantle", "sucker", "jet", "veil", "tinker", "papilla", "ooze"]);
  assert.deepEqual([...Cuttlefish.TRICKS], ["bone", "pupil", "chroma", "hover", "blot", "strike", "zebra"]);
  assert.deepEqual([...Nautilus.TRICKS], ["spiral", "siphuncle", "nacre", "pinhole", "fringe", "hyponome", "aperture"]);
  assert.deepEqual([...CarpetPython.TRICKS], ["legend", "rung", "contour", "runner", "bearing", "canopy", "inset"]);
  assert.equal(T.TRICKS.includes("chime"), false);
  assert.equal(T.TRICKS.includes("pulse"), false);
  assert.equal(T.TRICKS.includes("drift"), false);
  assert.equal(T.TRICKS.includes("jet"), false);
  assert.equal(T.TRICKS.includes("mantle"), false);
  assert.equal(T.TRICKS.includes("bone"), false);
  assert.equal(T.TRICKS.includes("spiral"), false);
  assert.equal(T.TRICKS.includes("hover"), false);
  assert.equal(T.TRICKS.includes("fringe"), false);
  assert.equal(T.TRICKS.includes("hood"), false);
  assert.equal(Cuttlefish.TRICKS.includes("bone"), true);
  assert.equal(Octopus.TRICKS.includes("jet"), true);
  assert.equal(Nautilus.TRICKS.includes("spiral"), true);
  assert.equal(Goldfish.TRICKS.includes("drift"), true);
  assert.equal(Fuse.HAPPY.includes("pulse"), true);
});

test("Pulse feed-happy is its own sit: halo/lumen/gel, and two feeds are not the same", () => {
  assert.deepEqual([...T.HAPPY], ["halo", "lumen", "gel"]);
  assert.equal(T.HAPPY.includes("bubble"), false);
  assert.equal(T.HAPPY.includes("munch"), false);
  assert.equal(T.HAPPY.includes("wink"), false);
  assert.equal(T.HAPPY.includes("keep"), false);
  assert.equal(T.HAPPY.includes("tint"), false);
  assert.equal(T.HAPPY.includes("squeeze"), false);
  assert.equal(T.HAPPY.includes("ripple"), false);
  assert.equal(T.HAPPY.includes("glance"), false);
  assert.equal(T.HAPPY.includes("dab"), false);
  assert.equal(T.HAPPY.includes("chamber"), false);
  assert.equal(T.HAPPY.includes("pearl"), false);
  assert.equal(T.HAPPY.includes("quiet"), false);
  assert.equal(T.HAPPY.includes("pulse"), false);
  assert.equal(T.HAPPY.includes("glow"), false);
  assert.equal(T.HAPPY.includes("tribute"), false);
  assert.equal(T.pickHappy("halo", 0), "lumen");
  assert.notEqual(T.pickHappy("halo", 0.9), "halo");
  assert.equal(Overlay.pickHappy("lumen", 0) !== "lumen", true);
  assert.equal(T.happyCanStart({ asleep: false, hidden: false, leaving: false, cmd: "idle" }), true);
  assert.equal(T.happyCanStart({ asleep: false, hidden: false, leaving: false, cmd: "idle", card: true }), true);
  assert.equal(T.happyCanStart({ asleep: true, hidden: false, leaving: false, cmd: "idle" }), false);
  assert.equal(T.happyShouldAbort({ cmd: "sleep" }), true);
  assert.equal(T.happyShouldAbort({ cmd: "hide" }), true);
  assert.equal(T.happyShouldAbort({ card: true, cmd: "idle" }), false);
  const haloH = T.beginHappy("halo", 80, 1);
  assert.equal(haloH.anim, "sit");
  const haloMid = T.stepHappy(haloH, 0.4, { cmd: "idle" });
  assert.ok(haloMid.lift !== 0 || Math.abs(haloMid.rot) > 0.5);
  assert.notEqual(haloMid.phase, "done");
  const lumen = T.beginHappy("lumen", 80, 1);
  assert.equal(lumen.anim, "talk");
  const lumenMid = T.stepHappy(lumen, 0.3, { cmd: "idle" });
  assert.ok(lumenMid.lift > 0.2 || Math.abs(lumenMid.rot) > 0.5);
  const gelH = T.beginHappy("gel", 80, 1);
  assert.equal(gelH.anim, "sit");
  const done = T.stepHappy(haloH, T.HAPPY_DUR.halo + 0.1, { cmd: "idle" });
  assert.equal(done.phase, "done");
  const aborted = T.stepHappy(lumenMid, 0.1, { asleep: true, cmd: "sleep" });
  assert.equal(aborted.phase, "done");
  assert.equal(aborted.abort, true);
  assert.equal(T.wantsThankYou("moon_jelly"), true);
  assert.equal(T.wantsThankYou("pulse"), true);
  assert.equal(T.wantsThankYou("nautilus"), false);
  assert.equal(T.wantsThankYou("chamber"), false);
  assert.equal(T.wantsThankYou("cuttlefish"), false);
  assert.equal(T.wantsThankYou("sepia"), false);
  assert.equal(T.wantsThankYou("octopus"), false);
  assert.equal(T.wantsThankYou("cup"), false);
  assert.equal(T.wantsThankYou("goldfish"), false);
  assert.equal(T.wantsThankYou("coin"), false);
  assert.equal(T.wantsThankYou("turtle"), false);
  assert.equal(T.wantsThankYou("axolotl"), false);
  const thanks = T.startThankYou("moon_jelly", "halo", 80, 1, { cmd: "idle", card: true, windowPlay: true });
  assert.ok(thanks);
  assert.notEqual(thanks.kind, "halo");
  assert.ok(thanks.happy.lift === 0);
  assert.notEqual(thanks.happy.anim, "eat");
  assert.notEqual(thanks.happy.anim, "idle");
  const thanksMid = T.stepHappy(thanks.happy, 0.35, { cmd: "idle", card: true });
  assert.ok(thanksMid.lift !== 0 || Math.abs(thanksMid.rot) > 0.5, "a thank-you halos or lumens");
  const blocked = T.startThankYou("moon_jelly", "tribute", 80, 1, { asleep: true, cmd: "idle" });
  assert.equal(blocked, null);
  const other = T.startThankYou("octopus", null, 80, 1, { cmd: "idle" });
  assert.equal(other, null);
  const second = T.startThankYou("moon_jelly", thanks.kind, 80, 1, { cmd: "idle", card: true });
  assert.ok(second);
  assert.notEqual(second.kind, thanks.kind);
});

test("ground registry keeps prior guests gated; Pulse selectable; prior guests still OK", () => {
  assert.equal(Rui.TRICK_KEY, "red_panda");
  assert.equal(Turtle.TRICK_KEY, "turtle");
  assert.equal(Goldfish.TRICK_KEY, "goldfish");
  assert.equal(Axolotl.TRICK_KEY, "axolotl");
  assert.equal(Octopus.TRICK_KEY, "octopus");
  assert.equal(Cuttlefish.TRICK_KEY, "cuttlefish");
  assert.equal(Nautilus.TRICK_KEY, "nautilus");
  assert.equal(CarpetPython.TRICK_KEY, "carpet_python");
  assert.equal(T.TRICK_KEY, "moon_jelly");
  assert.deepEqual([...Turtle.TRICKS], ["soak", "tuck", "crane", "plod", "paddle", "snorkel", "wipe"]);
  assert.deepEqual([...Goldfish.TRICKS], ["drift", "gulp", "flare", "glint", "dart", "yawn", "forage"]);
  assert.deepEqual([...Axolotl.TRICKS], ["gill", "amble", "mend", "smile", "plume", "sprout", "glop"]);
  assert.deepEqual([...Octopus.TRICKS], ["mantle", "sucker", "jet", "veil", "tinker", "papilla", "ooze"]);
  assert.deepEqual([...Cuttlefish.TRICKS], ["bone", "pupil", "chroma", "hover", "blot", "strike", "zebra"]);
  assert.deepEqual([...Nautilus.TRICKS], ["spiral", "siphuncle", "nacre", "pinhole", "fringe", "hyponome", "aperture"]);
  assert.deepEqual([...CarpetPython.TRICKS], ["legend", "rung", "contour", "runner", "bearing", "canopy", "inset"]);
  assert.deepEqual([...T.TRICKS], ["bell", "oral", "lucent", "trail", "medusa", "rhopalium", "horseshoe"]);
  assert.equal(T.wantsThankYou("moon_jelly"), true);
  assert.equal(T.wantsThankYou("pulse"), true);
  assert.equal(Turtle.wantsThankYou("ink"), true);
  assert.equal(Goldfish.wantsThankYou("coin"), true);
  assert.equal(Axolotl.wantsThankYou("bloom"), true);
  assert.equal(Octopus.wantsThankYou("cup"), true);
  assert.equal(Cuttlefish.wantsThankYou("sepia"), true);
  assert.equal(Nautilus.wantsThankYou("chamber"), true);
  assert.equal(Rui.sleepHoldFrame("red_panda", 4), 1);
  assert.equal(T.sleepHoldFrame("moon_jelly", 4), null);
  globalThis.PetRuiTricks = OverlayRui;
  globalThis.PetRelayTricks = OverlayRelay;
  globalThis.PetFuseTricks = OverlayFuse;
  globalThis.PetEarthTricks = OverlayEarth;
  globalThis.PetCatTricks = OverlayCat;
  globalThis.PetDogTricks = OverlayDog;
  globalThis.PetRabbitTricks = OverlayRabbit;
  globalThis.PetHamsterTricks = OverlayHamster;
  globalThis.PetGuineaPigTricks = OverlayGuineaPig;
  globalThis.PetTurtleTricks = OverlayTurtle;
  globalThis.PetGoldfishTricks = OverlayGoldfish;
  globalThis.PetBudgieTricks = OverlayBudgie;
  globalThis.PetFoxTricks = OverlayFox;
  globalThis.PetPenguinTricks = OverlayPenguin;
  globalThis.PetParrotTricks = OverlayParrot;
  globalThis.PetFerretTricks = OverlayFerret;
  globalThis.PetHedgehogTricks = OverlayHedgehog;
  globalThis.PetChinchillaTricks = OverlayChinchilla;
  globalThis.PetAxolotlTricks = OverlayAxolotl;
  globalThis.PetToucanTricks = OverlayToucan;
  globalThis.PetIguanaTricks = OverlayIguana;
  globalThis.PetDragonTricks = OverlayDragon;
  globalThis.PetPhoenixTricks = OverlayPhoenix;
  globalThis.PetBallPythonTricks = OverlayBallPython;
  globalThis.PetCornSnakeTricks = OverlayCornSnake;
  globalThis.PetKingsnakeTricks = OverlayKingsnake;
  globalThis.PetGreenTreePythonTricks = OverlayGreenTreePython;
  globalThis.PetHognoseTricks = OverlayHognose;
  globalThis.PetGarterTricks = OverlayGarter;
  globalThis.PetBoaTricks = OverlayBoa;
  globalThis.PetMilkSnakeTricks = OverlayMilkSnake;
  globalThis.PetRosyBoaTricks = OverlayRosyBoa;
  globalThis.PetCarpetPythonTricks = OverlayCarpetPython;
  globalThis.PetOctopusTricks = OverlayOctopus;
  globalThis.PetCuttlefishTricks = OverlayCuttlefish;
  globalThis.PetNautilusTricks = OverlayNautilus;
  globalThis.PetMoonJellyTricks = Overlay;
  assert.equal(OverlayGround.tricksFor("red_panda"), OverlayRui);
  assert.equal(OverlayGround.tricksFor("rui"), OverlayRui);
  assert.equal(OverlayGround.tricksFor("turtle"), OverlayTurtle);
  assert.equal(OverlayGround.tricksFor("ink"), OverlayTurtle);
  assert.equal(OverlayGround.tricksFor("goldfish"), OverlayGoldfish);
  assert.equal(OverlayGround.tricksFor("coin"), OverlayGoldfish);
  assert.equal(OverlayGround.tricksFor("axolotl"), OverlayAxolotl);
  assert.equal(OverlayGround.tricksFor("bloom"), OverlayAxolotl);
  assert.equal(OverlayGround.tricksFor("octopus"), OverlayOctopus);
  assert.equal(OverlayGround.tricksFor("cup"), OverlayOctopus);
  assert.equal(OverlayGround.tricksFor("cuttlefish"), OverlayCuttlefish);
  assert.equal(OverlayGround.tricksFor("sepia"), OverlayCuttlefish);
  assert.equal(OverlayGround.tricksFor("nautilus"), OverlayNautilus);
  assert.equal(OverlayGround.tricksFor("chamber"), OverlayNautilus);
  assert.equal(OverlayGround.tricksFor("carpet_python"), OverlayCarpetPython);
  assert.equal(OverlayGround.tricksFor("atlas"), OverlayCarpetPython);
  assert.equal(OverlayGround.tricksFor("moon_jelly"), Overlay);
  assert.equal(OverlayGround.tricksFor("pulse"), Overlay);
  assert.equal(OverlayGround.wantsThankYou("turtle"), true);
  assert.equal(OverlayGround.wantsThankYou("ink"), true);
  assert.equal(OverlayGround.wantsThankYou("goldfish"), true);
  assert.equal(OverlayGround.wantsThankYou("coin"), true);
  assert.equal(OverlayGround.wantsThankYou("axolotl"), true);
  assert.equal(OverlayGround.wantsThankYou("bloom"), true);
  assert.equal(OverlayGround.wantsThankYou("octopus"), true);
  assert.equal(OverlayGround.wantsThankYou("cup"), true);
  assert.equal(OverlayGround.wantsThankYou("cuttlefish"), true);
  assert.equal(OverlayGround.wantsThankYou("sepia"), true);
  assert.equal(OverlayGround.wantsThankYou("nautilus"), true);
  assert.equal(OverlayGround.wantsThankYou("chamber"), true);
  assert.equal(OverlayGround.wantsThankYou("carpet_python"), true);
  assert.equal(OverlayGround.wantsThankYou("atlas"), true);
  assert.equal(OverlayGround.wantsThankYou("moon_jelly"), true);
  assert.equal(OverlayGround.wantsThankYou("pulse"), true);
  assert.equal(OverlayGround.sleepHoldFrame("red_panda", 4), 1);
  assert.equal(OverlayGround.sleepHoldFrame("moon_jelly", 4), null);
  assert.deepEqual([...OverlayTurtle.TRICKS], ["soak", "tuck", "crane", "plod", "paddle", "snorkel", "wipe"]);
  assert.deepEqual([...OverlayGoldfish.TRICKS], ["drift", "gulp", "flare", "glint", "dart", "yawn", "forage"]);
  assert.deepEqual([...OverlayAxolotl.TRICKS], ["gill", "amble", "mend", "smile", "plume", "sprout", "glop"]);
  assert.deepEqual([...OverlayOctopus.TRICKS], ["mantle", "sucker", "jet", "veil", "tinker", "papilla", "ooze"]);
  assert.deepEqual([...OverlayCuttlefish.TRICKS], ["bone", "pupil", "chroma", "hover", "blot", "strike", "zebra"]);
  assert.deepEqual([...OverlayNautilus.TRICKS], ["spiral", "siphuncle", "nacre", "pinhole", "fringe", "hyponome", "aperture"]);
  assert.deepEqual([...OverlayCarpetPython.TRICKS], ["legend", "rung", "contour", "runner", "bearing", "canopy", "inset"]);
  assert.deepEqual([...Overlay.TRICKS], ["bell", "oral", "lucent", "trail", "medusa", "rhopalium", "horseshoe"]);
  assert.equal(Overlay.TRICKS.includes("chime"), false);
  assert.equal(Overlay.TRICKS.includes("pulse"), false);
  assert.equal(Overlay.TRICKS.includes("drift"), false);
  assert.equal(Overlay.TRICKS.includes("jet"), false);
  assert.equal(Overlay.TRICKS.includes("mantle"), false);
  assert.equal(Overlay.TRICKS.includes("bone"), false);
  assert.equal(Overlay.TRICKS.includes("spiral"), false);
  assert.equal(Overlay.TRICKS.includes("tuck"), false);
  assert.equal(Overlay.TRICKS.includes("gill"), false);
  assert.equal(Overlay.TRICKS.includes("legend"), false);
});

test("ultra-polish: Pulse bell/rhopalium/horseshoe lifts are Rui-visible (not micro idle-gen)", () => {
  const bel = T.beginTrick("bell", 80, 1);
  const mid = T.stepTrick(bel, 5, { cmd: "idle" });
  assert.ok(Math.abs(mid.rot) > 10, `bell mid rot ${mid.rot}`);
  assert.ok(Math.abs(mid.lift) > 0.5, `bell mid lift ${mid.lift}`);
  const rh = T.beginTrick("rhopalium", 80, 1);
  const r2 = T.stepTrick(rh, T.DUR.rhopalium * 0.4, { cmd: "idle" });
  assert.ok(r2.lift > 2 || Math.abs(r2.rot) > 4 || Math.abs(r2.x - 80) > 1, `rhopalium mid ${r2.lift}/${r2.rot}/${r2.x}`);
  const hs = T.beginTrick("horseshoe", 80, 1);
  const h2 = T.stepTrick(hs, T.DUR.horseshoe * 0.4, { cmd: "idle" });
  assert.ok(h2.lift > 2 || Math.abs(h2.rot) > 8 || Math.abs(h2.x - 80) > 0.3, `horseshoe mid ${h2.lift}/${h2.rot}/${h2.x}`);
  const tr = T.beginTrick("trail", 80, 1);
  const t2 = T.stepTrick(tr, T.DUR.trail * 0.4, { cmd: "idle" });
  assert.ok(t2.lift > 0.5 || Math.abs(t2.rot) > 4 || Math.abs(t2.x - 80) > 0.5, `trail mid ${t2.lift}/${t2.rot}/${t2.x}`);
  assert.ok(Overlay.rhopaliumPose && Overlay.horseshoePose);
  assert.deepEqual([...T.TRICKS], [...Overlay.TRICKS]);
});

test("notes: Pulse idle-life ultra done; Anchor / seahorse ultra done; next house-order ultra guest is Kite / manta (birds Soot→Ember + Miso + Pip + Thimble + Clip + Whee + Ink + Coin + Rue + Wick + Burr + Floss + Bloom + Sol + Vesper + Nori + Saffron + Bandit + Jade + Bluff + Sash + Lula + Coral + Blush + Atlas + Cup + Sepia + Chamber + Pulse + Ochre + Tenant + Ledger + Anchor already ultra; Echo/budgie + Peck/penguin + Quill/parrot + Keel/toucan + Ember skip bird", () => {
  assert.equal(T.TRICK_KEY, "moon_jelly");
  assert.equal(T.wantsThankYou("pulse"), true);
  assert.equal(OverlayGround.tricksFor("moon_jelly"), Overlay);
  assert.equal(OverlayGround.tricksFor("pulse"), Overlay);
  assert.equal(OverlayGround.wantsThankYou("moon_jelly"), true);
  assert.equal(OverlayGround.wantsThankYou("pulse"), true);
  assert.equal(OverlayGround.tricksFor("nautilus"), OverlayNautilus);
  assert.equal(OverlayGround.tricksFor("chamber"), OverlayNautilus);
  assert.equal(OverlayGround.tricksFor("cuttlefish"), OverlayCuttlefish);
  assert.equal(OverlayGround.tricksFor("sepia"), OverlayCuttlefish);
  assert.equal(OverlayGround.tricksFor("octopus"), OverlayOctopus);
  assert.equal(OverlayGround.tricksFor("cup"), OverlayOctopus);
  assert.equal(OverlayGround.tricksFor("carpet_python"), OverlayCarpetPython);
  assert.equal(OverlayGround.tricksFor("atlas"), OverlayCarpetPython);
  assert.equal(OverlayGround.tricksFor("turtle"), OverlayTurtle);
  assert.equal(OverlayGround.tricksFor("ink"), OverlayTurtle);
  assert.equal(OverlayGround.tricksFor("goldfish"), OverlayGoldfish);
  assert.equal(OverlayGround.tricksFor("coin"), OverlayGoldfish);
  assert.equal(OverlayGround.tricksFor("axolotl"), OverlayAxolotl);
  assert.equal(OverlayGround.tricksFor("bloom"), OverlayAxolotl);
  assert.equal(OverlayGround.tricksFor("hermit_crab") == null, true);
  assert.equal(OverlayGround.wantsThankYou("hermit_crab"), false);
  assert.equal(OverlayGround.tricksFor("tenant") == null, true);
  assert.equal(OverlayGround.wantsThankYou("tenant"), false);
});
