import assert from "node:assert/strict";
import { createRequire } from "node:module";
import { dirname, join } from "node:path";
import { test } from "node:test";
import { fileURLToPath, pathToFileURL } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const T = await import(pathToFileURL(join(root, "src/lib/pets/nautilus-tricks.ts")).href);
const Cuttlefish = await import(pathToFileURL(join(root, "src/lib/pets/cuttlefish-tricks.ts")).href);
const Octopus = await import(pathToFileURL(join(root, "src/lib/pets/octopus-tricks.ts")).href);
const CarpetPython = await import(pathToFileURL(join(root, "src/lib/pets/carpet-python-tricks.ts")).href);
const RosyBoa = await import(pathToFileURL(join(root, "src/lib/pets/rosy-boa-tricks.ts")).href);
const MilkSnake = await import(pathToFileURL(join(root, "src/lib/pets/milk-snake-tricks.ts")).href);
const Garter = await import(pathToFileURL(join(root, "src/lib/pets/garter-tricks.ts")).href);
const Boa = await import(pathToFileURL(join(root, "src/lib/pets/boa-tricks.ts")).href);
const Hognose = await import(pathToFileURL(join(root, "src/lib/pets/hognose-tricks.ts")).href);
const GreenTreePython = await import(pathToFileURL(join(root, "src/lib/pets/green-tree-python-tricks.ts")).href);
const BallPython = await import(pathToFileURL(join(root, "src/lib/pets/ball-python-tricks.ts")).href);
const CornSnake = await import(pathToFileURL(join(root, "src/lib/pets/corn-snake-tricks.ts")).href);
const Kingsnake = await import(pathToFileURL(join(root, "src/lib/pets/kingsnake-tricks.ts")).href);
const Phoenix = await import(pathToFileURL(join(root, "src/lib/pets/phoenix-tricks.ts")).href);
const Dragon = await import(pathToFileURL(join(root, "src/lib/pets/dragon-tricks.ts")).href);
const Rui = await import(pathToFileURL(join(root, "src/lib/pets/rui-tricks.ts")).href);
const Relay = await import(pathToFileURL(join(root, "src/lib/pets/relay-tricks.ts")).href);
const Fuse = await import(pathToFileURL(join(root, "src/lib/pets/fuse-tricks.ts")).href);
const Earth = await import(pathToFileURL(join(root, "src/lib/pets/earth-tricks.ts")).href);
const Cat = await import(pathToFileURL(join(root, "src/lib/pets/cat-tricks.ts")).href);
const Dog = await import(pathToFileURL(join(root, "src/lib/pets/dog-tricks.ts")).href);
const Rabbit = await import(pathToFileURL(join(root, "src/lib/pets/rabbit-tricks.ts")).href);
const Hamster = await import(pathToFileURL(join(root, "src/lib/pets/hamster-tricks.ts")).href);
const GuineaPig = await import(pathToFileURL(join(root, "src/lib/pets/guinea-pig-tricks.ts")).href);
const Turtle = await import(pathToFileURL(join(root, "src/lib/pets/turtle-tricks.ts")).href);
const Goldfish = await import(pathToFileURL(join(root, "src/lib/pets/goldfish-tricks.ts")).href);
const Budgie = await import(pathToFileURL(join(root, "src/lib/pets/budgie-tricks.ts")).href);
const Fox = await import(pathToFileURL(join(root, "src/lib/pets/fox-tricks.ts")).href);
const Penguin = await import(pathToFileURL(join(root, "src/lib/pets/penguin-tricks.ts")).href);
const Parrot = await import(pathToFileURL(join(root, "src/lib/pets/parrot-tricks.ts")).href);
const Ferret = await import(pathToFileURL(join(root, "src/lib/pets/ferret-tricks.ts")).href);
const Hedgehog = await import(pathToFileURL(join(root, "src/lib/pets/hedgehog-tricks.ts")).href);
const Chinchilla = await import(pathToFileURL(join(root, "src/lib/pets/chinchilla-tricks.ts")).href);
const Axolotl = await import(pathToFileURL(join(root, "src/lib/pets/axolotl-tricks.ts")).href);
const Toucan = await import(pathToFileURL(join(root, "src/lib/pets/toucan-tricks.ts")).href);
const Iguana = await import(pathToFileURL(join(root, "src/lib/pets/iguana-tricks.ts")).href);
const Overlay = createRequire(import.meta.url)(join(root, "../desktop/renderer/nautilus-tricks.js"));
const OverlayCuttlefish = createRequire(import.meta.url)(join(root, "../desktop/renderer/cuttlefish-tricks.js"));
const OverlayOctopus = createRequire(import.meta.url)(join(root, "../desktop/renderer/octopus-tricks.js"));
const OverlayCarpetPython = createRequire(import.meta.url)(join(root, "../desktop/renderer/carpet-python-tricks.js"));
const OverlayRosyBoa = createRequire(import.meta.url)(join(root, "../desktop/renderer/rosy-boa-tricks.js"));
const OverlayMilkSnake = createRequire(import.meta.url)(join(root, "../desktop/renderer/milk-snake-tricks.js"));
const OverlayGarter = createRequire(import.meta.url)(join(root, "../desktop/renderer/garter-tricks.js"));
const OverlayBoa = createRequire(import.meta.url)(join(root, "../desktop/renderer/boa-tricks.js"));
const OverlayHognose = createRequire(import.meta.url)(join(root, "../desktop/renderer/hognose-tricks.js"));
const OverlayGreenTreePython = createRequire(import.meta.url)(join(root, "../desktop/renderer/green-tree-python-tricks.js"));
const OverlayBallPython = createRequire(import.meta.url)(join(root, "../desktop/renderer/ball-python-tricks.js"));
const OverlayCornSnake = createRequire(import.meta.url)(join(root, "../desktop/renderer/corn-snake-tricks.js"));
const OverlayKingsnake = createRequire(import.meta.url)(join(root, "../desktop/renderer/kingsnake-tricks.js"));
const OverlayPhoenix = createRequire(import.meta.url)(join(root, "../desktop/renderer/phoenix-tricks.js"));
const OverlayGround = createRequire(import.meta.url)(join(root, "../desktop/renderer/ground-tricks.js"));
const OverlayRui = createRequire(import.meta.url)(join(root, "../desktop/renderer/rui-tricks.js"));
const OverlayRelay = createRequire(import.meta.url)(join(root, "../desktop/renderer/relay-tricks.js"));
const OverlayFuse = createRequire(import.meta.url)(join(root, "../desktop/renderer/fuse-tricks.js"));
const OverlayEarth = createRequire(import.meta.url)(join(root, "../desktop/renderer/earth-tricks.js"));
const OverlayCat = createRequire(import.meta.url)(join(root, "../desktop/renderer/cat-tricks.js"));
const OverlayDog = createRequire(import.meta.url)(join(root, "../desktop/renderer/dog-tricks.js"));
const OverlayRabbit = createRequire(import.meta.url)(join(root, "../desktop/renderer/rabbit-tricks.js"));
const OverlayHamster = createRequire(import.meta.url)(join(root, "../desktop/renderer/hamster-tricks.js"));
const OverlayGuineaPig = createRequire(import.meta.url)(join(root, "../desktop/renderer/guinea-pig-tricks.js"));
const OverlayTurtle = createRequire(import.meta.url)(join(root, "../desktop/renderer/turtle-tricks.js"));
const OverlayGoldfish = createRequire(import.meta.url)(join(root, "../desktop/renderer/goldfish-tricks.js"));
const OverlayBudgie = createRequire(import.meta.url)(join(root, "../desktop/renderer/budgie-tricks.js"));
const OverlayFox = createRequire(import.meta.url)(join(root, "../desktop/renderer/fox-tricks.js"));
const OverlayPenguin = createRequire(import.meta.url)(join(root, "../desktop/renderer/penguin-tricks.js"));
const OverlayParrot = createRequire(import.meta.url)(join(root, "../desktop/renderer/parrot-tricks.js"));
const OverlayFerret = createRequire(import.meta.url)(join(root, "../desktop/renderer/ferret-tricks.js"));
const OverlayHedgehog = createRequire(import.meta.url)(join(root, "../desktop/renderer/hedgehog-tricks.js"));
const OverlayChinchilla = createRequire(import.meta.url)(join(root, "../desktop/renderer/chinchilla-tricks.js"));
const OverlayAxolotl = createRequire(import.meta.url)(join(root, "../desktop/renderer/axolotl-tricks.js"));
const OverlayToucan = createRequire(import.meta.url)(join(root, "../desktop/renderer/toucan-tricks.js"));
const OverlayIguana = createRequire(import.meta.url)(join(root, "../desktop/renderer/iguana-tricks.js"));
const OverlayDragon = createRequire(import.meta.url)(join(root, "../desktop/renderer/dragon-tricks.js"));

test("Chamber tricks start only on idle ground", () => {
  assert.deepEqual([...Turtle.TRICKS], ["soak", "tuck", "crane", "plod", "paddle", "snorkel", "wipe"]);
  assert.deepEqual([...Goldfish.TRICKS], ["drift", "gulp", "flare", "glint", "dart", "yawn", "forage"]);
  assert.deepEqual([...Axolotl.TRICKS], ["gill", "amble", "mend", "smile", "plume", "sprout", "glop"]);
  assert.deepEqual([...Octopus.TRICKS], ["mantle", "sucker", "jet", "veil", "tinker", "papilla", "ooze"]);
  assert.deepEqual([...Cuttlefish.TRICKS], ["bone", "pupil", "chroma", "hover", "blot"]);
  assert.deepEqual([...CarpetPython.TRICKS], ["legend", "rung", "contour", "runner", "bearing", "canopy", "inset"]);
  assert.deepEqual([...T.TRICKS], ["spiral", "siphuncle", "nacre", "pinhole", "fringe"]);
  assert.equal(T.canStart({ asleep: false, hidden: false, leaving: false, cmd: "idle" }), true);
  assert.equal(T.canStart({ asleep: true, hidden: false, leaving: false, cmd: "idle" }), false);
  assert.equal(T.canStart({ asleep: false, hidden: true, leaving: false, cmd: "idle" }), false);
  assert.equal(T.canStart({ asleep: false, hidden: false, leaving: false, cmd: "sleep" }), false);
  assert.equal(T.canStart({ asleep: false, hidden: false, leaving: false, cmd: "seek" }), false);
  assert.equal(T.canStart({ asleep: false, hidden: false, leaving: false, cmd: "idle", windowPlay: true }), false);
  assert.equal(T.canStart({ asleep: false, hidden: false, leaving: false, cmd: "idle", card: true }), false);
  assert.equal(T.shouldAbort({ asleep: true, hidden: false, leaving: false, cmd: "idle" }), true);
  assert.equal(T.shouldAbort({ asleep: false, hidden: false, leaving: false, cmd: "idle", card: true }), true);
  assert.equal(T.shouldAbort({ asleep: false, hidden: false, leaving: false, cmd: "idle" }), false);
  assert.equal(T.pickTrick(0.99, true), "spiral");
  assert.notEqual(T.pickTrick(0.3, false, "spiral"), "drift");
  assert.notEqual(T.pickTrick(0.3, false, "spiral"), "soak");
  assert.notEqual(T.pickTrick(0.3, false, "spiral"), "gill");
  assert.notEqual(T.pickTrick(0.3, false, "spiral"), "mantle");
  assert.notEqual(T.pickTrick(0.3, false, "spiral"), "bone");
  assert.notEqual(T.pickTrick(0.3, false, "spiral"), "legend");
  assert.equal(Overlay.TRICK_KEY, "nautilus");
  assert.equal(T.sleepHoldFrame("nautilus", 4), null);
  assert.equal(T.TRICKS.includes("rise"), false);
  assert.equal(T.TRICKS.includes("flush"), false);
  assert.equal(T.TRICKS.includes("flash"), false);
  assert.equal(T.TRICKS.includes("lid"), false);
  assert.equal(T.TRICKS.includes("mantle"), false);
  assert.equal(T.TRICKS.includes("sucker"), false);
  assert.equal(T.TRICKS.includes("jet"), false);
  assert.equal(T.TRICKS.includes("veil"), false);
  assert.equal(T.TRICKS.includes("tinker"), false);
  assert.equal(T.TRICKS.includes("bone"), false);
  assert.equal(T.TRICKS.includes("pupil"), false);
  assert.equal(T.TRICKS.includes("chroma"), false);
  assert.equal(T.TRICKS.includes("hover"), false);
  assert.equal(T.TRICKS.includes("blot"), false);
  assert.equal(T.TRICKS.includes("drift"), false);
  assert.equal(T.TRICKS.includes("gulp"), false);
  assert.equal(T.TRICKS.includes("flare"), false);
  assert.equal(T.TRICKS.includes("dart"), false);
  assert.equal(T.TRICKS.includes("soak"), false);
  assert.equal(T.TRICKS.includes("tuck"), false);
  assert.equal(T.TRICKS.includes("paddle"), false);
  assert.equal(T.TRICKS.includes("gill"), false);
  assert.equal(T.TRICKS.includes("amble"), false);
  assert.equal(T.TRICKS.includes("plume"), false);
  assert.equal(T.TRICKS.includes("hood"), false);
  assert.equal(Overlay.TRICKS.includes("rise"), false);
  assert.equal(Overlay.HAPPY.includes("keep"), false);
  assert.equal(Overlay.HAPPY.includes("ripple"), false);
  assert.equal(Overlay.HAPPY.includes("tribute"), false);
  assert.deepEqual([...Overlay.TRICKS], ["spiral", "siphuncle", "nacre", "pinhole", "fringe"]);
  assert.deepEqual([...Overlay.HAPPY], ["chamber", "pearl", "quiet"]);
});

test("spiral/siphuncle/nacre/pinhole/fringe are house-nautilus-true, not copies of prior guests", () => {
  const ground = { asleep: false, hidden: false, leaving: false, cmd: "idle" };
  const spiral = T.beginTrick("spiral", 80, 1);
  assert.equal(spiral.anim, "sit");
  assert.equal(spiral.phase, "hold");
  const held = T.stepTrick(spiral, 5, ground);
  assert.equal(held.phase, "hold");
  assert.equal(held.anim, "sit");
  assert.ok(held.rot !== 0 || held.lift > 0);
  const release = T.stepTrick(spiral, T.SPIRAL_HOLD + 0.2, ground);
  assert.equal(release.phase, "release");
  assert.equal(release.anim, "sit");
  const doneSpiral = T.stepTrick(spiral, T.DUR.spiral + 0.1, ground);
  assert.equal(doneSpiral.phase, "done");
  assert.ok(T.nextTrickWait(true, 0, "spiral") > T.nextTrickWait(true, 0, "pinhole"));
  const siphuncle = T.beginTrick("siphuncle", 80, 1);
  assert.equal(siphuncle.anim, "walk");
  const siphuncleMid = T.stepTrick(siphuncle, 0.5, ground);
  assert.ok(Math.abs(siphuncleMid.lift) > 0.3 || Math.abs(siphuncleMid.rot) > 1 || Math.abs(siphuncleMid.x - 80) > 0.05);
  const nacre = T.beginTrick("nacre", 80, 1);
  assert.equal(nacre.anim, "sit");
  const nacreMid = T.stepTrick(nacre, 0.5, ground);
  assert.ok(Math.abs(nacreMid.lift) > 0.05 || Math.abs(nacreMid.rot) > 1 || Math.abs(nacreMid.x - 80) > 0.05);
  const pinhole = T.beginTrick("pinhole", 80, 1);
  assert.equal(pinhole.anim, "talk");
  const pinholeMid = T.stepTrick(pinhole, 0.5, ground);
  assert.ok(Math.abs(pinholeMid.lift) > 0.05 || Math.abs(pinholeMid.rot) > 1 || Math.abs(pinholeMid.x - 80) > 0.05);
  const fringe = T.beginTrick("fringe", 80, 1);
  assert.equal(fringe.anim, "play");
  const fringeMid = T.stepTrick(fringe, 0.5, ground);
  assert.ok(Math.abs(fringeMid.lift) > 0.05 || Math.abs(fringeMid.rot) > 1 || Math.abs(fringeMid.x - 80) > 0.05);
  const fringeDone = T.stepTrick(fringe, 1.6, ground);
  assert.equal(fringeDone.phase, "done");
  const aborted = T.stepTrick(held, 0.1, { asleep: true, cmd: "sleep" });
  assert.equal(aborted.phase, "done");
  for (const mod of [Rui, Cat, Dog, Rabbit, Hamster, GuineaPig, Turtle, Goldfish, Budgie, Fox, Penguin, Parrot, Ferret, Hedgehog, Chinchilla, Axolotl, Toucan, Iguana, Dragon, Phoenix, BallPython, CornSnake, Kingsnake, GreenTreePython, Hognose, Garter, Boa, MilkSnake, RosyBoa, CarpetPython, Octopus, Cuttlefish, Relay, Fuse, Earth]) {
    assert.equal(mod.TRICKS.includes("spiral"), false);
    assert.equal(mod.TRICKS.includes("siphuncle"), false);
    assert.equal(mod.TRICKS.includes("nacre"), false);
    assert.equal(mod.TRICKS.includes("pinhole"), false);
    assert.equal(mod.TRICKS.includes("fringe"), false);
  }
  assert.deepEqual([...Turtle.TRICKS], ["soak", "tuck", "crane", "plod", "paddle", "snorkel", "wipe"]);
  assert.deepEqual([...Goldfish.TRICKS], ["drift", "gulp", "flare", "glint", "dart", "yawn", "forage"]);
  assert.deepEqual([...Axolotl.TRICKS], ["gill", "amble", "mend", "smile", "plume", "sprout", "glop"]);
  assert.deepEqual([...Octopus.TRICKS], ["mantle", "sucker", "jet", "veil", "tinker", "papilla", "ooze"]);
  assert.deepEqual([...Cuttlefish.TRICKS], ["bone", "pupil", "chroma", "hover", "blot"]);
  assert.deepEqual([...CarpetPython.TRICKS], ["legend", "rung", "contour", "runner", "bearing", "canopy", "inset"]);
  assert.equal(T.TRICKS.includes("rise"), false);
  assert.equal(T.TRICKS.includes("jet"), false);
  assert.equal(T.TRICKS.includes("mantle"), false);
  assert.equal(T.TRICKS.includes("bone"), false);
  assert.equal(T.TRICKS.includes("pupil"), false);
  assert.equal(T.TRICKS.includes("chroma"), false);
  assert.equal(T.TRICKS.includes("hover"), false);
  assert.equal(T.TRICKS.includes("blot"), false);
  assert.equal(T.TRICKS.includes("drift"), false);
  assert.equal(T.TRICKS.includes("hood"), false);
  assert.equal(Cuttlefish.TRICKS.includes("bone"), true);
  assert.equal(Octopus.TRICKS.includes("jet"), true);
});

test("Chamber feed-happy is its own sit: chamber/pearl/quiet, and two feeds are not the same", () => {
  assert.deepEqual([...T.HAPPY], ["chamber", "pearl", "quiet"]);
  assert.equal(T.HAPPY.includes("bubble"), false);
  assert.equal(T.HAPPY.includes("munch"), false);
  assert.equal(T.HAPPY.includes("wink"), false);
  assert.equal(T.HAPPY.includes("keep"), false);
  assert.equal(T.HAPPY.includes("tint"), false);
  assert.equal(T.HAPPY.includes("squeeze"), false);
  assert.equal(T.HAPPY.includes("ripple"), false);
  assert.equal(T.HAPPY.includes("glance"), false);
  assert.equal(T.HAPPY.includes("dab"), false);
  assert.equal(T.HAPPY.includes("tribute"), false);
  assert.equal(T.HAPPY.includes("survey"), false);
  assert.equal(T.pickHappy("chamber", 0), "pearl");
  assert.notEqual(T.pickHappy("chamber", 0.9), "chamber");
  assert.equal(Overlay.pickHappy("pearl", 0) !== "pearl", true);
  assert.equal(T.happyCanStart({ asleep: false, hidden: false, leaving: false, cmd: "idle" }), true);
  assert.equal(T.happyCanStart({ asleep: false, hidden: false, leaving: false, cmd: "idle", card: true }), true);
  assert.equal(T.happyCanStart({ asleep: true, hidden: false, leaving: false, cmd: "idle" }), false);
  assert.equal(T.happyShouldAbort({ cmd: "sleep" }), true);
  assert.equal(T.happyShouldAbort({ cmd: "hide" }), true);
  assert.equal(T.happyShouldAbort({ card: true, cmd: "idle" }), false);
  const chamberH = T.beginHappy("chamber", 80, 1);
  assert.equal(chamberH.anim, "sit");
  const chamberMid = T.stepHappy(chamberH, 0.4, { cmd: "idle" });
  assert.ok(chamberMid.lift !== 0 || Math.abs(chamberMid.rot) > 0.5);
  assert.notEqual(chamberMid.phase, "done");
  const pearl = T.beginHappy("pearl", 80, 1);
  assert.equal(pearl.anim, "talk");
  const pearlMid = T.stepHappy(pearl, 0.3, { cmd: "idle" });
  assert.ok(pearlMid.lift > 0.2 || Math.abs(pearlMid.rot) > 0.5);
  const quietH = T.beginHappy("quiet", 80, 1);
  assert.equal(quietH.anim, "sit");
  const done = T.stepHappy(chamberH, T.HAPPY_DUR.chamber + 0.1, { cmd: "idle" });
  assert.equal(done.phase, "done");
  const aborted = T.stepHappy(pearlMid, 0.1, { asleep: true, cmd: "sleep" });
  assert.equal(aborted.phase, "done");
  assert.equal(aborted.abort, true);
  assert.equal(T.wantsThankYou("nautilus"), true);
  assert.equal(T.wantsThankYou("chamber"), true);
  assert.equal(T.wantsThankYou("cuttlefish"), false);
  assert.equal(T.wantsThankYou("sepia"), false);
  assert.equal(T.wantsThankYou("octopus"), false);
  assert.equal(T.wantsThankYou("cup"), false);
  assert.equal(T.wantsThankYou("goldfish"), false);
  assert.equal(T.wantsThankYou("coin"), false);
  assert.equal(T.wantsThankYou("turtle"), false);
  assert.equal(T.wantsThankYou("axolotl"), false);
  const thanks = T.startThankYou("nautilus", "chamber", 80, 1, { cmd: "idle", card: true, windowPlay: true });
  assert.ok(thanks);
  assert.notEqual(thanks.kind, "chamber");
  assert.ok(thanks.happy.lift === 0);
  assert.notEqual(thanks.happy.anim, "eat");
  assert.notEqual(thanks.happy.anim, "idle");
  const thanksMid = T.stepHappy(thanks.happy, 0.35, { cmd: "idle", card: true });
  assert.ok(thanksMid.lift !== 0 || Math.abs(thanksMid.rot) > 0.5, "a thank-you chambers or pearls");
  const blocked = T.startThankYou("nautilus", "tribute", 80, 1, { asleep: true, cmd: "idle" });
  assert.equal(blocked, null);
  const other = T.startThankYou("octopus", null, 80, 1, { cmd: "idle" });
  assert.equal(other, null);
  const second = T.startThankYou("nautilus", thanks.kind, 80, 1, { cmd: "idle", card: true });
  assert.ok(second);
  assert.notEqual(second.kind, thanks.kind);
});

test("ground registry keeps prior guests gated; Chamber selectable; prior guests still OK", () => {
  assert.equal(Rui.TRICK_KEY, "red_panda");
  assert.equal(Turtle.TRICK_KEY, "turtle");
  assert.equal(Goldfish.TRICK_KEY, "goldfish");
  assert.equal(Axolotl.TRICK_KEY, "axolotl");
  assert.equal(Octopus.TRICK_KEY, "octopus");
  assert.equal(Cuttlefish.TRICK_KEY, "cuttlefish");
  assert.equal(CarpetPython.TRICK_KEY, "carpet_python");
  assert.equal(T.TRICK_KEY, "nautilus");
  assert.deepEqual([...Turtle.TRICKS], ["soak", "tuck", "crane", "plod", "paddle", "snorkel", "wipe"]);
  assert.deepEqual([...Goldfish.TRICKS], ["drift", "gulp", "flare", "glint", "dart", "yawn", "forage"]);
  assert.deepEqual([...Axolotl.TRICKS], ["gill", "amble", "mend", "smile", "plume", "sprout", "glop"]);
  assert.deepEqual([...Octopus.TRICKS], ["mantle", "sucker", "jet", "veil", "tinker", "papilla", "ooze"]);
  assert.deepEqual([...Cuttlefish.TRICKS], ["bone", "pupil", "chroma", "hover", "blot"]);
  assert.deepEqual([...CarpetPython.TRICKS], ["legend", "rung", "contour", "runner", "bearing", "canopy", "inset"]);
  assert.deepEqual([...T.TRICKS], ["spiral", "siphuncle", "nacre", "pinhole", "fringe"]);
  assert.equal(T.wantsThankYou("nautilus"), true);
  assert.equal(T.wantsThankYou("chamber"), true);
  assert.equal(Turtle.wantsThankYou("ink"), true);
  assert.equal(Goldfish.wantsThankYou("coin"), true);
  assert.equal(Axolotl.wantsThankYou("bloom"), true);
  assert.equal(Octopus.wantsThankYou("cup"), true);
  assert.equal(Cuttlefish.wantsThankYou("sepia"), true);
  assert.equal(Rui.sleepHoldFrame("red_panda", 4), 1);
  assert.equal(T.sleepHoldFrame("nautilus", 4), null);
  globalThis.PetRuiTricks = OverlayRui;
  globalThis.PetRelayTricks = OverlayRelay;
  globalThis.PetFuseTricks = OverlayFuse;
  globalThis.PetEarthTricks = OverlayEarth;
  globalThis.PetCatTricks = OverlayCat;
  globalThis.PetDogTricks = OverlayDog;
  globalThis.PetRabbitTricks = OverlayRabbit;
  globalThis.PetHamsterTricks = OverlayHamster;
  globalThis.PetGuineaPigTricks = OverlayGuineaPig;
  globalThis.PetTurtleTricks = OverlayTurtle;
  globalThis.PetGoldfishTricks = OverlayGoldfish;
  globalThis.PetBudgieTricks = OverlayBudgie;
  globalThis.PetFoxTricks = OverlayFox;
  globalThis.PetPenguinTricks = OverlayPenguin;
  globalThis.PetParrotTricks = OverlayParrot;
  globalThis.PetFerretTricks = OverlayFerret;
  globalThis.PetHedgehogTricks = OverlayHedgehog;
  globalThis.PetChinchillaTricks = OverlayChinchilla;
  globalThis.PetAxolotlTricks = OverlayAxolotl;
  globalThis.PetToucanTricks = OverlayToucan;
  globalThis.PetIguanaTricks = OverlayIguana;
  globalThis.PetDragonTricks = OverlayDragon;
  globalThis.PetPhoenixTricks = OverlayPhoenix;
  globalThis.PetBallPythonTricks = OverlayBallPython;
  globalThis.PetCornSnakeTricks = OverlayCornSnake;
  globalThis.PetKingsnakeTricks = OverlayKingsnake;
  globalThis.PetGreenTreePythonTricks = OverlayGreenTreePython;
  globalThis.PetHognoseTricks = OverlayHognose;
  globalThis.PetGarterTricks = OverlayGarter;
  globalThis.PetBoaTricks = OverlayBoa;
  globalThis.PetMilkSnakeTricks = OverlayMilkSnake;
  globalThis.PetRosyBoaTricks = OverlayRosyBoa;
  globalThis.PetCarpetPythonTricks = OverlayCarpetPython;
  globalThis.PetOctopusTricks = OverlayOctopus;
  globalThis.PetCuttlefishTricks = OverlayCuttlefish;
  globalThis.PetNautilusTricks = Overlay;
  assert.equal(OverlayGround.tricksFor("red_panda"), OverlayRui);
  assert.equal(OverlayGround.tricksFor("rui"), OverlayRui);
  assert.equal(OverlayGround.tricksFor("turtle"), OverlayTurtle);
  assert.equal(OverlayGround.tricksFor("ink"), OverlayTurtle);
  assert.equal(OverlayGround.tricksFor("goldfish"), OverlayGoldfish);
  assert.equal(OverlayGround.tricksFor("coin"), OverlayGoldfish);
  assert.equal(OverlayGround.tricksFor("axolotl"), OverlayAxolotl);
  assert.equal(OverlayGround.tricksFor("bloom"), OverlayAxolotl);
  assert.equal(OverlayGround.tricksFor("octopus"), OverlayOctopus);
  assert.equal(OverlayGround.tricksFor("cup"), OverlayOctopus);
  assert.equal(OverlayGround.tricksFor("cuttlefish"), OverlayCuttlefish);
  assert.equal(OverlayGround.tricksFor("sepia"), OverlayCuttlefish);
  assert.equal(OverlayGround.tricksFor("carpet_python"), OverlayCarpetPython);
  assert.equal(OverlayGround.tricksFor("atlas"), OverlayCarpetPython);
  assert.equal(OverlayGround.tricksFor("nautilus"), Overlay);
  assert.equal(OverlayGround.tricksFor("chamber"), Overlay);
  assert.equal(OverlayGround.wantsThankYou("turtle"), true);
  assert.equal(OverlayGround.wantsThankYou("ink"), true);
  assert.equal(OverlayGround.wantsThankYou("goldfish"), true);
  assert.equal(OverlayGround.wantsThankYou("coin"), true);
  assert.equal(OverlayGround.wantsThankYou("axolotl"), true);
  assert.equal(OverlayGround.wantsThankYou("bloom"), true);
  assert.equal(OverlayGround.wantsThankYou("octopus"), true);
  assert.equal(OverlayGround.wantsThankYou("cup"), true);
  assert.equal(OverlayGround.wantsThankYou("cuttlefish"), true);
  assert.equal(OverlayGround.wantsThankYou("sepia"), true);
  assert.equal(OverlayGround.wantsThankYou("carpet_python"), true);
  assert.equal(OverlayGround.wantsThankYou("atlas"), true);
  assert.equal(OverlayGround.wantsThankYou("nautilus"), true);
  assert.equal(OverlayGround.wantsThankYou("chamber"), true);
  assert.equal(OverlayGround.sleepHoldFrame("red_panda", 4), 1);
  assert.equal(OverlayGround.sleepHoldFrame("nautilus", 4), null);
  assert.deepEqual([...OverlayTurtle.TRICKS], ["soak", "tuck", "crane", "plod", "paddle", "snorkel", "wipe"]);
  assert.deepEqual([...OverlayGoldfish.TRICKS], ["drift", "gulp", "flare", "glint", "dart", "yawn", "forage"]);
  assert.deepEqual([...OverlayAxolotl.TRICKS], ["gill", "amble", "mend", "smile", "plume", "sprout", "glop"]);
  assert.deepEqual([...OverlayOctopus.TRICKS], ["mantle", "sucker", "jet", "veil", "tinker", "papilla", "ooze"]);
  assert.deepEqual([...OverlayCuttlefish.TRICKS], ["bone", "pupil", "chroma", "hover", "blot"]);
  assert.deepEqual([...OverlayCarpetPython.TRICKS], ["legend", "rung", "contour", "runner", "bearing", "canopy", "inset"]);
  assert.deepEqual([...Overlay.TRICKS], ["spiral", "siphuncle", "nacre", "pinhole", "fringe"]);
  assert.equal(Overlay.TRICKS.includes("rise"), false);
  assert.equal(Overlay.TRICKS.includes("jet"), false);
  assert.equal(Overlay.TRICKS.includes("mantle"), false);
  assert.equal(Overlay.TRICKS.includes("bone"), false);
  assert.equal(Overlay.TRICKS.includes("drift"), false);
  assert.equal(Overlay.TRICKS.includes("tuck"), false);
  assert.equal(Overlay.TRICKS.includes("gill"), false);
  assert.equal(Overlay.TRICKS.includes("legend"), false);
});

test("notes: Chamber idle-life done; next house-order guest still lacking tricks is Pulse / moon_jelly", () => {
  assert.equal(T.TRICK_KEY, "nautilus");
  assert.equal(T.wantsThankYou("chamber"), true);
  assert.equal(OverlayGround.tricksFor("nautilus"), Overlay);
  assert.equal(OverlayGround.tricksFor("chamber"), Overlay);
  assert.equal(OverlayGround.wantsThankYou("nautilus"), true);
  assert.equal(OverlayGround.wantsThankYou("chamber"), true);
  assert.equal(OverlayGround.tricksFor("cuttlefish"), OverlayCuttlefish);
  assert.equal(OverlayGround.tricksFor("sepia"), OverlayCuttlefish);
  assert.equal(OverlayGround.tricksFor("octopus"), OverlayOctopus);
  assert.equal(OverlayGround.tricksFor("cup"), OverlayOctopus);
  assert.equal(OverlayGround.tricksFor("carpet_python"), OverlayCarpetPython);
  assert.equal(OverlayGround.tricksFor("atlas"), OverlayCarpetPython);
  assert.equal(OverlayGround.tricksFor("turtle"), OverlayTurtle);
  assert.equal(OverlayGround.tricksFor("ink"), OverlayTurtle);
  assert.equal(OverlayGround.tricksFor("goldfish"), OverlayGoldfish);
  assert.equal(OverlayGround.tricksFor("coin"), OverlayGoldfish);
  assert.equal(OverlayGround.tricksFor("axolotl"), OverlayAxolotl);
  assert.equal(OverlayGround.tricksFor("bloom"), OverlayAxolotl);
  assert.equal(OverlayGround.tricksFor("moon_jelly"), null);
  assert.equal(OverlayGround.wantsThankYou("moon_jelly"), false);
  assert.equal(OverlayGround.tricksFor("pulse"), null);
  assert.equal(OverlayGround.wantsThankYou("pulse"), false);
});
