import assert from "node:assert/strict";
import { createRequire } from "node:module";
import { dirname, join } from "node:path";
import { test } from "node:test";
import { fileURLToPath, pathToFileURL } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const Orchid = await import(pathToFileURL(join(root, "src/lib/pets/orchid-tricks.ts")).href);
const Saguaro = await import(pathToFileURL(join(root, "src/lib/pets/saguaro-tricks.ts")).href);
const VenusFlytrap = await import(pathToFileURL(join(root, "src/lib/pets/venus_flytrap-tricks.ts")).href);
const T = await import(pathToFileURL(join(root, "src/lib/pets/pitcher-tricks.ts")).href);
const Sundew = await import(pathToFileURL(join(root, "src/lib/pets/sundew-tricks.ts")).href);
const Honeybee = await import(pathToFileURL(join(root, "src/lib/pets/honeybee-tricks.ts")).href);
const Monarch = await import(pathToFileURL(join(root, "src/lib/pets/monarch-tricks.ts")).href);
const Luna = await import(pathToFileURL(join(root, "src/lib/pets/luna-tricks.ts")).href);
const Oak = await import(pathToFileURL(join(root, "src/lib/pets/oak-tricks.ts")).href);
const WaterLily = await import(pathToFileURL(join(root, "src/lib/pets/water_lily-tricks.ts")).href);
const Ginkgo = await import(pathToFileURL(join(root, "src/lib/pets/ginkgo-tricks.ts")).href);
const Maidenhair = await import(pathToFileURL(join(root, "src/lib/pets/maidenhair-tricks.ts")).href);
const Moss = await import(pathToFileURL(join(root, "src/lib/pets/moss-tricks.ts")).href);
const Manta = await import(pathToFileURL(join(root, "src/lib/pets/manta-tricks.ts")).href);
const Moray = await import(pathToFileURL(join(root, "src/lib/pets/moray-tricks.ts")).href);
const Seahorse = await import(pathToFileURL(join(root, "src/lib/pets/seahorse-tricks.ts")).href);
const SeaStar = await import(pathToFileURL(join(root, "src/lib/pets/sea_star-tricks.ts")).href);
const HermitCrab = await import(pathToFileURL(join(root, "src/lib/pets/hermit_crab-tricks.ts")).href);
const HorseshoeCrab = await import(pathToFileURL(join(root, "src/lib/pets/horseshoe_crab-tricks.ts")).href);
const MoonJelly = await import(pathToFileURL(join(root, "src/lib/pets/moon_jelly-tricks.ts")).href);
const Nautilus = await import(pathToFileURL(join(root, "src/lib/pets/nautilus-tricks.ts")).href);
const Cuttlefish = await import(pathToFileURL(join(root, "src/lib/pets/cuttlefish-tricks.ts")).href);
const Octopus = await import(pathToFileURL(join(root, "src/lib/pets/octopus-tricks.ts")).href);
const CarpetPython = await import(pathToFileURL(join(root, "src/lib/pets/carpet-python-tricks.ts")).href);
const RosyBoa = await import(pathToFileURL(join(root, "src/lib/pets/rosy-boa-tricks.ts")).href);
const MilkSnake = await import(pathToFileURL(join(root, "src/lib/pets/milk-snake-tricks.ts")).href);
const Garter = await import(pathToFileURL(join(root, "src/lib/pets/garter-tricks.ts")).href);
const Boa = await import(pathToFileURL(join(root, "src/lib/pets/boa-tricks.ts")).href);
const Hognose = await import(pathToFileURL(join(root, "src/lib/pets/hognose-tricks.ts")).href);
const GreenTreePython = await import(pathToFileURL(join(root, "src/lib/pets/green-tree-python-tricks.ts")).href);
const BallPython = await import(pathToFileURL(join(root, "src/lib/pets/ball-python-tricks.ts")).href);
const CornSnake = await import(pathToFileURL(join(root, "src/lib/pets/corn-snake-tricks.ts")).href);
const Kingsnake = await import(pathToFileURL(join(root, "src/lib/pets/kingsnake-tricks.ts")).href);
const Phoenix = await import(pathToFileURL(join(root, "src/lib/pets/phoenix-tricks.ts")).href);
const Dragon = await import(pathToFileURL(join(root, "src/lib/pets/dragon-tricks.ts")).href);
const Rui = await import(pathToFileURL(join(root, "src/lib/pets/rui-tricks.ts")).href);
const Relay = await import(pathToFileURL(join(root, "src/lib/pets/relay-tricks.ts")).href);
const Fuse = await import(pathToFileURL(join(root, "src/lib/pets/fuse-tricks.ts")).href);
const Earth = await import(pathToFileURL(join(root, "src/lib/pets/earth-tricks.ts")).href);
const Cat = await import(pathToFileURL(join(root, "src/lib/pets/cat-tricks.ts")).href);
const Dog = await import(pathToFileURL(join(root, "src/lib/pets/dog-tricks.ts")).href);
const Rabbit = await import(pathToFileURL(join(root, "src/lib/pets/rabbit-tricks.ts")).href);
const Hamster = await import(pathToFileURL(join(root, "src/lib/pets/hamster-tricks.ts")).href);
const GuineaPig = await import(pathToFileURL(join(root, "src/lib/pets/guinea-pig-tricks.ts")).href);
const Turtle = await import(pathToFileURL(join(root, "src/lib/pets/turtle-tricks.ts")).href);
const Goldfish = await import(pathToFileURL(join(root, "src/lib/pets/goldfish-tricks.ts")).href);
const Budgie = await import(pathToFileURL(join(root, "src/lib/pets/budgie-tricks.ts")).href);
const Fox = await import(pathToFileURL(join(root, "src/lib/pets/fox-tricks.ts")).href);
const Penguin = await import(pathToFileURL(join(root, "src/lib/pets/penguin-tricks.ts")).href);
const Parrot = await import(pathToFileURL(join(root, "src/lib/pets/parrot-tricks.ts")).href);
const Ferret = await import(pathToFileURL(join(root, "src/lib/pets/ferret-tricks.ts")).href);
const Hedgehog = await import(pathToFileURL(join(root, "src/lib/pets/hedgehog-tricks.ts")).href);
const Chinchilla = await import(pathToFileURL(join(root, "src/lib/pets/chinchilla-tricks.ts")).href);
const Axolotl = await import(pathToFileURL(join(root, "src/lib/pets/axolotl-tricks.ts")).href);
const Toucan = await import(pathToFileURL(join(root, "src/lib/pets/toucan-tricks.ts")).href);
const Iguana = await import(pathToFileURL(join(root, "src/lib/pets/iguana-tricks.ts")).href);
const OverlayOrchid = createRequire(import.meta.url)(join(root, "../desktop/renderer/orchid-tricks.js"));
const OverlaySaguaro = createRequire(import.meta.url)(join(root, "../desktop/renderer/saguaro-tricks.js"));
const OverlayVenusFlytrap = createRequire(import.meta.url)(join(root, "../desktop/renderer/venus_flytrap-tricks.js"));
const Overlay = createRequire(import.meta.url)(join(root, "../desktop/renderer/pitcher-tricks.js"));
const OverlaySundew = createRequire(import.meta.url)(join(root, "../desktop/renderer/sundew-tricks.js"));
const OverlayHoneybee = createRequire(import.meta.url)(join(root, "../desktop/renderer/honeybee-tricks.js"));
const OverlayMonarch = createRequire(import.meta.url)(join(root, "../desktop/renderer/monarch-tricks.js"));
const OverlayLuna = createRequire(import.meta.url)(join(root, "../desktop/renderer/luna-tricks.js"));
const OverlayOak = createRequire(import.meta.url)(join(root, "../desktop/renderer/oak-tricks.js"));
const OverlayWaterLily = createRequire(import.meta.url)(join(root, "../desktop/renderer/water_lily-tricks.js"));
const OverlayGinkgo = createRequire(import.meta.url)(join(root, "../desktop/renderer/ginkgo-tricks.js"));
const OverlayMaidenhair = createRequire(import.meta.url)(join(root, "../desktop/renderer/maidenhair-tricks.js"));
const OverlayMoss = createRequire(import.meta.url)(join(root, "../desktop/renderer/moss-tricks.js"));
const OverlayManta = createRequire(import.meta.url)(join(root, "../desktop/renderer/manta-tricks.js"));
const OverlayMoray = createRequire(import.meta.url)(join(root, "../desktop/renderer/moray-tricks.js"));
const OverlaySeahorse = createRequire(import.meta.url)(join(root, "../desktop/renderer/seahorse-tricks.js"));
const OverlaySeaStar = createRequire(import.meta.url)(join(root, "../desktop/renderer/sea_star-tricks.js"));
const OverlayHermitCrab = createRequire(import.meta.url)(join(root, "../desktop/renderer/hermit_crab-tricks.js"));
const OverlayHorseshoeCrab = createRequire(import.meta.url)(join(root, "../desktop/renderer/horseshoe_crab-tricks.js"));
const OverlayMoonJelly = createRequire(import.meta.url)(join(root, "../desktop/renderer/moon_jelly-tricks.js"));
const OverlayNautilus = createRequire(import.meta.url)(join(root, "../desktop/renderer/nautilus-tricks.js"));
const OverlayCuttlefish = createRequire(import.meta.url)(join(root, "../desktop/renderer/cuttlefish-tricks.js"));
const OverlayOctopus = createRequire(import.meta.url)(join(root, "../desktop/renderer/octopus-tricks.js"));
const OverlayCarpetPython = createRequire(import.meta.url)(join(root, "../desktop/renderer/carpet-python-tricks.js"));
const OverlayRosyBoa = createRequire(import.meta.url)(join(root, "../desktop/renderer/rosy-boa-tricks.js"));
const OverlayMilkSnake = createRequire(import.meta.url)(join(root, "../desktop/renderer/milk-snake-tricks.js"));
const OverlayGarter = createRequire(import.meta.url)(join(root, "../desktop/renderer/garter-tricks.js"));
const OverlayBoa = createRequire(import.meta.url)(join(root, "../desktop/renderer/boa-tricks.js"));
const OverlayHognose = createRequire(import.meta.url)(join(root, "../desktop/renderer/hognose-tricks.js"));
const OverlayGreenTreePython = createRequire(import.meta.url)(join(root, "../desktop/renderer/green-tree-python-tricks.js"));
const OverlayBallPython = createRequire(import.meta.url)(join(root, "../desktop/renderer/ball-python-tricks.js"));
const OverlayCornSnake = createRequire(import.meta.url)(join(root, "../desktop/renderer/corn-snake-tricks.js"));
const OverlayKingsnake = createRequire(import.meta.url)(join(root, "../desktop/renderer/kingsnake-tricks.js"));
const OverlayPhoenix = createRequire(import.meta.url)(join(root, "../desktop/renderer/phoenix-tricks.js"));
const OverlayGround = createRequire(import.meta.url)(join(root, "../desktop/renderer/ground-tricks.js"));
const OverlayRui = createRequire(import.meta.url)(join(root, "../desktop/renderer/rui-tricks.js"));
const OverlayRelay = createRequire(import.meta.url)(join(root, "../desktop/renderer/relay-tricks.js"));
const OverlayFuse = createRequire(import.meta.url)(join(root, "../desktop/renderer/fuse-tricks.js"));
const OverlayEarth = createRequire(import.meta.url)(join(root, "../desktop/renderer/earth-tricks.js"));
const OverlayCat = createRequire(import.meta.url)(join(root, "../desktop/renderer/cat-tricks.js"));
const OverlayDog = createRequire(import.meta.url)(join(root, "../desktop/renderer/dog-tricks.js"));
const OverlayRabbit = createRequire(import.meta.url)(join(root, "../desktop/renderer/rabbit-tricks.js"));
const OverlayHamster = createRequire(import.meta.url)(join(root, "../desktop/renderer/hamster-tricks.js"));
const OverlayGuineaPig = createRequire(import.meta.url)(join(root, "../desktop/renderer/guinea-pig-tricks.js"));
const OverlayTurtle = createRequire(import.meta.url)(join(root, "../desktop/renderer/turtle-tricks.js"));
const OverlayGoldfish = createRequire(import.meta.url)(join(root, "../desktop/renderer/goldfish-tricks.js"));
const OverlayBudgie = createRequire(import.meta.url)(join(root, "../desktop/renderer/budgie-tricks.js"));
const OverlayFox = createRequire(import.meta.url)(join(root, "../desktop/renderer/fox-tricks.js"));
const OverlayPenguin = createRequire(import.meta.url)(join(root, "../desktop/renderer/penguin-tricks.js"));
const OverlayParrot = createRequire(import.meta.url)(join(root, "../desktop/renderer/parrot-tricks.js"));
const OverlayFerret = createRequire(import.meta.url)(join(root, "../desktop/renderer/ferret-tricks.js"));
const OverlayHedgehog = createRequire(import.meta.url)(join(root, "../desktop/renderer/hedgehog-tricks.js"));
const OverlayChinchilla = createRequire(import.meta.url)(join(root, "../desktop/renderer/chinchilla-tricks.js"));
const OverlayAxolotl = createRequire(import.meta.url)(join(root, "../desktop/renderer/axolotl-tricks.js"));
const OverlayToucan = createRequire(import.meta.url)(join(root, "../desktop/renderer/toucan-tricks.js"));
const OverlayIguana = createRequire(import.meta.url)(join(root, "../desktop/renderer/iguana-tricks.js"));
const OverlayDragon = createRequire(import.meta.url)(join(root, "../desktop/renderer/dragon-tricks.js"));

test("Drown tricks start only on idle ground", () => {
  assert.deepEqual([...Turtle.TRICKS], ["soak", "tuck", "crane", "plod", "paddle", "snorkel", "wipe"]);
  assert.deepEqual([...Goldfish.TRICKS], ["drift", "gulp", "flare", "glint", "dart", "yawn", "forage"]);
  assert.deepEqual([...Axolotl.TRICKS], ["gill", "amble", "mend", "smile", "plume", "sprout", "glop"]);
  assert.deepEqual([...Octopus.TRICKS], ["mantle", "sucker", "jet", "veil", "tinker", "papilla", "ooze"]);
  assert.deepEqual([...Cuttlefish.TRICKS], ["bone", "pupil", "chroma", "hover", "blot", "strike", "zebra"]);
  assert.deepEqual([...Nautilus.TRICKS], ["spiral", "siphuncle", "nacre", "pinhole", "fringe", "hyponome", "aperture"]);
  assert.deepEqual([...CarpetPython.TRICKS], ["legend", "rung", "contour", "runner", "bearing", "canopy", "inset"]);
  assert.deepEqual([...T.TRICKS], ["peristome", "cistern", "brine", "operculum", "urn", "ala", "baffle"]);
  assert.deepEqual([...Oak.TRICKS], ["acorn", "sinus", "gall", "taproot", "bole", "catkin", "tyloses"]);
  assert.deepEqual([...Moss.TRICKS], ["tuft", "bead", "spore", "cushion", "thatch", "rhizoid", "seta"]);
  assert.equal(T.canStart({ asleep: false, hidden: false, leaving: false, cmd: "idle" }), true);
  assert.equal(T.canStart({ asleep: true, hidden: false, leaving: false, cmd: "idle" }), false);
  assert.equal(T.canStart({ asleep: false, hidden: true, leaving: false, cmd: "idle" }), false);
  assert.equal(T.canStart({ asleep: false, hidden: false, leaving: false, cmd: "sleep" }), false);
  assert.equal(T.canStart({ asleep: false, hidden: false, leaving: false, cmd: "seek" }), false);
  assert.equal(T.canStart({ asleep: false, hidden: false, leaving: false, cmd: "idle", windowPlay: true }), false);
  assert.equal(T.canStart({ asleep: false, hidden: false, leaving: false, cmd: "idle", card: true }), false);
  assert.equal(T.shouldAbort({ asleep: true, hidden: false, leaving: false, cmd: "idle" }), true);
  assert.equal(T.shouldAbort({ asleep: false, hidden: false, leaving: false, cmd: "idle", card: true }), true);
  assert.equal(T.shouldAbort({ asleep: false, hidden: false, leaving: false, cmd: "idle" }), false);
  assert.equal(T.pickTrick(0.99, true), "urn");
  assert.notEqual(T.pickTrick(0.3, false, "urn"), "drift");
  assert.notEqual(T.pickTrick(0.3, false, "urn"), "soak");
  assert.notEqual(T.pickTrick(0.3, false, "urn"), "gill");
  assert.notEqual(T.pickTrick(0.3, false, "urn"), "mantle");
  assert.notEqual(T.pickTrick(0.3, false, "urn"), "bone");
  assert.notEqual(T.pickTrick(0.3, false, "urn"), "spiral");
  assert.notEqual(T.pickTrick(0.3, false, "urn"), "legend");
  assert.notEqual(T.pickTrick(0.3, false, "urn"), "bell");
  assert.notEqual(T.pickTrick(0.3, false, "urn"), "podia");
  assert.notEqual(T.pickTrick(0.3, false, "urn"), "scurry");
  assert.notEqual(T.pickTrick(0.3, false, "urn"), "curl");
  assert.equal(Overlay.TRICK_KEY, "pitcher");
  assert.equal(T.sleepHoldFrame("pitcher", 4), null);
  assert.equal(T.TRICKS.includes("barrel"), false);
  assert.equal(T.TRICKS.includes("coil"), false);
  assert.equal(T.TRICKS.includes("buoy"), false);
  assert.equal(T.TRICKS.includes("siphon"), false);
  assert.equal(T.TRICKS.includes("swivel"), false);
  assert.equal(T.TRICKS.includes("pouch"), false);
  assert.equal(T.TRICKS.includes("somersault"), false);
  assert.equal(T.TRICKS.includes("drift"), false);
  assert.equal(T.HAPPY.includes("coronet"), false);
  assert.equal(T.TRICKS.includes("plow"), false);
  assert.equal(T.TRICKS.includes("plow"), false);
  assert.equal(T.TRICKS.includes("swap"), false);
  assert.equal(T.TRICKS.includes("withdraw"), false);
  assert.equal(T.TRICKS.includes("vacancy"), false);
  assert.equal(T.TRICKS.includes("antenna"), false);
  assert.equal(T.TRICKS.includes("scuttle"), false);
  assert.equal(T.HAPPY.includes("halo"), false);
  assert.equal(T.HAPPY.includes("lumen"), false);
  assert.equal(T.HAPPY.includes("gel"), false);

  assert.equal(T.TRICKS.includes("soar"), false);
  assert.equal(T.TRICKS.includes("rise"), false);
  assert.equal(T.TRICKS.includes("drift"), false);
  assert.equal(T.TRICKS.includes("hover"), false);
  assert.equal(T.TRICKS.includes("mantle"), false);
  assert.equal(T.TRICKS.includes("jet"), false);
  assert.equal(T.TRICKS.includes("veil"), false);
  assert.equal(T.TRICKS.includes("bone"), false);
  assert.equal(T.TRICKS.includes("spiral"), false);
  assert.equal(T.TRICKS.includes("fringe"), false);
  assert.equal(T.TRICKS.includes("nacre"), false);
  assert.equal(T.TRICKS.includes("gulp"), false);
  assert.equal(T.TRICKS.includes("flare"), false);
  assert.equal(T.TRICKS.includes("dart"), false);
  assert.equal(T.TRICKS.includes("soak"), false);
  assert.equal(T.TRICKS.includes("gill"), false);
  assert.equal(T.TRICKS.includes("hood"), false);
  assert.equal(Overlay.TRICKS.includes("barrel"), false);
  assert.equal(Overlay.TRICKS.includes("soar"), false);
  assert.equal(Overlay.TRICKS.includes("plow"), false);
  assert.equal(Overlay.TRICKS.includes("plow"), false);
  assert.equal(Overlay.TRICKS.includes("bell"), false);
  assert.equal(Overlay.HAPPY.includes("damp"), false);
  assert.equal(Overlay.HAPPY.includes("keep"), false);
  assert.equal(Overlay.HAPPY.includes("ripple"), false);
  assert.equal(Overlay.HAPPY.includes("chamber"), false);
  assert.equal(Overlay.HAPPY.includes("pulse"), false);
  assert.equal(Overlay.HAPPY.includes("bubble"), false);
  assert.equal(Overlay.HAPPY.includes("glow"), false);
  assert.deepEqual([...Overlay.TRICKS], ["peristome", "cistern", "brine", "operculum", "urn", "ala", "baffle"]);
  assert.deepEqual([...Overlay.HAPPY], ["midge", "rain", "maroon"]);
  assert.deepEqual([...WaterLily.TRICKS], ["pad", "corolla", "rhizome", "calyx", "sheen", "peltate", "hydropote"]);

  assert.equal(T.TRICKS.includes("gape"), false);
  assert.equal(T.TRICKS.includes("crevice"), false);
  assert.equal(T.TRICKS.includes("flash"), false);
  assert.equal(T.TRICKS.includes("wing"), false);
  assert.equal(T.TRICKS.includes("lobe"), false);
  assert.equal(T.TRICKS.includes("gyre"), false);
  assert.equal(T.TRICKS.includes("vault"), false);
  assert.equal(T.TRICKS.includes("span"), false);
  assert.equal(T.TRICKS.includes("coil"), false);
  assert.equal(T.HAPPY.includes("ceil"), false);
  assert.equal(T.HAPPY.includes("scoop"), false);
  assert.equal(T.HAPPY.includes("breadth"), false);
  assert.equal(T.HAPPY.includes("coronet"), false);
  assert.equal(T.TRICKS.includes("frond"), false);
  assert.equal(T.TRICKS.includes("rachis"), false);
  assert.equal(T.TRICKS.includes("fiddle"), false);
  assert.equal(T.TRICKS.includes("pinna"), false);
  assert.equal(T.TRICKS.includes("saucer"), false);
  assert.equal(T.TRICKS.includes("tuft"), false);
  assert.equal(T.TRICKS.includes("gold"), false);
  assert.equal(T.TRICKS.includes("fossil"), false);
  assert.equal(T.TRICKS.includes("lean"), false);
  assert.equal(T.TRICKS.includes("nod"), false);
  assert.equal(Maidenhair.TRICKS.includes("frond"), true);
  assert.equal(Moss.TRICKS.includes("tuft"), true);
  assert.equal(Parrot.TRICKS.includes("fan"), true);
});

test("peristome/cistern/brine/operculum/urn/ala/baffle are house-pitcher-true, not copies of prior guests", () => {
  const ground = { asleep: false, hidden: false, leaving: false, cmd: "idle" };
  const bole = T.beginTrick("urn", 80, 1);
  assert.equal(bole.anim, "sit");
  assert.equal(bole.phase, "hold");
  const held = T.stepTrick(bole, 5, ground);
  assert.equal(held.phase, "hold");
  assert.equal(held.anim, "sit");
  assert.ok(held.rot !== 0 || held.lift > 0);
  const release = T.stepTrick(bole, T.URN_HOLD + 0.2, ground);
  assert.equal(release.phase, "release");
  assert.equal(release.anim, "sit");
  const doneBole = T.stepTrick(bole, T.DUR.urn + 0.1, ground);
  assert.equal(doneBole.phase, "done");
  assert.ok(T.nextTrickWait(true, 0, "urn") > T.nextTrickWait(true, 0, "brine"));
  const acorn = T.beginTrick("peristome", 80, 1);
  assert.equal(acorn.anim, "play");
  const acornMid = T.stepTrick(acorn, 0.5, ground);
  assert.ok(Math.abs(acornMid.lift) > 0.05 || Math.abs(acornMid.rot) > 1 || Math.abs(acornMid.x - 80) > 0.05);
  const gall = T.beginTrick("cistern", 80, 1);
  assert.equal(gall.anim, "sit");
  const gallMid = T.stepTrick(gall, 0.5, ground);
  assert.ok(Math.abs(gallMid.lift) > 0.05 || Math.abs(gallMid.rot) > 1 || Math.abs(gallMid.x - 80) > 0.05);
  const sinus = T.beginTrick("brine", 80, 1);
  assert.equal(sinus.anim, "sit");
  const sinusMid = T.stepTrick(sinus, 0.5, ground);
  assert.ok(Math.abs(sinusMid.lift) > 0.05 || Math.abs(sinusMid.rot) > 1 || Math.abs(sinusMid.x - 80) > 0.05);
  const taproot = T.beginTrick("operculum", 80, 1);
  assert.equal(taproot.anim, "talk");
  const taprootMid = T.stepTrick(taproot, 0.5, ground);
  assert.ok(Math.abs(taprootMid.lift) > 0.05 || Math.abs(taprootMid.rot) > 1 || Math.abs(taprootMid.x - 80) > 0.05);
  const ala = T.beginTrick("ala", 80, 1);
  assert.equal(ala.anim, "play");
  const alaMid = T.stepTrick(ala, 0.5, ground);
  assert.ok(Math.abs(alaMid.lift) > 0.05 || Math.abs(alaMid.rot) > 1 || Math.abs(alaMid.x - 80) > 0.05);
  const baffle = T.beginTrick("baffle", 80, 1);
  assert.equal(baffle.anim, "talk");
  const baffleMid = T.stepTrick(baffle, 0.5, ground);
  assert.ok(Math.abs(baffleMid.lift) > 0.05 || Math.abs(baffleMid.rot) > 1 || Math.abs(baffleMid.x - 80) > 0.05);
  const sinusDone = T.stepTrick(sinus, T.DUR.brine + 0.1, ground);
  assert.equal(sinusDone.phase, "done");
  const aborted = T.stepTrick(held, 0.1, { asleep: true, cmd: "sleep" });
  assert.equal(aborted.phase, "done");
  for (const mod of [Rui, Cat, Dog, Rabbit, Hamster, GuineaPig, Turtle, Goldfish, Budgie, Fox, Penguin, Parrot, Ferret, Hedgehog, Chinchilla, Axolotl, Toucan, Iguana, Dragon, Phoenix, BallPython, CornSnake, Kingsnake, GreenTreePython, Hognose, Garter, Boa, MilkSnake, RosyBoa, CarpetPython, Octopus, Cuttlefish, Nautilus, MoonJelly, SeaStar, HermitCrab, HorseshoeCrab, Seahorse, Manta, Moray, Moss, Maidenhair, Ginkgo, Oak, WaterLily, Orchid, Saguaro, VenusFlytrap, Sundew, Monarch, Luna, Relay, Fuse, Earth]) {
    assert.equal(mod.TRICKS.includes("peristome"), false);
    assert.equal(mod.TRICKS.includes("cistern"), false);
    assert.equal(mod.TRICKS.includes("brine"), false);
    assert.equal(mod.TRICKS.includes("operculum"), false);
    assert.equal(mod.TRICKS.includes("urn"), false);
    assert.equal(mod.TRICKS.includes("ala"), false);
    assert.equal(mod.TRICKS.includes("baffle"), false);
  }
  assert.equal(T.TRICKS.includes("pad"), false);
  assert.equal(T.TRICKS.includes("corolla"), false);
  assert.equal(T.TRICKS.includes("rhizome"), false);
  assert.equal(T.TRICKS.includes("calyx"), false);
  assert.equal(T.TRICKS.includes("sheen"), false);
  assert.equal(T.HAPPY.includes("silt"), false);
  assert.equal(T.HAPPY.includes("nectar"), false);
  assert.equal(T.HAPPY.includes("dew"), false);
  assert.deepEqual([...WaterLily.TRICKS], ["pad", "corolla", "rhizome", "calyx", "sheen", "peltate", "hydropote"]);
  assert.deepEqual([...WaterLily.HAPPY], ["silt", "nectar", "dew"]);
  assert.deepEqual([...Turtle.TRICKS], ["soak", "tuck", "crane", "plod", "paddle", "snorkel", "wipe"]);
  assert.deepEqual([...Goldfish.TRICKS], ["drift", "gulp", "flare", "glint", "dart", "yawn", "forage"]);
  assert.deepEqual([...Axolotl.TRICKS], ["gill", "amble", "mend", "smile", "plume", "sprout", "glop"]);
  assert.deepEqual([...Octopus.TRICKS], ["mantle", "sucker", "jet", "veil", "tinker", "papilla", "ooze"]);
  assert.deepEqual([...Cuttlefish.TRICKS], ["bone", "pupil", "chroma", "hover", "blot", "strike", "zebra"]);
  assert.deepEqual([...Nautilus.TRICKS], ["spiral", "siphuncle", "nacre", "pinhole", "fringe", "hyponome", "aperture"]);
  assert.deepEqual([...CarpetPython.TRICKS], ["legend", "rung", "contour", "runner", "bearing", "canopy", "inset"]);
  assert.equal(T.TRICKS.includes("chime"), false);
  assert.equal(T.TRICKS.includes("pulse"), false);
  assert.equal(T.TRICKS.includes("drift"), false);
  assert.equal(T.TRICKS.includes("jet"), false);
  assert.equal(T.TRICKS.includes("mantle"), false);
  assert.equal(T.TRICKS.includes("bone"), false);
  assert.equal(T.TRICKS.includes("spiral"), false);
  assert.equal(T.TRICKS.includes("hover"), false);
  assert.equal(T.TRICKS.includes("fringe"), false);
  assert.equal(T.TRICKS.includes("hood"), false);
  assert.equal(Cuttlefish.TRICKS.includes("bone"), true);
  assert.equal(Octopus.TRICKS.includes("jet"), true);
  assert.equal(Nautilus.TRICKS.includes("spiral"), true);
  assert.equal(Goldfish.TRICKS.includes("drift"), true);
  assert.equal(Fuse.HAPPY.includes("densfuse"), true);
  assert.equal(T.TRICKS.includes("podia"), false);
  assert.equal(T.TRICKS.includes("righting"), false);
  assert.equal(T.TRICKS.includes("crawl"), false);
  assert.equal(T.TRICKS.includes("evert"), false);
  assert.equal(T.TRICKS.includes("penta"), false);
  assert.equal(T.TRICKS.includes("scurry"), false);
  assert.equal(T.TRICKS.includes("nest"), false);
  assert.equal(T.TRICKS.includes("cheek"), false);
  assert.equal(T.TRICKS.includes("curl"), false);
  assert.equal(T.TRICKS.includes("tuck"), false);
  assert.equal(T.TRICKS.includes("barrel"), false);
  assert.equal(T.TRICKS.includes("plow"), false);
  assert.equal(T.TRICKS.includes("plow"), false);
  assert.equal(T.TRICKS.includes("swap"), false);
  assert.equal(T.TRICKS.includes("withdraw"), false);
  assert.equal(T.TRICKS.includes("vacancy"), false);
  assert.equal(T.TRICKS.includes("antenna"), false);
  assert.equal(T.TRICKS.includes("scuttle"), false);
  assert.equal(T.HAPPY.includes("halo"), false);
  assert.equal(T.HAPPY.includes("lumen"), false);
  assert.equal(T.HAPPY.includes("gel"), false);

  assert.equal(T.TRICKS.includes("trade"), false);
  assert.equal(T.HAPPY.includes("damp"), false);
  assert.equal(T.HAPPY.includes("press"), false);
  assert.equal(T.HAPPY.includes("tide"), false);
  assert.equal(T.HAPPY.includes("tap"), false);
  assert.deepEqual([...Hamster.TRICKS], ["nest", "cheek", "scurry", "pocket", "reel", "scrub", "seed"]);
  assert.deepEqual([...Hedgehog.TRICKS], ["curl", "snuffle", "anoint", "bristle", "root", "trundle", "wheel"]);
  assert.deepEqual([...SeaStar.TRICKS], ["podia", "righting", "crawl", "evert", "penta", "madre", "papula"]);
  assert.deepEqual([...HermitCrab.TRICKS], ["swap", "antenna", "scuttle", "withdraw", "vacancy", "chela", "bailer"]);
  assert.deepEqual([...HorseshoeCrab.TRICKS], ["carapace", "bookgill", "telson", "furrow", "fossil", "pusher", "ocular"]);
  assert.deepEqual([...Seahorse.TRICKS], ["coil", "buoy", "siphon", "swivel", "pouch", "dorsal", "pectoral"]);
  assert.deepEqual([...Manta.TRICKS], ["wing", "lobe", "gyre", "vault", "span", "breach", "ram"]);
  assert.equal(SeaStar.TRICKS.includes("podia"), true);
  assert.equal(HermitCrab.TRICKS.includes("swap"), true);
  assert.equal(Hamster.TRICKS.includes("scurry"), true);
  assert.equal(Hedgehog.TRICKS.includes("curl"), true);
});

test("Drown feed-happy is its own sit: midge/rain/maroon, and two feeds are not the same", () => {
  assert.deepEqual([...T.HAPPY], ["midge", "rain", "maroon"]);
  assert.equal(T.HAPPY.includes("halo"), false);
  assert.equal(T.HAPPY.includes("lumen"), false);
  assert.equal(T.HAPPY.includes("gel"), false);
  assert.equal(T.HAPPY.includes("bubble"), false);
  assert.equal(T.HAPPY.includes("munch"), false);
  assert.equal(T.HAPPY.includes("wink"), false);
  assert.equal(T.HAPPY.includes("keep"), false);
  assert.equal(T.HAPPY.includes("tint"), false);
  assert.equal(T.HAPPY.includes("squeeze"), false);
  assert.equal(T.HAPPY.includes("ripple"), false);
  assert.equal(T.HAPPY.includes("glance"), false);
  assert.equal(T.HAPPY.includes("dab"), false);
  assert.equal(T.HAPPY.includes("chamber"), false);
  assert.equal(T.HAPPY.includes("silt"), false);
  assert.equal(T.HAPPY.includes("nectar"), false);
  assert.equal(T.HAPPY.includes("dew"), false);
  assert.equal(T.HAPPY.includes("quiet"), false);
  assert.equal(T.HAPPY.includes("pulse"), false);
  assert.equal(T.HAPPY.includes("glow"), false);
  assert.equal(T.HAPPY.includes("tribute"), false);
  assert.equal(T.pickHappy("midge", 0), "rain");
  assert.notEqual(T.pickHappy("midge", 0.9), "ceil");
  assert.equal(Overlay.pickHappy("rain", 0) !== "peat", true);
  assert.equal(T.happyCanStart({ asleep: false, hidden: false, leaving: false, cmd: "idle" }), true);
  assert.equal(T.happyCanStart({ asleep: false, hidden: false, leaving: false, cmd: "idle", card: true }), true);
  assert.equal(T.happyCanStart({ asleep: true, hidden: false, leaving: false, cmd: "idle" }), false);
  assert.equal(T.happyShouldAbort({ cmd: "sleep" }), true);
  assert.equal(T.happyShouldAbort({ cmd: "hide" }), true);
  assert.equal(T.happyShouldAbort({ card: true, cmd: "idle" }), false);
  const cupuleH = T.beginHappy("midge", 80, 1);
  assert.equal(cupuleH.anim, "play");
  const cupuleMid = T.stepHappy(cupuleH, 0.4, { cmd: "idle" });
  assert.ok(cupuleMid.lift > 1.5 || Math.abs(cupuleMid.rot) > 4, "Rui-visible midge thank-you");
  assert.notEqual(cupuleMid.phase, "done");
  const tanninH = T.beginHappy("rain", 80, 1);
  assert.equal(tanninH.anim, "sit");
  const tanninMid = T.stepHappy(tanninH, 0.3, { cmd: "idle" });
  assert.ok(tanninMid.lift !== 0 || Math.abs(tanninMid.rot) > 0.5);
  const groveH = T.beginHappy("maroon", 80, 1);
  assert.equal(groveH.anim, "talk");
  const done = T.stepHappy(cupuleH, T.HAPPY_DUR.midge + 0.1, { cmd: "idle" });
  assert.equal(done.phase, "done");
  const aborted = T.stepHappy(tanninMid, 0.1, { asleep: true, cmd: "sleep" });
  assert.equal(aborted.phase, "done");
  assert.equal(aborted.abort, true);
  assert.equal(T.wantsThankYou("pitcher"), true);
  assert.equal(T.wantsThankYou("drown"), true);
  assert.equal(T.wantsThankYou("moon_jelly"), false);
  assert.equal(T.wantsThankYou("sea_star"), false);
  assert.equal(T.wantsThankYou("cling"), false);
  assert.equal(T.wantsThankYou("hermit_crab"), false);
  assert.equal(T.wantsThankYou("tenant"), false);
  assert.equal(T.wantsThankYou("hamster"), false);
  assert.equal(T.wantsThankYou("clip"), false);
  assert.equal(T.wantsThankYou("hedgehog"), false);
  assert.equal(T.wantsThankYou("burr"), false);
  assert.equal(T.wantsThankYou("pulse"), false);
  assert.equal(T.wantsThankYou("nautilus"), false);
  assert.equal(T.wantsThankYou("chamber"), false);
  assert.equal(T.wantsThankYou("cuttlefish"), false);
  assert.equal(T.wantsThankYou("sepia"), false);
  assert.equal(T.wantsThankYou("octopus"), false);
  assert.equal(T.wantsThankYou("cup"), false);
  assert.equal(T.wantsThankYou("goldfish"), false);
  assert.equal(T.wantsThankYou("coin"), false);
  assert.equal(T.wantsThankYou("turtle"), false);
  assert.equal(T.wantsThankYou("axolotl"), false);
  const thanks = T.startThankYou("pitcher", "midge", 80, 1, { cmd: "idle", card: true, windowPlay: true });
  assert.ok(thanks);
  assert.notEqual(thanks.kind, "ceil");
  assert.ok(thanks.happy.lift === 0);
  assert.notEqual(thanks.happy.anim, "eat");
  assert.notEqual(thanks.happy.anim, "idle");
  const thanksMid = T.stepHappy(thanks.happy, 0.35, { cmd: "idle", card: true });
  assert.ok(thanksMid.lift !== 0 || Math.abs(thanksMid.rot) > 0.5, "a thank-you midges or rains");
  const blocked = T.startThankYou("pitcher", "tribute", 80, 1, { asleep: true, cmd: "idle" });
  assert.equal(blocked, null);
  const other = T.startThankYou("moon_jelly", null, 80, 1, { cmd: "idle" });
  assert.equal(other, null);
  const second = T.startThankYou("pitcher", thanks.kind, 80, 1, { cmd: "idle", card: true });
  assert.ok(second);
  assert.notEqual(second.kind, thanks.kind);
});

test("ground registry keeps prior guests gated; Drown selectable; prior guests still OK", () => {
  assert.equal(Rui.TRICK_KEY, "red_panda");
  assert.equal(Turtle.TRICK_KEY, "turtle");
  assert.equal(Goldfish.TRICK_KEY, "goldfish");
  assert.equal(Axolotl.TRICK_KEY, "axolotl");
  assert.equal(Octopus.TRICK_KEY, "octopus");
  assert.equal(Cuttlefish.TRICK_KEY, "cuttlefish");
  assert.equal(Nautilus.TRICK_KEY, "nautilus");
  assert.equal(CarpetPython.TRICK_KEY, "carpet_python");
  assert.equal(SeaStar.TRICK_KEY, "sea_star");
  assert.equal(HermitCrab.TRICK_KEY, "hermit_crab");
  assert.equal(HorseshoeCrab.TRICK_KEY, "horseshoe_crab");
  assert.equal(T.TRICK_KEY, "pitcher");
  assert.deepEqual([...Turtle.TRICKS], ["soak", "tuck", "crane", "plod", "paddle", "snorkel", "wipe"]);
  assert.deepEqual([...Goldfish.TRICKS], ["drift", "gulp", "flare", "glint", "dart", "yawn", "forage"]);
  assert.deepEqual([...Axolotl.TRICKS], ["gill", "amble", "mend", "smile", "plume", "sprout", "glop"]);
  assert.deepEqual([...Octopus.TRICKS], ["mantle", "sucker", "jet", "veil", "tinker", "papilla", "ooze"]);
  assert.deepEqual([...Cuttlefish.TRICKS], ["bone", "pupil", "chroma", "hover", "blot", "strike", "zebra"]);
  assert.deepEqual([...Nautilus.TRICKS], ["spiral", "siphuncle", "nacre", "pinhole", "fringe", "hyponome", "aperture"]);
  assert.deepEqual([...CarpetPython.TRICKS], ["legend", "rung", "contour", "runner", "bearing", "canopy", "inset"]);
  assert.deepEqual([...SeaStar.TRICKS], ["podia", "righting", "crawl", "evert", "penta", "madre", "papula"]);
  assert.deepEqual([...HermitCrab.TRICKS], ["swap", "antenna", "scuttle", "withdraw", "vacancy", "chela", "bailer"]);
  assert.deepEqual([...T.TRICKS], ["peristome", "cistern", "brine", "operculum", "urn", "ala", "baffle"]);
  assert.equal(T.wantsThankYou("pitcher"), true);
  assert.equal(T.wantsThankYou("drown"), true);
  assert.equal(Turtle.wantsThankYou("ink"), true);
  assert.equal(Goldfish.wantsThankYou("coin"), true);
  assert.equal(Axolotl.wantsThankYou("bloom"), true);
  assert.equal(Octopus.wantsThankYou("cup"), true);
  assert.equal(Cuttlefish.wantsThankYou("sepia"), true);
  assert.equal(Nautilus.wantsThankYou("chamber"), true);
  assert.equal(Rui.sleepHoldFrame("red_panda", 4), 1);
  assert.equal(T.sleepHoldFrame("pitcher", 4), null);
  globalThis.PetRuiTricks = OverlayRui;
  globalThis.PetRelayTricks = OverlayRelay;
  globalThis.PetFuseTricks = OverlayFuse;
  globalThis.PetEarthTricks = OverlayEarth;
  globalThis.PetCatTricks = OverlayCat;
  globalThis.PetDogTricks = OverlayDog;
  globalThis.PetRabbitTricks = OverlayRabbit;
  globalThis.PetHamsterTricks = OverlayHamster;
  globalThis.PetGuineaPigTricks = OverlayGuineaPig;
  globalThis.PetTurtleTricks = OverlayTurtle;
  globalThis.PetGoldfishTricks = OverlayGoldfish;
  globalThis.PetBudgieTricks = OverlayBudgie;
  globalThis.PetFoxTricks = OverlayFox;
  globalThis.PetPenguinTricks = OverlayPenguin;
  globalThis.PetParrotTricks = OverlayParrot;
  globalThis.PetFerretTricks = OverlayFerret;
  globalThis.PetHedgehogTricks = OverlayHedgehog;
  globalThis.PetChinchillaTricks = OverlayChinchilla;
  globalThis.PetAxolotlTricks = OverlayAxolotl;
  globalThis.PetToucanTricks = OverlayToucan;
  globalThis.PetIguanaTricks = OverlayIguana;
  globalThis.PetDragonTricks = OverlayDragon;
  globalThis.PetPhoenixTricks = OverlayPhoenix;
  globalThis.PetBallPythonTricks = OverlayBallPython;
  globalThis.PetCornSnakeTricks = OverlayCornSnake;
  globalThis.PetKingsnakeTricks = OverlayKingsnake;
  globalThis.PetGreenTreePythonTricks = OverlayGreenTreePython;
  globalThis.PetHognoseTricks = OverlayHognose;
  globalThis.PetGarterTricks = OverlayGarter;
  globalThis.PetBoaTricks = OverlayBoa;
  globalThis.PetMilkSnakeTricks = OverlayMilkSnake;
  globalThis.PetRosyBoaTricks = OverlayRosyBoa;
  globalThis.PetCarpetPythonTricks = OverlayCarpetPython;
  globalThis.PetOctopusTricks = OverlayOctopus;
  globalThis.PetCuttlefishTricks = OverlayCuttlefish;
  globalThis.PetNautilusTricks = OverlayNautilus;
  globalThis.PetMoonJellyTricks = OverlayMoonJelly;
  globalThis.PetSeaStarTricks = OverlaySeaStar;
  globalThis.PetHermitCrabTricks = OverlayHermitCrab;
  globalThis.PetHorseshoeCrabTricks = OverlayHorseshoeCrab;
  globalThis.PetSeahorseTricks = OverlaySeahorse;
  globalThis.PetMantaTricks = OverlayManta;
  globalThis.PetMorayTricks = OverlayMoray;
  globalThis.PetMossTricks = OverlayMoss;
  globalThis.PetMaidenhairTricks = OverlayMaidenhair;
  globalThis.PetGinkgoTricks = OverlayGinkgo;
globalThis.PetOakTricks = OverlayOak;
globalThis.PetWaterLilyTricks = OverlayWaterLily;
globalThis.PetOrchidTricks = OverlayOrchid;
globalThis.PetSaguaroTricks = OverlaySaguaro;
globalThis.PetVenusFlytrapTricks = OverlayVenusFlytrap;
globalThis.PetPitcherTricks = Overlay;
globalThis.PetSundewTricks = OverlaySundew;
globalThis.PetHoneybeeTricks = OverlayHoneybee;
globalThis.PetMonarchTricks = OverlayMonarch;
globalThis.PetLunaTricks = OverlayLuna;
  assert.equal(OverlayGround.tricksFor("red_panda"), OverlayRui);
  assert.equal(OverlayGround.tricksFor("rui"), OverlayRui);
  assert.equal(OverlayGround.tricksFor("turtle"), OverlayTurtle);
  assert.equal(OverlayGround.tricksFor("ink"), OverlayTurtle);
  assert.equal(OverlayGround.tricksFor("goldfish"), OverlayGoldfish);
  assert.equal(OverlayGround.tricksFor("coin"), OverlayGoldfish);
  assert.equal(OverlayGround.tricksFor("axolotl"), OverlayAxolotl);
  assert.equal(OverlayGround.tricksFor("bloom"), OverlayAxolotl);
  assert.equal(OverlayGround.tricksFor("octopus"), OverlayOctopus);
  assert.equal(OverlayGround.tricksFor("cup"), OverlayOctopus);
  assert.equal(OverlayGround.tricksFor("cuttlefish"), OverlayCuttlefish);
  assert.equal(OverlayGround.tricksFor("sepia"), OverlayCuttlefish);
  assert.equal(OverlayGround.tricksFor("nautilus"), OverlayNautilus);
  assert.equal(OverlayGround.tricksFor("chamber"), OverlayNautilus);
  assert.equal(OverlayGround.tricksFor("carpet_python"), OverlayCarpetPython);
  assert.equal(OverlayGround.tricksFor("atlas"), OverlayCarpetPython);
  assert.equal(OverlayGround.tricksFor("moon_jelly"), OverlayMoonJelly);
  assert.equal(OverlayGround.tricksFor("pulse"), OverlayMoonJelly);
  assert.equal(OverlayGround.tricksFor("sea_star"), OverlaySeaStar);
  assert.equal(OverlayGround.tricksFor("cling"), OverlaySeaStar);
  assert.equal(OverlayGround.tricksFor("hermit_crab"), OverlayHermitCrab);
  assert.equal(OverlayGround.tricksFor("tenant"), OverlayHermitCrab);
  assert.equal(OverlayGround.tricksFor("horseshoe_crab"), OverlayHorseshoeCrab);
  assert.equal(OverlayGround.tricksFor("ledger"), OverlayHorseshoeCrab);
  assert.equal(OverlayGround.tricksFor("seahorse"), OverlaySeahorse);
  assert.equal(OverlayGround.tricksFor("anchor"), OverlaySeahorse);
  assert.equal(OverlayGround.wantsThankYou("turtle"), true);
  assert.equal(OverlayGround.wantsThankYou("ink"), true);
  assert.equal(OverlayGround.wantsThankYou("goldfish"), true);
  assert.equal(OverlayGround.wantsThankYou("coin"), true);
  assert.equal(OverlayGround.wantsThankYou("axolotl"), true);
  assert.equal(OverlayGround.wantsThankYou("bloom"), true);
  assert.equal(OverlayGround.wantsThankYou("octopus"), true);
  assert.equal(OverlayGround.wantsThankYou("cup"), true);
  assert.equal(OverlayGround.wantsThankYou("cuttlefish"), true);
  assert.equal(OverlayGround.wantsThankYou("sepia"), true);
  assert.equal(OverlayGround.wantsThankYou("nautilus"), true);
  assert.equal(OverlayGround.wantsThankYou("chamber"), true);
  assert.equal(OverlayGround.wantsThankYou("carpet_python"), true);
  assert.equal(OverlayGround.wantsThankYou("atlas"), true);
  assert.equal(OverlayGround.wantsThankYou("moon_jelly"), true);
  assert.equal(OverlayGround.wantsThankYou("pulse"), true);
  assert.equal(OverlayGround.wantsThankYou("sea_star"), true);
  assert.equal(OverlayGround.wantsThankYou("cling"), true);
  assert.equal(OverlayGround.wantsThankYou("hermit_crab"), true);
  assert.equal(OverlayGround.wantsThankYou("tenant"), true);
  assert.equal(OverlayGround.wantsThankYou("horseshoe_crab"), true);
  assert.equal(OverlayGround.wantsThankYou("ledger"), true);
  assert.equal(OverlayGround.wantsThankYou("moss"), true);
  assert.equal(OverlayGround.wantsThankYou("felt"), true);
  assert.equal(OverlayGround.wantsThankYou("maidenhair"), true);
  assert.equal(OverlayGround.wantsThankYou("vein"), true);
  assert.equal(OverlayGround.wantsThankYou("ginkgo"), true);
  assert.equal(OverlayGround.wantsThankYou("fan"), true);
  assert.equal(OverlayGround.tricksFor("oak"), OverlayOak);
  assert.equal(OverlayGround.wantsThankYou("oak"), true);
  assert.equal(OverlayGround.tricksFor("mast"), OverlayOak);
  assert.equal(OverlayGround.wantsThankYou("mast"), true);
  assert.equal(OverlayGround.tricksFor("orchid"), OverlayOrchid);
  assert.equal(OverlayGround.wantsThankYou("orchid"), true);
  assert.equal(OverlayGround.tricksFor("moth"), OverlayOrchid);
  assert.equal(OverlayGround.wantsThankYou("moth"), true);
  assert.equal(OverlayGround.tricksFor("venus_flytrap"), OverlayVenusFlytrap);
  assert.equal(OverlayGround.tricksFor("snap"), OverlayVenusFlytrap);
  assert.equal(OverlayGround.tricksFor("pitcher"), Overlay);
  assert.equal(OverlayGround.wantsThankYou("pitcher"), true);
  assert.equal(OverlayGround.tricksFor("snap"), OverlayVenusFlytrap);
  assert.equal(OverlayGround.wantsThankYou("snap"), true); // Snap still gated via VenusFlytrap
  assert.equal(OverlayGround.tricksFor("saguaro"), OverlaySaguaro);
  assert.equal(OverlayGround.wantsThankYou("saguaro"), true);
  assert.equal(OverlayGround.tricksFor("arm"), OverlaySaguaro);
  assert.equal(OverlayGround.wantsThankYou("arm"), true);
  assert.deepEqual([...OverlaySaguaro.TRICKS], ["rib", "branch", "nocturne", "areole", "sentinel", "pleat", "boot"]);
  assert.equal(OverlayGround.tricksFor("water_lily"), OverlayWaterLily);
  assert.equal(OverlayGround.wantsThankYou("water_lily"), true);
  assert.equal(OverlayGround.tricksFor("disk"), OverlayWaterLily);
  assert.equal(OverlayGround.wantsThankYou("disk"), true);
  assert.deepEqual([...OverlayWaterLily.TRICKS], ["pad", "corolla", "rhizome", "calyx", "sheen", "peltate", "hydropote"]);
  assert.equal(OverlayGround.wantsThankYou("hamster"), true);
  assert.equal(OverlayGround.wantsThankYou("clip"), true);
  assert.equal(OverlayGround.wantsThankYou("hedgehog"), true);
  assert.equal(OverlayGround.wantsThankYou("burr"), true);
  assert.equal(OverlayGround.sleepHoldFrame("red_panda", 4), 1);
  assert.equal(OverlayGround.sleepHoldFrame("moon_jelly", 4), null);
  assert.deepEqual([...OverlayTurtle.TRICKS], ["soak", "tuck", "crane", "plod", "paddle", "snorkel", "wipe"]);
  assert.deepEqual([...OverlayGoldfish.TRICKS], ["drift", "gulp", "flare", "glint", "dart", "yawn", "forage"]);
  assert.deepEqual([...OverlayAxolotl.TRICKS], ["gill", "amble", "mend", "smile", "plume", "sprout", "glop"]);
  assert.deepEqual([...OverlayOctopus.TRICKS], ["mantle", "sucker", "jet", "veil", "tinker", "papilla", "ooze"]);
  assert.deepEqual([...OverlayCuttlefish.TRICKS], ["bone", "pupil", "chroma", "hover", "blot", "strike", "zebra"]);
  assert.deepEqual([...OverlayNautilus.TRICKS], ["spiral", "siphuncle", "nacre", "pinhole", "fringe", "hyponome", "aperture"]);
  assert.deepEqual([...OverlaySeaStar.TRICKS], ["podia", "righting", "crawl", "evert", "penta", "madre", "papula"]);
  assert.deepEqual([...OverlayHermitCrab.TRICKS], ["swap", "antenna", "scuttle", "withdraw", "vacancy", "chela", "bailer"]);
  assert.deepEqual([...OverlayHorseshoeCrab.TRICKS], ["carapace", "bookgill", "telson", "furrow", "fossil", "pusher", "ocular"]);
  assert.deepEqual([...OverlayCarpetPython.TRICKS], ["legend", "rung", "contour", "runner", "bearing", "canopy", "inset"]);
  assert.deepEqual([...OverlayMoss.TRICKS], ["tuft", "bead", "spore", "cushion", "thatch", "rhizoid", "seta"]);
  assert.deepEqual([...OverlayMaidenhair.TRICKS], ["frond", "rachis", "fiddle", "pinna", "saucer", "sori", "stipe"]);
  assert.equal(OverlayGround.tricksFor("maidenhair"), OverlayMaidenhair);
  assert.equal(OverlayGround.tricksFor("vein"), OverlayMaidenhair);
  assert.equal(OverlayGround.tricksFor("ginkgo"), OverlayGinkgo);
  assert.equal(OverlayGround.tricksFor("fan"), OverlayGinkgo);
  assert.deepEqual([...Overlay.TRICKS], ["peristome", "cistern", "brine", "operculum", "urn", "ala", "baffle"]);
  assert.equal(Overlay.TRICKS.includes("barrel"), false);
  assert.equal(Overlay.TRICKS.includes("soar"), false);
  assert.equal(Overlay.TRICKS.includes("plow"), false);
  assert.equal(Overlay.TRICKS.includes("plow"), false);
  assert.equal(Overlay.TRICKS.includes("bell"), false);
  assert.equal(Overlay.TRICKS.includes("drift"), false);
  assert.equal(Overlay.TRICKS.includes("jet"), false);
  assert.equal(Overlay.TRICKS.includes("mantle"), false);
  assert.equal(Overlay.TRICKS.includes("bone"), false);
  assert.equal(Overlay.TRICKS.includes("spiral"), false);
  assert.equal(Overlay.TRICKS.includes("tuck"), false);
  assert.equal(Overlay.TRICKS.includes("gill"), false);
  assert.equal(Overlay.TRICKS.includes("legend"), false);
  assert.equal(Overlay.TRICKS.includes("podia"), false);
  assert.equal(Overlay.TRICKS.includes("scurry"), false);
  assert.equal(Overlay.TRICKS.includes("curl"), false);
  assert.equal(Overlay.TRICKS.includes("barrel"), false);
  assert.equal(Overlay.TRICKS.includes("trade"), false);
  assert.deepEqual([...OverlayHamster.TRICKS], ["nest", "cheek", "scurry", "pocket", "reel", "scrub", "seed"]);
  assert.deepEqual([...OverlayHedgehog.TRICKS], ["curl", "snuffle", "anoint", "bristle", "root", "trundle", "wheel"]);
  assert.deepEqual([...OverlaySeaStar.TRICKS], ["podia", "righting", "crawl", "evert", "penta", "madre", "papula"]);

  assert.deepEqual([...Manta.TRICKS], ["wing", "lobe", "gyre", "vault", "span", "breach", "ram"]);
  assert.deepEqual([...OverlayManta.TRICKS], ["wing", "lobe", "gyre", "vault", "span", "breach", "ram"]);
  assert.equal(Manta.wantsThankYou("kite"), true);
  assert.equal(OverlayGround.tricksFor("manta"), OverlayManta);
  assert.equal(OverlayGround.tricksFor("kite"), OverlayManta);
  assert.deepEqual([...Moray.TRICKS], ["hinge", "pharynx", "knot", "lurk", "jamb", "mucus", "sentry"]);
  assert.deepEqual([...OverlayMoray.TRICKS], ["hinge", "pharynx", "knot", "lurk", "jamb", "mucus", "sentry"]);
  assert.equal(Moray.wantsThankYou("door"), true);
  assert.equal(OverlayGround.tricksFor("moray"), OverlayMoray);
  assert.equal(OverlayGround.tricksFor("door"), OverlayMoray);
  assert.equal(Garter.TRICKS.includes("moss"), true);
  assert.equal(T.TRICKS.includes("moss"), false);
  assert.equal(T.TRICKS.includes("tuft"), false);
  assert.equal(T.TRICKS.includes("bead"), false);
  assert.equal(T.TRICKS.includes("spore"), false);
  assert.equal(T.TRICKS.includes("cushion"), false);
  assert.equal(T.TRICKS.includes("thatch"), false);
  assert.equal(T.TRICKS.includes("unfurl"), false);
  assert.equal(T.TRICKS.includes("hinge"), false);
  assert.equal(T.TRICKS.includes("swell"), false);
  assert.equal(T.TRICKS.includes("lift"), false);
  assert.equal(T.TRICKS.includes("creep"), false);
  assert.equal(T.TRICKS.includes("lean"), false);
  assert.equal(T.TRICKS.includes("fan"), false);
  assert.equal(T.TRICKS.includes("nod"), false);
  assert.equal(T.HAPPY.includes("swell"), false);
  assert.equal(T.HAPPY.includes("humid"), false);
  assert.equal(T.HAPPY.includes("velvet"), false);
  assert.equal(T.HAPPY.includes("meadow"), false);
  assert.equal(OverlayGround.tricksFor("ginkgo"), OverlayGinkgo);
  assert.equal(OverlayGround.tricksFor("fan"), OverlayGinkgo);
});

test("notes: Well ultra-polish done; Dew + Comb + Milk + Ghost ultra also done; Spark ultra also done; Dart ultra also done; next house-order ultra is Lattice / morel", () => {
  assert.equal(T.TRICK_KEY, "pitcher");
  assert.equal(T.wantsThankYou("drown"), true);
  assert.equal(OverlayGround.tricksFor("manta"), OverlayManta);
  assert.equal(OverlayGround.tricksFor("kite"), OverlayManta);
  assert.equal(OverlayGround.wantsThankYou("manta"), true);
  assert.equal(OverlayGround.wantsThankYou("kite"), true);
  assert.equal(OverlayGround.tricksFor("moray"), OverlayMoray);
  assert.equal(OverlayGround.tricksFor("door"), OverlayMoray);
  assert.equal(OverlayGround.wantsThankYou("moray"), true);
  assert.equal(OverlayGround.wantsThankYou("door"), true);
  assert.equal(OverlayGround.tricksFor("seahorse"), OverlaySeahorse);
  assert.equal(OverlayGround.tricksFor("anchor"), OverlaySeahorse);
  assert.equal(OverlayGround.tricksFor("hermit_crab"), OverlayHermitCrab);
  assert.equal(OverlayGround.tricksFor("tenant"), OverlayHermitCrab);
  assert.equal(OverlayGround.tricksFor("sea_star"), OverlaySeaStar);
  assert.equal(OverlayGround.tricksFor("cling"), OverlaySeaStar);
  assert.equal(OverlayGround.tricksFor("moon_jelly"), OverlayMoonJelly);
  assert.equal(OverlayGround.tricksFor("pulse"), OverlayMoonJelly);
  assert.equal(OverlayGround.tricksFor("nautilus"), OverlayNautilus);
  assert.equal(OverlayGround.tricksFor("chamber"), OverlayNautilus);
  assert.equal(OverlayGround.tricksFor("cuttlefish"), OverlayCuttlefish);
  assert.equal(OverlayGround.tricksFor("sepia"), OverlayCuttlefish);
  assert.equal(OverlayGround.tricksFor("octopus"), OverlayOctopus);
  assert.equal(OverlayGround.tricksFor("cup"), OverlayOctopus);
  assert.equal(OverlayGround.tricksFor("carpet_python"), OverlayCarpetPython);
  assert.equal(OverlayGround.tricksFor("atlas"), OverlayCarpetPython);
  assert.equal(OverlayGround.tricksFor("turtle"), OverlayTurtle);
  assert.equal(OverlayGround.tricksFor("ink"), OverlayTurtle);
  assert.equal(OverlayGround.tricksFor("goldfish"), OverlayGoldfish);
  assert.equal(OverlayGround.tricksFor("coin"), OverlayGoldfish);
  assert.equal(OverlayGround.tricksFor("axolotl"), OverlayAxolotl);
  assert.equal(OverlayGround.tricksFor("bloom"), OverlayAxolotl);
  assert.equal(OverlayGround.tricksFor("hamster"), OverlayHamster);
  assert.equal(OverlayGround.tricksFor("clip"), OverlayHamster);
  assert.equal(OverlayGround.tricksFor("hedgehog"), OverlayHedgehog);
  assert.equal(OverlayGround.tricksFor("burr"), OverlayHedgehog);
  assert.equal(OverlayGround.tricksFor("horseshoe_crab"), OverlayHorseshoeCrab);
  assert.equal(OverlayGround.tricksFor("ledger"), OverlayHorseshoeCrab);
  assert.equal(OverlayGround.wantsThankYou("horseshoe_crab"), true);
  assert.equal(OverlayGround.wantsThankYou("ledger"), true);
  assert.equal(OverlayGround.tricksFor("moss"), OverlayMoss);
  assert.equal(OverlayGround.wantsThankYou("moss"), true);
  assert.equal(OverlayGround.tricksFor("felt"), OverlayMoss);
  assert.equal(OverlayGround.wantsThankYou("felt"), true);
  assert.equal(OverlayGround.tricksFor("maidenhair"), OverlayMaidenhair);
  assert.equal(OverlayGround.wantsThankYou("maidenhair"), true);
  assert.equal(OverlayGround.tricksFor("vein"), OverlayMaidenhair);
  assert.equal(OverlayGround.wantsThankYou("vein"), true);
  assert.equal(OverlayGround.tricksFor("ginkgo"), OverlayGinkgo);
  assert.equal(OverlayGround.wantsThankYou("ginkgo"), true);
  assert.equal(OverlayGround.tricksFor("fan"), OverlayGinkgo);
  assert.equal(OverlayGround.wantsThankYou("fan"), true);
  assert.deepEqual([...Moray.TRICKS], ["hinge", "pharynx", "knot", "lurk", "jamb", "mucus", "sentry"]);
  assert.deepEqual([...Manta.TRICKS], ["wing", "lobe", "gyre", "vault", "span", "breach", "ram"]);
  assert.deepEqual([...Moss.TRICKS], ["tuft", "bead", "spore", "cushion", "thatch", "rhizoid", "seta"]);
  assert.deepEqual([...Maidenhair.TRICKS], ["frond", "rachis", "fiddle", "pinna", "saucer", "sori", "stipe"]);
  assert.equal(T.TRICKS.includes("moss"), false);
  assert.equal(T.TRICKS.includes("tuft"), false);
  assert.equal(T.TRICKS.includes("frond"), false);
  assert.equal(T.TRICKS.includes("rachis"), false);
  assert.equal(T.TRICKS.includes("fiddle"), false);
  assert.equal(T.TRICKS.includes("pinna"), false);
  assert.equal(T.TRICKS.includes("saucer"), false);
  assert.equal(T.TRICKS.includes("hinge"), false);
  assert.equal(T.TRICKS.includes("unfurl"), false);
  assert.equal(T.TRICKS.includes("gold"), false);
  assert.equal(T.TRICKS.includes("fan"), false);
  assert.equal(T.TRICKS.includes("fossil"), false);
  assert.equal(T.TRICKS.includes("lobe"), false);
  assert.equal(T.HAPPY.includes("mist"), false);
  assert.equal(T.HAPPY.includes("humid"), false);
  assert.equal(OverlayGround.tricksFor("oak"), OverlayOak);
  assert.equal(OverlayGround.wantsThankYou("oak"), true);
  assert.equal(OverlayGround.tricksFor("mast"), OverlayOak);
  assert.equal(OverlayGround.wantsThankYou("mast"), true);
  assert.equal(OverlayGround.tricksFor("water_lily"), OverlayWaterLily);
  assert.equal(OverlayGround.wantsThankYou("water_lily"), true);
  assert.equal(OverlayGround.tricksFor("disk"), OverlayWaterLily);
  assert.equal(OverlayGround.wantsThankYou("disk"), true);
  assert.deepEqual([...WaterLily.TRICKS], ["pad", "corolla", "rhizome", "calyx", "sheen", "peltate", "hydropote"]);
  assert.deepEqual([...OverlayWaterLily.TRICKS], ["pad", "corolla", "rhizome", "calyx", "sheen", "peltate", "hydropote"]);
  assert.equal(OverlayGround.tricksFor("orchid"), OverlayOrchid);
  assert.equal(OverlayGround.wantsThankYou("orchid"), true);
  assert.equal(OverlayGround.tricksFor("moth"), OverlayOrchid);
  assert.equal(OverlayGround.wantsThankYou("moth"), true);
  assert.equal(OverlayGround.tricksFor("pitcher"), Overlay);
  assert.equal(OverlayGround.wantsThankYou("pitcher"), true);
  assert.equal(OverlayGround.tricksFor("snap"), OverlayVenusFlytrap);
  assert.equal(OverlayGround.wantsThankYou("snap"), true); // Snap still gated via VenusFlytrap
  assert.deepEqual([...Oak.TRICKS], ["acorn", "sinus", "gall", "taproot", "bole", "catkin", "tyloses"]);
  assert.deepEqual([...OverlayOak.TRICKS], ["acorn", "sinus", "gall", "taproot", "bole", "catkin", "tyloses"]);
  assert.deepEqual([...T.TRICKS], ["peristome", "cistern", "brine", "operculum", "urn", "ala", "baffle"]);
  assert.deepEqual([...Overlay.TRICKS], ["peristome", "cistern", "brine", "operculum", "urn", "ala", "baffle"]);
  assert.deepEqual([...T.HAPPY], ["midge", "rain", "maroon"]);
  assert.equal(T.TRICKS.includes("pad"), false);
  assert.equal(T.TRICKS.includes("mount"), false);
  assert.equal(T.TRICKS.includes("labellum"), false);
  assert.equal(T.TRICKS.includes("velamen"), false);
  assert.equal(T.TRICKS.includes("column"), false);
  assert.equal(T.TRICKS.includes("spike"), false);
  assert.equal(T.TRICKS.includes("bark"), false);
  assert.equal(T.TRICKS.includes("store"), false);
  assert.equal(T.TRICKS.includes("mesa"), false);
  assert.equal(T.TRICKS.includes("arroyo"), false);
  assert.equal(T.HAPPY.includes("pearl"), false);
  assert.equal(T.HAPPY.includes("pollen"), false);
  assert.equal(T.HAPPY.includes("perfume"), false);
  assert.equal(T.HAPPY.includes("swell"), false);
  assert.equal(T.TRICKS.includes("unfurl"), false);
  assert.equal(T.TRICKS.includes("bloom"), false);
  assert.equal(OverlayGround.tricksFor("pitcher"), Overlay);
  assert.equal(OverlayGround.wantsThankYou("pitcher"), true);
  assert.equal(OverlayGround.tricksFor("snap"), OverlayVenusFlytrap);
  assert.equal(OverlayGround.wantsThankYou("snap"), true); // Snap still gated via VenusFlytrap
  assert.deepEqual([...Orchid.TRICKS], ["labellum", "velamen", "column", "spike", "epiphyte", "keiki", "pollinia"]);
  assert.deepEqual([...OverlayOrchid.TRICKS], ["labellum", "velamen", "column", "spike", "epiphyte", "keiki", "pollinia"]);
  assert.deepEqual([...Saguaro.TRICKS], ["rib", "branch", "nocturne", "areole", "sentinel", "pleat", "boot"]);
  assert.deepEqual([...OverlaySaguaro.TRICKS], ["rib", "branch", "nocturne", "areole", "sentinel", "pleat", "boot"]);
  assert.equal(OverlayGround.tricksFor("saguaro"), OverlaySaguaro);
  assert.equal(OverlayGround.wantsThankYou("saguaro"), true);
  assert.equal(OverlayGround.tricksFor("arm"), OverlaySaguaro);
  assert.equal(OverlayGround.wantsThankYou("arm"), true);
  assert.equal(OverlayGround.tricksFor("pitcher"), Overlay);
  assert.equal(OverlayGround.wantsThankYou("pitcher"), true);
  assert.equal(OverlayGround.tricksFor("drown"), Overlay);
  assert.equal(OverlayGround.wantsThankYou("drown"), true);
  assert.equal(OverlayGround.tricksFor("sundew"), OverlaySundew);
  assert.equal(OverlayGround.wantsThankYou("sundew"), true);
  assert.equal(OverlayGround.tricksFor("dew"), OverlaySundew);
  assert.equal(OverlayGround.wantsThankYou("dew"), true);
  assert.deepEqual([...Sundew.TRICKS], ["mucilage", "tentacle", "digest", "gland", "rosette", "lamina", "circinate"]);
  assert.deepEqual([...OverlaySundew.TRICKS], ["mucilage", "tentacle", "digest", "gland", "rosette", "lamina", "circinate"]);
  assert.equal(OverlayGround.tricksFor("honeybee"), OverlayHoneybee);
  assert.equal(OverlayGround.wantsThankYou("honeybee"), true);
  assert.equal(OverlayGround.tricksFor("comb"), OverlayHoneybee);
  assert.equal(OverlayGround.wantsThankYou("comb"), true);
  assert.deepEqual([...Honeybee.TRICKS], ["figure", "corbicula", "hex", "proboscis", "hive", "ocelli", "nasonov"]);
  assert.deepEqual([...OverlayHoneybee.TRICKS], ["figure", "corbicula", "hex", "proboscis", "hive", "ocelli", "nasonov"]);
  assert.equal(OverlayGround.tricksFor("monarch"), OverlayMonarch);
  assert.equal(OverlayGround.wantsThankYou("monarch"), true);
  assert.equal(OverlayGround.tricksFor("milk"), OverlayMonarch);
  assert.equal(OverlayGround.wantsThankYou("milk"), true);
  assert.deepEqual([...Monarch.TRICKS], ["asclepias", "oyamel", "warning", "chrysalis", "danaus", "cremaster", "tarsus"]);
  assert.deepEqual([...OverlayMonarch.TRICKS], ["asclepias", "oyamel", "warning", "chrysalis", "danaus", "cremaster", "tarsus"]);
  assert.equal(OverlayGround.tricksFor("luna"), OverlayLuna);
  assert.equal(OverlayGround.wantsThankYou("luna"), true);
  assert.equal(OverlayGround.tricksFor("ghost"), OverlayLuna);
  assert.equal(OverlayGround.wantsThankYou("ghost"), true);
  assert.deepEqual([...Luna.TRICKS], ["plumose", "lunule", "silk", "stream", "actias", "aphagy", "cauda"]);
  assert.deepEqual([...OverlayLuna.TRICKS], ["plumose", "lunule", "silk", "stream", "actias", "aphagy", "cauda"]);
  assert.ok(OverlayGround.tricksFor("firefly") == null);
  assert.equal(OverlayGround.wantsThankYou("firefly"), false);
  assert.ok(OverlayGround.tricksFor("spark") == null);
  assert.equal(OverlayGround.wantsThankYou("spark"), false);
  
  assert.equal(T.TRICKS.includes("clamp"), false);
  assert.equal(T.TRICKS.includes("trichome"), false);
  assert.equal(T.TRICKS.includes("stew"), false);
  assert.equal(T.TRICKS.includes("unseal"), false);
  assert.equal(T.TRICKS.includes("poise"), false);
  assert.equal(T.TRICKS.includes("cage"), false);
  assert.equal(T.TRICKS.includes("scape"), false);
  assert.equal(T.TRICKS.includes("ala"), true);
  assert.equal(T.TRICKS.includes("baffle"), true);
  assert.equal(T.HAPPY.includes("gnat"), false);
  assert.equal(T.HAPPY.includes("peat"), false);
  assert.equal(T.HAPPY.includes("crimson"), false);
  assert.deepEqual([...VenusFlytrap.TRICKS], ["clamp", "trichome", "stew", "unseal", "poise", "cage", "scape"]);
  assert.deepEqual([...OverlayVenusFlytrap.TRICKS], ["clamp", "trichome", "stew", "unseal", "poise", "cage", "scape"]);

  assert.equal(T.TRICKS.includes("rib"), false);
  assert.equal(T.TRICKS.includes("branch"), false);
  assert.equal(T.TRICKS.includes("nocturne"), false);
  assert.equal(T.TRICKS.includes("areole"), false);
  assert.equal(T.TRICKS.includes("sentinel"), false);
  assert.equal(T.TRICKS.includes("count"), false);
  assert.equal(T.TRICKS.includes("snap"), false);
  assert.equal(T.TRICKS.includes("lobe"), false);
  assert.equal(T.TRICKS.includes("open"), false);
  assert.equal(T.HAPPY.includes("monsoon"), false);
  assert.equal(T.HAPPY.includes("snap"), false);
});
