import assert from "node:assert/strict";
import { createRequire } from "node:module";
import { dirname, join } from "node:path";
import { test } from "node:test";
import { fileURLToPath, pathToFileURL } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const T = await import(pathToFileURL(join(root, "src/lib/pets/rabbit-tricks.ts")).href);
const Rui = await import(pathToFileURL(join(root, "src/lib/pets/rui-tricks.ts")).href);
const Relay = await import(pathToFileURL(join(root, "src/lib/pets/relay-tricks.ts")).href);
const Fuse = await import(pathToFileURL(join(root, "src/lib/pets/fuse-tricks.ts")).href);
const Earth = await import(pathToFileURL(join(root, "src/lib/pets/earth-tricks.ts")).href);
const Cat = await import(pathToFileURL(join(root, "src/lib/pets/cat-tricks.ts")).href);
const Dog = await import(pathToFileURL(join(root, "src/lib/pets/dog-tricks.ts")).href);
const Overlay = createRequire(import.meta.url)(join(root, "../desktop/renderer/rabbit-tricks.js"));
const OverlayGround = createRequire(import.meta.url)(join(root, "../desktop/renderer/ground-tricks.js"));
const OverlayRui = createRequire(import.meta.url)(join(root, "../desktop/renderer/rui-tricks.js"));
const OverlayRelay = createRequire(import.meta.url)(join(root, "../desktop/renderer/relay-tricks.js"));
const OverlayFuse = createRequire(import.meta.url)(join(root, "../desktop/renderer/fuse-tricks.js"));
const OverlayEarth = createRequire(import.meta.url)(join(root, "../desktop/renderer/earth-tricks.js"));
const OverlayCat = createRequire(import.meta.url)(join(root, "../desktop/renderer/cat-tricks.js"));
const OverlayDog = createRequire(import.meta.url)(join(root, "../desktop/renderer/dog-tricks.js"));
const OverlayHamster = createRequire(import.meta.url)(join(root, "../desktop/renderer/hamster-tricks.js"));
const OverlayGuineaPig = createRequire(import.meta.url)(join(root, "../desktop/renderer/guinea-pig-tricks.js"));

test("Thimble tricks start only on idle ground", () => {
  assert.deepEqual([...T.TRICKS], ["flop", "groom", "periscope", "dig", "binky", "rub", "nosh"]);
  assert.equal(T.canStart({ asleep: false, hidden: false, leaving: false, cmd: "idle" }), true);
  assert.equal(T.canStart({ asleep: true, hidden: false, leaving: false, cmd: "idle" }), false);
  assert.equal(T.canStart({ asleep: false, hidden: true, leaving: false, cmd: "idle" }), false);
  assert.equal(T.canStart({ asleep: false, hidden: false, leaving: false, cmd: "sleep" }), false);
  assert.equal(T.canStart({ asleep: false, hidden: false, leaving: false, cmd: "seek" }), false);
  assert.equal(T.canStart({ asleep: false, hidden: false, leaving: false, cmd: "idle", windowPlay: true }), false);
  assert.equal(T.canStart({ asleep: false, hidden: false, leaving: false, cmd: "idle", card: true }), false);
  assert.equal(T.shouldAbort({ asleep: true, hidden: false, leaving: false, cmd: "idle" }), true);
  assert.equal(T.shouldAbort({ asleep: false, hidden: false, leaving: false, cmd: "idle", card: true }), true);
  assert.equal(T.shouldAbort({ asleep: false, hidden: false, leaving: false, cmd: "idle" }), false);
  assert.equal(T.pickTrick(0.99, true), "flop");
  assert.notEqual(T.pickTrick(0.3, false, "flop"), "flop");
  assert.equal(Overlay.TRICK_KEY, "rabbit");
  assert.equal(T.sleepHoldFrame("rabbit", 4), null);
  assert.equal(T.TRICKS.includes("somersault"), false);
  assert.equal(T.TRICKS.includes("scratch"), false);
  assert.equal(T.TRICKS.includes("loaf"), false);
  assert.equal(T.TRICKS.includes("wait"), false);
  assert.equal(T.TRICKS.includes("bow"), false);
  assert.equal(T.TRICKS.includes("zoom"), false);
  assert.equal(T.TRICKS.includes("thump"), false);
  assert.equal(T.TRICKS.includes("chin"), false);
});

test("flop/groom/periscope/dig/binky/rub/nosh are house-rabbit-true, not Rui cat dog or dragon clones", () => {
  const ground = { asleep: false, hidden: false, leaving: false, cmd: "idle" };
  const flop = T.beginTrick("flop", 80, 1);
  assert.equal(flop.anim, "sit");
  assert.equal(flop.phase, "hold");
  const held = T.stepTrick(flop, 5, ground);
  assert.equal(held.phase, "hold");
  assert.equal(held.anim, "sit");
  assert.ok(Math.abs(held.rot) > 6);
  assert.ok(held.lift < 0);
  const release = T.stepTrick(flop, T.FLOP_HOLD + 0.2, ground);
  assert.equal(release.phase, "release");
  assert.equal(release.anim, "sit");
  const doneFlop = T.stepTrick(flop, T.DUR.flop + 0.1, ground);
  assert.equal(doneFlop.phase, "done");
  assert.ok(T.nextTrickWait(true, 0, "flop") > T.nextTrickWait(true, 0, "groom"));
  const groom = T.beginTrick("groom", 80, 1);
  assert.equal(groom.anim, "sit");
  const groomMid = T.stepTrick(groom, 0.25, ground);
  assert.ok(Math.abs(groomMid.rot) > 0.5 || groomMid.lift !== 0);
  const peri = T.beginTrick("periscope", 80, 1);
  assert.equal(peri.anim, "sit");
  const periMid = T.stepTrick(peri, 0.5, ground);
  assert.ok(periMid.lift > 2 || periMid.rot > 0);
  const dig = T.beginTrick("dig", 80, 1);
  assert.equal(dig.anim, "sit");
  const digMid = T.stepTrick(dig, 0.3, ground);
  assert.ok(Math.abs(digMid.rot) > 0.5 || digMid.lift < 0);
  const binky = T.beginTrick("binky", 80, 1);
  assert.equal(binky.anim, "play");
  const binkyMid = T.stepTrick(binky, T.DUR.binky * 0.45, ground);
  assert.ok(binkyMid.lift > 1 || Math.abs(binkyMid.x - 80) > 2 || Math.abs(binkyMid.rot) > 2);
  const binkyDone = T.stepTrick(binky, T.DUR.binky + 0.1, ground);
  assert.equal(binkyDone.phase, "done");
  const rub = T.beginTrick("rub", 80, 1);
  assert.equal(rub.anim, "sit");
  const rubMid = T.stepTrick(rub, T.DUR.rub * 0.4, ground);
  assert.ok(rubMid.lift < -1 || Math.abs(rubMid.rot) > 6);
  const nosh = T.beginTrick("nosh", 80, 1);
  assert.equal(nosh.anim, "sit");
  const noshMid = T.stepTrick(nosh, T.DUR.nosh * 0.4, ground);
  assert.ok(noshMid.lift < 0 || Math.abs(noshMid.rot) > 4);
  assert.equal(Overlay.TRICKS.includes("rub"), true);
  assert.equal(Overlay.TRICKS.includes("nosh"), true);
  const aborted = T.stepTrick(held, 0.1, { asleep: true, cmd: "sleep" });
  assert.equal(aborted.phase, "done");
  assert.equal(Rui.TRICKS.includes("flop"), false);
  assert.equal(Cat.TRICKS.includes("groom"), false);
  assert.equal(Dog.TRICKS.includes("periscope"), false);
  assert.equal(Relay.TRICKS.includes("dig"), false);
  assert.equal(Fuse.TRICKS.includes("binky"), false);
  assert.equal(Earth.TRICKS.includes("binky"), false);
  assert.equal(Dog.TRICKS.includes("binky"), false);
  assert.equal(Cat.TRICKS.includes("binky"), false);
  assert.equal(Cat.TRICKS.includes("rub"), false);
  assert.equal(Cat.TRICKS.includes("nosh"), false);
  assert.equal(T.TRICKS.includes("bow"), false);
  assert.equal(T.TRICKS.includes("thump"), false);
});

test("Thimble feed-happy is its own sit: twitch/ears/nudge, and two feeds are not the same", () => {
  assert.deepEqual([...T.HAPPY], ["twitch", "ears", "nudge"]);
  assert.equal(T.HAPPY.includes("spark"), false);
  assert.equal(T.HAPPY.includes("purr"), false);
  assert.equal(T.HAPPY.includes("tail"), false);
  assert.equal(T.pickHappy("twitch", 0), "ears");
  assert.notEqual(T.pickHappy("twitch", 0.9), "twitch");
  assert.equal(Overlay.pickHappy("ears", 0) !== "ears", true);
  assert.equal(T.happyCanStart({ asleep: false, hidden: false, leaving: false, cmd: "idle" }), true);
  assert.equal(T.happyCanStart({ asleep: false, hidden: false, leaving: false, cmd: "idle", card: true }), true);
  assert.equal(T.happyCanStart({ asleep: true, hidden: false, leaving: false, cmd: "idle" }), false);
  assert.equal(T.happyShouldAbort({ cmd: "sleep" }), true);
  assert.equal(T.happyShouldAbort({ cmd: "hide" }), true);
  assert.equal(T.happyShouldAbort({ card: true, cmd: "idle" }), false);
  const twitch = T.beginHappy("twitch", 80, 1);
  assert.equal(twitch.anim, "talk");
  const twitchMid = T.stepHappy(twitch, 0.4, { cmd: "idle" });
  assert.ok(twitchMid.lift > 0.2 || Math.abs(twitchMid.rot) > 0.5);
  assert.notEqual(twitchMid.phase, "done");
  const ears = T.beginHappy("ears", 80, 1);
  assert.equal(ears.anim, "sit");
  const earsMid = T.stepHappy(ears, 0.3, { cmd: "idle" });
  assert.ok(earsMid.rot > 2 || earsMid.lift < 0);
  const nudge = T.beginHappy("nudge", 80, 1);
  assert.equal(nudge.anim, "play");
  const done = T.stepHappy(twitch, T.HAPPY_DUR.twitch + 0.1, { cmd: "idle" });
  assert.equal(done.phase, "done");
  const aborted = T.stepHappy(twitchMid, 0.1, { asleep: true, cmd: "sleep" });
  assert.equal(aborted.phase, "done");
  assert.equal(aborted.abort, true);
  assert.equal(T.wantsThankYou("rabbit"), true);
  assert.equal(T.wantsThankYou("thimble"), true);
  assert.equal(T.wantsThankYou("dog"), false);
  assert.equal(T.wantsThankYou("cat"), false);
  assert.equal(T.wantsThankYou("red_panda"), false);
  assert.equal(T.wantsThankYou("ground_dragon"), false);
  const thanks = T.startThankYou("rabbit", "twitch", 80, 1, { cmd: "idle", card: true, windowPlay: true });
  assert.ok(thanks);
  assert.notEqual(thanks.kind, "twitch");
  assert.ok(thanks.happy.lift === 0);
  assert.notEqual(thanks.happy.anim, "eat");
  assert.notEqual(thanks.happy.anim, "idle");
  const thanksMid = T.stepHappy(thanks.happy, 0.35, { cmd: "idle", card: true });
  assert.ok(thanksMid.lift !== 0 || Math.abs(thanksMid.rot) > 0.5, "a thank-you twitches or nudges");
  const blocked = T.startThankYou("rabbit", "ears", 80, 1, { asleep: true, cmd: "idle" });
  assert.equal(blocked, null);
  const other = T.startThankYou("hamster", null, 80, 1, { cmd: "idle" });
  assert.equal(other, null);
  const second = T.startThankYou("rabbit", thanks.kind, 80, 1, { cmd: "idle", card: true });
  assert.ok(second);
  assert.notEqual(second.kind, thanks.kind);
});

test("ground registry keeps prior guests gated; Thimble selectable; no scratch/thump/bow-name collision", () => {
  assert.equal(Rui.TRICK_KEY, "red_panda");
  assert.equal(Relay.TRICK_KEY, "relay_dragon");
  assert.equal(Fuse.TRICK_KEY, "fuse_dragon");
  assert.equal(Earth.TRICK_KEY, "ground_dragon");
  assert.equal(Cat.TRICK_KEY, "cat");
  assert.equal(Dog.TRICK_KEY, "dog");
  assert.equal(T.TRICK_KEY, "rabbit");
  assert.deepEqual([...Rui.TRICKS], ["somersault", "lie", "scratch", "wave", "dance"]);
  assert.deepEqual([...Relay.TRICKS], ["contactclick", "latchseat", "arcflick", "coilbuzz", "poleswitch", "armaturetap", "relayhush"]);
  assert.deepEqual([...Fuse.TRICKS], ["railseat", "holdcurrent", "blowclear", "reseatsnap", "cartridgerattle", "bladeflash", "fusehush"]);
  assert.deepEqual([...Earth.TRICKS], ["lugstrap", "earthseat", "heaveplate", "bedsettle", "soilgrip", "plateclamp", "groundhush"]);
  assert.deepEqual([...Cat.TRICKS], ["loaf", "knead", "stretch", "wash", "pounce", "bunting", "mlem"]);
  assert.deepEqual([...Dog.TRICKS], ["wait", "wag", "sniff", "bow", "zoom", "beg", "pant"]);
  assert.equal(T.TRICKS.includes("scratch"), false);
  assert.equal(T.TRICKS.includes("thump"), false);
  assert.equal(T.TRICKS.includes("bow"), false);
  assert.equal(Rui.wantsThankYou("rabbit"), false);
  assert.equal(Relay.wantsThankYou("rabbit"), false);
  assert.equal(Fuse.wantsThankYou("rabbit"), false);
  assert.equal(Earth.wantsThankYou("rabbit"), false);
  assert.equal(Cat.wantsThankYou("rabbit"), false);
  assert.equal(Dog.wantsThankYou("rabbit"), false);
  assert.equal(T.wantsThankYou("rabbit"), true);
  assert.equal(T.wantsThankYou("thimble"), true);
  assert.equal(T.wantsThankYou("dog"), false);
  assert.equal(T.wantsThankYou("cat"), false);
  assert.equal(Rui.sleepHoldFrame("red_panda", 4), 1);
  assert.equal(T.sleepHoldFrame("rabbit", 4), null);
  globalThis.PetRuiTricks = OverlayRui;
  globalThis.PetRelayTricks = OverlayRelay;
  globalThis.PetFuseTricks = OverlayFuse;
  globalThis.PetEarthTricks = OverlayEarth;
  globalThis.PetCatTricks = OverlayCat;
  globalThis.PetDogTricks = OverlayDog;
  globalThis.PetRabbitTricks = Overlay;
  globalThis.PetHamsterTricks = OverlayHamster;
  globalThis.PetGuineaPigTricks = OverlayGuineaPig;
  assert.equal(OverlayGround.tricksFor("red_panda"), OverlayRui);
  assert.equal(OverlayGround.tricksFor("rui"), OverlayRui);
  assert.equal(OverlayGround.tricksFor("relay_dragon"), OverlayRelay);
  assert.equal(OverlayGround.tricksFor("fuse_dragon"), OverlayFuse);
  assert.equal(OverlayGround.tricksFor("ground_dragon"), OverlayEarth);
  assert.equal(OverlayGround.tricksFor("ground"), OverlayEarth);
  assert.equal(OverlayGround.tricksFor("cat"), OverlayCat);
  assert.equal(OverlayGround.tricksFor("miso"), OverlayCat);
  assert.equal(OverlayGround.tricksFor("dog"), OverlayDog);
  assert.equal(OverlayGround.tricksFor("pip"), OverlayDog);
  assert.equal(OverlayGround.tricksFor("rabbit"), Overlay);
  assert.equal(OverlayGround.tricksFor("thimble"), Overlay);
  assert.equal(OverlayGround.tricksFor("hamster"), OverlayHamster);
  assert.equal(OverlayGround.tricksFor("clip"), OverlayHamster);
  assert.equal(OverlayGround.tricksFor("guinea_pig"), OverlayGuineaPig);
  assert.equal(OverlayGround.tricksFor("whee"), OverlayGuineaPig);
  assert.equal(OverlayGround.tricksFor("turtle") == null, true);
  assert.equal(OverlayGround.wantsThankYou("red_panda"), true);
  assert.equal(OverlayGround.wantsThankYou("relay_dragon"), true);
  assert.equal(OverlayGround.wantsThankYou("fuse_dragon"), true);
  assert.equal(OverlayGround.wantsThankYou("ground_dragon"), true);
  assert.equal(OverlayGround.wantsThankYou("cat"), true);
  assert.equal(OverlayGround.wantsThankYou("miso"), true);
  assert.equal(OverlayGround.wantsThankYou("dog"), true);
  assert.equal(OverlayGround.wantsThankYou("pip"), true);
  assert.equal(OverlayGround.wantsThankYou("rabbit"), true);
  assert.equal(OverlayGround.wantsThankYou("thimble"), true);
  assert.equal(OverlayGround.wantsThankYou("hamster"), true);
  assert.equal(OverlayGround.wantsThankYou("clip"), true);
  assert.equal(OverlayGround.wantsThankYou("guinea_pig"), true);
  assert.equal(OverlayGround.wantsThankYou("whee"), true);
  assert.equal(OverlayGround.wantsThankYou("turtle"), false);
  assert.equal(OverlayGround.sleepHoldFrame("red_panda", 4), 1);
  assert.equal(OverlayGround.sleepHoldFrame("dog", 4), null);
  assert.equal(OverlayGround.sleepHoldFrame("cat", 4), null);
  assert.equal(OverlayGround.sleepHoldFrame("rabbit", 4), null);
  assert.equal(OverlayGround.sleepHoldFrame("hamster", 4), null);
});

test("ultra-polish: Thimble flop/groom/periscope/rub/nosh lifts are Rui-visible (not micro idle-gen)", () => {
  const ex = T.beginTrick("flop", 80, 1);
  const mid = T.stepTrick(ex, 5, { cmd: "idle" });
  assert.ok(Math.abs(mid.rot) > 6, `flop mid rot ${mid.rot}`);
  assert.ok(Math.abs(mid.lift) > 2, `flop mid lift ${mid.lift}`);
  const gr = T.beginTrick("groom", 80, 1);
  const g2 = T.stepTrick(gr, T.DUR.groom * 0.4, { cmd: "idle" });
  assert.ok(Math.abs(g2.rot) > 6, `groom mid rot ${g2.rot}`);
  assert.ok(Math.abs(g2.lift) > 2 || g2.lift > 2, `groom mid lift ${g2.lift}`);
  const pe = T.beginTrick("periscope", 80, 1);
  const p2 = T.stepTrick(pe, T.DUR.periscope * 0.4, { cmd: "idle" });
  assert.ok(p2.lift > 6, `periscope mid lift ${p2.lift}`);
  const rb = T.beginTrick("rub", 80, 1);
  const r2 = T.stepTrick(rb, T.DUR.rub * 0.4, { cmd: "idle" });
  assert.ok(r2.lift < -1 || Math.abs(r2.rot) > 6, `rub mid lift/rot ${r2.lift}/${r2.rot}`);
  const ns = T.beginTrick("nosh", 80, 1);
  const n2 = T.stepTrick(ns, T.DUR.nosh * 0.4, { cmd: "idle" });
  assert.ok(n2.lift < 0 || Math.abs(n2.rot) > 6, `nosh mid lift/rot ${n2.lift}/${n2.rot}`);
  assert.ok(Overlay.rubPose && Overlay.noshPose);
  assert.ok(T.nextTrickWait(true, 0, "flop") < 80);
  assert.ok(T.nextTrickWait(true, 0, "flop") > T.nextTrickWait(true, 0, "groom"));
});

test("notes: Thimble idle-life ultra done; Clip / hamster ultra next-or-done; following house-order ultra guest is Whee / guinea_pig (birds Soot→Ember + Miso + Pip already ultra)", () => {
  assert.deepEqual([...T.TRICKS], ["flop", "groom", "periscope", "dig", "binky", "rub", "nosh"]);
  assert.equal(T.TRICKS.includes("scratch"), false);
  assert.equal(T.TRICKS.includes("loaf"), false);
  assert.equal(T.TRICKS.includes("wait"), false);
  assert.equal(T.TRICKS.includes("bunting"), false);
  assert.equal(T.TRICKS.includes("somersault"), false);
  assert.equal(T.TRICKS.includes("lug"), false);
  assert.equal(T.TRICKS.includes("thump"), false);
  assert.equal(T.TRICKS.includes("mlem"), false);
  assert.equal(T.TRICKS.includes("chin"), false);
});
