import assert from "node:assert/strict";
import { createRequire } from "node:module";
import { dirname, join } from "node:path";
import { test } from "node:test";
import { fileURLToPath, pathToFileURL } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const T = await import(pathToFileURL(join(root, "src/lib/pets/relay-tricks.ts")).href);
const Rui = await import(pathToFileURL(join(root, "src/lib/pets/rui-tricks.ts")).href);
const Overlay = createRequire(import.meta.url)(join(root, "../desktop/renderer/relay-tricks.js"));
const OverlayGround = createRequire(import.meta.url)(join(root, "../desktop/renderer/ground-tricks.js"));
const OverlayRui = createRequire(import.meta.url)(join(root, "../desktop/renderer/rui-tricks.js"));

test("Relay tricks start only on idle ground", () => {
  assert.deepEqual([...T.TRICKS], ["click", "latch", "arc", "buzz", "switch"]);
  assert.equal(T.canStart({ asleep: false, hidden: false, leaving: false, cmd: "idle" }), true);
  assert.equal(T.canStart({ asleep: true, hidden: false, leaving: false, cmd: "idle" }), false);
  assert.equal(T.canStart({ asleep: false, hidden: true, leaving: false, cmd: "idle" }), false);
  assert.equal(T.canStart({ asleep: false, hidden: false, leaving: false, cmd: "sleep" }), false);
  assert.equal(T.canStart({ asleep: false, hidden: false, leaving: false, cmd: "seek" }), false);
  assert.equal(T.canStart({ asleep: false, hidden: false, leaving: false, cmd: "idle", windowPlay: true }), false);
  assert.equal(T.canStart({ asleep: false, hidden: false, leaving: false, cmd: "idle", card: true }), false);
  assert.equal(T.shouldAbort({ asleep: true, hidden: false, leaving: false, cmd: "idle" }), true);
  assert.equal(T.shouldAbort({ asleep: false, hidden: false, leaving: false, cmd: "idle", card: true }), true);
  assert.equal(T.shouldAbort({ asleep: false, hidden: false, leaving: false, cmd: "idle" }), false);
  assert.equal(T.pickTrick(0.99, true), "switch");
  assert.notEqual(T.pickTrick(0.3, false, "latch"), "latch");
  assert.equal(Overlay.TRICK_KEY, "relay_dragon");
  assert.equal(T.sleepHoldFrame("relay_dragon", 4), null);
  assert.equal(T.TRICKS.includes("somersault"), false);
  assert.equal(T.TRICKS.includes("dance"), false);
});

test("click/arc/latch are electrical-mechanical, not Rui clones", () => {
  const ground = { asleep: false, hidden: false, leaving: false, cmd: "idle" };
  const click = T.beginTrick("click", 80, 1);
  assert.equal(click.anim, "sit");
  const clickMid = T.stepTrick(click, 0.06, ground);
  assert.ok(Math.abs(clickMid.rot) > 2 || clickMid.lift > 0);
  const arc = T.beginTrick("arc", 80, 1);
  assert.equal(arc.anim, "play");
  const mid = T.stepTrick(arc, 0.39);
  assert.ok(mid.lift > 10);
  assert.ok(Math.abs(mid.rot) > 40);
  assert.ok(Math.abs(mid.rot) < 200, "half-flip arc, not a full 360 somersault");
  const done = T.stepTrick(arc, 1);
  assert.equal(done.phase, "done");
  const latch = T.beginTrick("latch", 80, 1);
  assert.equal(latch.anim, "sit");
  assert.equal(latch.phase, "hold");
  const held = T.stepTrick(latch, 5, ground);
  assert.equal(held.phase, "hold");
  assert.equal(held.anim, "sit");
  assert.equal(held.rot, 0);
  const release = T.stepTrick(latch, T.LATCH_HOLD + 0.2, ground);
  assert.equal(release.phase, "release");
  assert.equal(release.anim, "talk");
  const hop = T.stepTrick(latch, T.LATCH_HOLD + T.RELEASE_S + 0.3, ground);
  assert.equal(hop.phase, "hop");
  assert.equal(hop.anim, "play");
  assert.ok(Math.abs(hop.rot) > 20);
  const doneLatch = T.stepTrick(latch, T.DUR.latch + 0.1, ground);
  assert.equal(doneLatch.phase, "done");
  const aborted = T.stepTrick(held, 0.1, { asleep: true, cmd: "sleep" });
  assert.equal(aborted.phase, "done");
  assert.ok(T.nextTrickWait(true, 0, "latch") > T.nextTrickWait(true, 0, "buzz"));
  const buzz = T.beginTrick("buzz", 80, 1);
  assert.equal(buzz.anim, "talk");
});

test("Relay feed-happy is its own sit: spark/toggle/chatter, and two feeds are not the same", () => {
  assert.deepEqual([...T.HAPPY], ["spark", "toggle", "chatter"]);
  assert.equal(T.HAPPY.includes("twirl"), false);
  assert.equal(T.HAPPY.includes("dance"), false);
  assert.equal(T.pickHappy("spark", 0), "toggle");
  assert.notEqual(T.pickHappy("spark", 0.9), "spark");
  assert.equal(Overlay.pickHappy("toggle", 0) !== "toggle", true);
  assert.equal(T.happyCanStart({ asleep: false, hidden: false, leaving: false, cmd: "idle" }), true);
  assert.equal(T.happyCanStart({ asleep: false, hidden: false, leaving: false, cmd: "idle", card: true }), true);
  assert.equal(T.happyCanStart({ asleep: true, hidden: false, leaving: false, cmd: "idle" }), false);
  assert.equal(T.happyShouldAbort({ cmd: "sleep" }), true);
  assert.equal(T.happyShouldAbort({ cmd: "hide" }), true);
  assert.equal(T.happyShouldAbort({ card: true, cmd: "idle" }), false);
  const spark = T.beginHappy("spark", 80, 1);
  assert.equal(spark.anim, "play");
  const sparkMid = T.stepHappy(spark, 0.4, { cmd: "idle" });
  assert.ok(sparkMid.lift > 4 || Math.abs(sparkMid.rot) > 4);
  assert.notEqual(sparkMid.phase, "done");
  const toggle = T.beginHappy("toggle", 80, 1);
  assert.equal(toggle.anim, "walk");
  const toggleMid = T.stepHappy(toggle, 0.25, { cmd: "idle" });
  assert.equal(toggleMid.anim, "walk");
  assert.ok(Math.abs(toggleMid.x - 80) > 2);
  const chatter = T.beginHappy("chatter", 80, 1);
  assert.equal(chatter.anim, "talk");
  const done = T.stepHappy(spark, T.HAPPY_DUR.spark + 0.1, { cmd: "idle" });
  assert.equal(done.phase, "done");
  const aborted = T.stepHappy(sparkMid, 0.1, { asleep: true, cmd: "sleep" });
  assert.equal(aborted.phase, "done");
  assert.equal(aborted.abort, true);
  assert.equal(T.wantsThankYou("relay_dragon"), true);
  assert.equal(T.wantsThankYou("relay"), true);
  assert.equal(T.wantsThankYou("red_panda"), false);
  assert.equal(T.wantsThankYou("gauss_dragon"), false);
  const thanks = T.startThankYou("relay_dragon", "spark", 80, 1, { cmd: "idle", card: true, windowPlay: true });
  assert.ok(thanks);
  assert.notEqual(thanks.kind, "spark");
  assert.ok(thanks.happy.lift === 0);
  assert.notEqual(thanks.happy.anim, "eat");
  assert.notEqual(thanks.happy.anim, "idle");
  const thanksMid = T.stepHappy(thanks.happy, 0.35, { cmd: "idle", card: true });
  assert.ok(thanksMid.lift > 0 || Math.abs(thanksMid.rot) > 4 || Math.abs(thanksMid.x - 80) > 4, "a thank-you lifts or moves");
  const blocked = T.startThankYou("relay_dragon", "toggle", 80, 1, { asleep: true, cmd: "idle" });
  assert.equal(blocked, null);
  const other = T.startThankYou("gauss_dragon", null, 80, 1, { cmd: "idle" });
  assert.equal(other, null);
  const second = T.startThankYou("relay_dragon", thanks.kind, 80, 1, { cmd: "idle", card: true });
  assert.ok(second);
  assert.notEqual(second.kind, thanks.kind);
});

test("ground registry keeps Rui gated and Relay selectable", () => {
  assert.equal(Rui.TRICK_KEY, "red_panda");
  assert.deepEqual([...Rui.TRICKS], ["somersault", "lie", "scratch", "wave", "dance"]);
  assert.equal(T.TRICK_KEY, "relay_dragon");
  assert.equal(Rui.wantsThankYou("red_panda"), true);
  assert.equal(Rui.wantsThankYou("relay_dragon"), false);
  assert.equal(T.wantsThankYou("relay_dragon"), true);
  assert.equal(T.wantsThankYou("red_panda"), false);
  assert.equal(Rui.sleepHoldFrame("red_panda", 4), 1);
  assert.equal(T.sleepHoldFrame("relay_dragon", 4), null);
  globalThis.PetRuiTricks = OverlayRui;
  globalThis.PetRelayTricks = Overlay;
  assert.equal(OverlayGround.tricksFor("red_panda"), OverlayRui);
  assert.equal(OverlayGround.tricksFor("rui"), OverlayRui);
  assert.equal(OverlayGround.tricksFor("relay_dragon"), Overlay);
  assert.equal(OverlayGround.tricksFor("relay"), Overlay);
  assert.equal(OverlayGround.tricksFor("fuse_dragon"), null);
  assert.equal(OverlayGround.tricksFor("cat"), null);
  assert.equal(OverlayGround.wantsThankYou("red_panda"), true);
  assert.equal(OverlayGround.wantsThankYou("relay_dragon"), true);
  assert.equal(OverlayGround.wantsThankYou("fuse_dragon"), false);
  assert.equal(OverlayGround.sleepHoldFrame("red_panda", 4), 1);
  assert.equal(OverlayGround.sleepHoldFrame("relay_dragon", 4), null);
});
