import assert from "node:assert/strict";
import { createRequire } from "node:module";
import { dirname, join } from "node:path";
import { test } from "node:test";
import { fileURLToPath, pathToFileURL } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const T = await import(pathToFileURL(join(root, "src/lib/pets/rui-tricks.ts")).href);
const Overlay = createRequire(import.meta.url)(join(root, "../desktop/renderer/rui-tricks.js"));

test("Rui tricks start only on idle ground", () => {
  assert.deepEqual([...T.TRICKS], ["somersault", "lie", "scratch", "wave", "dance"]);
  assert.equal(T.canStart({ asleep: false, hidden: false, leaving: false, cmd: "idle" }), true);
  assert.equal(T.canStart({ asleep: true, hidden: false, leaving: false, cmd: "idle" }), false);
  assert.equal(T.canStart({ asleep: false, hidden: true, leaving: false, cmd: "idle" }), false);
  assert.equal(T.canStart({ asleep: false, hidden: false, leaving: false, cmd: "sleep" }), false);
  assert.equal(T.canStart({ asleep: false, hidden: false, leaving: false, cmd: "seek" }), false);
  assert.equal(T.canStart({ asleep: false, hidden: false, leaving: false, cmd: "idle", windowPlay: true }), false);
  assert.equal(T.canStart({ asleep: false, hidden: false, leaving: false, cmd: "idle", card: true }), false);
  assert.equal(T.shouldAbort({ asleep: true, hidden: false, leaving: false, cmd: "idle" }), true);
  assert.equal(T.shouldAbort({ asleep: false, hidden: false, leaving: false, cmd: "idle", card: true }), true);
  assert.equal(T.shouldAbort({ asleep: false, hidden: false, leaving: false, cmd: "idle" }), false);
  assert.equal(T.pickTrick(0.99, true), "dance");
  assert.notEqual(T.pickTrick(0.3, false, "lie"), "lie");
  assert.equal(Overlay.TRICK_KEY, "red_panda");
  assert.equal(T.sleepHoldFrame("red_panda", 4), 1);
  assert.equal(T.sleepHoldFrame("cat", 4), null);
});

test("somersault is a rotate+arc on existing play frames", () => {
  const start = T.beginTrick("somersault", 80, 1);
  assert.equal(start.anim, "play");
  const mid = T.stepTrick(start, 0.46);
  assert.ok(mid.lift > 20);
  assert.ok(Math.abs(mid.rot) > 90);
  const done = T.stepTrick(start, 1);
  assert.equal(done.phase, "done");
  const lie = T.beginTrick("lie", 80, 1);
  assert.equal(lie.anim, "sleep");
  assert.equal(lie.phase, "lie");
  const ground = { asleep: false, hidden: false, leaving: false, cmd: "idle" };
  const held = T.stepTrick(lie, 6, ground);
  assert.equal(held.phase, "lie");
  assert.equal(held.anim, "sleep");
  assert.equal(held.rot, 0);
  const stretch = T.stepTrick(lie, T.LIE_HOLD + 0.4, ground);
  assert.equal(stretch.phase, "stretch");
  assert.equal(stretch.anim, "sit");
  const flip = T.stepTrick(lie, T.LIE_HOLD + T.STRETCH_S + 0.4, ground);
  assert.equal(flip.phase, "flip");
  assert.equal(flip.anim, "play");
  assert.ok(Math.abs(flip.rot) > 40);
  const doneLie = T.stepTrick(lie, T.DUR.lie + 0.1, ground);
  assert.equal(doneLie.phase, "done");
  const aborted = T.stepTrick(held, 0.1, { asleep: true, cmd: "sleep" });
  assert.equal(aborted.phase, "done");
  assert.ok(T.nextTrickWait(true, 0, "lie") > T.nextTrickWait(true, 0, "wave"));
  const wave = T.beginTrick("wave", 80, 1);
  assert.equal(wave.anim, "talk");
});

test("feed-happy is its own sit: three dances, not the music loop, and two feeds are not the same", () => {
  assert.deepEqual([...T.HAPPY], ["twirl", "bounce", "shuffle"]);
  assert.equal(T.HAPPY.includes("dance"), false);
  assert.equal(T.pickHappy("twirl", 0), "bounce");
  assert.notEqual(T.pickHappy("twirl", 0.9), "twirl");
  assert.equal(Overlay.pickHappy("bounce", 0) !== "bounce", true);
  assert.equal(T.happyCanStart({ asleep: false, hidden: false, leaving: false, cmd: "idle" }), true);
  assert.equal(T.happyCanStart({ asleep: false, hidden: false, leaving: false, cmd: "idle", card: true }), true);
  assert.equal(T.happyCanStart({ asleep: true, hidden: false, leaving: false, cmd: "idle" }), false);
  assert.equal(T.happyShouldAbort({ cmd: "sleep" }), true);
  assert.equal(T.happyShouldAbort({ cmd: "hide" }), true);
  assert.equal(T.happyShouldAbort({ card: true, cmd: "idle" }), false);
  const twirl = T.beginHappy("twirl", 80, 1);
  assert.equal(twirl.anim, "play");
  const twirlMid = T.stepHappy(twirl, 0.7, { cmd: "idle" });
  assert.ok(Math.abs(twirlMid.rot) > 40);
  assert.notEqual(twirlMid.phase, "done");
  const bounce = T.beginHappy("bounce", 80, 1);
  const bounceMid = T.stepHappy(bounce, 0.2, { cmd: "idle" });
  assert.ok(bounceMid.lift > 8);
  assert.ok(Math.abs(bounceMid.rot) < 40);
  const shuffle = T.beginHappy("shuffle", 80, 1);
  assert.equal(shuffle.anim, "walk");
  const shuffleMid = T.stepHappy(shuffle, 0.3, { cmd: "idle" });
  assert.equal(shuffleMid.anim, "walk");
  assert.ok(Math.abs(shuffleMid.x - 80) > 4);
  const done = T.stepHappy(twirl, T.HAPPY_DUR.twirl + 0.1, { cmd: "idle" });
  assert.equal(done.phase, "done");
  const aborted = T.stepHappy(bounceMid, 0.1, { asleep: true, cmd: "sleep" });
  assert.equal(aborted.phase, "done");
  assert.equal(aborted.abort, true);
  assert.equal(T.wantsThankYou("red_panda"), true);
  assert.equal(T.wantsThankYou("rui"), true);
  assert.equal(T.wantsThankYou("gauss_dragon"), false);
  assert.equal(T.happyCanStart({ asleep: false, hidden: false, leaving: false, cmd: "idle", card: true, windowPlay: true }), true);
  const thanks = T.startThankYou("red_panda", "twirl", 80, 1, { cmd: "idle", card: true, windowPlay: true });
  assert.ok(thanks);
  assert.notEqual(thanks.kind, "twirl");
  assert.ok(thanks.happy.lift === 0);
  assert.notEqual(thanks.happy.anim, "eat");
  assert.notEqual(thanks.happy.anim, "idle");
  const thanksMid = T.stepHappy(thanks.happy, 0.35, { cmd: "idle", card: true });
  assert.ok(thanksMid.lift > 0 || Math.abs(thanksMid.rot) > 4 || Math.abs(thanksMid.x - 80) > 4, "a thank-you lifts or moves — not idle eat-only");
  const blocked = T.startThankYou("red_panda", "bounce", 80, 1, { asleep: true, cmd: "idle" });
  assert.equal(blocked, null);
  const other = T.startThankYou("gauss_dragon", null, 80, 1, { cmd: "idle" });
  assert.equal(other, null);
  const second = T.startThankYou("red_panda", thanks.kind, 80, 1, { cmd: "idle", card: true });
  assert.ok(second);
  assert.notEqual(second.kind, thanks.kind);
});
