import assert from "node:assert/strict";
import { createRequire } from "node:module";
import { dirname, join } from "node:path";
import { test } from "node:test";
import { fileURLToPath, pathToFileURL } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const T = await import(pathToFileURL(join(root, "src/lib/pets/sea_star-tricks.ts")).href);
const MoonJelly = await import(pathToFileURL(join(root, "src/lib/pets/moon_jelly-tricks.ts")).href);
const Nautilus = await import(pathToFileURL(join(root, "src/lib/pets/nautilus-tricks.ts")).href);
const Cuttlefish = await import(pathToFileURL(join(root, "src/lib/pets/cuttlefish-tricks.ts")).href);
const Octopus = await import(pathToFileURL(join(root, "src/lib/pets/octopus-tricks.ts")).href);
const CarpetPython = await import(pathToFileURL(join(root, "src/lib/pets/carpet-python-tricks.ts")).href);
const RosyBoa = await import(pathToFileURL(join(root, "src/lib/pets/rosy-boa-tricks.ts")).href);
const MilkSnake = await import(pathToFileURL(join(root, "src/lib/pets/milk-snake-tricks.ts")).href);
const Garter = await import(pathToFileURL(join(root, "src/lib/pets/garter-tricks.ts")).href);
const Boa = await import(pathToFileURL(join(root, "src/lib/pets/boa-tricks.ts")).href);
const Hognose = await import(pathToFileURL(join(root, "src/lib/pets/hognose-tricks.ts")).href);
const GreenTreePython = await import(pathToFileURL(join(root, "src/lib/pets/green-tree-python-tricks.ts")).href);
const BallPython = await import(pathToFileURL(join(root, "src/lib/pets/ball-python-tricks.ts")).href);
const CornSnake = await import(pathToFileURL(join(root, "src/lib/pets/corn-snake-tricks.ts")).href);
const Kingsnake = await import(pathToFileURL(join(root, "src/lib/pets/kingsnake-tricks.ts")).href);
const Phoenix = await import(pathToFileURL(join(root, "src/lib/pets/phoenix-tricks.ts")).href);
const Dragon = await import(pathToFileURL(join(root, "src/lib/pets/dragon-tricks.ts")).href);
const Rui = await import(pathToFileURL(join(root, "src/lib/pets/rui-tricks.ts")).href);
const Relay = await import(pathToFileURL(join(root, "src/lib/pets/relay-tricks.ts")).href);
const Fuse = await import(pathToFileURL(join(root, "src/lib/pets/fuse-tricks.ts")).href);
const Earth = await import(pathToFileURL(join(root, "src/lib/pets/earth-tricks.ts")).href);
const Cat = await import(pathToFileURL(join(root, "src/lib/pets/cat-tricks.ts")).href);
const Dog = await import(pathToFileURL(join(root, "src/lib/pets/dog-tricks.ts")).href);
const Rabbit = await import(pathToFileURL(join(root, "src/lib/pets/rabbit-tricks.ts")).href);
const Hamster = await import(pathToFileURL(join(root, "src/lib/pets/hamster-tricks.ts")).href);
const GuineaPig = await import(pathToFileURL(join(root, "src/lib/pets/guinea-pig-tricks.ts")).href);
const Turtle = await import(pathToFileURL(join(root, "src/lib/pets/turtle-tricks.ts")).href);
const Goldfish = await import(pathToFileURL(join(root, "src/lib/pets/goldfish-tricks.ts")).href);
const Budgie = await import(pathToFileURL(join(root, "src/lib/pets/budgie-tricks.ts")).href);
const Fox = await import(pathToFileURL(join(root, "src/lib/pets/fox-tricks.ts")).href);
const Penguin = await import(pathToFileURL(join(root, "src/lib/pets/penguin-tricks.ts")).href);
const Parrot = await import(pathToFileURL(join(root, "src/lib/pets/parrot-tricks.ts")).href);
const Ferret = await import(pathToFileURL(join(root, "src/lib/pets/ferret-tricks.ts")).href);
const Hedgehog = await import(pathToFileURL(join(root, "src/lib/pets/hedgehog-tricks.ts")).href);
const Chinchilla = await import(pathToFileURL(join(root, "src/lib/pets/chinchilla-tricks.ts")).href);
const Axolotl = await import(pathToFileURL(join(root, "src/lib/pets/axolotl-tricks.ts")).href);
const Toucan = await import(pathToFileURL(join(root, "src/lib/pets/toucan-tricks.ts")).href);
const Iguana = await import(pathToFileURL(join(root, "src/lib/pets/iguana-tricks.ts")).href);
const Overlay = createRequire(import.meta.url)(join(root, "../desktop/renderer/sea_star-tricks.js"));
const OverlayMoonJelly = createRequire(import.meta.url)(join(root, "../desktop/renderer/moon_jelly-tricks.js"));
const OverlayNautilus = createRequire(import.meta.url)(join(root, "../desktop/renderer/nautilus-tricks.js"));
const OverlayCuttlefish = createRequire(import.meta.url)(join(root, "../desktop/renderer/cuttlefish-tricks.js"));
const OverlayOctopus = createRequire(import.meta.url)(join(root, "../desktop/renderer/octopus-tricks.js"));
const OverlayCarpetPython = createRequire(import.meta.url)(join(root, "../desktop/renderer/carpet-python-tricks.js"));
const OverlayRosyBoa = createRequire(import.meta.url)(join(root, "../desktop/renderer/rosy-boa-tricks.js"));
const OverlayMilkSnake = createRequire(import.meta.url)(join(root, "../desktop/renderer/milk-snake-tricks.js"));
const OverlayGarter = createRequire(import.meta.url)(join(root, "../desktop/renderer/garter-tricks.js"));
const OverlayBoa = createRequire(import.meta.url)(join(root, "../desktop/renderer/boa-tricks.js"));
const OverlayHognose = createRequire(import.meta.url)(join(root, "../desktop/renderer/hognose-tricks.js"));
const OverlayGreenTreePython = createRequire(import.meta.url)(join(root, "../desktop/renderer/green-tree-python-tricks.js"));
const OverlayBallPython = createRequire(import.meta.url)(join(root, "../desktop/renderer/ball-python-tricks.js"));
const OverlayCornSnake = createRequire(import.meta.url)(join(root, "../desktop/renderer/corn-snake-tricks.js"));
const OverlayKingsnake = createRequire(import.meta.url)(join(root, "../desktop/renderer/kingsnake-tricks.js"));
const OverlayPhoenix = createRequire(import.meta.url)(join(root, "../desktop/renderer/phoenix-tricks.js"));
const OverlayGround = createRequire(import.meta.url)(join(root, "../desktop/renderer/ground-tricks.js"));
const OverlayRui = createRequire(import.meta.url)(join(root, "../desktop/renderer/rui-tricks.js"));
const OverlayRelay = createRequire(import.meta.url)(join(root, "../desktop/renderer/relay-tricks.js"));
const OverlayFuse = createRequire(import.meta.url)(join(root, "../desktop/renderer/fuse-tricks.js"));
const OverlayEarth = createRequire(import.meta.url)(join(root, "../desktop/renderer/earth-tricks.js"));
const OverlayCat = createRequire(import.meta.url)(join(root, "../desktop/renderer/cat-tricks.js"));
const OverlayDog = createRequire(import.meta.url)(join(root, "../desktop/renderer/dog-tricks.js"));
const OverlayRabbit = createRequire(import.meta.url)(join(root, "../desktop/renderer/rabbit-tricks.js"));
const OverlayHamster = createRequire(import.meta.url)(join(root, "../desktop/renderer/hamster-tricks.js"));
const OverlayGuineaPig = createRequire(import.meta.url)(join(root, "../desktop/renderer/guinea-pig-tricks.js"));
const OverlayTurtle = createRequire(import.meta.url)(join(root, "../desktop/renderer/turtle-tricks.js"));
const OverlayGoldfish = createRequire(import.meta.url)(join(root, "../desktop/renderer/goldfish-tricks.js"));
const OverlayBudgie = createRequire(import.meta.url)(join(root, "../desktop/renderer/budgie-tricks.js"));
const OverlayFox = createRequire(import.meta.url)(join(root, "../desktop/renderer/fox-tricks.js"));
const OverlayPenguin = createRequire(import.meta.url)(join(root, "../desktop/renderer/penguin-tricks.js"));
const OverlayParrot = createRequire(import.meta.url)(join(root, "../desktop/renderer/parrot-tricks.js"));
const OverlayFerret = createRequire(import.meta.url)(join(root, "../desktop/renderer/ferret-tricks.js"));
const OverlayHedgehog = createRequire(import.meta.url)(join(root, "../desktop/renderer/hedgehog-tricks.js"));
const OverlayChinchilla = createRequire(import.meta.url)(join(root, "../desktop/renderer/chinchilla-tricks.js"));
const OverlayAxolotl = createRequire(import.meta.url)(join(root, "../desktop/renderer/axolotl-tricks.js"));
const OverlayToucan = createRequire(import.meta.url)(join(root, "../desktop/renderer/toucan-tricks.js"));
const OverlayIguana = createRequire(import.meta.url)(join(root, "../desktop/renderer/iguana-tricks.js"));
const OverlayDragon = createRequire(import.meta.url)(join(root, "../desktop/renderer/dragon-tricks.js"));

test("Cling tricks start only on idle ground", () => {
  assert.deepEqual([...Turtle.TRICKS], ["soak", "tuck", "crane", "plod", "paddle", "snorkel", "wipe"]);
  assert.deepEqual([...Goldfish.TRICKS], ["drift", "gulp", "flare", "glint", "dart", "yawn", "forage"]);
  assert.deepEqual([...Axolotl.TRICKS], ["gill", "amble", "mend", "smile", "plume", "sprout", "glop"]);
  assert.deepEqual([...Octopus.TRICKS], ["mantle", "sucker", "jet", "veil", "tinker", "papilla", "ooze"]);
  assert.deepEqual([...Cuttlefish.TRICKS], ["bone", "pupil", "chroma", "hover", "blot", "strike", "zebra"]);
  assert.deepEqual([...Nautilus.TRICKS], ["spiral", "siphuncle", "nacre", "pinhole", "fringe", "hyponome", "aperture"]);
  assert.deepEqual([...CarpetPython.TRICKS], ["legend", "rung", "contour", "runner", "bearing", "canopy", "inset"]);
  assert.deepEqual([...T.TRICKS], ["podia", "righting", "crawl", "evert", "penta", "madre", "papula"]);
  assert.equal(T.canStart({ asleep: false, hidden: false, leaving: false, cmd: "idle" }), true);
  assert.equal(T.canStart({ asleep: true, hidden: false, leaving: false, cmd: "idle" }), false);
  assert.equal(T.canStart({ asleep: false, hidden: true, leaving: false, cmd: "idle" }), false);
  assert.equal(T.canStart({ asleep: false, hidden: false, leaving: false, cmd: "sleep" }), false);
  assert.equal(T.canStart({ asleep: false, hidden: false, leaving: false, cmd: "seek" }), false);
  assert.equal(T.canStart({ asleep: false, hidden: false, leaving: false, cmd: "idle", windowPlay: true }), false);
  assert.equal(T.canStart({ asleep: false, hidden: false, leaving: false, cmd: "idle", card: true }), false);
  assert.equal(T.shouldAbort({ asleep: true, hidden: false, leaving: false, cmd: "idle" }), true);
  assert.equal(T.shouldAbort({ asleep: false, hidden: false, leaving: false, cmd: "idle", card: true }), true);
  assert.equal(T.shouldAbort({ asleep: false, hidden: false, leaving: false, cmd: "idle" }), false);
  assert.equal(T.pickTrick(0.99, true), "podia");
  assert.notEqual(T.pickTrick(0.3, false, "podia"), "drift");
  assert.notEqual(T.pickTrick(0.3, false, "podia"), "soak");
  assert.notEqual(T.pickTrick(0.3, false, "podia"), "gill");
  assert.notEqual(T.pickTrick(0.3, false, "podia"), "mantle");
  assert.notEqual(T.pickTrick(0.3, false, "podia"), "bone");
  assert.notEqual(T.pickTrick(0.3, false, "podia"), "spiral");
  assert.notEqual(T.pickTrick(0.3, false, "podia"), "legend");
  assert.notEqual(T.pickTrick(0.3, false, "podia"), "bell");
  assert.equal(Overlay.TRICK_KEY, "sea_star");
  assert.equal(T.sleepHoldFrame("sea_star", 4), null);
  assert.equal(T.TRICKS.includes("reef"), false);
  assert.equal(T.TRICKS.includes("cling"), false);
  assert.equal(T.TRICKS.includes("rise"), false);
  assert.equal(T.TRICKS.includes("drift"), false);
  assert.equal(T.TRICKS.includes("hover"), false);
  assert.equal(T.TRICKS.includes("mantle"), false);
  assert.equal(T.TRICKS.includes("jet"), false);
  assert.equal(T.TRICKS.includes("veil"), false);
  assert.equal(T.TRICKS.includes("bone"), false);
  assert.equal(T.TRICKS.includes("spiral"), false);
  assert.equal(T.TRICKS.includes("fringe"), false);
  assert.equal(T.TRICKS.includes("nacre"), false);
  assert.equal(T.TRICKS.includes("gulp"), false);
  assert.equal(T.TRICKS.includes("flare"), false);
  assert.equal(T.TRICKS.includes("dart"), false);
  assert.equal(T.TRICKS.includes("soak"), false);
  assert.equal(T.TRICKS.includes("gill"), false);
  assert.equal(T.TRICKS.includes("hood"), false);
  assert.equal(Overlay.TRICKS.includes("reef"), false);
  assert.equal(Overlay.TRICKS.includes("cling"), false);
  assert.equal(Overlay.TRICKS.includes("bell"), false);
  assert.equal(Overlay.HAPPY.includes("keep"), false);
  assert.equal(Overlay.HAPPY.includes("ripple"), false);
  assert.equal(Overlay.HAPPY.includes("chamber"), false);
  assert.equal(Overlay.HAPPY.includes("pulse"), false);
  assert.equal(Overlay.HAPPY.includes("bubble"), false);
  assert.equal(Overlay.HAPPY.includes("glow"), false);
  assert.deepEqual([...Overlay.TRICKS], ["podia", "righting", "crawl", "evert", "penta", "madre", "papula"]);
  assert.deepEqual([...Overlay.HAPPY], ["damp", "adhere", "tide"]);
});

test("podia/righting/crawl/evert/penta/madre/papula are house-sea-star-true, not copies of prior guests", () => {
  const ground = { asleep: false, hidden: false, leaving: false, cmd: "idle" };
  const podia = T.beginTrick("podia", 80, 1);
  assert.equal(podia.anim, "sit");
  assert.equal(podia.phase, "hold");
  const held = T.stepTrick(podia, 5, ground);
  assert.equal(held.phase, "hold");
  assert.equal(held.anim, "sit");
  assert.ok(held.rot !== 0 || held.lift > 0);
  const release = T.stepTrick(podia, T.PODIA_HOLD + 0.2, ground);
  assert.equal(release.phase, "release");
  assert.equal(release.anim, "sit");
  const donePodia = T.stepTrick(podia, T.DUR.podia + 0.1, ground);
  assert.equal(donePodia.phase, "done");
  assert.ok(T.nextTrickWait(true, 0, "podia") > T.nextTrickWait(true, 0, "penta"));
  const righting = T.beginTrick("righting", 80, 1);
  assert.equal(righting.anim, "play");
  const rightingMid = T.stepTrick(righting, 0.5, ground);
  assert.ok(Math.abs(rightingMid.lift) > 0.05 || Math.abs(rightingMid.rot) > 1 || Math.abs(rightingMid.x - 80) > 0.05);
  const crawl = T.beginTrick("crawl", 80, 1);
  assert.equal(crawl.anim, "walk");
  const crawlMid = T.stepTrick(crawl, 0.5, ground);
  assert.ok(Math.abs(crawlMid.lift) > 0.05 || Math.abs(crawlMid.rot) > 1 || Math.abs(crawlMid.x - 80) > 0.05);
  const evert = T.beginTrick("evert", 80, 1);
  assert.equal(evert.anim, "talk");
  const evertMid = T.stepTrick(evert, 0.5, ground);
  assert.ok(Math.abs(evertMid.lift) > 0.05 || Math.abs(evertMid.rot) > 1 || Math.abs(evertMid.x - 80) > 0.05);
  const penta = T.beginTrick("penta", 80, 1);
  assert.equal(penta.anim, "sit");
  const pentaMid = T.stepTrick(penta, 0.5, ground);
  assert.ok(Math.abs(pentaMid.lift) > 0.05 || Math.abs(pentaMid.rot) > 1 || Math.abs(pentaMid.x - 80) > 0.05);
  const madre = T.beginTrick("madre", 80, 1);
  assert.equal(madre.anim, "talk");
  const madreMid = T.stepTrick(madre, T.DUR.madre * 0.4, ground);
  assert.ok(Math.abs(madreMid.lift) > 0.05 || Math.abs(madreMid.rot) > 1 || Math.abs(madreMid.x - 80) > 0.05);
  const papula = T.beginTrick("papula", 80, 1);
  assert.equal(papula.anim, "play");
  const papulaMid = T.stepTrick(papula, T.DUR.papula * 0.4, ground);
  assert.ok(Math.abs(papulaMid.lift) > 0.05 || Math.abs(papulaMid.rot) > 1 || Math.abs(papulaMid.x - 80) > 0.05);
  const evertDone = T.stepTrick(evert, T.DUR.evert + 0.1, ground);
  assert.equal(evertDone.phase, "done");
  const aborted = T.stepTrick(held, 0.1, { asleep: true, cmd: "sleep" });
  assert.equal(aborted.phase, "done");
  for (const mod of [Rui, Cat, Dog, Rabbit, Hamster, GuineaPig, Turtle, Goldfish, Budgie, Fox, Penguin, Parrot, Ferret, Hedgehog, Chinchilla, Axolotl, Toucan, Iguana, Dragon, Phoenix, BallPython, CornSnake, Kingsnake, GreenTreePython, Hognose, Garter, Boa, MilkSnake, RosyBoa, CarpetPython, Octopus, Cuttlefish, Nautilus, Relay, Fuse, Earth]) {
    assert.equal(mod.TRICKS.includes("bell"), false);
    assert.equal(mod.TRICKS.includes("oral"), false);
    assert.equal(mod.TRICKS.includes("lucent"), false);
    assert.equal(mod.TRICKS.includes("trail"), false);
    assert.equal(mod.TRICKS.includes("medusa"), false);
  }
  assert.deepEqual([...Turtle.TRICKS], ["soak", "tuck", "crane", "plod", "paddle", "snorkel", "wipe"]);
  assert.deepEqual([...Goldfish.TRICKS], ["drift", "gulp", "flare", "glint", "dart", "yawn", "forage"]);
  assert.deepEqual([...Axolotl.TRICKS], ["gill", "amble", "mend", "smile", "plume", "sprout", "glop"]);
  assert.deepEqual([...Octopus.TRICKS], ["mantle", "sucker", "jet", "veil", "tinker", "papilla", "ooze"]);
  assert.deepEqual([...Cuttlefish.TRICKS], ["bone", "pupil", "chroma", "hover", "blot", "strike", "zebra"]);
  assert.deepEqual([...Nautilus.TRICKS], ["spiral", "siphuncle", "nacre", "pinhole", "fringe", "hyponome", "aperture"]);
  assert.deepEqual([...CarpetPython.TRICKS], ["legend", "rung", "contour", "runner", "bearing", "canopy", "inset"]);
  assert.equal(T.TRICKS.includes("chime"), false);
  assert.equal(T.TRICKS.includes("pulse"), false);
  assert.equal(T.TRICKS.includes("drift"), false);
  assert.equal(MoonJelly.TRICKS.includes("madre"), false);
  assert.equal(MoonJelly.TRICKS.includes("papula"), false);
  assert.equal(Nautilus.TRICKS.includes("madre"), false);
  assert.equal(Cuttlefish.TRICKS.includes("madre"), false);
  assert.equal(Octopus.TRICKS.includes("madre"), false);
  assert.equal(Axolotl.TRICKS.includes("papula"), false);
  assert.equal(T.TRICKS.includes("jet"), false);
  assert.equal(T.TRICKS.includes("mantle"), false);
  assert.equal(T.TRICKS.includes("bone"), false);
  assert.equal(T.TRICKS.includes("spiral"), false);
  assert.equal(T.TRICKS.includes("hover"), false);
  assert.equal(T.TRICKS.includes("fringe"), false);
  assert.equal(T.TRICKS.includes("hood"), false);
  assert.equal(Cuttlefish.TRICKS.includes("bone"), true);
  assert.equal(Octopus.TRICKS.includes("jet"), true);
  assert.equal(Nautilus.TRICKS.includes("spiral"), true);
  assert.equal(Goldfish.TRICKS.includes("drift"), true);
  assert.equal(Fuse.HAPPY.includes("pulse"), false);
  assert.equal(Fuse.HAPPY.includes("densfuse"), true);
});

test("Cling feed-happy is its own sit: damp/adhere/tide, and two feeds are not the same", () => {
  assert.deepEqual([...T.HAPPY], ["damp", "adhere", "tide"]);
  assert.equal(T.HAPPY.includes("halo"), false);
  assert.equal(T.HAPPY.includes("lumen"), false);
  assert.equal(T.HAPPY.includes("gel"), false);
  assert.equal(T.HAPPY.includes("bubble"), false);
  assert.equal(T.HAPPY.includes("munch"), false);
  assert.equal(T.HAPPY.includes("wink"), false);
  assert.equal(T.HAPPY.includes("keep"), false);
  assert.equal(T.HAPPY.includes("tint"), false);
  assert.equal(T.HAPPY.includes("squeeze"), false);
  assert.equal(T.HAPPY.includes("ripple"), false);
  assert.equal(T.HAPPY.includes("glance"), false);
  assert.equal(T.HAPPY.includes("dab"), false);
  assert.equal(T.HAPPY.includes("chamber"), false);
  assert.equal(T.HAPPY.includes("pearl"), false);
  assert.equal(T.HAPPY.includes("quiet"), false);
  assert.equal(T.HAPPY.includes("pulse"), false);
  assert.equal(T.HAPPY.includes("glow"), false);
  assert.equal(T.HAPPY.includes("tribute"), false);
  assert.equal(T.pickHappy("damp", 0), "adhere");
  assert.notEqual(T.pickHappy("damp", 0.9), "damp");
  assert.equal(Overlay.pickHappy("adhere", 0) !== "adhere", true);
  assert.equal(T.happyCanStart({ asleep: false, hidden: false, leaving: false, cmd: "idle" }), true);
  assert.equal(T.happyCanStart({ asleep: false, hidden: false, leaving: false, cmd: "idle", card: true }), true);
  assert.equal(T.happyCanStart({ asleep: true, hidden: false, leaving: false, cmd: "idle" }), false);
  assert.equal(T.happyShouldAbort({ cmd: "sleep" }), true);
  assert.equal(T.happyShouldAbort({ cmd: "hide" }), true);
  assert.equal(T.happyShouldAbort({ card: true, cmd: "idle" }), false);
  const dampH = T.beginHappy("damp", 80, 1);
  assert.equal(dampH.anim, "sit");
  const dampMid = T.stepHappy(dampH, 0.4, { cmd: "idle" });
  assert.ok(dampMid.lift !== 0 || Math.abs(dampMid.rot) > 0.5);
  assert.notEqual(dampMid.phase, "done");
  const pressH = T.beginHappy("adhere", 80, 1);
  assert.equal(pressH.anim, "talk");
  const pressMid = T.stepHappy(pressH, 0.3, { cmd: "idle" });
  assert.ok(pressMid.lift > 0.2 || Math.abs(pressMid.rot) > 0.5);
  const tideH = T.beginHappy("tide", 80, 1);
  assert.equal(tideH.anim, "sit");
  const done = T.stepHappy(dampH, T.HAPPY_DUR.damp + 0.1, { cmd: "idle" });
  assert.equal(done.phase, "done");
  const aborted = T.stepHappy(pressMid, 0.1, { asleep: true, cmd: "sleep" });
  assert.equal(aborted.phase, "done");
  assert.equal(aborted.abort, true);
  assert.equal(T.wantsThankYou("sea_star"), true);
  assert.equal(T.wantsThankYou("cling"), true);
  assert.equal(T.wantsThankYou("moon_jelly"), false);
  assert.equal(T.wantsThankYou("pulse"), false);
  assert.equal(T.wantsThankYou("nautilus"), false);
  assert.equal(T.wantsThankYou("chamber"), false);
  assert.equal(T.wantsThankYou("cuttlefish"), false);
  assert.equal(T.wantsThankYou("sepia"), false);
  assert.equal(T.wantsThankYou("octopus"), false);
  assert.equal(T.wantsThankYou("cup"), false);
  assert.equal(T.wantsThankYou("goldfish"), false);
  assert.equal(T.wantsThankYou("coin"), false);
  assert.equal(T.wantsThankYou("turtle"), false);
  assert.equal(T.wantsThankYou("axolotl"), false);
  const thanks = T.startThankYou("sea_star", "damp", 80, 1, { cmd: "idle", card: true, windowPlay: true });
  assert.ok(thanks);
  assert.notEqual(thanks.kind, "damp");
  assert.ok(thanks.happy.lift === 0);
  assert.notEqual(thanks.happy.anim, "eat");
  assert.notEqual(thanks.happy.anim, "idle");
  const thanksMid = T.stepHappy(thanks.happy, 0.35, { cmd: "idle", card: true });
  assert.ok(thanksMid.lift !== 0 || Math.abs(thanksMid.rot) > 0.5, "a thank-you damps or presses");
  const blocked = T.startThankYou("sea_star", "tribute", 80, 1, { asleep: true, cmd: "idle" });
  assert.equal(blocked, null);
  const other = T.startThankYou("moon_jelly", null, 80, 1, { cmd: "idle" });
  assert.equal(other, null);
  const second = T.startThankYou("sea_star", thanks.kind, 80, 1, { cmd: "idle", card: true });
  assert.ok(second);
  assert.notEqual(second.kind, thanks.kind);
});

test("ground registry keeps prior guests gated; Cling selectable; prior guests still OK", () => {
  assert.equal(Rui.TRICK_KEY, "red_panda");
  assert.equal(Turtle.TRICK_KEY, "turtle");
  assert.equal(Goldfish.TRICK_KEY, "goldfish");
  assert.equal(Axolotl.TRICK_KEY, "axolotl");
  assert.equal(Octopus.TRICK_KEY, "octopus");
  assert.equal(Cuttlefish.TRICK_KEY, "cuttlefish");
  assert.equal(Nautilus.TRICK_KEY, "nautilus");
  assert.equal(CarpetPython.TRICK_KEY, "carpet_python");
  assert.equal(T.TRICK_KEY, "sea_star");
  assert.deepEqual([...Turtle.TRICKS], ["soak", "tuck", "crane", "plod", "paddle", "snorkel", "wipe"]);
  assert.deepEqual([...Goldfish.TRICKS], ["drift", "gulp", "flare", "glint", "dart", "yawn", "forage"]);
  assert.deepEqual([...Axolotl.TRICKS], ["gill", "amble", "mend", "smile", "plume", "sprout", "glop"]);
  assert.deepEqual([...Octopus.TRICKS], ["mantle", "sucker", "jet", "veil", "tinker", "papilla", "ooze"]);
  assert.deepEqual([...Cuttlefish.TRICKS], ["bone", "pupil", "chroma", "hover", "blot", "strike", "zebra"]);
  assert.deepEqual([...Nautilus.TRICKS], ["spiral", "siphuncle", "nacre", "pinhole", "fringe", "hyponome", "aperture"]);
  assert.deepEqual([...CarpetPython.TRICKS], ["legend", "rung", "contour", "runner", "bearing", "canopy", "inset"]);
  assert.deepEqual([...T.TRICKS], ["podia", "righting", "crawl", "evert", "penta", "madre", "papula"]);
  assert.equal(T.wantsThankYou("sea_star"), true);
  assert.equal(T.wantsThankYou("cling"), true);
  assert.equal(Turtle.wantsThankYou("ink"), true);
  assert.equal(Goldfish.wantsThankYou("coin"), true);
  assert.equal(Axolotl.wantsThankYou("bloom"), true);
  assert.equal(Octopus.wantsThankYou("cup"), true);
  assert.equal(Cuttlefish.wantsThankYou("sepia"), true);
  assert.equal(Nautilus.wantsThankYou("chamber"), true);
  assert.equal(Rui.sleepHoldFrame("red_panda", 4), 1);
  assert.equal(T.sleepHoldFrame("sea_star", 4), null);
  globalThis.PetRuiTricks = OverlayRui;
  globalThis.PetRelayTricks = OverlayRelay;
  globalThis.PetFuseTricks = OverlayFuse;
  globalThis.PetEarthTricks = OverlayEarth;
  globalThis.PetCatTricks = OverlayCat;
  globalThis.PetDogTricks = OverlayDog;
  globalThis.PetRabbitTricks = OverlayRabbit;
  globalThis.PetHamsterTricks = OverlayHamster;
  globalThis.PetGuineaPigTricks = OverlayGuineaPig;
  globalThis.PetTurtleTricks = OverlayTurtle;
  globalThis.PetGoldfishTricks = OverlayGoldfish;
  globalThis.PetBudgieTricks = OverlayBudgie;
  globalThis.PetFoxTricks = OverlayFox;
  globalThis.PetPenguinTricks = OverlayPenguin;
  globalThis.PetParrotTricks = OverlayParrot;
  globalThis.PetFerretTricks = OverlayFerret;
  globalThis.PetHedgehogTricks = OverlayHedgehog;
  globalThis.PetChinchillaTricks = OverlayChinchilla;
  globalThis.PetAxolotlTricks = OverlayAxolotl;
  globalThis.PetToucanTricks = OverlayToucan;
  globalThis.PetIguanaTricks = OverlayIguana;
  globalThis.PetDragonTricks = OverlayDragon;
  globalThis.PetPhoenixTricks = OverlayPhoenix;
  globalThis.PetBallPythonTricks = OverlayBallPython;
  globalThis.PetCornSnakeTricks = OverlayCornSnake;
  globalThis.PetKingsnakeTricks = OverlayKingsnake;
  globalThis.PetGreenTreePythonTricks = OverlayGreenTreePython;
  globalThis.PetHognoseTricks = OverlayHognose;
  globalThis.PetGarterTricks = OverlayGarter;
  globalThis.PetBoaTricks = OverlayBoa;
  globalThis.PetMilkSnakeTricks = OverlayMilkSnake;
  globalThis.PetRosyBoaTricks = OverlayRosyBoa;
  globalThis.PetCarpetPythonTricks = OverlayCarpetPython;
  globalThis.PetOctopusTricks = OverlayOctopus;
  globalThis.PetCuttlefishTricks = OverlayCuttlefish;
  globalThis.PetNautilusTricks = OverlayNautilus;
  globalThis.PetMoonJellyTricks = OverlayMoonJelly;
  globalThis.PetSeaStarTricks = Overlay;
  assert.equal(OverlayGround.tricksFor("red_panda"), OverlayRui);
  assert.equal(OverlayGround.tricksFor("rui"), OverlayRui);
  assert.equal(OverlayGround.tricksFor("turtle"), OverlayTurtle);
  assert.equal(OverlayGround.tricksFor("ink"), OverlayTurtle);
  assert.equal(OverlayGround.tricksFor("goldfish"), OverlayGoldfish);
  assert.equal(OverlayGround.tricksFor("coin"), OverlayGoldfish);
  assert.equal(OverlayGround.tricksFor("axolotl"), OverlayAxolotl);
  assert.equal(OverlayGround.tricksFor("bloom"), OverlayAxolotl);
  assert.equal(OverlayGround.tricksFor("octopus"), OverlayOctopus);
  assert.equal(OverlayGround.tricksFor("cup"), OverlayOctopus);
  assert.equal(OverlayGround.tricksFor("cuttlefish"), OverlayCuttlefish);
  assert.equal(OverlayGround.tricksFor("sepia"), OverlayCuttlefish);
  assert.equal(OverlayGround.tricksFor("nautilus"), OverlayNautilus);
  assert.equal(OverlayGround.tricksFor("chamber"), OverlayNautilus);
  assert.equal(OverlayGround.tricksFor("carpet_python"), OverlayCarpetPython);
  assert.equal(OverlayGround.tricksFor("atlas"), OverlayCarpetPython);
  assert.equal(OverlayGround.tricksFor("moon_jelly"), OverlayMoonJelly);
  assert.equal(OverlayGround.tricksFor("pulse"), OverlayMoonJelly);
  assert.equal(OverlayGround.tricksFor("sea_star"), Overlay);
  assert.equal(OverlayGround.tricksFor("cling"), Overlay);
  assert.equal(OverlayGround.wantsThankYou("turtle"), true);
  assert.equal(OverlayGround.wantsThankYou("ink"), true);
  assert.equal(OverlayGround.wantsThankYou("goldfish"), true);
  assert.equal(OverlayGround.wantsThankYou("coin"), true);
  assert.equal(OverlayGround.wantsThankYou("axolotl"), true);
  assert.equal(OverlayGround.wantsThankYou("bloom"), true);
  assert.equal(OverlayGround.wantsThankYou("octopus"), true);
  assert.equal(OverlayGround.wantsThankYou("cup"), true);
  assert.equal(OverlayGround.wantsThankYou("cuttlefish"), true);
  assert.equal(OverlayGround.wantsThankYou("sepia"), true);
  assert.equal(OverlayGround.wantsThankYou("nautilus"), true);
  assert.equal(OverlayGround.wantsThankYou("chamber"), true);
  assert.equal(OverlayGround.wantsThankYou("carpet_python"), true);
  assert.equal(OverlayGround.wantsThankYou("atlas"), true);
  assert.equal(OverlayGround.wantsThankYou("moon_jelly"), true);
  assert.equal(OverlayGround.wantsThankYou("pulse"), true);
  assert.equal(OverlayGround.sleepHoldFrame("red_panda", 4), 1);
  assert.equal(OverlayGround.sleepHoldFrame("moon_jelly", 4), null);
  assert.deepEqual([...OverlayTurtle.TRICKS], ["soak", "tuck", "crane", "plod", "paddle", "snorkel", "wipe"]);
  assert.deepEqual([...OverlayGoldfish.TRICKS], ["drift", "gulp", "flare", "glint", "dart", "yawn", "forage"]);
  assert.deepEqual([...OverlayAxolotl.TRICKS], ["gill", "amble", "mend", "smile", "plume", "sprout", "glop"]);
  assert.deepEqual([...OverlayOctopus.TRICKS], ["mantle", "sucker", "jet", "veil", "tinker", "papilla", "ooze"]);
  assert.deepEqual([...OverlayCuttlefish.TRICKS], ["bone", "pupil", "chroma", "hover", "blot", "strike", "zebra"]);
  assert.deepEqual([...OverlayNautilus.TRICKS], ["spiral", "siphuncle", "nacre", "pinhole", "fringe", "hyponome", "aperture"]);
  assert.deepEqual([...OverlayCarpetPython.TRICKS], ["legend", "rung", "contour", "runner", "bearing", "canopy", "inset"]);
  assert.deepEqual([...Overlay.TRICKS], ["podia", "righting", "crawl", "evert", "penta", "madre", "papula"]);
  assert.equal(Overlay.TRICKS.includes("reef"), false);
  assert.equal(Overlay.TRICKS.includes("cling"), false);
  assert.equal(Overlay.TRICKS.includes("bell"), false);
  assert.equal(Overlay.TRICKS.includes("drift"), false);
  assert.equal(Overlay.TRICKS.includes("jet"), false);
  assert.equal(Overlay.TRICKS.includes("mantle"), false);
  assert.equal(Overlay.TRICKS.includes("bone"), false);
  assert.equal(Overlay.TRICKS.includes("spiral"), false);
  assert.equal(Overlay.TRICKS.includes("tuck"), false);
  assert.equal(Overlay.TRICKS.includes("gill"), false);
  assert.equal(Overlay.TRICKS.includes("legend"), false);
});


test("ultra-polish: Ochre podia/madre/papula lifts are Rui-visible (not micro idle-gen)", () => {
  const pod = T.beginTrick("podia", 80, 1);
  const mid = T.stepTrick(pod, 5, { cmd: "idle" });
  assert.ok(Math.abs(mid.rot) > 10, `podia mid rot ${mid.rot}`);
  assert.ok(Math.abs(mid.lift) > 0.5, `podia mid lift ${mid.lift}`);
  const md = T.beginTrick("madre", 80, 1);
  const m2 = T.stepTrick(md, T.DUR.madre * 0.4, { cmd: "idle" });
  assert.ok(m2.lift > 2 || Math.abs(m2.rot) > 4 || Math.abs(m2.x - 80) > 1, `madre mid ${m2.lift}/${m2.rot}/${m2.x}`);
  const pp = T.beginTrick("papula", 80, 1);
  const p2 = T.stepTrick(pp, T.DUR.papula * 0.4, { cmd: "idle" });
  assert.ok(p2.lift > 2 || Math.abs(p2.rot) > 8 || Math.abs(p2.x - 80) > 0.3, `papula mid ${p2.lift}/${p2.rot}/${p2.x}`);
  const cr = T.beginTrick("crawl", 80, 1);
  const c2 = T.stepTrick(cr, T.DUR.crawl * 0.4, { cmd: "idle" });
  assert.ok(c2.lift > 0.5 || Math.abs(c2.rot) > 4 || Math.abs(c2.x - 80) > 0.5, `crawl mid ${c2.lift}/${c2.rot}/${c2.x}`);
  assert.ok(Overlay.madrePose && Overlay.papulaPose);
  assert.deepEqual([...T.TRICKS], [...Overlay.TRICKS]);
  assert.equal(T.PODIA_HOLD, Overlay.PODIA_HOLD);
  assert.equal(T.PODIA_HOLD, 11.2);
  assert.equal(T.RELEASE_S, 1.18);
  assert.ok(T.nextTrickWait(true, 0, "podia") > 39);
});

test("notes: Ochre Rui-dense ultra (PODIA_HOLD=11.2); Tenant densified; Ledger densified; Anchor densified; Kite densified; Door densified; Felt densified; Vein densified; Fan densified; Mast densified; Disk densified; next leftover Wax / honeycomb", () => {
  assert.equal(T.TRICK_KEY, "sea_star");
  assert.equal(T.wantsThankYou("cling"), true);
  assert.equal(OverlayGround.tricksFor("sea_star"), Overlay);
  assert.equal(OverlayGround.tricksFor("cling"), Overlay);
  assert.equal(OverlayGround.wantsThankYou("sea_star"), true);
  assert.equal(OverlayGround.wantsThankYou("cling"), true);
  assert.equal(OverlayGround.tricksFor("moon_jelly"), OverlayMoonJelly);
  assert.equal(OverlayGround.tricksFor("pulse"), OverlayMoonJelly);
  assert.equal(OverlayGround.tricksFor("nautilus"), OverlayNautilus);
  assert.equal(OverlayGround.tricksFor("chamber"), OverlayNautilus);
  assert.equal(OverlayGround.tricksFor("cuttlefish"), OverlayCuttlefish);
  assert.equal(OverlayGround.tricksFor("sepia"), OverlayCuttlefish);
  assert.equal(OverlayGround.tricksFor("octopus"), OverlayOctopus);
  assert.equal(OverlayGround.tricksFor("cup"), OverlayOctopus);
  assert.equal(OverlayGround.tricksFor("carpet_python"), OverlayCarpetPython);
  assert.equal(OverlayGround.tricksFor("atlas"), OverlayCarpetPython);
  assert.equal(OverlayGround.tricksFor("turtle"), OverlayTurtle);
  assert.equal(OverlayGround.tricksFor("ink"), OverlayTurtle);
  assert.equal(OverlayGround.tricksFor("goldfish"), OverlayGoldfish);
  assert.equal(OverlayGround.tricksFor("coin"), OverlayGoldfish);
  assert.equal(OverlayGround.tricksFor("axolotl"), OverlayAxolotl);
  assert.equal(OverlayGround.tricksFor("bloom"), OverlayAxolotl);
  assert.equal(OverlayGround.tricksFor("seahorse") == null, true);
  assert.equal(OverlayGround.wantsThankYou("seahorse"), false);
  assert.equal(OverlayGround.tricksFor("anchor") == null, true);
  assert.equal(OverlayGround.wantsThankYou("anchor"), false);
});
