import assert from "node:assert/strict";
import { createRequire } from "node:module";
import { dirname, join } from "node:path";
import { test } from "node:test";
import { fileURLToPath, pathToFileURL } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const T = await import(pathToFileURL(join(root, "src/lib/pets/seahorse-tricks.ts")).href);
const SeaStar = await import(pathToFileURL(join(root, "src/lib/pets/sea_star-tricks.ts")).href);
const HermitCrab = await import(pathToFileURL(join(root, "src/lib/pets/hermit_crab-tricks.ts")).href);
const HorseshoeCrab = await import(pathToFileURL(join(root, "src/lib/pets/horseshoe_crab-tricks.ts")).href);
const MoonJelly = await import(pathToFileURL(join(root, "src/lib/pets/moon_jelly-tricks.ts")).href);
const Nautilus = await import(pathToFileURL(join(root, "src/lib/pets/nautilus-tricks.ts")).href);
const Cuttlefish = await import(pathToFileURL(join(root, "src/lib/pets/cuttlefish-tricks.ts")).href);
const Octopus = await import(pathToFileURL(join(root, "src/lib/pets/octopus-tricks.ts")).href);
const CarpetPython = await import(pathToFileURL(join(root, "src/lib/pets/carpet-python-tricks.ts")).href);
const RosyBoa = await import(pathToFileURL(join(root, "src/lib/pets/rosy-boa-tricks.ts")).href);
const MilkSnake = await import(pathToFileURL(join(root, "src/lib/pets/milk-snake-tricks.ts")).href);
const Garter = await import(pathToFileURL(join(root, "src/lib/pets/garter-tricks.ts")).href);
const Boa = await import(pathToFileURL(join(root, "src/lib/pets/boa-tricks.ts")).href);
const Hognose = await import(pathToFileURL(join(root, "src/lib/pets/hognose-tricks.ts")).href);
const GreenTreePython = await import(pathToFileURL(join(root, "src/lib/pets/green-tree-python-tricks.ts")).href);
const BallPython = await import(pathToFileURL(join(root, "src/lib/pets/ball-python-tricks.ts")).href);
const CornSnake = await import(pathToFileURL(join(root, "src/lib/pets/corn-snake-tricks.ts")).href);
const Kingsnake = await import(pathToFileURL(join(root, "src/lib/pets/kingsnake-tricks.ts")).href);
const Phoenix = await import(pathToFileURL(join(root, "src/lib/pets/phoenix-tricks.ts")).href);
const Dragon = await import(pathToFileURL(join(root, "src/lib/pets/dragon-tricks.ts")).href);
const Rui = await import(pathToFileURL(join(root, "src/lib/pets/rui-tricks.ts")).href);
const Relay = await import(pathToFileURL(join(root, "src/lib/pets/relay-tricks.ts")).href);
const Fuse = await import(pathToFileURL(join(root, "src/lib/pets/fuse-tricks.ts")).href);
const Earth = await import(pathToFileURL(join(root, "src/lib/pets/earth-tricks.ts")).href);
const Cat = await import(pathToFileURL(join(root, "src/lib/pets/cat-tricks.ts")).href);
const Dog = await import(pathToFileURL(join(root, "src/lib/pets/dog-tricks.ts")).href);
const Rabbit = await import(pathToFileURL(join(root, "src/lib/pets/rabbit-tricks.ts")).href);
const Hamster = await import(pathToFileURL(join(root, "src/lib/pets/hamster-tricks.ts")).href);
const GuineaPig = await import(pathToFileURL(join(root, "src/lib/pets/guinea-pig-tricks.ts")).href);
const Turtle = await import(pathToFileURL(join(root, "src/lib/pets/turtle-tricks.ts")).href);
const Goldfish = await import(pathToFileURL(join(root, "src/lib/pets/goldfish-tricks.ts")).href);
const Budgie = await import(pathToFileURL(join(root, "src/lib/pets/budgie-tricks.ts")).href);
const Fox = await import(pathToFileURL(join(root, "src/lib/pets/fox-tricks.ts")).href);
const Penguin = await import(pathToFileURL(join(root, "src/lib/pets/penguin-tricks.ts")).href);
const Parrot = await import(pathToFileURL(join(root, "src/lib/pets/parrot-tricks.ts")).href);
const Ferret = await import(pathToFileURL(join(root, "src/lib/pets/ferret-tricks.ts")).href);
const Hedgehog = await import(pathToFileURL(join(root, "src/lib/pets/hedgehog-tricks.ts")).href);
const Chinchilla = await import(pathToFileURL(join(root, "src/lib/pets/chinchilla-tricks.ts")).href);
const Axolotl = await import(pathToFileURL(join(root, "src/lib/pets/axolotl-tricks.ts")).href);
const Toucan = await import(pathToFileURL(join(root, "src/lib/pets/toucan-tricks.ts")).href);
const Iguana = await import(pathToFileURL(join(root, "src/lib/pets/iguana-tricks.ts")).href);
const Overlay = createRequire(import.meta.url)(join(root, "../desktop/renderer/seahorse-tricks.js"));
const OverlaySeaStar = createRequire(import.meta.url)(join(root, "../desktop/renderer/sea_star-tricks.js"));
const OverlayHermitCrab = createRequire(import.meta.url)(join(root, "../desktop/renderer/hermit_crab-tricks.js"));
const OverlayHorseshoeCrab = createRequire(import.meta.url)(join(root, "../desktop/renderer/horseshoe_crab-tricks.js"));
const OverlayMoonJelly = createRequire(import.meta.url)(join(root, "../desktop/renderer/moon_jelly-tricks.js"));
const OverlayNautilus = createRequire(import.meta.url)(join(root, "../desktop/renderer/nautilus-tricks.js"));
const OverlayCuttlefish = createRequire(import.meta.url)(join(root, "../desktop/renderer/cuttlefish-tricks.js"));
const OverlayOctopus = createRequire(import.meta.url)(join(root, "../desktop/renderer/octopus-tricks.js"));
const OverlayCarpetPython = createRequire(import.meta.url)(join(root, "../desktop/renderer/carpet-python-tricks.js"));
const OverlayRosyBoa = createRequire(import.meta.url)(join(root, "../desktop/renderer/rosy-boa-tricks.js"));
const OverlayMilkSnake = createRequire(import.meta.url)(join(root, "../desktop/renderer/milk-snake-tricks.js"));
const OverlayGarter = createRequire(import.meta.url)(join(root, "../desktop/renderer/garter-tricks.js"));
const OverlayBoa = createRequire(import.meta.url)(join(root, "../desktop/renderer/boa-tricks.js"));
const OverlayHognose = createRequire(import.meta.url)(join(root, "../desktop/renderer/hognose-tricks.js"));
const OverlayGreenTreePython = createRequire(import.meta.url)(join(root, "../desktop/renderer/green-tree-python-tricks.js"));
const OverlayBallPython = createRequire(import.meta.url)(join(root, "../desktop/renderer/ball-python-tricks.js"));
const OverlayCornSnake = createRequire(import.meta.url)(join(root, "../desktop/renderer/corn-snake-tricks.js"));
const OverlayKingsnake = createRequire(import.meta.url)(join(root, "../desktop/renderer/kingsnake-tricks.js"));
const OverlayPhoenix = createRequire(import.meta.url)(join(root, "../desktop/renderer/phoenix-tricks.js"));
const OverlayGround = createRequire(import.meta.url)(join(root, "../desktop/renderer/ground-tricks.js"));
const OverlayRui = createRequire(import.meta.url)(join(root, "../desktop/renderer/rui-tricks.js"));
const OverlayRelay = createRequire(import.meta.url)(join(root, "../desktop/renderer/relay-tricks.js"));
const OverlayFuse = createRequire(import.meta.url)(join(root, "../desktop/renderer/fuse-tricks.js"));
const OverlayEarth = createRequire(import.meta.url)(join(root, "../desktop/renderer/earth-tricks.js"));
const OverlayCat = createRequire(import.meta.url)(join(root, "../desktop/renderer/cat-tricks.js"));
const OverlayDog = createRequire(import.meta.url)(join(root, "../desktop/renderer/dog-tricks.js"));
const OverlayRabbit = createRequire(import.meta.url)(join(root, "../desktop/renderer/rabbit-tricks.js"));
const OverlayHamster = createRequire(import.meta.url)(join(root, "../desktop/renderer/hamster-tricks.js"));
const OverlayGuineaPig = createRequire(import.meta.url)(join(root, "../desktop/renderer/guinea-pig-tricks.js"));
const OverlayTurtle = createRequire(import.meta.url)(join(root, "../desktop/renderer/turtle-tricks.js"));
const OverlayGoldfish = createRequire(import.meta.url)(join(root, "../desktop/renderer/goldfish-tricks.js"));
const OverlayBudgie = createRequire(import.meta.url)(join(root, "../desktop/renderer/budgie-tricks.js"));
const OverlayFox = createRequire(import.meta.url)(join(root, "../desktop/renderer/fox-tricks.js"));
const OverlayPenguin = createRequire(import.meta.url)(join(root, "../desktop/renderer/penguin-tricks.js"));
const OverlayParrot = createRequire(import.meta.url)(join(root, "../desktop/renderer/parrot-tricks.js"));
const OverlayFerret = createRequire(import.meta.url)(join(root, "../desktop/renderer/ferret-tricks.js"));
const OverlayHedgehog = createRequire(import.meta.url)(join(root, "../desktop/renderer/hedgehog-tricks.js"));
const OverlayChinchilla = createRequire(import.meta.url)(join(root, "../desktop/renderer/chinchilla-tricks.js"));
const OverlayAxolotl = createRequire(import.meta.url)(join(root, "../desktop/renderer/axolotl-tricks.js"));
const OverlayToucan = createRequire(import.meta.url)(join(root, "../desktop/renderer/toucan-tricks.js"));
const OverlayIguana = createRequire(import.meta.url)(join(root, "../desktop/renderer/iguana-tricks.js"));
const OverlayDragon = createRequire(import.meta.url)(join(root, "../desktop/renderer/dragon-tricks.js"));

test("Anchor tricks start only on idle ground", () => {
  assert.deepEqual([...Turtle.TRICKS], ["soak", "tuck", "crane", "plod", "paddle", "snorkel", "wipe"]);
  assert.deepEqual([...Goldfish.TRICKS], ["drift", "gulp", "flare", "glint", "dart", "yawn", "forage"]);
  assert.deepEqual([...Axolotl.TRICKS], ["gill", "amble", "mend", "smile", "plume", "sprout", "glop"]);
  assert.deepEqual([...Octopus.TRICKS], ["mantle", "sucker", "jet", "veil", "tinker", "papilla", "ooze"]);
  assert.deepEqual([...Cuttlefish.TRICKS], ["bone", "pupil", "chroma", "hover", "blot", "strike", "zebra"]);
  assert.deepEqual([...Nautilus.TRICKS], ["spiral", "siphuncle", "nacre", "pinhole", "fringe", "hyponome", "aperture"]);
  assert.deepEqual([...CarpetPython.TRICKS], ["legend", "rung", "contour", "runner", "bearing", "canopy", "inset"]);
  assert.deepEqual([...T.TRICKS], ["coil", "buoy", "siphon", "swivel", "pouch", "dorsal", "pectoral"]);
  assert.equal(T.canStart({ asleep: false, hidden: false, leaving: false, cmd: "idle" }), true);
  assert.equal(T.canStart({ asleep: true, hidden: false, leaving: false, cmd: "idle" }), false);
  assert.equal(T.canStart({ asleep: false, hidden: true, leaving: false, cmd: "idle" }), false);
  assert.equal(T.canStart({ asleep: false, hidden: false, leaving: false, cmd: "sleep" }), false);
  assert.equal(T.canStart({ asleep: false, hidden: false, leaving: false, cmd: "seek" }), false);
  assert.equal(T.canStart({ asleep: false, hidden: false, leaving: false, cmd: "idle", windowPlay: true }), false);
  assert.equal(T.canStart({ asleep: false, hidden: false, leaving: false, cmd: "idle", card: true }), false);
  assert.equal(T.shouldAbort({ asleep: true, hidden: false, leaving: false, cmd: "idle" }), true);
  assert.equal(T.shouldAbort({ asleep: false, hidden: false, leaving: false, cmd: "idle", card: true }), true);
  assert.equal(T.shouldAbort({ asleep: false, hidden: false, leaving: false, cmd: "idle" }), false);
  assert.equal(T.pickTrick(0.99, true), "coil");
  assert.notEqual(T.pickTrick(0.3, false, "coil"), "drift");
  assert.notEqual(T.pickTrick(0.3, false, "coil"), "soak");
  assert.notEqual(T.pickTrick(0.3, false, "coil"), "gill");
  assert.notEqual(T.pickTrick(0.3, false, "coil"), "mantle");
  assert.notEqual(T.pickTrick(0.3, false, "coil"), "bone");
  assert.notEqual(T.pickTrick(0.3, false, "coil"), "spiral");
  assert.notEqual(T.pickTrick(0.3, false, "coil"), "legend");
  assert.notEqual(T.pickTrick(0.3, false, "coil"), "bell");
  assert.notEqual(T.pickTrick(0.3, false, "coil"), "podia");
  assert.notEqual(T.pickTrick(0.3, false, "coil"), "scurry");
  assert.notEqual(T.pickTrick(0.3, false, "coil"), "curl");
  assert.equal(Overlay.TRICK_KEY, "seahorse");
  assert.equal(T.sleepHoldFrame("seahorse", 4), null);
  assert.equal(T.TRICKS.includes("hitch"), false);
  assert.equal(T.TRICKS.includes("plow"), false);
  assert.equal(T.TRICKS.includes("plow"), false);
  assert.equal(T.TRICKS.includes("swap"), false);
  assert.equal(T.TRICKS.includes("withdraw"), false);
  assert.equal(T.TRICKS.includes("vacancy"), false);
  assert.equal(T.TRICKS.includes("antenna"), false);
  assert.equal(T.TRICKS.includes("scuttle"), false);
  assert.equal(T.HAPPY.includes("halo"), false);
  assert.equal(T.HAPPY.includes("lumen"), false);
  assert.equal(T.HAPPY.includes("gel"), false);

  assert.equal(T.TRICKS.includes("anchor"), false);
  assert.equal(T.TRICKS.includes("rise"), false);
  assert.equal(T.TRICKS.includes("drift"), false);
  assert.equal(T.TRICKS.includes("hover"), false);
  assert.equal(T.TRICKS.includes("mantle"), false);
  assert.equal(T.TRICKS.includes("jet"), false);
  assert.equal(T.TRICKS.includes("veil"), false);
  assert.equal(T.TRICKS.includes("bone"), false);
  assert.equal(T.TRICKS.includes("spiral"), false);
  assert.equal(T.TRICKS.includes("fringe"), false);
  assert.equal(T.TRICKS.includes("nacre"), false);
  assert.equal(T.TRICKS.includes("gulp"), false);
  assert.equal(T.TRICKS.includes("flare"), false);
  assert.equal(T.TRICKS.includes("dart"), false);
  assert.equal(T.TRICKS.includes("soak"), false);
  assert.equal(T.TRICKS.includes("gill"), false);
  assert.equal(T.TRICKS.includes("hood"), false);
  assert.equal(Overlay.TRICKS.includes("hitch"), false);
  assert.equal(Overlay.TRICKS.includes("anchor"), false);
  assert.equal(Overlay.TRICKS.includes("plow"), false);
  assert.equal(Overlay.TRICKS.includes("plow"), false);
  assert.equal(Overlay.TRICKS.includes("bell"), false);
  assert.equal(Overlay.HAPPY.includes("damp"), false);
  assert.equal(Overlay.HAPPY.includes("keep"), false);
  assert.equal(Overlay.HAPPY.includes("ripple"), false);
  assert.equal(Overlay.HAPPY.includes("chamber"), false);
  assert.equal(Overlay.HAPPY.includes("pulse"), false);
  assert.equal(Overlay.HAPPY.includes("bubble"), false);
  assert.equal(Overlay.HAPPY.includes("glow"), false);
  assert.deepEqual([...Overlay.TRICKS], ["coil", "buoy", "siphon", "swivel", "pouch", "dorsal", "pectoral"]);
  assert.deepEqual([...Overlay.HAPPY], ["coronet", "pipe", "moor"]);
});

test("coil/buoy/siphon/swivel/pouch/dorsal/pectoral are house-seahorse-true, not copies of prior guests", () => {
  const ground = { asleep: false, hidden: false, leaving: false, cmd: "idle" };
  const coil = T.beginTrick("coil", 80, 1);
  assert.equal(coil.anim, "sit");
  assert.equal(coil.phase, "hold");
  const held = T.stepTrick(coil, 5, ground);
  assert.equal(held.phase, "hold");
  assert.equal(held.anim, "sit");
  assert.ok(held.rot !== 0 || held.lift > 0);
  const release = T.stepTrick(coil, T.COIL_HOLD + 0.2, ground);
  assert.equal(release.phase, "release");
  assert.equal(release.anim, "sit");
  const doneCarapace = T.stepTrick(coil, T.DUR.coil + 0.1, ground);
  assert.equal(doneCarapace.phase, "done");
  assert.ok(T.nextTrickWait(true, 0, "coil") > T.nextTrickWait(true, 0, "swivel"));
  const buoy = T.beginTrick("buoy", 80, 1);
  assert.equal(buoy.anim, "play");
  const buoyMid = T.stepTrick(buoy, 0.5, ground);
  assert.ok(Math.abs(buoyMid.lift) > 0.05 || Math.abs(buoyMid.rot) > 1 || Math.abs(buoyMid.x - 80) > 0.05);
  const siphon = T.beginTrick("siphon", 80, 1);
  assert.equal(siphon.anim, "talk");
  const siphonMid = T.stepTrick(siphon, 0.5, ground);
  assert.ok(Math.abs(siphonMid.lift) > 0.05 || Math.abs(siphonMid.rot) > 1 || Math.abs(siphonMid.x - 80) > 0.05);
  const swivel = T.beginTrick("swivel", 80, 1);
  assert.equal(swivel.anim, "talk");
  const swivelMid = T.stepTrick(swivel, 0.5, ground);
  assert.ok(Math.abs(swivelMid.lift) > 0.05 || Math.abs(swivelMid.rot) > 1 || Math.abs(swivelMid.x - 80) > 0.05);
  const pouch = T.beginTrick("pouch", 80, 1);
  assert.equal(pouch.anim, "sit");
  const pouchMid = T.stepTrick(pouch, 0.5, ground);
  assert.ok(Math.abs(pouchMid.lift) > 0.05 || Math.abs(pouchMid.rot) > 1 || Math.abs(pouchMid.x - 80) > 0.05);
  const dorsal = T.beginTrick("dorsal", 80, 1);
  assert.equal(dorsal.anim, "walk");
  const dorsalMid = T.stepTrick(dorsal, T.DUR.dorsal * 0.4, ground);
  assert.ok(Math.abs(dorsalMid.lift) > 0.05 || Math.abs(dorsalMid.rot) > 1 || Math.abs(dorsalMid.x - 80) > 0.05);
  const pectoral = T.beginTrick("pectoral", 80, 1);
  assert.equal(pectoral.anim, "talk");
  const pectoralMid = T.stepTrick(pectoral, T.DUR.pectoral * 0.4, ground);
  assert.ok(Math.abs(pectoralMid.lift) > 0.05 || Math.abs(pectoralMid.rot) > 1 || Math.abs(pectoralMid.x - 80) > 0.05);
  const swivelDone = T.stepTrick(swivel, T.DUR.swivel + 0.1, ground);
  assert.equal(swivelDone.phase, "done");
  const aborted = T.stepTrick(held, 0.1, { asleep: true, cmd: "sleep" });
  assert.equal(aborted.phase, "done");
  for (const mod of [Rui, Cat, Dog, Rabbit, Hamster, GuineaPig, Turtle, Goldfish, Budgie, Fox, Penguin, Parrot, Ferret, Hedgehog, Chinchilla, Axolotl, Toucan, Iguana, Dragon, Phoenix, BallPython, CornSnake, Kingsnake, GreenTreePython, Hognose, Garter, Boa, MilkSnake, RosyBoa, CarpetPython, Octopus, Cuttlefish, Nautilus, MoonJelly, SeaStar, HermitCrab, HorseshoeCrab, Relay, Fuse, Earth]) {
    assert.equal(mod.TRICKS.includes("coil"), false);
    assert.equal(mod.TRICKS.includes("buoy"), false);
    assert.equal(mod.TRICKS.includes("siphon"), false);
    assert.equal(mod.TRICKS.includes("swivel"), false);
    assert.equal(mod.TRICKS.includes("pouch"), false);
    assert.equal(mod.TRICKS.includes("dorsal"), false);
    assert.equal(mod.TRICKS.includes("pectoral"), false);
  }
  assert.deepEqual([...Turtle.TRICKS], ["soak", "tuck", "crane", "plod", "paddle", "snorkel", "wipe"]);
  assert.deepEqual([...Goldfish.TRICKS], ["drift", "gulp", "flare", "glint", "dart", "yawn", "forage"]);
  assert.deepEqual([...Axolotl.TRICKS], ["gill", "amble", "mend", "smile", "plume", "sprout", "glop"]);
  assert.deepEqual([...Octopus.TRICKS], ["mantle", "sucker", "jet", "veil", "tinker", "papilla", "ooze"]);
  assert.deepEqual([...Cuttlefish.TRICKS], ["bone", "pupil", "chroma", "hover", "blot", "strike", "zebra"]);
  assert.deepEqual([...Nautilus.TRICKS], ["spiral", "siphuncle", "nacre", "pinhole", "fringe", "hyponome", "aperture"]);
  assert.deepEqual([...CarpetPython.TRICKS], ["legend", "rung", "contour", "runner", "bearing", "canopy", "inset"]);
  assert.equal(T.TRICKS.includes("chime"), false);
  assert.equal(T.TRICKS.includes("pulse"), false);
  assert.equal(T.TRICKS.includes("drift"), false);
  assert.equal(T.TRICKS.includes("jet"), false);
  assert.equal(T.TRICKS.includes("mantle"), false);
  assert.equal(T.TRICKS.includes("bone"), false);
  assert.equal(T.TRICKS.includes("spiral"), false);
  assert.equal(T.TRICKS.includes("hover"), false);
  assert.equal(T.TRICKS.includes("fringe"), false);
  assert.equal(T.TRICKS.includes("hood"), false);
  assert.equal(Cuttlefish.TRICKS.includes("bone"), true);
  assert.equal(Octopus.TRICKS.includes("jet"), true);
  assert.equal(Nautilus.TRICKS.includes("spiral"), true);
  assert.equal(Goldfish.TRICKS.includes("drift"), true);
  assert.equal(Fuse.HAPPY.includes("pulse"), true);
  assert.equal(T.TRICKS.includes("podia"), false);
  assert.equal(T.TRICKS.includes("righting"), false);
  assert.equal(T.TRICKS.includes("crawl"), false);
  assert.equal(T.TRICKS.includes("evert"), false);
  assert.equal(T.TRICKS.includes("penta"), false);
  assert.equal(T.TRICKS.includes("scurry"), false);
  assert.equal(T.TRICKS.includes("nest"), false);
  assert.equal(T.TRICKS.includes("cheek"), false);
  assert.equal(T.TRICKS.includes("curl"), false);
  assert.equal(T.TRICKS.includes("tuck"), false);
  assert.equal(T.TRICKS.includes("hitch"), false);
  assert.equal(T.TRICKS.includes("plow"), false);
  assert.equal(T.TRICKS.includes("plow"), false);
  assert.equal(T.TRICKS.includes("swap"), false);
  assert.equal(T.TRICKS.includes("withdraw"), false);
  assert.equal(T.TRICKS.includes("vacancy"), false);
  assert.equal(T.TRICKS.includes("antenna"), false);
  assert.equal(T.TRICKS.includes("scuttle"), false);
  assert.equal(T.HAPPY.includes("halo"), false);
  assert.equal(T.HAPPY.includes("lumen"), false);
  assert.equal(T.HAPPY.includes("gel"), false);

  assert.equal(T.TRICKS.includes("trade"), false);
  assert.equal(T.HAPPY.includes("damp"), false);
  assert.equal(T.HAPPY.includes("press"), false);
  assert.equal(T.HAPPY.includes("tide"), false);
  assert.equal(T.HAPPY.includes("tap"), false);
  assert.deepEqual([...Hamster.TRICKS], ["nest", "cheek", "scurry", "pocket", "reel", "scrub", "seed"]);
  assert.deepEqual([...Hedgehog.TRICKS], ["curl", "snuffle", "anoint", "bristle", "root", "trundle", "wheel"]);
  assert.deepEqual([...SeaStar.TRICKS], ["podia", "righting", "crawl", "evert", "penta", "madre", "papula"]);
  assert.deepEqual([...HermitCrab.TRICKS], ["swap", "antenna", "scuttle", "withdraw", "vacancy", "chela", "bailer"]);
  assert.deepEqual([...HorseshoeCrab.TRICKS], ["carapace", "bookgill", "telson", "furrow", "fossil", "pusher", "ocular"]);
  assert.equal(SeaStar.TRICKS.includes("podia"), true);
  assert.equal(HermitCrab.TRICKS.includes("swap"), true);
  assert.equal(Hamster.TRICKS.includes("scurry"), true);
  assert.equal(Hedgehog.TRICKS.includes("curl"), true);
});

test("Anchor feed-happy is its own sit: coronet/pipe/moor, and two feeds are not the same", () => {
  assert.deepEqual([...T.HAPPY], ["coronet", "pipe", "moor"]);
  assert.equal(T.HAPPY.includes("halo"), false);
  assert.equal(T.HAPPY.includes("lumen"), false);
  assert.equal(T.HAPPY.includes("gel"), false);
  assert.equal(T.HAPPY.includes("bubble"), false);
  assert.equal(T.HAPPY.includes("munch"), false);
  assert.equal(T.HAPPY.includes("wink"), false);
  assert.equal(T.HAPPY.includes("keep"), false);
  assert.equal(T.HAPPY.includes("tint"), false);
  assert.equal(T.HAPPY.includes("squeeze"), false);
  assert.equal(T.HAPPY.includes("ripple"), false);
  assert.equal(T.HAPPY.includes("glance"), false);
  assert.equal(T.HAPPY.includes("dab"), false);
  assert.equal(T.HAPPY.includes("chamber"), false);
  assert.equal(T.HAPPY.includes("pearl"), false);
  assert.equal(T.HAPPY.includes("quiet"), false);
  assert.equal(T.HAPPY.includes("pulse"), false);
  assert.equal(T.HAPPY.includes("glow"), false);
  assert.equal(T.HAPPY.includes("tribute"), false);
  assert.equal(T.pickHappy("coronet", 0), "pipe");
  assert.notEqual(T.pickHappy("coronet", 0.9), "coronet");
  assert.equal(Overlay.pickHappy("pipe", 0) !== "pipe", true);
  assert.equal(T.happyCanStart({ asleep: false, hidden: false, leaving: false, cmd: "idle" }), true);
  assert.equal(T.happyCanStart({ asleep: false, hidden: false, leaving: false, cmd: "idle", card: true }), true);
  assert.equal(T.happyCanStart({ asleep: true, hidden: false, leaving: false, cmd: "idle" }), false);
  assert.equal(T.happyShouldAbort({ cmd: "sleep" }), true);
  assert.equal(T.happyShouldAbort({ cmd: "hide" }), true);
  assert.equal(T.happyShouldAbort({ card: true, cmd: "idle" }), false);
  const coronetH = T.beginHappy("coronet", 80, 1);
  assert.equal(coronetH.anim, "talk");
  const coronetMid = T.stepHappy(coronetH, 0.4, { cmd: "idle" });
  assert.ok(coronetMid.lift !== 0 || Math.abs(coronetMid.rot) > 0.5);
  assert.notEqual(coronetMid.phase, "done");
  const pipeH = T.beginHappy("pipe", 80, 1);
  assert.equal(pipeH.anim, "play");
  const pipeMid = T.stepHappy(pipeH, 0.3, { cmd: "idle" });
  assert.ok(pipeMid.lift > 0.2 || Math.abs(pipeMid.rot) > 0.5);
  const moorH = T.beginHappy("moor", 80, 1);
  assert.equal(moorH.anim, "sit");
  const done = T.stepHappy(coronetH, T.HAPPY_DUR.coronet + 0.1, { cmd: "idle" });
  assert.equal(done.phase, "done");
  const aborted = T.stepHappy(pipeMid, 0.1, { asleep: true, cmd: "sleep" });
  assert.equal(aborted.phase, "done");
  assert.equal(aborted.abort, true);
  assert.equal(T.wantsThankYou("seahorse"), true);
  assert.equal(T.wantsThankYou("anchor"), true);
  assert.equal(T.wantsThankYou("moon_jelly"), false);
  assert.equal(T.wantsThankYou("sea_star"), false);
  assert.equal(T.wantsThankYou("cling"), false);
  assert.equal(T.wantsThankYou("hermit_crab"), false);
  assert.equal(T.wantsThankYou("tenant"), false);
  assert.equal(T.wantsThankYou("hamster"), false);
  assert.equal(T.wantsThankYou("clip"), false);
  assert.equal(T.wantsThankYou("hedgehog"), false);
  assert.equal(T.wantsThankYou("burr"), false);
  assert.equal(T.wantsThankYou("pulse"), false);
  assert.equal(T.wantsThankYou("nautilus"), false);
  assert.equal(T.wantsThankYou("chamber"), false);
  assert.equal(T.wantsThankYou("cuttlefish"), false);
  assert.equal(T.wantsThankYou("sepia"), false);
  assert.equal(T.wantsThankYou("octopus"), false);
  assert.equal(T.wantsThankYou("cup"), false);
  assert.equal(T.wantsThankYou("goldfish"), false);
  assert.equal(T.wantsThankYou("coin"), false);
  assert.equal(T.wantsThankYou("turtle"), false);
  assert.equal(T.wantsThankYou("axolotl"), false);
  const thanks = T.startThankYou("seahorse", "coronet", 80, 1, { cmd: "idle", card: true, windowPlay: true });
  assert.ok(thanks);
  assert.notEqual(thanks.kind, "coronet");
  assert.ok(thanks.happy.lift === 0);
  assert.notEqual(thanks.happy.anim, "eat");
  assert.notEqual(thanks.happy.anim, "idle");
  const thanksMid = T.stepHappy(thanks.happy, 0.35, { cmd: "idle", card: true });
  assert.ok(thanksMid.lift !== 0 || Math.abs(thanksMid.rot) > 0.5, "a thank-you coronets or pipes");
  const blocked = T.startThankYou("seahorse", "tribute", 80, 1, { asleep: true, cmd: "idle" });
  assert.equal(blocked, null);
  const other = T.startThankYou("moon_jelly", null, 80, 1, { cmd: "idle" });
  assert.equal(other, null);
  const second = T.startThankYou("seahorse", thanks.kind, 80, 1, { cmd: "idle", card: true });
  assert.ok(second);
  assert.notEqual(second.kind, thanks.kind);
});

test("ground registry keeps prior guests gated; Anchor selectable; prior guests still OK", () => {
  assert.equal(Rui.TRICK_KEY, "red_panda");
  assert.equal(Turtle.TRICK_KEY, "turtle");
  assert.equal(Goldfish.TRICK_KEY, "goldfish");
  assert.equal(Axolotl.TRICK_KEY, "axolotl");
  assert.equal(Octopus.TRICK_KEY, "octopus");
  assert.equal(Cuttlefish.TRICK_KEY, "cuttlefish");
  assert.equal(Nautilus.TRICK_KEY, "nautilus");
  assert.equal(CarpetPython.TRICK_KEY, "carpet_python");
  assert.equal(SeaStar.TRICK_KEY, "sea_star");
  assert.equal(HermitCrab.TRICK_KEY, "hermit_crab");
  assert.equal(HorseshoeCrab.TRICK_KEY, "horseshoe_crab");
  assert.equal(T.TRICK_KEY, "seahorse");
  assert.deepEqual([...Turtle.TRICKS], ["soak", "tuck", "crane", "plod", "paddle", "snorkel", "wipe"]);
  assert.deepEqual([...Goldfish.TRICKS], ["drift", "gulp", "flare", "glint", "dart", "yawn", "forage"]);
  assert.deepEqual([...Axolotl.TRICKS], ["gill", "amble", "mend", "smile", "plume", "sprout", "glop"]);
  assert.deepEqual([...Octopus.TRICKS], ["mantle", "sucker", "jet", "veil", "tinker", "papilla", "ooze"]);
  assert.deepEqual([...Cuttlefish.TRICKS], ["bone", "pupil", "chroma", "hover", "blot", "strike", "zebra"]);
  assert.deepEqual([...Nautilus.TRICKS], ["spiral", "siphuncle", "nacre", "pinhole", "fringe", "hyponome", "aperture"]);
  assert.deepEqual([...CarpetPython.TRICKS], ["legend", "rung", "contour", "runner", "bearing", "canopy", "inset"]);
  assert.deepEqual([...SeaStar.TRICKS], ["podia", "righting", "crawl", "evert", "penta", "madre", "papula"]);
  assert.deepEqual([...HermitCrab.TRICKS], ["swap", "antenna", "scuttle", "withdraw", "vacancy", "chela", "bailer"]);
  assert.deepEqual([...T.TRICKS], ["coil", "buoy", "siphon", "swivel", "pouch", "dorsal", "pectoral"]);
  assert.equal(T.wantsThankYou("seahorse"), true);
  assert.equal(T.wantsThankYou("anchor"), true);
  assert.equal(Turtle.wantsThankYou("ink"), true);
  assert.equal(Goldfish.wantsThankYou("coin"), true);
  assert.equal(Axolotl.wantsThankYou("bloom"), true);
  assert.equal(Octopus.wantsThankYou("cup"), true);
  assert.equal(Cuttlefish.wantsThankYou("sepia"), true);
  assert.equal(Nautilus.wantsThankYou("chamber"), true);
  assert.equal(Rui.sleepHoldFrame("red_panda", 4), 1);
  assert.equal(T.sleepHoldFrame("seahorse", 4), null);
  globalThis.PetRuiTricks = OverlayRui;
  globalThis.PetRelayTricks = OverlayRelay;
  globalThis.PetFuseTricks = OverlayFuse;
  globalThis.PetEarthTricks = OverlayEarth;
  globalThis.PetCatTricks = OverlayCat;
  globalThis.PetDogTricks = OverlayDog;
  globalThis.PetRabbitTricks = OverlayRabbit;
  globalThis.PetHamsterTricks = OverlayHamster;
  globalThis.PetGuineaPigTricks = OverlayGuineaPig;
  globalThis.PetTurtleTricks = OverlayTurtle;
  globalThis.PetGoldfishTricks = OverlayGoldfish;
  globalThis.PetBudgieTricks = OverlayBudgie;
  globalThis.PetFoxTricks = OverlayFox;
  globalThis.PetPenguinTricks = OverlayPenguin;
  globalThis.PetParrotTricks = OverlayParrot;
  globalThis.PetFerretTricks = OverlayFerret;
  globalThis.PetHedgehogTricks = OverlayHedgehog;
  globalThis.PetChinchillaTricks = OverlayChinchilla;
  globalThis.PetAxolotlTricks = OverlayAxolotl;
  globalThis.PetToucanTricks = OverlayToucan;
  globalThis.PetIguanaTricks = OverlayIguana;
  globalThis.PetDragonTricks = OverlayDragon;
  globalThis.PetPhoenixTricks = OverlayPhoenix;
  globalThis.PetBallPythonTricks = OverlayBallPython;
  globalThis.PetCornSnakeTricks = OverlayCornSnake;
  globalThis.PetKingsnakeTricks = OverlayKingsnake;
  globalThis.PetGreenTreePythonTricks = OverlayGreenTreePython;
  globalThis.PetHognoseTricks = OverlayHognose;
  globalThis.PetGarterTricks = OverlayGarter;
  globalThis.PetBoaTricks = OverlayBoa;
  globalThis.PetMilkSnakeTricks = OverlayMilkSnake;
  globalThis.PetRosyBoaTricks = OverlayRosyBoa;
  globalThis.PetCarpetPythonTricks = OverlayCarpetPython;
  globalThis.PetOctopusTricks = OverlayOctopus;
  globalThis.PetCuttlefishTricks = OverlayCuttlefish;
  globalThis.PetNautilusTricks = OverlayNautilus;
  globalThis.PetMoonJellyTricks = OverlayMoonJelly;
  globalThis.PetSeaStarTricks = OverlaySeaStar;
  globalThis.PetHermitCrabTricks = OverlayHermitCrab;
  globalThis.PetHorseshoeCrabTricks = OverlayHorseshoeCrab;
  globalThis.PetSeahorseTricks = Overlay;
  assert.equal(OverlayGround.tricksFor("red_panda"), OverlayRui);
  assert.equal(OverlayGround.tricksFor("rui"), OverlayRui);
  assert.equal(OverlayGround.tricksFor("turtle"), OverlayTurtle);
  assert.equal(OverlayGround.tricksFor("ink"), OverlayTurtle);
  assert.equal(OverlayGround.tricksFor("goldfish"), OverlayGoldfish);
  assert.equal(OverlayGround.tricksFor("coin"), OverlayGoldfish);
  assert.equal(OverlayGround.tricksFor("axolotl"), OverlayAxolotl);
  assert.equal(OverlayGround.tricksFor("bloom"), OverlayAxolotl);
  assert.equal(OverlayGround.tricksFor("octopus"), OverlayOctopus);
  assert.equal(OverlayGround.tricksFor("cup"), OverlayOctopus);
  assert.equal(OverlayGround.tricksFor("cuttlefish"), OverlayCuttlefish);
  assert.equal(OverlayGround.tricksFor("sepia"), OverlayCuttlefish);
  assert.equal(OverlayGround.tricksFor("nautilus"), OverlayNautilus);
  assert.equal(OverlayGround.tricksFor("chamber"), OverlayNautilus);
  assert.equal(OverlayGround.tricksFor("carpet_python"), OverlayCarpetPython);
  assert.equal(OverlayGround.tricksFor("atlas"), OverlayCarpetPython);
  assert.equal(OverlayGround.tricksFor("moon_jelly"), OverlayMoonJelly);
  assert.equal(OverlayGround.tricksFor("pulse"), OverlayMoonJelly);
  assert.equal(OverlayGround.tricksFor("sea_star"), OverlaySeaStar);
  assert.equal(OverlayGround.tricksFor("cling"), OverlaySeaStar);
  assert.equal(OverlayGround.tricksFor("hermit_crab"), OverlayHermitCrab);
  assert.equal(OverlayGround.tricksFor("tenant"), OverlayHermitCrab);
  assert.equal(OverlayGround.tricksFor("horseshoe_crab"), OverlayHorseshoeCrab);
  assert.equal(OverlayGround.tricksFor("ledger"), OverlayHorseshoeCrab);
  assert.equal(OverlayGround.tricksFor("seahorse"), Overlay);
  assert.equal(OverlayGround.tricksFor("anchor"), Overlay);
  assert.equal(OverlayGround.wantsThankYou("turtle"), true);
  assert.equal(OverlayGround.wantsThankYou("ink"), true);
  assert.equal(OverlayGround.wantsThankYou("goldfish"), true);
  assert.equal(OverlayGround.wantsThankYou("coin"), true);
  assert.equal(OverlayGround.wantsThankYou("axolotl"), true);
  assert.equal(OverlayGround.wantsThankYou("bloom"), true);
  assert.equal(OverlayGround.wantsThankYou("octopus"), true);
  assert.equal(OverlayGround.wantsThankYou("cup"), true);
  assert.equal(OverlayGround.wantsThankYou("cuttlefish"), true);
  assert.equal(OverlayGround.wantsThankYou("sepia"), true);
  assert.equal(OverlayGround.wantsThankYou("nautilus"), true);
  assert.equal(OverlayGround.wantsThankYou("chamber"), true);
  assert.equal(OverlayGround.wantsThankYou("carpet_python"), true);
  assert.equal(OverlayGround.wantsThankYou("atlas"), true);
  assert.equal(OverlayGround.wantsThankYou("moon_jelly"), true);
  assert.equal(OverlayGround.wantsThankYou("pulse"), true);
  assert.equal(OverlayGround.wantsThankYou("sea_star"), true);
  assert.equal(OverlayGround.wantsThankYou("cling"), true);
  assert.equal(OverlayGround.wantsThankYou("hermit_crab"), true);
  assert.equal(OverlayGround.wantsThankYou("tenant"), true);
  assert.equal(OverlayGround.wantsThankYou("horseshoe_crab"), true);
  assert.equal(OverlayGround.wantsThankYou("ledger"), true);
  assert.equal(OverlayGround.wantsThankYou("seahorse"), true);
  assert.equal(OverlayGround.wantsThankYou("anchor"), true);
  assert.equal(OverlayGround.wantsThankYou("hamster"), true);
  assert.equal(OverlayGround.wantsThankYou("clip"), true);
  assert.equal(OverlayGround.wantsThankYou("hedgehog"), true);
  assert.equal(OverlayGround.wantsThankYou("burr"), true);
  assert.equal(OverlayGround.sleepHoldFrame("red_panda", 4), 1);
  assert.equal(OverlayGround.sleepHoldFrame("moon_jelly", 4), null);
  assert.deepEqual([...OverlayTurtle.TRICKS], ["soak", "tuck", "crane", "plod", "paddle", "snorkel", "wipe"]);
  assert.deepEqual([...OverlayGoldfish.TRICKS], ["drift", "gulp", "flare", "glint", "dart", "yawn", "forage"]);
  assert.deepEqual([...OverlayAxolotl.TRICKS], ["gill", "amble", "mend", "smile", "plume", "sprout", "glop"]);
  assert.deepEqual([...OverlayOctopus.TRICKS], ["mantle", "sucker", "jet", "veil", "tinker", "papilla", "ooze"]);
  assert.deepEqual([...OverlayCuttlefish.TRICKS], ["bone", "pupil", "chroma", "hover", "blot", "strike", "zebra"]);
  assert.deepEqual([...OverlayNautilus.TRICKS], ["spiral", "siphuncle", "nacre", "pinhole", "fringe", "hyponome", "aperture"]);
  assert.deepEqual([...OverlaySeaStar.TRICKS], ["podia", "righting", "crawl", "evert", "penta", "madre", "papula"]);
  assert.deepEqual([...OverlayHermitCrab.TRICKS], ["swap", "antenna", "scuttle", "withdraw", "vacancy", "chela", "bailer"]);
  assert.deepEqual([...OverlayHorseshoeCrab.TRICKS], ["carapace", "bookgill", "telson", "furrow", "fossil", "pusher", "ocular"]);
  assert.deepEqual([...OverlayCarpetPython.TRICKS], ["legend", "rung", "contour", "runner", "bearing", "canopy", "inset"]);
  assert.deepEqual([...Overlay.TRICKS], ["coil", "buoy", "siphon", "swivel", "pouch", "dorsal", "pectoral"]);
  assert.equal(Overlay.TRICKS.includes("hitch"), false);
  assert.equal(Overlay.TRICKS.includes("anchor"), false);
  assert.equal(Overlay.TRICKS.includes("plow"), false);
  assert.equal(Overlay.TRICKS.includes("plow"), false);
  assert.equal(Overlay.TRICKS.includes("bell"), false);
  assert.equal(Overlay.TRICKS.includes("drift"), false);
  assert.equal(Overlay.TRICKS.includes("jet"), false);
  assert.equal(Overlay.TRICKS.includes("mantle"), false);
  assert.equal(Overlay.TRICKS.includes("bone"), false);
  assert.equal(Overlay.TRICKS.includes("spiral"), false);
  assert.equal(Overlay.TRICKS.includes("tuck"), false);
  assert.equal(Overlay.TRICKS.includes("gill"), false);
  assert.equal(Overlay.TRICKS.includes("legend"), false);
  assert.equal(Overlay.TRICKS.includes("podia"), false);
  assert.equal(Overlay.TRICKS.includes("scurry"), false);
  assert.equal(Overlay.TRICKS.includes("curl"), false);
  assert.equal(Overlay.TRICKS.includes("hitch"), false);
  assert.equal(Overlay.TRICKS.includes("trade"), false);
  assert.deepEqual([...OverlayHamster.TRICKS], ["nest", "cheek", "scurry", "pocket", "reel", "scrub", "seed"]);
  assert.deepEqual([...OverlayHedgehog.TRICKS], ["curl", "snuffle", "anoint", "bristle", "root", "trundle", "wheel"]);
  assert.deepEqual([...OverlaySeaStar.TRICKS], ["podia", "righting", "crawl", "evert", "penta", "madre", "papula"]);
});


test("ultra-polish: Anchor coil/dorsal/pectoral lifts are Rui-visible (not micro idle-gen)", () => {
  const coil = T.beginTrick("coil", 80, 1);
  const mid = T.stepTrick(coil, 5, { cmd: "idle" });
  assert.ok(Math.abs(mid.rot) > 10, `coil mid rot ${mid.rot}`);
  assert.ok(Math.abs(mid.lift) > 0.5, `coil mid lift ${mid.lift}`);
  const du = T.beginTrick("dorsal", 80, 1);
  const d2 = T.stepTrick(du, T.DUR.dorsal * 0.4, { cmd: "idle" });
  assert.ok(d2.lift > 2 || Math.abs(d2.rot) > 4 || Math.abs(d2.x - 80) > 1, `dorsal mid ${d2.lift}/${d2.rot}/${d2.x}`);
  const pe = T.beginTrick("pectoral", 80, 1);
  const p2 = T.stepTrick(pe, T.DUR.pectoral * 0.4, { cmd: "idle" });
  assert.ok(p2.lift > 2 || Math.abs(p2.rot) > 8 || Math.abs(p2.x - 80) > 0.3, `pectoral mid ${p2.lift}/${p2.rot}/${p2.x}`);
  const bu = T.beginTrick("buoy", 80, 1);
  const b2 = T.stepTrick(bu, T.DUR.buoy * 0.4, { cmd: "idle" });
  assert.ok(b2.lift > 0.5 || Math.abs(b2.rot) > 4 || Math.abs(b2.x - 80) > 0.5, `buoy mid ${b2.lift}/${b2.rot}/${b2.x}`);
  assert.ok(Overlay.dorsalPose && Overlay.pectoralPose);
  assert.deepEqual([...T.TRICKS], [...Overlay.TRICKS]);
});

test("notes: Anchor idle-life ultra done; next house-order ultra guest is Kite / manta (birds Soot→Ember + Miso + Pip + Thimble + Clip + Whee + Ink + Coin + Rue + Wick + Burr + Floss + Bloom + Sol + Vesper + Nori + Saffron + Bandit + Jade + Bluff + Sash + Lula + Coral + Blush + Atlas + Cup + Sepia + Chamber + Pulse + Ochre + Tenant + Ledger + Anchor already ultra; Echo/budgie + Peck/penguin + Quill/parrot + Keel/toucan + Ember skip bird)", () => {
  assert.equal(T.TRICK_KEY, "seahorse");
  assert.equal(T.wantsThankYou("anchor"), true);
  assert.equal(OverlayGround.tricksFor("seahorse"), Overlay);
  assert.equal(OverlayGround.tricksFor("anchor"), Overlay);
  assert.equal(OverlayGround.wantsThankYou("seahorse"), true);
  assert.equal(OverlayGround.wantsThankYou("anchor"), true);
  assert.equal(OverlayGround.tricksFor("hermit_crab"), OverlayHermitCrab);
  assert.equal(OverlayGround.tricksFor("tenant"), OverlayHermitCrab);
  assert.equal(OverlayGround.wantsThankYou("hermit_crab"), true);
  assert.equal(OverlayGround.wantsThankYou("tenant"), true);
  assert.equal(OverlayGround.tricksFor("sea_star"), OverlaySeaStar);
  assert.equal(OverlayGround.tricksFor("cling"), OverlaySeaStar);
  assert.equal(OverlayGround.tricksFor("moon_jelly"), OverlayMoonJelly);
  assert.equal(OverlayGround.tricksFor("pulse"), OverlayMoonJelly);
  assert.equal(OverlayGround.tricksFor("nautilus"), OverlayNautilus);
  assert.equal(OverlayGround.tricksFor("chamber"), OverlayNautilus);
  assert.equal(OverlayGround.tricksFor("cuttlefish"), OverlayCuttlefish);
  assert.equal(OverlayGround.tricksFor("sepia"), OverlayCuttlefish);
  assert.equal(OverlayGround.tricksFor("octopus"), OverlayOctopus);
  assert.equal(OverlayGround.tricksFor("cup"), OverlayOctopus);
  assert.equal(OverlayGround.tricksFor("carpet_python"), OverlayCarpetPython);
  assert.equal(OverlayGround.tricksFor("atlas"), OverlayCarpetPython);
  assert.equal(OverlayGround.tricksFor("turtle"), OverlayTurtle);
  assert.equal(OverlayGround.tricksFor("ink"), OverlayTurtle);
  assert.equal(OverlayGround.tricksFor("goldfish"), OverlayGoldfish);
  assert.equal(OverlayGround.tricksFor("coin"), OverlayGoldfish);
  assert.equal(OverlayGround.tricksFor("axolotl"), OverlayAxolotl);
  assert.equal(OverlayGround.tricksFor("bloom"), OverlayAxolotl);
  assert.equal(OverlayGround.tricksFor("hamster"), OverlayHamster);
  assert.equal(OverlayGround.tricksFor("clip"), OverlayHamster);
  assert.equal(OverlayGround.tricksFor("hedgehog"), OverlayHedgehog);
  assert.equal(OverlayGround.tricksFor("burr"), OverlayHedgehog);
  assert.equal(OverlayGround.tricksFor("horseshoe_crab"), OverlayHorseshoeCrab);
  assert.equal(OverlayGround.tricksFor("ledger"), OverlayHorseshoeCrab);
  assert.equal(OverlayGround.wantsThankYou("horseshoe_crab"), true);
  assert.equal(OverlayGround.wantsThankYou("ledger"), true);
  assert.equal(OverlayGround.tricksFor("seahorse"), Overlay);
  assert.equal(OverlayGround.wantsThankYou("seahorse"), true);
  assert.equal(OverlayGround.tricksFor("anchor"), Overlay);
  assert.equal(OverlayGround.wantsThankYou("anchor"), true);
  assert.equal(OverlayGround.tricksFor("manta") == null, true);
  assert.equal(OverlayGround.wantsThankYou("manta"), false);
  assert.equal(OverlayGround.tricksFor("kite") == null, true);
  assert.equal(OverlayGround.wantsThankYou("kite"), false);
});
