import assert from "node:assert/strict";
import { createRequire } from "node:module";
import { dirname, join } from "node:path";
import { test } from "node:test";
import { fileURLToPath, pathToFileURL } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const T = await import(pathToFileURL(join(root, "src/lib/pets/toucan-tricks.ts")).href);
const Rui = await import(pathToFileURL(join(root, "src/lib/pets/rui-tricks.ts")).href);
const Relay = await import(pathToFileURL(join(root, "src/lib/pets/relay-tricks.ts")).href);
const Fuse = await import(pathToFileURL(join(root, "src/lib/pets/fuse-tricks.ts")).href);
const Earth = await import(pathToFileURL(join(root, "src/lib/pets/earth-tricks.ts")).href);
const Cat = await import(pathToFileURL(join(root, "src/lib/pets/cat-tricks.ts")).href);
const Dog = await import(pathToFileURL(join(root, "src/lib/pets/dog-tricks.ts")).href);
const Rabbit = await import(pathToFileURL(join(root, "src/lib/pets/rabbit-tricks.ts")).href);
const Hamster = await import(pathToFileURL(join(root, "src/lib/pets/hamster-tricks.ts")).href);
const GuineaPig = await import(pathToFileURL(join(root, "src/lib/pets/guinea-pig-tricks.ts")).href);
const Turtle = await import(pathToFileURL(join(root, "src/lib/pets/turtle-tricks.ts")).href);
const Goldfish = await import(pathToFileURL(join(root, "src/lib/pets/goldfish-tricks.ts")).href);
const Budgie = await import(pathToFileURL(join(root, "src/lib/pets/budgie-tricks.ts")).href);
const Fox = await import(pathToFileURL(join(root, "src/lib/pets/fox-tricks.ts")).href);
const Penguin = await import(pathToFileURL(join(root, "src/lib/pets/penguin-tricks.ts")).href);
const Parrot = await import(pathToFileURL(join(root, "src/lib/pets/parrot-tricks.ts")).href);
const Ferret = await import(pathToFileURL(join(root, "src/lib/pets/ferret-tricks.ts")).href);
const Hedgehog = await import(pathToFileURL(join(root, "src/lib/pets/hedgehog-tricks.ts")).href);
const Chinchilla = await import(pathToFileURL(join(root, "src/lib/pets/chinchilla-tricks.ts")).href);
const Axolotl = await import(pathToFileURL(join(root, "src/lib/pets/axolotl-tricks.ts")).href);
const Overlay = createRequire(import.meta.url)(join(root, "../desktop/renderer/toucan-tricks.js"));
const OverlayGround = createRequire(import.meta.url)(join(root, "../desktop/renderer/ground-tricks.js"));
const OverlayRui = createRequire(import.meta.url)(join(root, "../desktop/renderer/rui-tricks.js"));
const OverlayRelay = createRequire(import.meta.url)(join(root, "../desktop/renderer/relay-tricks.js"));
const OverlayFuse = createRequire(import.meta.url)(join(root, "../desktop/renderer/fuse-tricks.js"));
const OverlayEarth = createRequire(import.meta.url)(join(root, "../desktop/renderer/earth-tricks.js"));
const OverlayCat = createRequire(import.meta.url)(join(root, "../desktop/renderer/cat-tricks.js"));
const OverlayDog = createRequire(import.meta.url)(join(root, "../desktop/renderer/dog-tricks.js"));
const OverlayRabbit = createRequire(import.meta.url)(join(root, "../desktop/renderer/rabbit-tricks.js"));
const OverlayHamster = createRequire(import.meta.url)(join(root, "../desktop/renderer/hamster-tricks.js"));
const OverlayGuineaPig = createRequire(import.meta.url)(join(root, "../desktop/renderer/guinea-pig-tricks.js"));
const OverlayTurtle = createRequire(import.meta.url)(join(root, "../desktop/renderer/turtle-tricks.js"));
const OverlayGoldfish = createRequire(import.meta.url)(join(root, "../desktop/renderer/goldfish-tricks.js"));
const OverlayBudgie = createRequire(import.meta.url)(join(root, "../desktop/renderer/budgie-tricks.js"));
const OverlayFox = createRequire(import.meta.url)(join(root, "../desktop/renderer/fox-tricks.js"));
const OverlayPenguin = createRequire(import.meta.url)(join(root, "../desktop/renderer/penguin-tricks.js"));
const OverlayParrot = createRequire(import.meta.url)(join(root, "../desktop/renderer/parrot-tricks.js"));
const OverlayFerret = createRequire(import.meta.url)(join(root, "../desktop/renderer/ferret-tricks.js"));
const OverlayHedgehog = createRequire(import.meta.url)(join(root, "../desktop/renderer/hedgehog-tricks.js"));
const OverlayChinchilla = createRequire(import.meta.url)(join(root, "../desktop/renderer/chinchilla-tricks.js"));
const OverlayAxolotl = createRequire(import.meta.url)(join(root, "../desktop/renderer/axolotl-tricks.js"));
const OverlayIguana = createRequire(import.meta.url)(join(root, "../desktop/renderer/iguana-tricks.js"));
const OverlayDragon = createRequire(import.meta.url)(join(root, "../desktop/renderer/dragon-tricks.js"));
const OverlayPhoenix = createRequire(import.meta.url)(join(root, "../desktop/renderer/phoenix-tricks.js"));

test("Keel tricks start only on idle ground", () => {
  assert.deepEqual([...T.TRICKS], ["roost", "berry", "juggle", "peer", "skip", "rattle", "clatter"]);
  assert.equal(T.canStart({ asleep: false, hidden: false, leaving: false, cmd: "idle" }), true);
  assert.equal(T.canStart({ asleep: true, hidden: false, leaving: false, cmd: "idle" }), false);
  assert.equal(T.canStart({ asleep: false, hidden: true, leaving: false, cmd: "idle" }), false);
  assert.equal(T.canStart({ asleep: false, hidden: false, leaving: false, cmd: "sleep" }), false);
  assert.equal(T.canStart({ asleep: false, hidden: false, leaving: false, cmd: "seek" }), false);
  assert.equal(T.canStart({ asleep: false, hidden: false, leaving: false, cmd: "idle", windowPlay: true }), false);
  assert.equal(T.canStart({ asleep: false, hidden: false, leaving: false, cmd: "idle", card: true }), false);
  assert.equal(T.shouldAbort({ asleep: true, hidden: false, leaving: false, cmd: "idle" }), true);
  assert.equal(T.shouldAbort({ asleep: false, hidden: false, leaving: false, cmd: "idle", card: true }), true);
  assert.equal(T.shouldAbort({ asleep: false, hidden: false, leaving: false, cmd: "idle" }), false);
  assert.equal(T.pickTrick(0.99, true), "roost");
  assert.notEqual(T.pickTrick(0.3, false, "roost"), "roost");
  assert.equal(Overlay.TRICK_KEY, "toucan");
  assert.equal(T.sleepHoldFrame("axolotl", 4), null);
  assert.equal(T.TRICKS.includes("toss"), false);
  assert.equal(T.TRICKS.includes("bill"), false);
  assert.equal(T.TRICKS.includes("flash"), false);
  assert.equal(T.TRICKS.includes("fan"), false);
  assert.equal(T.TRICKS.includes("quote"), false);
  assert.equal(T.TRICKS.includes("strut"), false);
  assert.equal(T.TRICKS.includes("crack"), false);
  assert.equal(T.TRICKS.includes("preen"), false);
  assert.equal(T.TRICKS.includes("beak"), false);
  assert.equal(T.TRICKS.includes("gill"), false);
  assert.equal(T.TRICKS.includes("plume"), false);
  assert.equal(T.TRICKS.includes("ash"), false);
  assert.equal(T.TRICKS.includes("tube"), false);
  assert.equal(T.TRICKS.includes("dig"), false);
  assert.equal(T.TRICKS.includes("potato"), false);
  assert.equal(T.TRICKS.includes("tuck"), false);
  assert.equal(T.TRICKS.includes("loaf"), false);
  assert.equal(T.TRICKS.includes("nest"), false);
  assert.equal(T.TRICKS.includes("scurry"), false);
  assert.equal(T.TRICKS.includes("den"), false);
  assert.equal(T.TRICKS.includes("zoom"), false);
  assert.equal(T.TRICKS.includes("dance"), false);
  assert.equal(T.TRICKS.includes("pounce"), false);
  assert.equal(T.TRICKS.includes("thread"), false);
  assert.equal(T.TRICKS.includes("hook"), false);
  assert.equal(T.TRICKS.includes("perch"), false);
  assert.equal(T.TRICKS.includes("popcorn"), false);
  assert.equal(T.TRICKS.includes("groom"), false);
});

test("roost/berry/juggle/peer/skip/rattle/clatter are house-toucan-true, not Rui cat dog rabbit hamster guinea-pig turtle goldfish budgie fox penguin parrot ferret hedgehog chinchilla axolotl or dragon clones", () => {
  const ground = { asleep: false, hidden: false, leaving: false, cmd: "idle" };
  const roost = T.beginTrick("roost", 80, 1);
  assert.equal(roost.anim, "sit");
  assert.equal(roost.phase, "hold");
  const held = T.stepTrick(roost, 5, ground);
  assert.equal(held.phase, "hold");
  assert.equal(held.anim, "sit");
  assert.ok(held.rot !== 0 || held.lift > 0);
  const release = T.stepTrick(roost, T.ROOST_HOLD + 0.2, ground);
  assert.equal(release.phase, "release");
  assert.equal(release.anim, "sit");
  const doneRoost = T.stepTrick(roost, T.DUR.roost + 0.1, ground);
  assert.equal(doneRoost.phase, "done");
  assert.ok(T.nextTrickWait(true, 0, "roost") > T.nextTrickWait(true, 0, "berry"));
  const berry = T.beginTrick("berry", 80, 1);
  assert.equal(berry.anim, "sit");
  const berryMid = T.stepTrick(berry, 0.55, ground);
  assert.ok(Math.abs(berryMid.lift) > 0.2 || Math.abs(berryMid.rot) > 1);
  const juggle = T.beginTrick("juggle", 80, 1);
  assert.equal(juggle.anim, "play");
  const juggleMid = T.stepTrick(juggle, 0.5, ground);
  assert.ok(Math.abs(juggleMid.lift) > 0.3 || Math.abs(juggleMid.rot) > 1);
  const peer = T.beginTrick("peer", 80, 1);
  assert.equal(peer.anim, "sit");
  const peerMid = T.stepTrick(peer, 0.4, ground);
  assert.ok(Math.abs(peerMid.lift) > 0.2 || Math.abs(peerMid.rot) > 1);
  const skip = T.beginTrick("skip", 80, 1);
  assert.equal(skip.anim, "walk");
  const skipMid = T.stepTrick(skip, 0.5, ground);
  assert.ok(Math.abs(skipMid.x - 80) > 1 || Math.abs(skipMid.lift) > 0.3 || Math.abs(skipMid.rot) > 1);
  const skipDone = T.stepTrick(skip, T.DUR.skip + 0.1, ground);
  assert.equal(skipDone.phase, "done");
  const rattle = T.beginTrick("rattle", 80, 1);
  assert.equal(rattle.anim, "play");
  const rattMid = T.stepTrick(rattle, T.DUR.rattle * 0.4, ground);
  assert.ok(rattMid.lift > 2 || Math.abs(rattMid.rot) > 1);
  const clatter = T.beginTrick("clatter", 80, 1);
  assert.equal(clatter.anim, "sit");
  const clatMid = T.stepTrick(clatter, T.DUR.clatter * 0.4, ground);
  assert.ok(Math.abs(clatMid.lift) > 1 || Math.abs(clatMid.rot) > 1);
  assert.equal(Overlay.TRICKS.includes("rattle"), true);
  assert.equal(Overlay.TRICKS.includes("clatter"), true);
  const aborted = T.stepTrick(held, 0.1, { asleep: true, cmd: "sleep" });
  assert.equal(aborted.phase, "done");
  assert.equal(Rui.TRICKS.includes("roost"), false);
  assert.equal(Cat.TRICKS.includes("berry"), false);
  assert.equal(Dog.TRICKS.includes("juggle"), false);
  assert.equal(Rabbit.TRICKS.includes("peer"), false);
  assert.equal(Hamster.TRICKS.includes("skip"), false);
  assert.equal(GuineaPig.TRICKS.includes("roost"), false);
  assert.equal(Turtle.TRICKS.includes("berry"), false);
  assert.equal(Goldfish.TRICKS.includes("juggle"), false);
  assert.equal(Budgie.TRICKS.includes("peer"), false);
  assert.equal(Fox.TRICKS.includes("skip"), false);
  assert.equal(Penguin.TRICKS.includes("roost"), false);
  assert.equal(Parrot.TRICKS.includes("berry"), false);
  assert.equal(Ferret.TRICKS.includes("juggle"), false);
  assert.equal(Relay.TRICKS.includes("roost"), false);
  assert.equal(Fuse.TRICKS.includes("berry"), false);
  assert.equal(Earth.TRICKS.includes("juggle"), false);
  assert.equal(Hedgehog.TRICKS.includes("roost"), false);
  assert.equal(Chinchilla.TRICKS.includes("berry"), false);
  assert.equal(Axolotl.TRICKS.includes("roost"), false);
  assert.equal(Axolotl.TRICKS.includes("berry"), false);
  assert.equal(Axolotl.TRICKS.includes("juggle"), false);
  assert.equal(Axolotl.TRICKS.includes("peer"), false);
  assert.equal(Axolotl.TRICKS.includes("skip"), false);
  assert.equal(Parrot.TRICKS.includes("flash"), true);
  assert.equal(T.TRICKS.includes("toss"), false);
  assert.equal(T.TRICKS.includes("flash"), false);
  assert.equal(T.TRICKS.includes("fan"), false);
  assert.equal(T.TRICKS.includes("bill"), false);
  assert.equal(T.TRICKS.includes("gill"), false);
});

test("Keel feed-happy is its own sit: clack/yelp/tok, and two feeds are not the same", () => {
  assert.deepEqual([...T.HAPPY], ["clack", "yelp", "tok"]);
  assert.equal(T.HAPPY.includes("spark"), false);
  assert.equal(T.HAPPY.includes("purr"), false);
  assert.equal(T.HAPPY.includes("tail"), false);
  assert.equal(T.HAPPY.includes("tilt"), false);
  assert.equal(T.HAPPY.includes("twitch"), false);
  assert.equal(T.HAPPY.includes("stuff"), false);
  assert.equal(T.HAPPY.includes("peep"), false);
  assert.equal(T.HAPPY.includes("munch"), false);
  assert.equal(T.HAPPY.includes("huff"), false);
  assert.equal(T.HAPPY.includes("gleam"), false);
  assert.equal(T.HAPPY.includes("bubble"), false);
  assert.equal(T.HAPPY.includes("chirp"), false);
  assert.equal(T.HAPPY.includes("chatter"), false);
  assert.equal(T.HAPPY.includes("bob"), false);
  assert.equal(T.HAPPY.includes("whistle"), false);
  assert.equal(T.HAPPY.includes("trill"), false);
  assert.equal(T.HAPPY.includes("ruffle"), false);
  assert.equal(T.HAPPY.includes("yip"), false);
  assert.equal(T.HAPPY.includes("chuff"), false);
  assert.equal(T.HAPPY.includes("nuzzle"), false);
  assert.equal(T.HAPPY.includes("woof"), false);
  assert.equal(T.HAPPY.includes("bray"), false);
  assert.equal(T.HAPPY.includes("beak"), false);
  assert.equal(T.HAPPY.includes("shimmy"), false);
  assert.equal(T.HAPPY.includes("squawk"), false);
  assert.equal(T.HAPPY.includes("bravo"), false);
  assert.equal(T.HAPPY.includes("scissor"), false);
  assert.equal(T.HAPPY.includes("chitter"), false);
  assert.equal(T.HAPPY.includes("bounce"), false);
  assert.equal(T.HAPPY.includes("shuffle"), false);
  assert.equal(T.HAPPY.includes("nibble"), false);
  assert.equal(T.HAPPY.includes("dook"), false);
  assert.equal(T.HAPPY.includes("kiss"), false);
  assert.equal(T.HAPPY.includes("chuckle"), false);
  assert.equal(T.HAPPY.includes("snort"), false);
  assert.equal(T.HAPPY.includes("soft"), false);
  assert.equal(T.HAPPY.includes("grunt"), false);
  assert.equal(T.HAPPY.includes("wink"), false);
  assert.equal(T.HAPPY.includes("blip"), false);
  assert.equal(T.HAPPY.includes("grin"), false);
  assert.equal(T.HAPPY.includes("eep"), false);
  assert.equal(T.HAPPY.includes("coo"), false);
  assert.equal(T.HAPPY.includes("bark"), false);
  assert.equal(T.HAPPY.includes("croak"), false);
  assert.equal(T.HAPPY.includes("tip"), false);
  assert.equal(T.pickHappy("clack", 0), "yelp");
  assert.notEqual(T.pickHappy("clack", 0.9), "clack");
  assert.equal(Overlay.pickHappy("yelp", 0) !== "yelp", true);
  assert.equal(T.happyCanStart({ asleep: false, hidden: false, leaving: false, cmd: "idle" }), true);
  assert.equal(T.happyCanStart({ asleep: false, hidden: false, leaving: false, cmd: "idle", card: true }), true);
  assert.equal(T.happyCanStart({ asleep: true, hidden: false, leaving: false, cmd: "idle" }), false);
  assert.equal(T.happyShouldAbort({ cmd: "sleep" }), true);
  assert.equal(T.happyShouldAbort({ cmd: "hide" }), true);
  assert.equal(T.happyShouldAbort({ card: true, cmd: "idle" }), false);
  const clack = T.beginHappy("clack", 80, 1);
  assert.equal(clack.anim, "sit");
  const clackMid = T.stepHappy(clack, 0.4, { cmd: "idle" });
  assert.ok(clackMid.lift !== 0 || Math.abs(clackMid.rot) > 0.5);
  assert.notEqual(clackMid.phase, "done");
  const yelp = T.beginHappy("yelp", 80, 1);
  assert.equal(yelp.anim, "talk");
  const yelpMid = T.stepHappy(yelp, 0.3, { cmd: "idle" });
  assert.ok(yelpMid.lift > 0.2 || Math.abs(yelpMid.rot) > 0.5);
  const tokH = T.beginHappy("tok", 80, 1);
  assert.equal(tokH.anim, "play");
  const done = T.stepHappy(clack, T.HAPPY_DUR.clack + 0.1, { cmd: "idle" });
  assert.equal(done.phase, "done");
  const aborted = T.stepHappy(yelpMid, 0.1, { asleep: true, cmd: "sleep" });
  assert.equal(aborted.phase, "done");
  assert.equal(aborted.abort, true);
  assert.equal(T.wantsThankYou("toucan"), true);
  assert.equal(T.wantsThankYou("keel"), true);
  assert.equal(T.wantsThankYou("axolotl"), false);
  assert.equal(T.wantsThankYou("bloom"), false);
  assert.equal(T.wantsThankYou("hedgehog"), false);
  assert.equal(T.wantsThankYou("burr"), false);
  assert.equal(T.wantsThankYou("chinchilla"), false);
  assert.equal(T.wantsThankYou("floss"), false);
  assert.equal(T.wantsThankYou("ferret"), false);
  assert.equal(T.wantsThankYou("wick"), false);
  assert.equal(T.wantsThankYou("parrot"), false);
  assert.equal(T.wantsThankYou("quill"), false);
  assert.equal(T.wantsThankYou("penguin"), false);
  assert.equal(T.wantsThankYou("peck"), false);
  assert.equal(T.wantsThankYou("fox"), false);
  assert.equal(T.wantsThankYou("rue"), false);
  assert.equal(T.wantsThankYou("budgie"), false);
  assert.equal(T.wantsThankYou("echo"), false);
  assert.equal(T.wantsThankYou("goldfish"), false);
  assert.equal(T.wantsThankYou("coin"), false);
  assert.equal(T.wantsThankYou("turtle"), false);
  assert.equal(T.wantsThankYou("guinea_pig"), false);
  assert.equal(T.wantsThankYou("hamster"), false);
  assert.equal(T.wantsThankYou("dog"), false);
  assert.equal(T.wantsThankYou("cat"), false);
  assert.equal(T.wantsThankYou("rabbit"), false);
  assert.equal(T.wantsThankYou("red_panda"), false);
  assert.equal(T.wantsThankYou("ground_dragon"), false);
  const thanks = T.startThankYou("toucan", "clack", 80, 1, { cmd: "idle", card: true, windowPlay: true });
  assert.ok(thanks);
  assert.notEqual(thanks.kind, "clack");
  assert.ok(thanks.happy.lift === 0);
  assert.notEqual(thanks.happy.anim, "eat");
  assert.notEqual(thanks.happy.anim, "idle");
  const thanksMid = T.stepHappy(thanks.happy, 0.35, { cmd: "idle", card: true });
  assert.ok(thanksMid.lift !== 0 || Math.abs(thanksMid.rot) > 0.5, "a thank-you clacks or yelps");
  const blocked = T.startThankYou("toucan", "yelp", 80, 1, { asleep: true, cmd: "idle" });
  assert.equal(blocked, null);
  const other = T.startThankYou("iguana", null, 80, 1, { cmd: "idle" });
  assert.equal(other, null);
  const second = T.startThankYou("toucan", thanks.kind, 80, 1, { cmd: "idle", card: true });
  assert.ok(second);
  assert.notEqual(second.kind, thanks.kind);
});

test("ground registry keeps prior guests gated; Keel selectable; no toss/flash/bill collision", () => {
  assert.equal(Rui.TRICK_KEY, "red_panda");
  assert.equal(Relay.TRICK_KEY, "relay_dragon");
  assert.equal(Fuse.TRICK_KEY, "fuse_dragon");
  assert.equal(Earth.TRICK_KEY, "ground_dragon");
  assert.equal(Cat.TRICK_KEY, "cat");
  assert.equal(Dog.TRICK_KEY, "dog");
  assert.equal(Rabbit.TRICK_KEY, "rabbit");
  assert.equal(Hamster.TRICK_KEY, "hamster");
  assert.equal(GuineaPig.TRICK_KEY, "guinea_pig");
  assert.equal(Turtle.TRICK_KEY, "turtle");
  assert.equal(Goldfish.TRICK_KEY, "goldfish");
  assert.equal(Budgie.TRICK_KEY, "budgie");
  assert.equal(Fox.TRICK_KEY, "fox");
  assert.equal(Penguin.TRICK_KEY, "penguin");
  assert.equal(Parrot.TRICK_KEY, "parrot");
  assert.equal(Ferret.TRICK_KEY, "ferret");
  assert.equal(Hedgehog.TRICK_KEY, "hedgehog");
  assert.equal(Chinchilla.TRICK_KEY, "chinchilla");
  assert.equal(Axolotl.TRICK_KEY, "axolotl");
  assert.equal(T.TRICK_KEY, "toucan");
  assert.deepEqual([...Rui.TRICKS], ["somersault", "lie", "scratch", "wave", "dance"]);
  assert.deepEqual([...Relay.TRICKS], ["contactclick", "latchseat", "arcflick", "coilbuzz", "poleswitch", "armaturetap", "relayhush"]);
  assert.deepEqual([...Fuse.TRICKS], ["railseat", "holdcurrent", "blowclear", "reseatsnap", "cartridgerattle", "bladeflash", "fusehush"]);
  assert.deepEqual([...Earth.TRICKS], ["lugstrap", "earthseat", "heaveplate", "bedsettle", "soilgrip", "plateclamp", "groundhush"]);
  assert.deepEqual([...Cat.TRICKS], ["loaf", "knead", "stretch", "wash", "pounce", "bunting", "mlem"]);
  assert.deepEqual([...Dog.TRICKS], ["wait", "wag", "sniff", "bow", "zoom", "beg", "pant"]);
  assert.deepEqual([...Rabbit.TRICKS], ["flop", "groom", "periscope", "dig", "binky", "rub", "nosh"]);
  assert.deepEqual([...Hamster.TRICKS], ["nest", "cheek", "scurry", "pocket", "reel", "scrub", "seed"]);
  assert.deepEqual([...GuineaPig.TRICKS], ["popcorn", "rumble", "hay", "potato", "zig", "lookout", "teeth"]);
  assert.deepEqual([...Turtle.TRICKS], ["soak", "tuck", "crane", "plod", "paddle", "snorkel", "wipe"]);
  assert.deepEqual([...Goldfish.TRICKS], ["drift", "gulp", "flare", "glint", "dart", "yawn", "forage"]);
  assert.deepEqual([...Budgie.TRICKS], ["preen", "bobble", "mimic", "sidle", "dangle", "beakgrind", "shellout"]);
  assert.deepEqual([...Fox.TRICKS], ["den", "mouser", "stalk", "trot", "prance", "cock", "stash"]);
  assert.deepEqual([...Penguin.TRICKS], ["huddle", "toboggan", "waddle", "porpoise", "trumpet", "rockhop", "ecstatic"]);
  assert.deepEqual([...Parrot.TRICKS], ["quote", "strut", "fan", "crack", "flash", "pineye", "invert"]);
  assert.deepEqual([...Ferret.TRICKS], ["tube", "romp", "steal", "puff", "noodle", "corkscrew", "slink"]);
  assert.deepEqual([...Hedgehog.TRICKS], ["curl", "snuffle", "anoint", "bristle", "root", "trundle", "wheel"]);
  assert.deepEqual([...Chinchilla.TRICKS], ["ash", "bound", "fluff", "chin", "sift", "ricochet", "gnaw"]);
  assert.deepEqual([...Axolotl.TRICKS], ["gill", "amble", "mend", "smile", "plume", "sprout", "glop"]);
  assert.deepEqual([...T.TRICKS], ["roost", "berry", "juggle", "peer", "skip", "rattle", "clatter"]);
  assert.equal(T.TRICKS.includes("toss"), false);
  assert.equal(T.TRICKS.includes("flash"), false);
  assert.equal(T.TRICKS.includes("bill"), false);
  assert.equal(T.TRICKS.includes("gill"), false);
  assert.equal(T.wantsThankYou("toucan"), true);
  assert.equal(T.wantsThankYou("keel"), true);
  assert.equal(T.wantsThankYou("axolotl"), false);
  assert.equal(T.wantsThankYou("bloom"), false);
  assert.equal(Rui.sleepHoldFrame("red_panda", 4), 1);
  assert.equal(T.sleepHoldFrame("toucan", 4), null);
  globalThis.PetRuiTricks = OverlayRui;
  globalThis.PetRelayTricks = OverlayRelay;
  globalThis.PetFuseTricks = OverlayFuse;
  globalThis.PetEarthTricks = OverlayEarth;
  globalThis.PetCatTricks = OverlayCat;
  globalThis.PetDogTricks = OverlayDog;
  globalThis.PetRabbitTricks = OverlayRabbit;
  globalThis.PetHamsterTricks = OverlayHamster;
  globalThis.PetGuineaPigTricks = OverlayGuineaPig;
  globalThis.PetTurtleTricks = OverlayTurtle;
  globalThis.PetGoldfishTricks = OverlayGoldfish;
  globalThis.PetBudgieTricks = OverlayBudgie;
  globalThis.PetFoxTricks = OverlayFox;
  globalThis.PetPenguinTricks = OverlayPenguin;
  globalThis.PetParrotTricks = OverlayParrot;
  globalThis.PetFerretTricks = OverlayFerret;
  globalThis.PetHedgehogTricks = OverlayHedgehog;
  globalThis.PetChinchillaTricks = OverlayChinchilla;
  globalThis.PetAxolotlTricks = OverlayAxolotl;
  globalThis.PetToucanTricks = Overlay;
  globalThis.PetIguanaTricks = OverlayIguana;
  globalThis.PetDragonTricks = OverlayDragon;
  globalThis.PetPhoenixTricks = OverlayPhoenix;
  assert.equal(OverlayGround.tricksFor("red_panda"), OverlayRui);
  assert.equal(OverlayGround.tricksFor("rui"), OverlayRui);
  assert.equal(OverlayGround.tricksFor("relay_dragon"), OverlayRelay);
  assert.equal(OverlayGround.tricksFor("fuse_dragon"), OverlayFuse);
  assert.equal(OverlayGround.tricksFor("ground_dragon"), OverlayEarth);
  assert.equal(OverlayGround.tricksFor("ground"), OverlayEarth);
  assert.equal(OverlayGround.tricksFor("cat"), OverlayCat);
  assert.equal(OverlayGround.tricksFor("miso"), OverlayCat);
  assert.equal(OverlayGround.tricksFor("dog"), OverlayDog);
  assert.equal(OverlayGround.tricksFor("pip"), OverlayDog);
  assert.equal(OverlayGround.tricksFor("rabbit"), OverlayRabbit);
  assert.equal(OverlayGround.tricksFor("thimble"), OverlayRabbit);
  assert.equal(OverlayGround.tricksFor("hamster"), OverlayHamster);
  assert.equal(OverlayGround.tricksFor("clip"), OverlayHamster);
  assert.equal(OverlayGround.tricksFor("guinea_pig"), OverlayGuineaPig);
  assert.equal(OverlayGround.tricksFor("whee"), OverlayGuineaPig);
  assert.equal(OverlayGround.tricksFor("turtle"), OverlayTurtle);
  assert.equal(OverlayGround.tricksFor("ink"), OverlayTurtle);
  assert.equal(OverlayGround.tricksFor("goldfish"), OverlayGoldfish);
  assert.equal(OverlayGround.tricksFor("coin"), OverlayGoldfish);
  assert.equal(OverlayGround.tricksFor("budgie"), OverlayBudgie);
  assert.equal(OverlayGround.tricksFor("echo"), OverlayBudgie);
  assert.equal(OverlayGround.tricksFor("fox"), OverlayFox);
  assert.equal(OverlayGround.tricksFor("rue"), OverlayFox);
  assert.equal(OverlayGround.tricksFor("penguin"), OverlayPenguin);
  assert.equal(OverlayGround.tricksFor("peck"), OverlayPenguin);
  assert.equal(OverlayGround.tricksFor("parrot"), OverlayParrot);
  assert.equal(OverlayGround.tricksFor("quill"), OverlayParrot);
  assert.equal(OverlayGround.tricksFor("ferret"), OverlayFerret);
  assert.equal(OverlayGround.tricksFor("wick"), OverlayFerret);
  assert.equal(OverlayGround.tricksFor("hedgehog"), OverlayHedgehog);
  assert.equal(OverlayGround.tricksFor("burr"), OverlayHedgehog);
  assert.equal(OverlayGround.tricksFor("chinchilla"), OverlayChinchilla);
  assert.equal(OverlayGround.tricksFor("floss"), OverlayChinchilla);
  assert.equal(OverlayGround.tricksFor("axolotl"), OverlayAxolotl);
  assert.equal(OverlayGround.tricksFor("bloom"), OverlayAxolotl);
  assert.equal(OverlayGround.tricksFor("toucan"), Overlay);
  assert.equal(OverlayGround.tricksFor("keel"), Overlay);
  assert.equal(OverlayGround.tricksFor("iguana"), OverlayIguana);
  assert.equal(OverlayGround.tricksFor("sol"), OverlayIguana);
  assert.equal(OverlayGround.tricksFor("dragon"), OverlayDragon);
  assert.equal(OverlayGround.tricksFor("vesper"), OverlayDragon);
  assert.equal(OverlayGround.wantsThankYou("red_panda"), true);
  assert.equal(OverlayGround.wantsThankYou("relay_dragon"), true);
  assert.equal(OverlayGround.wantsThankYou("fuse_dragon"), true);
  assert.equal(OverlayGround.wantsThankYou("ground_dragon"), true);
  assert.equal(OverlayGround.wantsThankYou("cat"), true);
  assert.equal(OverlayGround.wantsThankYou("miso"), true);
  assert.equal(OverlayGround.wantsThankYou("dog"), true);
  assert.equal(OverlayGround.wantsThankYou("pip"), true);
  assert.equal(OverlayGround.wantsThankYou("rabbit"), true);
  assert.equal(OverlayGround.wantsThankYou("thimble"), true);
  assert.equal(OverlayGround.wantsThankYou("hamster"), true);
  assert.equal(OverlayGround.wantsThankYou("clip"), true);
  assert.equal(OverlayGround.wantsThankYou("guinea_pig"), true);
  assert.equal(OverlayGround.wantsThankYou("whee"), true);
  assert.equal(OverlayGround.wantsThankYou("turtle"), true);
  assert.equal(OverlayGround.wantsThankYou("ink"), true);
  assert.equal(OverlayGround.wantsThankYou("goldfish"), true);
  assert.equal(OverlayGround.wantsThankYou("coin"), true);
  assert.equal(OverlayGround.wantsThankYou("budgie"), true);
  assert.equal(OverlayGround.wantsThankYou("echo"), true);
  assert.equal(OverlayGround.wantsThankYou("fox"), true);
  assert.equal(OverlayGround.wantsThankYou("rue"), true);
  assert.equal(OverlayGround.wantsThankYou("penguin"), true);
  assert.equal(OverlayGround.wantsThankYou("peck"), true);
  assert.equal(OverlayGround.wantsThankYou("parrot"), true);
  assert.equal(OverlayGround.wantsThankYou("quill"), true);
  assert.equal(OverlayGround.wantsThankYou("ferret"), true);
  assert.equal(OverlayGround.wantsThankYou("wick"), true);
  assert.equal(OverlayGround.wantsThankYou("hedgehog"), true);
  assert.equal(OverlayGround.wantsThankYou("burr"), true);
  assert.equal(OverlayGround.wantsThankYou("chinchilla"), true);
  assert.equal(OverlayGround.wantsThankYou("floss"), true);
  assert.equal(OverlayGround.wantsThankYou("axolotl"), true);
  assert.equal(OverlayGround.wantsThankYou("bloom"), true);
  assert.equal(OverlayGround.wantsThankYou("toucan"), true);
  assert.equal(OverlayGround.wantsThankYou("keel"), true);
  assert.equal(OverlayGround.wantsThankYou("iguana"), true);
  assert.equal(OverlayGround.wantsThankYou("sol"), true);
  assert.equal(OverlayGround.wantsThankYou("dragon"), true);
  assert.equal(OverlayGround.wantsThankYou("vesper"), true);
  assert.equal(OverlayGround.sleepHoldFrame("red_panda", 4), 1);
  assert.equal(OverlayGround.sleepHoldFrame("dog", 4), null);
  assert.equal(OverlayGround.sleepHoldFrame("cat", 4), null);
  assert.equal(OverlayGround.sleepHoldFrame("rabbit", 4), null);
  assert.equal(OverlayGround.sleepHoldFrame("hamster", 4), null);
  assert.equal(OverlayGround.sleepHoldFrame("guinea_pig", 4), null);
  assert.equal(OverlayGround.sleepHoldFrame("turtle", 4), null);
  assert.equal(OverlayGround.sleepHoldFrame("goldfish", 4), null);
  assert.equal(OverlayGround.sleepHoldFrame("budgie", 4), null);
  assert.equal(OverlayGround.sleepHoldFrame("fox", 4), null);
  assert.equal(OverlayGround.sleepHoldFrame("penguin", 4), null);
  assert.equal(OverlayGround.sleepHoldFrame("parrot", 4), null);
  assert.equal(OverlayGround.sleepHoldFrame("ferret", 4), null);
  assert.equal(OverlayGround.sleepHoldFrame("hedgehog", 4), null);
  assert.equal(OverlayGround.sleepHoldFrame("axolotl", 4), null);
  assert.equal(OverlayGround.sleepHoldFrame("toucan", 4), null);
  assert.equal(OverlayGround.sleepHoldFrame("iguana", 4), null);
  assert.equal(OverlayGround.sleepHoldFrame("dragon", 4), null);
});

test("notes: Keel base idle-life done; Sol / iguana now has tricks; Vesper / dragon now has tricks; Ember / phoenix now has tricks; Nori densified; Saffron densified; Bandit densified; Jade densified; Bluff densified; Sash densified; Lula densified; Coral densified; Blush densified; Atlas densified; Cup densified; Sepia densified; Chamber densified; Pulse densified; Ochre densified; Tenant densified; Ledger densified; Anchor densified; Kite densified; Door densified; Felt densified; Vein densified; next leftover Fan / ginkgo", () => {
  assert.equal(T.TRICK_KEY, "toucan");
  assert.equal(T.wantsThankYou("keel"), true);
  assert.equal(OverlayGround.tricksFor("iguana"), OverlayIguana);
  assert.equal(OverlayGround.tricksFor("sol"), OverlayIguana);
  assert.equal(OverlayGround.tricksFor("dragon"), OverlayDragon);
  assert.equal(OverlayGround.wantsThankYou("iguana"), true);
  assert.equal(OverlayGround.wantsThankYou("sol"), true);
  assert.equal(OverlayGround.wantsThankYou("dragon"), true);
  assert.equal(OverlayGround.tricksFor("phoenix"), OverlayPhoenix);
  assert.equal(OverlayGround.wantsThankYou("phoenix"), true);
});

test("ultra-polish: Keel roost/berry/juggle/rattle/clatter lifts are Rui-visible (not micro idle-gen)", () => {
  const ex = T.beginTrick("roost", 80, 1);
  const mid = T.stepTrick(ex, 5, { cmd: "idle" });
  assert.ok(Math.abs(mid.rot) > 6, `roost mid rot ${mid.rot}`);
  assert.ok(mid.lift > 2, `roost mid lift ${mid.lift}`);
  const berry = T.beginTrick("berry", 80, 1);
  const b2 = T.stepTrick(berry, T.DUR.berry * 0.22, { cmd: "idle" });
  assert.ok(Math.abs(b2.rot) > 6, `berry mid rot ${b2.rot}`);
  assert.ok(Math.abs(b2.lift) > 2 || Math.abs(b2.rot) > 10, `berry mid lift/rot ${b2.lift}/${b2.rot}`);
  const jug = T.beginTrick("juggle", 80, 1);
  const j2 = T.stepTrick(jug, T.DUR.juggle * 0.4, { cmd: "idle" });
  assert.ok(j2.lift > 5, `juggle mid lift ${j2.lift}`);
  const rt = T.beginTrick("rattle", 80, 1);
  const r2 = T.stepTrick(rt, T.DUR.rattle * 0.4, { cmd: "idle" });
  assert.ok(r2.lift > 4, `rattle mid lift ${r2.lift}`);
  const cl = T.beginTrick("clatter", 80, 1);
  const c2 = T.stepTrick(cl, T.DUR.clatter * 0.4, { cmd: "idle" });
  assert.ok(Math.abs(c2.lift) > 2 || Math.abs(c2.rot) > 6, `clatter mid lift/rot ${c2.lift}/${c2.rot}`);
  assert.ok(Overlay.rattlePose && Overlay.clatterPose);
  assert.equal(T.ROOST_HOLD, Overlay.ROOST_HOLD);
  assert.equal(T.ROOST_HOLD, 11.2);
  assert.equal(T.RELEASE_S, 1.18);
  assert.ok(T.nextTrickWait(true, 0, "roost") > 39);
  assert.ok(T.nextTrickWait(true, 0, "roost") < 80);
  assert.ok(T.nextTrickWait(true, 0, "roost") > T.nextTrickWait(true, 0, "berry"));
});

test("notes: Keel Rui-dense ultra (ROOST_HOLD=11.2); next house-order densify leftover after early house guests: Sol / iguana then Vesper / dragon", () => {
  assert.deepEqual([...T.TRICKS], ["roost", "berry", "juggle", "peer", "skip", "rattle", "clatter"]);
  assert.equal(T.TRICKS.includes("toss"), false);
  assert.equal(T.TRICKS.includes("bill"), false);
  assert.equal(T.TRICKS.includes("flash"), false);
  assert.equal(T.TRICKS.includes("pineye"), false);
  assert.equal(T.TRICKS.includes("invert"), false);
  assert.equal(T.TRICKS.includes("rockhop"), false);
  assert.equal(T.TRICKS.includes("quote"), false);
  assert.equal(T.TRICKS.includes("preen"), false);
});
