import assert from "node:assert/strict";
import { createRequire } from "node:module";
import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { test } from "node:test";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const P = await import(join(root, "src/lib/pets/window-play.ts"));
const require = createRequire(import.meta.url);
const Overlay = require(join(root, "../desktop/renderer/window-play.js"));

const livingSrc = readFileSync(join(root, "src/components/desk/living-pet.tsx"), "utf8");
const demoSrc = readFileSync(join(root, "src/components/desk/demo-stage.tsx"), "utf8");
const rosterSrc = readFileSync(join(root, "src/lib/pets/roster.ts"), "utf8");
const guideSrc = readFileSync(join(root, "src/lib/pets/house-guide.ts"), "utf8");

const WORK = { width: 1400, height: 800, floorLift: 0 };
const WIN = { id: "hw", x: 360, y: 80, width: 640, height: 420 };

test("Rui cling-dive is shared; Arc ridge is shared; Volt coil is shared; Trace path is shared; Flux field is shared; Miso sits a ledge; Pip watches from the floor; Thimble thumps then vanishes; Clip stashes in a drawer; Whee wheeks at a window; Ink basks on a rail; Coin circles a bowl; Echo perches a shade; Rue scents a jamb; Peck bows a pane; Quill hooks a jamb; Wick threads a gap; Burr balls at a pane foot; Floss dusts a meeting rail; Bloom walks a tank wall; Keel tosses fruit from a cornice; Sol flattens on a sun-warmed pane; Vesper drapes a lintel", () => {
  assert.equal(P.playFor("red_panda"), Overlay.playFor("red_panda"));
  assert.equal(P.playFor("cyber_dragon"), "ridge");
  assert.equal(P.playFor("cyber_dragon"), Overlay.playFor("cyber_dragon"));
  assert.equal(P.playFor("volt_dragon"), "coil");
  assert.equal(P.playFor("volt_dragon"), Overlay.playFor("volt_dragon"));
  assert.equal(P.playFor("trace_dragon"), "path");
  assert.equal(P.playFor("trace_dragon"), Overlay.playFor("trace_dragon"));
  assert.equal(P.playFor("flux_dragon"), "field");
  assert.equal(P.playFor("flux_dragon"), Overlay.playFor("flux_dragon"));
  assert.equal(P.playFor("spark_dragon"), "crackle");
  assert.equal(P.playFor("spark_dragon"), Overlay.playFor("spark_dragon"));
  assert.equal(P.playFor("ion_dragon"), "charge");
  assert.equal(P.playFor("ion_dragon"), Overlay.playFor("ion_dragon"));
  assert.equal(P.playFor("gauss_dragon"), "orbit");
  assert.equal(P.playFor("gauss_dragon"), Overlay.playFor("gauss_dragon"));
  assert.equal(P.playFor("relay_dragon"), "click");
  assert.equal(P.playFor("relay_dragon"), Overlay.playFor("relay_dragon"));
  assert.equal(P.playFor("fuse_dragon"), "hold");
  assert.equal(P.playFor("fuse_dragon"), Overlay.playFor("fuse_dragon"));
  assert.equal(P.playFor("ground_dragon"), "earth");
  assert.equal(P.playFor("ground_dragon"), Overlay.playFor("ground_dragon"));
  assert.equal(P.playFor("cat"), "ledge");
  assert.equal(P.playFor("cat"), Overlay.playFor("cat"));
  assert.equal(P.playFor("dog"), "watch");
  assert.equal(P.playFor("dog"), Overlay.playFor("dog"));
  assert.equal(P.playFor("rabbit"), "thump");
  assert.equal(P.playFor("rabbit"), Overlay.playFor("rabbit"));
  assert.equal(P.playFor("hamster"), "stash");
  assert.equal(P.playFor("hamster"), Overlay.playFor("hamster"));
  assert.equal(P.playFor("guinea_pig"), "wheek");
  assert.equal(P.playFor("guinea_pig"), Overlay.playFor("guinea_pig"));
  assert.equal(P.playFor("turtle"), "bask");
  assert.equal(P.playFor("turtle"), Overlay.playFor("turtle"));
  assert.equal(P.playFor("goldfish"), "circle");
  assert.equal(P.playFor("goldfish"), Overlay.playFor("goldfish"));
  assert.equal(P.playFor("budgie"), "perch");
  assert.equal(P.playFor("budgie"), Overlay.playFor("budgie"));
  assert.equal(P.playFor("fox"), "scent");
  assert.equal(P.playFor("fox"), Overlay.playFor("fox"));
  assert.equal(P.playFor("penguin"), "bow");
  assert.equal(P.playFor("penguin"), Overlay.playFor("penguin"));
  assert.equal(P.playFor("parrot"), "hook");
  assert.equal(P.playFor("parrot"), Overlay.playFor("parrot"));
  assert.equal(P.playFor("ferret"), "thread");
  assert.equal(P.playFor("ferret"), Overlay.playFor("ferret"));
  assert.equal(P.playFor("hedgehog"), "ball");
  assert.equal(P.playFor("hedgehog"), Overlay.playFor("hedgehog"));
  assert.equal(P.playFor("chinchilla"), "dust");
  assert.equal(P.playFor("chinchilla"), Overlay.playFor("chinchilla"));
  assert.equal(P.playFor("axolotl"), "wall");
  assert.equal(P.playFor("axolotl"), Overlay.playFor("axolotl"));
  assert.equal(P.playFor("toucan"), "toss");
  assert.equal(P.playFor("toucan"), Overlay.playFor("toucan"));
  assert.equal(P.playFor("iguana"), "flatten");
  assert.equal(P.playFor("iguana"), Overlay.playFor("iguana"));
  assert.equal(P.playFor("dragon"), "drape");
  assert.equal(P.playFor("dragon"), Overlay.playFor("dragon"));
  assert.equal(P.playFor("gecko"), "sill");
  assert.equal(P.playFor("phoenix"), "sill");
  assert.equal(P.canStart({ asleep: true, cmd: "idle" }), false);
  const spin = P.divePath(0.5, { x: 400, lift: 200, side: "right" }, { x: 500, lift: 0 }, "spin");
  const desk = Overlay.divePath(0.5, { x: 400, lift: 200, side: "right" }, { x: 500, lift: 0 }, "spin");
  assert.equal(spin.rot, desk.rot);
  assert.ok(spin.rot > 0);
  const webRidge = P.ridgePoint(WIN, 0.5, 176, WORK);
  const deskRidge = Overlay.ridgePoint(WIN, 0.5, 176, WORK);
  assert.equal(webRidge.lift, deskRidge.lift);
  const webCoil = P.coilPoint(WIN, "left", 176, WORK);
  const deskCoil = Overlay.coilPoint(WIN, "left", 176, WORK);
  assert.equal(webCoil.lift, deskCoil.lift);
  assert.equal(webCoil.x, deskCoil.x);
  const webPath = P.pathPoint(WIN, 0.5, 176, WORK, "left");
  const deskPath = Overlay.pathPoint(WIN, 0.5, 176, WORK, "left");
  assert.equal(webPath.lift, deskPath.lift);
  assert.equal(webPath.x, deskPath.x);
  const webField = P.fieldPoint(WIN, 176, WORK);
  const deskField = Overlay.fieldPoint(WIN, 176, WORK);
  assert.equal(webField.lift, deskField.lift);
  assert.equal(webField.x, deskField.x);
  const webCharge = P.chargePoint(WIN, "tl", 176, WORK);
  const deskCharge = Overlay.chargePoint(WIN, "tl", 176, WORK);
  assert.equal(webCharge.lift, deskCharge.lift);
  assert.equal(webCharge.x, deskCharge.x);
  const webClick = P.clickPoint(WIN, "left", 176, WORK);
  const deskClick = Overlay.clickPoint(WIN, "left", 176, WORK);
  assert.equal(webClick.lift, deskClick.lift);
  assert.equal(webClick.x, deskClick.x);
  const webHold = P.holdPoint(WIN, "jamb", "left", 176, WORK);
  const deskHold = Overlay.holdPoint(WIN, "jamb", "left", 176, WORK);
  assert.equal(webHold.lift, deskHold.lift);
  assert.equal(webHold.x, deskHold.x);
  const webEarth = P.earthPoint(WIN, 176, WORK);
  const deskEarth = Overlay.earthPoint(WIN, 176, WORK);
  assert.equal(webEarth.lift, deskEarth.lift);
  assert.equal(webEarth.x, deskEarth.x);
  const webLedge = P.ledgePoint(WIN, 176, WORK);
  const deskLedge = Overlay.ledgePoint(WIN, 176, WORK);
  assert.equal(webLedge.lift, deskLedge.lift);
  assert.equal(webLedge.x, deskLedge.x);
  const webWatch = P.watchPoint(WIN, 176, WORK);
  const deskWatch = Overlay.watchPoint(WIN, 176, WORK);
  assert.equal(webWatch.lift, deskWatch.lift);
  assert.equal(webWatch.x, deskWatch.x);
  assert.equal(webWatch.lift, 0);
  const webThump = P.thumpPoint(WIN, 176, WORK, "left");
  const deskThump = Overlay.thumpPoint(WIN, 176, WORK, "left");
  assert.equal(webThump.lift, deskThump.lift);
  assert.equal(webThump.x, deskThump.x);
  assert.equal(webThump.lift, 0);
  const webStash = P.stashPoint(WIN, "left", 176, WORK);
  const deskStash = Overlay.stashPoint(WIN, "left", 176, WORK);
  assert.equal(webStash.lift, deskStash.lift);
  assert.equal(webStash.x, deskStash.x);
  assert.ok(webStash.lift > 16);
  const webWheek = P.wheekPoint(WIN, 176, WORK);
  const deskWheek = Overlay.wheekPoint(WIN, 176, WORK);
  assert.equal(webWheek.lift, deskWheek.lift);
  assert.equal(webWheek.x, deskWheek.x);
  assert.equal(webWheek.lift, 0);
  const webBask = P.baskPoint(WIN, 176, WORK);
  const deskBask = Overlay.baskPoint(WIN, 176, WORK);
  assert.equal(webBask.lift, deskBask.lift);
  assert.equal(webBask.x, deskBask.x);
  assert.ok(webBask.lift > webEarth.lift);
  const webCircle = P.circlePoint(WIN, 0, 176, WORK, 1);
  const deskCircle = Overlay.circlePoint(WIN, 0, 176, WORK, 1);
  assert.equal(webCircle.lift, deskCircle.lift);
  assert.equal(webCircle.x, deskCircle.x);
  assert.ok(webCircle.x > WIN.x && webCircle.x + 176 < WIN.x + WIN.width);
  const webPerch = P.perchPoint(WIN, "left", 176, WORK);
  const deskPerch = Overlay.perchPoint(WIN, "left", 176, WORK);
  assert.equal(webPerch.lift, deskPerch.lift);
  assert.equal(webPerch.x, deskPerch.x);
  assert.ok(webPerch.lift > 16);
  const webScent = P.scentPoint(WIN, "left", 176, WORK);
  const deskScent = Overlay.scentPoint(WIN, "left", 176, WORK);
  assert.equal(webScent.lift, deskScent.lift);
  assert.equal(webScent.x, deskScent.x);
  assert.equal(webScent.lift, 0);
  const webBow = P.bowPoint(WIN, 176, WORK);
  const deskBow = Overlay.bowPoint(WIN, 176, WORK);
  assert.equal(webBow.lift, deskBow.lift);
  assert.equal(webBow.x, deskBow.x);
  assert.ok(webBow.lift > 16);
  const webHook = P.hookPoint(WIN, "left", 1, 176, WORK);
  const deskHook = Overlay.hookPoint(WIN, "left", 1, 176, WORK);
  assert.equal(webHook.lift, deskHook.lift);
  assert.equal(webHook.x, deskHook.x);
  assert.ok(webHook.lift > 16);
  const webHookStart = P.hookPoint(WIN, "left", 0, 176, WORK);
  const deskHookStart = Overlay.hookPoint(WIN, "left", 0, 176, WORK);
  assert.equal(webHookStart.lift, deskHookStart.lift);
  assert.equal(webHookStart.x, deskHookStart.x);
  assert.ok(webHook.lift > webHookStart.lift + 40);
  const webThread = P.threadPoint(WIN, 0, 176, WORK);
  const deskThread = Overlay.threadPoint(WIN, 0, 176, WORK);
  assert.equal(webThread.lift, deskThread.lift);
  assert.equal(webThread.x, deskThread.x);
  const webThreadEnd = P.threadPoint(WIN, 1, 176, WORK);
  const deskThreadEnd = Overlay.threadPoint(WIN, 1, 176, WORK);
  assert.equal(webThreadEnd.lift, deskThreadEnd.lift);
  assert.equal(webThreadEnd.x, deskThreadEnd.x);
  assert.ok(Math.abs(webThreadEnd.x - webThread.x) > 80);
  assert.ok(webThread.lift > 8);
  const webBall = P.ballPoint(WIN, 176, WORK);
  const deskBall = Overlay.ballPoint(WIN, 176, WORK);
  assert.equal(webBall.lift, deskBall.lift);
  assert.equal(webBall.x, deskBall.x);
  assert.equal(webBall.lift, 0);
  const webDust = P.dustPoint(WIN, 176, WORK);
  const deskDust = Overlay.dustPoint(WIN, 176, WORK);
  assert.equal(webDust.lift, deskDust.lift);
  assert.equal(webDust.x, deskDust.x);
  assert.ok(webDust.lift > 36);
  const webWall = P.wallPoint(WIN, 0, "left", 176, WORK);
  const deskWall = Overlay.wallPoint(WIN, 0, "left", 176, WORK);
  assert.equal(webWall.lift, deskWall.lift);
  assert.equal(webWall.x, deskWall.x);
  const webWallEnd = P.wallPoint(WIN, 1, "left", 176, WORK);
  const deskWallEnd = Overlay.wallPoint(WIN, 1, "left", 176, WORK);
  assert.equal(webWallEnd.lift, deskWallEnd.lift);
  assert.equal(webWallEnd.x, deskWallEnd.x);
  assert.ok(webWallEnd.lift > webWall.lift + 40, "she walks up the pane");
  const webToss = P.tossPoint(WIN, "left", 176, WORK);
  const deskToss = Overlay.tossPoint(WIN, "left", 176, WORK);
  assert.equal(webToss.lift, deskToss.lift);
  assert.equal(webToss.x, deskToss.x);
  assert.ok(webToss.lift > 36);
  const webFlatten = P.flattenPoint(WIN, 176, WORK);
  const deskFlatten = Overlay.flattenPoint(WIN, 176, WORK);
  assert.equal(webFlatten.lift, deskFlatten.lift);
  assert.equal(webFlatten.x, deskFlatten.x);
  assert.ok(webFlatten.lift > 36);
  const webDrape = P.drapePoint(WIN, "left", 176, WORK);
  const deskDrape = Overlay.drapePoint(WIN, "left", 176, WORK);
  assert.equal(webDrape.lift, deskDrape.lift);
  assert.equal(webDrape.x, deskDrape.x);
  assert.ok(webDrape.lift > 36);
});

test("the demo room walks the same Rui climb against a drawn window", () => {
  assert.match(demoSrc, /demoWindow/);
  assert.match(livingSrc, /playFor/);
  assert.match(livingSrc, /stepPlay/);
  assert.match(livingSrc, /shouldAbort/);
  assert.match(livingSrc, /asleepRef/);
  const target = P.pickTarget([WIN], 40, "red_panda", WORK, 176, { side: "left", spin: "backflip", diveFrom: "top" });
  let play = P.beginPlay(target, target.approachX);
  const seen = new Set();
  for (let i = 0; i < 400 && play.phase !== "done"; i++) {
    seen.add(play.phase);
    play = P.stepPlay(play, 0.05, { x: play.x, lift: play.lift }, [WIN], WORK, 176, { cmd: "idle" });
  }
  assert.ok(seen.has("cling"));
  assert.ok(seen.has("dive"));
  assert.equal(play.phase, "done");
});

test("the demo window plate walks Arc's ridge the same way", () => {
  assert.match(demoSrc, /demoWindow/);
  assert.match(livingSrc, /ridge-leap|playFor/);
  const target = P.pickTarget([WIN], 40, "cyber_dragon", WORK, 176, { leave: "hop" });
  let play = P.beginPlay(target, target.approachX);
  const seen = new Set();
  for (let i = 0; i < 400 && play.phase !== "done"; i++) {
    seen.add(play.phase);
    play = P.stepPlay(play, 0.05, { x: play.x, lift: play.lift }, [WIN], WORK, 176, { cmd: "idle" });
    assert.notEqual(play.phase, "cling");
    assert.notEqual(play.phase, "dive");
  }
  assert.ok(seen.has("ridge-leap"));
  assert.ok(seen.has("ridge-hold"));
  assert.ok(seen.has("ridge-off"));
  assert.equal(play.phase, "done");
});

test("the demo window plate walks Volt's coil the same way", () => {
  assert.match(demoSrc, /demoWindow/);
  assert.match(livingSrc, /coil-on|playFor/);
  const target = P.pickTarget([WIN], 40, "volt_dragon", WORK, 176, { side: "right" });
  let play = P.beginPlay(target, target.approachX);
  const seen = new Set();
  for (let i = 0; i < 400 && play.phase !== "done"; i++) {
    seen.add(play.phase);
    play = P.stepPlay(play, 0.05, { x: play.x, lift: play.lift }, [WIN], WORK, 176, { cmd: "idle" });
    assert.notEqual(play.phase, "cling");
    assert.notEqual(play.phase, "dive");
    assert.notEqual(play.phase, "ridge-hold");
    assert.notEqual(play.phase, "sill-walk");
  }
  assert.ok(seen.has("coil-on"));
  assert.ok(seen.has("coil-hold"));
  assert.ok(seen.has("coil-off"));
  assert.equal(play.phase, "done");
});

test("the demo window plate walks Trace's path the same way", () => {
  assert.match(demoSrc, /demoWindow/);
  assert.match(livingSrc, /path-on|playFor/);
  const overlayTarget = Overlay.pickTarget([WIN], 40, "trace_dragon", WORK, 176, { side: "left", leave: "hop" });
  const target = P.pickTarget([WIN], 40, "trace_dragon", WORK, 176, { side: "left", leave: "hop" });
  assert.equal(target.kind, overlayTarget.kind);
  assert.equal(target.holdX, overlayTarget.holdX);
  assert.equal(target.holdLift, overlayTarget.holdLift);
  let play = P.beginPlay(target, target.approachX);
  const seen = new Set();
  for (let i = 0; i < 500 && play.phase !== "done"; i++) {
    seen.add(play.phase);
    play = P.stepPlay(play, 0.05, { x: play.x, lift: play.lift }, [WIN], WORK, 176, { cmd: "idle" });
    assert.notEqual(play.phase, "cling");
    assert.notEqual(play.phase, "dive");
    assert.notEqual(play.phase, "ridge-hold");
    assert.notEqual(play.phase, "coil-hold");
    assert.notEqual(play.phase, "sill-walk");
  }
  assert.ok(seen.has("path-on"));
  assert.ok(seen.has("path-walk"));
  assert.ok(seen.has("path-sit"));
  assert.ok(seen.has("path-off"));
  assert.equal(play.phase, "done");
});

test("the demo window plate walks Flux's field the same way", () => {
  assert.match(demoSrc, /demoWindow/);
  assert.match(livingSrc, /field-on|playFor/);
  const overlayTarget = Overlay.pickTarget([WIN], 40, "flux_dragon", WORK, 176, { leave: "drift" });
  const target = P.pickTarget([WIN], 40, "flux_dragon", WORK, 176, { leave: "drift" });
  assert.equal(target.kind, overlayTarget.kind);
  assert.equal(target.holdX, overlayTarget.holdX);
  assert.equal(target.holdLift, overlayTarget.holdLift);
  let play = P.beginPlay(target, target.approachX);
  const seen = new Set();
  for (let i = 0; i < 500 && play.phase !== "done"; i++) {
    seen.add(play.phase);
    play = P.stepPlay(play, 0.05, { x: play.x, lift: play.lift }, [WIN], WORK, 176, { cmd: "idle" });
    assert.notEqual(play.phase, "cling");
    assert.notEqual(play.phase, "dive");
    assert.notEqual(play.phase, "ridge-hold");
    assert.notEqual(play.phase, "coil-hold");
    assert.notEqual(play.phase, "path-walk");
    assert.notEqual(play.phase, "sill-walk");
  }
  assert.ok(seen.has("field-on"));
  assert.ok(seen.has("field-hold"));
  assert.ok(seen.has("field-off"));
  assert.equal(play.phase, "done");
});

test("the demo window plate walks Spark's crackle the same way", () => {
  assert.match(demoSrc, /demoWindow/);
  assert.match(livingSrc, /crackle-on|playFor/);
  const overlayTarget = Overlay.pickTarget([WIN], 40, "spark_dragon", WORK, 176, { side: "left", leave: "hop", hopFrom: 0 });
  const target = P.pickTarget([WIN], 40, "spark_dragon", WORK, 176, { side: "left", leave: "hop", hopFrom: 0 });
  assert.equal(target.kind, overlayTarget.kind);
  assert.equal(target.holdX, overlayTarget.holdX);
  assert.equal(target.holdLift, overlayTarget.holdLift);
  let play = P.beginPlay(target, target.approachX);
  const seen = new Set();
  for (let i = 0; i < 500 && play.phase !== "done"; i++) {
    seen.add(play.phase);
    play = P.stepPlay(play, 0.05, { x: play.x, lift: play.lift }, [WIN], WORK, 176, { cmd: "idle" });
    assert.notEqual(play.phase, "cling");
    assert.notEqual(play.phase, "ridge-hold");
    assert.notEqual(play.phase, "coil-hold");
    assert.notEqual(play.phase, "field-hold");
    assert.notEqual(play.phase, "sill-walk");
  }
  assert.ok(seen.has("crackle-on"));
  assert.ok(seen.has("crackle-hop"));
  assert.ok(seen.has("crackle-off"));
  assert.equal(play.phase, "done");
});

test("the demo window plate walks Ion's charge the same way", () => {
  assert.match(demoSrc, /demoWindow/);
  assert.match(livingSrc, /charge-on|playFor/);
  const overlayTarget = Overlay.pickTarget([WIN], 40, "ion_dragon", WORK, 176, { side: "left", corner: "tl", leave: "hop" });
  const target = P.pickTarget([WIN], 40, "ion_dragon", WORK, 176, { side: "left", corner: "tl", leave: "hop" });
  assert.equal(target.kind, overlayTarget.kind);
  assert.equal(target.holdX, overlayTarget.holdX);
  assert.equal(target.holdLift, overlayTarget.holdLift);
  assert.equal(target.chargeEndX, overlayTarget.chargeEndX);
  let play = P.beginPlay(target, target.approachX);
  const seen = new Set();
  for (let i = 0; i < 500 && play.phase !== "done"; i++) {
    seen.add(play.phase);
    play = P.stepPlay(play, 0.05, { x: play.x, lift: play.lift }, [WIN], WORK, 176, { cmd: "idle" });
    assert.notEqual(play.phase, "cling");
    assert.notEqual(play.phase, "ridge-hold");
    assert.notEqual(play.phase, "coil-hold");
    assert.notEqual(play.phase, "path-walk");
    assert.notEqual(play.phase, "field-hold");
    assert.notEqual(play.phase, "crackle-hop");
    assert.notEqual(play.phase, "sill-walk");
  }
  assert.ok(seen.has("charge-on"));
  assert.ok(seen.has("charge-bolt"));
  assert.ok(seen.has("charge-hold"));
  assert.ok(seen.has("charge-off"));
  assert.equal(play.phase, "done");
});

test("the demo window plate walks Gauss's orbit the same way", () => {
  assert.match(demoSrc, /demoWindow/);
  assert.match(livingSrc, /orbit-on|playFor/);
  const overlayTarget = Overlay.pickTarget([WIN], 40, "gauss_dragon", WORK, 176, { side: "left", orbitDir: 1, leave: "hop" });
  const target = P.pickTarget([WIN], 40, "gauss_dragon", WORK, 176, { side: "left", orbitDir: 1, leave: "hop" });
  assert.equal(target.kind, overlayTarget.kind);
  assert.equal(target.holdX, overlayTarget.holdX);
  assert.equal(target.holdLift, overlayTarget.holdLift);
  assert.equal(target.orbitEndX, overlayTarget.orbitEndX);
  let play = P.beginPlay(target, target.approachX);
  const seen = new Set();
  for (let i = 0; i < 500 && play.phase !== "done"; i++) {
    seen.add(play.phase);
    play = P.stepPlay(play, 0.05, { x: play.x, lift: play.lift }, [WIN], WORK, 176, { cmd: "idle" });
    assert.notEqual(play.phase, "cling");
    assert.notEqual(play.phase, "ridge-hold");
    assert.notEqual(play.phase, "coil-hold");
    assert.notEqual(play.phase, "path-walk");
    assert.notEqual(play.phase, "field-hold");
    assert.notEqual(play.phase, "crackle-hop");
    assert.notEqual(play.phase, "charge-bolt");
    assert.notEqual(play.phase, "sill-walk");
  }
  assert.ok(seen.has("orbit-on"));
  assert.ok(seen.has("orbit-loop"));
  assert.ok(seen.has("orbit-hold"));
  assert.ok(seen.has("orbit-off"));
  assert.equal(play.phase, "done");
});

test("the demo window plates walk Relay's click the same way", () => {
  assert.match(demoSrc, /demoWindow/);
  assert.match(livingSrc, /click-on|playFor/);
  const WIN_B = { id: "hw2", x: 1040, y: 120, width: 300, height: 360 };
  const overlayTarget = Overlay.pickTarget([WIN, WIN_B], 40, "relay_dragon", WORK, 176, { leave: "hop" });
  const target = P.pickTarget([WIN, WIN_B], 40, "relay_dragon", WORK, 176, { leave: "hop" });
  assert.equal(target.kind, overlayTarget.kind);
  assert.equal(target.holdX, overlayTarget.holdX);
  assert.equal(target.holdLift, overlayTarget.holdLift);
  assert.equal(target.clickEndX, overlayTarget.clickEndX);
  assert.equal(target.clickToId, overlayTarget.clickToId);
  let play = P.beginPlay(target, target.approachX);
  const seen = new Set();
  for (let i = 0; i < 500 && play.phase !== "done"; i++) {
    seen.add(play.phase);
    play = P.stepPlay(play, 0.05, { x: play.x, lift: play.lift }, [WIN, WIN_B], WORK, 176, { cmd: "idle" });
    assert.notEqual(play.phase, "cling");
    assert.notEqual(play.phase, "ridge-hold");
    assert.notEqual(play.phase, "coil-hold");
    assert.notEqual(play.phase, "path-walk");
    assert.notEqual(play.phase, "field-hold");
    assert.notEqual(play.phase, "crackle-hop");
    assert.notEqual(play.phase, "charge-bolt");
    assert.notEqual(play.phase, "orbit-loop");
    assert.notEqual(play.phase, "sill-walk");
  }
  assert.ok(seen.has("click-on"));
  assert.ok(seen.has("click-a"));
  assert.ok(seen.has("click-hop"));
  assert.ok(seen.has("click-b"));
  assert.ok(seen.has("click-off"));
  assert.equal(play.phase, "done");
});

test("the demo window plate walks Fuse's hold the same way", () => {
  assert.match(demoSrc, /demoWindow/);
  assert.match(livingSrc, /hold-on|playFor/);
  const overlayTarget = Overlay.pickTarget([WIN], 40, "fuse_dragon", WORK, 176, { side: "left", clip: "jamb", leave: "hop" });
  const target = P.pickTarget([WIN], 40, "fuse_dragon", WORK, 176, { side: "left", clip: "jamb", leave: "hop" });
  assert.equal(target.kind, overlayTarget.kind);
  assert.equal(target.holdX, overlayTarget.holdX);
  assert.equal(target.holdLift, overlayTarget.holdLift);
  assert.equal(target.clip, overlayTarget.clip);
  assert.equal(target.clickToId, undefined);
  let play = P.beginPlay(target, target.approachX);
  const seen = new Set();
  for (let i = 0; i < 600 && play.phase !== "done"; i++) {
    seen.add(play.phase);
    play = P.stepPlay(play, 0.05, { x: play.x, lift: play.lift }, [WIN], WORK, 176, { cmd: "idle" });
    assert.notEqual(play.phase, "cling");
    assert.notEqual(play.phase, "ridge-hold");
    assert.notEqual(play.phase, "coil-hold");
    assert.notEqual(play.phase, "path-walk");
    assert.notEqual(play.phase, "field-hold");
    assert.notEqual(play.phase, "crackle-hop");
    assert.notEqual(play.phase, "charge-bolt");
    assert.notEqual(play.phase, "orbit-loop");
    assert.notEqual(play.phase, "click-hop");
    assert.notEqual(play.phase, "sill-walk");
  }
  assert.ok(seen.has("hold-on"));
  assert.ok(seen.has("hold-sit"));
  assert.ok(seen.has("hold-off"));
  assert.equal(play.phase, "done");
});

test("the demo window plate walks Ground's earth the same way", () => {
  assert.match(demoSrc, /demoWindow/);
  assert.match(livingSrc, /earth-on|playFor/);
  const overlayTarget = Overlay.pickTarget([WIN], 40, "ground_dragon", WORK, 176, { leave: "step" });
  const target = P.pickTarget([WIN], 40, "ground_dragon", WORK, 176, { leave: "step" });
  assert.equal(target.kind, overlayTarget.kind);
  assert.equal(target.holdX, overlayTarget.holdX);
  assert.equal(target.holdLift, overlayTarget.holdLift);
  assert.equal(target.side, "bottom");
  assert.equal(target.clickToId, undefined);
  let play = P.beginPlay(target, target.approachX);
  const seen = new Set();
  for (let i = 0; i < 600 && play.phase !== "done"; i++) {
    seen.add(play.phase);
    play = P.stepPlay(play, 0.05, { x: play.x, lift: play.lift }, [WIN], WORK, 176, { cmd: "idle" });
    assert.notEqual(play.phase, "cling");
    assert.notEqual(play.phase, "ridge-hold");
    assert.notEqual(play.phase, "coil-hold");
    assert.notEqual(play.phase, "path-walk");
    assert.notEqual(play.phase, "field-hold");
    assert.notEqual(play.phase, "crackle-hop");
    assert.notEqual(play.phase, "charge-bolt");
    assert.notEqual(play.phase, "orbit-loop");
    assert.notEqual(play.phase, "click-hop");
    assert.notEqual(play.phase, "hold-sit");
    assert.notEqual(play.phase, "sill-walk");
  }
  assert.ok(seen.has("earth-on"));
  assert.ok(seen.has("earth-sit"));
  assert.ok(seen.has("earth-off"));
  assert.equal(play.phase, "done");
});

test("the demo window plate walks Miso's ledge the same way", () => {
  assert.match(demoSrc, /demoWindow/);
  assert.match(livingSrc, /ledge-on|playFor/);
  const overlayTarget = Overlay.pickTarget([WIN], 40, "cat", WORK, 176);
  const target = P.pickTarget([WIN], 40, "cat", WORK, 176);
  assert.equal(target.kind, overlayTarget.kind);
  assert.equal(target.kind, "ledge");
  assert.equal(target.holdX, overlayTarget.holdX);
  assert.equal(target.holdLift, overlayTarget.holdLift);
  assert.equal(target.side, "top");
  assert.equal(target.leave, "hop");
  assert.equal(target.clickToId, undefined);
  let play = P.beginPlay(target, target.approachX);
  const seen = new Set();
  let sitXMin = Infinity;
  let sitXMax = -Infinity;
  for (let i = 0; i < 700 && play.phase !== "done"; i++) {
    seen.add(play.phase);
    play = P.stepPlay(play, 0.05, { x: play.x, lift: play.lift }, [WIN], WORK, 176, { cmd: "idle" });
    assert.notEqual(play.phase, "cling");
    assert.notEqual(play.phase, "ridge-hold");
    assert.notEqual(play.phase, "coil-hold");
    assert.notEqual(play.phase, "path-walk");
    assert.notEqual(play.phase, "field-hold");
    assert.notEqual(play.phase, "crackle-hop");
    assert.notEqual(play.phase, "charge-bolt");
    assert.notEqual(play.phase, "orbit-loop");
    assert.notEqual(play.phase, "click-hop");
    assert.notEqual(play.phase, "hold-sit");
    assert.notEqual(play.phase, "earth-sit");
    assert.notEqual(play.phase, "watch-hold");
    assert.notEqual(play.phase, "thump");
    assert.notEqual(play.phase, "stash-cheek");
    assert.notEqual(play.phase, "wheek");
    assert.notEqual(play.phase, "bask");
    assert.notEqual(play.phase, "bask-withdraw");
    assert.notEqual(play.phase, "sill-walk");
    if (play.phase === "ledge-sit") {
      sitXMin = Math.min(sitXMin, play.x);
      sitXMax = Math.max(sitXMax, play.x);
    }
  }
  assert.ok(seen.has("ledge-on"));
  assert.ok(seen.has("ledge-sit"));
  assert.ok(seen.has("ledge-off"));
  assert.ok(sitXMax - sitXMin < 2, "one sit — not a walk across");
  assert.equal(play.phase, "done");
});

test("the demo window plate walks Pip's watch the same way", () => {
  assert.match(demoSrc, /demoWindow/);
  assert.match(livingSrc, /watch-on|playFor/);
  const overlayTarget = Overlay.pickTarget([WIN], 40, "dog", WORK, 176);
  const target = P.pickTarget([WIN], 40, "dog", WORK, 176);
  assert.equal(target.kind, overlayTarget.kind);
  assert.equal(target.kind, "watch");
  assert.equal(target.holdX, overlayTarget.holdX);
  assert.equal(target.holdLift, overlayTarget.holdLift);
  assert.equal(target.holdLift, 0);
  assert.equal(target.side, "feet");
  assert.equal(target.leave, "trot");
  assert.equal(target.clickToId, undefined);
  let play = P.beginPlay(target, target.approachX);
  const seen = new Set();
  let sitXMin = Infinity;
  let sitXMax = -Infinity;
  let maxLift = 0;
  for (let i = 0; i < 700 && play.phase !== "done"; i++) {
    seen.add(play.phase);
    play = P.stepPlay(play, 0.05, { x: play.x, lift: play.lift }, [WIN], WORK, 176, { cmd: "idle" });
    maxLift = Math.max(maxLift, play.lift);
    assert.notEqual(play.phase, "cling");
    assert.notEqual(play.phase, "ridge-hold");
    assert.notEqual(play.phase, "coil-hold");
    assert.notEqual(play.phase, "path-walk");
    assert.notEqual(play.phase, "field-hold");
    assert.notEqual(play.phase, "crackle-hop");
    assert.notEqual(play.phase, "charge-bolt");
    assert.notEqual(play.phase, "orbit-loop");
    assert.notEqual(play.phase, "click-hop");
    assert.notEqual(play.phase, "hold-sit");
    assert.notEqual(play.phase, "earth-sit");
    assert.notEqual(play.phase, "ledge-sit");
    assert.notEqual(play.phase, "thump");
    assert.notEqual(play.phase, "stash-cheek");
    assert.notEqual(play.phase, "wheek");
    assert.notEqual(play.phase, "bask");
    assert.notEqual(play.phase, "bask-withdraw");
    assert.notEqual(play.phase, "sill-walk");
    if (play.phase === "watch-hold") {
      sitXMin = Math.min(sitXMin, play.x);
      sitXMax = Math.max(sitXMax, play.x);
      assert.equal(play.lift, 0);
    }
  }
  assert.ok(seen.has("watch-on"));
  assert.ok(seen.has("watch-hold"));
  assert.ok(seen.has("watch-off"));
  assert.ok(sitXMax - sitXMin < 2, "one watch — not a walk across");
  assert.equal(maxLift, 0, "never hops onto the frame");
  assert.equal(play.phase, "done");
});

test("the demo window plate walks Thimble's thump the same way", () => {
  assert.match(demoSrc, /demoWindow/);
  assert.match(livingSrc, /thump-on|playFor/);
  const overlayTarget = Overlay.pickTarget([WIN], 40, "rabbit", WORK, 176, { side: "left" });
  const target = P.pickTarget([WIN], 40, "rabbit", WORK, 176, { side: "left" });
  assert.equal(target.kind, overlayTarget.kind);
  assert.equal(target.kind, "thump");
  assert.equal(target.holdX, overlayTarget.holdX);
  assert.equal(target.holdLift, overlayTarget.holdLift);
  assert.equal(target.holdLift, 0);
  assert.equal(target.leave, "vanish");
  assert.equal(target.clickToId, undefined);
  let play = P.beginPlay(target, target.approachX);
  const seen = new Set();
  let stampXMin = Infinity;
  let stampXMax = -Infinity;
  let maxLift = 0;
  for (let i = 0; i < 700 && play.phase !== "done"; i++) {
    seen.add(play.phase);
    play = P.stepPlay(play, 0.05, { x: play.x, lift: play.lift }, [WIN], WORK, 176, { cmd: "idle" });
    maxLift = Math.max(maxLift, play.lift);
    assert.notEqual(play.phase, "cling");
    assert.notEqual(play.phase, "ridge-hold");
    assert.notEqual(play.phase, "coil-hold");
    assert.notEqual(play.phase, "path-walk");
    assert.notEqual(play.phase, "field-hold");
    assert.notEqual(play.phase, "crackle-hop");
    assert.notEqual(play.phase, "charge-bolt");
    assert.notEqual(play.phase, "orbit-loop");
    assert.notEqual(play.phase, "click-hop");
    assert.notEqual(play.phase, "hold-sit");
    assert.notEqual(play.phase, "earth-sit");
    assert.notEqual(play.phase, "ledge-sit");
    assert.notEqual(play.phase, "watch-hold");
    assert.notEqual(play.phase, "stash-cheek");
    assert.notEqual(play.phase, "wheek");
    assert.notEqual(play.phase, "bask");
    assert.notEqual(play.phase, "bask-withdraw");
    assert.notEqual(play.phase, "sill-walk");
    if (play.phase === "thump") {
      stampXMin = Math.min(stampXMin, play.x);
      stampXMax = Math.max(stampXMax, play.x);
      assert.ok(play.lift < 16);
    }
  }
  assert.ok(seen.has("thump-on"));
  assert.ok(seen.has("thump"));
  assert.ok(seen.has("thump-off"));
  assert.ok(stampXMax - stampXMin < 2, "one stamp — not a walk across");
  assert.ok(maxLift > 8, "she hops to the window and hops away");
  assert.ok(maxLift < 40, "never hops onto the frame");
  assert.equal(play.phase, "done");
});

test("the demo window plate walks Clip's stash the same way", () => {
  assert.match(demoSrc, /demoWindow/);
  assert.match(livingSrc, /stash-on|playFor/);
  const overlayTarget = Overlay.pickTarget([WIN], 40, "hamster", WORK, 176, { side: "left" });
  const target = P.pickTarget([WIN], 40, "hamster", WORK, 176, { side: "left" });
  assert.equal(target.kind, overlayTarget.kind);
  assert.equal(target.kind, "stash");
  assert.equal(target.holdX, overlayTarget.holdX);
  assert.equal(target.holdLift, overlayTarget.holdLift);
  assert.ok(target.holdLift > 16);
  assert.equal(target.leave, "pop");
  assert.equal(target.clickToId, undefined);
  let play = P.beginPlay(target, target.approachX);
  const seen = new Set();
  let cheekXMin = Infinity;
  let cheekXMax = -Infinity;
  let maxLift = 0;
  for (let i = 0; i < 700 && play.phase !== "done"; i++) {
    seen.add(play.phase);
    play = P.stepPlay(play, 0.05, { x: play.x, lift: play.lift }, [WIN], WORK, 176, { cmd: "idle" });
    maxLift = Math.max(maxLift, play.lift);
    assert.notEqual(play.phase, "cling");
    assert.notEqual(play.phase, "ridge-hold");
    assert.notEqual(play.phase, "coil-hold");
    assert.notEqual(play.phase, "path-walk");
    assert.notEqual(play.phase, "field-hold");
    assert.notEqual(play.phase, "crackle-hop");
    assert.notEqual(play.phase, "charge-bolt");
    assert.notEqual(play.phase, "orbit-loop");
    assert.notEqual(play.phase, "click-hop");
    assert.notEqual(play.phase, "hold-sit");
    assert.notEqual(play.phase, "earth-sit");
    assert.notEqual(play.phase, "ledge-sit");
    assert.notEqual(play.phase, "watch-hold");
    assert.notEqual(play.phase, "thump");
    assert.notEqual(play.phase, "wheek");
    assert.notEqual(play.phase, "bask");
    assert.notEqual(play.phase, "bask-withdraw");
    assert.notEqual(play.phase, "sill-walk");
    if (play.phase === "stash-cheek") {
      cheekXMin = Math.min(cheekXMin, play.x);
      cheekXMax = Math.max(cheekXMax, play.x);
      assert.ok(play.lift > 16);
    }
  }
  assert.ok(seen.has("stash-on"));
  assert.ok(seen.has("stash-cheek"));
  assert.ok(seen.has("stash-off"));
  assert.ok(cheekXMax - cheekXMin < 2, "one hamster to a drawer");
  assert.ok(maxLift > 40, "he hops into the window drawer");
  assert.equal(play.phase, "done");
});

test("the demo window plate walks Whee's wheek the same way", () => {
  assert.match(demoSrc, /demoWindow/);
  assert.match(livingSrc, /wheek-on|playFor/);
  const overlayTarget = Overlay.pickTarget([WIN], 40, "guinea_pig", WORK, 176);
  const target = P.pickTarget([WIN], 40, "guinea_pig", WORK, 176);
  assert.equal(target.kind, overlayTarget.kind);
  assert.equal(target.kind, "wheek");
  assert.equal(target.holdX, overlayTarget.holdX);
  assert.equal(target.holdLift, overlayTarget.holdLift);
  assert.equal(target.holdLift, 0);
  assert.equal(target.leave, "waddle");
  assert.equal(target.clickToId, undefined);
  let play = P.beginPlay(target, target.approachX);
  const seen = new Set();
  let loafXMin = Infinity;
  let loafXMax = -Infinity;
  let wheekXMin = Infinity;
  let wheekXMax = -Infinity;
  let maxLift = 0;
  for (let i = 0; i < 700 && play.phase !== "done"; i++) {
    seen.add(play.phase);
    play = P.stepPlay(play, 0.05, { x: play.x, lift: play.lift }, [WIN], WORK, 176, { cmd: "idle" });
    maxLift = Math.max(maxLift, play.lift);
    assert.notEqual(play.phase, "cling");
    assert.notEqual(play.phase, "ridge-hold");
    assert.notEqual(play.phase, "coil-hold");
    assert.notEqual(play.phase, "path-walk");
    assert.notEqual(play.phase, "field-hold");
    assert.notEqual(play.phase, "crackle-hop");
    assert.notEqual(play.phase, "charge-bolt");
    assert.notEqual(play.phase, "orbit-loop");
    assert.notEqual(play.phase, "click-hop");
    assert.notEqual(play.phase, "hold-sit");
    assert.notEqual(play.phase, "earth-sit");
    assert.notEqual(play.phase, "ledge-sit");
    assert.notEqual(play.phase, "watch-hold");
    assert.notEqual(play.phase, "thump");
    assert.notEqual(play.phase, "stash-cheek");
    assert.notEqual(play.phase, "bask");
    assert.notEqual(play.phase, "bask-withdraw");
    assert.notEqual(play.phase, "sill-walk");
    if (play.phase === "wheek-loaf") {
      loafXMin = Math.min(loafXMin, play.x);
      loafXMax = Math.max(loafXMax, play.x);
      assert.equal(play.lift, 0);
      assert.equal(play.rot, 0);
      assert.equal(play.anim, "sit");
    }
    if (play.phase === "wheek") {
      wheekXMin = Math.min(wheekXMin, play.x);
      wheekXMax = Math.max(wheekXMax, play.x);
      assert.equal(play.anim, "talk");
      assert.equal(play.rot, 0);
    }
  }
  assert.ok(seen.has("wheek-on"));
  assert.ok(seen.has("wheek-loaf"));
  assert.ok(seen.has("wheek"));
  assert.ok(seen.has("wheek-pop"));
  assert.ok(seen.has("wheek-off"));
  assert.ok(loafXMax - loafXMin < 2, "one loaf — not a walk across");
  assert.ok(wheekXMax - wheekXMin < 2, "one wheek — she meant you");
  assert.ok(maxLift > 16, "one popcorn hop of joy");
  assert.ok(maxLift < 40, "never hops onto the frame");
  assert.equal(play.phase, "done");
});

test("the demo window plate walks Ink's bask the same way", () => {
  assert.match(demoSrc, /demoWindow/);
  assert.match(livingSrc, /bask-on|playFor/);
  const overlayTarget = Overlay.pickTarget([WIN], 40, "turtle", WORK, 176);
  const target = P.pickTarget([WIN], 40, "turtle", WORK, 176);
  assert.equal(target.kind, overlayTarget.kind);
  assert.equal(target.kind, "bask");
  assert.equal(target.side, "rail");
  assert.equal(target.holdX, overlayTarget.holdX);
  assert.equal(target.holdLift, overlayTarget.holdLift);
  assert.ok(target.holdLift > 16);
  assert.equal(target.leave, "slide");
  assert.equal(target.clickToId, undefined);
  const earth = P.earthPoint(WIN, 176, WORK);
  assert.ok(target.holdLift > earth.lift, "on the rail, not below the frame");
  let play = P.beginPlay(target, target.approachX);
  const seen = new Set();
  let withdrawXMin = Infinity;
  let withdrawXMax = -Infinity;
  let sitLift = 0;
  for (let i = 0; i < 800 && play.phase !== "done"; i++) {
    seen.add(play.phase);
    play = P.stepPlay(play, 0.05, { x: play.x, lift: play.lift }, [WIN], WORK, 176, { cmd: "idle" });
    assert.notEqual(play.phase, "cling");
    assert.notEqual(play.phase, "ridge-hold");
    assert.notEqual(play.phase, "coil-hold");
    assert.notEqual(play.phase, "path-walk");
    assert.notEqual(play.phase, "field-hold");
    assert.notEqual(play.phase, "crackle-hop");
    assert.notEqual(play.phase, "charge-bolt");
    assert.notEqual(play.phase, "orbit-loop");
    assert.notEqual(play.phase, "click-hop");
    assert.notEqual(play.phase, "hold-sit");
    assert.notEqual(play.phase, "earth-sit");
    assert.notEqual(play.phase, "ledge-sit");
    assert.notEqual(play.phase, "watch-hold");
    assert.notEqual(play.phase, "thump");
    assert.notEqual(play.phase, "stash-cheek");
    assert.notEqual(play.phase, "wheek");
    assert.notEqual(play.phase, "sill-walk");
    assert.notEqual(play.phase, "circle");
    assert.notEqual(play.phase, "circle-on");
    if (play.phase === "bask") {
      sitLift = play.lift;
      assert.equal(play.anim, "sit");
      assert.ok(play.lift > earth.lift);
    }
    if (play.phase === "bask-withdraw") {
      withdrawXMin = Math.min(withdrawXMin, play.x);
      withdrawXMax = Math.max(withdrawXMax, play.x);
      assert.equal(play.anim, "sit");
      assert.equal(play.rot, 0);
    }
  }
  assert.ok(seen.has("bask-on"));
  assert.ok(seen.has("bask"));
  assert.ok(seen.has("bask-withdraw"));
  assert.ok(seen.has("bask-off"));
  assert.ok(sitLift > earth.lift, "the stone is on the rail");
  assert.ok(withdrawXMax - withdrawXMin < 12, "the head tucks; he does not walk the rail");
  assert.equal(play.phase, "done");
});

test("the demo window plate walks Coin's circle the same way", () => {
  assert.match(demoSrc, /demoWindow/);
  assert.match(livingSrc, /circle-on|playFor/);
  const overlayTarget = Overlay.pickTarget([WIN], 40, "goldfish", WORK, 176);
  const target = P.pickTarget([WIN], 40, "goldfish", WORK, 176);
  assert.equal(target.kind, overlayTarget.kind);
  assert.equal(target.kind, "circle");
  assert.equal(target.side, "bowl");
  assert.equal(target.holdX, overlayTarget.holdX);
  assert.equal(target.holdLift, overlayTarget.holdLift);
  assert.ok(target.holdLift > 16);
  assert.equal(target.leave, "drift");
  assert.equal(target.clickToId, undefined);
  const field = P.fieldPoint(WIN, 176, WORK);
  const orbit = Overlay.orbitPoint(WIN, 0, 176, WORK, 1);
  const bask = P.baskPoint(WIN, 176, WORK);
  assert.ok(Math.abs(target.holdX - field.x) > 40 || Math.abs(target.holdLift - field.lift) > 20, "not Flux");
  assert.ok(Math.abs(target.holdX - orbit.x) > 40, "not Gauss");
  assert.ok(Math.abs(target.holdLift - bask.lift) > 40, "not Ink");
  let play = P.beginPlay(target, target.approachX);
  const seen = new Set();
  let circleXMin = Infinity;
  let circleXMax = -Infinity;
  let circleLiftMin = Infinity;
  let circleLiftMax = -Infinity;
  for (let i = 0; i < 800 && play.phase !== "done"; i++) {
    seen.add(play.phase);
    play = P.stepPlay(play, 0.05, { x: play.x, lift: play.lift }, [WIN], WORK, 176, { cmd: "idle" });
    assert.notEqual(play.phase, "cling");
    assert.notEqual(play.phase, "ridge-hold");
    assert.notEqual(play.phase, "coil-hold");
    assert.notEqual(play.phase, "path-walk");
    assert.notEqual(play.phase, "field-hold");
    assert.notEqual(play.phase, "crackle-hop");
    assert.notEqual(play.phase, "charge-bolt");
    assert.notEqual(play.phase, "orbit-loop");
    assert.notEqual(play.phase, "click-hop");
    assert.notEqual(play.phase, "hold-sit");
    assert.notEqual(play.phase, "earth-sit");
    assert.notEqual(play.phase, "ledge-sit");
    assert.notEqual(play.phase, "watch-hold");
    assert.notEqual(play.phase, "thump");
    assert.notEqual(play.phase, "stash-cheek");
    assert.notEqual(play.phase, "wheek");
    assert.notEqual(play.phase, "bask");
    assert.notEqual(play.phase, "bask-withdraw");
    assert.notEqual(play.phase, "perch-talk");
    assert.notEqual(play.phase, "sill-walk");
    if (play.phase === "circle") {
      circleXMin = Math.min(circleXMin, play.x);
      circleXMax = Math.max(circleXMax, play.x);
      circleLiftMin = Math.min(circleLiftMin, play.lift);
      circleLiftMax = Math.max(circleLiftMax, play.lift);
      assert.equal(play.anim, "play");
      assert.equal(play.rot, 0);
    }
  }
  assert.ok(seen.has("circle-on"));
  assert.ok(seen.has("circle"));
  assert.ok(seen.has("circle-off"));
  assert.ok(circleXMax - circleXMin > 40, "one thought crosses the bowl");
  assert.ok(circleLiftMax - circleLiftMin > 40, "the circle changes height");
  assert.equal(play.phase, "done");
});

test("the demo window plate walks Echo's perch the same way", () => {
  assert.match(demoSrc, /demoWindow/);
  assert.match(livingSrc, /perch-on|playFor/);
  const overlayTarget = Overlay.pickTarget([WIN], 40, "budgie", WORK, 176, { side: "left" });
  const target = P.pickTarget([WIN], 40, "budgie", WORK, 176, { side: "left" });
  assert.equal(target.kind, overlayTarget.kind);
  assert.equal(target.kind, "perch");
  assert.equal(target.side, "left");
  assert.equal(target.holdX, overlayTarget.holdX);
  assert.equal(target.holdLift, overlayTarget.holdLift);
  assert.ok(target.holdLift > 16);
  assert.equal(target.leave, "hop");
  assert.equal(target.clickToId, undefined);
  const ledge = P.ledgePoint(WIN, 176, WORK);
  const cling = P.sideHold(WIN, "left", 176, WORK);
  const circle = P.circlePoint(WIN, 0, 176, WORK, 1);
  const sill = P.sillPoint(WIN, 0.12, 176, WORK);
  assert.ok(Math.abs(target.holdLift - ledge.lift) > 40, "not Miso");
  assert.ok(Math.abs(target.holdX - cling.x) > 20 || Math.abs(target.holdLift - cling.lift) > 20, "not Rui");
  assert.ok(Math.abs(target.holdX - circle.x) > 20 || Math.abs(target.holdLift - circle.lift) > 20, "not Coin");
  assert.ok(Math.abs(target.holdLift - sill.lift) > 40, "not a generic sill");
  let play = P.beginPlay(target, target.approachX);
  const seen = new Set();
  let talkXMin = Infinity;
  let talkXMax = -Infinity;
  for (let i = 0; i < 800 && play.phase !== "done"; i++) {
    seen.add(play.phase);
    play = P.stepPlay(play, 0.05, { x: play.x, lift: play.lift }, [WIN], WORK, 176, { cmd: "idle" });
    assert.notEqual(play.phase, "cling");
    assert.notEqual(play.phase, "ridge-hold");
    assert.notEqual(play.phase, "coil-hold");
    assert.notEqual(play.phase, "path-walk");
    assert.notEqual(play.phase, "field-hold");
    assert.notEqual(play.phase, "crackle-hop");
    assert.notEqual(play.phase, "charge-bolt");
    assert.notEqual(play.phase, "orbit-loop");
    assert.notEqual(play.phase, "click-hop");
    assert.notEqual(play.phase, "hold-sit");
    assert.notEqual(play.phase, "earth-sit");
    assert.notEqual(play.phase, "ledge-sit");
    assert.notEqual(play.phase, "watch-hold");
    assert.notEqual(play.phase, "thump");
    assert.notEqual(play.phase, "stash-cheek");
    assert.notEqual(play.phase, "wheek");
    assert.notEqual(play.phase, "bask");
    assert.notEqual(play.phase, "bask-withdraw");
    assert.notEqual(play.phase, "circle");
    assert.notEqual(play.phase, "scent");
    assert.notEqual(play.phase, "sill-walk");
    if (play.phase === "perch-talk") {
      talkXMin = Math.min(talkXMin, play.x);
      talkXMax = Math.max(talkXMax, play.x);
      assert.equal(play.anim, "talk");
      assert.ok(play.lift > 16);
    }
  }
  assert.ok(seen.has("perch-on"));
  assert.ok(seen.has("perch-talk"));
  assert.ok(seen.has("perch-off"));
  assert.ok(talkXMax - talkXMin < 2, "one perch — not a walk across");
  assert.equal(play.phase, "done");
});

test("the demo window plate walks Rue's scent the same way", () => {
  assert.match(demoSrc, /demoWindow/);
  assert.match(livingSrc, /scent-on|playFor/);
  const overlayTarget = Overlay.pickTarget([WIN], 40, "fox", WORK, 176, { side: "left" });
  const target = P.pickTarget([WIN], 40, "fox", WORK, 176, { side: "left" });
  assert.equal(target.kind, overlayTarget.kind);
  assert.equal(target.kind, "scent");
  assert.equal(target.side, "left");
  assert.equal(target.holdX, overlayTarget.holdX);
  assert.equal(target.holdLift, overlayTarget.holdLift);
  assert.equal(target.holdLift, 0);
  assert.equal(target.leave, "slip");
  assert.equal(target.clickToId, undefined);
  const perch = P.perchPoint(WIN, "left", 176, WORK);
  const watch = P.watchPoint(WIN, 176, WORK);
  const thump = P.thumpPoint(WIN, 176, WORK, "left");
  const ledge = P.ledgePoint(WIN, 176, WORK);
  const cling = P.sideHold(WIN, "left", 176, WORK);
  const sill = P.sillPoint(WIN, 0.12, 176, WORK);
  assert.ok(Math.abs(target.holdLift - perch.lift) > 20, "not Echo");
  assert.ok(Math.abs(target.holdX - watch.x) > 20, "not Pip");
  assert.ok(Math.abs(target.holdX - thump.x) > 12, "not Thimble");
  assert.ok(Math.abs(target.holdLift - ledge.lift) > 40, "not Miso");
  assert.ok(Math.abs(target.holdLift - cling.lift) > 20, "not Rui");
  assert.ok(Math.abs(target.holdLift - sill.lift) > 16, "not a generic sill");
  let play = P.beginPlay(target, target.approachX);
  const seen = new Set();
  let scentXMin = Infinity;
  let scentXMax = -Infinity;
  for (let i = 0; i < 800 && play.phase !== "done"; i++) {
    seen.add(play.phase);
    play = P.stepPlay(play, 0.05, { x: play.x, lift: play.lift }, [WIN], WORK, 176, { cmd: "idle" });
    assert.notEqual(play.phase, "cling");
    assert.notEqual(play.phase, "ridge-hold");
    assert.notEqual(play.phase, "coil-hold");
    assert.notEqual(play.phase, "path-walk");
    assert.notEqual(play.phase, "field-hold");
    assert.notEqual(play.phase, "crackle-hop");
    assert.notEqual(play.phase, "charge-bolt");
    assert.notEqual(play.phase, "orbit-loop");
    assert.notEqual(play.phase, "click-hop");
    assert.notEqual(play.phase, "hold-sit");
    assert.notEqual(play.phase, "earth-sit");
    assert.notEqual(play.phase, "ledge-sit");
    assert.notEqual(play.phase, "watch-hold");
    assert.notEqual(play.phase, "thump");
    assert.notEqual(play.phase, "stash-cheek");
    assert.notEqual(play.phase, "wheek");
    assert.notEqual(play.phase, "bask");
    assert.notEqual(play.phase, "circle");
    assert.notEqual(play.phase, "perch-talk");
    assert.notEqual(play.phase, "sill-walk");
    if (play.phase === "scent") {
      scentXMin = Math.min(scentXMin, play.x);
      scentXMax = Math.max(scentXMax, play.x);
      assert.equal(play.anim, "sit");
      assert.ok(play.lift < 12);
    }
  }
  assert.ok(seen.has("scent-on"));
  assert.ok(seen.has("scent"));
  assert.ok(seen.has("scent-off"));
  assert.ok(scentXMax - scentXMin > 2, "the nose works the crack");
  assert.ok(scentXMax - scentXMin < 28, "one jamb — not a walk across");
  assert.equal(play.phase, "done");
});

test("the demo window plate walks Peck's bow the same way", () => {
  assert.match(demoSrc, /demoWindow/);
  assert.match(livingSrc, /bow-on|playFor/);
  const overlayTarget = Overlay.pickTarget([WIN], 40, "penguin", WORK, 176);
  const target = P.pickTarget([WIN], 40, "penguin", WORK, 176);
  assert.equal(target.kind, overlayTarget.kind);
  assert.equal(target.kind, "bow");
  assert.equal(target.side, "pane");
  assert.equal(target.holdX, overlayTarget.holdX);
  assert.equal(target.holdLift, overlayTarget.holdLift);
  assert.ok(target.holdLift > 16);
  assert.equal(target.leave, "hop");
  assert.equal(target.clickToId, undefined);
  const scent = P.scentPoint(WIN, "left", 176, WORK);
  const perch = P.perchPoint(WIN, "left", 176, WORK);
  const watch = P.watchPoint(WIN, 176, WORK);
  const ledge = P.ledgePoint(WIN, 176, WORK);
  const circle = P.circlePoint(WIN, 0, 176, WORK, 1);
  const bask = P.baskPoint(WIN, 176, WORK);
  const sill = P.sillPoint(WIN, 0.12, 176, WORK);
  const ridge = P.ridgePoint(WIN, 0.5, 176, WORK);
  assert.ok(Math.abs(target.holdLift - scent.lift) > 16, "not Rue");
  assert.ok(Math.abs(target.holdX - perch.x) > 20 || Math.abs(target.holdLift - perch.lift) > 20, "not Echo");
  assert.ok(target.holdLift !== 0 && Math.abs(target.holdX - watch.x) > 20, "not Pip");
  assert.ok(Math.abs(target.holdLift - ledge.lift) > 40, "not Miso");
  assert.ok(Math.abs(target.holdX - circle.x) > 20 || Math.abs(target.holdLift - circle.lift) > 20, "not Coin");
  assert.ok(Math.abs(target.holdLift - bask.lift) > 20, "not Ink");
  assert.ok(Math.abs(target.holdLift - sill.lift) > 40, "not a generic sill");
  assert.ok(Math.abs(target.holdLift - ridge.lift) > 40, "not Arc");
  let play = P.beginPlay(target, target.approachX);
  const seen = new Set();
  let bowXMin = Infinity;
  let bowXMax = -Infinity;
  let dipRot = 0;
  for (let i = 0; i < 800 && play.phase !== "done"; i++) {
    seen.add(play.phase);
    play = P.stepPlay(play, 0.05, { x: play.x, lift: play.lift }, [WIN], WORK, 176, { cmd: "idle" });
    assert.notEqual(play.phase, "cling");
    assert.notEqual(play.phase, "ridge-hold");
    assert.notEqual(play.phase, "coil-hold");
    assert.notEqual(play.phase, "path-walk");
    assert.notEqual(play.phase, "field-hold");
    assert.notEqual(play.phase, "crackle-hop");
    assert.notEqual(play.phase, "charge-bolt");
    assert.notEqual(play.phase, "orbit-loop");
    assert.notEqual(play.phase, "click-hop");
    assert.notEqual(play.phase, "hold-sit");
    assert.notEqual(play.phase, "earth-sit");
    assert.notEqual(play.phase, "ledge-sit");
    assert.notEqual(play.phase, "watch-hold");
    assert.notEqual(play.phase, "thump");
    assert.notEqual(play.phase, "stash-cheek");
    assert.notEqual(play.phase, "wheek");
    assert.notEqual(play.phase, "bask");
    assert.notEqual(play.phase, "circle");
    assert.notEqual(play.phase, "perch-talk");
    assert.notEqual(play.phase, "scent");
    assert.notEqual(play.phase, "hook");
    assert.notEqual(play.phase, "sill-walk");
    if (play.phase === "bow-stand") {
      assert.equal(play.anim, "sit");
      assert.equal(play.rot, 0);
    }
    if (play.phase === "bow") {
      bowXMin = Math.min(bowXMin, play.x);
      bowXMax = Math.max(bowXMax, play.x);
      dipRot = Math.max(dipRot, Math.abs(play.rot));
      assert.equal(play.anim, "play");
    }
  }
  assert.ok(seen.has("bow-on"));
  assert.ok(seen.has("bow-stand"));
  assert.ok(seen.has("bow"));
  assert.ok(seen.has("bow-off"));
  assert.ok(bowXMax - bowXMin < 2, "one rock — not a walk across");
  assert.ok(dipRot > 6, "the bow is visible");
  assert.equal(play.phase, "done");
});

test("the demo window plate walks Quill's hook the same way", () => {
  assert.match(demoSrc, /demoWindow/);
  assert.match(livingSrc, /hook-on|playFor/);
  const overlayTarget = Overlay.pickTarget([WIN], 40, "parrot", WORK, 176, { side: "left" });
  const target = P.pickTarget([WIN], 40, "parrot", WORK, 176, { side: "left" });
  assert.equal(target.kind, overlayTarget.kind);
  assert.equal(target.kind, "hook");
  assert.equal(target.side, "left");
  assert.equal(target.holdX, overlayTarget.holdX);
  assert.equal(target.holdLift, overlayTarget.holdLift);
  assert.ok(target.holdLift > 16);
  assert.equal(target.leave, "drop");
  assert.equal(target.clickToId, undefined);
  const bow = P.bowPoint(WIN, 176, WORK);
  const scent = P.scentPoint(WIN, "left", 176, WORK);
  const perch = P.perchPoint(WIN, "left", 176, WORK);
  const watch = P.watchPoint(WIN, 176, WORK);
  const ledge = P.ledgePoint(WIN, 176, WORK);
  const circle = P.circlePoint(WIN, 0, 176, WORK, 1);
  const bask = P.baskPoint(WIN, 176, WORK);
  const sill = P.sillPoint(WIN, 0.12, 176, WORK);
  const cling = P.sideHold(WIN, "left", 176, WORK);
  assert.ok(Math.abs(target.holdX - bow.x) > 20 || Math.abs(target.holdLift - bow.lift) > 20, "not Peck");
  assert.ok(Math.abs(target.holdLift - scent.lift) > 16, "not Rue");
  assert.ok(Math.abs(target.holdX - perch.x) > 20 || Math.abs(target.holdLift - perch.lift) > 20, "not Echo");
  assert.ok(target.holdLift !== 0 && Math.abs(target.holdX - watch.x) > 20, "not Pip");
  assert.ok(Math.abs(target.holdLift - ledge.lift) > 40, "not Miso");
  assert.ok(Math.abs(target.holdX - circle.x) > 20 || Math.abs(target.holdLift - circle.lift) > 20, "not Coin");
  assert.ok(Math.abs(target.holdLift - bask.lift) > 20, "not Ink");
  assert.ok(Math.abs(target.holdX - cling.x) > 20 || Math.abs(target.holdLift - cling.lift) > 20, "not Rui");
  assert.ok(Math.abs(target.holdLift - sill.lift) > 40, "not a generic sill");
  let play = P.beginPlay(target, target.approachX);
  const seen = new Set();
  let climbLiftMin = Infinity;
  let climbLiftMax = -Infinity;
  let quoteXMin = Infinity;
  let quoteXMax = -Infinity;
  let hangRot = 0;
  for (let i = 0; i < 800 && play.phase !== "done"; i++) {
    seen.add(play.phase);
    play = P.stepPlay(play, 0.05, { x: play.x, lift: play.lift }, [WIN], WORK, 176, { cmd: "idle" });
    assert.notEqual(play.phase, "cling");
    assert.notEqual(play.phase, "ridge-hold");
    assert.notEqual(play.phase, "coil-hold");
    assert.notEqual(play.phase, "path-walk");
    assert.notEqual(play.phase, "field-hold");
    assert.notEqual(play.phase, "crackle-hop");
    assert.notEqual(play.phase, "charge-bolt");
    assert.notEqual(play.phase, "orbit-loop");
    assert.notEqual(play.phase, "click-hop");
    assert.notEqual(play.phase, "hold-sit");
    assert.notEqual(play.phase, "earth-sit");
    assert.notEqual(play.phase, "ledge-sit");
    assert.notEqual(play.phase, "watch-hold");
    assert.notEqual(play.phase, "thump");
    assert.notEqual(play.phase, "stash-cheek");
    assert.notEqual(play.phase, "wheek");
    assert.notEqual(play.phase, "bask");
    assert.notEqual(play.phase, "circle");
    assert.notEqual(play.phase, "perch-talk");
    assert.notEqual(play.phase, "scent");
    assert.notEqual(play.phase, "bow");
    assert.notEqual(play.phase, "sill-walk");
    if (play.phase === "hook-climb") {
      climbLiftMin = Math.min(climbLiftMin, play.lift);
      climbLiftMax = Math.max(climbLiftMax, play.lift);
      assert.equal(play.anim, "play");
    }
    if (play.phase === "hook") {
      quoteXMin = Math.min(quoteXMin, play.x);
      quoteXMax = Math.max(quoteXMax, play.x);
      hangRot = Math.max(hangRot, Math.abs(play.rot));
      assert.equal(play.anim, "talk");
      assert.ok(play.lift > 16);
    }
  }
  assert.ok(seen.has("hook-on"));
  assert.ok(seen.has("hook-climb"));
  assert.ok(seen.has("hook"));
  assert.ok(seen.has("hook-off"));
  assert.ok(climbLiftMax - climbLiftMin > 40, "the climb travels the jamb");
  assert.ok(quoteXMax - quoteXMin < 2, "one hang — not a walk across");
  assert.ok(hangRot > 50, "the hang is sideways");
  assert.equal(play.phase, "done");
});

test("the demo window plate walks Wick's thread the same way", () => {
  assert.match(demoSrc, /demoWindow/);
  assert.match(livingSrc, /thread-on|playFor/);
  const overlayTarget = Overlay.pickTarget([WIN], 40, "ferret", WORK, 176, { side: "left" });
  const target = P.pickTarget([WIN], 40, "ferret", WORK, 176, { side: "left" });
  assert.equal(target.kind, overlayTarget.kind);
  assert.equal(target.kind, "thread");
  assert.equal(target.side, "gap");
  assert.equal(target.holdX, overlayTarget.holdX);
  assert.equal(target.holdLift, overlayTarget.holdLift);
  assert.equal(target.threadEndX, overlayTarget.threadEndX);
  assert.ok(target.holdLift > 8);
  assert.equal(target.leave, "dash");
  assert.equal(target.clickToId, undefined);
  const hook = P.hookPoint(WIN, "left", 1, 176, WORK);
  const bow = P.bowPoint(WIN, 176, WORK);
  const scent = P.scentPoint(WIN, "left", 176, WORK);
  const perch = P.perchPoint(WIN, "left", 176, WORK);
  const watch = P.watchPoint(WIN, 176, WORK);
  const ledge = P.ledgePoint(WIN, 176, WORK);
  const stash = P.stashPoint(WIN, "left", 176, WORK);
  const bask = P.baskPoint(WIN, 176, WORK);
  const earth = P.earthPoint(WIN, 176, WORK);
  const sill = P.sillPoint(WIN, 0.12, 176, WORK);
  assert.ok(Math.abs(target.holdX - hook.x) > 20 || Math.abs(target.holdLift - hook.lift) > 20, "not Quill");
  assert.ok(Math.abs(target.holdX - bow.x) > 20 || Math.abs(target.holdLift - bow.lift) > 20, "not Peck");
  assert.ok(Math.abs(target.holdLift - scent.lift) > 16, "not Rue");
  assert.ok(Math.abs(target.holdX - perch.x) > 20 || Math.abs(target.holdLift - perch.lift) > 20, "not Echo");
  assert.ok(target.holdLift !== 0 && Math.abs(target.holdX - watch.x) > 20, "not Pip");
  assert.ok(Math.abs(target.holdLift - ledge.lift) > 40, "not Miso");
  assert.ok(Math.abs(target.holdX - stash.x) > 20, "not Clip");
  assert.ok(Math.abs(target.holdLift - bask.lift) > 20, "not Ink");
  assert.ok(Math.abs(target.holdLift - earth.lift) > 20, "not Ground");
  assert.ok(Math.abs(target.holdLift - sill.lift) > 40, "not a generic sill");
  let play = P.beginPlay(target, target.approachX);
  const seen = new Set();
  let threadXMin = Infinity;
  let threadXMax = -Infinity;
  let wriggle = 0;
  for (let i = 0; i < 800 && play.phase !== "done"; i++) {
    seen.add(play.phase);
    play = P.stepPlay(play, 0.05, { x: play.x, lift: play.lift }, [WIN], WORK, 176, { cmd: "idle" });
    assert.notEqual(play.phase, "cling");
    assert.notEqual(play.phase, "ridge-hold");
    assert.notEqual(play.phase, "coil-hold");
    assert.notEqual(play.phase, "path-walk");
    assert.notEqual(play.phase, "field-hold");
    assert.notEqual(play.phase, "crackle-hop");
    assert.notEqual(play.phase, "charge-bolt");
    assert.notEqual(play.phase, "orbit-loop");
    assert.notEqual(play.phase, "click-hop");
    assert.notEqual(play.phase, "hold-sit");
    assert.notEqual(play.phase, "earth-sit");
    assert.notEqual(play.phase, "ledge-sit");
    assert.notEqual(play.phase, "watch-hold");
    assert.notEqual(play.phase, "thump");
    assert.notEqual(play.phase, "stash-cheek");
    assert.notEqual(play.phase, "wheek");
    assert.notEqual(play.phase, "bask");
    assert.notEqual(play.phase, "circle");
    assert.notEqual(play.phase, "perch-talk");
    assert.notEqual(play.phase, "scent");
    assert.notEqual(play.phase, "bow");
    assert.notEqual(play.phase, "hook");
    assert.notEqual(play.phase, "sill-walk");
    if (play.phase === "thread") {
      threadXMin = Math.min(threadXMin, play.x);
      threadXMax = Math.max(threadXMax, play.x);
      wriggle = Math.max(wriggle, Math.abs(play.rot));
      assert.equal(play.anim, "play");
      assert.ok(play.lift > 8);
    }
  }
  assert.ok(seen.has("thread-on"));
  assert.ok(seen.has("thread"));
  assert.ok(seen.has("thread-off"));
  assert.ok(threadXMax - threadXMin > 80, "he threads the gap");
  assert.ok(wriggle > 4, "the body wriggles");
  assert.equal(play.phase, "done");
});

test("the demo window plate walks Burr's ball the same way", () => {
  assert.match(demoSrc, /demoWindow/);
  assert.match(livingSrc, /ball-on|playFor/);
  assert.match(rosterSrc, /key: "hedgehog"[\s\S]{0,80}slug: "burr"/);
  assert.match(guideSrc, /"hedgehog"/);
  const overlayTarget = Overlay.pickTarget([WIN], 40, "hedgehog", WORK, 176);
  const target = P.pickTarget([WIN], 40, "hedgehog", WORK, 176);
  assert.equal(target.kind, overlayTarget.kind);
  assert.equal(target.kind, "ball");
  assert.equal(target.side, "foot");
  assert.equal(target.holdX, overlayTarget.holdX);
  assert.equal(target.holdLift, overlayTarget.holdLift);
  assert.equal(target.holdLift, 0);
  assert.equal(target.leave, "shuffle");
  assert.equal(target.clickToId, undefined);
  const hook = P.hookPoint(WIN, "left", 1, 176, WORK);
  const bow = P.bowPoint(WIN, 176, WORK);
  const scent = P.scentPoint(WIN, "left", 176, WORK);
  const perch = P.perchPoint(WIN, "left", 176, WORK);
  const watch = P.watchPoint(WIN, 176, WORK);
  const wheek = P.wheekPoint(WIN, 176, WORK);
  const thump = P.thumpPoint(WIN, 176, WORK, "left");
  const ledge = P.ledgePoint(WIN, 176, WORK);
  const stash = P.stashPoint(WIN, "left", 176, WORK);
  const bask = P.baskPoint(WIN, 176, WORK);
  const earth = P.earthPoint(WIN, 176, WORK);
  const thread = P.threadPoint(WIN, 0, 176, WORK);
  const sill = P.sillPoint(WIN, 0.12, 176, WORK);
  assert.ok(Math.abs(target.holdX - watch.x) > 20, "not Pip");
  assert.ok(Math.abs(target.holdX - wheek.x) > 20, "not Whee");
  assert.ok(Math.abs(target.holdX - scent.x) > 20, "not Rue");
  assert.ok(Math.abs(target.holdX - thump.x) > 20, "not Thimble");
  assert.ok(Math.abs(target.holdX - hook.x) > 20 || Math.abs(target.holdLift - hook.lift) > 20, "not Quill");
  assert.ok(Math.abs(target.holdX - bow.x) > 20 || Math.abs(target.holdLift - bow.lift) > 20, "not Peck");
  assert.ok(Math.abs(target.holdX - perch.x) > 20 || Math.abs(target.holdLift - perch.lift) > 20, "not Echo");
  assert.ok(Math.abs(target.holdLift - ledge.lift) > 40, "not Miso");
  assert.ok(Math.abs(target.holdX - stash.x) > 20 || Math.abs(target.holdLift - stash.lift) > 16, "not Clip");
  assert.ok(Math.abs(target.holdLift - bask.lift) > 16, "not Ink");
  assert.ok(Math.abs(target.holdLift - earth.lift) > 16, "not Ground");
  assert.ok(Math.abs(target.holdLift - thread.lift) > 8, "not Wick");
  assert.ok(Math.abs(target.holdLift - sill.lift) > 40, "not a generic sill");
  let play = P.beginPlay(target, target.approachX);
  const seen = new Set();
  let ballXMin = Infinity;
  let ballXMax = -Infinity;
  let snuffle = 0;
  let tuck = 0;
  for (let i = 0; i < 800 && play.phase !== "done"; i++) {
    seen.add(play.phase);
    play = P.stepPlay(play, 0.05, { x: play.x, lift: play.lift }, [WIN], WORK, 176, { cmd: "idle" });
    assert.notEqual(play.phase, "cling");
    assert.notEqual(play.phase, "ridge-hold");
    assert.notEqual(play.phase, "coil-hold");
    assert.notEqual(play.phase, "path-walk");
    assert.notEqual(play.phase, "field-hold");
    assert.notEqual(play.phase, "crackle-hop");
    assert.notEqual(play.phase, "charge-bolt");
    assert.notEqual(play.phase, "orbit-loop");
    assert.notEqual(play.phase, "click-hop");
    assert.notEqual(play.phase, "hold-sit");
    assert.notEqual(play.phase, "earth-sit");
    assert.notEqual(play.phase, "ledge-sit");
    assert.notEqual(play.phase, "watch-hold");
    assert.notEqual(play.phase, "thump");
    assert.notEqual(play.phase, "stash-cheek");
    assert.notEqual(play.phase, "wheek");
    assert.notEqual(play.phase, "bask");
    assert.notEqual(play.phase, "circle");
    assert.notEqual(play.phase, "perch-talk");
    assert.notEqual(play.phase, "scent");
    assert.notEqual(play.phase, "bow");
    assert.notEqual(play.phase, "hook");
    assert.notEqual(play.phase, "thread");
    assert.notEqual(play.phase, "sill-walk");
    if (play.phase === "ball-snuffle") {
      snuffle = Math.max(snuffle, Math.abs(play.x - target.holdX), Math.abs(play.rot));
      assert.equal(play.anim, "play");
    }
    if (play.phase === "ball") {
      ballXMin = Math.min(ballXMin, play.x);
      ballXMax = Math.max(ballXMax, play.x);
      tuck = Math.max(tuck, Math.abs(play.rot));
      assert.equal(play.anim, "sit");
      assert.equal(play.lift, 0);
    }
  }
  assert.ok(seen.has("ball-on"));
  assert.ok(seen.has("ball-snuffle"));
  assert.ok(seen.has("ball"));
  assert.ok(seen.has("ball-off"));
  assert.ok(snuffle > 2, "she snuffles the pane foot");
  assert.ok(ballXMax - ballXMin < 2, "the ball stays put");
  assert.ok(tuck > 10, "she tucks into a ball");
  assert.equal(play.phase, "done");
});

test("the demo window plate walks Floss's dust the same way", () => {
  assert.match(demoSrc, /demoWindow/);
  assert.match(livingSrc, /dust-on|playFor/);
  assert.match(rosterSrc, /key: "chinchilla"[\s\S]{0,80}slug: "floss"/);
  assert.match(guideSrc, /"chinchilla"/);
  const overlayTarget = Overlay.pickTarget([WIN], 40, "chinchilla", WORK, 176);
  const target = P.pickTarget([WIN], 40, "chinchilla", WORK, 176);
  assert.equal(target.kind, overlayTarget.kind);
  assert.equal(target.kind, "dust");
  assert.equal(target.side, "tray");
  assert.equal(target.holdX, overlayTarget.holdX);
  assert.equal(target.holdLift, overlayTarget.holdLift);
  assert.ok(target.holdLift > 36);
  assert.equal(target.leave, "hop");
  assert.equal(target.clickToId, undefined);
  const hook = P.hookPoint(WIN, "left", 1, 176, WORK);
  const bow = P.bowPoint(WIN, 176, WORK);
  const scent = P.scentPoint(WIN, "left", 176, WORK);
  const perch = P.perchPoint(WIN, "left", 176, WORK);
  const watch = P.watchPoint(WIN, 176, WORK);
  const wheek = P.wheekPoint(WIN, 176, WORK);
  const thump = P.thumpPoint(WIN, 176, WORK, "left");
  const ledge = P.ledgePoint(WIN, 176, WORK);
  const stash = P.stashPoint(WIN, "left", 176, WORK);
  const bask = P.baskPoint(WIN, 176, WORK);
  const earth = P.earthPoint(WIN, 176, WORK);
  const thread = P.threadPoint(WIN, 0, 176, WORK);
  const ball = P.ballPoint(WIN, 176, WORK);
  const field = P.fieldPoint(WIN, 176, WORK);
  const sill = P.sillPoint(WIN, 0.12, 176, WORK);
  assert.ok(Math.abs(target.holdX - watch.x) > 20 || Math.abs(target.holdLift - watch.lift) > 20, "not Pip");
  assert.ok(Math.abs(target.holdX - wheek.x) > 20 || Math.abs(target.holdLift - wheek.lift) > 20, "not Whee");
  assert.ok(Math.abs(target.holdX - scent.x) > 20 || Math.abs(target.holdLift - scent.lift) > 20, "not Rue");
  assert.ok(Math.abs(target.holdX - thump.x) > 20 || Math.abs(target.holdLift - thump.lift) > 20, "not Thimble");
  assert.ok(Math.abs(target.holdX - hook.x) > 20 || Math.abs(target.holdLift - hook.lift) > 20, "not Quill");
  assert.ok(Math.abs(target.holdX - bow.x) > 20 || Math.abs(target.holdLift - bow.lift) > 20, "not Peck");
  assert.ok(Math.abs(target.holdX - perch.x) > 20 || Math.abs(target.holdLift - perch.lift) > 20, "not Echo");
  assert.ok(Math.abs(target.holdLift - ledge.lift) > 40, "not Miso");
  assert.ok(Math.abs(target.holdX - stash.x) > 20 || Math.abs(target.holdLift - stash.lift) > 16, "not Clip");
  assert.ok(Math.abs(target.holdLift - bask.lift) > 16, "not Ink");
  assert.ok(Math.abs(target.holdLift - earth.lift) > 16, "not Ground");
  assert.ok(Math.abs(target.holdLift - thread.lift) > 8, "not Wick");
  assert.ok(Math.abs(target.holdLift - ball.lift) > 20, "not Burr");
  assert.ok(Math.abs(target.holdX - field.x) > 20 || Math.abs(target.holdLift - field.lift) > 20, "not Flux");
  assert.ok(Math.abs(target.holdLift - sill.lift) > 40, "not a generic sill");
  let play = P.beginPlay(target, target.approachX);
  const seen = new Set();
  let dustXMin = Infinity;
  let dustXMax = -Infinity;
  let roll = 0;
  let fluff = 0;
  for (let i = 0; i < 800 && play.phase !== "done"; i++) {
    seen.add(play.phase);
    play = P.stepPlay(play, 0.05, { x: play.x, lift: play.lift }, [WIN], WORK, 176, { cmd: "idle" });
    assert.notEqual(play.phase, "cling");
    assert.notEqual(play.phase, "ridge-hold");
    assert.notEqual(play.phase, "coil-hold");
    assert.notEqual(play.phase, "path-walk");
    assert.notEqual(play.phase, "field-hold");
    assert.notEqual(play.phase, "crackle-hop");
    assert.notEqual(play.phase, "charge-bolt");
    assert.notEqual(play.phase, "orbit-loop");
    assert.notEqual(play.phase, "click-hop");
    assert.notEqual(play.phase, "hold-sit");
    assert.notEqual(play.phase, "earth-sit");
    assert.notEqual(play.phase, "ledge-sit");
    assert.notEqual(play.phase, "watch-hold");
    assert.notEqual(play.phase, "thump");
    assert.notEqual(play.phase, "stash-cheek");
    assert.notEqual(play.phase, "wheek");
    assert.notEqual(play.phase, "bask");
    assert.notEqual(play.phase, "circle");
    assert.notEqual(play.phase, "perch-talk");
    assert.notEqual(play.phase, "scent");
    assert.notEqual(play.phase, "bow");
    assert.notEqual(play.phase, "hook");
    assert.notEqual(play.phase, "thread");
    assert.notEqual(play.phase, "ball");
    assert.notEqual(play.phase, "sill-walk");
    if (play.phase === "dust") {
      dustXMin = Math.min(dustXMin, play.x);
      dustXMax = Math.max(dustXMax, play.x);
      roll = Math.max(roll, Math.abs(play.rot));
      assert.equal(play.anim, "play");
      assert.ok(play.lift > 36);
    }
    if (play.phase === "dust-fluff") {
      fluff = Math.max(fluff, play.lift - target.holdLift, Math.abs(play.rot));
      assert.equal(play.anim, "play");
    }
  }
  assert.ok(seen.has("dust-on"));
  assert.ok(seen.has("dust"));
  assert.ok(seen.has("dust-fluff"));
  assert.ok(seen.has("dust-off"));
  assert.ok(roll > 30, "she rolls in the sash-dust");
  assert.ok(dustXMax - dustXMin < 24, "the roll stays on the tray");
  assert.ok(fluff > 2, "she fluffs the coat");
  assert.equal(play.phase, "done");
});

test("the demo window plate walks Bloom's tank wall the same way", () => {
  assert.match(demoSrc, /demoWindow/);
  assert.match(livingSrc, /wall-on|playFor/);
  assert.match(rosterSrc, /key: "axolotl"[\s\S]{0,80}slug: "bloom"/);
  assert.match(guideSrc, /"axolotl"/);
  const overlayTarget = Overlay.pickTarget([WIN], 40, "axolotl", WORK, 176);
  const target = P.pickTarget([WIN], 40, "axolotl", WORK, 176);
  assert.equal(target.kind, overlayTarget.kind);
  assert.equal(target.kind, "wall");
  assert.equal(target.side, "tank");
  assert.equal(target.holdX, overlayTarget.holdX);
  assert.equal(target.holdLift, overlayTarget.holdLift);
  assert.equal(target.wallEndX, overlayTarget.wallEndX);
  assert.equal(target.wallEndLift, overlayTarget.wallEndLift);
  assert.ok(target.holdLift > 36);
  assert.ok(target.wallEndLift > target.holdLift + 40, "the walk goes up the pane");
  assert.equal(target.leave, "sink");
  assert.equal(target.clickToId, undefined);
  const hook = P.hookPoint(WIN, "left", 1, 176, WORK);
  const bow = P.bowPoint(WIN, 176, WORK);
  const scent = P.scentPoint(WIN, "left", 176, WORK);
  const perch = P.perchPoint(WIN, "left", 176, WORK);
  const watch = P.watchPoint(WIN, 176, WORK);
  const wheek = P.wheekPoint(WIN, 176, WORK);
  const thump = P.thumpPoint(WIN, 176, WORK, "left");
  const ledge = P.ledgePoint(WIN, 176, WORK);
  const stash = P.stashPoint(WIN, "left", 176, WORK);
  const bask = P.baskPoint(WIN, 176, WORK);
  const earth = P.earthPoint(WIN, 176, WORK);
  const thread = P.threadPoint(WIN, 0, 176, WORK);
  const ball = P.ballPoint(WIN, 176, WORK);
  const field = P.fieldPoint(WIN, 176, WORK);
  const circle = P.circlePoint(WIN, 0, 176, WORK, 1);
  const dust = P.dustPoint(WIN, 176, WORK);
  const sill = P.sillPoint(WIN, 0.12, 176, WORK);
  assert.ok(Math.abs(target.holdX - watch.x) > 20 || Math.abs(target.holdLift - watch.lift) > 20, "not Pip");
  assert.ok(Math.abs(target.holdX - wheek.x) > 20 || Math.abs(target.holdLift - wheek.lift) > 20, "not Whee");
  assert.ok(Math.abs(target.holdX - scent.x) > 20 || Math.abs(target.holdLift - scent.lift) > 20, "not Rue");
  assert.ok(Math.abs(target.holdX - thump.x) > 20 || Math.abs(target.holdLift - thump.lift) > 20, "not Thimble");
  assert.ok(Math.abs(target.holdX - hook.x) > 20 || Math.abs(target.holdLift - hook.lift) > 20, "not Quill");
  assert.ok(Math.abs(target.holdX - bow.x) > 20 || Math.abs(target.holdLift - bow.lift) > 20, "not Peck");
  assert.ok(Math.abs(target.holdX - perch.x) > 20 || Math.abs(target.holdLift - perch.lift) > 20, "not Echo");
  assert.ok(Math.abs(target.holdLift - ledge.lift) > 40, "not Miso");
  assert.ok(Math.abs(target.holdX - stash.x) > 20 || Math.abs(target.holdLift - stash.lift) > 16, "not Clip");
  assert.ok(Math.abs(target.holdLift - bask.lift) > 16, "not Ink");
  assert.ok(Math.abs(target.holdLift - earth.lift) > 16, "not Ground");
  assert.ok(Math.abs(target.holdLift - thread.lift) > 8, "not Wick");
  assert.ok(Math.abs(target.holdLift - ball.lift) > 20, "not Burr");
  assert.ok(Math.abs(target.holdX - field.x) > 20 || Math.abs(target.holdLift - field.lift) > 20, "not Flux");
  assert.ok(Math.abs(target.holdX - circle.x) > 20 || Math.abs(target.holdLift - circle.lift) > 20, "not Coin");
  assert.ok(Math.abs(target.holdX - dust.x) > 20 || Math.abs(target.holdLift - dust.lift) > 20, "not Floss");
  assert.ok(Math.abs(target.holdLift - sill.lift) > 40, "not a generic sill");
  let play = P.beginPlay(target, target.approachX);
  const seen = new Set();
  let wallXMin = Infinity;
  let wallXMax = -Infinity;
  let wallLiftMin = Infinity;
  let wallLiftMax = -Infinity;
  for (let i = 0; i < 800 && play.phase !== "done"; i++) {
    seen.add(play.phase);
    play = P.stepPlay(play, 0.05, { x: play.x, lift: play.lift }, [WIN], WORK, 176, { cmd: "idle" });
    assert.notEqual(play.phase, "cling");
    assert.notEqual(play.phase, "ridge-hold");
    assert.notEqual(play.phase, "coil-hold");
    assert.notEqual(play.phase, "path-walk");
    assert.notEqual(play.phase, "field-hold");
    assert.notEqual(play.phase, "crackle-hop");
    assert.notEqual(play.phase, "charge-bolt");
    assert.notEqual(play.phase, "orbit-loop");
    assert.notEqual(play.phase, "click-hop");
    assert.notEqual(play.phase, "hold-sit");
    assert.notEqual(play.phase, "earth-sit");
    assert.notEqual(play.phase, "ledge-sit");
    assert.notEqual(play.phase, "watch-hold");
    assert.notEqual(play.phase, "thump");
    assert.notEqual(play.phase, "stash-cheek");
    assert.notEqual(play.phase, "wheek");
    assert.notEqual(play.phase, "bask");
    assert.notEqual(play.phase, "circle");
    assert.notEqual(play.phase, "perch-talk");
    assert.notEqual(play.phase, "scent");
    assert.notEqual(play.phase, "bow");
    assert.notEqual(play.phase, "hook");
    assert.notEqual(play.phase, "thread");
    assert.notEqual(play.phase, "ball");
    assert.notEqual(play.phase, "dust");
    assert.notEqual(play.phase, "sill-walk");
    if (play.phase === "wall") {
      wallXMin = Math.min(wallXMin, play.x);
      wallXMax = Math.max(wallXMax, play.x);
      wallLiftMin = Math.min(wallLiftMin, play.lift);
      wallLiftMax = Math.max(wallLiftMax, play.lift);
      assert.equal(play.anim, "walk");
      assert.ok(play.lift > 36);
    }
  }
  assert.ok(seen.has("wall-on"));
  assert.ok(seen.has("wall"));
  assert.ok(seen.has("wall-off"));
  assert.ok(wallLiftMax - wallLiftMin > 40, "she walks the pane as a tank wall");
  assert.ok(wallXMax - wallXMin < 24, "the walk stays on one wall — not a circle");
  assert.equal(play.phase, "done");
});

test("the demo window plate walks Keel's toss the same way", () => {
  assert.match(demoSrc, /demoWindow/);
  assert.match(livingSrc, /toss-on|playFor/);
  assert.match(rosterSrc, /key: "toucan"[\s\S]{0,80}slug: "keel"/);
  assert.match(guideSrc, /"toucan"/);
  const overlayTarget = Overlay.pickTarget([WIN], 40, "toucan", WORK, 176);
  const target = P.pickTarget([WIN], 40, "toucan", WORK, 176);
  assert.equal(target.kind, overlayTarget.kind);
  assert.equal(target.kind, "toss");
  assert.equal(target.side, "cornice");
  assert.equal(target.holdX, overlayTarget.holdX);
  assert.equal(target.holdLift, overlayTarget.holdLift);
  assert.ok(target.holdLift > 36);
  assert.equal(target.leave, "hop");
  assert.equal(target.clickToId, undefined);
  const wall = P.wallPoint(WIN, 0, "left", 176, WORK);
  const hook = P.hookPoint(WIN, "left", 1, 176, WORK);
  const bow = P.bowPoint(WIN, 176, WORK);
  const scent = P.scentPoint(WIN, "left", 176, WORK);
  const perch = P.perchPoint(WIN, "left", 176, WORK);
  const watch = P.watchPoint(WIN, 176, WORK);
  const wheek = P.wheekPoint(WIN, 176, WORK);
  const thump = P.thumpPoint(WIN, 176, WORK, "left");
  const ledge = P.ledgePoint(WIN, 176, WORK);
  const ridge = P.ridgePoint(WIN, 0.5, 176, WORK);
  const stash = P.stashPoint(WIN, "left", 176, WORK);
  const bask = P.baskPoint(WIN, 176, WORK);
  const earth = P.earthPoint(WIN, 176, WORK);
  const thread = P.threadPoint(WIN, 0, 176, WORK);
  const ball = P.ballPoint(WIN, 176, WORK);
  const field = P.fieldPoint(WIN, 176, WORK);
  const circle = P.circlePoint(WIN, 0, 176, WORK, 1);
  const dust = P.dustPoint(WIN, 176, WORK);
  const sill = P.sillPoint(WIN, 0.12, 176, WORK);
  assert.ok(Math.abs(target.holdX - watch.x) > 20 || Math.abs(target.holdLift - watch.lift) > 20, "not Pip");
  assert.ok(Math.abs(target.holdX - wheek.x) > 20 || Math.abs(target.holdLift - wheek.lift) > 20, "not Whee");
  assert.ok(Math.abs(target.holdX - scent.x) > 20 || Math.abs(target.holdLift - scent.lift) > 20, "not Rue");
  assert.ok(Math.abs(target.holdX - thump.x) > 20 || Math.abs(target.holdLift - thump.lift) > 20, "not Thimble");
  assert.ok(Math.abs(target.holdX - hook.x) > 20 || Math.abs(target.holdLift - hook.lift) > 20, "not Quill");
  assert.ok(Math.abs(target.holdX - bow.x) > 20 || Math.abs(target.holdLift - bow.lift) > 20, "not Peck");
  assert.ok(Math.abs(target.holdX - perch.x) > 20 || Math.abs(target.holdLift - perch.lift) > 20, "not Echo");
  assert.ok(Math.abs(target.holdLift - ledge.lift) > 40, "not Miso");
  assert.ok(Math.abs(target.holdLift - ridge.lift) > 40, "not Arc");
  assert.ok(Math.abs(target.holdX - stash.x) > 20 || Math.abs(target.holdLift - stash.lift) > 16, "not Clip");
  assert.ok(Math.abs(target.holdLift - bask.lift) > 16, "not Ink");
  assert.ok(Math.abs(target.holdLift - earth.lift) > 16, "not Ground");
  assert.ok(Math.abs(target.holdLift - thread.lift) > 8, "not Wick");
  assert.ok(Math.abs(target.holdLift - ball.lift) > 20, "not Burr");
  assert.ok(Math.abs(target.holdX - field.x) > 20 || Math.abs(target.holdLift - field.lift) > 20, "not Flux");
  assert.ok(Math.abs(target.holdX - circle.x) > 20 || Math.abs(target.holdLift - circle.lift) > 20, "not Coin");
  assert.ok(Math.abs(target.holdX - dust.x) > 20 || Math.abs(target.holdLift - dust.lift) > 20, "not Floss");
  assert.ok(Math.abs(target.holdX - wall.x) > 20 || Math.abs(target.holdLift - wall.lift) > 20, "not Bloom");
  assert.ok(Math.abs(target.holdLift - sill.lift) > 40, "not a generic sill");
  let play = P.beginPlay(target, target.approachX);
  const seen = new Set();
  let sitXMin = Infinity;
  let sitXMax = -Infinity;
  let tossXMin = Infinity;
  let tossXMax = -Infinity;
  let flickRot = 0;
  for (let i = 0; i < 800 && play.phase !== "done"; i++) {
    seen.add(play.phase);
    play = P.stepPlay(play, 0.05, { x: play.x, lift: play.lift }, [WIN], WORK, 176, { cmd: "idle" });
    assert.notEqual(play.phase, "cling");
    assert.notEqual(play.phase, "ridge-hold");
    assert.notEqual(play.phase, "coil-hold");
    assert.notEqual(play.phase, "path-walk");
    assert.notEqual(play.phase, "field-hold");
    assert.notEqual(play.phase, "crackle-hop");
    assert.notEqual(play.phase, "charge-bolt");
    assert.notEqual(play.phase, "orbit-loop");
    assert.notEqual(play.phase, "click-hop");
    assert.notEqual(play.phase, "hold-sit");
    assert.notEqual(play.phase, "earth-sit");
    assert.notEqual(play.phase, "ledge-sit");
    assert.notEqual(play.phase, "watch-hold");
    assert.notEqual(play.phase, "thump");
    assert.notEqual(play.phase, "stash-cheek");
    assert.notEqual(play.phase, "wheek");
    assert.notEqual(play.phase, "bask");
    assert.notEqual(play.phase, "circle");
    assert.notEqual(play.phase, "perch-talk");
    assert.notEqual(play.phase, "scent");
    assert.notEqual(play.phase, "bow");
    assert.notEqual(play.phase, "hook");
    assert.notEqual(play.phase, "thread");
    assert.notEqual(play.phase, "ball");
    assert.notEqual(play.phase, "dust");
    assert.notEqual(play.phase, "wall");
    assert.notEqual(play.phase, "sill-walk");
    if (play.phase === "toss-sit") {
      sitXMin = Math.min(sitXMin, play.x);
      sitXMax = Math.max(sitXMax, play.x);
      assert.equal(play.anim, "sit");
      assert.ok(play.lift > 36);
    }
    if (play.phase === "toss") {
      tossXMin = Math.min(tossXMin, play.x);
      tossXMax = Math.max(tossXMax, play.x);
      flickRot = Math.max(flickRot, Math.abs(play.rot));
      assert.equal(play.anim, "play");
      assert.ok(play.lift > 16);
    }
  }
  assert.ok(seen.has("toss-on"));
  assert.ok(seen.has("toss-sit"));
  assert.ok(seen.has("toss"));
  assert.ok(seen.has("toss-off"));
  assert.ok(sitXMax - sitXMin < 2, "one cornice — not a walk across");
  assert.ok(tossXMax - tossXMin < 2, "one toss — the bill stays on the branch");
  assert.ok(flickRot > 16, "the toss is visible");
  assert.equal(play.phase, "done");
});

test("the demo window plate walks Sol's flatten the same way", () => {
  assert.match(demoSrc, /demoWindow/);
  assert.match(livingSrc, /flatten-on|playFor/);
  assert.match(rosterSrc, /key: "iguana"[\s\S]{0,80}slug: "sol"/);
  assert.match(guideSrc, /"iguana"/);
  const overlayTarget = Overlay.pickTarget([WIN], 40, "iguana", WORK, 176);
  const target = P.pickTarget([WIN], 40, "iguana", WORK, 176);
  assert.equal(target.kind, overlayTarget.kind);
  assert.equal(target.kind, "flatten");
  assert.equal(target.side, "brick");
  assert.equal(target.holdX, overlayTarget.holdX);
  assert.equal(target.holdLift, overlayTarget.holdLift);
  assert.ok(target.holdLift > 36);
  assert.equal(target.leave, "climb");
  assert.equal(target.clickToId, undefined);
  const toss = P.tossPoint(WIN, "left", 176, WORK);
  const wall = P.wallPoint(WIN, 0, "left", 176, WORK);
  const hook = P.hookPoint(WIN, "left", 1, 176, WORK);
  const bow = P.bowPoint(WIN, 176, WORK);
  const scent = P.scentPoint(WIN, "left", 176, WORK);
  const perch = P.perchPoint(WIN, "left", 176, WORK);
  const watch = P.watchPoint(WIN, 176, WORK);
  const wheek = P.wheekPoint(WIN, 176, WORK);
  const thump = P.thumpPoint(WIN, 176, WORK, "left");
  const ledge = P.ledgePoint(WIN, 176, WORK);
  const ridge = P.ridgePoint(WIN, 0.5, 176, WORK);
  const stash = P.stashPoint(WIN, "left", 176, WORK);
  const bask = P.baskPoint(WIN, 176, WORK);
  const earth = P.earthPoint(WIN, 176, WORK);
  const thread = P.threadPoint(WIN, 0, 176, WORK);
  const ball = P.ballPoint(WIN, 176, WORK);
  const field = P.fieldPoint(WIN, 176, WORK);
  const circle = P.circlePoint(WIN, 0, 176, WORK, 1);
  const dust = P.dustPoint(WIN, 176, WORK);
  const sill = P.sillPoint(WIN, 0.12, 176, WORK);
  assert.ok(Math.abs(target.holdX - watch.x) > 20 || Math.abs(target.holdLift - watch.lift) > 20, "not Pip");
  assert.ok(Math.abs(target.holdX - wheek.x) > 20 || Math.abs(target.holdLift - wheek.lift) > 20, "not Whee");
  assert.ok(Math.abs(target.holdX - scent.x) > 20 || Math.abs(target.holdLift - scent.lift) > 20, "not Rue");
  assert.ok(Math.abs(target.holdX - thump.x) > 20 || Math.abs(target.holdLift - thump.lift) > 20, "not Thimble");
  assert.ok(Math.abs(target.holdX - hook.x) > 20 || Math.abs(target.holdLift - hook.lift) > 20, "not Quill");
  assert.ok(Math.abs(target.holdX - bow.x) > 20 || Math.abs(target.holdLift - bow.lift) > 20, "not Peck");
  assert.ok(Math.abs(target.holdX - perch.x) > 20 || Math.abs(target.holdLift - perch.lift) > 20, "not Echo");
  assert.ok(Math.abs(target.holdLift - ledge.lift) > 40, "not Miso");
  assert.ok(Math.abs(target.holdLift - ridge.lift) > 40, "not Arc");
  assert.ok(Math.abs(target.holdX - stash.x) > 20 || Math.abs(target.holdLift - stash.lift) > 16, "not Clip");
  assert.ok(Math.abs(target.holdLift - bask.lift) > 16, "not Ink");
  assert.ok(Math.abs(target.holdLift - earth.lift) > 16, "not Ground");
  assert.ok(Math.abs(target.holdLift - thread.lift) > 8, "not Wick");
  assert.ok(Math.abs(target.holdLift - ball.lift) > 20, "not Burr");
  assert.ok(Math.abs(target.holdX - field.x) > 20 || Math.abs(target.holdLift - field.lift) > 20, "not Flux");
  assert.ok(Math.abs(target.holdX - circle.x) > 20 || Math.abs(target.holdLift - circle.lift) > 20, "not Coin");
  assert.ok(Math.abs(target.holdX - dust.x) > 20 || Math.abs(target.holdLift - dust.lift) > 20, "not Floss");
  assert.ok(Math.abs(target.holdX - wall.x) > 20 || Math.abs(target.holdLift - wall.lift) > 20, "not Bloom");
  assert.ok(Math.abs(target.holdX - toss.x) > 20 || Math.abs(target.holdLift - toss.lift) > 20, "not Keel");
  assert.ok(Math.abs(target.holdLift - sill.lift) > 40, "not a generic sill");
  let play = P.beginPlay(target, target.approachX);
  const seen = new Set();
  let sitXMin = Infinity;
  let sitXMax = -Infinity;
  let bobXMin = Infinity;
  let bobXMax = -Infinity;
  let bobRot = 0;
  for (let i = 0; i < 800 && play.phase !== "done"; i++) {
    seen.add(play.phase);
    play = P.stepPlay(play, 0.05, { x: play.x, lift: play.lift }, [WIN], WORK, 176, { cmd: "idle" });
    assert.notEqual(play.phase, "cling");
    assert.notEqual(play.phase, "ridge-hold");
    assert.notEqual(play.phase, "coil-hold");
    assert.notEqual(play.phase, "path-walk");
    assert.notEqual(play.phase, "field-hold");
    assert.notEqual(play.phase, "crackle-hop");
    assert.notEqual(play.phase, "charge-bolt");
    assert.notEqual(play.phase, "orbit-loop");
    assert.notEqual(play.phase, "click-hop");
    assert.notEqual(play.phase, "hold-sit");
    assert.notEqual(play.phase, "earth-sit");
    assert.notEqual(play.phase, "ledge-sit");
    assert.notEqual(play.phase, "watch-hold");
    assert.notEqual(play.phase, "thump");
    assert.notEqual(play.phase, "stash-cheek");
    assert.notEqual(play.phase, "wheek");
    assert.notEqual(play.phase, "bask");
    assert.notEqual(play.phase, "circle");
    assert.notEqual(play.phase, "perch-talk");
    assert.notEqual(play.phase, "scent");
    assert.notEqual(play.phase, "bow");
    assert.notEqual(play.phase, "hook");
    assert.notEqual(play.phase, "thread");
    assert.notEqual(play.phase, "ball");
    assert.notEqual(play.phase, "dust");
    assert.notEqual(play.phase, "wall");
    assert.notEqual(play.phase, "toss");
    assert.notEqual(play.phase, "sill-walk");
    if (play.phase === "flatten") {
      sitXMin = Math.min(sitXMin, play.x);
      sitXMax = Math.max(sitXMax, play.x);
      assert.equal(play.anim, "sit");
      assert.ok(play.lift > 36);
      assert.equal(play.rot, 0);
    }
    if (play.phase === "flatten-bob") {
      bobXMin = Math.min(bobXMin, play.x);
      bobXMax = Math.max(bobXMax, play.x);
      bobRot = Math.max(bobRot, Math.abs(play.rot));
      assert.equal(play.anim, "play");
      assert.ok(play.lift > 16);
    }
  }
  assert.ok(seen.has("flatten-on"));
  assert.ok(seen.has("flatten-bob"));
  assert.ok(seen.has("flatten"));
  assert.ok(seen.has("flatten-off"));
  assert.ok(sitXMax - sitXMin < 2, "one brick — not a walk across");
  assert.ok(bobXMax - bobXMin < 2, "one bob — the head nods, the feet stay");
  assert.ok(bobRot > 8, "the bob is visible");
  assert.equal(play.phase, "done");
});

test("the demo window plate walks Vesper's drape the same way", () => {
  assert.match(demoSrc, /demoWindow/);
  assert.match(livingSrc, /drape-on|playFor/);
  assert.match(rosterSrc, /key: "dragon"[\s\S]{0,80}slug: "vesper"/);
  assert.match(guideSrc, /"dragon"/);
  const overlayTarget = Overlay.pickTarget([WIN], 40, "dragon", WORK, 176);
  const target = P.pickTarget([WIN], 40, "dragon", WORK, 176);
  assert.equal(target.kind, overlayTarget.kind);
  assert.equal(target.kind, "drape");
  assert.equal(target.side, "lintel");
  assert.equal(target.holdX, overlayTarget.holdX);
  assert.equal(target.holdLift, overlayTarget.holdLift);
  assert.ok(target.holdLift > 36);
  assert.equal(target.leave, "slip");
  assert.equal(target.clickToId, undefined);
  const flatten = P.flattenPoint(WIN, 176, WORK);
  const toss = P.tossPoint(WIN, "left", 176, WORK);
  const wall = P.wallPoint(WIN, 0, "left", 176, WORK);
  const hook = P.hookPoint(WIN, "left", 1, 176, WORK);
  const bow = P.bowPoint(WIN, 176, WORK);
  const scent = P.scentPoint(WIN, "left", 176, WORK);
  const perch = P.perchPoint(WIN, "left", 176, WORK);
  const watch = P.watchPoint(WIN, 176, WORK);
  const wheek = P.wheekPoint(WIN, 176, WORK);
  const thump = P.thumpPoint(WIN, 176, WORK, "left");
  const ledge = P.ledgePoint(WIN, 176, WORK);
  const ridge = P.ridgePoint(WIN, 0.5, 176, WORK);
  const coil = P.coilPoint(WIN, "left", 176, WORK);
  const stash = P.stashPoint(WIN, "left", 176, WORK);
  const bask = P.baskPoint(WIN, 176, WORK);
  const earth = P.earthPoint(WIN, 176, WORK);
  const thread = P.threadPoint(WIN, 0, 176, WORK);
  const ball = P.ballPoint(WIN, 176, WORK);
  const field = P.fieldPoint(WIN, 176, WORK);
  const circle = P.circlePoint(WIN, 0, 176, WORK, 1);
  const dust = P.dustPoint(WIN, 176, WORK);
  const sill = P.sillPoint(WIN, 0.12, 176, WORK);
  assert.ok(Math.abs(target.holdX - watch.x) > 20 || Math.abs(target.holdLift - watch.lift) > 20, "not Pip");
  assert.ok(Math.abs(target.holdX - wheek.x) > 20 || Math.abs(target.holdLift - wheek.lift) > 20, "not Whee");
  assert.ok(Math.abs(target.holdX - scent.x) > 20 || Math.abs(target.holdLift - scent.lift) > 20, "not Rue");
  assert.ok(Math.abs(target.holdX - thump.x) > 20 || Math.abs(target.holdLift - thump.lift) > 20, "not Thimble");
  assert.ok(Math.abs(target.holdX - hook.x) > 20 || Math.abs(target.holdLift - hook.lift) > 20, "not Quill");
  assert.ok(Math.abs(target.holdX - bow.x) > 20 || Math.abs(target.holdLift - bow.lift) > 20, "not Peck");
  assert.ok(Math.abs(target.holdX - perch.x) > 20 || Math.abs(target.holdLift - perch.lift) > 20, "not Echo");
  assert.ok(Math.abs(target.holdLift - ledge.lift) > 40, "not Miso");
  assert.ok(Math.abs(target.holdLift - ridge.lift) > 40, "not Arc");
  assert.ok(Math.abs(target.holdX - coil.x) > 20 || Math.abs(target.holdLift - coil.lift) > 20, "not Volt");
  assert.ok(Math.abs(target.holdX - stash.x) > 20 || Math.abs(target.holdLift - stash.lift) > 16, "not Clip");
  assert.ok(Math.abs(target.holdLift - bask.lift) > 16, "not Ink");
  assert.ok(Math.abs(target.holdLift - earth.lift) > 16, "not Ground");
  assert.ok(Math.abs(target.holdLift - thread.lift) > 8, "not Wick");
  assert.ok(Math.abs(target.holdLift - ball.lift) > 20, "not Burr");
  assert.ok(Math.abs(target.holdX - field.x) > 20 || Math.abs(target.holdLift - field.lift) > 20, "not Flux");
  assert.ok(Math.abs(target.holdX - circle.x) > 20 || Math.abs(target.holdLift - circle.lift) > 20, "not Coin");
  assert.ok(Math.abs(target.holdX - dust.x) > 20 || Math.abs(target.holdLift - dust.lift) > 20, "not Floss");
  assert.ok(Math.abs(target.holdX - wall.x) > 20 || Math.abs(target.holdLift - wall.lift) > 20, "not Bloom");
  assert.ok(Math.abs(target.holdX - toss.x) > 20 || Math.abs(target.holdLift - toss.lift) > 20, "not Keel");
  assert.ok(Math.abs(target.holdLift - flatten.lift) > 40, "not Sol");
  assert.ok(Math.abs(target.holdLift - sill.lift) > 40, "not a generic sill");
  let play = P.beginPlay(target, target.approachX);
  const seen = new Set();
  let sitXMin = Infinity;
  let sitXMax = -Infinity;
  let settleXMin = Infinity;
  let settleXMax = -Infinity;
  let settleRot = 0;
  for (let i = 0; i < 800 && play.phase !== "done"; i++) {
    seen.add(play.phase);
    play = P.stepPlay(play, 0.05, { x: play.x, lift: play.lift }, [WIN], WORK, 176, { cmd: "idle" });
    assert.notEqual(play.phase, "cling");
    assert.notEqual(play.phase, "ridge-hold");
    assert.notEqual(play.phase, "coil-hold");
    assert.notEqual(play.phase, "path-walk");
    assert.notEqual(play.phase, "field-hold");
    assert.notEqual(play.phase, "crackle-hop");
    assert.notEqual(play.phase, "charge-bolt");
    assert.notEqual(play.phase, "orbit-loop");
    assert.notEqual(play.phase, "click-hop");
    assert.notEqual(play.phase, "hold-sit");
    assert.notEqual(play.phase, "earth-sit");
    assert.notEqual(play.phase, "ledge-sit");
    assert.notEqual(play.phase, "watch-hold");
    assert.notEqual(play.phase, "thump");
    assert.notEqual(play.phase, "stash-cheek");
    assert.notEqual(play.phase, "wheek");
    assert.notEqual(play.phase, "bask");
    assert.notEqual(play.phase, "circle");
    assert.notEqual(play.phase, "perch-talk");
    assert.notEqual(play.phase, "scent");
    assert.notEqual(play.phase, "bow");
    assert.notEqual(play.phase, "hook");
    assert.notEqual(play.phase, "thread");
    assert.notEqual(play.phase, "ball");
    assert.notEqual(play.phase, "dust");
    assert.notEqual(play.phase, "wall");
    assert.notEqual(play.phase, "toss");
    assert.notEqual(play.phase, "flatten");
    assert.notEqual(play.phase, "flatten-bob");
    assert.notEqual(play.phase, "sill-walk");
    if (play.phase === "drape") {
      sitXMin = Math.min(sitXMin, play.x);
      sitXMax = Math.max(sitXMax, play.x);
      assert.equal(play.anim, "sit");
      assert.ok(play.lift > 36);
      assert.ok(Math.abs(play.rot) > 14, "the tail hangs");
    }
    if (play.phase === "drape-settle") {
      settleXMin = Math.min(settleXMin, play.x);
      settleXMax = Math.max(settleXMax, play.x);
      settleRot = Math.max(settleRot, Math.abs(play.rot));
      assert.equal(play.anim, "play");
      assert.ok(play.lift > 16);
    }
  }
  assert.ok(seen.has("drape-on"));
  assert.ok(seen.has("drape-settle"));
  assert.ok(seen.has("drape"));
  assert.ok(seen.has("drape-off"));
  assert.ok(sitXMax - sitXMin < 2, "one lintel — not a walk across");
  assert.ok(settleXMax - settleXMin < 2, "one settle — the fold stays");
  assert.ok(settleRot > 14, "the drape is visible");
  assert.equal(play.phase, "done");
});
