/** Species ground-trick registry. Rui, Relay, Fuse, Ground, Miso, Pip, Thimble, Clip, Whee, Ink, Coin, Echo, Rue, Peck, Quill, Wick, Burr, Floss, Bloom, Keel, Sol, Vesper, Ember, Nori, Saffron, Bandit, Jade, Bluff, Sash, Lula, Coral, Blush, Atlas, Cup, Sepia, Chamber, Pulse, Cling, Tenant, Ledger, Anchor, Kite, Door, Felt, Vein, Fan, Mast, Disk, Moth, Arm, Snap, Drown, Dew, Comb, Milk, Ghost, Spark, Dart, Twig, Column, Seven, Fold, Brood, Thrum, Auger, Mortar, Disc, Pot, Sheen, Bank, Hum, Keep, Wax, Frill, Cap, Lattice, Horn, Ring, Mane, Puff, Flame, Starter, Pact, Gleam, Choir, Drift, Shard, Dusk, Knot, Brine, Beacon, Hush, Arca, Reed, Pebble, Eft, Dapple, Slip, Pinch, Whorl, Hinge, Latch, Prickle, Soot, Wedge, Heart, Hook, Dee, Brick, Drake, Vee, Drum, Sip, Loom, Leap, Prowl, Velvet, Hour, Stem, Barb, Whip, Clasp, Gale, Flag, Cape, Cache, Slick, Wash, Stripe, Grin, Dam, Spine, Coal, Soak, Pad, Wink, Dash, Shift, Spike, Levee, Jaw, Beak, Lid, Peak, Lunge, Speck, Whisk, Penny, Bar, Lance, Night, Spoon, Round, Silver, Haste, Link, Armor, Cast, Jet, Hop, Tun, Thread, Scud, Wave, Pale, Cone, Cement, Mail, Spire,, Forceps, Snout, Click, Hang, Sun, Swing, Sail, Glide, Boom, Ridge, Wreath, Paint, Scrape, Scrub, Tube, and Veil today. Overlay + /demo lockstep. */
(function (root) {
  function tricksFor(key) {
    if (!key) return null;
    const Rui = root.PetRuiTricks;
    const Relay = root.PetRelayTricks;
    const Fuse = root.PetFuseTricks;
    const Earth = root.PetEarthTricks;
    const Cat = root.PetCatTricks;
    const Dog = root.PetDogTricks;
    const Rabbit = root.PetRabbitTricks;
    const Hamster = root.PetHamsterTricks;
    const GuineaPig = root.PetGuineaPigTricks;
    const Turtle = root.PetTurtleTricks;
    const Goldfish = root.PetGoldfishTricks;
    const Budgie = root.PetBudgieTricks;
    const Fox = root.PetFoxTricks;
    const Penguin = root.PetPenguinTricks;
    const Parrot = root.PetParrotTricks;
    const Ferret = root.PetFerretTricks;
    const Hedgehog = root.PetHedgehogTricks;
    const Chinchilla = root.PetChinchillaTricks;
    const Axolotl = root.PetAxolotlTricks;
    const Toucan = root.PetToucanTricks;
    const Iguana = root.PetIguanaTricks;
    const Dragon = root.PetDragonTricks;
    const Phoenix = root.PetPhoenixTricks;
    const BallPython = root.PetBallPythonTricks;
    const CornSnake = root.PetCornSnakeTricks;
    const Kingsnake = root.PetKingsnakeTricks;
    const GreenTreePython = root.PetGreenTreePythonTricks;
    const Hognose = root.PetHognoseTricks;
    const Garter = root.PetGarterTricks;
    const Boa = root.PetBoaTricks;
    const MilkSnake = root.PetMilkSnakeTricks;
    const RosyBoa = root.PetRosyBoaTricks;
    const CarpetPython = root.PetCarpetPythonTricks;
    const Octopus = root.PetOctopusTricks;
    const Cuttlefish = root.PetCuttlefishTricks;
    const Nautilus = root.PetNautilusTricks;
    const MoonJelly = root.PetMoonJellyTricks;
    const SeaStar = root.PetSeaStarTricks;
    const HermitCrab = root.PetHermitCrabTricks;
    const HorseshoeCrab = root.PetHorseshoeCrabTricks;
    const Seahorse = root.PetSeahorseTricks;
    const Manta = root.PetMantaTricks;
    const Moray = root.PetMorayTricks;
    const Moss = root.PetMossTricks;
    const Maidenhair = root.PetMaidenhairTricks;
    const Ginkgo = root.PetGinkgoTricks;
    const Oak = root.PetOakTricks;
    const WaterLily = root.PetWaterLilyTricks;
    const Orchid = root.PetOrchidTricks;
    const Saguaro = root.PetSaguaroTricks;
    const VenusFlytrap = root.PetVenusFlytrapTricks;
    const Pitcher = root.PetPitcherTricks;
    const Sundew = root.PetSundewTricks;
    const Honeybee = root.PetHoneybeeTricks;
    const Monarch = root.PetMonarchTricks;
    const Luna = root.PetLunaTricks;
    const Firefly = root.PetFireflyTricks;
    const Darner = root.PetDarnerTricks;
    const Stick = root.PetStickTricks;
    const CarpenterAnt = root.PetCarpenterAntTricks;
    const Ladybird = root.PetLadybirdTricks;
    const Mantis = root.PetMantisTricks;
    const Cicada = root.PetCicadaTricks;
    const Bumblebee = root.PetBumblebeeTricks;
    const CarpenterBee = root.PetCarpenterBeeTricks;
    const MasonBee = root.PetMasonBeeTricks;
    const Leafcutter = root.PetLeafcutterTricks;
    const Stingless = root.PetStinglessTricks;
    const SweatBee = root.PetSweatBeeTricks;
    const MiningBee = root.PetMiningBeeTricks;
    const HoneyDrone = root.PetHoneyDroneTricks;
    const HoneyQueen = root.PetHoneyQueenTricks;
  const Honeycomb = root.PetHoneycombTricks;
  const Oyster = root.PetOysterTricks;
  const FlyAgaric = root.PetFlyAgaricTricks;
const Morel = root.PetMorelTricks;
  const Chanterelle = root.PetChanterelleTricks;
  const TurkeyTail = root.PetTurkeyTailTricks;
  const LionsMane = root.PetLionsManeTricks;
  const Puffball = root.PetPuffballTricks;
  const ChickenOfWoods = root.PetChickenOfWoodsTricks;
  const Yeast = root.PetYeastTricks;
  const Lichen = root.PetLichenTricks;
  const Photovore = root.PetPhotovoreTricks;
  const Choir = root.PetChoirTricks;
  const Nimbus = root.PetNimbusTricks;
  const Silica = root.PetSilicaTricks;
  const Terminator = root.PetTerminatorTricks;
  const Nexus = root.PetNexusTricks;
  const Halovore = root.PetHalovoreTricks;
  const Magneton = root.PetMagnetonTricks;
  const Umbral = root.PetUmbralTricks;
  const Cyst = root.PetCystTricks;
  const Frog = root.PetFrogTricks;
  const Toad = root.PetToadTricks;
  const Newt = root.PetNewtTricks;
  const Salamander = root.PetSalamanderTricks;
  const Caecilian = root.PetCaecilianTricks;
  const Crayfish = root.PetCrayfishTricks;
  const PondSnail = root.PetPondSnailTricks;
  const Mussel = root.PetMusselTricks;
  const Leech = root.PetLeechTricks;
  const Stickleback = root.PetSticklebackTricks;
  const Crow = root.PetCrowTricks;
  const Raven = root.PetRavenTricks;
  const BarnOwl = root.PetBarnOwlTricks;
  const RedTail = root.PetRedTailTricks;
  const Chickadee = root.PetChickadeeTricks;
  const Robin = root.PetRobinTricks;
  const Mallard = root.PetMallardTricks;
  const CanadaGoose = root.PetCanadaGooseTricks;
  const Pileated = root.PetPileatedTricks;
  const Hummingbird = root.PetHummingbirdTricks;
  const OrbWeaver = root.PetOrbWeaverTricks;
  const JumpingSpider = root.PetJumpingSpiderTricks;
  const WolfSpider = root.PetWolfSpiderTricks;
  const Tarantula = root.PetTarantulaTricks;
  const Widow = root.PetWidowTricks;
  const Harvestman = root.PetHarvestmanTricks;
  const Scorpion = root.PetScorpionTricks;
  const Vinegaroon = root.PetVinegaroonTricks;
  const Tick = root.PetTickTricks;
  const Solifuge = root.PetSolifugeTricks;
  const Deer = root.PetDeerTricks;
  const Bat = root.PetBatTricks;
  const Squirrel = root.PetSquirrelTricks;
  const Otter = root.PetOtterTricks;
  const Raccoon = root.PetRaccoonTricks;
  const Skunk = root.PetSkunkTricks;
  const Opossum = root.PetOpossumTricks;
  const Beaver = root.PetBeaverTricks;
  const Porcupine = root.PetPorcupineTricks;
  const BlackBear = root.PetBlackBearTricks;
  const Capybara = root.PetCapybaraTricks;
  const Gecko = root.PetGeckoTricks;
  const Anole = root.PetAnoleTricks;
  const Skink = root.PetSkinkTricks;
  const Chameleon = root.PetChameleonTricks;
  const HornedLizard = root.PetHornedLizardTricks;
  const Alligator = root.PetAlligatorTricks;
  const Crocodile = root.PetCrocodileTricks;
  const Snapper = root.PetSnapperTricks;
  const BoxTurtle = root.PetBoxTurtleTricks;
  const Tuatara = root.PetTuataraTricks;
  const Bass = root.PetBassTricks;
  const BrookTrout = root.PetBrookTroutTricks;
  const Catfish = root.PetCatfishTricks;
  const Bluegill = root.PetBluegillTricks;
  const Perch = root.PetPerchTricks;
  const Pike = root.PetPikeTricks;
  const Walleye = root.PetWalleyeTricks;
  const Paddlefish = root.PetPaddlefishTricks;
  const Lamprey = root.PetLampreyTricks;
  const AmericanEel = root.PetAmericanEelTricks;
  const HouseCentipede = root.PetHouseCentipedeTricks;
  const Millipede = root.PetMillipedeTricks;
  const Pillbug = root.PetPillbugTricks;
  const Earthworm = root.PetEarthwormTricks;
  const VelvetWorm = root.PetVelvetWormTricks;
  const Springtail = root.PetSpringtailTricks;
  const Tardigrade = root.PetTardigradeTricks;
  const Planarian = root.PetPlanarianTricks;
  const Nematode = root.PetNematodeTricks;
  const Amphipod = root.PetAmphipodTricks;
  const FiddlerCrab = root.PetFiddlerCrabTricks;
  const GhostCrab = root.PetGhostCrabTricks;
  const Limpet = root.PetLimpetTricks;
  const Barnacle = root.PetBarnacleTricks;
  const Chiton = root.PetChitonTricks;
  const Periwinkle = root.PetPeriwinkleTricks;
  const SandDollar = root.PetSandDollarTricks;
  const SeaUrchin = root.PetSeaUrchinTricks;
  const KnobbedWhelk = root.PetKnobbedWhelkTricks;
  const Lugworm = root.PetLugwormTricks;
  const FieldCricket = root.PetFieldCricketTricks;
  const Katydid = root.PetKatydidTricks;
  const Grasshopper = root.PetGrasshopperTricks;
  const Swallowtail = root.PetSwallowtailTricks;
  const Jewelwing = root.PetJewelwingTricks;
  const Lacewing = root.PetLacewingTricks;
  const Earwig = root.PetEarwigTricks;
  const AcornWeevil = root.PetAcornWeevilTricks;
  const ClickBeetle = root.PetClickBeetleTricks;
  const RobberFly = root.PetRobberFlyTricks;
  const Sloth = root.PetSlothTricks;
  const Lemur = root.PetLemurTricks;
  const Gibbon = root.PetGibbonTricks;
  const Kinkajou = root.PetKinkajouTricks;
    const Colugo = root.PetColugoTricks;
    const FlyingSquirrel = root.PetFlyingSquirrelTricks;
    const Howler = root.PetHowlerTricks;
    const Tarsier = root.PetTarsierTricks;
    const Potto = root.PetPottoTricks;
    const Koala = root.PetKoalaTricks;
    const BrainCoral = root.PetBrainCoralTricks;
    const Anemone = root.PetAnemoneTricks;
    const Clownfish = root.PetClownfishTricks;
    const Parrotfish = root.PetParrotfishTricks;
    const CleanerShrimp = root.PetCleanerShrimpTricks;
    const SeaCucumber = root.PetSeaCucumberTricks;
    const Lionfish = root.PetLionfishTricks;
    const GiantClam = root.PetGiantClamTricks;
    const EagleRay = root.PetEagleRayTricks;
    const Grouper = root.PetGrouperTricks;
    const CyberDragon = root.PetCyberDragonTricks;
    const VoltDragon = root.PetVoltDragonTricks;
    const TraceDragon = root.PetTraceDragonTricks;
    const FluxDragon = root.PetFluxDragonTricks;
    const SparkDragon = root.PetSparkDragonTricks;
    const IonDragon = root.PetIonDragonTricks;
    const GaussDragon = root.PetGaussDragonTricks;
    const Paramecium = root.PetParameciumTricks;
    const Amoeba = root.PetAmoebaTricks;
    const Euglena = root.PetEuglenaTricks;
    const Volvox = root.PetVolvoxTricks;
    const Diatom = root.PetDiatomTricks;
    const Kelp = root.PetKelpTricks;
    const Chlamydomonas = root.PetChlamydomonasTricks;
    const Stentor = root.PetStentorTricks;
    const Coli = root.PetColiTricks;
    const Haloarchaea = root.PetHaloarchaeaTricks;
    if (Rui && (key === Rui.TRICK_KEY || key === "rui")) return Rui;
    if (Relay && (key === Relay.TRICK_KEY || key === "relay")) return Relay;
    if (Fuse && (key === Fuse.TRICK_KEY || key === "fuse")) return Fuse;
    if (Earth && (key === Earth.TRICK_KEY || key === "ground")) return Earth;
    if (Cat && (key === Cat.TRICK_KEY || key === "miso")) return Cat;
    if (Dog && (key === Dog.TRICK_KEY || key === "pip")) return Dog;
    if (Rabbit && (key === Rabbit.TRICK_KEY || key === "thimble")) return Rabbit;
    if (Hamster && (key === Hamster.TRICK_KEY || key === "clip")) return Hamster;
    if (GuineaPig && (key === GuineaPig.TRICK_KEY || key === "whee")) return GuineaPig;
    if (Turtle && (key === Turtle.TRICK_KEY || key === "ink")) return Turtle;
    if (Goldfish && (key === Goldfish.TRICK_KEY || key === "coin")) return Goldfish;
    if (Budgie && (key === Budgie.TRICK_KEY || key === "echo")) return Budgie;
    if (Fox && (key === Fox.TRICK_KEY || key === "rue")) return Fox;
    if (Penguin && (key === Penguin.TRICK_KEY || key === "peck")) return Penguin;
    if (Parrot && (key === Parrot.TRICK_KEY || key === "quill")) return Parrot;
    if (Ferret && (key === Ferret.TRICK_KEY || key === "wick")) return Ferret;
    if (Hedgehog && (key === Hedgehog.TRICK_KEY || key === "burr")) return Hedgehog;
    if (Chinchilla && (key === Chinchilla.TRICK_KEY || key === "floss")) return Chinchilla;
    if (Axolotl && (key === Axolotl.TRICK_KEY || key === "bloom")) return Axolotl;
    if (Toucan && (key === Toucan.TRICK_KEY || key === "keel")) return Toucan;
    if (Iguana && (key === Iguana.TRICK_KEY || key === "sol")) return Iguana;
    if (Dragon && (key === Dragon.TRICK_KEY || key === "vesper")) return Dragon;
    if (Phoenix && (key === Phoenix.TRICK_KEY || key === "ember")) return Phoenix;
    if (BallPython && (key === BallPython.TRICK_KEY || key === "nori")) return BallPython;
    if (CornSnake && (key === CornSnake.TRICK_KEY || key === "saffron")) return CornSnake;
    if (Kingsnake && (key === Kingsnake.TRICK_KEY || key === "bandit")) return Kingsnake;
    if (GreenTreePython && (key === GreenTreePython.TRICK_KEY || key === "jade")) return GreenTreePython;
    if (Hognose && (key === Hognose.TRICK_KEY || key === "bluff")) return Hognose;
    if (Garter && (key === Garter.TRICK_KEY || key === "sash")) return Garter;
    if (Boa && (key === Boa.TRICK_KEY || key === "lula")) return Boa;
    if (MilkSnake && (key === MilkSnake.TRICK_KEY || key === "coral")) return MilkSnake;
    if (RosyBoa && (key === RosyBoa.TRICK_KEY || key === "blush")) return RosyBoa;
    if (CarpetPython && (key === CarpetPython.TRICK_KEY || key === "atlas")) return CarpetPython;
    if (Octopus && (key === Octopus.TRICK_KEY || key === "cup")) return Octopus;
    if (Cuttlefish && (key === Cuttlefish.TRICK_KEY || key === "sepia")) return Cuttlefish;
    if (Nautilus && (key === Nautilus.TRICK_KEY || key === "chamber")) return Nautilus;
    if (MoonJelly && (key === MoonJelly.TRICK_KEY || key === "pulse")) return MoonJelly;
    if (SeaStar && (key === SeaStar.TRICK_KEY || key === "cling")) return SeaStar;
    if (HermitCrab && (key === HermitCrab.TRICK_KEY || key === "tenant")) return HermitCrab;
    if (HorseshoeCrab && (key === HorseshoeCrab.TRICK_KEY || key === "ledger")) return HorseshoeCrab;
    if (Seahorse && (key === Seahorse.TRICK_KEY || key === "anchor")) return Seahorse;
    if (Manta && (key === Manta.TRICK_KEY || key === "kite")) return Manta;
    if (Moray && (key === Moray.TRICK_KEY || key === "door")) return Moray;
    if (Moss && (key === Moss.TRICK_KEY || key === "felt")) return Moss;
    if (Maidenhair && (key === Maidenhair.TRICK_KEY || key === "vein")) return Maidenhair;
    if (Ginkgo && (key === Ginkgo.TRICK_KEY || key === "fan")) return Ginkgo;
    if (Oak && (key === Oak.TRICK_KEY || key === "mast")) return Oak;
    if (WaterLily && (key === WaterLily.TRICK_KEY || key === "disk")) return WaterLily;
    if (Orchid && (key === Orchid.TRICK_KEY || key === "moth")) return Orchid;
    if (Saguaro && (key === Saguaro.TRICK_KEY || key === "arm")) return Saguaro;
    if (VenusFlytrap && (key === VenusFlytrap.TRICK_KEY || key === "snap")) return VenusFlytrap;
    if (Pitcher && (key === Pitcher.TRICK_KEY || key === "drown")) return Pitcher;
    if (Sundew && (key === Sundew.TRICK_KEY || key === "dew")) return Sundew;
    if (Honeybee && (key === Honeybee.TRICK_KEY || key === "comb")) return Honeybee;
    if (Monarch && (key === Monarch.TRICK_KEY || key === "milk")) return Monarch;
    if (Luna && (key === Luna.TRICK_KEY || key === "ghost")) return Luna;
    if (Firefly && (key === Firefly.TRICK_KEY || key === "spark")) return Firefly;
    if (Darner && (key === Darner.TRICK_KEY || key === "dart")) return Darner;
    if (Stick && (key === Stick.TRICK_KEY || key === "twig")) return Stick;
    if (CarpenterAnt && (key === CarpenterAnt.TRICK_KEY || key === "column")) return CarpenterAnt;
    if (Ladybird && (key === Ladybird.TRICK_KEY || key === "seven")) return Ladybird;
    if (Mantis && (key === Mantis.TRICK_KEY || key === "fold")) return Mantis;
    if (Cicada && (key === Cicada.TRICK_KEY || key === "brood")) return Cicada;
    if (Bumblebee && (key === Bumblebee.TRICK_KEY || key === "thrum")) return Bumblebee;
    if (CarpenterBee && (key === CarpenterBee.TRICK_KEY || key === "auger")) return CarpenterBee;
    if (MasonBee && (key === MasonBee.TRICK_KEY || key === "mortar")) return MasonBee;
    if (Leafcutter && (key === Leafcutter.TRICK_KEY || key === "disc")) return Leafcutter;
    if (Stingless && (key === Stingless.TRICK_KEY || key === "pot")) return Stingless;
    if (SweatBee && (key === SweatBee.TRICK_KEY || key === "sheen")) return SweatBee;
    if (MiningBee && (key === MiningBee.TRICK_KEY || key === "bank")) return MiningBee;
    if (HoneyDrone && (key === HoneyDrone.TRICK_KEY || key === "hum")) return HoneyDrone;
    if (HoneyQueen && (key === HoneyQueen.TRICK_KEY || key === "keep")) return HoneyQueen;
    if (Honeycomb && (key === Honeycomb.TRICK_KEY || key === "wax")) return Honeycomb;
    if (Oyster && (key === Oyster.TRICK_KEY || key === "frill")) return Oyster;
    if (FlyAgaric && (key === FlyAgaric.TRICK_KEY || key === "cap")) return FlyAgaric;
if (Morel && (key === Morel.TRICK_KEY || key === "lattice")) return Morel;
    if (Chanterelle && (key === Chanterelle.TRICK_KEY || key === "horn")) return Chanterelle;
    if (TurkeyTail && (key === TurkeyTail.TRICK_KEY || key === "ring")) return TurkeyTail;
    if (LionsMane && (key === LionsMane.TRICK_KEY || key === "mane")) return LionsMane;
    if (Puffball && (key === Puffball.TRICK_KEY || key === "puff")) return Puffball;
    if (ChickenOfWoods && (key === ChickenOfWoods.TRICK_KEY || key === "flame")) return ChickenOfWoods;
    if (Yeast && (key === Yeast.TRICK_KEY || key === "starter")) return Yeast;
    if (Lichen && (key === Lichen.TRICK_KEY || key === "pact")) return Lichen;
    if (Photovore && (key === Photovore.TRICK_KEY || key === "gleam")) return Photovore;
    if (Choir && (key === Choir.TRICK_KEY || key === "choir")) return Choir;
    if (Nimbus && (key === Nimbus.TRICK_KEY || key === "nimbus" || key === "drift")) return Nimbus;
    if (Silica && (key === Silica.TRICK_KEY || key === "silica" || key === "shard")) return Silica;
    if (Terminator && (key === Terminator.TRICK_KEY || key === "terminator" || key === "dusk")) return Terminator;
    if (Nexus && (key === Nexus.TRICK_KEY || key === "nexus" || key === "knot")) return Nexus;
    if (Halovore && (key === Halovore.TRICK_KEY || key === "halovore" || key === "brine")) return Halovore;
    if (Magneton && (key === Magneton.TRICK_KEY || key === "magneton" || key === "beacon")) return Magneton;
    if (Umbral && (key === Umbral.TRICK_KEY || key === "umbral" || key === "hush")) return Umbral;
    if (Cyst && (key === Cyst.TRICK_KEY || key === "cyst" || key === "arca")) return Cyst;
    if (Frog && (key === Frog.TRICK_KEY || key === "frog" || key === "reed")) return Frog;
    if (Toad && (key === Toad.TRICK_KEY || key === "toad" || key === "pebble")) return Toad;
    if (Newt && (key === Newt.TRICK_KEY || key === "newt" || key === "eft")) return Newt;
    if (Salamander && (key === Salamander.TRICK_KEY || key === "salamander" || key === "dapple")) return Salamander;
    if (Caecilian && (key === Caecilian.TRICK_KEY || key === "caecilian" || key === "slip")) return Caecilian;
    if (Crayfish && (key === Crayfish.TRICK_KEY || key === "crayfish" || key === "pinch")) return Crayfish;
    if (PondSnail && (key === PondSnail.TRICK_KEY || key === "pond_snail" || key === "whorl")) return PondSnail;
    if (Mussel && (key === Mussel.TRICK_KEY || key === "mussel" || key === "hinge")) return Mussel;
    if (Leech && (key === Leech.TRICK_KEY || key === "leech" || key === "latch")) return Leech;
    if (Stickleback && (key === Stickleback.TRICK_KEY || key === "stickleback" || key === "prickle")) return Stickleback;
    if (Crow && (key === Crow.TRICK_KEY || key === "crow" || key === "soot")) return Crow;
    if (Raven && (key === Raven.TRICK_KEY || key === "raven" || key === "wedge")) return Raven;
    if (BarnOwl && (key === BarnOwl.TRICK_KEY || key === "barn_owl" || key === "heart")) return BarnOwl;
    if (RedTail && (key === RedTail.TRICK_KEY || key === "red_tail" || key === "hook")) return RedTail;
    if (Chickadee && (key === Chickadee.TRICK_KEY || key === "chickadee" || key === "dee")) return Chickadee;
    if (Robin && (key === Robin.TRICK_KEY || key === "robin" || key === "brick")) return Robin;
    if (Mallard && (key === Mallard.TRICK_KEY || key === "mallard" || key === "drake")) return Mallard;
    if (CanadaGoose && (key === CanadaGoose.TRICK_KEY || key === "canada_goose" || key === "vee")) return CanadaGoose;
    if (Pileated && (key === Pileated.TRICK_KEY || key === "pileated" || key === "drum")) return Pileated;
    if (Hummingbird && (key === Hummingbird.TRICK_KEY || key === "hummingbird" || key === "sip")) return Hummingbird;
    if (OrbWeaver && (key === OrbWeaver.TRICK_KEY || key === "orb_weaver" || key === "loom")) return OrbWeaver;
    if (JumpingSpider && (key === JumpingSpider.TRICK_KEY || key === "jumping_spider" || key === "leap")) return JumpingSpider;
    if (WolfSpider && (key === WolfSpider.TRICK_KEY || key === "wolf_spider" || key === "prowl")) return WolfSpider;
    if (Tarantula && (key === Tarantula.TRICK_KEY || key === "tarantula" || key === "velvet")) return Tarantula;
    if (Widow && (key === Widow.TRICK_KEY || key === "widow" || key === "hour")) return Widow;
    if (Harvestman && (key === Harvestman.TRICK_KEY || key === "harvestman" || key === "stem")) return Harvestman;
    if (Scorpion && (key === Scorpion.TRICK_KEY || key === "scorpion" || key === "barb")) return Scorpion;
    if (Vinegaroon && (key === Vinegaroon.TRICK_KEY || key === "vinegaroon" || key === "whip")) return Vinegaroon;
    if (Tick && (key === Tick.TRICK_KEY || key === "tick" || key === "clasp")) return Tick;
    if (Solifuge && (key === Solifuge.TRICK_KEY || key === "solifuge" || key === "gale")) return Solifuge;
    if (Deer && (key === Deer.TRICK_KEY || key === "deer" || key === "rack" || key === "flag")) return Deer;
    if (Bat && (key === Bat.TRICK_KEY || key === "bat" || key === "cape")) return Bat;
    if (Squirrel && (key === Squirrel.TRICK_KEY || key === "squirrel" || key === "cache")) return Squirrel;
    if (Otter && (key === Otter.TRICK_KEY || key === "otter" || key === "slick")) return Otter;
    if (Raccoon && (key === Raccoon.TRICK_KEY || key === "raccoon" || key === "wash")) return Raccoon;
    if (Skunk && (key === Skunk.TRICK_KEY || key === "skunk" || key === "stripe")) return Skunk;
    if (Opossum && (key === Opossum.TRICK_KEY || key === "opossum" || key === "grin")) return Opossum;
    if (Beaver && (key === Beaver.TRICK_KEY || key === "beaver" || key === "dam")) return Beaver;
    if (Porcupine && (key === Porcupine.TRICK_KEY || key === "porcupine" || key === "spine")) return Porcupine;
    if (BlackBear && (key === BlackBear.TRICK_KEY || key === "black_bear" || key === "coal")) return BlackBear;
    if (Capybara && (key === Capybara.TRICK_KEY || key === "capybara" || key === "soak")) return Capybara;
    if (Gecko && (key === Gecko.TRICK_KEY || key === "gecko" || key === "pad")) return Gecko;
    if (Anole && (key === Anole.TRICK_KEY || key === "anole" || key === "wink")) return Anole;
    if (Skink && (key === Skink.TRICK_KEY || key === "skink" || key === "dash")) return Skink;
    if (Chameleon && (key === Chameleon.TRICK_KEY || key === "chameleon" || key === "shift")) return Chameleon;
    if (HornedLizard && (key === HornedLizard.TRICK_KEY || key === "horned_lizard" || key === "spike")) return HornedLizard;
    if (Alligator && (key === Alligator.TRICK_KEY || key === "alligator" || key === "levee")) return Alligator;
    if (Crocodile && (key === Crocodile.TRICK_KEY || key === "crocodile" || key === "jaw")) return Crocodile;
    if (Snapper && (key === Snapper.TRICK_KEY || key === "snapper" || key === "beak")) return Snapper;
    if (BoxTurtle && (key === BoxTurtle.TRICK_KEY || key === "box_turtle" || key === "lid")) return BoxTurtle;
    if (Tuatara && (key === Tuatara.TRICK_KEY || key === "tuatara" || key === "peak")) return Tuatara;
    if (Bass && (key === Bass.TRICK_KEY || key === "bass" || key === "lunge")) return Bass;
    if (BrookTrout && (key === BrookTrout.TRICK_KEY || key === "brook_trout" || key === "speck")) return BrookTrout;
    if (Catfish && (key === Catfish.TRICK_KEY || key === "catfish" || key === "whisk")) return Catfish;
    if (Bluegill && (key === Bluegill.TRICK_KEY || key === "bluegill" || key === "penny")) return Bluegill;
    if (Perch && (key === Perch.TRICK_KEY || key === "perch" || key === "bar")) return Perch;
    if (Pike && (key === Pike.TRICK_KEY || key === "pike" || key === "lance")) return Pike;
    if (Walleye && (key === Walleye.TRICK_KEY || key === "walleye" || key === "night")) return Walleye;
    if (Paddlefish && (key === Paddlefish.TRICK_KEY || key === "paddlefish" || key === "spoon")) return Paddlefish;
    if (Lamprey && (key === Lamprey.TRICK_KEY || key === "lamprey" || key === "round")) return Lamprey;
    if (AmericanEel && (key === AmericanEel.TRICK_KEY || key === "american_eel" || key === "silver")) return AmericanEel;
    if (HouseCentipede && (key === HouseCentipede.TRICK_KEY || key === "house_centipede" || key === "haste")) return HouseCentipede;
    if (Millipede && (key === Millipede.TRICK_KEY || key === "millipede" || key === "link")) return Millipede;
    if (Pillbug && (key === Pillbug.TRICK_KEY || key === "pillbug" || key === "armor")) return Pillbug;
    if (Earthworm && (key === Earthworm.TRICK_KEY || key === "earthworm" || key === "cast")) return Earthworm;
    if (VelvetWorm && (key === VelvetWorm.TRICK_KEY || key === "velvet_worm" || key === "jet")) return VelvetWorm;
    if (Springtail && (key === Springtail.TRICK_KEY || key === "springtail" || key === "hop")) return Springtail;
    if (Tardigrade && (key === Tardigrade.TRICK_KEY || key === "tardigrade" || key === "tun")) return Tardigrade;
    if (Planarian && (key === Planarian.TRICK_KEY || key === "planarian" || key === "half")) return Planarian;
    if (Nematode && (key === Nematode.TRICK_KEY || key === "nematode" || key === "thread")) return Nematode;
    if (Amphipod && (key === Amphipod.TRICK_KEY || key === "amphipod" || key === "scud")) return Amphipod;
  if (FiddlerCrab && (key === FiddlerCrab.TRICK_KEY || key === "fiddler_crab" || key === "wave")) return FiddlerCrab;
  if (GhostCrab && (key === GhostCrab.TRICK_KEY || key === "ghost_crab" || key === "pale")) return GhostCrab;
  if (Limpet && (key === Limpet.TRICK_KEY || key === "limpet" || key === "cone")) return Limpet;
  if (Barnacle && (key === Barnacle.TRICK_KEY || key === "barnacle" || key === "cement")) return Barnacle;
  if (Chiton && (key === Chiton.TRICK_KEY || key === "chiton" || key === "mail")) return Chiton;
    if (Periwinkle && (key === Periwinkle.TRICK_KEY || key === "periwinkle" || key === "spire")) return Periwinkle;
    if (SandDollar && (key === SandDollar.TRICK_KEY || key === "sand_dollar" || key === "token")) return SandDollar;
    if (SeaUrchin && (key === SeaUrchin.TRICK_KEY || key === "sea_urchin" || key === "thorn")) return SeaUrchin;
    if (KnobbedWhelk && (key === KnobbedWhelk.TRICK_KEY || key === "knobbed_whelk" || key === "knurl")) return KnobbedWhelk;
    if (Lugworm && (key === Lugworm.TRICK_KEY || key === "lugworm" || key === "heap")) return Lugworm;
    if (FieldCricket && (key === FieldCricket.TRICK_KEY || key === "field_cricket" || key === "chirp")) return FieldCricket;
    if (Katydid && (key === Katydid.TRICK_KEY || key === "katydid" || key === "blade")) return Katydid;
    if (Grasshopper && (key === Grasshopper.TRICK_KEY || key === "grasshopper" || key === "vault")) return Grasshopper;
    if (Swallowtail && (key === Swallowtail.TRICK_KEY || key === "swallowtail" || key === "banner")) return Swallowtail;
    if (Jewelwing && (key === Jewelwing.TRICK_KEY || key === "jewelwing" || key === "jewel")) return Jewelwing;
    if (Lacewing && (key === Lacewing.TRICK_KEY || key === "lacewing" || key === "lace")) return Lacewing;
    if (Earwig && (key === Earwig.TRICK_KEY || key === "earwig" || key === "forceps")) return Earwig;
    if (AcornWeevil && (key === AcornWeevil.TRICK_KEY || key === "acorn_weevil" || key === "snout")) return AcornWeevil;
    if (ClickBeetle && (key === ClickBeetle.TRICK_KEY || key === "click_beetle" || key === "click")) return ClickBeetle;
    if (RobberFly && (key === RobberFly.TRICK_KEY || key === "robber_fly" || key === "rob")) return RobberFly;
    if (Sloth && (key === Sloth.TRICK_KEY || key === "sloth" || key === "hang")) return Sloth;
    if (Lemur && (key === Lemur.TRICK_KEY || key === "lemur" || key === "sun")) return Lemur;
    if (Gibbon && (key === Gibbon.TRICK_KEY || key === "gibbon" || key === "swing")) return Gibbon;
    if (Kinkajou && (key === Kinkajou.TRICK_KEY || key === "kinkajou" || key === "wrist")) return Kinkajou;
    if (Colugo && (key === Colugo.TRICK_KEY || key === "colugo" || key === "sail")) return Colugo;
    if (FlyingSquirrel && (key === FlyingSquirrel.TRICK_KEY || key === "flying_squirrel" || key === "glide")) return FlyingSquirrel;
    if (Howler && (key === Howler.TRICK_KEY || key === "howler" || key === "boom")) return Howler;
    if (Tarsier && (key === Tarsier.TRICK_KEY || key === "tarsier" || key === "gaze")) return Tarsier;
    if (Potto && (key === Potto.TRICK_KEY || key === "potto" || key === "still")) return Potto;
    if (Koala && (key === Koala.TRICK_KEY || key === "koala" || key === "gum")) return Koala;
    if (BrainCoral && (key === BrainCoral.TRICK_KEY || key === "brain_coral" || key === "ridge")) return BrainCoral;
    if (Anemone && (key === Anemone.TRICK_KEY || key === "anemone" || key === "wreath")) return Anemone;
    if (Clownfish && (key === Clownfish.TRICK_KEY || key === "clownfish" || key === "paint")) return Clownfish;
    if (Parrotfish && (key === Parrotfish.TRICK_KEY || key === "parrotfish" || key === "scrape")) return Parrotfish;
    if (CleanerShrimp && (key === CleanerShrimp.TRICK_KEY || key === "cleaner_shrimp" || key === "scrub")) return CleanerShrimp;
    if (SeaCucumber && (key === SeaCucumber.TRICK_KEY || key === "sea_cucumber" || key === "tube")) return SeaCucumber;
    if (Lionfish && (key === Lionfish.TRICK_KEY || key === "lionfish" || key === "veil")) return Lionfish;
    if (GiantClam && (key === GiantClam.TRICK_KEY || key === "giant_clam" || key === "gate")) return GiantClam;
    if (EagleRay && (key === EagleRay.TRICK_KEY || key === "eagle_ray" || key === "soar")) return EagleRay;
    if (Grouper && (key === Grouper.TRICK_KEY || key === "grouper" || key === "hide")) return Grouper;
    if (CyberDragon && (key === CyberDragon.TRICK_KEY || key === "cyber_dragon" || key === "arc")) return CyberDragon;
    if (VoltDragon && (key === VoltDragon.TRICK_KEY || key === "volt_dragon" || key === "volt")) return VoltDragon;
    if (TraceDragon && (key === TraceDragon.TRICK_KEY || key === "trace_dragon" || key === "trace")) return TraceDragon;
    if (FluxDragon && (key === FluxDragon.TRICK_KEY || key === "flux_dragon" || key === "flux")) return FluxDragon;
    if (SparkDragon && (key === SparkDragon.TRICK_KEY || key === "spark_dragon" || key === "crackle")) return SparkDragon;
    if (IonDragon && (key === IonDragon.TRICK_KEY || key === "ion_dragon" || key === "ion")) return IonDragon;
    if (GaussDragon && (key === GaussDragon.TRICK_KEY || key === "gauss_dragon" || key === "gauss")) return GaussDragon;
    if (Paramecium && (key === Paramecium.TRICK_KEY || key === "paramecium" || key === "boot")) return Paramecium;
    if (Amoeba && (key === Amoeba.TRICK_KEY || key === "amoeba" || key === "reach")) return Amoeba;
    if (Euglena && (key === Euglena.TRICK_KEY || key === "euglena" || key === "spot")) return Euglena;
    if (Volvox && (key === Volvox.TRICK_KEY || key === "volvox" || key === "orb")) return Volvox;
    if (Diatom && (key === Diatom.TRICK_KEY || key === "diatom" || key === "pane")) return Diatom;
    if (Kelp && (key === Kelp.TRICK_KEY || key === "kelp" || key === "hold")) return Kelp;
    if (Chlamydomonas && (key === Chlamydomonas.TRICK_KEY || key === "chlamydomonas" || key === "spin")) return Chlamydomonas;
    if (Stentor && (key === Stentor.TRICK_KEY || key === "stentor" || key === "bell")) return Stentor;
    if (Coli && (key === Coli.TRICK_KEY || key === "coli" || key === "rod")) return Coli;
    if (Haloarchaea && (key === Haloarchaea.TRICK_KEY || key === "haloarchaea" || key === "rose")) return Haloarchaea;
    return null;
  }

  function wantsThankYou(key) {
    const T = tricksFor(key);
    return !!(T && T.wantsThankYou && T.wantsThankYou(key));
  }

  function startThankYou(key, lastKind, x, facing, flags) {
    const T = tricksFor(key);
    if (!T || !T.startThankYou) return null;
    return T.startThankYou(key, lastKind, x, facing, flags);
  }

  function sleepHoldFrame(key, frameCount) {
    const T = tricksFor(key);
    if (!T || !T.sleepHoldFrame) return null;
    return T.sleepHoldFrame(key, frameCount);
  }

  const api = { tricksFor, wantsThankYou, startThankYou, sleepHoldFrame };
  if (typeof module !== "undefined" && module.exports) module.exports = api;
  root.PetGroundTricks = api;
})(typeof window !== "undefined" ? window : globalThis);




