/** Species ground-trick registry. Rui, Relay, Fuse, Ground, Miso, Pip, Thimble, Clip, Whee, Ink, Coin, Echo, Rue, Peck, Quill, Wick, Burr, Floss, Bloom, Keel, Sol, Vesper, Ember, Nori, Saffron, Bandit, Jade, Bluff, Sash, Lula, Coral, Blush, Atlas, Cup, Sepia, Chamber, Pulse, Cling, Tenant, Ledger, Anchor, Kite, Door, Felt, Vein, Fan, Mast, Disk, Moth, Arm, Snap, Drown, Dew, Comb, Milk, Ghost, Spark, Dart, Twig, Column, Seven, Fold, Brood, Thrum, Auger, Mortar, Disc, Pot, Sheen, Bank, Hum, Keep, Wax, Frill, Cap, Lattice, Horn, Ring, Mane, Puff, Flame, Starter, Pact, Gleam, Choir, Drift, Shard, Dusk, Knot, Brine, Beacon, Hush, Arca, Reed, Pebble, Eft, Dapple, Slip, Pinch, Whorl, Hinge, Latch, Prickle, Soot, Wedge, Heart, Hook, Dee, Brick, Drake, Vee, Drum, Sip, Loom, Leap, Prowl, Velvet, Hour, Stem, Barb, Whip, Clasp, Gale, Flag, and Cape today. Overlay + /demo lockstep. */
(function (root) {
  function tricksFor(key) {
    if (!key) return null;
    const Rui = root.PetRuiTricks;
    const Relay = root.PetRelayTricks;
    const Fuse = root.PetFuseTricks;
    const Earth = root.PetEarthTricks;
    const Cat = root.PetCatTricks;
    const Dog = root.PetDogTricks;
    const Rabbit = root.PetRabbitTricks;
    const Hamster = root.PetHamsterTricks;
    const GuineaPig = root.PetGuineaPigTricks;
    const Turtle = root.PetTurtleTricks;
    const Goldfish = root.PetGoldfishTricks;
    const Budgie = root.PetBudgieTricks;
    const Fox = root.PetFoxTricks;
    const Penguin = root.PetPenguinTricks;
    const Parrot = root.PetParrotTricks;
    const Ferret = root.PetFerretTricks;
    const Hedgehog = root.PetHedgehogTricks;
    const Chinchilla = root.PetChinchillaTricks;
    const Axolotl = root.PetAxolotlTricks;
    const Toucan = root.PetToucanTricks;
    const Iguana = root.PetIguanaTricks;
    const Dragon = root.PetDragonTricks;
    const Phoenix = root.PetPhoenixTricks;
    const BallPython = root.PetBallPythonTricks;
    const CornSnake = root.PetCornSnakeTricks;
    const Kingsnake = root.PetKingsnakeTricks;
    const GreenTreePython = root.PetGreenTreePythonTricks;
    const Hognose = root.PetHognoseTricks;
    const Garter = root.PetGarterTricks;
    const Boa = root.PetBoaTricks;
    const MilkSnake = root.PetMilkSnakeTricks;
    const RosyBoa = root.PetRosyBoaTricks;
    const CarpetPython = root.PetCarpetPythonTricks;
    const Octopus = root.PetOctopusTricks;
    const Cuttlefish = root.PetCuttlefishTricks;
    const Nautilus = root.PetNautilusTricks;
    const MoonJelly = root.PetMoonJellyTricks;
    const SeaStar = root.PetSeaStarTricks;
    const HermitCrab = root.PetHermitCrabTricks;
    const HorseshoeCrab = root.PetHorseshoeCrabTricks;
    const Seahorse = root.PetSeahorseTricks;
    const Manta = root.PetMantaTricks;
    const Moray = root.PetMorayTricks;
    const Moss = root.PetMossTricks;
    const Maidenhair = root.PetMaidenhairTricks;
    const Ginkgo = root.PetGinkgoTricks;
    const Oak = root.PetOakTricks;
    const WaterLily = root.PetWaterLilyTricks;
    const Orchid = root.PetOrchidTricks;
    const Saguaro = root.PetSaguaroTricks;
    const VenusFlytrap = root.PetVenusFlytrapTricks;
    const Pitcher = root.PetPitcherTricks;
    const Sundew = root.PetSundewTricks;
    const Honeybee = root.PetHoneybeeTricks;
    const Monarch = root.PetMonarchTricks;
    const Luna = root.PetLunaTricks;
    const Firefly = root.PetFireflyTricks;
    const Darner = root.PetDarnerTricks;
    const Stick = root.PetStickTricks;
    const CarpenterAnt = root.PetCarpenterAntTricks;
    const Ladybird = root.PetLadybirdTricks;
    const Mantis = root.PetMantisTricks;
    const Cicada = root.PetCicadaTricks;
    const Bumblebee = root.PetBumblebeeTricks;
    const CarpenterBee = root.PetCarpenterBeeTricks;
    const MasonBee = root.PetMasonBeeTricks;
    const Leafcutter = root.PetLeafcutterTricks;
    const Stingless = root.PetStinglessTricks;
    const SweatBee = root.PetSweatBeeTricks;
    const MiningBee = root.PetMiningBeeTricks;
    const HoneyDrone = root.PetHoneyDroneTricks;
    const HoneyQueen = root.PetHoneyQueenTricks;
  const Honeycomb = root.PetHoneycombTricks;
  const Oyster = root.PetOysterTricks;
  const FlyAgaric = root.PetFlyAgaricTricks;
const Morel = root.PetMorelTricks;
  const Chanterelle = root.PetChanterelleTricks;
  const TurkeyTail = root.PetTurkeyTailTricks;
  const LionsMane = root.PetLionsManeTricks;
  const Puffball = root.PetPuffballTricks;
  const ChickenOfWoods = root.PetChickenOfWoodsTricks;
  const Yeast = root.PetYeastTricks;
  const Lichen = root.PetLichenTricks;
  const Photovore = root.PetPhotovoreTricks;
  const Choir = root.PetChoirTricks;
  const Nimbus = root.PetNimbusTricks;
  const Silica = root.PetSilicaTricks;
  const Terminator = root.PetTerminatorTricks;
  const Nexus = root.PetNexusTricks;
  const Halovore = root.PetHalovoreTricks;
  const Magneton = root.PetMagnetonTricks;
  const Umbral = root.PetUmbralTricks;
  const Cyst = root.PetCystTricks;
  const Frog = root.PetFrogTricks;
  const Toad = root.PetToadTricks;
  const Newt = root.PetNewtTricks;
  const Salamander = root.PetSalamanderTricks;
  const Caecilian = root.PetCaecilianTricks;
  const Crayfish = root.PetCrayfishTricks;
  const PondSnail = root.PetPondSnailTricks;
  const Mussel = root.PetMusselTricks;
  const Leech = root.PetLeechTricks;
  const Stickleback = root.PetSticklebackTricks;
  const Crow = root.PetCrowTricks;
  const Raven = root.PetRavenTricks;
  const BarnOwl = root.PetBarnOwlTricks;
  const RedTail = root.PetRedTailTricks;
  const Chickadee = root.PetChickadeeTricks;
  const Robin = root.PetRobinTricks;
  const Mallard = root.PetMallardTricks;
  const CanadaGoose = root.PetCanadaGooseTricks;
  const Pileated = root.PetPileatedTricks;
  const Hummingbird = root.PetHummingbirdTricks;
  const OrbWeaver = root.PetOrbWeaverTricks;
  const JumpingSpider = root.PetJumpingSpiderTricks;
  const WolfSpider = root.PetWolfSpiderTricks;
  const Tarantula = root.PetTarantulaTricks;
  const Widow = root.PetWidowTricks;
  const Harvestman = root.PetHarvestmanTricks;
  const Scorpion = root.PetScorpionTricks;
  const Vinegaroon = root.PetVinegaroonTricks;
  const Tick = root.PetTickTricks;
  const Solifuge = root.PetSolifugeTricks;
  const Deer = root.PetDeerTricks;
  const Bat = root.PetBatTricks;
    if (Rui && (key === Rui.TRICK_KEY || key === "rui")) return Rui;
    if (Relay && (key === Relay.TRICK_KEY || key === "relay")) return Relay;
    if (Fuse && (key === Fuse.TRICK_KEY || key === "fuse")) return Fuse;
    if (Earth && (key === Earth.TRICK_KEY || key === "ground")) return Earth;
    if (Cat && (key === Cat.TRICK_KEY || key === "miso")) return Cat;
    if (Dog && (key === Dog.TRICK_KEY || key === "pip")) return Dog;
    if (Rabbit && (key === Rabbit.TRICK_KEY || key === "thimble")) return Rabbit;
    if (Hamster && (key === Hamster.TRICK_KEY || key === "clip")) return Hamster;
    if (GuineaPig && (key === GuineaPig.TRICK_KEY || key === "whee")) return GuineaPig;
    if (Turtle && (key === Turtle.TRICK_KEY || key === "ink")) return Turtle;
    if (Goldfish && (key === Goldfish.TRICK_KEY || key === "coin")) return Goldfish;
    if (Budgie && (key === Budgie.TRICK_KEY || key === "echo")) return Budgie;
    if (Fox && (key === Fox.TRICK_KEY || key === "rue")) return Fox;
    if (Penguin && (key === Penguin.TRICK_KEY || key === "peck")) return Penguin;
    if (Parrot && (key === Parrot.TRICK_KEY || key === "quill")) return Parrot;
    if (Ferret && (key === Ferret.TRICK_KEY || key === "wick")) return Ferret;
    if (Hedgehog && (key === Hedgehog.TRICK_KEY || key === "burr")) return Hedgehog;
    if (Chinchilla && (key === Chinchilla.TRICK_KEY || key === "floss")) return Chinchilla;
    if (Axolotl && (key === Axolotl.TRICK_KEY || key === "bloom")) return Axolotl;
    if (Toucan && (key === Toucan.TRICK_KEY || key === "keel")) return Toucan;
    if (Iguana && (key === Iguana.TRICK_KEY || key === "sol")) return Iguana;
    if (Dragon && (key === Dragon.TRICK_KEY || key === "vesper")) return Dragon;
    if (Phoenix && (key === Phoenix.TRICK_KEY || key === "ember")) return Phoenix;
    if (BallPython && (key === BallPython.TRICK_KEY || key === "nori")) return BallPython;
    if (CornSnake && (key === CornSnake.TRICK_KEY || key === "saffron")) return CornSnake;
    if (Kingsnake && (key === Kingsnake.TRICK_KEY || key === "bandit")) return Kingsnake;
    if (GreenTreePython && (key === GreenTreePython.TRICK_KEY || key === "jade")) return GreenTreePython;
    if (Hognose && (key === Hognose.TRICK_KEY || key === "bluff")) return Hognose;
    if (Garter && (key === Garter.TRICK_KEY || key === "sash")) return Garter;
    if (Boa && (key === Boa.TRICK_KEY || key === "lula")) return Boa;
    if (MilkSnake && (key === MilkSnake.TRICK_KEY || key === "coral")) return MilkSnake;
    if (RosyBoa && (key === RosyBoa.TRICK_KEY || key === "blush")) return RosyBoa;
    if (CarpetPython && (key === CarpetPython.TRICK_KEY || key === "atlas")) return CarpetPython;
    if (Octopus && (key === Octopus.TRICK_KEY || key === "cup")) return Octopus;
    if (Cuttlefish && (key === Cuttlefish.TRICK_KEY || key === "sepia")) return Cuttlefish;
    if (Nautilus && (key === Nautilus.TRICK_KEY || key === "chamber")) return Nautilus;
    if (MoonJelly && (key === MoonJelly.TRICK_KEY || key === "pulse")) return MoonJelly;
    if (SeaStar && (key === SeaStar.TRICK_KEY || key === "cling")) return SeaStar;
    if (HermitCrab && (key === HermitCrab.TRICK_KEY || key === "tenant")) return HermitCrab;
    if (HorseshoeCrab && (key === HorseshoeCrab.TRICK_KEY || key === "ledger")) return HorseshoeCrab;
    if (Seahorse && (key === Seahorse.TRICK_KEY || key === "anchor")) return Seahorse;
    if (Manta && (key === Manta.TRICK_KEY || key === "kite")) return Manta;
    if (Moray && (key === Moray.TRICK_KEY || key === "door")) return Moray;
    if (Moss && (key === Moss.TRICK_KEY || key === "felt")) return Moss;
    if (Maidenhair && (key === Maidenhair.TRICK_KEY || key === "vein")) return Maidenhair;
    if (Ginkgo && (key === Ginkgo.TRICK_KEY || key === "fan")) return Ginkgo;
    if (Oak && (key === Oak.TRICK_KEY || key === "mast")) return Oak;
    if (WaterLily && (key === WaterLily.TRICK_KEY || key === "disk")) return WaterLily;
    if (Orchid && (key === Orchid.TRICK_KEY || key === "moth")) return Orchid;
    if (Saguaro && (key === Saguaro.TRICK_KEY || key === "arm")) return Saguaro;
    if (VenusFlytrap && (key === VenusFlytrap.TRICK_KEY || key === "snap")) return VenusFlytrap;
    if (Pitcher && (key === Pitcher.TRICK_KEY || key === "drown")) return Pitcher;
    if (Sundew && (key === Sundew.TRICK_KEY || key === "dew")) return Sundew;
    if (Honeybee && (key === Honeybee.TRICK_KEY || key === "comb")) return Honeybee;
    if (Monarch && (key === Monarch.TRICK_KEY || key === "milk")) return Monarch;
    if (Luna && (key === Luna.TRICK_KEY || key === "ghost")) return Luna;
    if (Firefly && (key === Firefly.TRICK_KEY || key === "spark")) return Firefly;
    if (Darner && (key === Darner.TRICK_KEY || key === "dart")) return Darner;
    if (Stick && (key === Stick.TRICK_KEY || key === "twig")) return Stick;
    if (CarpenterAnt && (key === CarpenterAnt.TRICK_KEY || key === "column")) return CarpenterAnt;
    if (Ladybird && (key === Ladybird.TRICK_KEY || key === "seven")) return Ladybird;
    if (Mantis && (key === Mantis.TRICK_KEY || key === "fold")) return Mantis;
    if (Cicada && (key === Cicada.TRICK_KEY || key === "brood")) return Cicada;
    if (Bumblebee && (key === Bumblebee.TRICK_KEY || key === "thrum")) return Bumblebee;
    if (CarpenterBee && (key === CarpenterBee.TRICK_KEY || key === "auger")) return CarpenterBee;
    if (MasonBee && (key === MasonBee.TRICK_KEY || key === "mortar")) return MasonBee;
    if (Leafcutter && (key === Leafcutter.TRICK_KEY || key === "disc")) return Leafcutter;
    if (Stingless && (key === Stingless.TRICK_KEY || key === "pot")) return Stingless;
    if (SweatBee && (key === SweatBee.TRICK_KEY || key === "sheen")) return SweatBee;
    if (MiningBee && (key === MiningBee.TRICK_KEY || key === "bank")) return MiningBee;
    if (HoneyDrone && (key === HoneyDrone.TRICK_KEY || key === "hum")) return HoneyDrone;
    if (HoneyQueen && (key === HoneyQueen.TRICK_KEY || key === "keep")) return HoneyQueen;
    if (Honeycomb && (key === Honeycomb.TRICK_KEY || key === "wax")) return Honeycomb;
    if (Oyster && (key === Oyster.TRICK_KEY || key === "frill")) return Oyster;
    if (FlyAgaric && (key === FlyAgaric.TRICK_KEY || key === "cap")) return FlyAgaric;
if (Morel && (key === Morel.TRICK_KEY || key === "lattice")) return Morel;
    if (Chanterelle && (key === Chanterelle.TRICK_KEY || key === "horn")) return Chanterelle;
    if (TurkeyTail && (key === TurkeyTail.TRICK_KEY || key === "ring")) return TurkeyTail;
    if (LionsMane && (key === LionsMane.TRICK_KEY || key === "mane")) return LionsMane;
    if (Puffball && (key === Puffball.TRICK_KEY || key === "puff")) return Puffball;
    if (ChickenOfWoods && (key === ChickenOfWoods.TRICK_KEY || key === "flame")) return ChickenOfWoods;
    if (Yeast && (key === Yeast.TRICK_KEY || key === "starter")) return Yeast;
    if (Lichen && (key === Lichen.TRICK_KEY || key === "pact")) return Lichen;
    if (Photovore && (key === Photovore.TRICK_KEY || key === "gleam")) return Photovore;
    if (Choir && (key === Choir.TRICK_KEY || key === "choir")) return Choir;
    if (Nimbus && (key === Nimbus.TRICK_KEY || key === "nimbus" || key === "drift")) return Nimbus;
    if (Silica && (key === Silica.TRICK_KEY || key === "silica" || key === "shard")) return Silica;
    if (Terminator && (key === Terminator.TRICK_KEY || key === "terminator" || key === "dusk")) return Terminator;
    if (Nexus && (key === Nexus.TRICK_KEY || key === "nexus" || key === "knot")) return Nexus;
    if (Halovore && (key === Halovore.TRICK_KEY || key === "halovore" || key === "brine")) return Halovore;
    if (Magneton && (key === Magneton.TRICK_KEY || key === "magneton" || key === "beacon")) return Magneton;
    if (Umbral && (key === Umbral.TRICK_KEY || key === "umbral" || key === "hush")) return Umbral;
    if (Cyst && (key === Cyst.TRICK_KEY || key === "cyst" || key === "arca")) return Cyst;
    if (Frog && (key === Frog.TRICK_KEY || key === "frog" || key === "reed")) return Frog;
    if (Toad && (key === Toad.TRICK_KEY || key === "toad" || key === "pebble")) return Toad;
    if (Newt && (key === Newt.TRICK_KEY || key === "newt" || key === "eft")) return Newt;
    if (Salamander && (key === Salamander.TRICK_KEY || key === "salamander" || key === "dapple")) return Salamander;
    if (Caecilian && (key === Caecilian.TRICK_KEY || key === "caecilian" || key === "slip")) return Caecilian;
    if (Crayfish && (key === Crayfish.TRICK_KEY || key === "crayfish" || key === "pinch")) return Crayfish;
    if (PondSnail && (key === PondSnail.TRICK_KEY || key === "pond_snail" || key === "whorl")) return PondSnail;
    if (Mussel && (key === Mussel.TRICK_KEY || key === "mussel" || key === "hinge")) return Mussel;
    if (Leech && (key === Leech.TRICK_KEY || key === "leech" || key === "latch")) return Leech;
    if (Stickleback && (key === Stickleback.TRICK_KEY || key === "stickleback" || key === "prickle")) return Stickleback;
    if (Crow && (key === Crow.TRICK_KEY || key === "crow" || key === "soot")) return Crow;
    if (Raven && (key === Raven.TRICK_KEY || key === "raven" || key === "wedge")) return Raven;
    if (BarnOwl && (key === BarnOwl.TRICK_KEY || key === "barn_owl" || key === "heart")) return BarnOwl;
    if (RedTail && (key === RedTail.TRICK_KEY || key === "red_tail" || key === "hook")) return RedTail;
    if (Chickadee && (key === Chickadee.TRICK_KEY || key === "chickadee" || key === "dee")) return Chickadee;
    if (Robin && (key === Robin.TRICK_KEY || key === "robin" || key === "brick")) return Robin;
    if (Mallard && (key === Mallard.TRICK_KEY || key === "mallard" || key === "drake")) return Mallard;
    if (CanadaGoose && (key === CanadaGoose.TRICK_KEY || key === "canada_goose" || key === "vee")) return CanadaGoose;
    if (Pileated && (key === Pileated.TRICK_KEY || key === "pileated" || key === "drum")) return Pileated;
    if (Hummingbird && (key === Hummingbird.TRICK_KEY || key === "hummingbird" || key === "sip")) return Hummingbird;
    if (OrbWeaver && (key === OrbWeaver.TRICK_KEY || key === "orb_weaver" || key === "loom")) return OrbWeaver;
    if (JumpingSpider && (key === JumpingSpider.TRICK_KEY || key === "jumping_spider" || key === "leap")) return JumpingSpider;
    if (WolfSpider && (key === WolfSpider.TRICK_KEY || key === "wolf_spider" || key === "prowl")) return WolfSpider;
    if (Tarantula && (key === Tarantula.TRICK_KEY || key === "tarantula" || key === "velvet")) return Tarantula;
    if (Widow && (key === Widow.TRICK_KEY || key === "widow" || key === "hour")) return Widow;
    if (Harvestman && (key === Harvestman.TRICK_KEY || key === "harvestman" || key === "stem")) return Harvestman;
    if (Scorpion && (key === Scorpion.TRICK_KEY || key === "scorpion" || key === "barb")) return Scorpion;
    if (Vinegaroon && (key === Vinegaroon.TRICK_KEY || key === "vinegaroon" || key === "whip")) return Vinegaroon;
    if (Tick && (key === Tick.TRICK_KEY || key === "tick" || key === "clasp")) return Tick;
    if (Solifuge && (key === Solifuge.TRICK_KEY || key === "solifuge" || key === "gale")) return Solifuge;
    if (Deer && (key === Deer.TRICK_KEY || key === "deer" || key === "rack")) return Deer;
    if (Bat && (key === Bat.TRICK_KEY || key === "bat" || key === "cape")) return Bat;
  }

  function wantsThankYou(key) {
    const T = tricksFor(key);
    return !!(T && T.wantsThankYou && T.wantsThankYou(key));
  }

  function startThankYou(key, lastKind, x, facing, flags) {
    const T = tricksFor(key);
    if (!T || !T.startThankYou) return null;
    return T.startThankYou(key, lastKind, x, facing, flags);
  }

  function sleepHoldFrame(key, frameCount) {
    const T = tricksFor(key);
    if (!T || !T.sleepHoldFrame) return null;
    return T.sleepHoldFrame(key, frameCount);
  }

  const api = { tricksFor, wantsThankYou, startThankYou, sleepHoldFrame };
  if (typeof module !== "undefined" && module.exports) module.exports = api;
  root.PetGroundTricks = api;
})(typeof window !== "undefined" ? window : globalThis);




