/** House snack lines. Same copy as web/src/lib/pets/hours.ts and the blotter. */
(function (root) {
  const SNACK_LINE = {
  red_panda: "A small treaty. Bamboo-adjacent.",
  cat: "I allow this crumb.",
  dog: "For me? I have prepared a sit.",
  rabbit: "A green thing. Correct.",
  hamster: "It fits. Officially.",
  guinea_pig: "Wheek, but smaller.",
  turtle: "I will arrive at the crumb in due course.",
  goldfish: "It drifted. I followed.",
  budgie: "Seed. The only review that matters.",
  fox: "I found it first.",
  penguin: "A pebble of food. Accepted.",
  parrot: "Crunch. Noted.",
  ferret: "Mine. Also that other bit.",
  hedgehog: "A quiet nibble.",
  chinchilla: "That crumb was a scandal. Now it is gone.",
  axolotl: "I grew a little more fed.",
  toucan: "The bill approves.",
  iguana: "I blinked at it. Then I ate.",
  dragon: "Tribute. Modest.",
  phoenix: "Warm. Good.",
  ball_python: "I will sit on the thought of it.",
  corn_snake: "Pinkie diplomacy. Accepted.",
  kingsnake: "Tribute in bands of flavor.",
  green_tree_python: "Warmth first. Then the treaty.",
  hognose: "I will eat this after my scene.",
  garter: "Worm treaty. Signed in three copies.",
  boa: "Tribute. I will take my time.",
  milk_snake: "An egg of a treaty.",
  rosy_boa: "A mouse of manners.",
  carpet_python: "A morsel for the cartographer.",
  octopus: "A crab of a treaty.",
  cuttlefish: "A shrimp of a treaty.",
  nautilus: "Tribute for the older office.",
  moon_jelly: "A drift of food. Accepted.",
  sea_star: "I will finish this this afternoon.",
  hermit_crab: "Scrap diplomacy. Accepted.",
  horseshoe_crab: "A worm of a treaty.",
  seahorse: "A brine of a treaty.",
  manta: "A filter of a treaty.",
  moray: "A fish of a treaty.",
  moss: "Dew of a treaty.",
  maidenhair: "Mist of a treaty.",
  ginkgo: "A leaf of a treaty.",
  oak: "Water of a treaty.",
  water_lily: "Silt of a treaty.",
  orchid: "Mist of a treaty.",
  saguaro: "Rain of a treaty.",
  venus_flytrap: "A fly of a treaty.",
  pitcher: "A midge of a treaty.",
  sundew: "A gnat of a treaty.",
  honeybee: "Nectar of a treaty.",
  monarch: "Milkweed of a treaty.",
  luna: "Nothing of a treaty. I decline the bite.",
  firefly: "A midge of a treaty.",
  darner: "A mosquito of a treaty.",
  stick: "A leaf of a treaty.",
  carpenter_ant: "Honeydew of a treaty.",
  ladybird: "An aphid of a treaty.",
  mantis: "A fly of a treaty.",
  cicada: "Sap of a treaty.",
  bumblebee: "Nectar of a treaty.",
  carpenter_bee: "Nectar of a treaty.",
  mason_bee: "Pollen of a treaty.",
  leafcutter: "Pollen of a treaty.",
  stingless: "Nectar of a treaty.",
  sweat_bee: "Nectar of a treaty.",
  mining_bee: "Pollen of a treaty.",
  honey_drone: "Nectar a worker already carried.",
  honey_queen: "Jelly of a treaty.",
  honeycomb: "Nectar of a store. I do not bite.",
  oyster: "Wood of a treaty.",
  fly_agaric: "Duff of a treaty.",
  morel: "Duff of a treaty.",
  chanterelle: "Duff of a treaty.",
  turkey_tail: "Wood of a treaty.",
  lions_mane: "Wood of a treaty.",
  puffball: "Duff of a treaty.",
  chicken_of_woods: "Oak of a treaty.",
  yeast: "Dough of a treaty.",
  lichen: "Dew of a treaty.",
  photovore: "Light of a treaty.",
  choir: "Tone of a treaty.",
  nimbus: "Gas of a treaty.",
  silica: "Silica of a treaty.",
  terminator: "Rim of a treaty.",
  nexus: "Count of a treaty.",
  halovore: "Salt of a treaty.",
  magneton: "North of a treaty.",
  umbral: "Cool of a treaty.",
  cyst: "Damp of a treaty.",
  frog: "Cricket of a treaty.",
  toad: "Cricket of a treaty.",
  newt: "Worm of a treaty.",
  salamander: "Worm of a treaty.",
  caecilian: "Worm of a treaty.",
  crayfish: "Scrap of a treaty.",
  pond_snail: "Algae of a treaty.",
  mussel: "Silt of a treaty.",
  leech: "Worm of a treaty.",
  stickleback: "Flake of a treaty.",
  paramecium: "Bacteria of a treaty.",
  amoeba: "Prey of a treaty.",
  euglena: "Light of a treaty.",
  volvox: "Light of a treaty.",
  diatom: "Silica of a treaty.",
  kelp: "Light of a treaty.",
  chlamydomonas: "Light of a treaty.",
  stentor: "Bacteria of a treaty.",
  coli: "Broth of a treaty.",
  haloarchaea: "Salt of a treaty.",
  crow: "Scrap of a treaty.",
  raven: "Scrap of a treaty.",
  barn_owl: "Vole of a treaty.",
  red_tail: "Vole of a treaty.",
  chickadee: "Seed of a treaty.",
  robin: "Worm of a treaty.",
  mallard: "Seed of a treaty.",
  canada_goose: "Grass of a treaty.",
  pileated: "Ant of a treaty.",
  hummingbird: "Nectar of a treaty.",
  orb_weaver: "Fly of a treaty.",
  jumping_spider: "Fly of a treaty.",
  wolf_spider: "Cricket of a treaty.",
  tarantula: "Cricket of a treaty.",
  widow: "Fly of a treaty.",
  harvestman: "Mite of a treaty.",
  scorpion: "Cricket of a treaty.",
  vinegaroon: "Cricket of a treaty.",
  tick: "Sip of a treaty.",
  solifuge: "Cricket of a treaty.",
  deer: "Browse of a treaty.",
  bat: "Beetle of a treaty.",
  squirrel: "Acorn of a treaty.",
  otter: "Fish of a treaty.",
  raccoon: "Scrap of a treaty.",
  skunk: "Grub of a treaty.",
  opossum: "Scrap of a treaty.",
  beaver: "Bark of a treaty.",
  porcupine: "Bark of a treaty.",
  black_bear: "Berry of a treaty.",
  gecko: "Moth of a treaty.",
  anole: "Cricket of a treaty.",
  skink: "Cricket of a treaty.",
  chameleon: "Cricket of a treaty.",
  horned_lizard: "Ant of a treaty.",
  alligator: "Fish of a treaty.",
  crocodile: "Fish of a treaty.",
  snapper: "Fish of a treaty.",
  box_turtle: "Worm of a treaty.",
  tuatara: "Insect of a treaty.",
  bass: "Minnow of a treaty.",
  brook_trout: "Fly of a treaty.",
  catfish: "Scrap of a treaty.",
  bluegill: "Insect of a treaty.",
  perch: "Minnow of a treaty.",
  pike: "Fish of a treaty.",
  walleye: "Minnow of a treaty.",
  paddlefish: "Plankton of a treaty.",
  lamprey: "Stone of a treaty.",
  american_eel: "Scrap of a treaty.",
  house_centipede: "Silverfish of a treaty.",
  millipede: "Leaf of a treaty.",
  pillbug: "Leaf of a treaty.",
  earthworm: "Leaf of a treaty.",
  velvet_worm: "Cricket of a treaty.",
  springtail: "Flake of a treaty.",
  tardigrade: "Moss of a treaty.",
  planarian: "Worm of a treaty.",
  nematode: "Flake of a treaty.",
  amphipod: "Scrap of a treaty.",
  fiddler_crab: "Algae of a treaty.",
  ghost_crab: "Scrap of a treaty.",
  limpet: "Algae of a treaty.",
  barnacle: "Drift of a treaty.",
  chiton: "Algae of a treaty.",
  periwinkle: "Algae of a treaty.",
  sand_dollar: "Diatom of a treaty.",
  sea_urchin: "Kelp of a treaty.",
  knobbed_whelk: "Clam of a treaty.",
  lugworm: "Silt of a treaty.",
  field_cricket: "Seed of a treaty.",
  katydid: "Leaf of a treaty.",
  grasshopper: "Leaf of a treaty.",
  swallowtail: "Nectar of a treaty.",
  jewelwing: "Midge of a treaty.",
  lacewing: "Aphid of a treaty.",
  earwig: "Scrap of a treaty.",
  acorn_weevil: "Acorn of a treaty.",
  click_beetle: "Scrap of a treaty.",
  robber_fly: "Prey of a treaty.",
  sloth: "Leaf of a treaty.",
  lemur: "Fruit of a treaty.",
  gibbon: "Fruit of a treaty.",
  kinkajou: "Nectar of a treaty.",
  colugo: "Leaf of a treaty.",
  flying_squirrel: "Nut of a treaty.",
  howler: "Leaf of a treaty.",
  tarsier: "Insect of a treaty.",
  potto: "Gum of a treaty.",
  koala: "Gum of a treaty.",
  brain_coral: "Plankton of a treaty.",
  anemone: "Drift of a treaty.",
  clownfish: "Scrap of a treaty.",
  parrotfish: "Algae of a treaty.",
  cleaner_shrimp: "Scrap of a treaty.",
  sea_cucumber: "Detritus of a treaty.",
  lionfish: "Prey of a treaty.",
  giant_clam: "Light of a treaty.",
  eagle_ray: "Clam of a treaty.",
  grouper: "Fish of a treaty.",
};
  function snackLine(key, existing) {
    if (existing) return existing;
    return SNACK_LINE[key] || "A small treaty.";
  }

  const api = { SNACK_LINE, snackLine };
  if (typeof module !== "undefined" && module.exports) module.exports = api;
  root.PetHours = api;
})(typeof window !== "undefined" ? window : globalThis);
