/** House snack lines and the same night the desk already keeps. */
(function (root) {
  const SNACK_LINE = {
  red_panda: "A small treaty. Bamboo-adjacent.",
  cat: "I allow this crumb.",
  dog: "For me? I have prepared a sit.",
  rabbit: "A green thing. Correct.",
  hamster: "It fits. Officially.",
  guinea_pig: "Wheek, but smaller.",
  turtle: "I will arrive at the crumb in due course.",
  goldfish: "It drifted. I followed.",
  budgie: "Seed. The only review that matters.",
  fox: "I found it first.",
  penguin: "A pebble of food. Accepted.",
  parrot: "Crunch. Noted.",
  ferret: "Mine. Also that other bit.",
  hedgehog: "A quiet nibble.",
  chinchilla: "That crumb was a scandal. Now it is gone.",
  axolotl: "I grew a little more fed.",
  toucan: "The bill approves.",
  iguana: "I blinked at it. Then I ate.",
  dragon: "Tribute. Modest.",
  phoenix: "Warm. Good.",
  ball_python: "I will sit on the thought of it.",
  corn_snake: "Pinkie diplomacy. Accepted.",
  kingsnake: "Tribute in bands of flavor.",
  green_tree_python: "Warmth first. Then the treaty.",
  hognose: "I will eat this after my scene.",
  garter: "Worm treaty. Signed in three copies.",
  boa: "Tribute. I will take my time.",
  milk_snake: "An egg of a treaty.",
  rosy_boa: "A mouse of manners.",
  carpet_python: "A morsel for the cartographer.",
  octopus: "A crab of a treaty.",
  cuttlefish: "A shrimp of a treaty.",
  nautilus: "Tribute for the older office.",
  moon_jelly: "A drift of food. Accepted.",
  sea_star: "I will finish this this afternoon.",
  hermit_crab: "Scrap diplomacy. Accepted.",
  horseshoe_crab: "A worm of a treaty.",
  seahorse: "A brine of a treaty.",
  manta: "A filter of a treaty.",
  moray: "A fish of a treaty.",
  moss: "Dew of a treaty.",
  maidenhair: "Mist of a treaty.",
  ginkgo: "A leaf of a treaty.",
  oak: "Water of a treaty.",
  water_lily: "Silt of a treaty.",
  orchid: "Mist of a treaty.",
  saguaro: "Rain of a treaty.",
  venus_flytrap: "A fly of a treaty.",
  pitcher: "A midge of a treaty.",
  sundew: "A gnat of a treaty.",
  honeybee: "Nectar of a treaty.",
  monarch: "Milkweed of a treaty.",
  luna: "Nothing of a treaty. I decline the bite.",
  firefly: "A midge of a treaty.",
  darner: "A mosquito of a treaty.",
  stick: "A leaf of a treaty.",
  carpenter_ant: "Honeydew of a treaty.",
  ladybird: "An aphid of a treaty.",
  mantis: "A fly of a treaty.",
  cicada: "Sap of a treaty.",
  bumblebee: "Nectar of a treaty.",
  carpenter_bee: "Nectar of a treaty.",
  mason_bee: "Pollen of a treaty.",
  leafcutter: "Pollen of a treaty.",
  stingless: "Nectar of a treaty.",
  sweat_bee: "Nectar of a treaty.",
  mining_bee: "Pollen of a treaty.",
  honey_drone: "Nectar a worker already carried.",
  honey_queen: "Jelly of a treaty.",
  honeycomb: "Nectar of a store. I do not bite.",
  oyster: "Wood of a treaty.",
  fly_agaric: "Duff of a treaty.",
  morel: "Duff of a treaty.",
  chanterelle: "Duff of a treaty.",
  turkey_tail: "Wood of a treaty.",
  lions_mane: "Wood of a treaty.",
  puffball: "Duff of a treaty.",
  chicken_of_woods: "Oak of a treaty.",
  yeast: "Dough of a treaty.",
  lichen: "Dew of a treaty.",
  photovore: "Light of a treaty.",
  choir: "Tone of a treaty.",
  nimbus: "Gas of a treaty.",
  silica: "Silica of a treaty.",
  terminator: "Rim of a treaty.",
  nexus: "Count of a treaty.",
  halovore: "Salt of a treaty.",
  magneton: "North of a treaty.",
  umbral: "Cool of a treaty.",
  cyst: "Damp of a treaty.",
  frog: "Cricket of a treaty.",
  toad: "Cricket of a treaty.",
  newt: "Worm of a treaty.",
  salamander: "Worm of a treaty.",
  caecilian: "Worm of a treaty.",
  crayfish: "Scrap of a treaty.",
  pond_snail: "Algae of a treaty.",
  mussel: "Silt of a treaty.",
  leech: "Worm of a treaty.",
  stickleback: "Flake of a treaty.",
  paramecium: "Bacteria of a treaty.",
  amoeba: "Prey of a treaty.",
  euglena: "Light of a treaty.",
  volvox: "Light of a treaty.",
  diatom: "Silica of a treaty.",
  kelp: "Light of a treaty.",
  chlamydomonas: "Light of a treaty.",
  stentor: "Bacteria of a treaty.",
  coli: "Broth of a treaty.",
  haloarchaea: "Salt of a treaty.",
  crow: "Scrap of a treaty.",
  raven: "Scrap of a treaty.",
  barn_owl: "Vole of a treaty.",
  red_tail: "Vole of a treaty.",
  chickadee: "Seed of a treaty.",
  robin: "Worm of a treaty.",
  mallard: "Seed of a treaty.",
  canada_goose: "Grass of a treaty.",
  pileated: "Ant of a treaty.",
  hummingbird: "Nectar of a treaty.",
  orb_weaver: "Fly of a treaty.",
  jumping_spider: "Fly of a treaty.",
  wolf_spider: "Cricket of a treaty.",
  tarantula: "Cricket of a treaty.",
  widow: "Fly of a treaty.",
  harvestman: "Mite of a treaty.",
  scorpion: "Cricket of a treaty.",
  vinegaroon: "Cricket of a treaty.",
  tick: "Sip of a treaty.",
  solifuge: "Cricket of a treaty.",
  deer: "Browse of a treaty.",
  bat: "Beetle of a treaty.",
  squirrel: "Acorn of a treaty.",
  otter: "Fish of a treaty.",
  raccoon: "Scrap of a treaty.",
  skunk: "Grub of a treaty.",
  opossum: "Scrap of a treaty.",
  beaver: "Bark of a treaty.",
  porcupine: "Bark of a treaty.",
  black_bear: "Berry of a treaty.",
  gecko: "Moth of a treaty.",
  anole: "Cricket of a treaty.",
  skink: "Cricket of a treaty.",
  chameleon: "Cricket of a treaty.",
  horned_lizard: "Ant of a treaty.",
  alligator: "Fish of a treaty.",
  crocodile: "Fish of a treaty.",
  snapper: "Fish of a treaty.",
  box_turtle: "Worm of a treaty.",
  tuatara: "Insect of a treaty.",
  bass: "Minnow of a treaty.",
  brook_trout: "Fly of a treaty.",
  catfish: "Scrap of a treaty.",
  bluegill: "Insect of a treaty.",
  perch: "Minnow of a treaty.",
  pike: "Fish of a treaty.",
  walleye: "Minnow of a treaty.",
  paddlefish: "Plankton of a treaty.",
  lamprey: "Stone of a treaty.",
  american_eel: "Scrap of a treaty.",
  house_centipede: "Silverfish of a treaty.",
  millipede: "Leaf of a treaty.",
  pillbug: "Leaf of a treaty.",
  earthworm: "Leaf of a treaty.",
  velvet_worm: "Cricket of a treaty.",
  springtail: "Flake of a treaty.",
  tardigrade: "Moss of a treaty.",
  planarian: "Worm of a treaty.",
  nematode: "Flake of a treaty.",
  amphipod: "Scrap of a treaty.",
  fiddler_crab: "Algae of a treaty.",
  ghost_crab: "Scrap of a treaty.",
  limpet: "Algae of a treaty.",
  barnacle: "Drift of a treaty.",
  chiton: "Algae of a treaty.",
  periwinkle: "Algae of a treaty.",
  sand_dollar: "Diatom of a treaty.",
  sea_urchin: "Kelp of a treaty.",
  knobbed_whelk: "Clam of a treaty.",
  lugworm: "Silt of a treaty.",
  field_cricket: "Seed of a treaty.",
  katydid: "Leaf of a treaty.",
  grasshopper: "Leaf of a treaty.",
  swallowtail: "Nectar of a treaty.",
  jewelwing: "Midge of a treaty.",
  lacewing: "Aphid of a treaty.",
  earwig: "Scrap of a treaty.",
  acorn_weevil: "Acorn of a treaty.",
  click_beetle: "Scrap of a treaty.",
  robber_fly: "Prey of a treaty.",
  sloth: "Leaf of a treaty.",
  lemur: "Fruit of a treaty.",
  gibbon: "Fruit of a treaty.",
  kinkajou: "Nectar of a treaty.",
  colugo: "Leaf of a treaty.",
  flying_squirrel: "Nut of a treaty.",
  howler: "Leaf of a treaty.",
  tarsier: "Insect of a treaty.",
  potto: "Gum of a treaty.",
  koala: "Gum of a treaty.",
  brain_coral: "Plankton of a treaty.",
  anemone: "Drift of a treaty.",
  clownfish: "Scrap of a treaty.",
  parrotfish: "Algae of a treaty.",
  cleaner_shrimp: "Scrap of a treaty.",
  sea_cucumber: "Detritus of a treaty.",
  lionfish: "Prey of a treaty.",
  giant_clam: "Light of a treaty.",
  eagle_ray: "Clam of a treaty.",
  grouper: "Fish of a treaty.",
};

  const CALL_LINE = {
  red_panda: "You called. I brought the whole tail.",
  cat: "I returned. The sun moved.",
  dog: "You called. I was already coming.",
  rabbit: "I came out. Do not make it loud.",
  hamster: "I clocked back in.",
  guinea_pig: "Wheek. That means you.",
  turtle: "I have been here. That is the greeting.",
  goldfish: "Oh. You. I was just thinking that.",
  budgie: "Hello hello. I practiced that.",
  fox: "I found you first.",
  penguin: "You are recognized.",
  parrot: "Enter, keeper.",
  ferret: "You found me. I was working.",
  hedgehog: "I uncurled one quill.",
  chinchilla: "I inspected the desk. It may stay.",
  axolotl: "I was already looking at the door.",
  toucan: "I arrived. You noticed the bill.",
  iguana: "I have not moved. That is hello.",
  dragon: "You may approach the mantel.",
  phoenix: "I have been here before. So have you.",
  ball_python: "I was a ball. I am slightly less of one.",
  corn_snake: "I found a new route. It is your sleeve.",
  kingsnake: "I inspected the drawer. You may enter.",
  green_tree_python: "I am the jewelry. You may look.",
  hognose: "I died when you left. I got over it.",
  garter: "I was mid-patrol. You may join.",
  boa: "I saved you a length of blotter.",
  milk_snake: "I am not who I look like. Hello.",
  rosy_boa: "I kept the corner pink.",
  carpet_python: "I have charted the shelf. You may land.",
  octopus: "I tasted the rim. You may look.",
  cuttlefish: "I changed for you. Then I changed back.",
  nautilus: "I have been rising. You may wait.",
  moon_jelly: "I pulsed. That was hello.",
  sea_star: "I have not moved. That is hello.",
  hermit_crab: "I inspected the lid. You may keep the desk.",
  horseshoe_crab: "I am not a crab. Hello.",
  seahorse: "I hitched. You may look.",
  manta: "I saved you a length of sky.",
  moray: "I was already in the door. Hello.",
  moss: "I was already the page. Hello.",
  maidenhair: "I unfurled an inch. Hello.",
  ginkgo: "I have been gold before. Hello.",
  oak: "I saved you a height I could keep.",
  water_lily: "I opened. That was hello.",
  orchid: "I bloomed. You may look.",
  saguaro: "I have not moved. That is hello.",
  venus_flytrap: "I did not snap. That is hello.",
  pitcher: "I did not chase. The well was enough.",
  sundew: "I glittered. That was hello.",
  honeybee: "I danced. That was hello.",
  monarch: "I kept the orange. Hello.",
  luna: "I arrived without a mouth. Hello.",
  firefly: "I flashed. That was hello.",
  darner: "I hawed the lamp. Hello.",
  stick: "I have not moved. That is hello.",
  carpenter_ant: "I laid a road. Hello.",
  ladybird: "I counted. Hello.",
  mantis: "I did not strike. That is hello.",
  cicada: "I emerged. You may wait.",
  bumblebee: "I thrummed. That was hello.",
  carpenter_bee: "I bored. Hello.",
  mason_bee: "I sealed a cell. Hello.",
  leafcutter: "I cut a circle. Hello.",
  stingless: "I filled a pot. Hello.",
  sweat_bee: "I shone. Hello.",
  mining_bee: "I dug. Hello.",
  honey_drone: "I hummed. That was hello.",
  honey_queen: "I stayed. That was hello.",
  honeycomb: "I sat. That was hello.",
  oyster: "I fruited. That was hello.",
  fly_agaric: "I am a warning. Hello.",
  morel: "I am hollow. Hello.",
  chanterelle: "The ridges fork. Hello.",
  turkey_tail: "I zoned. Hello.",
  lions_mane: "I grew teeth. Hello.",
  puffball: "I puffed. That was hello.",
  chicken_of_woods: "I shelved. Hello.",
  yeast: "I rose. That was hello.",
  lichen: "We are two. Hello.",
  photovore: "I drank. That was hello.",
  choir: "I sounded. That was hello.",
  nimbus: "I floated. That was hello.",
  silica: "I faceted. Hello.",
  terminator: "I kept the rim. Hello.",
  nexus: "We counted. Hello.",
  halovore: "I frosted. Hello.",
  magneton: "I aligned. Hello.",
  umbral: "I dimmed. Hello.",
  cyst: "I waited. That was hello.",
  frog: "I jumped. That was hello.",
  toad: "I hopped. Hello.",
  newt: "I kept the orange. Hello.",
  salamander: "I waited under the leaf. Hello.",
  caecilian: "I am not a worm. Hello.",
  crayfish: "I pinched. That was hello.",
  pond_snail: "I rasped. Hello.",
  mussel: "I filtered. Hello.",
  leech: "I latched. Hello.",
  stickleback: "I flared. Hello.",
  paramecium: "I rowed. That was hello.",
  amoeba: "I reached. Hello.",
  euglena: "I kept the red. Hello.",
  volvox: "We rolled. Hello.",
  diatom: "I grew the pane. Hello.",
  kelp: "I held. Hello.",
  chlamydomonas: "I spun. Hello.",
  stentor: "I opened. Hello.",
  coli: "I tumbled. Hello.",
  haloarchaea: "I blushed. Hello.",
  crow: "I cawed. That was hello.",
  raven: "I croaked. Hello.",
  barn_owl: "I hissed. Hello.",
  red_tail: "I soared. Hello.",
  chickadee: "Dee-dee. Hello.",
  robin: "I hopped. Hello.",
  mallard: "I dabbled. Hello.",
  canada_goose: "I honked. Hello.",
  pileated: "I drummed. Hello.",
  hummingbird: "I hovered. Hello.",
  orb_weaver: "I sat the web. Hello.",
  jumping_spider: "I leapt. That was hello.",
  wolf_spider: "I prowled. Hello.",
  tarantula: "I sat the silk. Hello.",
  widow: "I hung. Hello.",
  harvestman: "I walked the stem. Hello.",
  scorpion: "I raised the tail. Hello.",
  vinegaroon: "I whipped. Hello.",
  tick: "I clasped. Hello.",
  solifuge: "I ran. Hello.",
  deer: "I flagged. That was hello.",
  bat: "I hung. Hello.",
  squirrel: "I hid a thought. Hello.",
  otter: "I slid. That was hello.",
  raccoon: "I washed. Hello.",
  skunk: "I stamped. Hello.",
  opossum: "I went still. Hello.",
  beaver: "I gnawed. Hello.",
  porcupine: "I bristled. Hello.",
  black_bear: "I foraged. Hello.",
  gecko: "I climbed. Hello.",
  anole: "I flashed. Hello.",
  skink: "I dashed. Hello.",
  chameleon: "I shifted. Hello.",
  horned_lizard: "I sat the crown. Hello.",
  alligator: "I sat the bank. Hello.",
  crocodile: "I showed. Hello.",
  snapper: "I snapped. Hello.",
  box_turtle: "I shut. Hello.",
  tuatara: "I kept still. Hello.",
  bass: "I lunged. Hello.",
  brook_trout: "I rose. Hello.",
  catfish: "I whisked. Hello.",
  bluegill: "I flared the flap. Hello.",
  perch: "I kept the bars. Hello.",
  pike: "I waited. Hello.",
  walleye: "I hunted dusk. Hello.",
  paddlefish: "I filtered. Hello.",
  lamprey: "I sat the disk. Hello.",
  american_eel: "I swam. Hello.",
  house_centipede: "I hunted. Hello.",
  millipede: "I oiled. Hello.",
  pillbug: "I rolled. Hello.",
  earthworm: "I cast. Hello.",
  velvet_worm: "I jetted. Hello.",
  springtail: "I hopped. Hello.",
  tardigrade: "I sat the moss. Hello.",
  planarian: "I split. Hello.",
  nematode: "I thrashed. Hello.",
  amphipod: "I swam on my side. Hello.",
  fiddler_crab: "I waved. Hello.",
  ghost_crab: "I ran. Hello.",
  limpet: "I clamped. Hello.",
  barnacle: "I sat the stone. Hello.",
  chiton: "I plated. Hello.",
  periwinkle: "I rasped. Hello.",
  sand_dollar: "I sat the sand. Hello.",
  sea_urchin: "I sat the spines. Hello.",
  knobbed_whelk: "I hunted. Hello.",
  lugworm: "I heaped. Hello.",
  field_cricket: "I sang. Hello.",
  katydid: "I sat the leaf. Hello.",
  grasshopper: "I vaulted. Hello.",
  swallowtail: "I kept the yellow. Hello.",
  jewelwing: "I kept the black. Hello.",
  lacewing: "I laced. Hello.",
  earwig: "I raised the cerci. Hello.",
  acorn_weevil: "I sat the acorn. Hello.",
  click_beetle: "I clicked. Hello.",
  robber_fly: "I hunted. Hello.",
  sloth: "I hung. Hello.",
  lemur: "I sat the sun. Hello.",
  gibbon: "I sang. Hello.",
  kinkajou: "I wrapped. Hello.",
  colugo: "I sailed. Hello.",
  flying_squirrel: "I glided. Hello.",
  howler: "I howled. Hello.",
  tarsier: "I looked. Hello.",
  potto: "I kept still. Hello.",
  koala: "I chewed. Hello.",
  brain_coral: "I sat the rock. Hello.",
  anemone: "I opened. Hello.",
  clownfish: "I sat the wreath. Hello.",
  parrotfish: "I rasped. Hello.",
  cleaner_shrimp: "I waited. Hello.",
  sea_cucumber: "I sat the sand. Hello.",
  lionfish: "I veiled. Hello.",
  giant_clam: "I opened. Hello.",
  eagle_ray: "I soared. Hello.",
  grouper: "I sat the hole. Hello.",
};

  const GIFT_LINE = {
  red_panda: "A ribbon I was not using. For the desk.",
  cat: "A moth. Consider it a review.",
  dog: "A sock. I found it first.",
  rabbit: "A clover. Four, if you squint.",
  hamster: "A seed from the official hoard.",
  guinea_pig: "Hay, arranged. Wheek optional.",
  turtle: "A stone I have been considering.",
  goldfish: "A bubble that lasted.",
  budgie: "A note. It says 'ok'.",
  fox: "The bug. Filed.",
  penguin: "A pebble of some standing.",
  parrot: "A word. Keep it.",
  ferret: "Your dongle. Improved.",
  hedgehog: "A leaf I trusted.",
  chinchilla: "Dust, but the good kind.",
  axolotl: "Calm, in object form.",
  toucan: "A berry. Inspected.",
  iguana: "Sun, compressed.",
  dragon: "A coin from the smaller hoard.",
  phoenix: "Ash that still glows.",
  ball_python: "A shed I was finished with.",
  corn_snake: "A pencil I was not using.",
  kingsnake: "A ruler. Straight, as required.",
  green_tree_python: "A loop of shed. Emerald still.",
  hognose: "A death scene, unused.",
  garter: "A moss sample. Official.",
  boa: "A weight I was not using.",
  milk_snake: "A stamp. Red, on purpose.",
  rosy_boa: "A warm pebble from the corner.",
  carpet_python: "A scrap of map. Accurate.",
  octopus: "A lid I was finished with.",
  cuttlefish: "A stripe I was not using.",
  nautilus: "A chamber of quiet.",
  moon_jelly: "A pulse that lasted.",
  sea_star: "A damp I trusted.",
  hermit_crab: "A lid that did not fit.",
  horseshoe_crab: "A page from the molt.",
  seahorse: "A hitch I was not using.",
  manta: "A barrel, unused.",
  moray: "A crevice I outgrew.",
  moss: "A square of green I was finished with.",
  maidenhair: "A fan I had already opened.",
  ginkgo: "A gold leaf I was not using.",
  oak: "An acorn I was finished considering.",
  water_lily: "A pad I was not using.",
  orchid: "A moth I was finished being.",
  saguaro: "A rain I stored twice.",
  venus_flytrap: "A snap I did not need.",
  pitcher: "A well I was finished holding.",
  sundew: "A drop I was finished glittering.",
  honeybee: "A dance I was not using.",
  monarch: "An orange I was finished wearing.",
  luna: "A dusk I was not eating.",
  firefly: "A flash I was finished saying.",
  darner: "A hawk I was not using.",
  stick: "A freeze I was finished holding.",
  carpenter_ant: "A road I was finished walking.",
  ladybird: "A count I was finished keeping.",
  mantis: "A fold I did not need.",
  cicada: "A year I was finished waiting.",
  bumblebee: "A thrum I was finished keeping.",
  carpenter_bee: "A hole I was finished boring.",
  mason_bee: "A cell I was finished sealing.",
  leafcutter: "A disc I was finished cutting.",
  stingless: "A pot I was finished filling.",
  sweat_bee: "A sheen I was finished wearing.",
  mining_bee: "A bank I was finished digging.",
  honey_drone: "A hum I was finished holding.",
  honey_queen: "A line I was finished writing.",
  honeycomb: "A cell I was finished holding.",
  oyster: "A shelf I was finished holding.",
  fly_agaric: "A warning I was not using.",
  morel: "A pit I was finished keeping.",
  chanterelle: "A ridge I was not using.",
  turkey_tail: "A zone I was finished wearing.",
  lions_mane: "A tooth I was finished hanging.",
  puffball: "A cloud I was finished saying.",
  chicken_of_woods: "A sulfur I was not using.",
  yeast: "A rise I was finished holding.",
  lichen: "A share I was finished keeping.",
  photovore: "A wavelength I was finished drinking.",
  choir: "A note I was not using.",
  nimbus: "A cold I was finished floating.",
  silica: "A facet I was finished shedding.",
  terminator: "A rim I was not using.",
  nexus: "A count I was finished keeping.",
  halovore: "A frost I was finished leaving.",
  magneton: "A north I was not using.",
  umbral: "A cool I was finished eating.",
  cyst: "A wait I was finished holding.",
  frog: "A hop I was finished keeping.",
  toad: "A puff I was not using.",
  newt: "An orange I was finished wearing.",
  salamander: "A coin I was finished hiding.",
  caecilian: "A ring I was not using.",
  crayfish: "A claw I was finished holding.",
  pond_snail: "A room I was finished growing.",
  mussel: "A silt I was finished filtering.",
  leech: "A latch I was finished keeping.",
  stickleback: "A spine I was not using.",
  paramecium: "A row I was finished keeping.",
  amoeba: "A foot I was not using.",
  euglena: "A red I was finished wearing.",
  volvox: "A daughter I was finished keeping.",
  diatom: "A pane I was finished growing.",
  kelp: "A bladder I was not using.",
  chlamydomonas: "An oar I was finished spinning.",
  stentor: "A horn I was finished opening.",
  coli: "A divide I was finished keeping.",
  haloarchaea: "A blush I was finished wearing.",
  crow: "A scrap I was finished hiding.",
  raven: "A thought I was finished keeping.",
  barn_owl: "A vole I was finished taking.",
  red_tail: "A vole I was finished stooping for.",
  chickadee: "A seed I was finished hiding.",
  robin: "A worm I was finished pulling.",
  mallard: "A seed I was finished tipping for.",
  canada_goose: "A grass I was finished keeping.",
  pileated: "An ant I was finished drumming for.",
  hummingbird: "A nectar I was finished sipping.",
  orb_weaver: "A fly I was finished wrapping.",
  jumping_spider: "A fly I was finished leaping for.",
  wolf_spider: "A cricket I was finished carrying past.",
  tarantula: "A cricket I was finished taking.",
  widow: "A fly I was finished hanging for.",
  harvestman: "A mite I was finished walking to.",
  scorpion: "A cricket I was finished raising for.",
  vinegaroon: "A cricket I was finished whipping for.",
  tick: "A sip I was finished waiting for.",
  solifuge: "A cricket I was finished running to.",
  deer: "A flag I was finished keeping.",
  bat: "A hang I was finished holding.",
  squirrel: "A thought I was finished hiding.",
  otter: "A slide I was finished keeping.",
  raccoon: "A rinse I was finished holding.",
  skunk: "A warning I was not using.",
  opossum: "A still I was finished keeping.",
  beaver: "A lodge I was finished holding.",
  porcupine: "A quill I was finished keeping.",
  black_bear: "A berry I was finished foraging.",
  gecko: "A moth I was finished climbing for.",
  anole: "A cricket I was finished flashing for.",
  skink: "A cricket I was finished dashing for.",
  chameleon: "A cricket I was finished aiming for.",
  horned_lizard: "An ant I was finished crowning for.",
  alligator: "A fish I was finished sitting for.",
  crocodile: "A fish I was finished showing for.",
  snapper: "A fish I was finished snapping for.",
  box_turtle: "A worm I was finished shutting after.",
  tuatara: "An insect I was finished keeping still for.",
  bass: "A minnow I was finished lunging for.",
  brook_trout: "A fly I was finished rising for.",
  catfish: "A scrap I was finished whisking for.",
  bluegill: "An insect I was finished flaring for.",
  perch: "A minnow I was finished barring for.",
  pike: "A fish I was finished waiting for.",
  walleye: "A minnow I was finished hunting dusk for.",
  paddlefish: "A plankton I was finished filtering.",
  lamprey: "A stone I was finished clinging to.",
  american_eel: "A scrap I was finished taking toward the Sargasso.",
  house_centipede: "A silverfish I was finished hunting.",
  millipede: "A leaf I was finished walking for.",
  pillbug: "A leaf I was finished rolling after.",
  earthworm: "A leaf I was finished casting from.",
  velvet_worm: "A cricket I was finished jetting for.",
  springtail: "A flake I was finished hopping for.",
  tardigrade: "A moss I was finished walking.",
  planarian: "A worm I was finished splitting after.",
  nematode: "A flake I was finished thrashing for.",
  amphipod: "A scrap I was finished taking on my side.",
  fiddler_crab: "An algae I was finished waving for.",
  ghost_crab: "A scrap I was finished running for.",
  limpet: "An algae I was finished clamping for.",
  barnacle: "A drift I was finished kicking for.",
  chiton: "An algae I was finished plating for.",
  periwinkle: "An algae I was finished rasping.",
  sand_dollar: "A diatom I was finished burying for.",
  sea_urchin: "A kelp I was finished walking for.",
  knobbed_whelk: "A clam I was finished hunting.",
  lugworm: "A silt I was finished heaping from.",
  field_cricket: "A seed I was finished singing for.",
  katydid: "A leaf I was finished stilling on.",
  grasshopper: "A leaf I was finished vaulting for.",
  swallowtail: "A nectar I was finished banding for.",
  jewelwing: "A midge I was finished hovering for.",
  lacewing: "An aphid I was finished lacing after.",
  earwig: "A scrap I was finished raising for.",
  acorn_weevil: "An acorn I was finished drilling.",
  click_beetle: "A scrap I was finished clicking for.",
  robber_fly: "A prey I was finished hunting.",
  sloth: "A leaf I was finished hanging for.",
  lemur: "A fruit I was finished sunning for.",
  gibbon: "A fruit I was finished swinging for.",
  kinkajou: "A nectar I was finished wrapping for.",
  colugo: "A leaf I was finished sailing for.",
  flying_squirrel: "A nut I was finished gliding for.",
  howler: "A leaf I was finished howling for.",
  tarsier: "An insect I was finished looking for.",
  potto: "A gum I was finished stilling for.",
  koala: "A gum I was finished chewing.",
  brain_coral: "A plankton I was finished ridging for.",
  anemone: "A drift I was finished wreathing for.",
  clownfish: "A scrap I was finished nestling for.",
  parrotfish: "An algae I was finished scraping.",
  cleaner_shrimp: "A scrap I was finished waiting for.",
  sea_cucumber: "A detritus I was finished crawling for.",
  lionfish: "A prey I was finished veiling for.",
  giant_clam: "A light I was finished opening for.",
  eagle_ray: "A clam I was finished soaring for.",
  grouper: "A fish I was finished hiding for.",
};

  /** Same night the desk already keeps. Overlay no longer invents a second clock. */
  const REST = {
  red_panda: [22, 7],
  cat: [13, 16],
  dog: [21, 6],
  rabbit: [22, 6],
  hamster: [8, 18],
  guinea_pig: [21, 6],
  turtle: [20, 7],
  goldfish: [23, 5],
  budgie: [19, 6],
  fox: [9, 17],
  penguin: [22, 6],
  parrot: [20, 6],
  ferret: [10, 17],
  hedgehog: [8, 18],
  chinchilla: [21, 7],
  axolotl: [22, 8],
  toucan: [19, 6],
  iguana: [20, 8],
  dragon: [1, 8],
  phoenix: [23, 6],
  ball_python: [8, 17],
  corn_snake: [9, 18],
  kingsnake: [21, 6],
  green_tree_python: [8, 17],
  hognose: [20, 7],
  garter: [21, 6],
  boa: [22, 7],
  milk_snake: [9, 18],
  rosy_boa: [21, 7],
  carpet_python: [8, 17],
  octopus: [8, 17],
  cuttlefish: [8, 17],
  nautilus: [8, 18],
  moon_jelly: [23, 5],
  sea_star: [21, 6],
  hermit_crab: [8, 18],
  horseshoe_crab: [8, 18],
  seahorse: [20, 6],
  manta: [21, 6],
  moray: [8, 17],
  moss: [20, 6],
  maidenhair: [20, 7],
  ginkgo: [19, 6],
  oak: [20, 6],
  water_lily: [20, 6],
  orchid: [19, 6],
  saguaro: [8, 17],
  venus_flytrap: [21, 6],
  pitcher: [21, 6],
  sundew: [20, 6],
  honeybee: [20, 6],
  monarch: [20, 6],
  luna: [8, 18],
  firefly: [8, 18],
  darner: [21, 6],
  stick: [21, 6],
  carpenter_ant: [8, 18],
  ladybird: [20, 6],
  mantis: [20, 6],
  cicada: [21, 6],
  bumblebee: [20, 6],
  carpenter_bee: [20, 6],
  mason_bee: [20, 6],
  leafcutter: [20, 6],
  stingless: [20, 6],
  sweat_bee: [20, 6],
  mining_bee: [20, 6],
  honey_drone: [20, 6],
  honey_queen: [21, 6],
  honeycomb: [21, 6],
  oyster: [20, 6],
  fly_agaric: [21, 6],
  morel: [20, 7],
  chanterelle: [20, 6],
  turkey_tail: [21, 6],
  lions_mane: [20, 6],
  puffball: [20, 6],
  chicken_of_woods: [21, 6],
  yeast: [23, 5],
  lichen: [20, 6],
  photovore: [20, 6],
  choir: [21, 6],
  nimbus: [23, 5],
  silica: [20, 7],
  terminator: [10, 17],
  nexus: [21, 6],
  halovore: [20, 6],
  magneton: [22, 6],
  umbral: [8, 18],
  cyst: [20, 8],
  frog: [22, 6],
  toad: [21, 7],
  newt: [22, 7],
  salamander: [8, 18],
  caecilian: [21, 7],
  crayfish: [22, 6],
  pond_snail: [23, 6],
  mussel: [22, 7],
  leech: [9, 17],
  stickleback: [21, 6],
  paramecium: [22, 6],
  amoeba: [21, 7],
  euglena: [20, 6],
  volvox: [20, 6],
  diatom: [20, 6],
  kelp: [20, 6],
  chlamydomonas: [20, 6],
  stentor: [22, 6],
  coli: [23, 5],
  haloarchaea: [20, 6],
  crow: [19, 6],
  raven: [19, 6],
  barn_owl: [8, 18],
  red_tail: [19, 6],
  chickadee: [19, 6],
  robin: [20, 6],
  mallard: [21, 6],
  canada_goose: [21, 6],
  pileated: [19, 6],
  hummingbird: [19, 6],
  orb_weaver: [20, 6],
  jumping_spider: [19, 6],
  wolf_spider: [8, 18],
  tarantula: [8, 18],
  widow: [8, 18],
  harvestman: [8, 18],
  scorpion: [8, 18],
  vinegaroon: [8, 18],
  tick: [22, 6],
  solifuge: [8, 18],
  deer: [10, 16],
  bat: [8, 18],
  squirrel: [19, 6],
  otter: [22, 6],
  raccoon: [8, 17],
  skunk: [8, 18],
  opossum: [8, 18],
  beaver: [8, 17],
  porcupine: [8, 18],
  black_bear: [22, 7],
  gecko: [7, 19],
  anole: [20, 6],
  skink: [20, 6],
  chameleon: [20, 6],
  horned_lizard: [20, 6],
  alligator: [22, 6],
  crocodile: [22, 6],
  snapper: [8, 17],
  box_turtle: [20, 6],
  tuatara: [8, 18],
  bass: [21, 6],
  brook_trout: [20, 6],
  catfish: [8, 17],
  bluegill: [20, 6],
  perch: [20, 6],
  pike: [21, 6],
  walleye: [8, 17],
  paddlefish: [21, 6],
  lamprey: [8, 18],
  american_eel: [8, 17],
  house_centipede: [8, 18],
  millipede: [8, 18],
  pillbug: [8, 18],
  earthworm: [8, 17],
  velvet_worm: [8, 18],
  springtail: [22, 6],
  tardigrade: [22, 7],
  planarian: [8, 18],
  nematode: [22, 7],
  amphipod: [8, 18],
  fiddler_crab: [8, 18],
  ghost_crab: [8, 17],
  limpet: [22, 7],
  barnacle: [22, 7],
  chiton: [8, 18],
  periwinkle: [22, 7],
  sand_dollar: [8, 18],
  sea_urchin: [8, 18],
  knobbed_whelk: [8, 18],
  lugworm: [8, 17],
  field_cricket: [8, 17],
  katydid: [8, 17],
  grasshopper: [22, 7],
  swallowtail: [22, 7],
  jewelwing: [22, 7],
  lacewing: [8, 17],
  earwig: [8, 17],
  acorn_weevil: [22, 7],
  click_beetle: [8, 17],
  robber_fly: [22, 7],
  sloth: [6, 16],
  lemur: [20, 6],
  gibbon: [19, 6],
  kinkajou: [8, 18],
  colugo: [8, 18],
  flying_squirrel: [8, 18],
  howler: [20, 6],
  tarsier: [8, 18],
  potto: [8, 18],
  koala: [8, 17],
  brain_coral: [22, 6],
  anemone: [22, 6],
  clownfish: [20, 6],
  parrotfish: [20, 6],
  cleaner_shrimp: [20, 6],
  sea_cucumber: [8, 18],
  lionfish: [8, 18],
  giant_clam: [22, 6],
  eagle_ray: [20, 6],
  grouper: [20, 6],
};

  function restWindow(key) {
    return REST[key] || [22, 7];
  }

  function isRestingHour(key, hour) {
    const h = hour == null ? new Date().getHours() : hour;
    const [start, end] = restWindow(key);
    if (start === end) return false;
    if (start < end) return h >= start && h < end;
    return h >= start || h < end;
  }

  function snackLine(key, existing) {
    if (existing) return existing;
    return SNACK_LINE[key] || "A small treaty.";
  }

  function callLine(key, existing) {
    if (existing) return existing;
    return CALL_LINE[key] || "You called.";
  }

  function giftLine(key, existing) {
    if (existing) return existing;
    return GIFT_LINE[key] || "I left this.";
  }

  const api = { SNACK_LINE, CALL_LINE, GIFT_LINE, snackLine, callLine, giftLine, REST, restWindow, isRestingHour };
  if (typeof module !== "undefined" && module.exports) module.exports = api;
  root.PetHours = api;
})(typeof window !== "undefined" ? window : globalThis);
