const assert = require("node:assert/strict");
const { existsSync, readFileSync } = require("node:fs");
const { join } = require("node:path");
const { test } = require("node:test");

const htmlSrc = readFileSync(join(__dirname, "index.html"), "utf8");
const petSrc = readFileSync(join(__dirname, "pet.js"), "utf8");
const styleSrc = readFileSync(join(__dirname, "styles.css"), "utf8");
const D = require("./desk.js");
const F = require("./bird-fly.js");
const S = require("./house-sounds.js");
const M = require("./house-music.js");
const Sleep = require("./house-sleep.js");
const R = require("./ribbon.js");
const T = require("./rui-tricks.js");
const C = require("./card.js");
const WP = require("./window-play.js");

test("Still leftover creeps a sash parting bead as a vine rail; next leftover is Gum; Gaze leftover still looks from a sash pulley box as a branch hollow; Boom leftover still howls a high transom as a crown perch; Glide leftover still planes a window stool as an oak fold; Sail leftover still clings a window jamb as a trunk sail; Wrist leftover still wraps a window-box bloom as a nectar cup; Swing leftover still sings a lamp-side stile as a lamp arm; Sun leftover still warms an upper sash light as a sun ledge; Hang leftover still reaches a transom soffit as a bough hook; Coal leftover still browses a window well as an oak denside; Spine leftover still bristles a window jamb as a pine post; Dam leftover still gnaws a sash stile as a lodge cup; Grin leftover still goes still on a transom soffit as a rafter hem; Stripe leftover still stamps a window foot as a duff dish; Wash leftover still rinses a sill pan as a wash bowl; Slick leftover still slides a window pane as an ink dish; Cache leftover still buries a window stool as an oak dish; Cape leftover still folds a transom soffit as a rafter fold; Gale leftover still runs a sash light as a dry dish; Clasp leftover still grips a sash apron hem as a blotter hem; Whip leftover still sprays a sill wash as a sand tray; Barb leftover still raises a window stool as a bark tray; Stem leftover still stilts a sash parting bead as a blotter stem; Hour leftover still hangs a bottom-inside jamb corner as a dark corner; Velvet leftover still kicks a sash well as a silk burrow; Prowl leftover still carries a window foot as leaf litter; Leap leftover still pounces a meeting-rail end as a blotter edge; Loom leftover still webs a lamp-side glass corner as a lamp web; Sip leftover still sips a window-box bloom as a nectar cup; Drum leftover still drums an upper sash stile as a dead-wood post; Vee leftover still honks a window apron as a blotter green; Drake leftover still tips a lower sash light as an ink dish; Brick leftover still pulls a window stool as a lawn; Dee leftover still caches a meeting-rail nosing as a twig cup; Hook leftover still soars a lamp-post stile as lift; Heart leftover still hisses a sash reveal as a beam hollow; Wedge leftover still croaks a high transom as a rafter; Soot leftover still caws a drip cap as a chimney pot; Prickle leftover still glues a putty fillet as a weed bowl; Latch leftover still drinks a sash drip as a damp blotter; Hinge leftover still filters a meeting-rail gap as a silt bed; Whorl leftover still rasps a glass rim as her own house; Pinch leftover still claws a sill wash as a pebble tray; Slip leftover still rings a sill throat as a silt tray; Dapple leftover still covers a window well as leaf mold; Eft leftover still trails a sash horn as a moss saucer; Pebble leftover still puffs a casement leaf as a leaf dish; Reed leftover still plops a window weep as a bank spring; Wax leftover still draws a window pane as a hive frame; Keep leftover still lays a window pane as a wax heart; Hum leftover still drones a window pane as congregation sky; Bank leftover still digs a window stool as a sand bank; Sheen leftover still licks a warm pane as a salt glass; Pot leftover still tends a sash pulley box as a cerumen hollow; Disc leftover still snips a window-box leaf as foliage; Mortar leftover still daubs a sash gap as an inkstone cell; Auger leftover still bores a sash stile as timber; Thrum leftover still forages a window box as a meadow; Dew leftover still curls a window glazing rebate as a peat saucer; Well leftover still fills a window sill pan as a bog cup; Snap leftover still counts a window meeting rail as a wetland cup; Arm leftover still stores a window stool as a sand tray; Moth leftover still mounts a window jamb as bark; Disk leftover still opens a window pane as an ink-dish pad; Mast leftover still seeds a window stool as an acorn dish; Fan leftover still golds a window lamp-side as autumn; Vein leftover still unfurls a window sash pocket as a damp saucer; Felt leftover still leans a window meeting rail as blotter felt; Door leftover still gapes a window sash-jamb crack as a book crevice; Kite leftover still barrels a window pane as the sky of a bowl; Anchor leftover still hitches a window parting bead as a pencil; Ledger leftover still plows a window stool as a sand tray; Tenant leftover still knobs a window sash lift as a vacant shell; Ochre leftover still reefs a window pane as a damp blotter; Pulse leftover still chimes a window pane as a glass of water; Chamber leftover still rises a window jamb as stacked nacre rooms; Sepia leftover still flushes a window light; Cup leftover still lids a sash latch; Atlas leftover still charts a transom; Blush leftover still stones a sill horn; Coral still mosaics; Lula still loops; Sash still patrols; Bluff still flips; Jade still saddles; Bandit still inspects; Saffron still writes; Nori still buns; Ember still kindles; Vesper still drapes; Sol still flattens; Keel still tosses; Bloom still walls; Floss still dusts; Burr still balls; Wick still threads; Quill still hooks; Peck still bows; Rue still scents; Echo still perches; Coin still circles; Ink still basks; Whee still wheeks; Clip still stashes; Thimble still thumps; Pip still watches; Miso still sits a ledge", () => {
  assert.equal(WP.playFor("frog"), "plop");
  assert.notEqual(WP.playFor("frog"), "reed");
  assert.notEqual(WP.playFor("frog"), "hop");
  assert.notEqual(WP.playFor("frog"), "jump");
  assert.notEqual(WP.playFor("frog"), "bask");
  assert.notEqual(WP.playFor("frog"), "wall");
  assert.notEqual(WP.playFor("frog"), "circle");
  assert.notEqual(WP.playFor("frog"), "draw");
  assert.notEqual(WP.playFor("frog"), "fill");
  assert.notEqual(WP.playFor("frog"), "sill");
  assert.equal(WP.playFor("toad"), "puff");
  assert.notEqual(WP.playFor("toad"), "pebble");
  assert.notEqual(WP.playFor("toad"), "hop");
  assert.notEqual(WP.playFor("toad"), "plop");
  assert.notEqual(WP.playFor("toad"), "bask");
  assert.notEqual(WP.playFor("toad"), "wall");
  assert.notEqual(WP.playFor("toad"), "stone");
  assert.notEqual(WP.playFor("toad"), "ball");
  assert.notEqual(WP.playFor("toad"), "circle");
  assert.notEqual(WP.playFor("toad"), "sill");
  assert.equal(WP.playFor("newt"), "trail");
  assert.notEqual(WP.playFor("newt"), "eft");
  assert.notEqual(WP.playFor("newt"), "walk");
  assert.notEqual(WP.playFor("newt"), "puff");
  assert.notEqual(WP.playFor("newt"), "plop");
  assert.notEqual(WP.playFor("newt"), "bask");
  assert.notEqual(WP.playFor("newt"), "wall");
  assert.notEqual(WP.playFor("newt"), "flatten");
  assert.notEqual(WP.playFor("newt"), "unfurl");
  assert.notEqual(WP.playFor("newt"), "circle");
  assert.notEqual(WP.playFor("newt"), "sill");
  assert.equal(WP.playFor("salamander"), "cover");
  assert.notEqual(WP.playFor("salamander"), "dapple");
  assert.notEqual(WP.playFor("salamander"), "hide");
  assert.notEqual(WP.playFor("salamander"), "trail");
  assert.notEqual(WP.playFor("salamander"), "puff");
  assert.notEqual(WP.playFor("salamander"), "plop");
  assert.notEqual(WP.playFor("salamander"), "bask");
  assert.notEqual(WP.playFor("salamander"), "wall");
  assert.notEqual(WP.playFor("salamander"), "flatten");
  assert.notEqual(WP.playFor("salamander"), "unfurl");
  assert.notEqual(WP.playFor("salamander"), "path");
  assert.notEqual(WP.playFor("salamander"), "bun");
  assert.notEqual(WP.playFor("salamander"), "circle");
  assert.notEqual(WP.playFor("salamander"), "sill");
  assert.equal(WP.playFor("caecilian"), "ring");
  assert.notEqual(WP.playFor("caecilian"), "slip");
  assert.notEqual(WP.playFor("caecilian"), "sill");
  assert.notEqual(WP.playFor("caecilian"), "cover");
  assert.notEqual(WP.playFor("caecilian"), "trail");
  assert.notEqual(WP.playFor("caecilian"), "puff");
  assert.notEqual(WP.playFor("caecilian"), "plop");
  assert.notEqual(WP.playFor("caecilian"), "thread");
  assert.notEqual(WP.playFor("caecilian"), "loop");
  assert.notEqual(WP.playFor("caecilian"), "gape");
  assert.notEqual(WP.playFor("caecilian"), "bun");
  assert.notEqual(WP.playFor("caecilian"), "write");
  assert.notEqual(WP.playFor("caecilian"), "chime");
  assert.equal(WP.playFor("crayfish"), "claw");
  assert.notEqual(WP.playFor("crayfish"), "pinch");
  assert.notEqual(WP.playFor("crayfish"), "sill");
  assert.notEqual(WP.playFor("crayfish"), "ring");
  assert.notEqual(WP.playFor("crayfish"), "cover");
  assert.notEqual(WP.playFor("crayfish"), "trail");
  assert.notEqual(WP.playFor("crayfish"), "puff");
  assert.notEqual(WP.playFor("crayfish"), "plop");
  assert.notEqual(WP.playFor("crayfish"), "stash");
  assert.notEqual(WP.playFor("crayfish"), "lid");
  assert.notEqual(WP.playFor("crayfish"), "knob");
  assert.notEqual(WP.playFor("crayfish"), "dig");
  assert.notEqual(WP.playFor("crayfish"), "plow");
  assert.equal(WP.playFor("pond_snail"), "rasp");
  assert.notEqual(WP.playFor("pond_snail"), "whorl");
  assert.notEqual(WP.playFor("pond_snail"), "sill");
  assert.notEqual(WP.playFor("pond_snail"), "claw");
  assert.notEqual(WP.playFor("pond_snail"), "ring");
  assert.notEqual(WP.playFor("pond_snail"), "cover");
  assert.notEqual(WP.playFor("pond_snail"), "trail");
  assert.notEqual(WP.playFor("pond_snail"), "puff");
  assert.notEqual(WP.playFor("pond_snail"), "plop");
  assert.notEqual(WP.playFor("pond_snail"), "knob");
  assert.notEqual(WP.playFor("pond_snail"), "lid");
  assert.notEqual(WP.playFor("pond_snail"), "circle");
  assert.notEqual(WP.playFor("pond_snail"), "rise");
  assert.notEqual(WP.playFor("pond_snail"), "lick");
  assert.equal(WP.playFor("mussel"), "filter");
  assert.notEqual(WP.playFor("mussel"), "hinge");
  assert.notEqual(WP.playFor("mussel"), "sill");
  assert.notEqual(WP.playFor("mussel"), "rasp");
  assert.notEqual(WP.playFor("mussel"), "claw");
  assert.notEqual(WP.playFor("mussel"), "ring");
  assert.notEqual(WP.playFor("mussel"), "cover");
  assert.notEqual(WP.playFor("mussel"), "trail");
  assert.notEqual(WP.playFor("mussel"), "puff");
  assert.notEqual(WP.playFor("mussel"), "plop");
  assert.notEqual(WP.playFor("mussel"), "knob");
  assert.notEqual(WP.playFor("mussel"), "lid");
  assert.notEqual(WP.playFor("mussel"), "gape");
  assert.notEqual(WP.playFor("mussel"), "circle");
  assert.notEqual(WP.playFor("mussel"), "open");
  assert.notEqual(WP.playFor("mussel"), "chime");
  assert.notEqual(WP.playFor("mussel"), "dig");
  assert.notEqual(WP.playFor("mussel"), "plow");
  assert.equal(WP.playFor("stickleback"), "glue");
  assert.notEqual(WP.playFor("stickleback"), "prickle");
  assert.notEqual(WP.playFor("stickleback"), "sill");
  assert.notEqual(WP.playFor("stickleback"), "drink");
  assert.notEqual(WP.playFor("stickleback"), "filter");
  assert.notEqual(WP.playFor("stickleback"), "rasp");
  assert.notEqual(WP.playFor("stickleback"), "claw");
  assert.notEqual(WP.playFor("stickleback"), "ring");
  assert.notEqual(WP.playFor("stickleback"), "cover");
  assert.notEqual(WP.playFor("stickleback"), "trail");
  assert.notEqual(WP.playFor("stickleback"), "puff");
  assert.notEqual(WP.playFor("stickleback"), "plop");
  assert.notEqual(WP.playFor("stickleback"), "circle");
  assert.notEqual(WP.playFor("stickleback"), "barrel");
  assert.notEqual(WP.playFor("stickleback"), "chime");
  assert.notEqual(WP.playFor("stickleback"), "open");
  assert.notEqual(WP.playFor("stickleback"), "lid");
  assert.notEqual(WP.playFor("stickleback"), "knob");
  assert.notEqual(WP.playFor("stickleback"), "gape");
  assert.notEqual(WP.playFor("stickleback"), "flare");
  assert.equal(WP.playFor("leech"), "drink");
  assert.notEqual(WP.playFor("leech"), "latch");
  assert.notEqual(WP.playFor("leech"), "sill");
  assert.notEqual(WP.playFor("leech"), "filter");
  assert.notEqual(WP.playFor("leech"), "rasp");
  assert.notEqual(WP.playFor("leech"), "claw");
  assert.notEqual(WP.playFor("leech"), "ring");
  assert.notEqual(WP.playFor("leech"), "cover");
  assert.notEqual(WP.playFor("leech"), "trail");
  assert.notEqual(WP.playFor("leech"), "puff");
  assert.notEqual(WP.playFor("leech"), "plop");
  assert.notEqual(WP.playFor("leech"), "lid");
  assert.notEqual(WP.playFor("leech"), "knob");
  assert.notEqual(WP.playFor("leech"), "gape");
  assert.notEqual(WP.playFor("leech"), "hold");
  assert.notEqual(WP.playFor("leech"), "hitch");
  assert.notEqual(WP.playFor("leech"), "thread");
  assert.notEqual(WP.playFor("leech"), "loop");
  assert.notEqual(WP.playFor("leech"), "sip");
  assert.equal(WP.playFor("honeycomb"), "draw");
  assert.equal(WP.playFor("bumblebee"), "forage");
  assert.notEqual(WP.playFor("bumblebee"), "thrum");
  assert.notEqual(WP.playFor("bumblebee"), "curl");
  assert.notEqual(WP.playFor("bumblebee"), "fill");
  assert.notEqual(WP.playFor("bumblebee"), "sill");
  assert.equal(WP.playFor("carpenter_bee"), "bore");
  assert.notEqual(WP.playFor("carpenter_bee"), "auger");
  assert.notEqual(WP.playFor("carpenter_bee"), "forage");
  assert.notEqual(WP.playFor("carpenter_bee"), "sill");
  assert.equal(WP.playFor("mason_bee"), "daub");
  assert.notEqual(WP.playFor("mason_bee"), "mortar");
  assert.notEqual(WP.playFor("mason_bee"), "bore");
  assert.notEqual(WP.playFor("mason_bee"), "forage");
  assert.notEqual(WP.playFor("mason_bee"), "sill");
  assert.equal(WP.playFor("leafcutter"), "snip");
  assert.notEqual(WP.playFor("leafcutter"), "disc");
  assert.notEqual(WP.playFor("leafcutter"), "disk");
  assert.notEqual(WP.playFor("leafcutter"), "daub");
  assert.notEqual(WP.playFor("leafcutter"), "bore");
  assert.notEqual(WP.playFor("leafcutter"), "forage");
  assert.notEqual(WP.playFor("leafcutter"), "circle");
  assert.notEqual(WP.playFor("leafcutter"), "sill");
  assert.equal(WP.playFor("honeybee"), "sill");
  assert.equal(WP.playFor("stingless"), "tend");
  assert.notEqual(WP.playFor("stingless"), "pot");
  assert.notEqual(WP.playFor("stingless"), "snip");
  assert.notEqual(WP.playFor("stingless"), "daub");
  assert.notEqual(WP.playFor("stingless"), "bore");
  assert.notEqual(WP.playFor("stingless"), "forage");
  assert.notEqual(WP.playFor("stingless"), "sill");
  assert.equal(WP.playFor("sweat_bee"), "lick");
  assert.notEqual(WP.playFor("sweat_bee"), "sheen");
  assert.notEqual(WP.playFor("sweat_bee"), "shine");
  assert.notEqual(WP.playFor("sweat_bee"), "sip");
  assert.notEqual(WP.playFor("sweat_bee"), "tend");
  assert.notEqual(WP.playFor("sweat_bee"), "snip");
  assert.notEqual(WP.playFor("sweat_bee"), "daub");
  assert.notEqual(WP.playFor("sweat_bee"), "bore");
  assert.notEqual(WP.playFor("sweat_bee"), "forage");
  assert.notEqual(WP.playFor("sweat_bee"), "sill");
  assert.equal(WP.playFor("mining_bee"), "dig");
  assert.notEqual(WP.playFor("mining_bee"), "bank");
  assert.notEqual(WP.playFor("mining_bee"), "lick");
  assert.notEqual(WP.playFor("mining_bee"), "tend");
  assert.notEqual(WP.playFor("mining_bee"), "snip");
  assert.notEqual(WP.playFor("mining_bee"), "daub");
  assert.notEqual(WP.playFor("mining_bee"), "bore");
  assert.notEqual(WP.playFor("mining_bee"), "forage");
  assert.notEqual(WP.playFor("mining_bee"), "plow");
  assert.notEqual(WP.playFor("mining_bee"), "store");
  assert.notEqual(WP.playFor("mining_bee"), "sill");
  assert.equal(WP.playFor("honey_drone"), "drone");
  assert.notEqual(WP.playFor("honey_drone"), "hum");
  assert.notEqual(WP.playFor("honey_drone"), "dig");
  assert.notEqual(WP.playFor("honey_drone"), "lick");
  assert.notEqual(WP.playFor("honey_drone"), "tend");
  assert.notEqual(WP.playFor("honey_drone"), "snip");
  assert.notEqual(WP.playFor("honey_drone"), "daub");
  assert.notEqual(WP.playFor("honey_drone"), "bore");
  assert.notEqual(WP.playFor("honey_drone"), "forage");
  assert.notEqual(WP.playFor("honey_drone"), "chime");
  assert.notEqual(WP.playFor("honey_drone"), "sill");
  assert.equal(WP.playFor("honey_queen"), "lay");
  assert.notEqual(WP.playFor("honey_queen"), "keep");
  assert.notEqual(WP.playFor("honey_queen"), "drone");
  assert.notEqual(WP.playFor("honey_queen"), "dig");
  assert.notEqual(WP.playFor("honey_queen"), "lick");
  assert.notEqual(WP.playFor("honey_queen"), "tend");
  assert.notEqual(WP.playFor("honey_queen"), "snip");
  assert.notEqual(WP.playFor("honey_queen"), "daub");
  assert.notEqual(WP.playFor("honey_queen"), "bore");
  assert.notEqual(WP.playFor("honey_queen"), "forage");
  assert.notEqual(WP.playFor("honey_queen"), "chart");
  assert.notEqual(WP.playFor("honey_queen"), "sill");
  assert.equal(WP.playFor("honeybee"), "sill");
  assert.equal(WP.playFor("honeycomb"), "draw");
  assert.notEqual(WP.playFor("honeycomb"), "wax");
  assert.notEqual(WP.playFor("honeycomb"), "comb");
  assert.notEqual(WP.playFor("honeycomb"), "lay");
  assert.notEqual(WP.playFor("honeycomb"), "drone");
  assert.notEqual(WP.playFor("honeycomb"), "dig");
  assert.notEqual(WP.playFor("honeycomb"), "lick");
  assert.notEqual(WP.playFor("honeycomb"), "tend");
  assert.notEqual(WP.playFor("honeycomb"), "snip");
  assert.notEqual(WP.playFor("honeycomb"), "daub");
  assert.notEqual(WP.playFor("honeycomb"), "bore");
  assert.notEqual(WP.playFor("honeycomb"), "forage");
  assert.notEqual(WP.playFor("honeycomb"), "mosaic");
  assert.notEqual(WP.playFor("honeycomb"), "field");
  assert.notEqual(WP.playFor("honeycomb"), "sill");
  assert.equal(WP.playFor("sundew"), "curl");
  assert.notEqual(WP.playFor("sundew"), "dew");
  assert.notEqual(WP.playFor("sundew"), "fill");
  assert.notEqual(WP.playFor("sundew"), "count");
  assert.notEqual(WP.playFor("sundew"), "sill");
  assert.notEqual(WP.playFor("sundew"), "forage");
  assert.equal(WP.playFor("pitcher"), "fill");
  assert.notEqual(WP.playFor("pitcher"), "well");
  assert.notEqual(WP.playFor("pitcher"), "dew");
  assert.notEqual(WP.playFor("pitcher"), "count");
  assert.notEqual(WP.playFor("pitcher"), "sill");
  assert.equal(WP.playFor("venus_flytrap"), "count");
  assert.notEqual(WP.playFor("venus_flytrap"), "snap");
  assert.notEqual(WP.playFor("venus_flytrap"), "well");
  assert.notEqual(WP.playFor("venus_flytrap"), "dew");
  assert.notEqual(WP.playFor("venus_flytrap"), "sill");
  assert.equal(WP.playFor("saguaro"), "store");
  assert.notEqual(WP.playFor("saguaro"), "arm");
  assert.notEqual(WP.playFor("saguaro"), "snap");
  assert.notEqual(WP.playFor("saguaro"), "well");
  assert.equal(WP.playFor("orchid"), "mount");
  assert.equal(WP.playFor("water_lily"), "open");
  assert.equal(WP.playFor("oak"), "seed");
  assert.equal(WP.playFor("ginkgo"), "gold");
  assert.equal(WP.playFor("maidenhair"), "unfurl");
  assert.equal(WP.playFor("moss"), "lean");
  assert.equal(WP.playFor("moray"), "gape");
  assert.equal(WP.playFor("manta"), "barrel");
  assert.equal(WP.playFor("seahorse"), "hitch");
  assert.equal(WP.playFor("horseshoe_crab"), "plow");
  assert.equal(WP.playFor("hermit_crab"), "knob");
  assert.equal(WP.playFor("sea_star"), "reef");
  assert.equal(WP.playFor("moon_jelly"), "chime");
  assert.equal(WP.playFor("nautilus"), "rise");
  assert.equal(WP.playFor("cuttlefish"), "flush");
  assert.equal(WP.playFor("octopus"), "lid");
  assert.equal(WP.playFor("rosy_boa"), "stone");
  assert.equal(WP.playFor("milk_snake"), "mosaic");
  assert.equal(WP.playFor("boa"), "loop");
  assert.equal(WP.playFor("garter"), "patrol");
  assert.equal(WP.playFor("carpet_python"), "chart");
  assert.equal(WP.playFor("hognose"), "flip");
  assert.equal(WP.playFor("green_tree_python"), "saddle");
  assert.equal(WP.playFor("kingsnake"), "inspect");
  assert.equal(WP.playFor("corn_snake"), "write");
  assert.equal(WP.playFor("ball_python"), "bun");
  assert.equal(WP.playFor("phoenix"), "kindle");
  assert.equal(WP.playFor("dragon"), "drape");
  assert.equal(WP.playFor("iguana"), "flatten");
  assert.equal(WP.playFor("toucan"), "toss");
  assert.equal(WP.playFor("axolotl"), "wall");
  assert.equal(WP.playFor("chinchilla"), "dust");
  assert.equal(WP.playFor("hedgehog"), "ball");
  assert.equal(WP.playFor("ferret"), "thread");
  assert.equal(WP.playFor("parrot"), "hook");
  assert.equal(WP.playFor("penguin"), "bow");
  assert.equal(WP.playFor("fox"), "scent");
  assert.equal(WP.playFor("budgie"), "perch");
  assert.equal(WP.playFor("goldfish"), "circle");
  assert.equal(WP.playFor("turtle"), "bask");
  assert.equal(WP.playFor("guinea_pig"), "wheek");
  assert.equal(WP.playFor("hamster"), "stash");
  assert.equal(WP.playFor("rabbit"), "thump");
  assert.equal(WP.playFor("dog"), "watch");
  assert.equal(WP.playFor("cat"), "ledge");
  assert.equal(WP.playFor("ground_dragon"), "earth");
  assert.equal(WP.playFor("fuse_dragon"), "hold");
  assert.equal(WP.playFor("relay_dragon"), "click");
  assert.equal(WP.playFor("gauss_dragon"), "orbit");
  assert.equal(WP.playFor("ion_dragon"), "charge");
  assert.equal(WP.playFor("flux_dragon"), "field");
  assert.equal(WP.playFor("red_panda"), "cling-dive");
  assert.equal(WP.playFor("cyber_dragon"), "ridge");
  assert.equal(WP.playFor("gecko"), "sill");
  assert.equal(WP.playFor("crow"), "caw");
  assert.notEqual(WP.playFor("crow"), "soot");
  assert.notEqual(WP.playFor("crow"), "sill");
  assert.notEqual(WP.playFor("crow"), "glue");
  assert.notEqual(WP.playFor("crow"), "drink");
  assert.notEqual(WP.playFor("crow"), "perch");
  assert.notEqual(WP.playFor("crow"), "hook");
  assert.notEqual(WP.playFor("crow"), "ledge");
  assert.notEqual(WP.playFor("crow"), "toss");
  assert.notEqual(WP.playFor("crow"), "bow");
  assert.notEqual(WP.playFor("crow"), "circle");
  assert.notEqual(WP.playFor("crow"), "stash");
  assert.notEqual(WP.playFor("crow"), "cache");
  assert.notEqual(WP.playFor("crow"), "croak");
  assert.notEqual(WP.playFor("crow"), "fan");
  assert.notEqual(WP.playFor("crow"), "ridge");
  assert.equal(WP.playFor("raven"), "croak");
  assert.notEqual(WP.playFor("raven"), "wedge");
  assert.notEqual(WP.playFor("raven"), "caw");
  assert.notEqual(WP.playFor("raven"), "sill");
  assert.notEqual(WP.playFor("raven"), "glue");
  assert.notEqual(WP.playFor("raven"), "drink");
  assert.notEqual(WP.playFor("raven"), "filter");
  assert.notEqual(WP.playFor("raven"), "rasp");
  assert.notEqual(WP.playFor("raven"), "claw");
  assert.notEqual(WP.playFor("raven"), "perch");
  assert.notEqual(WP.playFor("raven"), "bow");
  assert.notEqual(WP.playFor("raven"), "hook");
  assert.notEqual(WP.playFor("raven"), "toss");
  assert.notEqual(WP.playFor("raven"), "ledge");
  assert.notEqual(WP.playFor("raven"), "chart");
  assert.notEqual(WP.playFor("raven"), "lid");
  assert.notEqual(WP.playFor("raven"), "knob");
  assert.notEqual(WP.playFor("raven"), "circle");
  assert.notEqual(WP.playFor("raven"), "draw");
  assert.notEqual(WP.playFor("raven"), "kindle");
  assert.notEqual(WP.playFor("raven"), "ridge");
  assert.notEqual(WP.playFor("raven"), "hiss");
  assert.notEqual(WP.playFor("raven"), "dee");
  assert.notEqual(WP.playFor("raven"), "sip");
  assert.notEqual(WP.playFor("raven"), "drum");
  assert.notEqual(WP.playFor("raven"), "vee");
  assert.equal(WP.playFor("barn_owl"), "hiss");
  assert.notEqual(WP.playFor("barn_owl"), "heart");
  assert.notEqual(WP.playFor("barn_owl"), "sill");
  assert.notEqual(WP.playFor("barn_owl"), "croak");
  assert.notEqual(WP.playFor("barn_owl"), "caw");
  assert.notEqual(WP.playFor("barn_owl"), "perch");
  assert.notEqual(WP.playFor("barn_owl"), "bow");
  assert.notEqual(WP.playFor("barn_owl"), "hook");
  assert.notEqual(WP.playFor("barn_owl"), "toss");
  assert.notEqual(WP.playFor("barn_owl"), "ledge");
  assert.notEqual(WP.playFor("barn_owl"), "drape");
  assert.notEqual(WP.playFor("barn_owl"), "chart");
  assert.notEqual(WP.playFor("barn_owl"), "unfurl");
  assert.notEqual(WP.playFor("barn_owl"), "hoot");
  assert.notEqual(WP.playFor("barn_owl"), "soar");
  assert.notEqual(WP.playFor("barn_owl"), "stoop");
  assert.notEqual(WP.playFor("barn_owl"), "dee");
  assert.notEqual(WP.playFor("barn_owl"), "sip");
  assert.notEqual(WP.playFor("barn_owl"), "drum");
  assert.notEqual(WP.playFor("barn_owl"), "vee");
  assert.equal(WP.playFor("red_tail"), "soar");
  assert.notEqual(WP.playFor("red_tail"), "hook");
  assert.notEqual(WP.playFor("red_tail"), "hiss");
  assert.notEqual(WP.playFor("red_tail"), "croak");
  assert.notEqual(WP.playFor("red_tail"), "caw");
  assert.notEqual(WP.playFor("red_tail"), "sill");
  assert.notEqual(WP.playFor("red_tail"), "perch");
  assert.notEqual(WP.playFor("red_tail"), "bow");
  assert.notEqual(WP.playFor("red_tail"), "toss");
  assert.notEqual(WP.playFor("red_tail"), "ledge");
  assert.notEqual(WP.playFor("red_tail"), "ridge");
  assert.notEqual(WP.playFor("red_tail"), "barrel");
  assert.notEqual(WP.playFor("red_tail"), "orbit");
  assert.notEqual(WP.playFor("red_tail"), "fan");
  assert.notEqual(WP.playFor("red_tail"), "stoop");
  assert.notEqual(WP.playFor("red_tail"), "dee");
  assert.notEqual(WP.playFor("red_tail"), "sip");
  assert.notEqual(WP.playFor("red_tail"), "drum");
  assert.notEqual(WP.playFor("red_tail"), "vee");
  assert.notEqual(WP.playFor("red_tail"), "dabble");
  assert.notEqual(WP.playFor("red_tail"), "honk");
  assert.notEqual(WP.playFor("red_tail"), "hover");
  assert.equal(WP.playFor("chickadee"), "cache");
  assert.notEqual(WP.playFor("chickadee"), "dee");
  assert.notEqual(WP.playFor("chickadee"), "soar");
  assert.notEqual(WP.playFor("chickadee"), "hiss");
  assert.notEqual(WP.playFor("chickadee"), "croak");
  assert.notEqual(WP.playFor("chickadee"), "caw");
  assert.notEqual(WP.playFor("chickadee"), "stash");
  assert.notEqual(WP.playFor("chickadee"), "sill");
  assert.notEqual(WP.playFor("chickadee"), "perch");
  assert.notEqual(WP.playFor("chickadee"), "hook");
  assert.notEqual(WP.playFor("chickadee"), "bow");
  assert.notEqual(WP.playFor("chickadee"), "toss");
  assert.notEqual(WP.playFor("chickadee"), "ledge");
  assert.notEqual(WP.playFor("chickadee"), "seed");
  assert.notEqual(WP.playFor("chickadee"), "forage");
  assert.notEqual(WP.playFor("chickadee"), "dust");
  assert.notEqual(WP.playFor("chickadee"), "lean");
  assert.notEqual(WP.playFor("chickadee"), "count");
  assert.notEqual(WP.playFor("chickadee"), "filter");
  assert.notEqual(WP.playFor("chickadee"), "hop");
  assert.notEqual(WP.playFor("chickadee"), "dabble");
  assert.notEqual(WP.playFor("chickadee"), "honk");
  assert.notEqual(WP.playFor("chickadee"), "drum");
  assert.notEqual(WP.playFor("chickadee"), "hover");
  assert.notEqual(WP.playFor("chickadee"), "sip");
  assert.notEqual(WP.playFor("chickadee"), "bury");
  assert.equal(WP.playFor("robin"), "pull");
  assert.notEqual(WP.playFor("robin"), "brick");
  assert.notEqual(WP.playFor("robin"), "cache");
  assert.notEqual(WP.playFor("robin"), "soar");
  assert.notEqual(WP.playFor("robin"), "hiss");
  assert.notEqual(WP.playFor("robin"), "croak");
  assert.notEqual(WP.playFor("robin"), "caw");
  assert.notEqual(WP.playFor("robin"), "sill");
  assert.notEqual(WP.playFor("robin"), "perch");
  assert.notEqual(WP.playFor("robin"), "hook");
  assert.notEqual(WP.playFor("robin"), "bow");
  assert.notEqual(WP.playFor("robin"), "plop");
  assert.notEqual(WP.playFor("robin"), "toss");
  assert.notEqual(WP.playFor("robin"), "ledge");
  assert.notEqual(WP.playFor("robin"), "stash");
  assert.notEqual(WP.playFor("robin"), "dig");
  assert.notEqual(WP.playFor("robin"), "forage");
  assert.notEqual(WP.playFor("robin"), "hop");
  assert.notEqual(WP.playFor("robin"), "dabble");
  assert.notEqual(WP.playFor("robin"), "honk");
  assert.notEqual(WP.playFor("robin"), "drum");
  assert.notEqual(WP.playFor("robin"), "hover");
  assert.notEqual(WP.playFor("robin"), "sip");
  assert.notEqual(WP.playFor("robin"), "vee");
  assert.equal(WP.playFor("red_tail"), "soar");
  assert.equal(WP.playFor("barn_owl"), "hiss");
  assert.equal(WP.playFor("raven"), "croak");
  assert.equal(WP.playFor("crow"), "caw");
  assert.equal(WP.playFor("parrot"), "hook");
  assert.equal(WP.playFor("stickleback"), "glue");
  assert.equal(WP.playFor("leech"), "drink");
  assert.equal(WP.playFor("mussel"), "filter");
  assert.equal(WP.playFor("goldfish"), "circle");
  assert.equal(WP.playFor("budgie"), "perch");
  assert.equal(WP.playFor("penguin"), "bow");
  assert.equal(WP.playFor("toucan"), "toss");
  assert.equal(WP.playFor("cat"), "ledge");
  assert.equal(WP.playFor("hamster"), "stash");
  assert.equal(WP.playFor("cyber_dragon"), "ridge");
  assert.equal(WP.playFor("octopus"), "lid");
  assert.equal(WP.playFor("hermit_crab"), "knob");
  assert.equal(WP.playFor("phoenix"), "kindle");
  assert.equal(WP.playFor("robin"), "pull");
  assert.equal(WP.playFor("mallard"), "tip");
  assert.notEqual(WP.playFor("mallard"), "drake");
  assert.notEqual(WP.playFor("mallard"), "dabble");
  assert.notEqual(WP.playFor("mallard"), "pull");
  assert.notEqual(WP.playFor("mallard"), "cache");
  assert.notEqual(WP.playFor("mallard"), "soar");
  assert.notEqual(WP.playFor("mallard"), "hiss");
  assert.notEqual(WP.playFor("mallard"), "croak");
  assert.notEqual(WP.playFor("mallard"), "caw");
  assert.notEqual(WP.playFor("mallard"), "circle");
  assert.notEqual(WP.playFor("mallard"), "open");
  assert.notEqual(WP.playFor("mallard"), "sill");
  assert.notEqual(WP.playFor("mallard"), "perch");
  assert.notEqual(WP.playFor("mallard"), "bow");
  assert.notEqual(WP.playFor("mallard"), "hook");
  assert.notEqual(WP.playFor("mallard"), "honk");
  assert.notEqual(WP.playFor("mallard"), "drum");
  assert.notEqual(WP.playFor("mallard"), "sip");
  assert.notEqual(WP.playFor("mallard"), "hover");
  assert.equal(WP.playFor("robin"), "pull");
  assert.equal(WP.playFor("chickadee"), "cache");
  assert.equal(WP.playFor("red_tail"), "soar");
  assert.equal(WP.playFor("barn_owl"), "hiss");
  assert.equal(WP.playFor("raven"), "croak");
  assert.equal(WP.playFor("crow"), "caw");
  assert.equal(WP.playFor("goldfish"), "circle");
  assert.equal(WP.playFor("water_lily"), "open");
  assert.equal(WP.playFor("parrot"), "hook");
  assert.equal(WP.playFor("budgie"), "perch");
  assert.equal(WP.playFor("penguin"), "bow");
  assert.equal(WP.playFor("leech"), "drink");
  assert.equal(WP.playFor("stickleback"), "glue");
  assert.equal(WP.playFor("octopus"), "lid");
  assert.equal(WP.playFor("hermit_crab"), "knob");
  assert.equal(WP.playFor("cyber_dragon"), "ridge");
  assert.equal(WP.playFor("phoenix"), "kindle");
  assert.equal(WP.playFor("canada_goose"), "honk");
  assert.notEqual(WP.playFor("canada_goose"), "vee");
  assert.notEqual(WP.playFor("canada_goose"), "goose");
  assert.notEqual(WP.playFor("canada_goose"), "tip");
  assert.notEqual(WP.playFor("canada_goose"), "pull");
  assert.notEqual(WP.playFor("canada_goose"), "cache");
  assert.notEqual(WP.playFor("canada_goose"), "soar");
  assert.notEqual(WP.playFor("canada_goose"), "loop");
  assert.notEqual(WP.playFor("canada_goose"), "sill");
  assert.notEqual(WP.playFor("canada_goose"), "drum");
  assert.notEqual(WP.playFor("canada_goose"), "sip");
  assert.notEqual(WP.playFor("canada_goose"), "hover");
  assert.equal(WP.playFor("pileated"), "drum");
  assert.notEqual(WP.playFor("pileated"), "sill");
  assert.notEqual(WP.playFor("pileated"), "soar");
  assert.notEqual(WP.playFor("pileated"), "bore");
  assert.notEqual(WP.playFor("pileated"), "honk");
  assert.notEqual(WP.playFor("pileated"), "sip");
  assert.notEqual(WP.playFor("pileated"), "hover");
  assert.equal(WP.playFor("hummingbird"), "sip");
  assert.notEqual(WP.playFor("hummingbird"), "sill");
  assert.notEqual(WP.playFor("hummingbird"), "hover");
  assert.notEqual(WP.playFor("hummingbird"), "forage");
  assert.notEqual(WP.playFor("hummingbird"), "snip");
  assert.notEqual(WP.playFor("hummingbird"), "drink");
  assert.notEqual(WP.playFor("hummingbird"), "drum");
  assert.notEqual(WP.playFor("hummingbird"), "web");
  assert.equal(WP.playFor("orb_weaver"), "web");
  assert.notEqual(WP.playFor("orb_weaver"), "sill");
  assert.notEqual(WP.playFor("orb_weaver"), "loom");
  assert.notEqual(WP.playFor("orb_weaver"), "sip");
  assert.notEqual(WP.playFor("orb_weaver"), "hover");
  assert.notEqual(WP.playFor("orb_weaver"), "coil");
  assert.notEqual(WP.playFor("orb_weaver"), "path");
  assert.notEqual(WP.playFor("orb_weaver"), "field");
  assert.notEqual(WP.playFor("orb_weaver"), "crackle");
  assert.notEqual(WP.playFor("orb_weaver"), "charge");
  assert.notEqual(WP.playFor("orb_weaver"), "draw");
  assert.notEqual(WP.playFor("orb_weaver"), "comb");
  assert.notEqual(WP.playFor("orb_weaver"), "drum");
  assert.notEqual(WP.playFor("orb_weaver"), "pounce");
  assert.equal(WP.playFor("jumping_spider"), "pounce");
  assert.notEqual(WP.playFor("jumping_spider"), "sill");
  assert.notEqual(WP.playFor("jumping_spider"), "leap");
  assert.notEqual(WP.playFor("jumping_spider"), "web");
  assert.notEqual(WP.playFor("jumping_spider"), "cache");
  assert.notEqual(WP.playFor("jumping_spider"), "dust");
  assert.notEqual(WP.playFor("jumping_spider"), "count");
  assert.notEqual(WP.playFor("jumping_spider"), "lean");
  assert.notEqual(WP.playFor("jumping_spider"), "coil");
  assert.notEqual(WP.playFor("jumping_spider"), "trail");
  assert.equal(WP.playFor("wolf_spider"), "carry");
  assert.notEqual(WP.playFor("wolf_spider"), "sill");
  assert.notEqual(WP.playFor("wolf_spider"), "prowl");
  assert.notEqual(WP.playFor("wolf_spider"), "pounce");
  assert.notEqual(WP.playFor("wolf_spider"), "web");
  assert.notEqual(WP.playFor("wolf_spider"), "leap");
  assert.notEqual(WP.playFor("wolf_spider"), "watch");
  assert.notEqual(WP.playFor("wolf_spider"), "scent");
  assert.notEqual(WP.playFor("wolf_spider"), "wheek");
  assert.notEqual(WP.playFor("wolf_spider"), "ball");
  assert.notEqual(WP.playFor("wolf_spider"), "cover");
  assert.equal(WP.playFor("tarantula"), "kick");
  assert.notEqual(WP.playFor("tarantula"), "velvet");
  assert.notEqual(WP.playFor("tarantula"), "sill");
  assert.notEqual(WP.playFor("tarantula"), "carry");
  assert.notEqual(WP.playFor("tarantula"), "pounce");
  assert.notEqual(WP.playFor("tarantula"), "web");
  assert.notEqual(WP.playFor("tarantula"), "bun");
  assert.notEqual(WP.playFor("tarantula"), "tend");
  assert.notEqual(WP.playFor("tarantula"), "hiss");
  assert.equal(WP.playFor("widow"), "hang");
  assert.notEqual(WP.playFor("widow"), "hour");
  assert.notEqual(WP.playFor("widow"), "kick");
  assert.notEqual(WP.playFor("widow"), "web");
  assert.notEqual(WP.playFor("widow"), "sill");
  assert.notEqual(WP.playFor("widow"), "stash");
  assert.notEqual(WP.playFor("widow"), "coil");
  assert.notEqual(WP.playFor("widow"), "velvet");
  assert.equal(WP.playFor("harvestman"), "stilt");
  assert.notEqual(WP.playFor("harvestman"), "stem");
  assert.notEqual(WP.playFor("harvestman"), "hang");
  assert.notEqual(WP.playFor("harvestman"), "web");
  assert.notEqual(WP.playFor("harvestman"), "hitch");
  assert.notEqual(WP.playFor("harvestman"), "inspect");
  assert.notEqual(WP.playFor("harvestman"), "sill");
  assert.equal(WP.playFor("scorpion"), "raise");
  assert.notEqual(WP.playFor("scorpion"), "barb");
  assert.notEqual(WP.playFor("scorpion"), "sill");
  assert.notEqual(WP.playFor("scorpion"), "stilt");
  assert.notEqual(WP.playFor("scorpion"), "pull");
  assert.notEqual(WP.playFor("scorpion"), "plow");
  assert.notEqual(WP.playFor("scorpion"), "dig");
  assert.notEqual(WP.playFor("scorpion"), "store");
  assert.notEqual(WP.playFor("scorpion"), "seed");
  assert.notEqual(WP.playFor("scorpion"), "rise");
  assert.notEqual(WP.playFor("scorpion"), "hang");
  assert.notEqual(WP.playFor("scorpion"), "sting");
  assert.equal(WP.playFor("vinegaroon"), "spray");
  assert.notEqual(WP.playFor("vinegaroon"), "whip");
  assert.notEqual(WP.playFor("vinegaroon"), "raise");
  assert.notEqual(WP.playFor("vinegaroon"), "claw");
  assert.notEqual(WP.playFor("vinegaroon"), "ring");
  assert.notEqual(WP.playFor("vinegaroon"), "plow");
  assert.notEqual(WP.playFor("vinegaroon"), "dig");
  assert.notEqual(WP.playFor("vinegaroon"), "store");
  assert.notEqual(WP.playFor("vinegaroon"), "sting");
  assert.notEqual(WP.playFor("vinegaroon"), "barb");
  assert.notEqual(WP.playFor("vinegaroon"), "sill");
  assert.equal(WP.playFor("tick"), "grip");
  assert.notEqual(WP.playFor("tick"), "clasp");
  assert.notEqual(WP.playFor("tick"), "spray");
  assert.notEqual(WP.playFor("tick"), "honk");
  assert.notEqual(WP.playFor("tick"), "loop");
  assert.notEqual(WP.playFor("tick"), "drink");
  assert.notEqual(WP.playFor("tick"), "cling-dive");
  assert.notEqual(WP.playFor("tick"), "sill");
  assert.notEqual(WP.playFor("tick"), "comb");
  assert.notEqual(WP.playFor("tick"), "wait");
  assert.equal(WP.playFor("solifuge"), "run");
  assert.notEqual(WP.playFor("solifuge"), "gale");
  assert.notEqual(WP.playFor("solifuge"), "grip");
  assert.notEqual(WP.playFor("solifuge"), "tip");
  assert.notEqual(WP.playFor("solifuge"), "circle");
  assert.notEqual(WP.playFor("solifuge"), "field");
  assert.notEqual(WP.playFor("solifuge"), "barrel");
  assert.notEqual(WP.playFor("solifuge"), "open");
  assert.notEqual(WP.playFor("solifuge"), "web");
  assert.notEqual(WP.playFor("solifuge"), "raise");
  assert.notEqual(WP.playFor("solifuge"), "sill");
  assert.equal(WP.playFor("deer"), "flag");
  assert.notEqual(WP.playFor("deer"), "rack");
  assert.notEqual(WP.playFor("deer"), "run");
  assert.notEqual(WP.playFor("deer"), "cache");
  assert.notEqual(WP.playFor("deer"), "forage");
  assert.notEqual(WP.playFor("deer"), "carry");
  assert.notEqual(WP.playFor("deer"), "honk");
  assert.notEqual(WP.playFor("deer"), "pull");
  assert.notEqual(WP.playFor("deer"), "sill");
  assert.equal(WP.playFor("bat"), "fold");
  assert.notEqual(WP.playFor("bat"), "cape");
  assert.notEqual(WP.playFor("bat"), "hang");
  assert.notEqual(WP.playFor("bat"), "croak");
  assert.notEqual(WP.playFor("bat"), "perch");
  assert.notEqual(WP.playFor("bat"), "sip");
  assert.notEqual(WP.playFor("bat"), "bow");
  assert.notEqual(WP.playFor("bat"), "flag");
  assert.notEqual(WP.playFor("bat"), "sill");
  assert.equal(WP.playFor("honeybee"), "sill");
  assert.notEqual(WP.playFor("honeybee"), "web");
  assert.equal(WP.playFor("squirrel"), "bury");
  assert.notEqual(WP.playFor("squirrel"), "cache");
  assert.notEqual(WP.playFor("squirrel"), "seed");
  assert.notEqual(WP.playFor("squirrel"), "pull");
  assert.notEqual(WP.playFor("squirrel"), "raise");
  assert.notEqual(WP.playFor("squirrel"), "plow");
  assert.notEqual(WP.playFor("squirrel"), "dig");
  assert.notEqual(WP.playFor("squirrel"), "store");
  assert.notEqual(WP.playFor("squirrel"), "hide");
  assert.notEqual(WP.playFor("squirrel"), "sill");
  assert.equal(WP.playFor("otter"), "slide");
  assert.notEqual(WP.playFor("otter"), "slick");
  assert.notEqual(WP.playFor("otter"), "tip");
  assert.notEqual(WP.playFor("otter"), "ring");
  assert.notEqual(WP.playFor("otter"), "run");
  assert.notEqual(WP.playFor("otter"), "circle");
  assert.notEqual(WP.playFor("otter"), "field");
  assert.notEqual(WP.playFor("otter"), "open");
  assert.notEqual(WP.playFor("otter"), "bask");
  assert.notEqual(WP.playFor("otter"), "bury");
  assert.notEqual(WP.playFor("otter"), "sill");
  assert.equal(WP.playFor("raccoon"), "rinse");
  assert.notEqual(WP.playFor("raccoon"), "wash");
  assert.notEqual(WP.playFor("raccoon"), "spray");
  assert.notEqual(WP.playFor("raccoon"), "fill");
  assert.notEqual(WP.playFor("raccoon"), "drink");
  assert.notEqual(WP.playFor("raccoon"), "slide");
  assert.notEqual(WP.playFor("raccoon"), "inspect");
  assert.notEqual(WP.playFor("raccoon"), "cling-dive");
  assert.notEqual(WP.playFor("raccoon"), "bury");
  assert.notEqual(WP.playFor("raccoon"), "sill");
  assert.equal(WP.playFor("skunk"), "stamp");
  assert.notEqual(WP.playFor("skunk"), "spray");
  assert.notEqual(WP.playFor("skunk"), "raise");
  assert.notEqual(WP.playFor("skunk"), "stripe");
  assert.notEqual(WP.playFor("skunk"), "carry");
  assert.notEqual(WP.playFor("skunk"), "rinse");
  assert.notEqual(WP.playFor("skunk"), "honk");
  assert.notEqual(WP.playFor("skunk"), "flag");
  assert.notEqual(WP.playFor("skunk"), "sill");
  assert.equal(WP.playFor("opossum"), "still");
  assert.notEqual(WP.playFor("opossum"), "fold");
  assert.notEqual(WP.playFor("opossum"), "hang");
  assert.notEqual(WP.playFor("opossum"), "grin");
  assert.notEqual(WP.playFor("opossum"), "sill");
  assert.equal(WP.playFor("beaver"), "gnaw");
  assert.notEqual(WP.playFor("beaver"), "bore");
  assert.notEqual(WP.playFor("beaver"), "drum");
  assert.notEqual(WP.playFor("beaver"), "dam");
  assert.notEqual(WP.playFor("beaver"), "sill");
  assert.equal(WP.playFor("porcupine"), "bristle");
  assert.notEqual(WP.playFor("porcupine"), "hook");
  assert.notEqual(WP.playFor("porcupine"), "ball");
  assert.notEqual(WP.playFor("porcupine"), "spine");
  assert.notEqual(WP.playFor("porcupine"), "sill");
  assert.equal(WP.playFor("black_bear"), "browse");
  assert.notEqual(WP.playFor("black_bear"), "forage");
  assert.notEqual(WP.playFor("black_bear"), "coal");
  assert.notEqual(WP.playFor("black_bear"), "sill");
  assert.equal(WP.playFor("widow"), "hang");
  assert.equal(WP.playFor("sloth"), "reach");
  assert.notEqual(WP.playFor("sloth"), "hang");
  assert.notEqual(WP.playFor("sloth"), "hook");
  assert.notEqual(WP.playFor("sloth"), "fold");
  assert.equal(WP.playFor("lemur"), "warm");
  assert.notEqual(WP.playFor("lemur"), "flag");
  assert.notEqual(WP.playFor("lemur"), "ring");
  assert.notEqual(WP.playFor("lemur"), "sun");
  assert.notEqual(WP.playFor("lemur"), "bask");
  assert.notEqual(WP.playFor("lemur"), "sill");
  assert.equal(WP.playFor("deer"), "flag");
  assert.equal(WP.playFor("gibbon"), "sing");
  assert.notEqual(WP.playFor("gibbon"), "swing");
  assert.notEqual(WP.playFor("gibbon"), "hook");
  assert.notEqual(WP.playFor("gibbon"), "reach");
  assert.equal(WP.playFor("colugo"), "cling");
  assert.notEqual(WP.playFor("colugo"), "sail");
  assert.notEqual(WP.playFor("colugo"), "fold");
  assert.notEqual(WP.playFor("colugo"), "glide");
  assert.notEqual(WP.playFor("colugo"), "drape");
  assert.notEqual(WP.playFor("colugo"), "mount");
  assert.notEqual(WP.playFor("colugo"), "hang");
  assert.notEqual(WP.playFor("colugo"), "wrap");
  assert.notEqual(WP.playFor("colugo"), "sill");
  assert.equal(WP.playFor("bat"), "fold");
  assert.equal(WP.playFor("kinkajou"), "wrap");
  assert.notEqual(WP.playFor("kinkajou"), "sip");
  assert.notEqual(WP.playFor("kinkajou"), "wrist");
  assert.notEqual(WP.playFor("kinkajou"), "drink");
  assert.notEqual(WP.playFor("kinkajou"), "hang");
  assert.notEqual(WP.playFor("kinkajou"), "hook");
  assert.notEqual(WP.playFor("kinkajou"), "curl");
  assert.notEqual(WP.playFor("kinkajou"), "sill");
  assert.equal(WP.playFor("hummingbird"), "sip");
  assert.equal(WP.playFor("flying_squirrel"), "plane");
  assert.notEqual(WP.playFor("flying_squirrel"), "glide");
  assert.notEqual(WP.playFor("flying_squirrel"), "fold");
  assert.notEqual(WP.playFor("flying_squirrel"), "cling");
  assert.notEqual(WP.playFor("flying_squirrel"), "sill");
  assert.equal(WP.playFor("howler"), "howl");
  assert.notEqual(WP.playFor("howler"), "boom");
  assert.notEqual(WP.playFor("howler"), "honk");
  assert.notEqual(WP.playFor("howler"), "sing");
  assert.notEqual(WP.playFor("howler"), "croak");
  assert.notEqual(WP.playFor("howler"), "perch");
  assert.notEqual(WP.playFor("howler"), "caw");
  assert.notEqual(WP.playFor("howler"), "sill");
  assert.equal(WP.playFor("tarsier"), "look");
  assert.notEqual(WP.playFor("tarsier"), "gaze");
  assert.notEqual(WP.playFor("tarsier"), "hiss");
  assert.notEqual(WP.playFor("tarsier"), "pounce");
  assert.notEqual(WP.playFor("tarsier"), "perch");
  assert.notEqual(WP.playFor("tarsier"), "watch");
  assert.notEqual(WP.playFor("tarsier"), "howl");
  assert.notEqual(WP.playFor("tarsier"), "tend");
  assert.notEqual(WP.playFor("tarsier"), "still");
  assert.notEqual(WP.playFor("tarsier"), "sill");
  assert.equal(WP.playFor("potto"), "creep");
  assert.notEqual(WP.playFor("potto"), "still");
  assert.notEqual(WP.playFor("potto"), "grip");
  assert.notEqual(WP.playFor("potto"), "stilt");
  assert.notEqual(WP.playFor("potto"), "hitch");
  assert.notEqual(WP.playFor("potto"), "reach");
  assert.notEqual(WP.playFor("potto"), "hang");
  assert.notEqual(WP.playFor("potto"), "look");
  assert.notEqual(WP.playFor("potto"), "sill");
  assert.equal(WP.playFor("barn_owl"), "hiss");
  assert.equal(WP.playFor("howler"), "howl");
  assert.equal(WP.playFor("opossum"), "still");
  assert.equal(WP.playFor("dog"), "watch");
  assert.equal(WP.playFor("canada_goose"), "honk");
  assert.equal(WP.playFor("gibbon"), "sing");
  assert.equal(WP.playFor("flying_squirrel"), "plane");
  assert.equal(WP.playFor("colugo"), "cling");
  assert.equal(WP.playFor("bat"), "fold");
  assert.equal(WP.playFor("red_panda"), "cling-dive");
  assert.equal(WP.playFor("gecko"), "sill");
});

test("overlay leftover sits weather, news, Sip, ribbon, and the card buses", () => {
  assert.match(htmlSrc, /id="weather-plate"/);
  assert.match(htmlSrc, /id="news-plate"/);
  assert.match(htmlSrc, /id="market-plate"/);
  assert.match(htmlSrc, /id="weather-q"/);
  assert.match(htmlSrc, /id="weather-lookup"/);
  assert.match(htmlSrc, /id="weather-here"/);
  assert.match(htmlSrc, /id="hud-radio-q"/);
  assert.match(htmlSrc, /id="news-q"/);
  assert.match(htmlSrc, /id="market-q"/);
  assert.match(htmlSrc, /market\.js/);
  assert.ok(htmlSrc.indexOf("market.js") < htmlSrc.indexOf("card.js"));
  assert.match(htmlSrc, /id="bird"/);
  assert.match(htmlSrc, /Call Sip/);
  assert.match(htmlSrc, /media-src 'self' https: http: blob:/);
  assert.match(htmlSrc, /weather-areas\.js/);
  assert.ok(htmlSrc.indexOf("weather-areas.js") < htmlSrc.indexOf("card.js"));
  assert.ok(htmlSrc.indexOf("house-sounds.js") < htmlSrc.indexOf("card.js"));
  assert.ok(htmlSrc.indexOf("house-sleep.js") < htmlSrc.indexOf("card.js"));
  assert.match(htmlSrc, /id="hud-sleep"/);
  assert.match(styleSrc, /\.desk-plate/);
  assert.match(styleSrc, /#hud[\s\S]*overflow-y:\s*auto/);
  assert.match(styleSrc, /#choice[\s\S]*overflow-y:\s*auto/);
  assert.match(styleSrc, /#bird\.show/);
  assert.match(petSrc, /callSip/);
  assert.match(petSrc, /spawnCalled/);
  assert.match(petSrc, /syncCalledPaint/);
  assert.doesNotMatch(petSrc, /calledRoot\.replaceChildren\(\)/);
  assert.match(petSrc, /setFocusable/);
  assert.match(petSrc, /pointerdown/);
  assert.match(petSrc, /closest\("input, textarea, select"\)/);
  assert.doesNotMatch(petSrc, /setFocusable\([\s\S]{0,80}hud-line-text/);
  assert.doesNotMatch(petSrc, /setFocusable\([\s\S]{0,80}hud-call-q/);
  assert.match(petSrc, /startThankYou|applyThankYou/);
  assert.match(petSrc, /TYPE_A_CITY|type a city/);
  assert.doesNotMatch(petSrc, /fetch\(N\.newsUrl\(\), \{ cache: "no-store"/);
  assert.doesNotMatch(petSrc, /hid a ribbon/);
  assert.match(petSrc, /stealDeskRibbon/);
  assert.match(petSrc, /playWindows/);
  assert.match(petSrc, /PetRuiTricks/);
  assert.match(petSrc, /ruiSleepBout/);
  assert.match(petSrc, /hostSleeping/);
  const tricksSrc = readFileSync(join(__dirname, "rui-tricks.js"), "utf8");
  assert.match(tricksSrc, /HAPPY\s*=/);
  const happyStart = tricksSrc.slice(tricksSrc.indexOf("function happyCanStart"), tricksSrc.indexOf("function happyShouldAbort"));
  assert.doesNotMatch(happyStart, /windowPlay/);
  assert.doesNotMatch(happyStart, /state\.card/);
  assert.match(tricksSrc, /function startThankYou/);
  assert.match(tricksSrc, /wantsThankYou/);
  assert.match(readFileSync(join(__dirname, "bird-fly.js"), "utf8"), /PERCH_HOST|approach-perch/);
  assert.match(petSrc, /PetDeskHouse\.playStep/);
  assert.deepEqual(C.MUTE_BUSES, ["talk", "special", "weather", "treats", "steps", "music"]);
});

test("call-guests sits on the leftover rooms, not invented dens", () => {
  const rooms = readFileSync(join(__dirname, "..", "..", "web", "src", "lib", "pets", "rooms.ts"), "utf8");
  const overlay = readFileSync(join(__dirname, "call-guests.js"), "utf8");
  const web = readFileSync(join(__dirname, "..", "..", "web", "src", "lib", "pets", "call-guests.ts"), "utf8");
  assert.match(rooms, /id: "garden"/);
  assert.match(rooms, /id: "roost"/);
  assert.match(overlay, /id: "garden"/);
  assert.match(overlay, /aliases: \["garden", "plant"/);
  assert.match(web, /id: "garden"/);
  assert.match(web, /aliases: \["garden", "plant"/);
  assert.match(overlay, /function matchCall/);
  assert.match(web, /export function matchCall/);
  assert.doesNotMatch(web, /from "\.\/rooms"/);
});

test("the tray pins Rui, Sip, and the grid ten", () => {
  assert.deepEqual(D.deskPicks(), [
    "red_panda",
    "hummingbird",
    "cyber_dragon",
    "volt_dragon",
    "trace_dragon",
    "flux_dragon",
    "spark_dragon",
    "ion_dragon",
    "gauss_dragon",
    "relay_dragon",
    "fuse_dragon",
    "ground_dragon",
  ]);
  assert.equal(D.deskPicks().length, 12);
  assert.equal(D.deskPicks()[1], "hummingbird");
  assert.equal(F.FLY_BIRD_KEY, "hummingbird");
  assert.ok(F.MIN_STAY_S >= 24);
  assert.deepEqual(S.VOICE_KEYS, ["red_panda", "hummingbird", "cat", "dog", "chickadee"]);
  assert.equal(S.stepDefault("red_panda"), "soft");
  assert.equal(M.RADIO_CANT_REACH, "can't reach");
  assert.equal(M.RADIO_EMPTY, "no station from that look-up");
  assert.equal(M.RADIO_LABEL, "Radio station");
  assert.equal(M.RADIO_LOCAL, "Local");
  assert.match(M.RADIO_UA, /ComputerPets/);
  assert.equal(M.parseRadioQuery("KEXP").call, "kexp");
  assert.equal(M.parseRadioQuery("KEXP").city, "");
  assert.match(M.radioSearchUrl("KEXP"), /name=KEXP/);
  assert.equal(M.parseRadioQuery("portland").city, "Portland");
  assert.ok(M.radioSearchUrls("portland").some((u) => /city=Portland|name=Portland/.test(u)));
  assert.equal(T.SLEEP_HOLD_FRAME, 1);
  assert.ok(T.nextTrickWait(true, 0, "lie") >= 48);
  assert.ok(T.LIE_HOLD >= 8);
  assert.equal(R.RIBBON_SPECIAL, "I found a ribbon. It was not lost. It is now safer.");
  assert.equal(T.TRICK_KEY, "red_panda");
  assert.equal(existsSync(join(__dirname, "sounds", "hummingbird.wav")), true);
  assert.equal(existsSync(join(__dirname, "sounds", "house-loop.wav")), true);
  assert.equal(existsSync(join(__dirname, "sounds", "sleep-rain.ogg")), true);
  assert.equal(Sleep.SLEEP_AID_PLUGINS[0].name, "Off");
  assert.equal(Sleep.SLEEP_AID_PLUGINS[1].name, "Rain and thunder");
  assert.equal(Sleep.SLEEP_AID_LICENSE, "CC0 · house-made");
});

function oggDurationSeconds(buf, rate = 22050) {
  let last = 0n;
  for (let i = 0; i < buf.length - 27; i++) {
    if (buf[i] === 0x4f && buf[i + 1] === 0x67 && buf[i + 2] === 0x67 && buf[i + 3] === 0x53) {
      const granule = buf.readBigUInt64LE(i + 6);
      if (granule > last) last = granule;
    }
  }
  return Number(last) / rate;
}

test("Sleep aid Off vs Rain and thunder starts, loops, and stops on mute", () => {
  assert.deepEqual(Sleep.SLEEP_AID_PLUGINS.map((p) => p.id), ["off", "rain"]);
  assert.equal(Sleep.shouldPlay({ plugin: "rain", playing: true }, { music: false }), true);
  assert.equal(Sleep.shouldPlay({ plugin: "rain", playing: true }, { music: true }), false);
  assert.equal(Sleep.shouldPlay({ plugin: "off", playing: false }, { music: false }), false);
  const makeAudio = (src) => {
    const node = { src, loop: false, volume: 1, paused: true, plays: 0, dataset: {} };
    node.play = () => {
      node.paused = false;
      node.plays += 1;
      return Promise.resolve();
    };
    node.pause = () => {
      node.paused = true;
    };
    return node;
  };
  const on = Sleep.applySleepAid(null, { plugin: "rain", playing: true }, { music: false }, 0.8, { makeAudio });
  assert.equal(on.loop, true);
  assert.equal(on.src, "sounds/sleep-rain.ogg");
  assert.equal(on.paused, false);
  const muted = Sleep.applySleepAid(on, { plugin: "rain", playing: true }, { music: true }, 0.8, { makeAudio });
  assert.equal(muted, null);
  assert.equal(on.paused, true);
  const off = Sleep.applySleepAid(makeAudio("x"), { plugin: "off", playing: false }, { music: false }, 0.8, { makeAudio });
  assert.equal(off, null);
  const buf = readFileSync(join(__dirname, "sounds", "sleep-rain.ogg"));
  const dur = oggDurationSeconds(buf);
  assert.ok(dur >= 170 && dur <= 195, `sleep-rain duration ${dur}`);
  assert.match(petSrc, /function sitSleepAid/);
  assert.match(petSrc, /sitSleepAid\(\)/);
  assert.equal(C.parseCard({}).sleepAid.plugin, "off");
  assert.equal(C.parseCard({ sleepAid: { plugin: "rain", playing: true } }).sleepAid.playing, true);
  const mainSrc = readFileSync(join(__dirname, "..", "main.cjs"), "utf8");
  assert.match(mainSrc, /sandbox:\s*true/);
  assert.match(mainSrc, /contextIsolation:\s*true/);
  assert.match(mainSrc, /nodeIntegration:\s*false/);
});

const News = require("./news.js");
const Market = require("./market.js");

test("news topics and quotes persist on the leftover card", () => {
  const world = News.currentTopic(News.blankNewsPrefs());
  assert.equal(world.id, "world");
  assert.equal(world.name, "World");
  let prefs = News.addTopic(News.blankNewsPrefs(), { name: "marijuana news", query: "marijuana news" });
  assert.equal(News.currentTopic(prefs).query, "marijuana news");
  assert.match(News.topicRssUrl("Tacoma crime"), /news\.google\.com/);
  const card = C.parseCard({ newsPrefs: prefs.topics, currentNewsId: prefs.currentId, marketTickers: [{ symbol: "AAPL" }, { symbol: "BTC" }] });
  assert.equal(card.currentNewsId, prefs.currentId);
  assert.ok(card.newsPrefs.some((t) => t.query === "marijuana news"));
  assert.equal(card.marketTickers.length, 2);
  assert.equal(Market.classify("AAPL").kind, "stock");
  assert.equal(Market.classify("BTC").kind, "crypto");
  assert.match(Market.yahooUrl("AAPL"), /query1\.finance\.yahoo\.com/);
  assert.match(Market.geckoUrl("bitcoin"), /api\.coingecko\.com/);
  assert.equal(Market.parseYahoo({ chart: { result: [{ meta: { regularMarketPrice: 12.5, shortName: "Apple", currency: "USD" } }] } }).price, 12.5);
  assert.equal(Market.parseGecko({ bitcoin: { usd: 64000 } }, "bitcoin").price, 64000);
});
