/** Per-species life traits — audited one by one. */
window.PET_TRAITS = {
  red_panda: {
    size: 1, walk: 98, hop: 26, pitch: 1.15, rate: 0.92,
    nocturnal: false, sleepStart: 22, sleepEnd: 7,
    hungerH: 6, energyH: 9, hygieneH: 14, hardy: 0.72, social: 0.85, messy: 0.38,
    clingy: false, perch: false, aquatic: false, wander: 0.48,
    special: "ribbon",
    diet: "herb",
    extra: {
      sick: ["My ears feel heavy. Not a napping heavy."],
      clean: ["The blotter is honest again."],
      bath: ["Ribbon first. Then water. Then dignity."],
      medicine: ["Bitter. I will invoice you in kindness."],
      praise: ["I stored that in the left ear."],
      hide: ["I went where the ribbon goes."],
      call: ["You called. I brought the whole tail."],
      special: ["I found a ribbon. It was not lost. It is now safer."],
    },
  },
  cat: {
    size: 1.02, walk: 68, hop: 16, pitch: 0.95, rate: 0.86,
    nocturnal: false, sleepStart: 13, sleepEnd: 16,
    hungerH: 7, energyH: 11, hygieneH: 18, hardy: 0.8, social: 0.45, messy: 0.18,
    clingy: false, perch: false, aquatic: false, wander: 0.22,
    special: "sun",
    diet: "omni",
    extra: {
      sick: ["I am not dramatic. I am unwell. There is a difference."],
      clean: ["Adequate."],
      bath: ["You will not. We will discuss a wipe."],
      medicine: ["I allow this. Once."],
      praise: ["I will consider a blink."],
      hide: ["The ledge is closed."],
      call: ["I returned. The sun moved."],
      special: ["This patch of light is reserved."],
    },
  },
  dog: {
    size: 0.96, walk: 122, hop: 30, pitch: 1.05, rate: 1.02,
    nocturnal: false, sleepStart: 21, sleepEnd: 6,
    hungerH: 5, energyH: 7, hygieneH: 10, hardy: 0.78, social: 1.2, messy: 0.55,
    clingy: true, perch: false, aquatic: false, wander: 0.62,
    special: "follow",
    diet: "omni",
    extra: {
      sick: ["I can still walk. I would rather sit beside you."],
      clean: ["The rug is a treaty again."],
      bath: ["I endured the water. For you."],
      medicine: ["If it helps the walk later."],
      praise: ["I stored that in the chest."],
      hide: ["I waited by the door that is not here."],
      call: ["You called. I was already coming."],
      special: ["The cursor moved. I have prepared a walk."],
    },
  },
  rabbit: {
    size: 0.86, walk: 136, hop: 36, pitch: 1.2, rate: 1.04,
    nocturnal: false, sleepStart: 23, sleepEnd: 6,
    hungerH: 5.5, energyH: 8, hygieneH: 12, hardy: 0.55, social: 0.6, messy: 0.42,
    clingy: false, perch: false, aquatic: false, wander: 0.4, startle: true,
    special: "thump",
    diet: "herb",
    extra: {
      sick: ["The warren feels too loud inside."],
      clean: ["The corner is safe again."],
      bath: ["A careful wipe. Then I vanish."],
      medicine: ["Small. Quiet. Thank you."],
      praise: ["I thumped that into the floorboards."],
      hide: ["Gone. Softly."],
      call: ["I came out. Do not make it loud."],
      special: ["Thump. That was a warning and a hello."],
    },
  },
  hamster: {
    size: 0.7, walk: 148, hop: 22, pitch: 1.25, rate: 1.08,
    nocturnal: true, sleepStart: 9, sleepEnd: 18,
    hungerH: 4.5, energyH: 6, hygieneH: 9, hardy: 0.6, social: 0.7, messy: 0.7,
    clingy: false, perch: false, aquatic: false, wander: 0.7,
    special: "hoard",
    diet: "seed",
    extra: {
      sick: ["The night shift is cancelled. Temporarily."],
      clean: ["Inventory restored."],
      bath: ["I will allow a seed-scented wipe."],
      medicine: ["Logged."],
      praise: ["Morale: rising."],
      hide: ["The drawer is closed."],
      call: ["I clocked back in."],
      special: ["This paperclip is now mine. Officially."],
    },
  },
  guinea_pig: {
    size: 0.8, walk: 84, hop: 18, pitch: 1.12, rate: 0.98,
    nocturnal: false, sleepStart: 21, sleepEnd: 7,
    hungerH: 4, energyH: 8, hygieneH: 8, hardy: 0.58, social: 1.35, messy: 0.62,
    clingy: true, perch: false, aquatic: false, wander: 0.5,
    special: "wheek",
    diet: "herb",
    extra: {
      sick: ["A small wheek. Not a party wheek."],
      clean: ["The bowl is a country again."],
      bath: ["Hay after. That is the law."],
      medicine: ["If salad follows, I agree."],
      praise: ["I wheeked that into the rafters."],
      hide: ["The hay closed."],
      call: ["Wheek. That means you."],
      special: ["Wheek. Deploy celebrated."],
    },
  },
  turtle: {
    size: 0.92, walk: 26, hop: 3, pitch: 0.82, rate: 0.78,
    nocturnal: false, sleepStart: 20, sleepEnd: 8,
    hungerH: 16, energyH: 20, hygieneH: 22, hardy: 0.96, social: 0.4, messy: 0.12,
    clingy: false, perch: false, aquatic: false, wander: 0.08,
    special: "still",
    diet: "herb",
    extra: {
      sick: ["Even I can be delayed."],
      clean: ["The dish is in order."],
      bath: ["A long soak. I invented this."],
      medicine: ["I will finish it this afternoon."],
      praise: ["I will carry that. Slowly."],
      hide: ["Withdrawn."],
      call: ["I have been here. That is the greeting."],
      special: ["I moved. You missed it. That is fine."],
    },
  },
  goldfish: {
    size: 0.78, walk: 52, hop: 6, pitch: 1.08, rate: 0.9,
    nocturnal: false, sleepStart: 0, sleepEnd: 4,
    hungerH: 6, energyH: 10, hygieneH: 7, hardy: 0.5, social: 0.55, messy: 0.35,
    clingy: false, perch: false, aquatic: true, wander: 0.8,
    special: "loop",
    diet: "flake",
    extra: {
      sick: ["The water feels like a smaller thought."],
      clean: ["The bowl shines. I will forget, then notice."],
      bath: ["I live here. This is already a bath."],
      medicine: ["A flake that is also a cure."],
      praise: ["I will swim that sentence until it shines."],
      hide: ["Behind the glass."],
      call: ["Oh. You. I was just thinking that."],
      special: ["Around again. The view improved."],
    },
  },
  budgie: {
    size: 0.68, walk: 92, hop: 20, pitch: 1.28, rate: 1.1,
    nocturnal: false, sleepStart: 19, sleepEnd: 6,
    hungerH: 5, energyH: 8, hygieneH: 11, hardy: 0.52, social: 1.1, messy: 0.48,
    clingy: false, perch: true, aquatic: false, wander: 0.45,
    special: "echo",
    diet: "seed",
    extra: {
      sick: ["My voice is a smaller bird today."],
      clean: ["The perch is editorial again."],
      bath: ["Splash. Encore."],
      medicine: ["Bitter. Bitter."],
      praise: ["Love. Love. I like that one."],
      hide: ["Shade down."],
      call: ["Hello hello. I practiced that."],
      special: ["Build failed. But musically."],
    },
  },
  fox: {
    size: 1.04, walk: 112, hop: 24, pitch: 0.98, rate: 0.94,
    nocturnal: true, sleepStart: 10, sleepEnd: 17,
    hungerH: 7, energyH: 9, hygieneH: 13, hardy: 0.74, social: 0.65, messy: 0.3,
    clingy: false, perch: false, aquatic: false, wander: 0.4,
    special: "bug",
    diet: "omni",
    extra: {
      sick: ["Even clever things get dull."],
      clean: ["The closet is a clean crime scene."],
      bath: ["I will not admit I liked it."],
      medicine: ["A calculated risk."],
      praise: ["Filed under obvious. Still nice."],
      hide: ["You will not find this den."],
      call: ["I found you first."],
      special: ["There is a bug in the left pocket. You knew."],
    },
  },
  penguin: {
    size: 0.9, walk: 58, hop: 12, pitch: 0.9, rate: 0.88,
    nocturnal: false, sleepStart: 21, sleepEnd: 6,
    hungerH: 8, energyH: 10, hygieneH: 15, hardy: 0.82, social: 0.75, messy: 0.2,
    clingy: false, perch: false, aquatic: false, wander: 0.28,
    special: "ritual",
    diet: "fish",
    extra: {
      sick: ["I must postpone the ceremony."],
      clean: ["The tile is correctly cold and clean."],
      bath: ["Protocol includes a dip."],
      medicine: ["Entered into the minutes."],
      praise: ["Noted. Warmly."],
      hide: ["Session adjourned."],
      call: ["You are recognized."],
      special: ["A bow. It is brief. It is required."],
    },
  },
  parrot: {
    size: 0.94, walk: 88, hop: 22, pitch: 1.06, rate: 0.96,
    nocturnal: false, sleepStart: 20, sleepEnd: 6,
    hungerH: 6, energyH: 8, hygieneH: 12, hardy: 0.64, social: 1.15, messy: 0.5,
    clingy: false, perch: true, aquatic: false, wander: 0.42,
    special: "quote",
    diet: "seed",
    extra: {
      sick: ["The understudy will not do."],
      clean: ["The stand is lit and swept."],
      bath: ["A scene in water."],
      medicine: ["For the second act."],
      praise: ["I will say that from the rafters."],
      hide: ["Curtain."],
      call: ["Enter, keeper."],
      special: ["Fix typo. A masterpiece."],
    },
  },
  ferret: {
    size: 0.88, walk: 156, hop: 20, pitch: 1.14, rate: 1.06,
    nocturnal: false, sleepStart: 2, sleepEnd: 10,
    hungerH: 5, energyH: 6, hygieneH: 7, hardy: 0.6, social: 0.9, messy: 0.92,
    clingy: false, perch: false, aquatic: false, wander: 0.75,
    special: "steal",
    diet: "omni",
    extra: {
      sick: ["The tunnel is too long today."],
      clean: ["I put the dongle back. Nearby."],
      bath: ["I escaped once. Then I endured."],
      medicine: ["If I must."],
      praise: ["I hid that in the good pocket."],
      hide: ["Relocated."],
      call: ["You found me. I was working."],
      special: ["I put your dongle somewhere better."],
    },
  },
  hedgehog: {
    size: 0.76, walk: 48, hop: 10, pitch: 1.02, rate: 0.9,
    nocturnal: true, sleepStart: 8, sleepEnd: 17,
    hungerH: 8, energyH: 11, hygieneH: 14, hardy: 0.7, social: 0.35, messy: 0.22,
    clingy: false, perch: false, aquatic: false, wander: 0.16,
    special: "curl",
    diet: "omni",
    extra: {
      sick: ["I am a smaller ball than usual."],
      clean: ["The knit is honest."],
      bath: ["A damp cloth. Then a long wait."],
      medicine: ["Offered, not tossed. Good."],
      praise: ["I will keep that under the quills."],
      hide: ["Ball. Official."],
      call: ["I uncurled one quill."],
      special: ["Waiting is a kindness I notice."],
    },
  },
  chinchilla: {
    size: 0.8, walk: 118, hop: 26, pitch: 1.18, rate: 1.0,
    nocturnal: false, sleepStart: 22, sleepEnd: 8,
    hungerH: 7, energyH: 8, hygieneH: 5, hardy: 0.58, social: 0.7, messy: 0.15,
    clingy: false, perch: false, aquatic: false, wander: 0.38,
    special: "bath",
    diet: "herb",
    extra: {
      sick: ["My coat has opinions. Bad ones."],
      clean: ["Finally."],
      bath: ["Dust, not water. Correct."],
      medicine: ["If it does not mat the fur."],
      praise: ["I will keep that off the floor."],
      hide: ["The bath is closed."],
      call: ["I inspected the desk. It may stay."],
      special: ["That crumb is a scandal."],
    },
  },
  axolotl: {
    size: 0.9, walk: 34, hop: 5, pitch: 0.88, rate: 0.8,
    nocturnal: false, sleepStart: 1, sleepEnd: 7,
    hungerH: 10, energyH: 14, hygieneH: 8, hardy: 0.88, social: 0.5, messy: 0.28,
    clingy: false, perch: false, aquatic: true, wander: 0.3,
    special: "regrow",
    diet: "pellet",
    extra: {
      sick: ["I am growing a quieter patience."],
      clean: ["The cistern is a clear thought."],
      bath: ["I never left the bath."],
      medicine: ["A small moon that heals."],
      praise: ["I will grow that back if I lose it."],
      hide: ["Behind the fronds."],
      call: ["I was already looking at the door."],
      special: ["I grew a little more calm."],
    },
  },
  toucan: {
    size: 1.08, walk: 80, hop: 18, pitch: 1.0, rate: 0.95,
    nocturnal: false, sleepStart: 19, sleepEnd: 6,
    hungerH: 6, energyH: 9, hygieneH: 12, hardy: 0.62, social: 0.85, messy: 0.4,
    clingy: false, perch: true, aquatic: false, wander: 0.34,
    special: "bill",
    diet: "fruit",
    extra: {
      sick: ["The bill is heavy. The bird is heavier."],
      clean: ["The shelf is a balcony again."],
      bath: ["The bill arrives first. Then the water."],
      medicine: ["Fruit that is also work."],
      praise: ["I will carry that in the big room."],
      hide: ["Above you. On purpose."],
      call: ["I arrived. You noticed the bill."],
      special: ["This perch has opinions about your posture."],
    },
  },
  iguana: {
    size: 1.06, walk: 20, hop: 4, pitch: 0.8, rate: 0.76,
    nocturnal: false, sleepStart: 19, sleepEnd: 8,
    hungerH: 14, energyH: 18, hygieneH: 16, hardy: 0.84, social: 0.3, messy: 0.14,
    clingy: false, perch: false, aquatic: false, wander: 0.06,
    special: "bask",
    diet: "herb",
    extra: {
      sick: ["The wall is colder than it should be."],
      clean: ["The brick is correct."],
      bath: ["A warm wipe. Then stillness."],
      medicine: ["I will finish it this hour."],
      praise: ["I will keep that until the light changes."],
      hide: ["Ornament mode."],
      call: ["I have not moved. That is hello."],
      special: ["I blinked. Minutes will not record it."],
    },
  },
  dragon: {
    size: 1.18, walk: 74, hop: 22, pitch: 0.78, rate: 0.84,
    nocturnal: false, sleepStart: 23, sleepEnd: 8,
    hungerH: 9, energyH: 11, hygieneH: 15, hardy: 0.9, social: 0.55, messy: 0.16,
    clingy: false, perch: false, aquatic: false, wander: 0.24,
    special: "hoard",
    diet: "myth",
    extra: {
      sick: ["A province should not be hollow."],
      clean: ["The mantel is a clean seat of state."],
      bath: ["I will not singe the towel."],
      medicine: ["Tribute of a different kind."],
      praise: ["Into the hoard that matters."],
      hide: ["The stone keeps me."],
      call: ["You may approach the mantel."],
      special: ["I could be larger. I choose this."],
    },
  },
  phoenix: {
    size: 1.12, walk: 86, hop: 24, pitch: 0.92, rate: 0.88,
    nocturnal: false, sleepStart: 0, sleepEnd: 5,
    hungerH: 11, energyH: 13, hygieneH: 16, hardy: 0.7, social: 0.6, messy: 0.1,
    clingy: false, perch: true, aquatic: false, wander: 0.3,
    special: "reborn",
    diet: "myth",
    extra: {
      sick: ["Ash is a kind of fever."],
      clean: ["The hearth is swept."],
      bath: ["Warm water. I recognize it."],
      medicine: ["A spark of a cure."],
      praise: ["I will bring that back with me."],
      hide: ["In the ash."],
      call: ["I have been here before. So have you."],
      special: ["I came back softer."],
    },
  },
};
