/** Today's caller. Same pick, same line, same walk as the desk HouseVisit. */
(function (root) {
  const VISIT_WAIT_MS = 7500;
  const VISIT_TALK_MS = 1600;
  const VISIT_WANDER_MS = 5200;
  const VISIT_LEAVE_MS = 14000;
  const VISIT_GONE_MS = 18500;

  const CATALOG_KEYS = ["red_panda","cat","dog","rabbit","hamster","guinea_pig","turtle","goldfish","budgie","fox","penguin","parrot","ferret","hedgehog","chinchilla","axolotl","toucan","iguana","dragon","phoenix","ball_python","corn_snake","kingsnake","green_tree_python","hognose","garter","boa","milk_snake","rosy_boa","carpet_python","octopus","cuttlefish","nautilus","moon_jelly","sea_star","hermit_crab","horseshoe_crab","seahorse","manta","moray","moss","maidenhair","ginkgo","oak","water_lily","orchid","saguaro","venus_flytrap","pitcher","sundew","honeybee","monarch","luna","firefly","darner","stick","carpenter_ant","ladybird","mantis","cicada","bumblebee","carpenter_bee","mason_bee","leafcutter","stingless","sweat_bee","mining_bee","honey_drone","honey_queen","honeycomb","oyster","fly_agaric","morel","chanterelle","turkey_tail","lions_mane","puffball","chicken_of_woods","yeast","lichen","photovore","choir","nimbus","silica","terminator","nexus","halovore","magneton","umbral","cyst","frog","toad","newt","salamander","caecilian","crayfish","pond_snail","mussel","leech","stickleback","paramecium","amoeba","euglena","volvox","diatom","kelp","chlamydomonas","stentor","coli","haloarchaea","crow","raven","barn_owl","red_tail","chickadee","robin","mallard","canada_goose","pileated","hummingbird","orb_weaver","jumping_spider","wolf_spider","tarantula","widow","harvestman","scorpion","vinegaroon","tick","solifuge","deer","bat","squirrel","otter","raccoon","skunk","opossum","beaver","porcupine","black_bear","gecko","anole","skink","chameleon","horned_lizard","alligator","crocodile","snapper","box_turtle","tuatara","bass","brook_trout","catfish","bluegill","perch","pike","walleye","paddlefish","lamprey","american_eel","house_centipede","millipede","pillbug","earthworm","velvet_worm","springtail","tardigrade","planarian","nematode","amphipod","fiddler_crab","ghost_crab","limpet","barnacle","chiton","periwinkle","sand_dollar","sea_urchin","knobbed_whelk","lugworm","field_cricket","katydid","grasshopper","swallowtail","jewelwing","lacewing","earwig","acorn_weevil","click_beetle","robber_fly","sloth","lemur","gibbon","kinkajou","colugo","flying_squirrel","howler","tarsier","potto","koala","brain_coral","anemone","clownfish","parrotfish","cleaner_shrimp","sea_cucumber","lionfish","giant_clam","eagle_ray","grouper"];

  const VISIT_LINE = {
  red_panda: "I came for the ribbon. I'll put it back. Maybe.",
  cat: "I inspected the blotter. It will do.",
  dog: "I brought the whole tail. Then I took it home.",
  rabbit: "A short visit. The greens here are theoretical.",
  hamster: "I mapped the crumbs. Officially.",
  guinea_pig: "Wheek. That is the entire review.",
  turtle: "I arrived. I will leave in due course.",
  goldfish: "I drifted through. That counts.",
  budgie: "A note: your house is loud. I approve.",
  fox: "I found this desk first. Then I left it.",
  penguin: "A pebble of a visit.",
  parrot: "I came to quote the furniture.",
  ferret: "I borrowed a dongle. I'll return a better one.",
  hedgehog: "A quiet walk-through.",
  chinchilla: "The dust here is a scandal. I took a sample.",
  axolotl: "I grew a little more present. Then less.",
  toucan: "The bill approves of this blotter.",
  iguana: "I blinked at your lamp. Then I left.",
  dragon: "A courtesy inspection of the hoard.",
  phoenix: "I warmed the corner. You're welcome.",
  ball_python: "I came as a bun. I will leave as a bun.",
  corn_snake: "I threaded through. Your gap is fine.",
  kingsnake: "I inspected. You may keep the desk.",
  green_tree_python: "I hung on your lamp. Briefly.",
  hognose: "I died on your blotter. I got over it.",
  garter: "I patrolled. The moss is adequate.",
  boa: "I held the edge. Then I let go.",
  milk_snake: "I was a rumor. Then I was lunch-minded.",
  rosy_boa: "I borrowed the warm corner. I left it pink.",
  carpet_python: "I charted your shelf. You may land.",
  octopus: "I tasted the rim. Then I was a cup again.",
  cuttlefish: "I flushed. Then I left the weather.",
  nautilus: "I rose through. The house can wait.",
  moon_jelly: "I pulsed through. That counts.",
  sea_star: "I clung. Then I unclung. Slowly.",
  hermit_crab: "I measured the lids. None were free.",
  horseshoe_crab: "I walked the sand. I am not a crab.",
  seahorse: "I hitched your pencil. Briefly.",
  manta: "I soared the bowl. You may keep the sky.",
  moray: "I was the door. Then I was gone.",
  moss: "I carpeted. Then I was the page again.",
  maidenhair: "I unfurled. Then I folded.",
  ginkgo: "I golded. Then I left the autumn.",
  oak: "I dropped one. Then I was small again.",
  water_lily: "I opened. Then I closed.",
  orchid: "I bloomed. Then I was bark again.",
  saguaro: "I stored a visit. Then I sat.",
  venus_flytrap: "I did not snap. Then I left the cup.",
  pitcher: "I kept the well. Then I left the rain.",
  sundew: "I glittered. Then I uncurled.",
  honeybee: "I danced. Then I left the map.",
  monarch: "I kept the orange. Then I left the cup.",
  luna: "I drifted. I did not eat.",
  firefly: "I flashed. Then I left the grammar.",
  darner: "I hawed. Then I was air again.",
  stick: "I froze. Then I was a pencil again.",
  carpenter_ant: "I laid a road. Then I left the grain.",
  ladybird: "I counted. Then I left the seven.",
  mantis: "I folded. Then I left the stem.",
  cicada: "I sat. Then I left the years.",
  bumblebee: "I thrummed. Then I left the cup.",
  carpenter_bee: "I bored. Then I left the hole.",
  mason_bee: "I sealed. Then I left the stone.",
  leafcutter: "I cut. Then I left the disc.",
  stingless: "I potted. Then I left the wax.",
  sweat_bee: "I shone. Then I left the rim.",
  mining_bee: "I dug. Then I left the bank.",
  honey_drone: "I hummed. Then I left the dish.",
  honey_queen: "I stayed. Then I left the line.",
  honeycomb: "I sat. Then the line went quieter.",
  oyster: "I fruited. Then I left the wood.",
  fly_agaric: "I warned. Then I left the cup.",
  morel: "I sat hollow. Then I left the mold.",
  chanterelle: "I forked. Then I left the rim.",
  turkey_tail: "I zoned. Then I left the grain.",
  lions_mane: "I hung teeth. Then I left the wound.",
  puffball: "I puffed. Then I left the cloud.",
  chicken_of_woods: "I shelved. Then I left the oak.",
  yeast: "I rose. Then I left the crock.",
  lichen: "We sat. Then we left the share.",
  photovore: "I drank. Then I left the glass.",
  choir: "I sounded. Then I left the air.",
  nimbus: "I floated. Then I left the bowl.",
  silica: "I faceted. Then I left the stone.",
  terminator: "I kept the rim. Then I left the belt.",
  nexus: "We counted. Then we left the name.",
  halovore: "I frosted. Then I left the dish.",
  magneton: "I aligned. Then I left the line.",
  umbral: "I dimmed. Then I left the cool.",
  cyst: "I waited. Then I left the seal.",
  frog: "I jumped. Then I left the bank.",
  toad: "I hopped. Then I left the leaf.",
  newt: "I kept the orange. Then I left the moss.",
  salamander: "I hid. Then I left the mold.",
  caecilian: "I slipped. Then I left the silt.",
  crayfish: "I pinched. Then I left the pebble.",
  pond_snail: "I rasped. Then I left the rim.",
  mussel: "I filtered. Then I left the silt.",
  leech: "I latched. Then I left the damp.",
  stickleback: "I flared. Then I left the nest.",
  paramecium: "I rowed. Then I left the drop.",
  amoeba: "I reached. Then I left the film.",
  euglena: "I drank. Then I left the red.",
  volvox: "We rolled. Then we left the bowl.",
  diatom: "I glided. Then I left the pane.",
  kelp: "I held. Then I left the cold.",
  chlamydomonas: "I spun. Then I left the plate.",
  stentor: "I opened. Then I left the horn.",
  coli: "I tumbled. Then I left the broth.",
  haloarchaea: "I blushed. Then I left the pan.",
  crow: "I cawed. Then I left the ledge.",
  raven: "I croaked. Then I left the rafter.",
  barn_owl: "I hissed. Then I left the beam.",
  red_tail: "I soared. Then I left the post.",
  chickadee: "I deeed. Then I left the cup.",
  robin: "I hopped. Then I left the rim.",
  mallard: "I dabbled. Then I left the dish.",
  canada_goose: "I honked. Then I left the green.",
  pileated: "I drummed. Then I left the post.",
  hummingbird: "I hovered. Then I left the cup.",
  orb_weaver: "I sat. Then I left the web.",
  jumping_spider: "I leapt. Then I left the edge.",
  wolf_spider: "I prowled. Then I left the litter.",
  tarantula: "I sat. Then I left the silk.",
  widow: "I hung. Then I left the corner.",
  harvestman: "I walked. Then I left the stem.",
  scorpion: "I raised. Then I left the bark.",
  vinegaroon: "I whipped. Then I left the sand.",
  tick: "I clasped. Then I left the hem.",
  solifuge: "I ran. Then I left the dish.",
  deer: "I flagged. Then I left the edge.",
  bat: "I hung. Then I left the fold.",
  squirrel: "I hid a thought. Then I left the dish.",
  otter: "I slid. Then I left the dish.",
  raccoon: "I washed. Then I left the bowl.",
  skunk: "I stamped. Then I left the duff.",
  opossum: "I went still. Then I left the hem.",
  beaver: "I gnawed. Then I left the lodge.",
  porcupine: "I bristled. Then I left the post.",
  black_bear: "I foraged. Then I left the denside.",
  gecko: "I climbed. Then I left the plaster.",
  anole: "I flashed. Then I left the post.",
  skink: "I dashed. Then I left the crack.",
  chameleon: "I shifted. Then I left the perch.",
  horned_lizard: "I sat the crown. Then I left the sand.",
  alligator: "I sat the bank. Then I left the dish.",
  crocodile: "I showed. Then I left the dish.",
  snapper: "I snapped. Then I left the mud.",
  box_turtle: "I shut. Then I left the leaf.",
  tuatara: "I kept still. Then I left the burrow.",
  bass: "I lunged. Then I left the edge.",
  brook_trout: "I rose. Then I left the riffle.",
  catfish: "I whisked. Then I left the mud.",
  bluegill: "I flared. Then I left the shade.",
  perch: "I kept the bars. Then I left the rail.",
  pike: "I waited. Then I left the reed.",
  walleye: "I hunted dusk. Then I left the run.",
  paddlefish: "I filtered. Then I left the current.",
  lamprey: "I sat the disk. Then I left the stone.",
  american_eel: "I swam. Then I left the hole.",
  house_centipede: "I hunted. Then I left the crack.",
  millipede: "I oiled. Then I left the log.",
  pillbug: "I rolled. Then I left the bark.",
  earthworm: "I cast. Then I left the soil.",
  velvet_worm: "I jetted. Then I left the wood.",
  springtail: "I hopped. Then I left the duff.",
  tardigrade: "I sat the moss. Then I left the film.",
  planarian: "I split. Then I left the film.",
  nematode: "I thrashed. Then I left the film.",
  amphipod: "I swam on my side. Then I left the pool.",
  fiddler_crab: "I waved. Then I left the marsh.",
  ghost_crab: "I ran. Then I left the sand.",
  limpet: "I clamped. Then I left the rim.",
  barnacle: "I sat the stone. Then I left the rim.",
  chiton: "I plated. Then I left the rock.",
  periwinkle: "I rasped. Then I left the face.",
  sand_dollar: "I sat the sand. Then I left the plate.",
  sea_urchin: "I sat the spines. Then I left the pool.",
  knobbed_whelk: "I hunted. Then I left the wrack.",
  lugworm: "I heaped. Then I left the sand.",
  field_cricket: "I sang. Then I left the grass.",
  katydid: "I sat the leaf. Then I left the rim.",
  grasshopper: "I vaulted. Then I left the grass.",
  swallowtail: "I kept the yellow. Then I left the blossom.",
  jewelwing: "I kept the black. Then I left the stream.",
  lacewing: "I laced. Then I left the leaf.",
  earwig: "I raised the cerci. Then I left the bark.",
  acorn_weevil: "I sat the acorn. Then I left the cup.",
  click_beetle: "I clicked. Then I left the bark.",
  robber_fly: "I hunted. Then I left the perch.",
  sloth: "I hung. Then I left the bough.",
  lemur: "I sat the sun. Then I left the troop.",
  gibbon: "I sang. Then I left the swing.",
  kinkajou: "I wrapped. Then I left the nectar.",
  colugo: "I sailed. Then I left the trunk.",
  flying_squirrel: "I glided. Then I left the oak.",
  howler: "I howled. Then I left the crown.",
  tarsier: "I looked. Then I left the branch.",
  potto: "I kept still. Then I left the vine.",
  koala: "I chewed. Then I left the gum.",
  brain_coral: "I sat the rock. Then I left the boulder.",
  anemone: "I opened. Then I left the column.",
  clownfish: "I sat the wreath. Then I left the cup.",
  parrotfish: "I rasped. Then I left the plate.",
  cleaner_shrimp: "I waited. Then I left the station.",
  sea_cucumber: "I sat the sand. Then I left the well.",
  lionfish: "I veiled. Then I left the ledge.",
  giant_clam: "I opened. Then I left the mantle.",
  eagle_ray: "I soared. Then I left the sky.",
  grouper: "I sat the hole. Then I left the dish.",
};

  function civilDay(now) {
    now = now || new Date();
    return Math.floor(Date.UTC(now.getFullYear(), now.getMonth(), now.getDate()) / 86400000);
  }

  function todaysVisitor(hostKey, keys, now) {
    const walk = keys && keys.length ? keys : CATALOG_KEYS;
    const others = walk.filter((key) => key !== hostKey);
    if (!others.length) return null;
    return others[Math.abs(civilDay(now) + String(hostKey || "").length) % others.length];
  }

  function visitLine(guestKey) {
    return VISIT_LINE[guestKey] || "I came. I saw the lamp. I left.";
  }

  function visitPhaseFromEnter(elapsedMs, hostHidden) {
    if (hostHidden) return "gone";
    if (elapsedMs < 0) return "wait";
    if (elapsedMs >= VISIT_GONE_MS) return "gone";
    if (elapsedMs >= VISIT_LEAVE_MS) return "leave";
    if (elapsedMs >= VISIT_WANDER_MS) return "wander";
    if (elapsedMs >= VISIT_TALK_MS) return "talk";
    return "in";
  }

  function visitPhaseFromWait(elapsedMs, hostHidden) {
    if (hostHidden) return "gone";
    if (elapsedMs < VISIT_WAIT_MS) return "wait";
    return visitPhaseFromEnter(elapsedMs - VISIT_WAIT_MS);
  }

  const api = {
    VISIT_WAIT_MS,
    VISIT_TALK_MS,
    VISIT_WANDER_MS,
    VISIT_LEAVE_MS,
    VISIT_GONE_MS,
    CATALOG_KEYS,
    VISIT_LINE,
    todaysVisitor,
    visitLine,
    visitPhaseFromEnter,
    visitPhaseFromWait,
  };
  if (typeof module !== "undefined" && module.exports) module.exports = api;
  root.PetVisitor = api;
})(typeof window !== "undefined" ? window : globalThis);
