"""Species-true idle acts — same map as web ``ethogram.ts`` and Electron ``ethogram.js``."""

from __future__ import annotations

import math
import random
from typing import TypedDict

from .species import SNAKE_KEYS


class IdleAct(TypedDict, total=False):
    name: str
    motion: str
    hold: float
    weight: float
    anim: str


def _a(name: str, motion: str, hold: float, weight: float, anim: str | None = None) -> IdleAct:
    act: IdleAct = {"name": name, "motion": motion, "hold": hold, "weight": weight}
    if anim:
        act["anim"] = anim
    return act


_PREEN: tuple[IdleAct, ...] = (
    _a("preen", "groom", 1.4, 3, "sit"),
    _a("hop_step", "hop", 0.5, 2, "play"),
    _a("wings", "pulse", 0.7, 1, "play"),
)

ETHOGRAM: dict[str, tuple[IdleAct, ...]] = {
    "dog": (_a("wait", "sit_hold", 2.0, 4, "sit"), _a("wag_soft", "wiggle", 1.0, 3, "play"), _a("sniff_soft", "bob", 0.9, 2, "sit"), _a("bow_soft", "stretch", 1.0, 2, "sit"), _a("zoom_soft", "hop", 0.8, 2, "play"), _a("beg_soft", "rise", 0.8, 2, "sit"), _a("pant_soft", "nod", 0.8, 2, "sit"), _a("scratch", "scratch", 1.1, 2, "sit")),
    "cat": (_a("loaf", "sit_hold", 2.0, 4, "sit"), _a("knead_soft", "wiggle", 1.0, 3, "play"), _a("wash_soft", "groom", 0.9, 2, "sit"), _a("pounce_soft", "hop", 0.8, 2, "play"), _a("bunting_soft", "bob", 0.8, 2, "sit"), _a("mlem_soft", "nod", 0.8, 2, "sit"), _a("scratch", "scratch", 1.1, 2, "sit"), _a("alert", "freeze", 1.6, 2, "sit")),
    "fox": (_a("den", "sit_hold", 2.4, 4, "sit"), _a("mouser_soft", "hop", 1.2, 2, "play"), _a("stalk_soft", "bob", 1.2, 2, "sit"), _a("trot_soft", "wiggle", 1.2, 2, "play"), _a("prance_soft", "hop", 1.2, 2, "play"), _a("cock_soft", "nod", 1.2, 2, "sit"), _a("stash_soft", "wiggle", 1.2, 2, "sit"), _a("freeze", "freeze", 1.4, 2)),
    "red_panda": (_a("groom", "groom", 1.5, 3, "sit"), _a("scratch", "scratch", 1.1, 2, "sit"), _a("steal_dart", "dart", 1.2, 2), _a("wash", "groom", 1.3, 2, "sit")),
    "rabbit": (_a("flop", "sit_hold", 2.0, 4, "sit"), _a("groom_soft", "groom", 1.0, 3, "sit"), _a("peri_soft", "rise", 0.9, 2, "sit"), _a("dig_soft", "wiggle", 0.9, 2, "sit"), _a("binky_soft", "hop", 0.8, 2, "play"), _a("rub_soft", "lean", 0.8, 2, "sit"), _a("nosh_soft", "eat", 0.8, 2, "eat"), _a("freeze", "freeze", 1.4, 2)),
    "hamster": (_a("nest", "sit_hold", 2.4, 4, "sit"), _a("cheek_soft", "wiggle", 1.2, 2, "sit"), _a("scurry_soft", "dart", 1.2, 2, "play"), _a("pocket_soft", "lean", 1.2, 2, "sit"), _a("reel_soft", "hop", 1.2, 2, "play"), _a("scrub_soft", "groom", 1.2, 2, "sit"), _a("seed_soft", "eat", 1.2, 2, "eat"), _a("freeze", "freeze", 1.4, 2)),

    "guinea_pig": (_a("potato", "sit_hold", 2.4, 4, "sit"), _a("hay_soft", "eat", 1.2, 2, "eat"), _a("rumble_soft", "wiggle", 1.2, 2, "sit"), _a("popcorn_soft", "hop", 1.2, 2, "play"), _a("zig_soft", "dart", 1.2, 2, "play"), _a("lookout_soft", "rise", 1.2, 2, "sit"), _a("teeth_soft", "talk", 1.2, 2, "talk"), _a("freeze", "freeze", 1.4, 2)),
    "ferret": (_a("tube", "sit_hold", 2.4, 4, "sit"), _a("romp_soft", "hop", 1.2, 2, "play"), _a("steal_soft", "walk", 1.2, 2, "sit"), _a("puff_soft", "sit", 1.2, 2, "sit"), _a("noodle_soft", "wiggle", 1.2, 2, "play"), _a("corkscrew_soft", "hop", 1.2, 2, "play"), _a("slink_soft", "walk", 1.2, 2, "sit"), _a("freeze", "freeze", 1.4, 2)),
    "hedgehog": (_a("curl", "sit_hold", 2.4, 4, "sit"), _a("snuffle_soft", "wiggle", 1.2, 2, "sit"), _a("anoint_soft", "sit", 1.2, 2, "sit"), _a("bristle_soft", "sit", 1.2, 2, "sit"), _a("root_soft", "play", 1.2, 2, "play"), _a("trundle_soft", "walk", 1.2, 2, "sit"), _a("wheel_soft", "hop", 1.2, 2, "play"), _a("freeze", "freeze", 1.4, 2)),
    "chinchilla": (_a("ash", "sit_hold", 2.4, 4, "sit"), _a("bound_soft", "hop", 1.2, 2, "play"), _a("fluff_soft", "groom", 1.2, 2, "sit"), _a("chin_soft", "sit", 1.2, 2, "sit"), _a("sift_soft", "shake", 1.2, 2, "play"), _a("ricochet_soft", "hop", 1.2, 2, "play"), _a("gnaw_soft", "sit", 1.2, 2, "sit"), _a("freeze", "freeze", 1.4, 2)),
    "turtle": (_a("soak", "sit_hold", 2.4, 4, "sit"), _a("tuck_soft", "curl", 1.2, 2, "sit"), _a("crane_soft", "rise", 1.2, 2, "sit"), _a("plod_soft", "dart", 1.2, 2, "play"), _a("paddle_soft", "wiggle", 1.2, 2, "play"), _a("snorkel_soft", "rise", 1.2, 2, "sit"), _a("wipe_soft", "groom", 1.2, 2, "sit"), _a("freeze", "freeze", 1.4, 2)),
    "iguana": (_a("sun", "sit_hold", 2.4, 4, "sit"), _a("dewlap_soft", "sit", 1.2, 2, "sit"), _a("nod_soft", "bob", 1.2, 2, "talk"), _a("press_soft", "play", 1.2, 2, "play"), _a("flick_soft", "sit", 1.2, 2, "sit"), _a("sneeze_soft", "sit", 1.2, 2, "sit"), _a("lash_soft", "shake", 1.2, 2, "play"), _a("freeze", "freeze", 1.4, 2)),
    "dragon": (_a("sprawl", "sit_hold", 2.4, 4, "sit"), _a("guard_soft", "sit", 1.2, 2, "sit"), _a("smolder_soft", "pulse", 1.2, 2, "sit"), _a("claim_soft", "play", 1.2, 2, "play"), _a("fold_soft", "play", 1.2, 2, "sit"), _a("ruff_soft", "sit", 1.2, 2, "talk"), _a("scrape_soft", "scratch", 1.2, 2, "play"), _a("freeze", "freeze", 1.4, 2)),
    "axolotl": (_a("gill", "sit_hold", 2.4, 4, "sit"), _a("amble_soft", "walk", 1.2, 2, "play"), _a("mend_soft", "sit", 1.2, 2, "sit"), _a("smile_soft", "sit", 1.2, 2, "sit"), _a("plume_soft", "shake", 1.2, 2, "play"), _a("sprout_soft", "play", 1.2, 2, "play"), _a("glop_soft", "sit", 1.2, 2, "sit"), _a("freeze", "freeze", 1.4, 2)),
    "budgie": (_a("preen", "sit_hold", 2.4, 4, "sit"), _a("bobble_soft", "bob", 1.2, 2, "sit"), _a("mimic_soft", "talk", 1.2, 2, "talk"), _a("sidle_soft", "hop", 1.2, 2, "play"), _a("dangle_soft", "pulse", 1.2, 2, "play"), _a("beakgrind_soft", "lean", 1.2, 2, "play"), _a("shellout_soft", "wiggle", 1.2, 2, "play"), _a("freeze", "freeze", 1.4, 2)),
    "parrot": (_a("quote", "sit_hold", 2.4, 4, "sit"), _a("strut_soft", "wiggle", 1.2, 2, "play"), _a("fan_soft", "pulse", 1.2, 2, "play"), _a("crack_soft", "nod", 1.2, 2, "sit"), _a("flash_soft", "hop", 1.2, 2, "play"), _a("pineye_soft", "bob", 1.2, 2, "sit"), _a("invert_soft", "lean", 1.2, 2, "play"), _a("freeze", "freeze", 1.4, 2)),
    "toucan": (_a("roost", "sit_hold", 2.4, 4, "sit"), _a("berry_soft", "nod", 1.2, 2, "sit"), _a("juggle_soft", "pulse", 1.2, 2, "play"), _a("peer_soft", "bob", 1.2, 2, "sit"), _a("skip_soft", "hop", 1.2, 2, "play"), _a("rattle_soft", "talk", 1.2, 2, "talk"), _a("clatter_soft", "sit", 1.2, 2, "sit"), _a("freeze", "freeze", 1.4, 2)),
    "phoenix": (_a("cinder", "sit_hold", 2.4, 4, "sit"), _a("blaze_soft", "pulse", 1.2, 2, "play"), _a("shed_soft", "wiggle", 1.2, 2, "play"), _a("lift_soft", "pulse", 1.2, 2, "play"), _a("return_soft", "bob", 1.2, 2, "sit"), _a("reignite_soft", "talk", 1.2, 2, "talk"), _a("hearth_soft", "sit", 1.2, 2, "sit"), _a("freeze", "freeze", 1.4, 2)),
    "penguin": (_a("huddle", "sit_hold", 2.4, 4, "sit"), _a("toboggan_soft", "pulse", 1.2, 2, "play"), _a("waddle_soft", "wiggle", 1.2, 2, "play"), _a("porpoise_soft", "lean", 1.2, 2, "play"), _a("trumpet_soft", "talk", 1.2, 2, "talk"), _a("rockhop_soft", "hop", 1.2, 2, "play"), _a("ecstatic_soft", "bob", 1.2, 2, "play"), _a("freeze", "freeze", 1.4, 2)),
    "goldfish": (_a("drift", "sit_hold", 2.4, 4, "sit"), _a("gulp_soft", "gulp", 1.2, 2, "talk"), _a("flare_soft", "pulse", 1.2, 2, "play"), _a("glint_soft", "lean", 1.2, 2, "sit"), _a("dart_soft", "dart", 1.2, 2, "play"), _a("yawn_soft", "yawn", 1.2, 2, "sit"), _a("forage_soft", "eat", 1.2, 2, "eat"), _a("freeze", "freeze", 1.4, 2)),
    "ball_python": (_a("tongue", "tongue", 0.7, 4), _a("orb", "sit_hold", 2.4, 4, "sit"), _a("nook_soft", "sit", 1.2, 2, "sit"), _a("taste_soft", "talk", 1.2, 2, "talk"), _a("inch_soft", "play", 1.2, 2, "play"), _a("unroll_soft", "play", 1.2, 2, "play"), _a("loom_soft", "sit", 1.2, 2, "talk"), _a("weave_soft", "play", 1.2, 2, "play"), _a("freeze", "freeze", 1.4, 2)),
    "corn_snake": (_a("tongue", "tongue", 0.7, 4), _a("comma", "sit_hold", 2.4, 4, "sit"), _a("gap_soft", "sit", 1.2, 2, "sit"), _a("probe_soft", "tongue", 1.2, 2, "talk"), _a("scribble_soft", "play", 1.2, 2, "play"), _a("canyon_soft", "play", 1.2, 2, "play"), _a("blotter_soft", "sit", 1.2, 2, "talk"), _a("pencil_soft", "play", 1.2, 2, "play"), _a("freeze", "freeze", 1.4, 2)),
    "kingsnake": (_a("tongue", "tongue", 0.7, 4), _a("verdict", "sit_hold", 2.4, 4, "sit"), _a("audit_soft", "sit", 1.2, 2, "sit"), _a("stripe_soft", "play", 1.2, 2, "play"), _a("plumb_soft", "sit", 1.2, 2, "talk"), _a("raid_soft", "play", 1.2, 2, "play"), _a("band_soft", "play", 1.2, 2, "play"), _a("drawer_soft", "sit", 1.2, 2, "talk"), _a("freeze", "freeze", 1.4, 2)),
    "green_tree_python": (_a("tongue", "tongue", 0.7, 4), _a("bracelet", "sit_hold", 2.6, 4, "sit"), _a("sway_soft", "play", 1.2, 2, "play"), _a("jewel_soft", "sit", 1.2, 2, "sit"), _a("heat_soft", "sit", 1.2, 2, "talk"), _a("bough_soft", "play", 1.2, 2, "play"), _a("liana_soft", "play", 1.2, 2, "play"), _a("arbor_soft", "sit", 1.2, 2, "talk"), _a("freeze", "freeze", 1.4, 2)),
    "hognose": (_a("tongue", "tongue", 0.7, 4), _a("flatten", "sit_hold", 2.6, 4, "sit"), _a("playdead", "sit_hold", 2.6, 3, "sit"), _a("gape", "gape", 1.2, 2, "talk"), _a("shovel_soft", "sit", 1.2, 2, "talk"), _a("encore_soft", "play", 1.2, 2, "play"), _a("quiver_soft", "play", 1.2, 2, "play"), _a("upright_soft", "sit", 1.2, 2, "sit"), _a("freeze", "freeze", 1.4, 2)),
    "garter": (_a("tongue", "tongue", 0.7, 4), _a("seam", "sit_hold", 2.6, 4, "sit"), _a("rounds_soft", "wiggle", 1.2, 2), _a("moss_soft", "sit", 1.2, 2, "sit"), _a("fork_soft", "talk", 1.2, 2, "talk"), _a("ribbon_soft", "play", 1.2, 2, "play"), _a("creek_soft", "wiggle", 1.2, 2), _a("freeze", "freeze", 1.4, 2)),
    "boa": (_a("tongue", "tongue", 0.7, 4), _a("hold", "sit_hold", 2.8, 4, "sit"), _a("pour_soft", "sit", 1.2, 2, "sit"), _a("heft_soft", "sit", 1.2, 2, "sit"), _a("oxbow_soft", "wiggle", 1.2, 2), _a("anchor_soft", "sit", 1.2, 2, "sit"), _a("meander_soft", "wiggle", 1.2, 2), _a("freeze", "freeze", 1.5, 2)),
    "milk_snake": (_a("tongue", "tongue", 0.7, 4), _a("rhyme", "sit_hold", 2.4, 4, "sit"), _a("rumor_soft", "talk", 1.2, 2, "talk"), _a("costume_soft", "sit", 1.2, 2, "sit"), _a("cipher_soft", "sit", 1.2, 2, "sit"), _a("verse_soft", "talk", 1.2, 2, "talk"), _a("tile_soft", "play", 1.2, 2, "play"), _a("freeze", "freeze", 1.4, 2)),
    "rosy_boa": (_a("tongue", "tongue", 0.7, 4), _a("pebble", "sit_hold", 2.4, 4, "sit"), _a("crevice_soft", "wiggle", 1.2, 2), _a("rosy_soft", "play", 1.2, 2, "play"), _a("mesa_soft", "sit", 1.2, 2, "sit"), _a("dune_soft", "walk", 1.2, 2), _a("talus_soft", "sit", 1.2, 2, "sit"), _a("freeze", "freeze", 1.4, 2)),
    "carpet_python": (_a("tongue", "tongue", 0.7, 4), _a("legend", "sit_hold", 2.4, 4, "sit"), _a("rung_soft", "play", 1.2, 2, "play"), _a("contour_soft", "walk", 1.2, 2), _a("runner_soft", "walk", 1.2, 2), _a("canopy_soft", "play", 1.2, 2, "play"), _a("inset_soft", "sit", 1.2, 2, "sit"), _a("freeze", "freeze", 1.4, 2)),
    "octopus": (_a("hide", "sit_hold", 2.4, 4, "sit"), _a("sucker_soft", "walk", 1.2, 2), _a("jet_soft", "dart", 1.2, 2), _a("veil_soft", "play", 1.2, 2, "play"), _a("tinker_soft", "play", 1.2, 2, "play"), _a("papilla_soft", "sit", 1.2, 2, "sit"), _a("ooze_soft", "walk", 1.2, 2), _a("freeze", "freeze", 1.4, 2)),
    "cuttlefish": (_a("bone", "sit_hold", 2.4, 4, "sit"), _a("pupil_soft", "talk", 1.2, 2, "talk"), _a("chroma_soft", "play", 1.2, 2, "play"), _a("hover_soft", "walk", 1.2, 2), _a("blot_soft", "play", 1.2, 2, "play"), _a("strike_soft", "walk", 1.2, 2), _a("zebra_soft", "play", 1.2, 2, "play"), _a("freeze", "freeze", 1.4, 2)),
    "nautilus": (_a("spiral", "sit_hold", 2.4, 4, "sit"), _a("siphuncle_soft", "walk", 1.2, 2), _a("nacre_soft", "sit", 1.2, 2, "sit"), _a("pinhole_soft", "talk", 1.2, 2, "talk"), _a("fringe_soft", "play", 1.2, 2, "play"), _a("hyponome_soft", "walk", 1.2, 2), _a("aperture_soft", "play", 1.2, 2, "play"), _a("freeze", "freeze", 1.4, 2)),
    "moon_jelly": (_a("bell", "sit_hold", 2.4, 4, "sit"), _a("oral_soft", "talk", 1.2, 2, "talk"), _a("lucent_soft", "sit", 1.2, 2, "sit"), _a("trail_soft", "play", 1.2, 2, "play"), _a("medusa_soft", "walk", 1.2, 2), _a("rhopalium_soft", "talk", 1.2, 2, "talk"), _a("horseshoe_soft", "play", 1.2, 2, "play"), _a("freeze", "freeze", 1.4, 2)),
    "sea_star": (_a("cling", "sit_hold", 2.4, 4, "sit"), _a("righting_soft", "play", 1.2, 2, "play"), _a("crawl_soft", "walk", 1.2, 2), _a("evert_soft", "talk", 1.2, 2, "talk"), _a("penta_soft", "sit", 1.2, 2, "sit"), _a("madre_soft", "talk", 1.2, 2, "talk"), _a("papula_soft", "play", 1.2, 2, "play"), _a("freeze", "freeze", 1.4, 2)),
    "hermit_crab": (_a("withdraw", "sit_hold", 2.4, 4, "sit"), _a("swap_soft", "play", 1.2, 2, "play"), _a("antenna_soft", "talk", 1.2, 2, "talk"), _a("scuttle_soft", "walk", 1.2, 2), _a("vacancy_soft", "walk", 1.2, 2), _a("chela_soft", "play", 1.2, 2, "play"), _a("bailer_soft", "talk", 1.2, 2, "talk"), _a("freeze", "freeze", 1.4, 2)),
    "horseshoe_crab": (_a("carapace", "sit_hold", 2.4, 4, "sit"), _a("bookgill_soft", "talk", 1.2, 2, "talk"), _a("telson_soft", "play", 1.2, 2, "play"), _a("furrow_soft", "walk", 1.2, 2), _a("fossil_soft", "sit", 1.2, 2, "sit"), _a("pusher_soft", "walk", 1.2, 2), _a("ocular_soft", "talk", 1.2, 2, "talk"), _a("freeze", "freeze", 1.4, 2)),
    "seahorse": (_a("coil", "sit_hold", 2.4, 4, "sit"), _a("buoy_soft", "play", 1.2, 2, "play"), _a("siphon_soft", "talk", 1.2, 2, "talk"), _a("swivel_soft", "talk", 1.2, 2, "talk"), _a("pouch_soft", "sit", 1.2, 2, "sit"), _a("dorsal_soft", "walk", 1.2, 2), _a("pectoral_soft", "talk", 1.2, 2, "talk"), _a("freeze", "freeze", 1.4, 2)),
    "manta": (_a("span", "sit_hold", 2.4, 4, "sit"), _a("wing_soft", "walk", 1.2, 2), _a("lobe_soft", "talk", 1.2, 2, "talk"), _a("gyre_soft", "play", 1.2, 2, "play"), _a("vault_soft", "play", 1.2, 2, "play"), _a("breach_soft", "play", 1.25, 2, "play"), _a("ram_soft", "talk", 1.2, 2, "talk"), _a("freeze", "freeze", 1.4, 2)),
    "moray": (_a("jamb", "sit_hold", 2.4, 4, "sit"), _a("hinge_soft", "talk", 1.2, 2, "talk"), _a("pharynx_soft", "play", 1.2, 2, "play"), _a("knot_soft", "play", 1.2, 2, "play"), _a("lurk_soft", "talk", 1.2, 2, "talk"), _a("mucus_soft", "sit", 1.2, 2, "sit"), _a("sentry_soft", "talk", 1.2, 2, "talk"), _a("freeze", "freeze", 1.4, 2)),
    "moss": (_a("thatch", "sit_hold", 2.4, 4, "sit"), _a("tuft_soft", "talk", 1.2, 2, "talk"), _a("bead_soft", "talk", 1.2, 2, "talk"), _a("spore_soft", "play", 1.2, 2, "play"), _a("cushion_soft", "sit", 1.2, 2, "sit"), _a("rhizoid_soft", "sit", 1.2, 2, "sit"), _a("seta_soft", "play", 1.2, 2, "play"), _a("freeze", "freeze", 1.4, 2)),
    "maidenhair": (_a("saucer", "sit_hold", 2.4, 4, "sit"), _a("frond_soft", "sit", 1.2, 2, "sit"), _a("rachis_soft", "talk", 1.2, 2, "talk"), _a("fiddle_soft", "play", 1.2, 2, "play"), _a("pinna_soft", "talk", 1.2, 2, "talk"), _a("sori_soft", "play", 1.2, 2, "play"), _a("stipe_soft", "talk", 1.2, 2, "talk"), _a("freeze", "freeze", 1.4, 2)),
    "ginkgo": (_a("amber", "sit_hold", 2.4, 4, "sit"), _a("biloba_soft", "sit", 1.2, 2, "sit"), _a("notch_soft", "talk", 1.2, 2, "talk"), _a("flutter_soft", "play", 1.2, 2, "play"), _a("drop_soft", "talk", 1.2, 2, "talk"), _a("dichotomy_soft", "play", 1.2, 2, "play"), _a("petiole_soft", "talk", 1.2, 2, "talk"), _a("freeze", "freeze", 1.4, 2)),
    "oak": (_a("bole", "sit_hold", 2.4, 4, "sit"), _a("acorn_soft", "talk", 1.2, 2, "talk"), _a("sinus_soft", "sit", 1.2, 2, "sit"), _a("gall_soft", "talk", 1.2, 2, "talk"), _a("taproot_soft", "play", 1.2, 2, "play"), _a("catkin_soft", "play", 1.2, 2, "play"), _a("tyloses_soft", "talk", 1.2, 2, "talk"), _a("freeze", "freeze", 1.4, 2)),
    "water_lily": (_a("sheen", "sit_hold", 2.4, 4, "sit"), _a("pad_soft", "sit", 1.2, 2, "sit"), _a("corolla_soft", "talk", 1.2, 2, "talk"), _a("rhizome_soft", "play", 1.2, 2, "play"), _a("calyx_soft", "talk", 1.2, 2, "talk"), _a("peltate_soft", "play", 1.2, 2, "play"), _a("hydropote_soft", "talk", 1.2, 2, "talk"), _a("freeze", "freeze", 1.4, 2)),
    "orchid": (_a("epiphyte", "sit_hold", 2.4, 4, "sit"), _a("labellum_soft", "sit", 1.2, 2, "sit"), _a("velamen_soft", "play", 1.2, 2, "play"), _a("column_soft", "talk", 1.15, 2, "talk"), _a("spike_soft", "talk", 1.15, 2, "talk"), _a("keiki_soft", "play", 1.2, 2, "play"), _a("pollinia_soft", "talk", 1.15, 2, "talk"), _a("freeze", "freeze", 1.4, 2)),
    "saguaro": (_a("sentinel", "sit_hold", 2.4, 4, "sit"), _a("rib_soft", "sit", 1.2, 2, "sit"), _a("branch_soft", "play", 1.2, 2, "play"), _a("nocturne_soft", "talk", 1.15, 2, "talk"), _a("areole_soft", "sit", 1.2, 2, "sit"), _a("pleat_soft", "play", 1.2, 2, "play"), _a("boot_soft", "talk", 1.15, 2, "talk"), _a("freeze", "freeze", 1.4, 2)),
    "venus_flytrap": (_a("poise", "sit_hold", 2.4, 4, "sit"), _a("clamp_soft", "play", 1.2, 2, "play"), _a("trichome_soft", "sit", 1.2, 2, "sit"), _a("stew_soft", "sit", 1.2, 2, "sit"), _a("unseal_soft", "talk", 1.15, 2, "talk"), _a("cage_soft", "play", 1.2, 2, "play"), _a("scape_soft", "talk", 1.15, 2, "talk"), _a("freeze", "freeze", 1.4, 2)),
    "pitcher": (_a("urn", "sit_hold", 2.4, 4, "sit"), _a("peristome_soft", "play", 1.2, 2, "play"), _a("cistern_soft", "sit", 1.2, 2, "sit"), _a("brine_soft", "sit", 1.2, 2, "sit"), _a("operculum_soft", "talk", 1.15, 2, "talk"), _a("ala_soft", "play", 1.2, 2, "play"), _a("baffle_soft", "talk", 1.15, 2, "talk"), _a("freeze", "freeze", 1.4, 2)),
    "sundew": (_a("rosette", "sit_hold", 2.4, 4, "sit"), _a("mucilage_soft", "play", 1.2, 2, "play"), _a("tentacle_soft", "talk", 1.2, 2, "talk"), _a("digest_soft", "sit", 1.2, 2, "sit"), _a("gland_soft", "talk", 1.15, 2, "talk"), _a("lamina_soft", "play", 1.2, 2, "play"), _a("circinate_soft", "talk", 1.15, 2, "talk"), _a("freeze", "freeze", 1.4, 2)),
    "honeybee": (_a("hive", "sit_hold", 2.4, 4, "sit"), _a("figure_soft", "play", 1.2, 2, "play"), _a("corbicula_soft", "talk", 1.2, 2, "talk"), _a("hex_soft", "sit", 1.2, 2, "sit"), _a("proboscis_soft", "talk", 1.15, 2, "talk"), _a("ocelli_soft", "play", 1.2, 2, "play"), _a("nasonov_soft", "talk", 1.15, 2, "talk"), _a("freeze", "freeze", 1.4, 2)),
    "monarch": (_a("danaus", "sit_hold", 2.4, 4, "sit"), _a("asclepias_soft", "talk", 1.2, 2, "talk"), _a("oyamel_soft", "sit", 1.2, 2, "sit"), _a("warning_soft", "play", 1.2, 2, "play"), _a("chrysalis_soft", "sit", 1.2, 2, "sit"), _a("cremaster_soft", "talk", 1.15, 2, "talk"), _a("tarsus_soft", "play", 1.2, 2, "play"), _a("freeze", "freeze", 1.4, 2)),
    "luna": (_a("actias", "sit_hold", 2.4, 4, "sit"), _a("plumose_soft", "talk", 1.2, 2, "talk"), _a("lunule_soft", "play", 1.2, 2, "play"), _a("silk_soft", "sit", 1.2, 2, "sit"), _a("stream_soft", "sit", 1.2, 2, "sit"), _a("aphagy_soft", "talk", 1.15, 2, "talk"), _a("cauda_soft", "play", 1.2, 2, "play"), _a("freeze", "freeze", 1.4, 2)),
    "firefly": (_a("photinus", "sit_hold", 2.4, 4, "sit"), _a("lantern_soft", "play", 1.2, 2, "play"), _a("jstroke_soft", "sit", 1.2, 2, "sit"), _a("semaphore_soft", "talk", 1.2, 2, "talk"), _a("elytra_soft", "sit", 1.2, 2, "sit"), _a("photocyte_soft", "play", 1.2, 2, "play"), _a("sternite_soft", "talk", 1.15, 2, "talk"), _a("freeze", "freeze", 1.4, 2)),
    "darner": (_a("anax", "sit_hold", 2.4, 4, "sit"), _a("hawking_soft", "play", 1.2, 2, "play"), _a("tandem_soft", "sit", 1.2, 2, "sit"), _a("nymph_soft", "sit", 1.2, 2, "sit"), _a("whir_soft", "talk", 1.2, 2, "talk"), _a("obelisk_soft", "sit", 1.15, 2, "sit"), _a("ommatidia_soft", "talk", 1.2, 2, "talk"), _a("freeze", "freeze", 1.4, 2)),
    "stick": (_a("diapheromera", "sit_hold", 2.4, 4, "sit"), _a("rocking_soft", "sit", 1.2, 2, "sit"), _a("catalepsy_soft", "sit", 1.2, 2, "sit"), _a("browse_soft", "sit", 1.2, 2, "sit"), _a("tread_soft", "walk", 1.2, 2, "walk"), _a("oviposit_soft", "sit", 1.15, 2, "sit"), _a("filiform_soft", "talk", 1.2, 2, "talk"), _a("freeze", "freeze", 1.4, 2)),
    "carpenter_ant": (_a("camponotus", "sit_hold", 2.4, 4, "sit"), _a("gallery_soft", "sit", 1.2, 2, "sit"), _a("pheromone_soft", "walk", 1.2, 2, "walk"), _a("crumb_soft", "walk", 1.2, 2, "walk"), _a("bustle_soft", "walk", 1.2, 2, "walk"), _a("trophallaxis_soft", "talk", 1.15, 2, "talk"), _a("frass_soft", "sit", 1.2, 2, "sit"), _a("freeze", "freeze", 1.4, 2)),
    "ladybird": (_a("coccinella", "sit_hold", 2.4, 4, "sit"), _a("spots_soft", "sit", 1.2, 2, "sit"), _a("aphid_soft", "walk", 1.2, 2, "walk"), _a("reflex_soft", "sit", 1.15, 2, "sit"), _a("climb_soft", "walk", 1.2, 2, "walk"), _a("pronotum_soft", "sit", 1.2, 2, "sit"), _a("alar_soft", "play", 1.2, 2, "play"), _a("freeze", "freeze", 1.4, 2)),
    "mantis": (_a("mantodea", "sit_hold", 2.4, 4, "sit"), _a("raptorial_soft", "sit", 1.2, 2, "sit"), _a("gimbal_soft", "sit", 1.15, 2, "sit"), _a("snatch_soft", "play", 1.2, 2, "play"), _a("pendulum_soft", "sit", 1.2, 2, "sit"), _a("ootheca_soft", "sit", 1.2, 2, "sit"), _a("deimatic_soft", "play", 1.2, 2, "play"), _a("freeze", "freeze", 1.4, 2)),
    "cicada": (_a("magicicada", "sit_hold", 2.4, 4, "sit"), _a("tymbal_soft", "talk", 1.2, 2, "talk"), _a("cast_soft", "sit", 1.2, 2, "sit"), _a("egress_soft", "play", 1.2, 2, "play"), _a("harden_soft", "sit", 1.2, 2, "sit"), _a("xylem_soft", "sit", 1.2, 2, "sit"), _a("pharaoh_soft", "play", 1.2, 2, "play"), _a("freeze", "freeze", 1.4, 2)),
    "bumblebee": (_a("bombus", "sit_hold", 2.4, 4, "sit"), _a("sonicate_soft", "talk", 1.2, 2, "talk"), _a("scopa_soft", "talk", 1.2, 2, "talk"), _a("fossor_soft", "play", 1.2, 2, "play"), _a("lumber_soft", "play", 1.2, 2, "play"), _a("thoraxload_soft", "sit", 1.15, 2, "sit"), _a("corbicularub_soft", "talk", 1.2, 2, "talk"), _a("freeze", "freeze", 1.4, 2)),
    "carpenter_bee": (_a("xylocopa", "sit_hold", 2.4, 4, "sit"), _a("rasp_soft", "play", 1.2, 2, "play"), _a("glabrous_soft", "talk", 1.2, 2, "talk"), _a("partition_soft", "play", 1.15, 2, "play"), _a("picket_soft", "play", 1.2, 2, "play"), _a("tunnelrasp_soft", "play", 1.2, 2, "play"), _a("baldflash_soft", "talk", 1.2, 2, "talk"), _a("freeze", "freeze", 1.4, 2)),
    "mason_bee": (_a("osmia", "sit_hold", 2.4, 4, "sit"), _a("trowel_soft", "play", 1.2, 2, "play"), _a("beebread_soft", "play", 1.15, 2, "play"), _a("orchard_soft", "talk", 1.2, 2, "talk"), _a("plug_soft", "play", 1.2, 2, "play"), _a("mudseptum_soft", "play", 1.2, 2, "play"), _a("tubeprovision_soft", "play", 1.2, 2, "play"), _a("freeze", "freeze", 1.4, 2)),
    "leafcutter": (_a("megachile", "sit_hold", 2.4, 4, "sit"), _a("circle_soft", "play", 1.2, 2, "play"), _a("liner_soft", "play", 1.15, 2, "play"), _a("cavity_soft", "talk", 1.2, 2, "talk"), _a("parcel_soft", "talk", 1.2, 2, "talk"), _a("discpress_soft", "play", 1.2, 2, "play"), _a("cellcup_soft", "play", 1.2, 2, "play"), _a("freeze", "freeze", 1.4, 2)),
    "stingless": (_a("melipona", "sit_hold", 2.4, 4, "sit"), _a("cerumen_soft", "play", 1.2, 2, "play"), _a("spout_soft", "play", 1.15, 2, "play"), _a("vessel_soft", "talk", 1.2, 2, "talk"), _a("batumen_soft", "talk", 1.2, 2, "talk"), _a("potpress_soft", "play", 1.2, 2, "play"), _a("involucrum_soft", "play", 1.2, 2, "play"), _a("freeze", "freeze", 1.4, 2)),
    "sweat_bee": (_a("agapostemon", "sit_hold", 2.4, 4, "sit"), _a("lustre_soft", "play", 1.2, 2, "play"), _a("tumulus_soft", "talk", 1.2, 2, "talk"), _a("salt_soft", "talk", 1.15, 2, "talk"), _a("commune_soft", "sit", 1.2, 2, "sit"), _a("metallictilt_soft", "play", 1.2, 2, "play"), _a("nestmound_soft", "talk", 1.2, 2, "talk"), _a("freeze", "freeze", 1.4, 2)),
    "mining_bee": (_a("andrena", "sit_hold", 2.4, 4, "sit"), _a("shaft_soft", "play", 1.2, 2, "play"), _a("mass_soft", "talk", 1.2, 2, "talk"), _a("vernal_soft", "play", 1.15, 2, "play"), _a("fovea_soft", "talk", 1.2, 2, "talk"), _a("floccus_soft", "play", 1.2, 2, "play"), _a("dufourline_soft", "talk", 1.2, 2, "talk"), _a("freeze", "freeze", 1.4, 2)),
    "honey_drone": (_a("mellifera", "sit_hold", 2.4, 4, "sit"), _a("holoptic_soft", "play", 1.2, 2, "play"), _a("congregation_soft", "talk", 1.2, 2, "talk"), _a("sortie_soft", "talk", 1.15, 2, "talk"), _a("ocellus_soft", "sit", 1.2, 2, "sit"), _a("dronepatrol_soft", "play", 1.2, 2, "play"), _a("eyemeet_soft", "talk", 1.2, 2, "talk"), _a("freeze", "freeze", 1.4, 2)),
    "honey_queen": (_a("regina", "sit_hold", 2.4, 4, "sit"), _a("tooting_soft", "play", 1.2, 2, "play"), _a("retinue_soft", "talk", 1.2, 2, "talk"), _a("duel_soft", "play", 1.15, 2, "play"), _a("royal_soft", "talk", 1.2, 2, "talk"), _a("spermatheca_soft", "play", 1.2, 2, "play"), _a("queenmark_soft", "talk", 1.2, 2, "talk"), _a("freeze", "freeze", 1.4, 2)),
    "honeycomb": (_a("tessera", "sit_hold", 2.4, 4, "sit"), _a("festoon_soft", "play", 1.2, 2, "play"), _a("capped_soft", "talk", 1.2, 2, "talk"), _a("midrib_soft", "talk", 1.2, 2, "talk"), _a("stores_soft", "sit", 1.2, 2, "sit"), _a("alveoli_soft", "sit", 1.2, 2, "sit"), _a("foundation_soft", "play", 1.2, 2, "play"), _a("freeze", "freeze", 1.4, 2)),
    "oyster": (_a("pleurotus", "sit_hold", 2.4, 4, "sit"), _a("lamella_soft", "play", 1.2, 2, "play"), _a("imbricate_soft", "talk", 1.2, 2, "talk"), _a("lasso_soft", "talk", 1.2, 2, "talk"), _a("margin_soft", "sit", 1.2, 2, "sit"), _a("sporulate_soft", "sit", 1.2, 2, "sit"), _a("hypha_soft", "play", 1.2, 2, "play"), _a("freeze", "freeze", 1.4, 2)),
    "fly_agaric": (_a("amanita", "sit_hold", 2.4, 4, "sit"), _a("annulus_soft", "play", 1.2, 2, "play"), _a("volva_soft", "talk", 1.2, 2, "talk"), _a("flake_soft", "talk", 1.2, 2, "talk"), _a("symbiont_soft", "sit", 1.2, 2, "sit"), _a("pileus_soft", "sit", 1.2, 2, "sit"), _a("bulb_soft", "play", 1.2, 2, "play"), _a("freeze", "freeze", 1.4, 2)),
    "morel": (_a("morchella", "sit_hold", 2.4, 4, "sit"), _a("alveolus_soft", "play", 1.2, 2, "play"), _a("ridge_soft", "talk", 1.2, 2, "talk"), _a("ephemeral_soft", "talk", 1.2, 2, "talk"), _a("sclerotium_soft", "sit", 1.2, 2, "sit"), _a("costa_soft", "sit", 1.2, 2, "sit"), _a("hymenium_soft", "play", 1.2, 2, "play"), _a("freeze", "freeze", 1.4, 2)),
    "chanterelle": (_a("cantharellus", "sit_hold", 2.4, 4, "sit"), _a("apricot_soft", "play", 1.2, 2, "play"), _a("funnel_soft", "talk", 1.2, 2, "talk"), _a("decurrent_soft", "talk", 1.2, 2, "talk"), _a("flute_soft", "sit", 1.2, 2, "sit"), _a("vase_soft", "sit", 1.2, 2, "sit"), _a("plica_soft", "play", 1.2, 2, "play"), _a("freeze", "freeze", 1.4, 2)),
    "turkey_tail": (_a("trametes", "sit_hold", 2.4, 4, "sit"), _a("pore_soft", "play", 1.2, 2, "play"), _a("bracket_soft", "talk", 1.2, 2, "talk"), _a("zonate_soft", "talk", 1.2, 2, "talk"), _a("leathery_soft", "sit", 1.2, 2, "sit"), _a("concentric_soft", "sit", 1.2, 2, "sit"), _a("tomentum_soft", "play", 1.2, 2, "play"), _a("freeze", "freeze", 1.4, 2)),
    "lions_mane": (_a("hericium", "sit_hold", 2.4, 4, "sit"), _a("spine_soft", "play", 1.2, 2, "play"), _a("icicle_soft", "talk", 1.2, 2, "talk"), _a("cascade_soft", "talk", 1.2, 2, "talk"), _a("wound_soft", "sit", 1.2, 2, "sit"), _a("pompon_soft", "sit", 1.2, 2, "sit"), _a("hydnoid_soft", "play", 1.2, 2, "play"), _a("freeze", "freeze", 1.4, 2)),
    "puffball": (_a("lycoperdon", "sit_hold", 2.4, 4, "sit"), _a("ostiole_soft", "play", 1.2, 2, "play"), _a("gleba_soft", "talk", 1.2, 2, "talk"), _a("peridium_soft", "talk", 1.2, 2, "talk"), _a("duff_soft", "sit", 1.2, 2, "sit"), _a("gemmate_soft", "sit", 1.2, 2, "sit"), _a("capillitium_soft", "play", 1.2, 2, "play"), _a("freeze", "freeze", 1.4, 2)),
    "chicken_of_woods": (_a("laetiporus", "sit_hold", 2.4, 4, "sit"), _a("sulfur_soft", "play", 1.2, 2, "play"), _a("tier_soft", "talk", 1.2, 2, "talk"), _a("oak_soft", "talk", 1.2, 2, "talk"), _a("tender_soft", "sit", 1.2, 2, "sit"), _a("poroid_soft", "sit", 1.2, 2, "sit"), _a("cluster_soft", "play", 1.2, 2, "play"), _a("freeze", "freeze", 1.4, 2)),
    "yeast": (_a("saccharomyces", "sit_hold", 2.4, 4, "sit"), _a("bud_soft", "play", 1.2, 2, "play"), _a("proof_soft", "talk", 1.2, 2, "talk"), _a("levain_soft", "talk", 1.2, 2, "talk"), _a("ferment_soft", "sit", 1.2, 2, "sit"), _a("ascus_soft", "sit", 1.2, 2, "sit"), _a("floc_soft", "play", 1.2, 2, "play"), _a("freeze", "freeze", 1.4, 2)),
    "lichen": (_a("cladonia", "sit_hold", 2.4, 4, "sit"), _a("podetium_soft", "play", 1.2, 2, "play"), _a("photobiont_soft", "talk", 1.2, 2, "talk"), _a("fruticose_soft", "talk", 1.2, 2, "talk"), _a("stone_soft", "sit", 1.2, 2, "sit"), _a("soredia_soft", "sit", 1.2, 2, "sit"), _a("scyphi_soft", "play", 1.2, 2, "play"), _a("freeze", "freeze", 1.4, 2)),
    "photovore": (_a("photovore", "sit_hold", 2.4, 4, "sit"), _a("photon_soft", "play", 1.2, 2, "play"), _a("wavelength_soft", "talk", 1.2, 2, "talk"), _a("fluence_soft", "talk", 1.2, 2, "talk"), _a("glass_soft", "sit", 1.2, 2, "sit"), _a("opsin_soft", "sit", 1.2, 2, "sit"), _a("iridophore_soft", "play", 1.2, 2, "play"), _a("freeze", "freeze", 1.4, 2)),
    "choir": (_a("harmonia", "sit_hold", 2.4, 4, "sit"), _a("polyphony_soft", "play", 1.2, 2, "play"), _a("partial_soft", "talk", 1.2, 2, "talk"), _a("timbre_soft", "talk", 1.2, 2, "talk"), _a("resonance_soft", "sit", 1.2, 2, "sit"), _a("formant_soft", "sit", 1.2, 2, "sit"), _a("dyad_soft", "play", 1.2, 2, "play"), _a("freeze", "freeze", 1.4, 2)),
    "nimbus": (_a("stratus", "sit_hold", 2.4, 4, "sit"), _a("waft_soft", "play", 1.2, 2, "play"), _a("billow_soft", "talk", 1.2, 2, "talk"), _a("cirrus_soft", "talk", 1.2, 2, "talk"), _a("virga_soft", "sit", 1.2, 2, "sit"), _a("tholin_soft", "sit", 1.2, 2, "sit"), _a("nucleate_soft", "play", 1.2, 2, "play"), _a("freeze", "freeze", 1.4, 2)),
    "silica": (_a("crescit", "sit_hold", 2.4, 4, "sit"), _a("cleavage_soft", "play", 1.2, 2, "play"), _a("twinning_soft", "talk", 1.2, 2, "talk"), _a("inclusion_soft", "talk", 1.2, 2, "talk"), _a("grit_soft", "sit", 1.2, 2, "sit"), _a("hopper_soft", "sit", 1.2, 2, "sit"), _a("phantom_soft", "play", 1.2, 2, "play"), _a("freeze", "freeze", 1.4, 2)),
    "terminator": (_a("limitor", "sit_hold", 2.4, 4, "sit"), _a("belt_soft", "play", 1.2, 2, "play"), _a("penumbra_soft", "talk", 1.2, 2, "talk"), _a("eclipse_soft", "talk", 1.2, 2, "talk"), _a("limb_soft", "sit", 1.2, 2, "sit"), _a("umbra_soft", "sit", 1.2, 2, "sit"), _a("syzygy_soft", "play", 1.2, 2, "play"), _a("freeze", "freeze", 1.4, 2)),
    "nexus": (_a("mesh", "sit_hold", 2.4, 4, "sit"), _a("plexus_soft", "play", 1.2, 2, "play"), _a("splice_soft", "talk", 1.2, 2, "talk"), _a("braid_soft", "talk", 1.2, 2, "talk"), _a("weft_soft", "sit", 1.2, 2, "sit"), _a("fascicle_soft", "sit", 1.2, 2, "sit"), _a("sennit_soft", "play", 1.2, 2, "play"), _a("freeze", "freeze", 1.4, 2)),
    "halovore": (_a("deliquesce", "sit_hold", 2.4, 4, "sit"), _a("halite_soft", "play", 1.2, 2, "play"), _a("salina_soft", "talk", 1.2, 2, "talk"), _a("rime_soft", "talk", 1.2, 2, "talk"), _a("bittern_soft", "sit", 1.2, 2, "sit"), _a("ectoine_soft", "sit", 1.2, 2, "sit"), _a("sabkha_soft", "play", 1.2, 2, "play"), _a("freeze", "freeze", 1.4, 2)),
    "magneton": (_a("remanence", "sit_hold", 2.4, 4, "sit"), _a("lodestone_soft", "play", 1.2, 2, "play"), _a("flux_soft", "talk", 1.2, 2, "talk"), _a("azimuth_soft", "talk", 1.2, 2, "talk"), _a("dipole_soft", "sit", 1.2, 2, "sit"), _a("barkhausen_soft", "sit", 1.2, 2, "sit"), _a("hysteresis_soft", "play", 1.2, 2, "play"), _a("freeze", "freeze", 1.4, 2)),
    "umbral": (_a("caligo", "sit_hold", 2.4, 4, "sit"), _a("silhouette_soft", "play", 1.2, 2, "play"), _a("adumbrate_soft", "talk", 1.2, 2, "talk"), _a("occultation_soft", "talk", 1.2, 2, "talk"), _a("antumbra_soft", "sit", 1.2, 2, "sit"), _a("sfumato_soft", "sit", 1.2, 2, "sit"), _a("tenebrae_soft", "play", 1.2, 2, "play"), _a("freeze", "freeze", 1.4, 2)),
    "cyst": (_a("cryptobiosis", "sit_hold", 2.4, 4, "sit"), _a("lorica_soft", "play", 1.2, 2, "play"), _a("tegument_soft", "talk", 1.2, 2, "talk"), _a("ampoule_soft", "talk", 1.2, 2, "talk"), _a("bradyzoite_soft", "sit", 1.2, 2, "sit"), _a("sporocyst_soft", "sit", 1.2, 2, "sit"), _a("tachyzoite_soft", "play", 1.2, 2, "play"), _a("freeze", "freeze", 1.4, 2)),
    "frog": (_a("lentic", "sit_hold", 2.4, 4, "sit"), _a("gular_soft", "talk", 1.2, 2, "talk"), _a("nictitate_soft", "sit", 1.2, 2, "sit"), _a("tympanum_soft", "talk", 1.2, 2, "talk"), _a("iliac_soft", "play", 1.2, 2, "play"), _a("toepad_soft", "sit", 1.2, 2, "sit"), _a("webbing_soft", "play", 1.2, 2, "play"), _a("freeze", "freeze", 1.4, 2)),
    "toad": (_a("bufonid", "sit_hold", 2.4, 4, "sit"), _a("verruca_soft", "play", 1.2, 2, "play"), _a("burrow_soft", "sit", 1.2, 2, "sit"), _a("parotoid_soft", "sit", 1.2, 2, "sit"), _a("tubercle_soft", "play", 1.2, 2, "play"), _a("unken_soft", "play", 1.2, 2, "play"), _a("cranial_soft", "talk", 1.2, 2, "talk"), _a("freeze", "freeze", 1.4, 2)),
    "newt": (_a("caudate", "sit_hold", 2.4, 4, "sit"), _a("crest_soft", "play", 1.2, 2, "play"), _a("caudal_soft", "walk", 1.2, 2, "play"), _a("filament_soft", "sit", 1.2, 2, "sit"), _a("costal_soft", "walk", 1.2, 2, "play"), _a("hedonic_soft", "sit", 1.2, 2, "sit"), _a("aposematic_soft", "play", 1.2, 2, "play"), _a("freeze", "freeze", 1.4, 2)),
    "salamander": (_a("ambystomid", "sit_hold", 2.4, 4, "sit"), _a("maculate_soft", "play", 1.2, 2, "play"), _a("litter_soft", "walk", 1.2, 2, "play"), _a("cutaneous_soft", "sit", 1.2, 2, "sit"), _a("nasolabial_soft", "sit", 1.2, 2, "sit"), _a("mental_soft", "sit", 1.2, 2, "sit"), _a("granular_soft", "play", 1.2, 2, "play"), _a("freeze", "freeze", 1.4, 2)),
    "caecilian": (_a("gymnophion", "sit_hold", 2.4, 4, "sit"), _a("annulate_soft", "play", 1.2, 2, "play"), _a("fossorial_soft", "walk", 1.2, 2, "play"), _a("tentacular_soft", "sit", 1.2, 2, "sit"), _a("hydrostatic_soft", "play", 1.2, 2, "play"), _a("stegos_soft", "sit", 1.2, 2, "sit"), _a("dualjaw_soft", "play", 1.2, 2, "play"), _a("freeze", "freeze", 1.4, 2)),
    "crayfish": (_a("astacid", "sit_hold", 2.4, 4, "sit"), _a("chelate_soft", "play", 1.2, 2, "play"), _a("caridoid_soft", "play", 1.2, 2, "play"), _a("chimney_soft", "walk", 1.2, 2, "play"), _a("antennule_soft", "sit", 1.2, 2, "sit"), _a("scaph_soft", "sit", 1.2, 2, "sit"), _a("meral_soft", "play", 1.2, 2, "play"), _a("freeze", "freeze", 1.4, 2)),
    "pond_snail": (_a("lymnaeid", "sit_hold", 2.4, 4, "sit"), _a("radula_soft", "play", 1.2, 2, "play"), _a("pedal_soft", "walk", 1.2, 2, "play"), _a("pneumostome_soft", "sit", 1.2, 2, "sit"), _a("ommatophore_soft", "sit", 1.2, 2, "sit"), _a("odontophore_soft", "play", 1.2, 2, "play"), _a("neuston_soft", "walk", 1.2, 2, "play"), _a("freeze", "freeze", 1.4, 2)),
    "mussel": (_a("unionid", "sit_hold", 2.4, 4, "sit"), _a("adductor_soft", "play", 1.2, 2, "play"), _a("protractor_soft", "walk", 1.2, 2, "play"), _a("inhalant_soft", "sit", 1.2, 2, "sit"), _a("ctenidium_soft", "sit", 1.2, 2, "sit"), _a("ligament_soft", "play", 1.2, 2, "play"), _a("glochid_soft", "walk", 1.2, 2, "play"), _a("freeze", "freeze", 1.4, 2)),
    "leech": (_a("hirudinean", "sit_hold", 2.4, 4, "sit"), _a("acetabulum_soft", "sit", 1.2, 2, "sit"), _a("prostomium_soft", "play", 1.2, 2, "play"), _a("looping_soft", "walk", 1.2, 2, "play"), _a("undulatory_soft", "play", 1.2, 2, "play"), _a("botryoidal_soft", "play", 1.2, 2, "play"), _a("auricle_soft", "walk", 1.2, 2, "play"), _a("freeze", "freeze", 1.4, 2)),
    "stickleback": (_a("gasterosteid", "sit_hold", 2.4, 4, "sit"), _a("spiggin_soft", "sit", 1.2, 2, "sit"), _a("zigzag_soft", "walk", 1.2, 2, "play"), _a("spinous_soft", "play", 1.2, 2, "play"), _a("fanning_soft", "play", 1.2, 2, "play"), _a("nuptial_soft", "play", 1.2, 2, "play"), _a("pelvic_soft", "walk", 1.2, 2, "play"), _a("freeze", "freeze", 1.4, 2)),
    "paramecium": (_a("ciliophora", "sit_hold", 2.4, 4, "sit"), _a("cilia_soft", "sit", 1.2, 2, "sit"), _a("pellicle_soft", "walk", 1.2, 2, "play"), _a("cytostome_soft", "play", 1.2, 2, "play"), _a("vacuole_soft", "play", 1.2, 2, "play"), _a("trichocyst_soft", "play", 1.2, 2, "play"), _a("avoiding_soft", "walk", 1.2, 2, "play"), _a("freeze", "freeze", 1.4, 2)),
    "amoeba": (_a("proteus", "sit_hold", 2.4, 4, "sit"), _a("pseudopod_soft", "sit", 1.2, 2, "sit"), _a("ectoplasm_soft", "walk", 1.2, 2, "play"), _a("endoplasm_soft", "play", 1.2, 2, "play"), _a("foodcup_soft", "play", 1.2, 2, "play"), _a("uroid_soft", "play", 1.2, 2, "play"), _a("streaming_soft", "walk", 1.2, 2, "play"), _a("freeze", "freeze", 1.4, 2)),
    "euglena": (_a("euglenid", "sit_hold", 2.4, 4, "sit"), _a("eyespot_soft", "sit", 1.2, 2, "sit"), _a("flagellum_soft", "walk", 1.2, 2, "play"), _a("chloroplast_soft", "play", 1.2, 2, "play"), _a("phototaxis_soft", "play", 1.2, 2, "play"), _a("metaboly_soft", "play", 1.2, 2, "play"), _a("paramylon_soft", "walk", 1.2, 2, "play"), _a("freeze", "freeze", 1.4, 2)),
    "volvox": (_a("coenobium", "sit_hold", 2.4, 4, "sit"), _a("colony_soft", "walk", 1.2, 2, "play"), _a("inversion_soft", "play", 1.2, 2, "play"), _a("phialopore_soft", "sit", 1.2, 2, "sit"), _a("somatic_soft", "play", 1.2, 2, "play"), _a("daughter_soft", "sit", 1.2, 2, "sit"), _a("gonidia_soft", "walk", 1.2, 2, "play"), _a("freeze", "freeze", 1.4, 2)),
    "diatom": (_a("navicula", "sit_hold", 2.4, 4, "sit"), _a("frustule_soft", "walk", 1.2, 2, "play"), _a("raphe_soft", "play", 1.2, 2, "play"), _a("girdle_soft", "sit", 1.2, 2, "sit"), _a("oilstore_soft", "play", 1.2, 2, "play"), _a("pennate_soft", "sit", 1.2, 2, "sit"), _a("epitheca_soft", "walk", 1.2, 2, "play"), _a("freeze", "freeze", 1.4, 2)),

    "kelp": (_a("meristem", "sit_hold", 2.4, 4, "sit"), _a("holdfast_soft", "walk", 1.2, 2, "play"), _a("haptera_soft", "play", 1.2, 2, "play"), _a("blade_soft", "sit", 1.2, 2, "sit"), _a("pneumatocyst_soft", "play", 1.2, 2, "play"), _a("sorus_soft", "sit", 1.2, 2, "sit"), _a("sporophyll_soft", "walk", 1.2, 2, "play"), _a("freeze", "freeze", 1.4, 2)),
        "chlamydomonas": (_a("palmella", "sit_hold", 2.4, 4, "sit"), _a("biflagellate_soft", "walk", 1.2, 2, "play"), _a("cupplast_soft", "play", 1.2, 2, "play"), _a("stigma_soft", "sit", 1.2, 2, "sit"), _a("pyrenoid_soft", "play", 1.2, 2, "play"), _a("cellwall_soft", "sit", 1.2, 2, "sit"), _a("wetplate_soft", "walk", 1.2, 2, "play"), _a("freeze", "freeze", 1.4, 2)),
        "stentor": (_a("introversus", "sit_hold", 2.4, 4, "sit"), _a("adoral_soft", "open", 1.2, 2, "sit"), _a("myoneme_soft", "sit", 1.2, 2, "sit"), _a("membranelle_soft", "play", 1.2, 2, "play"), _a("holdfoot_soft", "sit", 1.2, 2, "sit"), _a("vortex_soft", "walk", 1.2, 2, "play"), _a("beadedmac_soft", "play", 1.2, 2, "play"), _a("freeze", "freeze", 1.4, 2)),
            "coli": (_a("nucleoid", "sit_hold", 2.4, 4, "sit"), _a("runandtumble_soft", "walk", 1.2, 2, "play"), _a("binaryfission_soft", "sit", 1.2, 2, "sit"), _a("pilus_soft", "play", 1.2, 2, "play"), _a("chemotax_soft", "sit", 1.2, 2, "sit"), _a("fimbria_soft", "walk", 1.2, 2, "play"), _a("flagmotor_soft", "play", 1.2, 2, "play"), _a("freeze", "freeze", 1.4, 2)),
        "haloarchaea": (_a("retinal", "sit_hold", 2.4, 4, "sit"), _a("bacteriorhodopsin_soft", "walk", 1.2, 2, "play"), _a("saltsquare_soft", "sit", 1.2, 2, "sit"), _a("gasvesicle_soft", "play", 1.2, 2, "play"), _a("carotenoid_soft", "sit", 1.2, 2, "sit"), _a("archaellum_soft", "walk", 1.2, 2, "play"), _a("brinedrift_soft", "play", 1.2, 2, "play"), _a("freeze", "freeze", 1.4, 2)),
"crow": (_a("corvid", "sit_hold", 2.4, 4, "sit"), _a("hopwalk_soft", "hop", 1.2, 2, "play"), _a("monocle_soft", "nod", 1.2, 2, "sit"), _a("fossick_soft", "wiggle", 1.2, 2, "sit"), _a("anting_soft", "pulse", 1.2, 2, "play"), _a("scrutinize_soft", "bob", 1.2, 2, "sit"), _a("glean_soft", "hop", 1.2, 2, "play"), _a("freeze", "freeze", 1.4, 2)),
    "raven": (_a("hackles", "sit_hold", 2.4, 4, "sit"), _a("dihedral_soft", "hop", 1.2, 2, "sit"), _a("billtap_soft", "nod", 1.2, 2, "sit"), _a("tumble_soft", "wiggle", 1.2, 2, "play"), _a("cronk_soft", "pulse", 1.2, 2, "talk"), _a("invite_soft", "bob", 1.2, 2, "play"), _a("toeing_soft", "hop", 1.2, 2, "sit"), _a("freeze", "freeze", 1.4, 2)),
    "barn_owl": (_a("tytonid", "sit_hold", 2.4, 4, "sit"), _a("diskturn_soft", "nod", 1.2, 2, "sit"), _a("softcrouch_soft", "lean", 1.2, 2, "sit"), _a("parallax_soft", "wiggle", 1.2, 2, "play"), _a("snore_soft", "pulse", 1.2, 2, "talk"), _a("twist_soft", "bob", 1.2, 2, "sit"), _a("pellet_soft", "hop", 1.2, 2, "play"), _a("freeze", "freeze", 1.4, 2)),
    "red_tail": (_a("buteo", "sit_hold", 2.4, 4, "sit"), _a("kettle_soft", "nod", 1.2, 2, "sit"), _a("stoop_soft", "lean", 1.2, 2, "sit"), _a("bind_soft", "wiggle", 1.2, 2, "play"), _a("keeyer_soft", "pulse", 1.2, 2, "talk"), _a("patagial_soft", "bob", 1.2, 2, "sit"), _a("tower_soft", "hop", 1.2, 2, "play"), _a("freeze", "freeze", 1.4, 2)),
    "chickadee": (_a("poecile", "sit_hold", 2.4, 4, "sit"), _a("feebee_soft", "talk", 1.2, 2, "talk"), _a("gargle_soft", "wiggle", 1.2, 2, "play"), _a("hangup_soft", "hop", 1.2, 2, "play"), _a("cache_soft", "nod", 1.2, 2, "sit"), _a("capflash_soft", "pulse", 1.2, 2, "sit"), _a("seedhammer_soft", "lean", 1.2, 2, "play"), _a("freeze", "freeze", 1.4, 2)),
    "robin": (_a("turdus", "sit_hold", 2.4, 4, "sit"), _a("runstop_soft", "hop", 1.2, 2, "play"), _a("listen_soft", "nod", 1.2, 2, "sit"), _a("carol_soft", "talk", 1.2, 2, "talk"), _a("tug_soft", "lean", 1.2, 2, "play"), _a("rufous_soft", "pulse", 1.2, 2, "sit"), _a("tailcock_soft", "wiggle", 1.2, 2, "play"), _a("freeze", "freeze", 1.4, 2)),
    "mallard": (_a("anas", "sit_hold", 2.4, 4, "sit"), _a("dabble_soft", "eat", 1.2, 2, "eat"), _a("upend_soft", "lean", 1.2, 2, "play"), _a("headshake_soft", "wiggle", 1.2, 2, "sit"), _a("gruntwhistle_soft", "talk", 1.2, 2, "talk"), _a("speculum_soft", "pulse", 1.2, 2, "sit"), _a("nodswim_soft", "hop", 1.2, 2, "play"), _a("freeze", "freeze", 1.4, 2)),
    "canada_goose": (_a("branta", "sit_hold", 2.4, 4, "sit"), _a("graze_soft", "eat", 1.2, 2, "eat"), _a("hiss_soft", "pulse", 1.2, 2, "sit"), _a("nestguard_soft", "lean", 1.2, 2, "sit"), _a("honk_soft", "talk", 1.2, 2, "talk"), _a("triumph_soft", "wiggle", 1.2, 2, "play"), _a("chinstrap_soft", "hop", 1.2, 2, "play"), _a("freeze", "freeze", 1.4, 2)),
    "pileated": (_a("dryocopus", "sit_hold", 2.4, 4, "sit"), _a("excavate_soft", "eat", 1.2, 2, "play"), _a("hitch_soft", "hop", 1.2, 2, "play"), _a("crestflare_soft", "pulse", 1.2, 2, "sit"), _a("kuk_soft", "talk", 1.2, 2, "talk"), _a("tongueprobe_soft", "lean", 1.2, 2, "play"), _a("chipcast_soft", "wiggle", 1.2, 2, "play"), _a("freeze", "freeze", 1.4, 2)),
    "hummingbird": (_a("archilochus", "sit_hold", 2.4, 4, "sit"), _a("nectary_soft", "eat", 1.2, 2, "eat"), _a("shuttle_soft", "hop", 1.2, 2, "play"), _a("gorget_soft", "pulse", 1.2, 2, "sit"), _a("chip_soft", "talk", 1.2, 2, "talk"), _a("trapline_soft", "lean", 1.2, 2, "play"), _a("gnatsnap_soft", "wiggle", 1.2, 2, "play"), _a("freeze", "freeze", 1.4, 2)),
    "orb_weaver": (_a("araneus", "sit_hold", 2.4, 4, "sit"), _a("radiate_soft", "walk", 1.2, 2, "play"), _a("stabilimentum_soft", "sit", 1.2, 2, "sit"), _a("swathe_soft", "play", 1.2, 2, "play"), _a("strum_soft", "sit", 1.2, 2, "sit"), _a("dragline_soft", "walk", 1.2, 2, "play"), _a("viscid_soft", "play", 1.2, 2, "play"), _a("freeze", "freeze", 1.4, 2)),
    "jumping_spider": (_a("phidippus", "sit_hold", 2.4, 4, "sit"), _a("orient_soft", "walk", 1.2, 2, "play"), _a("saccade_soft", "sit", 1.2, 2, "sit"), _a("palp_soft", "play", 1.2, 2, "play"), _a("safetyline_soft", "sit", 1.2, 2, "sit"), _a("ame_soft", "walk", 1.2, 2, "play"), _a("scopula_soft", "play", 1.2, 2, "play"), _a("freeze", "freeze", 1.4, 2)),
    "wolf_spider": (_a("tigrosa", "sit_hold", 2.4, 4, "sit"), _a("cursor_soft", "walk", 1.2, 2, "play"), _a("eggsac_soft", "sit", 1.2, 2, "sit"), _a("spiderling_soft", "play", 1.2, 2, "play"), _a("eyeshine_soft", "sit", 1.2, 2, "sit"), _a("spur_soft", "walk", 1.2, 2, "play"), _a("apron_soft", "play", 1.2, 2, "play"), _a("freeze", "freeze", 1.4, 2)),
    "tarantula": (_a("aphonopelma", "sit_hold", 2.4, 4, "sit"), _a("urticate_soft", "walk", 1.2, 2, "play"), _a("threat_soft", "sit", 1.2, 2, "sit"), _a("cork_soft", "play", 1.2, 2, "play"), _a("ecdysis_soft", "sit", 1.2, 2, "sit"), _a("rastellum_soft", "walk", 1.2, 2, "play"), _a("apophysis_soft", "play", 1.2, 2, "play"), _a("freeze", "freeze", 1.4, 2)),
    "widow": (_a("latrodectus", "sit_hold", 2.4, 4, "sit"), _a("hourglass_soft", "sit", 1.2, 2, "sit"), _a("tangle_soft", "talk", 1.2, 2, "talk"), _a("wrap_soft", "play", 1.2, 2, "play"), _a("gumfoot_soft", "play", 1.2, 2, "play"), _a("combfoot_soft", "walk", 1.2, 2, "play"), _a("theridiid_soft", "play", 1.2, 2, "play"), _a("freeze", "freeze", 1.4, 2)),
    "harvestman": (_a("phalangium", "sit_hold", 2.4, 4, "sit"), _a("legwave_soft", "talk", 1.2, 2, "talk"), _a("oscillate_soft", "play", 1.2, 2, "play"), _a("autotomy_soft", "play", 1.2, 2, "play"), _a("gregarious_soft", "sit", 1.2, 2, "sit"), _a("ozopore_soft", "play", 1.2, 2, "play"), _a("leiobunum_soft", "walk", 1.2, 2, "play"), _a("freeze", "freeze", 1.4, 2)),
    "scorpion": (_a("centruroides", "sit_hold", 2.4, 4, "sit"), _a("pedipalp_soft", "talk", 1.2, 2, "talk"), _a("metasoma_soft", "play", 1.2, 2, "play"), _a("fluoresce_soft", "sit", 1.2, 2, "sit"), _a("sanddig_soft", "play", 1.2, 2, "play"), _a("pectines_soft", "talk", 1.2, 2, "talk"), _a("booklung_soft", "play", 1.2, 2, "play"), _a("freeze", "freeze", 1.4, 2)),
    "vinegaroon": (_a("mastigoproctus", "sit_hold", 2.4, 4, "sit"), _a("caudalwhip_soft", "talk", 1.2, 2, "talk"), _a("acetic_soft", "play", 1.2, 2, "play"), _a("palpcrush_soft", "play", 1.2, 2, "play"), _a("trayburrow_soft", "play", 1.2, 2, "play"), _a("pygidial_soft", "talk", 1.2, 2, "talk"), _a("antenniform_soft", "play", 1.2, 2, "play"), _a("freeze", "freeze", 1.4, 2)),
    "tick": (_a("ixodes", "sit_hold", 2.4, 4, "sit"), _a("quest_soft", "talk", 1.2, 2, "talk"), _a("haller_soft", "talk", 1.2, 2, "talk"), _a("hypostome_soft", "play", 1.2, 2, "play"), _a("engorge_soft", "play", 1.2, 2, "play"), _a("scutum_soft", "sit", 1.2, 2, "sit"), _a("capitulum_soft", "play", 1.2, 2, "play"), _a("freeze", "freeze", 1.4, 2)),
    "solifuge": (_a("eremobates", "sit_hold", 2.4, 4, "sit"), _a("malleoli_soft", "talk", 1.2, 2, "talk"), _a("suctorial_soft", "talk", 1.2, 2, "talk"), _a("chelicrush_soft", "play", 1.2, 2, "play"), _a("sprintburst_soft", "play", 1.2, 2, "play"), _a("propeltidium_soft", "sit", 1.2, 2, "sit"), _a("tracheate_soft", "play", 1.2, 2, "play"), _a("freeze", "freeze", 1.4, 2)),
    "deer": (_a("odocoileus", "sit_hold", 2.4, 4, "sit"), _a("flagtail_soft", "play", 1.2, 2, "play"), _a("edgebrowse_soft", "talk", 1.2, 2, "talk"), _a("earswivel_soft", "talk", 1.2, 2, "talk"), _a("forestamp_soft", "play", 1.2, 2, "play"), _a("stotbound_soft", "play", 1.2, 2, "play"), _a("snortblow_soft", "talk", 1.2, 2, "talk"), _a("freeze", "freeze", 1.4, 2)),
    "bat": (_a("eptesicus", "sit_hold", 2.4, 4, "sit"), _a("wingwrap_soft", "play", 1.2, 2, "play"), _a("traguscup_soft", "talk", 1.2, 2, "talk"), _a("thumbcrawl_soft", "play", 1.2, 2, "play"), _a("duskhang_soft", "play", 1.2, 2, "play"), _a("echolocate_soft", "talk", 1.2, 2, "talk"), _a("calcar_soft", "play", 1.2, 2, "play"), _a("freeze", "freeze", 1.4, 2)),
    "squirrel": (_a("sciurus", "sit_hold", 2.4, 4, "sit"), _a("nutbury_soft", "play", 1.2, 2, "play"), _a("tailflick_soft", "play", 1.2, 2, "play"), _a("cheekpouch_soft", "talk", 1.2, 2, "talk"), _a("branchleap_soft", "play", 1.2, 2, "play"), _a("barkscramble_soft", "play", 1.2, 2, "play"), _a("scold_soft", "talk", 1.2, 2, "talk"), _a("freeze", "freeze", 1.4, 2)),
    "otter": (_a("lontra", "sit_hold", 2.4, 4, "sit"), _a("bellyglide_soft", "play", 1.2, 2, "play"), _a("corkroll_soft", "play", 1.2, 2, "play"), _a("shellcrunch_soft", "talk", 1.2, 2, "talk"), _a("whiskernudge_soft", "play", 1.2, 2, "play"), _a("denslide_soft", "play", 1.2, 2, "play"), _a("spraint_soft", "talk", 1.2, 2, "talk"), _a("freeze", "freeze", 1.4, 2)),
    "raccoon": (_a("procyon", "sit_hold", 2.4, 4, "sit"), _a("pawdouse_soft", "play", 1.2, 2, "play"), _a("litterdig_soft", "play", 1.2, 2, "play"), _a("rearstand_soft", "talk", 1.2, 2, "talk"), _a("maskpeer_soft", "talk", 1.2, 2, "talk"), _a("dexterous_soft", "play", 1.2, 2, "play"), _a("ringtail_soft", "play", 1.2, 2, "play"), _a("freeze", "freeze", 1.4, 2)),
    "skunk": (_a("mephitis", "sit_hold", 2.4, 4, "sit"), _a("footstomp_soft", "play", 1.2, 2, "play"), _a("duffgrub_soft", "play", 1.2, 2, "play"), _a("handwarn_soft", "talk", 1.2, 2, "talk"), _a("plumeaim_soft", "talk", 1.2, 2, "talk"), _a("scentraise_soft", "play", 1.2, 2, "play"), _a("plantigrade_soft", "play", 1.2, 2, "play"), _a("freeze", "freeze", 1.4, 2)),
    "opossum": (_a("didelphis", "sit_hold", 2.4, 4, "sit"), _a("stillfeign_soft", "play", 1.2, 2, "play"), _a("scrapnose_soft", "play", 1.2, 2, "play"), _a("gapegrin_soft", "talk", 1.2, 2, "talk"), _a("raftergrip_soft", "talk", 1.2, 2, "talk"), _a("pouchcarry_soft", "play", 1.2, 2, "play"), _a("prehensile_soft", "play", 1.2, 2, "play"), _a("freeze", "freeze", 1.4, 2)),
    "beaver": (_a("castor", "sit_hold", 2.4, 4, "sit"), _a("woodfell_soft", "play", 1.2, 2, "play"), _a("paddleclap_soft", "play", 1.2, 2, "play"), _a("lodgehaul_soft", "talk", 1.2, 2, "talk"), _a("mudpack_soft", "talk", 1.2, 2, "talk"), _a("aspen_soft", "play", 1.2, 2, "play"), _a("divehush_soft", "play", 1.2, 2, "play"), _a("freeze", "freeze", 1.4, 2)),
    "capybara": (_a("hydrochoerus", "sit_hold", 2.4, 4, "sit"), _a("mudwallow_soft", "sit", 1.2, 2, "sit"), _a("sedgecrop_soft", "play", 1.2, 2, "play"), _a("alarmwhistle_soft", "talk", 1.2, 2, "talk"), _a("pilelean_soft", "talk", 1.2, 2, "talk"), _a("scentgland_soft", "talk", 1.2, 2, "talk"), _a("socialpile_soft", "play", 1.2, 2, "play"), _a("freeze", "freeze", 1.4, 2)),
    "porcupine": (_a("erethizon", "sit_hold", 2.4, 4, "sit"), _a("toothclack_soft", "talk", 1.2, 2, "talk"), _a("boleclimb_soft", "play", 1.2, 2, "play"), _a("cambiumchew_soft", "play", 1.2, 2, "play"), _a("dorsoflare_soft", "talk", 1.2, 2, "talk"), _a("guardhair_soft", "talk", 1.2, 2, "talk"), _a("pinehush_soft", "play", 1.2, 2, "play"), _a("freeze", "freeze", 1.4, 2)),
    "black_bear": (_a("ursus", "sit_hold", 2.4, 4, "sit"), _a("bipedrise_soft", "talk", 1.2, 2, "talk"), _a("clawscar_soft", "play", 1.2, 2, "play"), _a("berrypluck_soft", "play", 1.2, 2, "play"), _a("denscrape_soft", "talk", 1.2, 2, "talk"), _a("bluffhuff_soft", "talk", 1.2, 2, "talk"), _a("mastforage_soft", "play", 1.2, 2, "play"), _a("freeze", "freeze", 1.4, 2)),
    "gecko": (_a("hemidactylus", "sit_hold", 2.4, 4, "sit"), _a("toepadcling_soft", "sit", 1.2, 2, "sit"), _a("vocalclick_soft", "talk", 1.2, 2, "talk"), _a("lickeye_soft", "play", 1.2, 2, "play"), _a("mothstalk_soft", "talk", 1.2, 2, "talk"), _a("setae_soft", "talk", 1.2, 2, "talk"), _a("lamphush_soft", "play", 1.2, 2, "play"), _a("freeze", "freeze", 1.4, 2)),
    "anole": (_a("anolis", "sit_hold", 2.4, 4, "sit"), _a("dewlapflash_soft", "sit", 1.2, 2, "sit"), _a("pushupshow_soft", "play", 1.2, 2, "play"), _a("hueshift_soft", "talk", 1.2, 2, "talk"), _a("preyinch_soft", "talk", 1.2, 2, "talk"), _a("nuchal_soft", "talk", 1.2, 2, "talk"), _a("vinehush_soft", "play", 1.2, 2, "play"), _a("freeze", "freeze", 1.4, 2)),
    "skink": (_a("plestiodon", "sit_hold", 2.4, 4, "sit"), _a("tailbluff_soft", "sit", 1.2, 2, "sit"), _a("litterdash_soft", "play", 1.2, 2, "play"), _a("tongueflick_soft", "talk", 1.2, 2, "talk"), _a("sunbask_soft", "sit", 1.2, 2, "sit"), _a("bluetail_soft", "talk", 1.2, 2, "talk"), _a("stonehush_soft", "play", 1.2, 2, "play"), _a("freeze", "freeze", 1.4, 2)),
    "chameleon": (_a("calyptratus", "sit_hold", 2.4, 4, "sit"), _a("veilflush_soft", "sit", 1.2, 2, "sit"), _a("turretgaze_soft", "talk", 1.2, 2, "talk"), _a("tongueshot_soft", "play", 1.2, 2, "play"), _a("branchrock_soft", "sit", 1.2, 2, "sit"), _a("casque_soft", "talk", 1.2, 2, "talk"), _a("zygodactyl_soft", "play", 1.2, 2, "play"), _a("freeze", "freeze", 1.4, 2)),
    "horned_lizard": (_a("phrynosoma", "sit_hold", 2.4, 4, "sit"), _a("bloodsquirt_soft", "play", 1.2, 2, "play"), _a("antfeast_soft", "play", 1.2, 2, "play"), _a("freezeflat_soft", "sit", 1.2, 2, "sit"), _a("rainharvest_soft", "talk", 1.2, 2, "talk"), _a("coronal_soft", "talk", 1.2, 2, "talk"), _a("sandhush_soft", "sit", 1.2, 2, "sit"), _a("freeze", "freeze", 1.4, 2)),
    "alligator": (_a("mississippi", "sit_hold", 2.4, 4, "sit"), _a("bellowbank_soft", "talk", 1.2, 2, "talk"), _a("deathcoil_soft", "play", 1.2, 2, "play"), _a("snoutspy_soft", "play", 1.2, 2, "play"), _a("baskgape_soft", "sit", 1.2, 2, "sit"), _a("osteoderm_soft", "sit", 1.2, 2, "sit"), _a("scutehush_soft", "sit", 1.2, 2, "sit"), _a("freeze", "freeze", 1.4, 2)),
    "crocodile": (_a("acutus", "sit_hold", 2.4, 4, "sit"), _a("toothlock_soft", "talk", 1.2, 2, "talk"), _a("highwalk_soft", "play", 1.2, 2, "play"), _a("nestpit_soft", "play", 1.2, 2, "play"), _a("salttear_soft", "sit", 1.2, 2, "sit"), _a("vsnout_soft", "sit", 1.2, 2, "sit"), _a("keelridge_soft", "sit", 1.2, 2, "sit"), _a("freeze", "freeze", 1.4, 2)),
    "snapper": (_a("serpentina", "sit_hold", 2.4, 4, "sit"), _a("ambushgape_soft", "talk", 1.2, 2, "talk"), _a("mudbury_soft", "sit", 1.2, 2, "sit"), _a("necklunge_soft", "play", 1.2, 2, "play"), _a("banksnap_soft", "play", 1.2, 2, "play"), _a("serrated_soft", "sit", 1.2, 2, "sit"), _a("plastron_soft", "sit", 1.2, 2, "sit"), _a("freeze", "freeze", 1.4, 2)),
    "box_turtle": (_a("carolinae", "sit_hold", 2.4, 4, "sit"), _a("hingeshut_soft", "sit", 1.2, 2, "sit"), _a("berryforage_soft", "play", 1.2, 2, "play"), _a("shellsoak_soft", "sit", 1.2, 2, "sit"), _a("nestscrape_soft", "play", 1.2, 2, "play"), _a("dome_soft", "sit", 1.2, 2, "sit"), _a("leafhush_soft", "sit", 1.2, 2, "sit"), _a("freeze", "freeze", 1.4, 2)),
    "tuatara": (_a("punctatus", "sit_hold", 2.4, 4, "sit"), _a("parietalgaze_soft", "talk", 1.2, 2, "talk"), _a("nuchalrise_soft", "play", 1.2, 2, "play"), _a("burrowsit_soft", "sit", 1.2, 2, "sit"), _a("eggseize_soft", "play", 1.2, 2, "play"), _a("acrodont_soft", "sit", 1.2, 2, "sit"), _a("diapsid_soft", "sit", 1.2, 2, "sit"), _a("freeze", "freeze", 1.4, 2)),
    "bass": (_a("salmoides", "sit_hold", 2.4, 4, "sit"), _a("coverstrike_soft", "play", 1.2, 2, "play"), _a("bedfan_soft", "sit", 1.2, 2, "sit"), _a("surboil_soft", "play", 1.2, 2, "play"), _a("latline_soft", "talk", 1.2, 2, "talk"), _a("maxilla_soft", "sit", 1.2, 2, "sit"), _a("weedline_soft", "sit", 1.2, 2, "sit"), _a("freeze", "freeze", 1.4, 2)),
    "brook_trout": (_a("fontinalis", "sit_hold", 2.4, 4, "sit"), _a("driftfeed_soft", "talk", 1.2, 2, "talk"), _a("insectrise_soft", "play", 1.2, 2, "play"), _a("reddscrape_soft", "sit", 1.2, 2, "sit"), _a("vermicflash_soft", "play", 1.2, 2, "play"), _a("adipose_soft", "sit", 1.2, 2, "sit"), _a("coldriffle_soft", "sit", 1.2, 2, "sit"), _a("freeze", "freeze", 1.4, 2)),
    "catfish": (_a("ictalurus", "sit_hold", 2.4, 4, "sit"), _a("barbelprobe_soft", "talk", 1.2, 2, "talk"), _a("cavitynest_soft", "sit", 1.2, 2, "sit"), _a("mudcloud_soft", "play", 1.2, 2, "play"), _a("caudalthrash_soft", "play", 1.2, 2, "play"), _a("channel_soft", "sit", 1.2, 2, "sit"), _a("mudhush_soft", "sit", 1.2, 2, "sit"), _a("freeze", "freeze", 1.4, 2)),
    "bluegill": (_a("macrochirus", "sit_hold", 2.4, 4, "sit"), _a("platehover_soft", "sit", 1.2, 2, "sit"), _a("colonyfan_soft", "sit", 1.2, 2, "sit"), _a("insectpeck_soft", "talk", 1.2, 2, "talk"), _a("gillflare_soft", "play", 1.2, 2, "play"), _a("opercle_soft", "play", 1.2, 2, "play"), _a("earflap_soft", "sit", 1.2, 2, "sit"), _a("freeze", "freeze", 1.4, 2)),
    "perch": (_a("flavescens", "sit_hold", 2.4, 4, "sit"), _a("tigerbar_soft", "sit", 1.2, 2, "sit"), _a("schoolhover_soft", "sit", 1.2, 2, "sit"), _a("duskrise_soft", "talk", 1.2, 2, "talk"), _a("ribbonspawn_soft", "play", 1.2, 2, "play"), _a("spiny_soft", "play", 1.2, 2, "play"), _a("yellowflank_soft", "sit", 1.2, 2, "sit"), _a("freeze", "freeze", 1.4, 2)),
    "pike": (_a("lucius", "sit_hold", 2.4, 4, "sit"), _a("weedambush_soft", "sit", 1.2, 2, "sit"), _a("scurve_soft", "play", 1.2, 2, "play"), _a("toothclamp_soft", "talk", 1.2, 2, "talk"), _a("torpedoglide_soft", "sit", 1.2, 2, "sit"), _a("duckbill_soft", "talk", 1.2, 2, "talk"), _a("lateral_soft", "sit", 1.2, 2, "sit"), _a("freeze", "freeze", 1.4, 2)),
    "walleye": (_a("vitreus", "sit_hold", 2.4, 4, "sit"), _a("tapetumglow_soft", "talk", 1.2, 2, "talk"), _a("duskcruise_soft", "sit", 1.2, 2, "sit"), _a("gravelspawn_soft", "play", 1.2, 2, "play"), _a("softfinhover_soft", "sit", 1.2, 2, "sit"), _a("canine_soft", "talk", 1.2, 2, "talk"), _a("glassy_soft", "sit", 1.2, 2, "sit"), _a("freeze", "freeze", 1.4, 2)),
    "paddlefish": (_a("spathula", "sit_hold", 2.4, 4, "sit"), _a("rostrumscan_soft", "talk", 1.2, 2, "talk"), _a("filterram_soft", "play", 1.2, 2, "play"), _a("rivercruise_soft", "sit", 1.2, 2, "sit"), _a("eggcast_soft", "play", 1.2, 2, "play"), _a("ampullae_soft", "talk", 1.2, 2, "talk"), _a("cartilaginous_soft", "sit", 1.2, 2, "sit"), _a("freeze", "freeze", 1.4, 2)),
    "lamprey": (_a("marinus", "sit_hold", 2.4, 4, "sit"), _a("oralclamp_soft", "talk", 1.2, 2, "talk"), _a("keratinrasp_soft", "play", 1.2, 2, "play"), _a("undulglide_soft", "sit", 1.2, 2, "sit"), _a("stonenest_soft", "play", 1.2, 2, "play"), _a("anadromous_soft", "talk", 1.2, 2, "talk"), _a("sevengill_soft", "sit", 1.2, 2, "sit"), _a("freeze", "freeze", 1.4, 2)),
    "american_eel": (_a("rostrata", "sit_hold", 2.4, 4, "sit"), _a("glasscrawl_soft", "talk", 1.2, 2, "talk"), _a("mucuscoat_soft", "play", 1.2, 2, "play"), _a("nightmigrate_soft", "sit", 1.2, 2, "sit"), _a("gravelhide_soft", "play", 1.2, 2, "play"), _a("sargasso_soft", "talk", 1.2, 2, "talk"), _a("yellowphase_soft", "sit", 1.2, 2, "sit"), _a("freeze", "freeze", 1.4, 2)),
    "house_centipede": (_a("scutigera", "sit_hold", 2.4, 4, "sit"), _a("forcipule_soft", "play", 1.2, 2, "play"), _a("wallrace_soft", "talk", 1.2, 2, "talk"), _a("antennaflick_soft", "play", 1.2, 2, "play"), _a("fleetlegs_soft", "talk", 1.2, 2, "talk"), _a("compound_soft", "talk", 1.2, 2, "talk"), _a("fifteenpair_soft", "sit", 1.2, 2, "sit"), _a("freeze", "freeze", 1.4, 2)),
    "millipede": (_a("narceus", "sit_hold", 2.4, 4, "sit"), _a("coilcurl_soft", "play", 1.2, 2, "play"), _a("detritusgrub_soft", "talk", 1.2, 2, "talk"), _a("slowmarch_soft", "play", 1.2, 2, "play"), _a("moistseek_soft", "talk", 1.2, 2, "talk"), _a("benzoquinone_soft", "talk", 1.2, 2, "talk"), _a("metachronal_soft", "sit", 1.2, 2, "sit"), _a("freeze", "freeze", 1.4, 2)),
    "pillbug": (_a("vulgare", "sit_hold", 2.4, 4, "sit"), _a("conglobate_soft", "play", 1.2, 2, "play"), _a("detritusnip_soft", "talk", 1.2, 2, "talk"), _a("volvation_soft", "play", 1.2, 2, "play"), _a("antennafeel_soft", "talk", 1.2, 2, "talk"), _a("pleopods_soft", "talk", 1.2, 2, "talk"), _a("uropodtap_soft", "sit", 1.2, 2, "sit"), _a("freeze", "freeze", 1.4, 2)),
    "earthworm": (_a("terrestris", "sit_hold", 2.4, 4, "sit"), _a("peristalse_soft", "play", 1.2, 2, "play"), _a("castheap_soft", "talk", 1.2, 2, "talk"), _a("surfacerise_soft", "talk", 1.2, 2, "talk"), _a("soilanchor_soft", "play", 1.2, 2, "play"), _a("clitellum_soft", "talk", 1.2, 2, "talk"), _a("setaebrace_soft", "sit", 1.2, 2, "sit"), _a("freeze", "freeze", 1.4, 2)),
    "velvet_worm": (_a("peripatus", "sit_hold", 2.4, 4, "sit"), _a("slimejet_soft", "play", 1.2, 2, "play"), _a("lobopod_soft", "talk", 1.2, 2, "talk"), _a("antennawhip_soft", "talk", 1.2, 2, "talk"), _a("preyharpoon_soft", "play", 1.2, 2, "play"), _a("oralpapilla_soft", "talk", 1.2, 2, "talk"), _a("onychophore_soft", "sit", 1.2, 2, "sit"), _a("freeze", "freeze", 1.4, 2)),
    "springtail": (_a("orchesella", "sit_hold", 2.4, 4, "sit"), _a("furculaflick_soft", "play", 1.2, 2, "play"), _a("antennawalk_soft", "talk", 1.2, 2, "talk"), _a("moistclingsoil_soft", "sit", 1.2, 2, "sit"), _a("foldtuck_soft", "sit", 1.2, 2, "sit"), _a("collophore_soft", "talk", 1.2, 2, "talk"), _a("denspring_soft", "play", 1.2, 2, "play"), _a("freeze", "freeze", 1.4, 2)),
    "tardigrade": (_a("eutardigrada", "sit_hold", 2.4, 4, "sit"), _a("cryptotun_soft", "play", 1.2, 2, "play"), _a("clawamble_soft", "talk", 1.2, 2, "talk"), _a("mosssip_soft", "sit", 1.2, 2, "sit"), _a("waterbearroll_soft", "sit", 1.2, 2, "sit"), _a("styletpierce_soft", "talk", 1.2, 2, "talk"), _a("anhydro_soft", "play", 1.2, 2, "play"), _a("freeze", "freeze", 1.4, 2)),
    "planarian": (_a("dugesia", "sit_hold", 2.4, 4, "sit"), _a("ciliaryglide_soft", "play", 1.2, 2, "play"), _a("lightflee_soft", "talk", 1.2, 2, "talk"), _a("preywrap_soft", "sit", 1.2, 2, "sit"), _a("regensplit_soft", "sit", 1.2, 2, "sit"), _a("auriclesense_soft", "talk", 1.2, 2, "talk"), _a("pharynxprobe_soft", "play", 1.2, 2, "play"), _a("freeze", "freeze", 1.4, 2)),
    "nematode": (_a("elegans", "sit_hold", 2.4, 4, "sit"), _a("sinusoid_soft", "play", 1.2, 2, "play"), _a("dauerrest_soft", "sit", 1.2, 2, "sit"), _a("pharynxpump_soft", "sit", 1.2, 2, "sit"), _a("thrashturn_soft", "play", 1.2, 2, "play"), _a("omegaturn_soft", "play", 1.2, 2, "play"), _a("vulvaseek_soft", "talk", 1.2, 2, "talk"), _a("freeze", "freeze", 1.4, 2)),
    "amphipod": (_a("gammarus", "sit_hold", 2.4, 4, "sit"), _a("sideswim_soft", "play", 1.2, 2, "play"), _a("gnathopod_soft", "play", 1.2, 2, "play"), _a("detritusclutch_soft", "sit", 1.2, 2, "sit"), _a("pairguard_soft", "sit", 1.2, 2, "sit"), _a("urosome_soft", "play", 1.2, 2, "play"), _a("pleopod_soft", "talk", 1.2, 2, "talk"), _a("freeze", "freeze", 1.4, 2)),
    "fiddler_crab": (_a("pugilator", "sit_hold", 2.4, 4, "sit"), _a("clawwave_soft", "play", 1.2, 2, "play"), _a("burrowdig_soft", "play", 1.2, 2, "play"), _a("sandfeed_soft", "sit", 1.2, 2, "sit"), _a("lateralsidestep_soft", "walk", 1.2, 2), _a("majorclaw_soft", "play", 1.2, 2, "play"), _a("mudball_soft", "talk", 1.2, 2, "talk"), _a("freeze", "freeze", 1.4, 2)),
    "ghost_crab": (_a("ocypodehush", "sit_hold", 2.4, 4, "sit"), _a("sprintdash_soft", "walk", 1.2, 2), _a("stalkeyescan_soft", "talk", 1.2, 2, "talk"), _a("burrowplunge_soft", "sit", 1.2, 2, "sit"), _a("freezecamo_soft", "sit", 1.2, 2, "sit"), _a("nightforage_soft", "play", 1.2, 2, "play"), _a("sandghost_soft", "talk", 1.2, 2, "talk"), _a("freeze", "freeze", 1.4, 2)),
    "limpet": (_a("patellahush", "sit_hold", 2.4, 4, "sit"), _a("clampseal_soft", "sit", 1.2, 2, "sit"), _a("radialgraze_soft", "play", 1.2, 2, "play"), _a("circumhome_soft", "walk", 1.2, 2), _a("shelltilt_soft", "sit", 1.2, 2, "sit"), _a("homescar_soft", "sit", 1.2, 2, "sit"), _a("radulasweep_soft", "talk", 1.2, 2, "talk"), _a("freeze", "freeze", 1.4, 2)),
    "barnacle": (_a("balanushush", "sit_hold", 2.4, 4, "sit"), _a("cirrikick_soft", "play", 1.2, 2, "play"), _a("opershut_soft", "sit", 1.2, 2, "sit"), _a("cementhold_soft", "sit", 1.2, 2, "sit"), _a("tidereopen_soft", "talk", 1.2, 2, "talk"), _a("cirrisweep_soft", "play", 1.2, 2, "play"), _a("plateshut_soft", "sit", 1.2, 2, "sit"), _a("freeze", "freeze", 1.4, 2)),
    "chiton": (_a("chitonhush", "sit_hold", 2.4, 4, "sit"), _a("plateflex_soft", "play", 1.2, 2, "play"), _a("radularasp_soft", "sit", 1.2, 2, "sit"), _a("girdlesettle_soft", "sit", 1.2, 2, "sit"), _a("rockcreep_soft", "walk", 1.2, 2, "walk"), _a("eightvalve_soft", "play", 1.2, 2, "play"), _a("aesthete_soft", "talk", 1.2, 2, "talk"), _a("freeze", "freeze", 1.4, 2)),
    "periwinkle": (_a("littorinahush", "sit_hold", 2.4, 4, "sit"), _a("spiralcrawl_soft", "walk", 1.2, 2, "walk"), _a("filmgraze_soft", "play", 1.2, 2, "play"), _a("opercshut_soft", "sit", 1.2, 2, "sit"), _a("tidehuddle_soft", "sit", 1.2, 2, "sit"), _a("tipup_soft", "play", 1.2, 2, "play"), _a("littorine_soft", "talk", 1.2, 2, "talk"), _a("freeze", "freeze", 1.4, 2)),
    "sand_dollar": (_a("mellitahush", "sit_hold", 2.4, 4, "sit"), _a("lunulesift_soft", "play", 1.2, 2, "play"), _a("dollarright_soft", "play", 1.2, 2, "play"), _a("sandfilmburrow_soft", "sit", 1.2, 2, "sit"), _a("spinefurcreep_soft", "walk", 1.2, 2, "walk"), _a("petaloid_soft", "play", 1.2, 2, "play"), _a("ambulacra_soft", "talk", 1.2, 2, "talk"), _a("freeze", "freeze", 1.4, 2)),
    "sea_urchin": (_a("strongylhush", "sit_hold", 2.4, 4, "sit"), _a("spinewalk_soft", "walk", 1.2, 2, "walk"), _a("lanterngraze_soft", "play", 1.2, 2, "play"), _a("gripcreep_soft", "walk", 1.2, 2, "walk"), _a("spineflare_soft", "play", 1.2, 2, "play"), _a("pedicellaria_soft", "play", 1.2, 2, "play"), _a("aristotle_soft", "talk", 1.2, 2, "talk"), _a("freeze", "freeze", 1.4, 2)),
    "knobbed_whelk": (_a("busyconhush", "sit_hold", 2.4, 4, "sit"), _a("siphonprobe_soft", "play", 1.2, 2, "play"), _a("footplow_soft", "walk", 1.2, 2, "walk"), _a("opercdoor_soft", "sit", 1.2, 2, "sit"), _a("knobbyrock_soft", "play", 1.2, 2, "play"), _a("whelkhaul_soft", "walk", 1.2, 2, "walk"), _a("canalprobe_soft", "talk", 1.2, 2, "talk"), _a("freeze", "freeze", 1.4, 2)),
    "lugworm": (_a("arenicolahush", "sit_hold", 2.4, 4, "sit"), _a("uburrow_soft", "play", 1.2, 2, "play"), _a("sedgulp_soft", "walk", 1.2, 2, "walk"), _a("gillflush_soft", "sit", 1.2, 2, "sit"), _a("heapcast_soft", "play", 1.2, 2, "play"), _a("tailcast_soft", "walk", 1.2, 2, "walk"), _a("headdig_soft", "talk", 1.2, 2, "talk"), _a("freeze", "freeze", 1.4, 2)),
    "field_cricket": (_a("gryllushush", "sit_hold", 2.4, 4, "sit"), _a("stridulate_soft", "talk", 1.2, 2, "talk"), _a("antennasweep_soft", "walk", 1.2, 2, "walk"), _a("hopskip_soft", "play", 1.2, 2, "play"), _a("burrowmouth_soft", "sit", 1.2, 2, "sit"), _a("cerciflick_soft", "walk", 1.2, 2, "walk"), _a("tegmenraise_soft", "talk", 1.2, 2, "talk"), _a("freeze", "freeze", 1.4, 2)),
    "katydid": (_a("tettigonihush", "sit_hold", 2.4, 4, "sit"), _a("leafstill_soft", "talk", 1.2, 2, "talk"), _a("antennatick_soft", "walk", 1.2, 2, "walk"), _a("tegminasong_soft", "play", 1.2, 2, "play"), _a("leafwalk_soft", "sit", 1.2, 2, "sit"), _a("tegminlift_soft", "walk", 1.2, 2, "walk"), _a("greenmimic_soft", "talk", 1.2, 2, "talk"), _a("freeze", "freeze", 1.4, 2)),
    "grasshopper": (_a("caeliferahush", "sit_hold", 2.4, 4, "sit"), _a("hindleap_soft", "talk", 1.2, 2, "talk"), _a("deskbask_soft", "walk", 1.2, 2, "walk"), _a("mandiblegraze_soft", "play", 1.2, 2, "play"), _a("femurrasp_soft", "sit", 1.2, 2, "sit"), _a("tympanal_soft", "walk", 1.2, 2, "walk"), _a("saltatory_soft", "talk", 1.2, 2, "talk"), _a("freeze", "freeze", 1.4, 2)),
    "swallowtail": (_a("papiliohush", "sit_hold", 2.4, 4, "sit"), _a("wingbanner_soft", "talk", 1.2, 2, "talk"), _a("puddlesip_soft", "walk", 1.2, 2, "walk"), _a("flutterhop_soft", "play", 1.2, 2, "play"), _a("tailglidesettle_soft", "sit", 1.2, 2, "sit"), _a("tornusflash_soft", "walk", 1.2, 2, "walk"), _a("tigerband_soft", "talk", 1.2, 2, "talk"), _a("freeze", "freeze", 1.4, 2)),
    "jewelwing": (_a("calopteryxhush", "sit_hold", 2.4, 4, "sit"), _a("jewelflick_soft", "talk", 1.2, 2, "talk"), _a("creekpatrol_soft", "walk", 1.2, 2, "walk"), _a("perchfan_soft", "play", 1.2, 2, "play"), _a("ovipositdip_soft", "sit", 1.2, 2, "sit"), _a("metallicwing_soft", "walk", 1.2, 2, "walk"), _a("damselflick_soft", "talk", 1.2, 2, "talk"), _a("freeze", "freeze", 1.4, 2)),
    "lacewing": (_a("chrysopahush", "sit_hold", 2.4, 4, "sit"), _a("wingtremble_soft", "talk", 1.2, 2, "talk"), _a("aphidstalk_soft", "walk", 1.2, 2, "walk"), _a("eggraise_soft", "play", 1.2, 2, "play"), _a("nightglint_soft", "sit", 1.2, 2, "sit"), _a("pedicel_soft", "walk", 1.2, 2, "walk"), _a("laceveil_soft", "talk", 1.2, 2, "talk"), _a("freeze", "freeze", 1.4, 2)),
    "earwig": (_a("forficulahush", "sit_hold", 2.4, 4, "sit"), _a("cercithreat_soft", "play", 1.2, 2, "play"), _a("fanwing_soft", "talk", 1.2, 2, "talk"), _a("nightscuttle_soft", "walk", 1.2, 2, "walk"), _a("broodguard_soft", "sit", 1.2, 2, "sit"), _a("tegminacurl_soft", "talk", 1.2, 2, "talk"), _a("cerciwhip_soft", "play", 1.2, 2, "play"), _a("freeze", "freeze", 1.4, 2)),
    "acorn_weevil": (_a("curculiohush", "sit_hold", 2.4, 4, "sit"), _a("rostrumdrill_soft", "play", 1.2, 2, "play"), _a("acornroll_soft", "talk", 1.2, 2, "talk"), _a("dropthanatosis_soft", "walk", 1.2, 2, "walk"), _a("snoutwalk_soft", "sit", 1.2, 2, "sit"), _a("elytraclamp_soft", "talk", 1.2, 2, "talk"), _a("cupprobe_soft", "play", 1.2, 2, "play"), _a("freeze", "freeze", 1.4, 2)),
    "click_beetle": (_a("elaterhush", "sit_hold", 2.4, 4, "sit"), _a("clickjack_soft", "play", 1.2, 2, "play"), _a("eyespotflash_soft", "talk", 1.2, 2, "talk"), _a("clickfreeze_soft", "walk", 1.2, 2, "walk"), _a("tickwalk_soft", "sit", 1.2, 2, "sit"), _a("feelertick_soft", "talk", 1.2, 2, "talk"), _a("rightingclick_soft", "play", 1.2, 2, "play"), _a("freeze", "freeze", 1.4, 2)),
    "robber_fly": (_a("asilushush", "sit_hold", 2.4, 4, "sit"), _a("sallyhawk_soft", "play", 1.2, 2, "play"), _a("beardgroom_soft", "talk", 1.2, 2, "talk"), _a("midsnatch_soft", "walk", 1.2, 2, "walk"), _a("stiltsstance_soft", "sit", 1.2, 2, "sit"), _a("mystaxwipe_soft", "talk", 1.2, 2, "talk"), _a("perchsally_soft", "play", 1.2, 2, "play"), _a("freeze", "freeze", 1.4, 2)),
    "sloth": (_a("bradypushush", "sit_hold", 2.4, 4, "sit"), _a("hangsway_soft", "play", 1.2, 2, "play"), _a("reachcrawl_soft", "talk", 1.2, 2, "talk"), _a("algaescratch_soft", "walk", 1.2, 2, "walk"), _a("headturnstare_soft", "sit", 1.2, 2, "sit"), _a("clawhook_soft", "talk", 1.2, 2, "talk"), _a("slowdrip_soft", "play", 1.2, 2, "play"), _a("freeze", "freeze", 1.4, 2)),
    "lemur": (_a("lemurhush", "sit_hold", 2.4, 4, "sit"), _a("bellybask_soft", "play", 1.2, 2, "play"), _a("ringtailcurl_soft", "talk", 1.2, 2, "talk"), _a("hopgallop_soft", "walk", 1.2, 2, "walk"), _a("scentmark_soft", "sit", 1.2, 2, "sit"), _a("stinkfight_soft", "talk", 1.2, 2, "talk"), _a("sunworship_soft", "play", 1.2, 2, "play"), _a("freeze", "freeze", 1.4, 2)),
    "gibbon": (_a("hylobateshush", "sit_hold", 2.4, 4, "sit"), _a("brachiate_soft", "play", 1.2, 2, "play"), _a("whoopduet_soft", "talk", 1.2, 2, "talk"), _a("bipedalstrut_soft", "walk", 1.2, 2, "walk"), _a("hangreach_soft", "sit", 1.2, 2, "sit"), _a("armhook_soft", "talk", 1.2, 2, "talk"), _a("duetbow_soft", "play", 1.2, 2, "play"), _a("freeze", "freeze", 1.4, 2)),
    "kinkajou": (_a("potoshush", "sit_hold", 2.4, 4, "sit"), _a("pretailhang_soft", "play", 1.2, 2, "play"), _a("nectarsip_soft", "talk", 1.2, 2, "talk"), _a("wristrotate_soft", "walk", 1.2, 2, "walk"), _a("nightscamper_soft", "sit", 1.2, 2, "sit"), _a("honeylap_soft", "talk", 1.2, 2, "talk"), _a("tailcoil_soft", "play", 1.2, 2, "play"), _a("freeze", "freeze", 1.4, 2)),
    "colugo": (_a("galeopterushush", "sit_hold", 2.4, 4, "sit"), _a("patagiumglide_soft", "play", 1.2, 2, "play"), _a("clingclimb_soft", "talk", 1.2, 2, "talk"), _a("headdownhang_soft", "walk", 1.2, 2, "walk"), _a("leaffoldsettle_soft", "sit", 1.2, 2, "sit"), _a("membranespread_soft", "talk", 1.2, 2, "talk"), _a("barkclamp_soft", "play", 1.2, 2, "play"), _a("freeze", "freeze", 1.4, 2)),
    "flying_squirrel": (_a("glaucomyshush", "sit_hold", 2.4, 4, "sit"), _a("membranelaunch_soft", "play", 1.2, 2, "play"), _a("softland_soft", "talk", 1.2, 2, "talk"), _a("nestboxhuddle_soft", "walk", 1.2, 2, "walk"), _a("nocturnalscurry_soft", "sit", 1.2, 2, "sit"), _a("flapstretch_soft", "talk", 1.2, 2, "talk"), _a("barksprint_soft", "play", 1.2, 2, "play"), _a("freeze", "freeze", 1.4, 2)),
    "howler": (_a("alouattahush", "sit_hold", 2.4, 4, "sit"), _a("hyoidboom_soft", "play", 1.2, 2, "play"), _a("tailbrace_soft", "talk", 1.2, 2, "talk"), _a("canopylounge_soft", "walk", 1.2, 2, "walk"), _a("leafchew_soft", "sit", 1.2, 2, "sit"), _a("mantelstretch_soft", "talk", 1.2, 2, "talk"), _a("throatpuff_soft", "play", 1.2, 2, "play"), _a("freeze", "freeze", 1.4, 2)),
    "tarsier": (_a("tarsiushush", "sit_hold", 2.4, 4, "sit"), _a("eyeswivel_soft", "talk", 1.2, 2, "talk"), _a("clingleap_soft", "play", 1.2, 2, "play"), _a("insectpounce_soft", "play", 1.2, 2, "play"), _a("stillstare_soft", "sit", 1.2, 2, "sit"), _a("earfan_soft", "talk", 1.2, 2, "talk"), _a("verticalcling_soft", "walk", 1.2, 2, "walk"), _a("freeze", "freeze", 1.4, 2)),
    "potto": (_a("perodicticushush", "sit_hold", 2.4, 4, "sit"), _a("scapularshield_soft", "talk", 1.2, 2, "talk"), _a("crypticcreep_soft", "play", 1.2, 2, "play"), _a("gumscrape_soft", "play", 1.2, 2, "play"), _a("gripclamp_soft", "sit", 1.2, 2, "sit"), _a("neckspine_soft", "talk", 1.2, 2, "talk"), _a("branchfreeze_soft", "walk", 1.2, 2, "walk"), _a("freeze", "freeze", 1.4, 2)),
    "koala": (_a("phascolarctoshush", "sit_hold", 2.4, 4, "sit"), _a("eucchewbrowse_soft", "eat", 1.2, 2, "eat"), _a("forkbranchperch_soft", "sit", 1.2, 2, "sit"), _a("sleepychintuck_soft", "sit", 1.2, 2, "sit"), _a("climbhugtrunk_soft", "walk", 1.2, 2, "walk"), _a("pouchpress_soft", "play", 1.2, 2, "play"), _a("eardroop_soft", "talk", 1.2, 2, "talk"), _a("freeze", "freeze", 1.4, 2)),
    "brain_coral": (_a("diploriahush", "sit_hold", 2.4, 4, "sit"), _a("meandroidridgepulse_soft", "eat", 1.2, 2, "eat"), _a("polyptentaclewave_soft", "sit", 1.2, 2, "sit"), _a("mucussheetsettle_soft", "sit", 1.2, 2, "sit"), _a("dayexpandnightcontract_soft", "walk", 1.2, 2, "walk"), _a("labyrinthfold_soft", "play", 1.2, 2, "play"), _a("zooxflash_soft", "talk", 1.2, 2, "talk"), _a("freeze", "freeze", 1.4, 2)),
    "anemone": (_a("actiniahush", "sit_hold", 2.4, 4, "sit"), _a("oraldiskwreathsway_soft", "eat", 1.2, 2, "eat"), _a("nematocysttuck_soft", "sit", 1.2, 2, "sit"), _a("pedaldiskwalkcreep_soft", "sit", 1.2, 2, "sit"), _a("retractintocolumn_soft", "walk", 1.2, 2, "walk"), _a("tentaclefan_soft", "play", 1.2, 2, "play"), _a("oralflare_soft", "talk", 1.2, 2, "talk"), _a("freeze", "freeze", 1.4, 2)),
    "clownfish": (_a("amphiprionhush", "sit_hold", 2.4, 4, "sit"), _a("wiggledancehostcue_soft", "eat", 1.2, 2, "eat"), _a("darthideinanemone_soft", "sit", 1.2, 2, "sit"), _a("stripeflashturn_soft", "sit", 1.2, 2, "sit"), _a("peckcleanhost_soft", "walk", 1.2, 2, "walk"), _a("hostnestle_soft", "play", 1.2, 2, "play"), _a("orangebarflash_soft", "talk", 1.2, 2, "talk"), _a("freeze", "freeze", 1.4, 2)),
    "parrotfish": (_a("scarushush", "sit_hold", 2.4, 4, "sit"), _a("pectoralhover_soft", "eat", 1.2, 2, "eat"), _a("mucuscocoonnightsettle_soft", "sit", 1.2, 2, "sit"), _a("sandpooppuffcue_soft", "sit", 1.2, 2, "sit"), _a("beakscrapegraze_soft", "walk", 1.2, 2, "walk"), _a("pharyngealmill_soft", "play", 1.2, 2, "play"), _a("greenphaseflash_soft", "talk", 1.2, 2, "talk"), _a("freeze", "freeze", 1.4, 2)),
    "cleaner_shrimp": (_a("lysmatahush", "sit_hold", 2.4, 4, "sit"), _a("antennawaveadvertise_soft", "eat", 1.2, 2, "eat"), _a("dancescrubclientcue_soft", "sit", 1.2, 2, "sit"), _a("rockcreviceretreat_soft", "sit", 1.2, 2, "sit"), _a("bipedalwalktick_soft", "walk", 1.2, 2, "walk"), _a("whitebandflash_soft", "play", 1.2, 2, "play"), _a("clientstation_soft", "talk", 1.2, 2, "talk"), _a("freeze", "freeze", 1.4, 2)),
    "sea_cucumber": (_a("holothuriahush", "sit_hold", 2.4, 4, "sit"), _a("tubefootcrawl_soft", "eat", 1.2, 2, "eat"), _a("depositfeedsift_soft", "sit", 1.2, 2, "sit"), _a("cucumberswellshrink_soft", "sit", 1.2, 2, "sit"), _a("softretractcue_soft", "walk", 1.2, 2, "walk"), _a("teatspike_soft", "play", 1.2, 2, "play"), _a("cloacalbreathe_soft", "talk", 1.2, 2, "talk"), _a("freeze", "freeze", 1.4, 2)),
    "lionfish": (_a("pteroishush", "sit_hold", 2.4, 4, "sit"), _a("pectoralveilfanflare_soft", "eat", 1.2, 2, "eat"), _a("gulpinginhalecue_soft", "sit", 1.2, 2, "sit"), _a("spinewarnraise_soft", "sit", 1.2, 2, "sit"), _a("slowhoverstalk_soft", "walk", 1.2, 2, "walk"), _a("stripebar_soft", "play", 1.2, 2, "play"), _a("venomwarn_soft", "talk", 1.2, 2, "talk"), _a("freeze", "freeze", 1.4, 2)),
    "giant_clam": (_a("tridacnahush", "sit_hold", 2.4, 4, "sit"), _a("mantlecurtainpulse_soft", "eat", 1.2, 2, "eat"), _a("siphonjetpuff_soft", "sit", 1.2, 2, "sit"), _a("shellgapeclosegate_soft", "sit", 1.2, 2, "sit"), _a("zooxanthellaesunbask_soft", "walk", 1.2, 2, "walk"), _a("byssusgrip_soft", "play", 1.2, 2, "play"), _a("mantleedge_soft", "talk", 1.2, 2, "talk"), _a("freeze", "freeze", 1.4, 2)),
    "eagle_ray": (_a("aetobatushush", "sit_hold", 2.4, 4, "sit"), _a("wingsoarflapglide_soft", "eat", 1.2, 2, "eat"), _a("cephaliclobesift_soft", "sit", 1.2, 2, "sit"), _a("sanddigbury_soft", "sit", 1.2, 2, "sit"), _a("leapbreachcue_soft", "walk", 1.2, 2, "walk"), _a("spotflash_soft", "play", 1.2, 2, "play"), _a("wingbank_soft", "talk", 1.2, 2, "talk"), _a("freeze", "freeze", 1.4, 2)),
    "grouper": (_a("epinephelushush", "sit_hold", 2.4, 4, "sit"), _a("cavernambushsettle_soft", "eat", 1.2, 2, "eat"), _a("gulargulpinhale_soft", "sit", 1.2, 2, "sit"), _a("colorpatternflush_soft", "sit", 1.2, 2, "sit"), _a("slowcaudalhover_soft", "walk", 1.2, 2, "walk"), _a("jawsnap_soft", "play", 1.2, 2, "play"), _a("stripeband_soft", "talk", 1.2, 2, "talk"), _a("freeze", "freeze", 1.4, 2)),
    "cyber_dragon": (_a("cyberhush", "sit_hold", 2.4, 4, "sit"), _a("arcsparkcoil_soft", "eat", 1.2, 2, "eat"), _a("circuitridgewalk_soft", "sit", 1.2, 2, "sit"), _a("databreathshimmer_soft", "sit", 1.2, 2, "sit"), _a("perchscanblink_soft", "walk", 1.2, 2, "walk"), _a("gridpulse_soft", "play", 1.2, 2, "play"), _a("packetflick_soft", "talk", 1.2, 2, "talk"), _a("freeze", "freeze", 1.4, 2)),
    "volt_dragon": (_a("volthush", "sit_hold", 2.4, 4, "sit"), _a("coiledgecharge_soft", "eat", 1.2, 2, "eat"), _a("windowwireskim_soft", "sit", 1.2, 2, "sit"), _a("staticfringecrackle_soft", "sit", 1.2, 2, "sit"), _a("sparkhop_soft", "walk", 1.2, 2, "walk"), _a("coilwind_soft", "play", 1.2, 2, "play"), _a("coronaflash_soft", "talk", 1.2, 2, "talk"), _a("freeze", "freeze", 1.4, 2)),
    "trace_dragon": (_a("tracehush", "sit_hold", 2.4, 4, "sit"), _a("outlinetracepathwalk_soft", "eat", 1.2, 2, "eat"), _a("dashedlineflicker_soft", "sit", 1.2, 2, "sit"), _a("cornersnapturn_soft", "sit", 1.2, 2, "sit"), _a("breadcrumbperch_soft", "walk", 1.2, 2, "walk"), _a("pathglow_soft", "play", 1.2, 2, "play"), _a("waypointskip_soft", "talk", 1.2, 2, "talk"), _a("freeze", "freeze", 1.4, 2)),
    "flux_dragon": (_a("fluxhush", "sit_hold", 2.4, 4, "sit"), _a("heatfieldclaimwalk_soft", "eat", 1.2, 2, "eat"), _a("fieldlineshimmer_soft", "sit", 1.2, 2, "sit"), _a("hideheatbloom_soft", "sit", 1.2, 2, "sit"), _a("treatyfieldsettle_soft", "walk", 1.2, 2, "walk"), _a("fieldripple_soft", "play", 1.2, 2, "play"), _a("boundaryglow_soft", "talk", 1.2, 2, "talk"), _a("freeze", "freeze", 1.4, 2)),
    "spark_dragon": (_a("sparkhush", "sit_hold", 2.4, 4, "sit"), _a("crackpointskitter_soft", "eat", 1.2, 2, "eat"), _a("snoutcrackpop_soft", "sit", 1.2, 2, "sit"), _a("clawtipcrackle_soft", "sit", 1.2, 2, "sit"), _a("tailpointperch_soft", "walk", 1.2, 2, "walk"), _a("fissureflash_soft", "play", 1.2, 2, "play"), _a("tipscorch_soft", "talk", 1.2, 2, "talk"), _a("freeze", "freeze", 1.4, 2)),
    "ion_dragon": (_a("ionhush", "sit_hold", 2.4, 4, "sit"), _a("paleionhazecling_soft", "eat", 1.2, 2, "eat"), _a("outlinehazedrift_soft", "sit", 1.2, 2, "sit"), _a("chargehazeclaim_soft", "sit", 1.2, 2, "sit"), _a("mistperchsettle_soft", "walk", 1.2, 2, "walk"), _a("hazeveil_soft", "play", 1.2, 2, "play"), _a("ionbloom_soft", "talk", 1.2, 2, "talk"), _a("freeze", "freeze", 1.4, 2)),
    "gauss_dragon": (_a("gausshush", "sit_hold", 2.4, 4, "sit"), _a("filinglinesbandwalk_soft", "eat", 1.2, 2, "eat"), _a("ironfilingsstand_soft", "sit", 1.2, 2, "sit"), _a("fieldlinealign_soft", "sit", 1.2, 2, "sit"), _a("magneticperchsettle_soft", "walk", 1.2, 2, "walk"), _a("filingsweep_soft", "play", 1.2, 2, "play"), _a("bandclamp_soft", "talk", 1.2, 2, "talk"), _a("freeze", "freeze", 1.4, 2)),
    "relay_dragon": (_a("relayhush", "sit_hold", 2.4, 4, "sit"), _a("contactclick_soft", "eat", 1.2, 2, "eat"), _a("latchseat_soft", "sit", 1.2, 2, "sit"), _a("arcflick_soft", "sit", 1.2, 2, "sit"), _a("coilbuzz_soft", "walk", 1.2, 2, "walk"), _a("poleswitch_soft", "play", 1.2, 2, "play"), _a("armaturetap_soft", "talk", 1.2, 2, "talk"), _a("freeze", "freeze", 1.4, 2)),
    "fuse_dragon": (_a("fusehush", "sit_hold", 2.4, 4, "sit"), _a("railseat_soft", "eat", 1.2, 2, "eat"), _a("holdcurrent_soft", "sit", 1.2, 2, "sit"), _a("blowclear_soft", "sit", 1.2, 2, "sit"), _a("reseatsnap_soft", "walk", 1.2, 2, "walk"), _a("cartridgerattle_soft", "play", 1.2, 2, "play"), _a("bladeflash_soft", "talk", 1.2, 2, "talk"), _a("freeze", "freeze", 1.4, 2)),
    "ground_dragon": (_a("groundhush", "sit_hold", 2.4, 4, "sit"), _a("lugstrap_soft", "eat", 1.2, 2, "eat"), _a("earthseat_soft", "sit", 1.2, 2, "sit"), _a("heaveplate_soft", "sit", 1.2, 2, "sit"), _a("bedsettle_soft", "walk", 1.2, 2, "walk"), _a("soilgrip_soft", "play", 1.2, 2, "play"), _a("plateclamp_soft", "talk", 1.2, 2, "talk"), _a("freeze", "freeze", 1.4, 2)),
}

TONGUE_KEYS = SNAKE_KEYS
SCRATCH_KEYS = ("dog", "cat", "red_panda")


def acts_for(key: str | None) -> tuple[IdleAct, ...]:
    if not key:
        return ()
    return ETHOGRAM.get(key, ())


def pick_act(key: str | None) -> IdleAct | None:
    acts = acts_for(key)
    if not acts:
        return None
    roll = random.random() * sum(a["weight"] for a in acts)
    for act in acts:
        roll -= act["weight"]
        if roll <= 0:
            return act
    return acts[-1]


def next_act_wait(wander: float, nocturnal: bool = False, night: bool = False) -> float:
    wait = 20.0 - max(0.0, min(1.0, wander)) * 12.0
    if wander < 0.18:
        wait += 8.0
    if nocturnal and night:
        wait *= 0.7
    if nocturnal and not night:
        wait *= 1.22
    return max(8.0, wait) * (0.85 + random.random() * 0.35)


def after_settle_wait(wander: float) -> float:
    late = wander < 0.18
    return (6.0 if late else 3.0) + random.random() * (5.0 if late else 4.0)


def tongue_flick(t: float, hold: float) -> float:
    if t < 0 or t > hold:
        return 0.0
    cycle = 0.22
    n = math.floor(t / cycle)
    if n >= 3:
        return 0.0
    u = (t % cycle) / cycle
    return 1.0 - u / 0.55 if u < 0.55 else 0.0


def act_pose(motion: str | None, t: float, hold: float) -> dict[str, float]:
    u = max(0.0, min(1.0, t / hold)) if hold > 0 else 1.0
    pose = {"dx": 0.0, "dy": 0.0, "rot": 0.0, "stretch": 1.0, "squat": 1.0}
    if motion == "scratch":
        pose["dx"] = math.sin(t * 28) * 2.2
        pose["rot"] = math.sin(t * 28) * 3.2
    elif motion == "shake":
        pose["dx"] = math.sin(t * 40) * 3.4
    elif motion == "yawn":
        pose["stretch"] = 1.0 + math.sin(u * math.pi) * 0.08
        pose["squat"] = 2.0 - pose["stretch"]
    elif motion == "groom":
        pose["dy"] = math.sin(t * 10) * 3.0
        pose["stretch"] = 1.0 + math.sin(t * 10) * 0.02
    elif motion == "stretch":
        pose["stretch"] = 1.0 + math.sin(u * math.pi) * 0.1
        pose["squat"] = 1.0 - math.sin(u * math.pi) * 0.05
    elif motion == "wiggle":
        pose["dx"] = math.sin(t * 16) * 2.0
    elif motion == "bob":
        pose["dy"] = math.sin(t * 8) * 4.0
    elif motion == "pulse":
        pose["stretch"] = 1.0 + math.sin(u * math.pi * 2) * 0.05
        pose["squat"] = 2.0 - pose["stretch"]
    elif motion == "gape":
        pose["stretch"] = 1.0 + math.sin(u * math.pi) * 0.07
        pose["squat"] = 2.0 - pose["stretch"]
    elif motion == "gulp":
        pose["dy"] = math.sin(u * math.pi) * 5.0
        pose["stretch"] = 1.0 + math.sin(u * math.pi) * 0.04
    elif motion == "nod":
        pose["dy"] = -math.sin(u * math.pi) * 6.0
        pose["stretch"] = 1.0 - math.sin(u * math.pi) * 0.04
    elif motion == "lean":
        pose["rot"] = math.sin(u * math.pi) * 8.0
        pose["dx"] = math.sin(u * math.pi) * 4.0
    elif motion == "unfurl":
        pose["stretch"] = 0.88 + math.sin(u * math.pi) * 0.16
        pose["squat"] = 2.0 - pose["stretch"]
    elif motion == "snap":
        pose["stretch"] = 1.0 - math.sin(u * math.pi) * 0.12
        pose["squat"] = 2.0 - pose["stretch"]
        pose["dy"] = math.sin(u * math.pi) * 3.0
    elif motion == "open":
        pose["stretch"] = 1.0 + math.sin(u * math.pi) * 0.1
        pose["squat"] = 2.0 - pose["stretch"]
    elif motion == "curl":
        pose["rot"] = math.sin(u * math.pi) * 6.0
        pose["stretch"] = 1.0 - math.sin(u * math.pi) * 0.08
        pose["squat"] = 2.0 - pose["stretch"]
    elif motion == "waggle":
        pose["dx"] = math.sin(t * 22) * 3.2
        pose["rot"] = math.sin(t * 22) * 10.0
    elif motion == "flash":
        pose["stretch"] = 1.0 + math.sin(u * math.pi * 2) * 0.07
        pose["squat"] = 2.0 - pose["stretch"]
        pose["dy"] = -math.sin(u * math.pi) * 5.0
    elif motion == "fold":
        pose["stretch"] = 1.0 - math.sin(u * math.pi) * 0.06
        pose["squat"] = 2.0 - pose["stretch"]
        pose["dy"] = math.sin(u * math.pi) * 2.0
    elif motion == "trail":
        pose["dx"] = math.sin(t * 14) * 2.4
        pose["dy"] = math.sin(t * 28) * 1.2
    elif motion == "emerge":
        pose["stretch"] = 0.9 + math.sin(u * math.pi) * 0.18
        pose["squat"] = 2.0 - pose["stretch"]
        pose["dy"] = -math.sin(u * math.pi) * 4.0
    elif motion == "puff":
        pose["stretch"] = 1.0 + math.sin(u * math.pi) * 0.14
        pose["squat"] = 2.0 - pose["stretch"]
        pose["dy"] = -math.sin(u * math.pi) * 6.0
    elif motion == "flush":
        pose["stretch"] = 1.0 + math.sin(u * math.pi * 2) * 0.06
        pose["squat"] = 2.0 - pose["stretch"]
        pose["rot"] = math.sin(u * math.pi) * 3.0
    elif motion == "rise":
        pose["dy"] = -math.sin(u * math.pi) * 8.0
        pose["stretch"] = 1.0 + math.sin(u * math.pi) * 0.08
        pose["squat"] = 2.0 - pose["stretch"]
    elif motion == "share":
        pose["dx"] = math.sin(u * math.pi) * 1.2
        pose["rot"] = math.sin(u * math.pi) * 2.0
    elif motion == "drink":
        pose["dy"] = -math.sin(u * math.pi) * 6.0
        pose["stretch"] = 1.0 + math.sin(u * math.pi) * 0.07
        pose["squat"] = 2.0 - pose["stretch"]
    elif motion == "chord":
        pose["stretch"] = 1.0 + math.sin(u * math.pi * 3) * 0.06
        pose["squat"] = 2.0 - pose["stretch"]
        pose["dx"] = math.sin(t * 10) * 1.4
    elif motion == "float":
        pose["dy"] = math.sin(t * 6) * 5.0
        pose["dx"] = math.sin(t * 3) * 2.0
    elif motion == "facet":
        pose["rot"] = math.sin(u * math.pi) * 4.0
        pose["stretch"] = 1.0 + math.sin(u * math.pi) * 0.05
    elif motion == "edge":
        pose["dx"] = math.sin(t * 12) * 3.2
        pose["dy"] = math.sin(t * 24) * 0.8
    elif motion == "ripple":
        pose["stretch"] = 1.0 + math.sin(u * math.pi * 3) * 0.05
        pose["dx"] = math.sin(u * math.pi * 2) * 2.4
    elif motion == "frost":
        pose["stretch"] = 1.0 - math.sin(u * math.pi) * 0.04
        pose["squat"] = 2.0 - pose["stretch"]
        pose["dy"] = math.sin(u * math.pi) * 2.0
    elif motion == "align":
        pose["stretch"] = 1.0 + math.sin(u * math.pi) * 0.1
        pose["dx"] = math.sin(u * math.pi) * 6.0
    elif motion == "dim":
        pose["dy"] = math.sin(u * math.pi) * 2.0
        pose["rot"] = math.sin(u * math.pi) * 2.0
    elif motion == "wake":
        pose["stretch"] = 0.88 + math.sin(u * math.pi) * 0.2
        pose["squat"] = 2.0 - pose["stretch"]
        pose["dy"] = -math.sin(u * math.pi) * 5.0
    return pose
