"""They leave a gift on the wood. Shed is not the only one.

Port of ``leaveGift`` / ``pickGift`` from ``web/src/lib/pets/care.ts``
and ``GIFT_LINE`` from ``treats.ts``. Same Known sit. Same two hundred ten
lines. Do not invent a new gift.
"""

from __future__ import annotations

import random
import time
from dataclasses import replace

from .life import CareResult, CareState, clamp
from .shed import Coat

GIFT_LINE: dict[str, str] = {
    "red_panda": "A ribbon I was not using. For the desk.",
    "cat": "A moth. Consider it a review.",
    "dog": "A sock. I found it first.",
    "rabbit": "A clover. Four, if you squint.",
    "hamster": "A seed from the official hoard.",
    "guinea_pig": "Hay, arranged. Wheek optional.",
    "turtle": "A stone I have been considering.",
    "goldfish": "A bubble that lasted.",
    "budgie": "A note. It says 'ok'.",
    "fox": "The bug. Filed.",
    "penguin": "A pebble of some standing.",
    "parrot": "A word. Keep it.",
    "ferret": "Your dongle. Improved.",
    "hedgehog": "A leaf I trusted.",
    "chinchilla": "Dust, but the good kind.",
    "axolotl": "Calm, in object form.",
    "toucan": "A berry. Inspected.",
    "iguana": "Sun, compressed.",
    "dragon": "A coin from the smaller hoard.",
    "phoenix": "Ash that still glows.",
    "ball_python": "A shed I was finished with.",
    "corn_snake": "A pencil I was not using.",
    "kingsnake": "A ruler. Straight, as required.",
    "green_tree_python": "A loop of shed. Emerald still.",
    "hognose": "A death scene, unused.",
    "garter": "A moss sample. Official.",
    "boa": "A weight I was not using.",
    "milk_snake": "A stamp. Red, on purpose.",
    "rosy_boa": "A warm pebble from the corner.",
    "carpet_python": "A scrap of map. Accurate.",
    "octopus": "A lid I was finished with.",
    "cuttlefish": "A stripe I was not using.",
    "nautilus": "A chamber of quiet.",
    "moon_jelly": "A pulse that lasted.",
    "sea_star": "A damp I trusted.",
    "hermit_crab": "A lid that did not fit.",
    "horseshoe_crab": "A page from the molt.",
    "seahorse": "A hitch I was not using.",
    "manta": "A barrel, unused.",
    "moray": "A crevice I outgrew.",
    "moss": "A square of green I was finished with.",
    "maidenhair": "A fan I had already opened.",
    "ginkgo": "A gold leaf I was not using.",
    "oak": "An acorn I was finished considering.",
    "water_lily": "A pad I was not using.",
    "orchid": "A moth I was finished being.",
    "saguaro": "A rain I stored twice.",
    "venus_flytrap": "A snap I did not need.",
    "pitcher": "A well I was finished holding.",
    "sundew": "A drop I was finished glittering.",
    "honeybee": "A dance I was not using.",
    "monarch": "An orange I was finished wearing.",
    "luna": "A dusk I was not eating.",
    "firefly": "A flash I was finished saying.",
    "darner": "A hawk I was not using.",
    "stick": "A freeze I was finished holding.",
    "carpenter_ant": "A road I was finished walking.",
    "ladybird": "A count I was finished keeping.",
    "mantis": "A fold I did not need.",
    "cicada": "A year I was finished waiting.",
    "bumblebee": "A thrum I was finished keeping.",
    "carpenter_bee": "A hole I was finished boring.",
    "mason_bee": "A cell I was finished sealing.",
    "leafcutter": "A disc I was finished cutting.",
    "stingless": "A pot I was finished filling.",
    "sweat_bee": "A sheen I was finished wearing.",
    "mining_bee": "A bank I was finished digging.",
    "honey_drone": "A hum I was finished holding.",
    "honey_queen": "A line I was finished writing.",
    "honeycomb": "A cell I was finished holding.",
    "oyster": "A shelf I was finished holding.",
    "fly_agaric": "A warning I was not using.",
    "morel": "A pit I was finished keeping.",
    "chanterelle": "A ridge I was not using.",
    "turkey_tail": "A zone I was finished wearing.",
    "lions_mane": "A tooth I was finished hanging.",
    "puffball": "A cloud I was finished saying.",
    "chicken_of_woods": "A sulfur I was not using.",
    "yeast": "A rise I was finished holding.",
    "lichen": "A share I was finished keeping.",
    "photovore": "A wavelength I was finished drinking.",
    "choir": "A note I was not using.",
    "nimbus": "A cold I was finished floating.",
    "silica": "A facet I was finished shedding.",
    "terminator": "A rim I was not using.",
    "nexus": "A count I was finished keeping.",
    "halovore": "A frost I was finished leaving.",
    "magneton": "A north I was not using.",
    "umbral": "A cool I was finished eating.",
    "cyst": "A wait I was finished holding.",
    "frog": "A hop I was finished keeping.",
    "toad": "A puff I was not using.",
    "newt": "An orange I was finished wearing.",
    "salamander": "A coin I was finished hiding.",
    "caecilian": "A ring I was not using.",
    "crayfish": "A claw I was finished holding.",
    "pond_snail": "A room I was finished growing.",
    "mussel": "A silt I was finished filtering.",
    "leech": "A latch I was finished keeping.",
    "stickleback": "A spine I was not using.",
    "paramecium": "A row I was finished keeping.",
    "amoeba": "A foot I was not using.",
    "euglena": "A red I was finished wearing.",
    "volvox": "A daughter I was finished keeping.",
    "diatom": "A pane I was finished growing.",
    "kelp": "A bladder I was not using.",
    "chlamydomonas": "An oar I was finished spinning.",
    "stentor": "A horn I was finished opening.",
    "coli": "A divide I was finished keeping.",
    "haloarchaea": "A blush I was finished wearing.",
    "crow": "A scrap I was finished hiding.",
    "raven": "A thought I was finished keeping.",
    "barn_owl": "A vole I was finished taking.",
    "red_tail": "A vole I was finished stooping for.",
    "chickadee": "A seed I was finished hiding.",
    "robin": "A worm I was finished pulling.",
    "mallard": "A seed I was finished tipping for.",
    "canada_goose": "A grass I was finished keeping.",
    "pileated": "An ant I was finished drumming for.",
    "hummingbird": "A nectar I was finished sipping.",
    "orb_weaver": "A fly I was finished wrapping.",
    "jumping_spider": "A fly I was finished leaping for.",
    "wolf_spider": "A cricket I was finished carrying past.",
    "tarantula": "A cricket I was finished taking.",
    "widow": "A fly I was finished hanging for.",
    "harvestman": "A mite I was finished walking to.",
    "scorpion": "A cricket I was finished raising for.",
    "vinegaroon": "A cricket I was finished whipping for.",
    "tick": "A sip I was finished waiting for.",
    "solifuge": "A cricket I was finished running to.",
    "deer": "A flag I was finished keeping.",
    "bat": "A hang I was finished holding.",
    "squirrel": "A thought I was finished hiding.",
    "otter": "A slide I was finished keeping.",
    "raccoon": "A rinse I was finished holding.",
    "skunk": "A warning I was not using.",
    "opossum": "A still I was finished keeping.",
    "beaver": "A lodge I was finished holding.",
    "porcupine": "A quill I was finished keeping.",
    "black_bear": "A berry I was finished foraging.",
    "gecko": "A moth I was finished climbing for.",
    "anole": "A cricket I was finished flashing for.",
    "skink": "A cricket I was finished dashing for.",
    "chameleon": "A cricket I was finished aiming for.",
    "horned_lizard": "An ant I was finished crowning for.",
    "alligator": "A fish I was finished sitting for.",
    "crocodile": "A fish I was finished showing for.",
    "snapper": "A fish I was finished snapping for.",
    "box_turtle": "A worm I was finished shutting after.",
    "tuatara": "An insect I was finished keeping still for.",
    "bass": "A minnow I was finished lunging for.",
    "brook_trout": "A fly I was finished rising for.",
    "catfish": "A scrap I was finished whisking for.",
    "bluegill": "An insect I was finished flaring for.",
    "perch": "A minnow I was finished barring for.",
    "pike": "A fish I was finished waiting for.",
    "walleye": "A minnow I was finished hunting dusk for.",
    "paddlefish": "A plankton I was finished filtering.",
    "lamprey": "A stone I was finished clinging to.",
    "american_eel": "A scrap I was finished taking toward the Sargasso.",
    "house_centipede": "A silverfish I was finished hunting.",
    "millipede": "A leaf I was finished walking for.",
    "pillbug": "A leaf I was finished rolling after.",
    "earthworm": "A leaf I was finished casting from.",
    "velvet_worm": "A cricket I was finished jetting for.",
    "springtail": "A flake I was finished hopping for.",
    "tardigrade": "A moss I was finished walking.",
    "planarian": "A worm I was finished splitting after.",
    "nematode": "A flake I was finished thrashing for.",
    "amphipod": "A scrap I was finished taking on my side.",
    "fiddler_crab": "An algae I was finished waving for.",
    "ghost_crab": "A scrap I was finished running for.",
    "limpet": "An algae I was finished clamping for.",
    "barnacle": "A drift I was finished kicking for.",
    "chiton": "An algae I was finished plating for.",
    "periwinkle": "An algae I was finished rasping.",
    "sand_dollar": "A diatom I was finished burying for.",
    "sea_urchin": "A kelp I was finished walking for.",
    "knobbed_whelk": "A clam I was finished hunting.",
    "lugworm": "A silt I was finished heaping from.",
    "field_cricket": "A seed I was finished singing for.",
    "katydid": "A leaf I was finished stilling on.",
    "grasshopper": "A leaf I was finished vaulting for.",
    "swallowtail": "A nectar I was finished banding for.",
    "jewelwing": "A midge I was finished hovering for.",
    "lacewing": "An aphid I was finished lacing after.",
    "earwig": "A scrap I was finished raising for.",
    "acorn_weevil": "An acorn I was finished drilling.",
    "click_beetle": "A scrap I was finished clicking for.",
    "robber_fly": "A prey I was finished hunting.",
    "sloth": "A leaf I was finished hanging for.",
    "lemur": "A fruit I was finished sunning for.",
    "gibbon": "A fruit I was finished swinging for.",
    "kinkajou": "A nectar I was finished wrapping for.",
    "colugo": "A leaf I was finished sailing for.",
    "flying_squirrel": "A nut I was finished gliding for.",
    "howler": "A leaf I was finished howling for.",
    "tarsier": "An insect I was finished looking for.",
    "potto": "A gum I was finished stilling for.",
    "koala": "A gum I was finished chewing.",
    "brain_coral": "A plankton I was finished ridging for.",
    "anemone": "A drift I was finished wreathing for.",
    "clownfish": "A scrap I was finished nestling for.",
    "parrotfish": "An algae I was finished scraping.",
    "cleaner_shrimp": "A scrap I was finished waiting for.",
    "sea_cucumber": "A detritus I was finished crawling for.",
    "lionfish": "A prey I was finished veiling for.",
    "giant_clam": "A light I was finished opening for.",
    "eagle_ray": "A clam I was finished soaring for.",
    "grouper": "A fish I was finished hiding for.",
}


def gift_line(key: str | None = None) -> str:
    if not key:
        return "I left this."
    return GIFT_LINE.get(key, "I left this.")


def now_ms() -> int:
    return int(time.time() * 1000)


def leave_gift(
    state: CareState,
    now: int | None = None,
    *,
    gift_x: float | None = None,
) -> CareState:
    """A Known guest may leave one. Two living gifts is enough."""
    if state.bond < 25 or len(state.gifts) >= 2:
        return state
    stamp = now if now is not None else now_ms()
    x = gift_x if gift_x is not None else 16 + random.random() * 68
    gifts = list(state.gifts)
    gifts.append(Coat(id=stamp, x=x, kind="gift"))
    return replace(state, gifts=gifts)


def pick_gift(state: CareState, gift_id: int, key: str | None = None) -> CareResult:
    """Pick the thing they left. Mood +6, bond +2. Same as the desk."""
    line = gift_line(key)
    next_state = replace(
        state,
        gifts=[gift for gift in state.gifts if gift.id != gift_id],
        mood=clamp(state.mood + 6),
        bond=clamp(state.bond + 2),
        last_line=line,
        anim="sit",
    )
    return CareResult(next_state, line, "sit", "sit")
