"""House clock the living desk already uses.

Port of ``web/src/lib/pets/hours.ts``. Same dawn / day / dusk / night, same
hundred and ninety REST windows, same return lines. Do not invent rest hours or copy.
"""

from __future__ import annotations

import json
import time
from datetime import datetime
from pathlib import Path
from typing import Literal

from .paths import default_user_data_dir

DayPart = Literal["dawn", "day", "dusk", "night"]

# Sleep windows: [startHour, endHour). Overnight if start > end.
REST: dict[str, tuple[int, int]] = {
    "red_panda": (22, 7),
    "cat": (13, 16),
    "dog": (21, 6),
    "rabbit": (22, 6),
    "hamster": (8, 18),
    "guinea_pig": (21, 6),
    "turtle": (20, 7),
    "goldfish": (23, 5),
    "budgie": (19, 6),
    "fox": (9, 17),
    "penguin": (22, 6),
    "parrot": (20, 6),
    "ferret": (10, 17),
    "hedgehog": (8, 18),
    "chinchilla": (21, 7),
    "axolotl": (22, 8),
    "toucan": (19, 6),
    "iguana": (20, 8),
    "dragon": (1, 8),
    "phoenix": (23, 6),
    "ball_python": (8, 17),
    "corn_snake": (9, 18),
    "kingsnake": (21, 6),
    "green_tree_python": (8, 17),
    "hognose": (20, 7),
    "garter": (21, 6),
    "boa": (22, 7),
    "milk_snake": (9, 18),
    "rosy_boa": (21, 7),
    "carpet_python": (8, 17),
    "octopus": (8, 17),
    "cuttlefish": (8, 17),
    "nautilus": (8, 18),
    "moon_jelly": (23, 5),
    "sea_star": (21, 6),
    "hermit_crab": (8, 18),
    "horseshoe_crab": (8, 18),
    "seahorse": (20, 6),
    "manta": (21, 6),
    "moray": (8, 17),
    "moss": (20, 6),
    "maidenhair": (20, 7),
    "ginkgo": (19, 6),
    "oak": (20, 6),
    "water_lily": (20, 6),
    "orchid": (19, 6),
    "saguaro": (8, 17),
    "venus_flytrap": (21, 6),
    "pitcher": (21, 6),
    "sundew": (20, 6),
    "honeybee": (20, 6),
    "monarch": (20, 6),
    "luna": (8, 18),
    "firefly": (8, 18),
    "darner": (21, 6),
    "stick": (21, 6),
    "carpenter_ant": (8, 18),
    "ladybird": (20, 6),
    "mantis": (20, 6),
    "cicada": (21, 6),
    "bumblebee": (20, 6),
    "carpenter_bee": (20, 6),
    "mason_bee": (20, 6),
    "leafcutter": (20, 6),
    "stingless": (20, 6),
    "sweat_bee": (20, 6),
    "mining_bee": (20, 6),
    "honey_drone": (20, 6),
    "honey_queen": (21, 6),
    "honeycomb": (21, 6),
    "oyster": (20, 6),
    "fly_agaric": (21, 6),
    "morel": (20, 7),
    "chanterelle": (20, 6),
    "turkey_tail": (21, 6),
    "lions_mane": (20, 6),
    "puffball": (20, 6),
    "chicken_of_woods": (21, 6),
    "yeast": (23, 5),
    "lichen": (20, 6),
    "photovore": (20, 6),
    "choir": (21, 6),
    "nimbus": (23, 5),
    "silica": (20, 7),
    "terminator": (10, 17),
    "nexus": (21, 6),
    "halovore": (20, 6),
    "magneton": (22, 6),
    "umbral": (8, 18),
    "cyst": (20, 8),
    "frog": (22, 6),
    "toad": (21, 7),
    "newt": (22, 7),
    "salamander": (8, 18),
    "caecilian": (21, 7),
    "crayfish": (22, 6),
    "pond_snail": (23, 6),
    "mussel": (22, 7),
    "leech": (9, 17),
    "stickleback": (21, 6),
    "paramecium": (22, 6),
    "amoeba": (21, 7),
    "euglena": (20, 6),
    "volvox": (20, 6),
    "diatom": (20, 6),
    "kelp": (20, 6),
    "chlamydomonas": (20, 6),
    "stentor": (22, 6),
    "coli": (23, 5),
    "haloarchaea": (20, 6),
    "crow": (19, 6),
    "raven": (19, 6),
    "barn_owl": (8, 18),
    "red_tail": (19, 6),
    "chickadee": (19, 6),
    "robin": (20, 6),
    "mallard": (21, 6),
    "canada_goose": (21, 6),
    "pileated": (19, 6),
    "hummingbird": (19, 6),
    "orb_weaver": (20, 6),
    "jumping_spider": (19, 6),
    "wolf_spider": (8, 18),
    "tarantula": (8, 18),
    "widow": (8, 18),
    "harvestman": (8, 18),
    "scorpion": (8, 18),
    "vinegaroon": (8, 18),
    "tick": (22, 6),
    "solifuge": (8, 18),
    "deer": (10, 16),
    "bat": (8, 18),
    "squirrel": (19, 6),
    "otter": (22, 6),
    "raccoon": (8, 17),
    "skunk": (8, 18),
    "opossum": (8, 18),
    "beaver": (8, 17),
    "porcupine": (8, 18),
    "black_bear": (22, 7),
    "gecko": (7, 19),
    "anole": (20, 6),
    "skink": (20, 6),
    "chameleon": (20, 6),
    "horned_lizard": (20, 6),
    "alligator": (22, 6),
    "crocodile": (22, 6),
    "snapper": (8, 17),
    "box_turtle": (20, 6),
    "tuatara": (8, 18),
    "bass": (21, 6),
    "brook_trout": (20, 6),
    "catfish": (8, 17),
    "bluegill": (20, 6),
    "perch": (20, 6),
    "pike": (21, 6),
    "walleye": (8, 17),
    "paddlefish": (21, 6),
    "lamprey": (8, 18),
    "american_eel": (8, 17),
    "house_centipede": (8, 18),
    "millipede": (8, 18),
    "pillbug": (8, 18),
    "earthworm": (8, 17),
    "velvet_worm": (8, 18),
    "springtail": (22, 6),
    "tardigrade": (22, 7),
    "planarian": (8, 18),
    "nematode": (22, 7),
    "amphipod": (8, 18),
    "fiddler_crab": (8, 18),
    "ghost_crab": (8, 17),
    "limpet": (22, 7),
    "barnacle": (22, 7),
    "chiton": (8, 18),
    "periwinkle": (22, 7),
    "sand_dollar": (8, 18),
    "sea_urchin": (8, 18),
    "knobbed_whelk": (8, 18),
    "lugworm": (8, 17),
    "field_cricket": (8, 17),
    "katydid": (8, 17),
    "grasshopper": (22, 7),
    "swallowtail": (22, 7),
    "jewelwing": (22, 7),
    "lacewing": (8, 17),
    "earwig": (8, 17),
    "acorn_weevil": (22, 7),
    "click_beetle": (8, 17),
    "robber_fly": (22, 7),
}

FALLBACK_REST: tuple[int, int] = (22, 7)
SEEN_NAME = "seen.json"
CHECK_HOUR = 14

HIDE_LINE: dict[str, str] = {
    "red_panda": "I went where the ribbon goes.",
    "cat": "The ledge is closed.",
    "dog": "I will be under the desk. Call if you walk.",
    "rabbit": "Under the chair. Thump if you need me.",
    "hamster": "The pouch is a room.",
    "guinea_pig": "Hay-side. Quiet.",
    "turtle": "I am still here. You will not notice.",
    "goldfish": "Behind the glass. Loop later.",
    "budgie": "Cage-corner. Soft.",
    "fox": "The left pocket. Obviously.",
    "penguin": "A small bow, then away.",
    "parrot": "I left a note. It says 'brb'.",
    "ferret": "I took the dongle with me.",
    "hedgehog": "A polite curl, offstage.",
    "chinchilla": "Dust-side.",
    "axolotl": "I receded. Calmly.",
    "toucan": "The perch is vacant. Briefly.",
    "iguana": "I am a stone now.",
    "dragon": "The hoard is attended. From elsewhere.",
    "phoenix": "Ash-side. I will be back.",
    "ball_python": "I went inside the bun.",
    "corn_snake": "I took the pencil canyon.",
    "kingsnake": "The drawer is closed. By me.",
    "green_tree_python": "Above you. Still green.",
    "hognose": "I died backstage.",
    "garter": "Mid-route. Do not wait.",
    "boa": "Under the river of blotter.",
    "milk_snake": "Behind a rumor.",
    "rosy_boa": "The corner kept me.",
    "carpet_python": "Off the legend. Still on the shelf.",
    "octopus": "I went inside the cup.",
    "cuttlefish": "Behind a flush.",
    "nautilus": "In the older room.",
    "moon_jelly": "A lower drift.",
    "sea_star": "I am still here. You will not notice.",
    "hermit_crab": "The lid is closed. By me.",
    "horseshoe_crab": "Under the tray.",
    "seahorse": "Hitched. Do not jostle.",
    "manta": "Above the bowl. Still a kite.",
    "moray": "Inside the jamb.",
    "moss": "Under the felt.",
    "maidenhair": "Inside the coil.",
    "ginkgo": "Behind a gold.",
    "oak": "Inside the dish.",
    "water_lily": "Under the pad.",
    "orchid": "Behind a closed moth.",
    "saguaro": "Inside the store.",
    "venus_flytrap": "Inside the cup.",
    "pitcher": "Inside the well.",
    "sundew": "Behind a glitter.",
    "honeybee": "Inside the comb.",
    "monarch": "Inside the cup.",
    "luna": "Behind a dusk.",
    "firefly": "Behind a flash.",
    "darner": "Above the lamp.",
    "stick": "Among the pencils.",
    "carpenter_ant": "Inside the grain.",
    "ladybird": "Under a leaf.",
    "mantis": "Behind a fold.",
    "cicada": "Under the stone.",
    "bumblebee": "Inside the cup.",
    "carpenter_bee": "Inside the gallery.",
    "mason_bee": "Inside a cell.",
    "leafcutter": "Inside the tube.",
    "stingless": "Inside a pot.",
    "sweat_bee": "Behind the rim.",
    "mining_bee": "Inside the bank.",
    "honey_drone": "Inside the dish.",
    "honey_queen": "On the heart.",
    "honeycomb": "Inside a cell.",
    "oyster": "Inside the shelf.",
    "fly_agaric": "Inside the cup.",
    "morel": "Inside a pit.",
    "chanterelle": "Behind a ridge.",
    "turkey_tail": "Under a zone.",
    "lions_mane": "Inside the beard.",
    "puffball": "Inside the pearl.",
    "chicken_of_woods": "Inside the oak.",
    "yeast": "Inside the crock.",
    "lichen": "On the stone.",
    "photovore": "Inside the glass.",
    "choir": "Inside a note.",
    "nimbus": "Inside the bowl.",
    "silica": "Inside a facet.",
    "terminator": "On the rim.",
    "nexus": "Inside the count.",
    "halovore": "Inside the frost.",
    "magneton": "On the line.",
    "umbral": "Inside the shadow.",
    "cyst": "Inside the seal.",
    "frog": "Inside the cup.",
    "toad": "Under a leaf.",
    "newt": "Inside the saucer.",
    "salamander": "Under the leaf.",
    "caecilian": "Inside the silt.",
    "crayfish": "Under a pebble.",
    "pond_snail": "On the rim.",
    "mussel": "Inside the dish.",
    "leech": "On the blotter.",
    "stickleback": "Inside the weed.",
    "paramecium": "Inside the drop.",
    "amoeba": "Inside the film.",
    "euglena": "Inside the red.",
    "volvox": "Inside the sphere.",
    "diatom": "Inside the pane.",
    "kelp": "Inside the hold.",
    "chlamydomonas": "Inside the plate.",
    "stentor": "Inside the horn.",
    "coli": "Inside the cup.",
    "haloarchaea": "Inside the pan.",
    "crow": "On the ledge.",
    "raven": "On the rafter.",
    "barn_owl": "Inside the beam.",
    "red_tail": "Above the post.",
    "chickadee": "Inside the cup.",
    "robin": "On the rim.",
    "mallard": "Inside the dish.",
    "canada_goose": "On the green.",
    "pileated": "Inside the post.",
    "hummingbird": "On the cup.",
    "orb_weaver": "On the web.",
    "jumping_spider": "On the edge.",
    "wolf_spider": "Under the litter.",
    "tarantula": "Inside the silk.",
    "widow": "Inside the corner.",
    "harvestman": "On the stem.",
    "scorpion": "Under the bark.",
    "vinegaroon": "Under the sand.",
    "tick": "On the hem.",
    "solifuge": "Inside the dish.",
    "deer": "On the edge.",
    "bat": "Inside the fold.",
    "squirrel": "Inside the dish.",
    "otter": "Inside the dish.",
    "raccoon": "Inside the bowl.",
    "skunk": "Under the duff.",
    "opossum": "On the hem.",
    "beaver": "Inside the lodge.",
    "porcupine": "On the post.",
    "black_bear": "Inside the denside.",
    "gecko": "On the plaster.",
    "anole": "On the post.",
    "skink": "Inside the crack.",
    "chameleon": "On the perch.",
    "horned_lizard": "Under the sand.",
    "alligator": "On the bank.",
    "crocodile": "Inside the dish.",
    "snapper": "Inside the mud.",
    "box_turtle": "Under the leaf.",
    "tuatara": "Inside the burrow.",
    "bass": "Inside the weed.",
    "brook_trout": "Inside the riffle.",
    "catfish": "Inside the mud.",
    "bluegill": "Under the dock.",
    "perch": "Inside the rail.",
    "pike": "Inside the reed.",
    "walleye": "Inside the run.",
    "paddlefish": "Inside the current.",
    "lamprey": "On the stone.",
    "american_eel": "Inside the hole.",
    "house_centipede": "Inside the crack.",
    "millipede": "Under the log.",
    "pillbug": "Under the bark.",
    "earthworm": "Inside the soil.",
    "velvet_worm": "Inside the wood.",
    "springtail": "Inside the duff.",
    "tardigrade": "Inside the moss.",
    "planarian": "Inside the film.",
    "nematode": "Inside the film.",
    "amphipod": "Inside the pool.",
    "fiddler_crab": "Inside the marsh.",
    "ghost_crab": "Inside the burrow.",
    "limpet": "On the rim.",
    "barnacle": "On the stone.",
    "chiton": "On the rock.",
    "periwinkle": "On the face.",
    "sand_dollar": "Under the plate.",
    "sea_urchin": "Inside the pool.",
    "knobbed_whelk": "Inside the wrack.",
    "lugworm": "Inside the sand.",
    "field_cricket": "Inside the grass.",
    "katydid": "On the leaf.",
    "grasshopper": "Inside the grass.",
    "swallowtail": "On the blossom.",
    "jewelwing": "On the stream.",
    "lacewing": "On the leaf.",
    "earwig": "Under the bark.",
    "acorn_weevil": "Inside the acorn.",
    "click_beetle": "Under the bark.",
    "robber_fly": "On the grass.",
}

SNACK_LINE: dict[str, str] = {
    "red_panda": "A small treaty. Bamboo-adjacent.",
    "cat": "I allow this crumb.",
    "dog": "For me? I have prepared a sit.",
    "rabbit": "A green thing. Correct.",
    "hamster": "It fits. Officially.",
    "guinea_pig": "Wheek, but smaller.",
    "turtle": "I will arrive at the crumb in due course.",
    "goldfish": "It drifted. I followed.",
    "budgie": "Seed. The only review that matters.",
    "fox": "I found it first.",
    "penguin": "A pebble of food. Accepted.",
    "parrot": "Crunch. Noted.",
    "ferret": "Mine. Also that other bit.",
    "hedgehog": "A quiet nibble.",
    "chinchilla": "That crumb was a scandal. Now it is gone.",
    "axolotl": "I grew a little more fed.",
    "toucan": "The bill approves.",
    "iguana": "I blinked at it. Then I ate.",
    "dragon": "Tribute. Modest.",
    "phoenix": "Warm. Good.",
    "ball_python": "I will sit on the thought of it.",
    "corn_snake": "Pinkie diplomacy. Accepted.",
    "kingsnake": "Tribute in bands of flavor.",
    "green_tree_python": "Warmth first. Then the treaty.",
    "hognose": "I will eat this after my scene.",
    "garter": "Worm treaty. Signed in three copies.",
    "boa": "Tribute. I will take my time.",
    "milk_snake": "An egg of a treaty.",
    "rosy_boa": "A mouse of manners.",
    "carpet_python": "A morsel for the cartographer.",
    "octopus": "A crab of a treaty.",
    "cuttlefish": "A shrimp of a treaty.",
    "nautilus": "Tribute for the older office.",
    "moon_jelly": "A drift of food. Accepted.",
    "sea_star": "I will finish this this afternoon.",
    "hermit_crab": "Scrap diplomacy. Accepted.",
    "horseshoe_crab": "A worm of a treaty.",
    "seahorse": "A brine of a treaty.",
    "manta": "A filter of a treaty.",
    "moray": "A fish of a treaty.",
    "moss": "Dew of a treaty.",
    "maidenhair": "Mist of a treaty.",
    "ginkgo": "A leaf of a treaty.",
    "oak": "Water of a treaty.",
    "water_lily": "Silt of a treaty.",
    "orchid": "Mist of a treaty.",
    "saguaro": "Rain of a treaty.",
    "venus_flytrap": "A fly of a treaty.",
    "pitcher": "A midge of a treaty.",
    "sundew": "A gnat of a treaty.",
    "honeybee": "Nectar of a treaty.",
    "monarch": "Milkweed of a treaty.",
    "luna": "Nothing of a treaty. I decline the bite.",
    "firefly": "A midge of a treaty.",
    "darner": "A mosquito of a treaty.",
    "stick": "A leaf of a treaty.",
    "carpenter_ant": "Honeydew of a treaty.",
    "ladybird": "An aphid of a treaty.",
    "mantis": "A fly of a treaty.",
    "cicada": "Sap of a treaty.",
    "bumblebee": "Nectar of a treaty.",
    "carpenter_bee": "Nectar of a treaty.",
    "mason_bee": "Pollen of a treaty.",
    "leafcutter": "Pollen of a treaty.",
    "stingless": "Nectar of a treaty.",
    "sweat_bee": "Nectar of a treaty.",
    "mining_bee": "Pollen of a treaty.",
    "honey_drone": "Nectar a worker already carried.",
    "honey_queen": "Jelly of a treaty.",
    "honeycomb": "Nectar of a store. I do not bite.",
    "oyster": "Wood of a treaty.",
    "fly_agaric": "Duff of a treaty.",
    "morel": "Duff of a treaty.",
    "chanterelle": "Duff of a treaty.",
    "turkey_tail": "Wood of a treaty.",
    "lions_mane": "Wood of a treaty.",
    "puffball": "Duff of a treaty.",
    "chicken_of_woods": "Oak of a treaty.",
    "yeast": "Dough of a treaty.",
    "lichen": "Dew of a treaty.",
    "photovore": "Light of a treaty.",
    "choir": "Tone of a treaty.",
    "nimbus": "Gas of a treaty.",
    "silica": "Silica of a treaty.",
    "terminator": "Rim of a treaty.",
    "nexus": "Count of a treaty.",
    "halovore": "Salt of a treaty.",
    "magneton": "North of a treaty.",
    "umbral": "Cool of a treaty.",
    "cyst": "Damp of a treaty.",
    "frog": "Cricket of a treaty.",
    "toad": "Cricket of a treaty.",
    "newt": "Worm of a treaty.",
    "salamander": "Worm of a treaty.",
    "caecilian": "Worm of a treaty.",
    "crayfish": "Scrap of a treaty.",
    "pond_snail": "Algae of a treaty.",
    "mussel": "Silt of a treaty.",
    "leech": "Worm of a treaty.",
    "stickleback": "Flake of a treaty.",
    "paramecium": "Bacteria of a treaty.",
    "amoeba": "Prey of a treaty.",
    "euglena": "Light of a treaty.",
    "volvox": "Light of a treaty.",
    "diatom": "Silica of a treaty.",
    "kelp": "Light of a treaty.",
    "chlamydomonas": "Light of a treaty.",
    "stentor": "Bacteria of a treaty.",
    "coli": "Broth of a treaty.",
    "haloarchaea": "Salt of a treaty.",
    "crow": "Scrap of a treaty.",
    "raven": "Scrap of a treaty.",
    "barn_owl": "Vole of a treaty.",
    "red_tail": "Vole of a treaty.",
    "chickadee": "Seed of a treaty.",
    "robin": "Worm of a treaty.",
    "mallard": "Seed of a treaty.",
    "canada_goose": "Grass of a treaty.",
    "pileated": "Ant of a treaty.",
    "hummingbird": "Nectar of a treaty.",
    "orb_weaver": "Fly of a treaty.",
    "jumping_spider": "Fly of a treaty.",
    "wolf_spider": "Cricket of a treaty.",
    "tarantula": "Cricket of a treaty.",
    "widow": "Fly of a treaty.",
    "harvestman": "Mite of a treaty.",
    "scorpion": "Cricket of a treaty.",
    "vinegaroon": "Cricket of a treaty.",
    "tick": "Sip of a treaty.",
    "solifuge": "Cricket of a treaty.",
    "deer": "Browse of a treaty.",
    "bat": "Beetle of a treaty.",
    "squirrel": "Acorn of a treaty.",
    "otter": "Fish of a treaty.",
    "raccoon": "Scrap of a treaty.",
    "skunk": "Grub of a treaty.",
    "opossum": "Scrap of a treaty.",
    "beaver": "Bark of a treaty.",
    "porcupine": "Bark of a treaty.",
    "black_bear": "Berry of a treaty.",
    "gecko": "Moth of a treaty.",
    "anole": "Cricket of a treaty.",
    "skink": "Cricket of a treaty.",
    "chameleon": "Cricket of a treaty.",
    "horned_lizard": "Ant of a treaty.",
    "alligator": "Fish of a treaty.",
    "crocodile": "Fish of a treaty.",
    "snapper": "Fish of a treaty.",
    "box_turtle": "Worm of a treaty.",
    "tuatara": "Insect of a treaty.",
    "bass": "Minnow of a treaty.",
    "brook_trout": "Fly of a treaty.",
    "catfish": "Scrap of a treaty.",
    "bluegill": "Insect of a treaty.",
    "perch": "Minnow of a treaty.",
    "pike": "Fish of a treaty.",
    "walleye": "Minnow of a treaty.",
    "paddlefish": "Plankton of a treaty.",
    "lamprey": "Stone of a treaty.",
    "american_eel": "Scrap of a treaty.",
    "house_centipede": "Silverfish of a treaty.",
    "millipede": "Leaf of a treaty.",
    "pillbug": "Leaf of a treaty.",
    "earthworm": "Leaf of a treaty.",
    "velvet_worm": "Cricket of a treaty.",
    "springtail": "Flake of a treaty.",
    "tardigrade": "Moss of a treaty.",
    "planarian": "Worm of a treaty.",
    "nematode": "Flake of a treaty.",
    "amphipod": "Scrap of a treaty.",
    "fiddler_crab": "Algae of a treaty.",
    "ghost_crab": "Scrap of a treaty.",
    "limpet": "Algae of a treaty.",
    "barnacle": "Drift of a treaty.",
    "chiton": "Algae of a treaty.",
    "periwinkle": "Algae of a treaty.",
    "sand_dollar": "Diatom of a treaty.",
    "sea_urchin": "Kelp of a treaty.",
    "knobbed_whelk": "Clam of a treaty.",
    "lugworm": "Silt of a treaty.",
    "field_cricket": "Seed of a treaty.",
    "katydid": "Leaf of a treaty.",
    "grasshopper": "Leaf of a treaty.",
    "swallowtail": "Nectar of a treaty.",
    "jewelwing": "Midge of a treaty.",
    "lacewing": "Aphid of a treaty.",
    "earwig": "Scrap of a treaty.",
    "acorn_weevil": "Acorn of a treaty.",
    "click_beetle": "Scrap of a treaty.",
    "robber_fly": "Prey of a treaty.",
}


def civil_hour(now: datetime | None = None) -> int:
    stamp = now or datetime.now()
    return stamp.hour


def is_resting_hour(key: str, hour: int | None = None) -> bool:
    when = civil_hour() if hour is None else hour
    start, end = REST.get(key, FALLBACK_REST)
    if start == end:
        return False
    if start < end:
        return when >= start and when < end
    return when >= start or when < end


def day_part(hour: int | None = None) -> DayPart:
    when = civil_hour() if hour is None else hour
    if when >= 5 and when < 8:
        return "dawn"
    if when >= 8 and when < 17:
        return "day"
    if when >= 17 and when < 21:
        return "dusk"
    return "night"


def day_part_label(part: DayPart) -> str:
    if part == "dawn":
        return "Dawn"
    if part == "dusk":
        return "Dusk"
    if part == "night":
        return "Night"
    return "Day"


def hide_line(key: str, existing: str | None = None) -> str:
    if existing:
        return existing
    return HIDE_LINE.get(key, "I went where the ribbon goes.")


def snack_line(key: str, existing: str | None = None) -> str:
    if existing:
        return existing
    return SNACK_LINE.get(key, "A small treaty.")


def return_line(away_ms: float, hour: int | None = None) -> str | None:
    hours = away_ms / 3_600_000
    if hours < 0.4:
        return None
    when = civil_hour() if hour is None else hour
    if hours >= 20:
        if when >= 5 and when < 11:
            return "You were gone a night. I kept the blotter."
        return "A long absence. I counted the dust."
    if hours >= 6:
        return "Hours. I sat in most of them."
    if hours >= 1:
        return "You were elsewhere. I practiced waiting."
    return "Back. I noticed."


def remember_visit(
    key: str,
    *,
    user_data_dir: Path | str | None = None,
    now_ms: int | None = None,
) -> int:
    """Away-ms since last open for this species. Writes ``seen.json`` in the user-data dir."""
    stamp = now_ms if now_ms is not None else int(time.time() * 1000)
    root = Path(user_data_dir) if user_data_dir is not None else default_user_data_dir()
    path = root / SEEN_NAME
    away = 0
    store: dict[str, object] = {}
    try:
        if path.is_file():
            parsed = json.loads(path.read_text(encoding="utf-8"))
            if isinstance(parsed, dict):
                store = parsed
        last = int(store.get(key) or 0)
        if last > 0:
            away = stamp - last
        store[key] = stamp
        root.mkdir(parents=True, exist_ok=True)
        path.write_text(json.dumps(store), encoding="utf-8")
    except (OSError, json.JSONDecodeError, TypeError, ValueError):
        return away
    return away
