/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CatalogRouteImport } from './routes/catalog'
import { Route as CellarRouteImport } from './routes/cellar'
import { Route as CollectionRouteImport } from './routes/collection'
import { Route as CornerRouteImport } from './routes/corner'
import { Route as FarRouteImport } from './routes/far'
import { Route as GardenRouteImport } from './routes/garden'
import { Route as HatchRouteImport } from './routes/hatch'
import { Route as HiveRouteImport } from './routes/hive'
import { Route as LiveRouteImport } from './routes/live'
import { Route as LogRouteImport } from './routes/log'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MeetRouteImport } from './routes/meet'
import { Route as MindRouteImport } from './routes/mind'
import { Route as NestRouteImport } from './routes/nest'
import { Route as PondRouteImport } from './routes/pond'
import { Route as RoostRouteImport } from './routes/roost'
import { Route as SeaRouteImport } from './routes/sea'
import { Route as SnakesRouteImport } from './routes/snakes'
import { Route as StudyRouteImport } from './routes/study'
import { Route as WellRouteImport } from './routes/well'
import { Route as CreekRouteImport } from './routes/creek'
import { Route as StoneRouteImport } from './routes/stone'
import { Route as WoodRouteImport } from './routes/wood'
import { Route as DemoSlugRouteImport } from './routes/demo.$slug'
import { Route as PetsKeyRouteImport } from './routes/pets.$key'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogRoute = CatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const CellarRoute = CellarRouteImport.update({
  id: '/cellar',
  path: '/cellar',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionRoute = CollectionRouteImport.update({
  id: '/collection',
  path: '/collection',
  getParentRoute: () => rootRouteImport,
} as any)
const CreekRoute = CreekRouteImport.update({
  id: '/creek',
  path: '/creek',
  getParentRoute: () => rootRouteImport,
} as any)
const CornerRoute = CornerRouteImport.update({
  id: '/corner',
  path: '/corner',
  getParentRoute: () => rootRouteImport,
} as any)
const FarRoute = FarRouteImport.update({
  id: '/far',
  path: '/far',
  getParentRoute: () => rootRouteImport,
} as any)
const GardenRoute = GardenRouteImport.update({
  id: '/garden',
  path: '/garden',
  getParentRoute: () => rootRouteImport,
} as any)
const HatchRoute = HatchRouteImport.update({
  id: '/hatch',
  path: '/hatch',
  getParentRoute: () => rootRouteImport,
} as any)
const HiveRoute = HiveRouteImport.update({
  id: '/hive',
  path: '/hive',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveRoute = LiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any)
const LogRoute = LogRouteImport.update({
  id: '/log',
  path: '/log',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MeetRoute = MeetRouteImport.update({
  id: '/meet',
  path: '/meet',
  getParentRoute: () => rootRouteImport,
} as any)
const MindRoute = MindRouteImport.update({
  id: '/mind',
  path: '/mind',
  getParentRoute: () => rootRouteImport,
} as any)
const NestRoute = NestRouteImport.update({
  id: '/nest',
  path: '/nest',
  getParentRoute: () => rootRouteImport,
} as any)
const PondRoute = PondRouteImport.update({
  id: '/pond',
  path: '/pond',
  getParentRoute: () => rootRouteImport,
} as any)
const RoostRoute = RoostRouteImport.update({
  id: '/roost',
  path: '/roost',
  getParentRoute: () => rootRouteImport,
} as any)
const SeaRoute = SeaRouteImport.update({
  id: '/sea',
  path: '/sea',
  getParentRoute: () => rootRouteImport,
} as any)
const SnakesRoute = SnakesRouteImport.update({
  id: '/snakes',
  path: '/snakes',
  getParentRoute: () => rootRouteImport,
} as any)
const StoneRoute = StoneRouteImport.update({
  id: '/stone',
  path: '/stone',
  getParentRoute: () => rootRouteImport,
} as any)
const StudyRoute = StudyRouteImport.update({
  id: '/study',
  path: '/study',
  getParentRoute: () => rootRouteImport,
} as any)
const WellRoute = WellRouteImport.update({
  id: '/well',
  path: '/well',
  getParentRoute: () => rootRouteImport,
} as any)
const WoodRoute = WoodRouteImport.update({
  id: '/wood',
  path: '/wood',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoSlugRoute = DemoSlugRouteImport.update({
  id: '/demo/$slug',
  path: '/demo/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PetsKeyRoute = PetsKeyRouteImport.update({
  id: '/pets/$key',
  path: '/pets/$key',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/catalog': typeof CatalogRoute
  '/cellar': typeof CellarRoute
  '/collection': typeof CollectionRoute
  '/corner': typeof CornerRoute
  '/creek': typeof CreekRoute
  '/far': typeof FarRoute
  '/garden': typeof GardenRoute
  '/hatch': typeof HatchRoute
  '/hive': typeof HiveRoute
  '/live': typeof LiveRoute
  '/log': typeof LogRoute
  '/login': typeof LoginRoute
  '/meet': typeof MeetRoute
  '/mind': typeof MindRoute
  '/nest': typeof NestRoute
  '/pond': typeof PondRoute
  '/roost': typeof RoostRoute
  '/sea': typeof SeaRoute
  '/snakes': typeof SnakesRoute
  '/stone': typeof StoneRoute
  '/study': typeof StudyRoute
  '/well': typeof WellRoute
  '/wood': typeof WoodRoute
  '/demo/$slug': typeof DemoSlugRoute
  '/pets/$key': typeof PetsKeyRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/catalog': typeof CatalogRoute
  '/cellar': typeof CellarRoute
  '/collection': typeof CollectionRoute
  '/corner': typeof CornerRoute
  '/creek': typeof CreekRoute
  '/far': typeof FarRoute
  '/garden': typeof GardenRoute
  '/hatch': typeof HatchRoute
  '/hive': typeof HiveRoute
  '/live': typeof LiveRoute
  '/log': typeof LogRoute
  '/login': typeof LoginRoute
  '/meet': typeof MeetRoute
  '/mind': typeof MindRoute
  '/nest': typeof NestRoute
  '/pond': typeof PondRoute
  '/roost': typeof RoostRoute
  '/sea': typeof SeaRoute
  '/snakes': typeof SnakesRoute
  '/stone': typeof StoneRoute
  '/study': typeof StudyRoute
  '/well': typeof WellRoute
  '/wood': typeof WoodRoute
  '/demo/$slug': typeof DemoSlugRoute
  '/pets/$key': typeof PetsKeyRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/catalog': typeof CatalogRoute
  '/cellar': typeof CellarRoute
  '/collection': typeof CollectionRoute
  '/corner': typeof CornerRoute
  '/creek': typeof CreekRoute
  '/far': typeof FarRoute
  '/garden': typeof GardenRoute
  '/hatch': typeof HatchRoute
  '/hive': typeof HiveRoute
  '/live': typeof LiveRoute
  '/log': typeof LogRoute
  '/login': typeof LoginRoute
  '/meet': typeof MeetRoute
  '/mind': typeof MindRoute
  '/nest': typeof NestRoute
  '/pond': typeof PondRoute
  '/roost': typeof RoostRoute
  '/sea': typeof SeaRoute
  '/snakes': typeof SnakesRoute
  '/stone': typeof StoneRoute
  '/study': typeof StudyRoute
  '/well': typeof WellRoute
  '/wood': typeof WoodRoute
  '/demo/$slug': typeof DemoSlugRoute
  '/pets/$key': typeof PetsKeyRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/catalog'
    | '/cellar'
    | '/collection'
    | '/corner'
    | '/creek'
    | '/far'
    | '/garden'
    | '/hatch'
    | '/hive'
    | '/live'
    | '/log'
    | '/login'
    | '/meet'
    | '/mind'
    | '/nest'
    | '/pond'
    | '/roost'
    | '/sea'
    | '/snakes'
    | '/stone'
    | '/study'
    | '/well'
    | '/wood'
    | '/demo/$slug'
    | '/pets/$key'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/catalog'
    | '/cellar'
    | '/collection'
    | '/corner'
    | '/creek'
    | '/far'
    | '/garden'
    | '/hatch'
    | '/hive'
    | '/live'
    | '/log'
    | '/login'
    | '/meet'
    | '/mind'
    | '/nest'
    | '/pond'
    | '/roost'
    | '/sea'
    | '/snakes'
    | '/stone'
    | '/study'
    | '/well'
    | '/wood'
    | '/demo/$slug'
    | '/pets/$key'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/catalog'
    | '/cellar'
    | '/collection'
    | '/corner'
    | '/creek'
    | '/far'
    | '/garden'
    | '/hatch'
    | '/hive'
    | '/live'
    | '/log'
    | '/login'
    | '/meet'
    | '/mind'
    | '/nest'
    | '/pond'
    | '/roost'
    | '/sea'
    | '/snakes'
    | '/stone'
    | '/study'
    | '/well'
    | '/wood'
    | '/demo/$slug'
    | '/pets/$key'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  CatalogRoute: typeof CatalogRoute
  CellarRoute: typeof CellarRoute
  CollectionRoute: typeof CollectionRoute
  CornerRoute: typeof CornerRoute
  CreekRoute: typeof CreekRoute
  FarRoute: typeof FarRoute
  GardenRoute: typeof GardenRoute
  HatchRoute: typeof HatchRoute
  HiveRoute: typeof HiveRoute
  LiveRoute: typeof LiveRoute
  LogRoute: typeof LogRoute
  LoginRoute: typeof LoginRoute
  MeetRoute: typeof MeetRoute
  MindRoute: typeof MindRoute
  NestRoute: typeof NestRoute
  PondRoute: typeof PondRoute
  RoostRoute: typeof RoostRoute
  SeaRoute: typeof SeaRoute
  SnakesRoute: typeof SnakesRoute
  StoneRoute: typeof StoneRoute
  StudyRoute: typeof StudyRoute
  WellRoute: typeof WellRoute
  WoodRoute: typeof WoodRoute
  DemoSlugRoute: typeof DemoSlugRoute
  PetsKeyRoute: typeof PetsKeyRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog': {
      id: '/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof CatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cellar': {
      id: '/cellar'
      path: '/cellar'
      fullPath: '/cellar'
      preLoaderRoute: typeof CellarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collection': {
      id: '/collection'
      path: '/collection'
      fullPath: '/collection'
      preLoaderRoute: typeof CollectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corner': {
      id: '/corner'
      path: '/corner'
      fullPath: '/corner'
      preLoaderRoute: typeof CornerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creek': {
      id: '/creek'
      path: '/creek'
      fullPath: '/creek'
      preLoaderRoute: typeof CreekRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/far': {
      id: '/far'
      path: '/far'
      fullPath: '/far'
      preLoaderRoute: typeof FarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/garden': {
      id: '/garden'
      path: '/garden'
      fullPath: '/garden'
      preLoaderRoute: typeof GardenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hatch': {
      id: '/hatch'
      path: '/hatch'
      fullPath: '/hatch'
      preLoaderRoute: typeof HatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hive': {
      id: '/hive'
      path: '/hive'
      fullPath: '/hive'
      preLoaderRoute: typeof HiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/log': {
      id: '/log'
      path: '/log'
      fullPath: '/log'
      preLoaderRoute: typeof LogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meet': {
      id: '/meet'
      path: '/meet'
      fullPath: '/meet'
      preLoaderRoute: typeof MeetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mind': {
      id: '/mind'
      path: '/mind'
      fullPath: '/mind'
      preLoaderRoute: typeof MindRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nest': {
      id: '/nest'
      path: '/nest'
      fullPath: '/nest'
      preLoaderRoute: typeof NestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pond': {
      id: '/pond'
      path: '/pond'
      fullPath: '/pond'
      preLoaderRoute: typeof PondRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roost': {
      id: '/roost'
      path: '/roost'
      fullPath: '/roost'
      preLoaderRoute: typeof RoostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sea': {
      id: '/sea'
      path: '/sea'
      fullPath: '/sea'
      preLoaderRoute: typeof SeaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/snakes': {
      id: '/snakes'
      path: '/snakes'
      fullPath: '/snakes'
      preLoaderRoute: typeof SnakesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stone': {
      id: '/stone'
      path: '/stone'
      fullPath: '/stone'
      preLoaderRoute: typeof StoneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/study': {
      id: '/study'
      path: '/study'
      fullPath: '/study'
      preLoaderRoute: typeof StudyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/well': {
      id: '/well'
      path: '/well'
      fullPath: '/well'
      preLoaderRoute: typeof WellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wood': {
      id: '/wood'
      path: '/wood'
      fullPath: '/wood'
      preLoaderRoute: typeof WoodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/$slug': {
      id: '/demo/$slug'
      path: '/demo/$slug'
      fullPath: '/demo/$slug'
      preLoaderRoute: typeof DemoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pets/$key': {
      id: '/pets/$key'
      path: '/pets/$key'
      fullPath: '/pets/$key'
      preLoaderRoute: typeof PetsKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  CatalogRoute: CatalogRoute,
  CellarRoute: CellarRoute,
  CollectionRoute: CollectionRoute,
  CornerRoute: CornerRoute,
  CreekRoute: CreekRoute,
  FarRoute: FarRoute,
  GardenRoute: GardenRoute,
  HatchRoute: HatchRoute,
  HiveRoute: HiveRoute,
  LiveRoute: LiveRoute,
  LogRoute: LogRoute,
  LoginRoute: LoginRoute,
  MeetRoute: MeetRoute,
  MindRoute: MindRoute,
  NestRoute: NestRoute,
  PondRoute: PondRoute,
  RoostRoute: RoostRoute,
  SeaRoute: SeaRoute,
  SnakesRoute: SnakesRoute,
  StoneRoute: StoneRoute,
  StudyRoute: StudyRoute,
  WellRoute: WellRoute,
  WoodRoute: WoodRoute,
  DemoSlugRoute: DemoSlugRoute,
  PetsKeyRoute: PetsKeyRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
